"""H1(iv) -- is B299's (theta,phi) Z3xZ3 the same as Boyle's SO(8)-triality cyclic permutation of h3(O)'s
three off-diagonal octonion blocks, under the standard 27 = (3,3bar,1)+(1,3,3bar)+(3bar,1,3) trinification
decomposition?

Method:
 1. Rebuild E6 root system (72 roots) from the E6_CARTAN (embedded, B299) via Weyl-reflection BFS.
 2. Reproduce B305's height-mod-3 grading: positive roots with height%3==0 give a rank-6 subsystem;
    check it splits into 3 mutually-orthogonal components of 3 roots each = A2 x A2 x A2 (SU(3)^3, the
    trinification subalgebra) -- this is Boyle's / the standard SU(3)_C x SU(3)_L x SU(3)_R.
 3. Build the Weyl group of each A2 factor (each generated by 2 simple reflections -> order 6, S3) and let
    W(A2)xW(A2)xW(A2) (order 216) act on the 27 minuscule weights (from B299's _weights_27). Its orbits
    should be exactly 3 orbits of size 9 -- these ARE the three trinification blocks (3,3bar,1) etc.
    (Boyle's x1,x2,x3.)
 4. Check whether theta / phi (B299, embedded) NORMALIZE the A2^3 subalgebra (map the height%3==0 root
    set to itself) and whether their action CYCLICALLY PERMUTES the 3 blocks found in step 3 -- i.e. for
    each of theta's 9 free size-3 orbits on the 27, do the 3 elements of the orbit lie one-each in the 3
    distinct blocks (Boyle's triality signature), or do orbits stay inside one block / mix non-cyclically?
"""
import sympy as sp
from collections import deque, Counter
import itertools

E6_CARTAN = sp.Matrix([[2, -1, 0, 0, 0, 0], [-1, 2, -1, 0, 0, 0], [0, -1, 2, -1, 0, -1],
                       [0, 0, -1, 2, -1, 0], [0, 0, 0, -1, 2, 0], [0, 0, -1, 0, 0, 2]])
THETA = sp.Matrix([[0, -1, 1, 0, 0, 0], [1, -1, 1, 0, 0, 0], [0, 0, 1, 0, 0, 0],
                   [0, 0, 1, 0, -1, 0], [0, 0, 0, 1, -1, 0], [0, 0, 0, 0, 0, 1]])
PHI = sp.Matrix([[1, 0, 0, 0, 0, -1], [0, 1, 0, 0, 0, -2], [0, 0, 1, 0, 0, -3],
                 [0, 0, 1, -1, 1, -2], [0, 0, 1, -1, 0, -1], [0, 0, 1, 0, 0, -2]])

C = E6_CARTAN

def gen_roots():
    """BFS-generate all roots (as coeff tuples in the simple-root basis) via simple reflections."""
    simple = [tuple(1 if j == i else 0 for j in range(6)) for i in range(6)]
    seen = set(simple)
    q = deque(simple)
    while q:
        r = q.popleft()
        for i in range(6):
            # <r, alpha_i^vee> = sum_j r_j * C[j,i]   (simply-laced, C symmetric)
            pairing = sum(r[j] * C[j, i] for j in range(6))
            s = tuple(r[j] - pairing * (1 if j == i else 0) for j in range(6))
            if s not in seen:
                seen.add(s); q.append(s)
    return list(seen)

roots = gen_roots()
print("total roots:", len(roots))  # E6 has 72

def height(r):
    return sum(r)

pos_roots = [r for r in roots if height(r) > 0]
print("positive roots:", len(pos_roots))  # 36

def form(r1, r2):
    return sum(r1[i] * C[i, j] * r2[j] for i in range(6) for j in range(6))

surv = [r for r in pos_roots if height(r) % 3 == 0]
print("height%3==0 positive roots:", len(surv))

import networkx as nx
G = nx.Graph(); G.add_nodes_from(range(len(surv)))
for i in range(len(surv)):
    for j in range(i + 1, len(surv)):
        if form(surv[i], surv[j]) != 0:
            G.add_edge(i, j)
comps = list(nx.connected_components(G))
comp_sizes = sorted(len(c) for c in comps)
print("A2^3 component sizes:", comp_sizes, "-> SU(3)^3 trinification:", comp_sizes == [3, 3, 3])

# simple roots of each A2 factor: within each component of 3 mutually-non-orthogonal roots (a full A2 has
# 6 roots -> our surv only has POSITIVE roots, 3 per factor = the 3 positive roots of that A2). Take any two
# non-proportional simple generators: the two "smallest" (height-minimal) among the 3 positive roots of each
# component span it (since A2 has 3 positive roots = a1, a2, a1+a2).
factor_positive_roots = [[surv[i] for i in c] for c in comps]
factor_simple = []
for fac in factor_positive_roots:
    fac_sorted = sorted(fac, key=height)
    simple_pair = fac_sorted[:2]   # the two height-minimal roots = the two simple roots of this A2
    assert height(fac_sorted[2]) == height(simple_pair[0]) + height(simple_pair[1])
    factor_simple.append(simple_pair)

print("factor simple-root coeff vectors:")
for k, pair in enumerate(factor_simple):
    print(f"  factor {k}: {pair}")

# --- 27 weights (Dynkin labels) from B299 ---
def weights_27():
    seen = {(1, 0, 0, 0, 0, 0)}
    q = deque(seen)
    while q:
        mu = q.popleft()
        for i in range(6):
            if mu[i] == 1:
                nu = tuple(mu[j] - C[i, j] for j in range(6))
                if nu not in seen:
                    seen.add(nu); q.append(nu)
    return list(seen)

W27 = weights_27()
assert len(W27) == 27

def reflect_weight(mu, alpha_coeffs):
    """Reflect a weight mu (Dynkin labels) in the root with simple-root-basis coeffs alpha_coeffs.
    s_alpha(mu) = mu - <mu, alpha^vee> * alpha_in_weight_space.
    <mu,alpha^vee> for alpha=sum n_j alpha_j (simply-laced, alpha^vee=alpha in suitable normalization):
       <mu, alpha^vee> = sum_j n_j * <mu, alpha_j^vee> = sum_j n_j * mu_j   (mu_j = Dynkin label j)
    alpha expressed IN THE WEIGHT (Dynkin-label) BASIS: alpha_j (simple root j) has Dynkin labels = row j of C.
    So alpha_in_weight_space = sum_j n_j * C[j, :].
    """
    pairing = sum(alpha_coeffs[j] * mu[j] for j in range(6))
    alpha_wt = [sum(alpha_coeffs[j] * C[j, k] for j in range(6)) for k in range(6)]
    return tuple(mu[k] - pairing * alpha_wt[k] for k in range(6))

# sanity: simple reflections s_i on weights should permute W27
for i in range(6):
    e = [1 if j == i else 0 for j in range(6)]
    for mu in W27:
        assert reflect_weight(mu, e) in W27
print("simple reflections preserve the 27-weight set: OK")

# Weyl(A2)^3 orbits on the 27 weights
Wset = set(W27)
def orbit_under_group(mu, gens):
    seen = {mu}; q = deque([mu])
    while q:
        cur = q.popleft()
        for g in gens:
            nxt = reflect_weight(cur, g)
            if nxt not in seen:
                seen.add(nxt); q.append(nxt)
    return seen

all_gens = [pair_elt for pair in factor_simple for pair_elt in pair]  # 6 simple reflections total
seen_all = set(); block_orbits = []
for mu in W27:
    if mu in seen_all: continue
    orb = orbit_under_group(mu, all_gens)
    seen_all.update(orb); block_orbits.append(orb)
print("W(A2^3) orbits on 27:", sorted(len(o) for o in block_orbits))

block_of = {}
for idx, orb in enumerate(block_orbits):
    for mu in orb:
        block_of[mu] = idx

# --- action of theta, phi on Dynkin labels (weight space): g acts by C g C^-1 in root basis; on weight
# labels the SAME matrix conjugation formula from B299 works (it operates on Dynkin-label vectors directly) ---
def action_on_dynkin(M):
    A = C * M * C.inv()
    return sp.Matrix(6, 6, lambda i, j: int(A[i, j]))

def orbits_and_block_pattern(M, name):
    A = action_on_dynkin(M)
    def act(mu):
        return tuple(sum(A[i, j] * mu[j] for j in range(6)) for i in range(6))
    seen = set(); orbits = []
    for mu in W27:
        if mu in seen: continue
        orb = [mu]; cur = act(mu)
        while cur != mu:
            orb.append(cur); cur = act(cur)
        seen.update(orb); orbits.append(orb)
    sizes = Counter(len(o) for o in orbits)
    print(f"{name}: orbit sizes on 27 = {dict(sizes)}")
    # for each orbit, the multiset of block-ids visited
    patterns = Counter()
    for orb in orbits:
        blocks = tuple(sorted(block_of[mu] for mu in orb))
        patterns[blocks] += 1
    print(f"{name}: block-id pattern per orbit -> count: {dict(patterns)}")
    # does theta/phi normalize the A2^3 root subsystem (map surv-derived root set to itself)?
    # check by mapping each factor's simple roots via THETA/PHI acting on ROOT coeffs (not weight labels)
    return orbits, patterns

print()
orbits_t, pat_t = orbits_and_block_pattern(THETA, "theta")
orbits_p, pat_p = orbits_and_block_pattern(PHI, "phi")

# does theta permute the 3 root-system factors? theta acts on ROOTS via M directly (roots live in the
# simple-root-coefficient space, same space Dynkin-label reflections used -- but M acts on ROOT vectors
# by ordinary matrix mult in that basis, per B299's fixed_dims/preserves_E6 usage)
def root_action(M, r):
    return tuple(int(x) for x in (M * sp.Matrix(r)))

rootset = set(roots)
for name, M in [("theta", THETA), ("phi", PHI)]:
    ok = all(root_action(M, r) in rootset for r in roots)
    print(f"{name} preserves full root system:", ok)
    # where do the 3 A2-factor simple roots go?
    for k, pair in enumerate(factor_simple):
        images = [root_action(M, tuple(p)) for p in pair]
        # which factor (by component index in `comps`) do the images land in (if positive) or -image if negative
        def locate(im):
            im_pos = im if height(im) > 0 else tuple(-x for x in im)
            for kk, fac in enumerate(factor_positive_roots):
                if im_pos in [tuple(f) for f in fac]:
                    return kk
            return None
        locs = [locate(im) for im in images]
        print(f"  {name}: factor {k} simple roots -> land in factor(s) {locs}")
