#!/usr/bin/env python3
"""B1630 -- THE TICK'S POINT: the weave at tau = i.  The principle's tick sigma^2 = LR has its axis on the circle
|z + 1/2| = sqrt5/2, which passes through i and not through omega (B1629's lowest geodesic).  B1617 computed the weave at
omega, the owner's tagged postulate, now retired as tested; i, the other distinguished point, was never computed.  This
arc reads the weave at i, as a READING ("given tau = i"), on B1617's and B1618's constructions.  Exact up to floating
point; no data.
 Z0  the tick's axis: the fixed points of LR's Moebius map, the circle they span, and whether i and omega lie on it (exact
     in Q(sqrt5)).
 Z1  the residual group at i on V: generated by the lifts of an automorphism whose H_1 matrix is S = [[0, -1], [1, 0]]
     (fixing i), of the sign iota and of conjugation by a and by b; its order; whether it preserves T.
 Z2  T under it: the commutant's dimension; how S's lift permutes T's three parity lines (characters (a, b) = (-, +),
     (+, -), (-, -)): which line it fixes.
 Z3  the mass terms at i, every automorphy phase: for each tensor (T-bar(x)T, T(x)T, Sym^2 T), the subspace fixed by the
     two inner lifts, split by iota's eigenvalue (+1 or -1, the weight's parity), and in it S's eigenspace at every 48th
     root of unity (any eigenvalue off them is counted and reported); for each eigenvector the spectrum (singular values) classified as three distinct, a pair and a
     single (1 + 2), three equal, or zero; and which parity line carries the single in the 1 + 2 cases.
 Z4  near i: S's eigenvalues on T (the residual charges), as fourth or eighth roots.
Writes weave_at_i.json."""
import json, pathlib, os, importlib.util, itertools
import numpy as np
HERE = pathlib.Path(__file__).resolve().parent
FRONTIER = pathlib.Path(os.environ.get("OA_FRONTIER", HERE.parents[1]))
spec = importlib.util.spec_from_file_location("om", FRONTIER / "B1617_the_weave_at_tau_omega" / "verification" / "weave_at_omega.py")
om = importlib.util.module_from_spec(spec); spec.loader.exec_module(om)
cp, nm = om.cp, om.nm
TB = cp.TB


def classify(sv, tol=1e-7):
    s = np.sort(np.abs(sv)); top = s[-1]
    if top < tol: return "zero", None
    s = s / top
    eq01, eq12 = abs(s[0] - s[1]) < tol, abs(s[1] - s[2]) < tol
    if eq01 and eq12: return "three equal", None
    if eq01 or eq12: return "pair + single", None
    return "three distinct", None


def main():
    out = {}
    L = {"a": "a", "b": "ab"}; R = {"a": "ab", "b": "b"}; Linv = {"a": "a", "b": "Ab"}; Rinv = {"a": "aB", "b": "b"}
    # Z0: the tick's axis, exactly: LR's matrix under the record's convention and its fixed points
    LR = om.compose(L, R); H = om.h1(LR); a, b, c, d = (int(x) for x in H.ravel())
    # fixed points of z -> (a z + b)/(c z + d):  c z^2 + (d - a) z - b = 0
    disc = (d - a) ** 2 + 4 * b * c
    center = (a - d) / (2 * c); radius = np.sqrt(disc) / (2 * abs(c))
    on = lambda z: abs(abs(z - center) - radius) < 1e-12
    omega = complex(-0.5, np.sqrt(3) / 2)
    out["Z0"] = {"LR_H1": H.tolist(), "discriminant": disc, "axis_center": center, "axis_radius_squared": disc / (4 * c * c),
                 "i_on_axis": bool(on(1j)), "omega_on_axis": bool(on(omega)),
                 "i_on_axis_exact": bool((0 - center) ** 2 + 1 == disc / (4 * c * c)),
                 "omega_on_axis_exact": bool((-0.5 - center) ** 2 + 0.75 == disc / (4 * c * c))}
    # Z1: an automorphism with H1 matrix S = [[0,-1],[1,0]]
    gens = {"L": L, "R": R, "l": Linv, "r": Rinv}; target = np.array([[0, -1], [1, 0]]); found = None
    for n in range(1, 6):
        for t in itertools.product(gens, repeat=n):
            f = {"a": "a", "b": "b"}
            for s in t: f = om.compose(f, gens[s])
            if np.array_equal(om.h1(f), target): found = ("".join(t), f); break
        if found: break
    word, S = found
    fixes_i = abs(complex(om.mobius(om.h1(S), 1j)) - 1j) < 1e-12
    iota = {"a": "A", "b": "B"}; inn_a = {"a": "a", "b": "abA"}; inn_b = {"a": "baB", "b": "b"}
    mats = {"S": om.M_of(S), "iota": om.M_of(iota), "inn_a": om.M_of(inn_a), "inn_b": om.M_of(inn_b)}
    Gres = cp.Group([mats["S"], mats["iota"], mats["inn_a"], mats["inn_b"]])
    TS, Ti, Ta, Tb = (cp.restrict(mats[k], TB) for k in ("S", "iota", "inn_a", "inn_b"))
    out["Z1"] = {"S_word": word, "S_images": S, "S_fixes_i": bool(fixes_i), "residual_order_on_V": Gres.n}
    # Z2: T under the residual group; the parity lines and S's permutation of them
    _, P = np.linalg.eig(Ta + 0.3719 * Tb); P, _ = np.linalg.qr(P)
    chars = [(int(round(float(np.real(np.vdot(P[:, i], Ta @ P[:, i]))))), int(round(float(np.real(np.vdot(P[:, i], Tb @ P[:, i])))))) for i in range(3)]
    PS = P.conj().T @ TS @ P
    perm = [int(np.argmax(np.abs(PS[:, i]))) for i in range(3)]
    monomial = all(np.sum(np.abs(PS[:, i]) > 1e-9) == 1 for i in range(3))
    fixed_lines = [chars[i] for i in range(3) if perm[i] == i]
    mats_T = [cp.restrict(M, TB) for M in Gres.els]
    rows = np.vstack([np.kron(np.eye(3), M) - np.kron(M.T, np.eye(3)) for M in mats_T])
    sv = np.linalg.svd(rows, compute_uv=False); comm = int(sum(1 for x in sv if x < 1e-8)) + max(0, 9 - len(sv))
    out["Z2"] = {"line_characters": chars, "S_monomial_on_lines": bool(monomial), "S_line_images": perm,
                 "lines_fixed_by_S": fixed_lines, "T_commutant_dim_under_residual": comm}
    # Z3: the mass terms at i, every phase
    res = {}
    for label in ("Tbar_x_T", "T_x_T", "Sym2_T"):
        if label == "Tbar_x_T":
            act = lambda A: np.kron(A.conj(), A); Bm = np.eye(9, dtype=complex)
        elif label == "T_x_T":
            act = lambda A: np.kron(A, A); Bm = np.eye(9, dtype=complex)
        else:
            Bm = nm.sym_basis(); act = lambda A: Bm.conj().T @ np.kron(A, A) @ Bm
        n = act(Ta).shape[0]
        stack = np.vstack([act(Ta) - np.eye(n), act(Tb) - np.eye(n)])
        _, s, Vh = np.linalg.svd(stack); k = int(sum(1 for x in s if x < 1e-8)) + max(0, n - len(s))
        F = Vh[n - k:].conj().T if k else np.zeros((n, 0))
        cells = []
        if k:
            F, _ = np.linalg.qr(F)
            Ir = F.conj().T @ act(Ti) @ F
            for lam in (1.0, -1.0):
                st = Ir - lam * np.eye(k); _, s2, Vh2 = np.linalg.svd(st)
                dd = int(sum(1 for x in s2 if x < 1e-8)) + max(0, k - len(s2))
                if not dd: cells.append({"iota": lam, "dim": 0}); continue
                E = F @ Vh2[k - dd:].conj().T; E, _ = np.linalg.qr(E)
                Sr = E.conj().T @ act(TS) @ E
                pres = bool(np.allclose(E @ Sr, act(TS) @ E, atol=1e-8))
                ev, Vv = np.linalg.eig(Sr); spec = []; dropped = 0
                for j in range(dd):
                    turn = round(float(np.angle(ev[j]) / (2 * np.pi)) % 1, 6)
                    if abs(turn * 48 - round(turn * 48)) > 1e-5: dropped += 1; continue
                    M3 = (Bm @ (E @ Vv[:, j])).reshape(3, 3)
                    if label == "Tbar_x_T": M3 = P.conj().T @ M3 @ P          # in the parity basis
                    else: M3 = P.T @ M3 @ P
                    svs = np.linalg.svd(M3, compute_uv=False); kind, _ = classify(svs)
                    single = None
                    if kind == "pair + single":
                        dg = np.abs(np.diag(M3))
                        if np.allclose(M3, np.diag(np.diag(M3)), atol=1e-8):
                            vals = np.round(dg / max(dg.max(), 1e-300), 6)
                            for i2 in range(3):
                                if sum(abs(vals[i2] - vals[j2]) < 1e-6 for j2 in range(3)) == 1: single = chars[i2]
                    spec.append({"S_turn": turn, "kind": kind, "normalised": [round(float(x / max(svs)), 6) for x in sorted(svs)], "single_line": single})
                cells.append({"iota": lam, "dim": dd, "S_preserves": pres, "spectra": spec, "eigenvalues_off_48th_roots": dropped,
                              "kinds": sorted({x["kind"] for x in spec})})
        res[label] = {"inner_fixed_dim": k, "cells": cells,
                      "any_three_distinct": any("three distinct" in c.get("kinds", []) for c in cells)}
    out["Z3"] = res
    evS = np.linalg.eigvals(TS)
    out["Z4"] = {"S_eigen_turns_on_T": sorted(round(float(np.angle(e) / (2 * np.pi)) % 1, 6) for e in evS),
                 "S_order_on_T": int(next(k for k in range(1, 49) if np.allclose(np.linalg.matrix_power(TS, k), np.eye(3), atol=1e-9)))}
    json.dump(out, open(HERE / "weave_at_i.json", "w"), indent=1, default=str); print(json.dumps(out, indent=1, default=str))


if __name__ == "__main__":
    main()
