#!/usr/bin/env python3
"""THE LINES THAT SPLIT THE DOUBLETS FROM THE TRIPLETS (B1300): among B1278's 706 464 Standard-Model Wilson lines of Y_9,
which ones project out the colour triplets D, Dbar of the 27s while keeping both Higgs doublets and the three
generations -- the closing's own solution of the doublet-triplet problem that B1283 found at tree level (one light Higgs
pair always comes with one light D pair on the full-spectrum lines)?

An SM-commuting Wilson line W is determined by the characters of Q, u^c, L (B1278); it lives in the torus generated by
Y, beta and gamma, and its HYPERCHARGE component acts differently on D (Y = -1/3) and H_u (Y = 1/2), which share
(beta, gamma) = (0, 4/3): so D and H_u can carry different characters and the triplets can be projected while the
doublets stay.  This script re-runs B1278's Y_9 pipeline (its own functions, imported), captures the arguments of the
K3 search, re-enumerates the SM lines with B1278's construction and records the SURVIVAL PATTERN of every component of
every 27 (h^1 of the family character times the W character), then classifies: full spectrum; doublet-triplet split
(D and Dbar absent in every generation, H_u and H_d present); the Higgs-pair count; what else is projected; the
per-generation patterns.
"""
from __future__ import annotations
import sys, math, collections, pathlib, time
from fractions import Fraction as F
import numpy as np
import sympy as sp

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[2]
sys.path.insert(0, str(ROOT / 'frontier' / 'B1278_the_six_fold_closing' / 'verification'))
import six_fold_closing as SF
from six_fold_closing import C, R, VM, smith_with_transforms

captured = {}
_orig = SF.wilson_search_k3


def _capture(n, gens, m, chars, coords, moduli, h1, chis, wts, lab, sm_roots, rts, ip, wN, wnc):
    captured.update(dict(n=n, gens=gens, m=m, chars=chars, coords=coords, moduli=moduli, h1=h1, chis=chis, wts=wts, lab=lab, sm_roots=sm_roots, rts=rts, ip=ip, wN=wN, wnc=wnc))
    return _orig(n, gens, m, chars, coords, moduli, h1, chis, wts, lab, sm_roots, rts, ip, wN, wnc)


SF.wilson_search_k3 = _capture


def classify(c):
    chars, coords, moduli, h1, chis, wts, lab, sm_roots, rts, ip, wN, wnc = (c[k] for k in ('chars', 'coords', 'moduli', 'h1', 'chis', 'wts', 'lab', 'sm_roots', 'rts', 'ip', 'wN', 'wnc'))
    N = len(chars)
    cidx = {x: i for i, x in enumerate(coords)}
    add = lambda x, y: tuple((p + q) % d for p, q, d in zip(x, y, moduli))
    a2c = {a: x for a, x in zip(chars, coords)}
    chic = [a2c[x] for x in chis]
    zero = tuple([0] * len(moduli))
    key = lambda x: sum(x[k] * int(np.prod(moduli[:k])) for k in range(len(moduli)))
    # h^1 of (chi_g times psi) for each family character g, indexed by the coordinate key of psi
    Hg = [np.zeros(N, dtype=np.int64) for _ in range(3)]
    for a, x in zip(chars, coords):
        for g in range(3):
            Hg[g][key(x)] = h1[chars[cidx[add(chic[g], x)]]]
    G = Hg[0] + Hg[1] + Hg[2]
    K3 = [x for x in coords if G[key(x)] >= 3]
    Rm = sp.Matrix([list(a) for a in sm_roots])
    D, U, V = smith_with_transforms(Rm)
    dprime = [int(D[j, j]) for j in range(min(D.shape))]
    rank = sum(1 for d in dprime if d != 0)
    free = list(range(rank, 6))
    VT = V.T
    coeff = {i: [int(v) for v in (VT * sp.Matrix(list(wts[i])))] for i in range(27)}
    comp = {l: next(i for i in range(27) if lab[i] == l) for l in ('Q', 'u^c', 'd^c', 'L', 'e^c', 'H_u', 'H_d', 'D', 'Dbar', 'S', 'nu^c')}
    Cm = sp.Matrix([[coeff[comp[l]][j] for j in free] for l in ('Q', 'u^c', 'L')])
    det = int(Cm.det()); adj = Cm.adjugate()
    K = len(K3); Kc = np.array(K3, dtype=np.int64); mods = np.array(moduli, dtype=np.int64)
    iQ, iu, iL = np.meshgrid(np.arange(K), np.arange(K), np.arange(K), indexing='ij')
    iQ, iu, iL = iQ.ravel(), iu.ravel(), iL.ravel()
    psi = [Kc[iQ], Kc[iu], Kc[iL]]
    inv = np.array([pow(det % int(d), -1, int(d)) for d in moduli], dtype=np.int64)
    nu = []
    for j in range(3):
        acc = np.zeros_like(psi[0])
        for k in range(3):
            acc = acc + int(adj[j, k]) * psi[k]
        nu.append((acc % mods) * inv % mods)

    def psi_of(coef):
        acc = np.zeros_like(psi[0])
        for j, f in enumerate(free):
            if coef[f]:
                acc = acc + coef[f] * nu[j]
        return acc % mods

    def keys(arr):
        k = np.zeros(arr.shape[0], dtype=np.int64)
        for t in range(len(moduli)):
            k += arr[:, t] * int(np.prod(moduli[:t]))
        return k
    # per-component keys for all lines (27 arrays)
    kk = {i: keys(psi_of(coeff[i])) for i in range(27)}
    # survival per (generation g, component i): Hg[g][key]
    surv = {(g, i): Hg[g][kk[i]] for g in range(3) for i in range(27)}
    tot = {l: sum(surv[(g, comp[l])] for g in range(3)) for l in comp}          # per-label totals over generations
    three = (tot['Q'] >= 3) & (tot['u^c'] >= 3) & (tot['L'] >= 3) & (tot['d^c'] >= 3) & (tot['e^c'] >= 3)
    pQ, pu, pe = kk[comp['Q']], kk[comp['u^c']], kk[comp['e^c']]
    broken = ~((pQ == pu) & (pu == pe))
    vac = (tot['S'] >= 1) & (tot['nu^c'] >= 1) & (tot['H_u'] >= 1) & (tot['H_d'] >= 1)
    sm = three & broken & vac
    n_sm = int(sm.sum())
    full = sm & (sum(surv[(g, i)] for g in range(3) for i in range(27)) == 81)
    split = sm & (tot['D'] == 0) & (tot['Dbar'] == 0)
    partial = sm & ((tot['D'] + tot['Dbar']) > 0) & ((tot['D'] + tot['Dbar']) < 6)
    out = dict(n_sm=n_sm, n_full=int(full.sum()), n_split=int(split.sum()), n_partial=int(partial.sum()))
    # Higgs pair counts and D counts on the SM lines
    hist = collections.Counter()
    for a, b, d1, d2 in zip(tot['H_u'][sm], tot['H_d'][sm], tot['D'][sm], tot['Dbar'][sm]):
        hist[(int(a), int(b), int(d1), int(d2))] += 1
    out['hist_HuHdDDbar'] = dict(sorted(hist.items()))
    hist2 = collections.Counter()
    for a, b in zip(tot['S'][sm], tot['nu^c'][sm]):
        hist2[(int(a), int(b))] += 1
    out['hist_SNu'] = dict(sorted(hist2.items()))
    # per-generation survival patterns of (H_u, H_d, D, Dbar, N, nu^c) on the NON-full SM lines
    nonfull = np.where(sm & ~full)[0]
    gp = collections.Counter()
    for t in nonfull:
        pat = tuple(tuple(int(surv[(g, comp[l])][t]) for l in ('H_u', 'H_d', 'D', 'Dbar', 'S', 'nu^c')) for g in range(3))
        gp[pat] += 1
    out['nonfull_gen_patterns'] = dict(gp.most_common(10))
    out['n_nonfull'] = int(len(nonfull))
    # which labels are ever projected on an SM line
    out['ever_projected'] = {l: int((tot[l][sm] < 3).sum()) for l in comp}
    # the split lines: what else is projected; per-generation patterns
    if out['n_split']:
        idx = np.where(split)[0]
        lab_tot = collections.Counter()
        gen_pat = collections.Counter()
        for t in idx:
            lab_tot[tuple((l, int(tot[l][t])) for l in ('Q', 'u^c', 'd^c', 'L', 'e^c', 'H_u', 'H_d', 'D', 'Dbar', 'S', 'nu^c'))] += 1
            pat = tuple(tuple(int(surv[(g, comp[l])][t]) for l in ('H_u', 'H_d', 'D', 'Dbar', 'S', 'nu^c')) for g in range(3))
            gen_pat[pat] += 1
        out['split_spectra'] = dict(lab_tot)
        out['split_gen_patterns'] = dict(gen_pat.most_common(12))
        # orders of the Wilson line's determining characters on the split lines
        order_of = lambda x: max([d // math.gcd(int(v), d) for v, d in zip(x, moduli)] + [1])
        ords = collections.Counter((order_of(Kc[iQ[t]]), order_of(Kc[iu[t]]), order_of(Kc[iL[t]])) for t in idx[:200000])
        out['split_orders'] = dict(ords.most_common(8))
    # control: the per-label totals of the full-spectrum lines are all 3
    if out['n_full']:
        t0 = np.where(full)[0][0]
        out['full_control'] = all(int(tot[l][t0]) == 3 for l in comp)
    return out


def main():
    t0 = time.time()
    wts, rep = C.load()
    lab, hy, wts2 = R.sm_labels(); assert wts2 == wts
    sub, Y, rts, Mf, ip, a1, a2 = VM.descent_data()
    sm_roots = sorted(set(a2) | {a1, tuple(-x for x in a1)})
    iN = next(i for i in range(27) if lab[i] == 'S'); inc = next(i for i in range(27) if lab[i] == 'nu^c')
    wN, wnc = [F(x) for x in wts[iN]], [F(x) for x in wts[inc]]
    res9 = SF.closing(9, wts, lab, sm_roots, enumerate_w=False, dps=40, extra=(rts, ip, wN, wnc))
    assert captured, "the K3 search did not run"
    print(f"\n=== the survival patterns of the SM lines of Y_9 ({time.time() - t0:.0f} s so far) ===")
    out = classify(captured)
    ks = res9['k3_search']
    print(f"  SM lines re-enumerated: {out['n_sm']} (B1278: {ks['sm_vacua']}); full-spectrum: {out['n_full']} (B1278: {ks['full_spectrum']}); full-line control (every label 3 of 3): {out.get('full_control')}")
    print(f"  (H_u, H_d, D, Dbar totals over the three 27s) -> number of SM lines: {out['hist_HuHdDDbar']}")
    print(f"  DOUBLET-TRIPLET SPLIT LINES (no D, no Dbar in any generation; both Higgs doublets present; three generations; SU(5) broken): {out['n_split']}")
    print(f"  lines with some but not all six triplets projected: {out['n_partial']}")
    print(f"  (N, nu^c totals over the three 27s) -> number of SM lines: {out['hist_SNu']}")
    print(f"  labels ever projected (total < 3) on an SM line -> number of lines: {out['ever_projected']}")
    print(f"  non-full SM lines: {out['n_nonfull']}; per-generation survival of (H_u, H_d, D, Dbar, N, nu^c), most common patterns: {out['nonfull_gen_patterns']}")
    if out['n_split']:
        print(f"  the split lines' spectra (label -> total over the three 27s): {out['split_spectra']}")
        print(f"  per-generation survival of (H_u, H_d, D, Dbar, N, nu^c) on the split lines (most common patterns): {out['split_gen_patterns']}")
        print(f"  orders of (psi_Q, psi_u, psi_L) on the split lines: {out['split_orders']}")
    ok = out['n_sm'] == ks['sm_vacua'] and out['n_full'] == ks['full_spectrum'] and out.get('full_control', False)
    print(f"\n  ({time.time() - t0:.0f} s)")
    return out, ok


if __name__ == "__main__":
    out, ok = main()
    print("\nSELFTEST:", "PASS" if ok else "FAIL")
    sys.exit(0 if ok else 1)
