#!/usr/bin/env python3
"""R54b -- exhibit an endomorphism of pi1(m004) realising the complex-conjugate (mirror) character.
Search pairs of words (u, v) in a, b, A=a^-1, B=b^-1 of length <= L with
  (tr rho(u), tr rho(v), tr rho(uv)) = conj(tr rho(a), tr rho(b), tr rho(ab))
and check that the relator r(u, v) maps to +-I (so a -> u, b -> v is a homomorphism), and that the
induced map on H1 = Z is +-1 (so it is surjective on H1)."""
import itertools, numpy as np, snappy, sys
M = snappy.Manifold('m004'); G = M.fundamental_group()
rel = G.relators()[0]; gens = G.generators()
mat = {g: np.array([[complex(G.SL2C(g)[i, j]) for j in range(2)] for i in range(2)]) for g in gens}
for g in gens: mat[g.upper()] = np.linalg.inv(mat[g])
def ev(w):
    m = np.eye(2, dtype=complex)
    for ch in w: m = m @ mat[ch]
    return m
def tr(w): return np.trace(ev(w))
a, b = gens
t0 = np.array([tr(a), tr(b), tr(a + b)])
target = np.conj(t0)
print("relator:", rel, " target (conj traces):", np.round(target, 6))
# H1: exponent sums of the relator
ea, eb = rel.count('a') - rel.count('A'), rel.count('b') - rel.count('B')
print("relator exponent sums (a,b):", (ea, eb), " -> H1 = Z generated by the generator with zero sum coefficient")
letters = ['a', 'b', 'A', 'B']
def words(L):
    for n in range(1, L + 1):
        for w in itertools.product(letters, repeat=n):
            s = ''.join(w)
            if any(s[i] == s[i + 1].swapcase() for i in range(len(s) - 1)): continue  # freely reduced
            yield s
L = int(sys.argv[1]) if len(sys.argv) > 1 else 5
W = list(words(L)); print("words:", len(W))
trs = {w: tr(w) for w in W}
cu = [w for w in W if abs(trs[w] - target[0]) < 1e-6]
cv = [w for w in W if abs(trs[w] - target[1]) < 1e-6]
print("candidates for u:", len(cu), " for v:", len(cv))
def subst(word, u, v):
    inv = lambda s: ''.join(ch.swapcase() for ch in reversed(s))
    return ''.join({'a': u, 'b': v, 'A': inv(u), 'B': inv(v)}[ch] for ch in word)
hits = []
for u in cu:
    for v in cv:
        if abs(tr(u + v) - target[2]) > 1e-6: continue
        R = ev(subst(rel, u, v))
        if np.allclose(R, np.eye(2), atol=1e-6) or np.allclose(R, -np.eye(2), atol=1e-6):
            # induced map on H1: exponent sums of u, v projected to the free H1 generator
            hits.append((u, v, 'rel->+I' if np.allclose(R, np.eye(2), atol=1e-6) else 'rel->-I'))
print("homomorphisms a->u, b->v realising the mirror character:", len(hits))
for h in hits[:12]: print("  ", h)
