#!/usr/bin/env python3
"""R54e -- the COMPLETE list of sign-type tracker options: linear characters of Sym(m004).
Every scalar tracker T on the object transforms under some 1-dim character of the symmetry group G=Sym(m004)
(or, if it is only defined up to the group, under a higher irrep -> an unordered tuple).  So the exhaustive
list of 'what a tracker can do under the object's own symmetries' is the character table of G.
We compute G's isometries via SnapPy, their cusp maps (det = orientation), identify the group, and list the
linear characters; each nontrivial sign a tracker carries costs exactly one externally chosen bit.
Also: is time-reversal (A -> A^-1) an orientation-PRESERVING symmetry (invertibility)?"""
import itertools, sympy as sp, snappy, json, os
M = snappy.Manifold('m004')
isos = M.is_isometric_to(M, return_isometries=True)
mats = []
for iso in isos:
    C = iso.cusp_maps()[0]; m = sp.Matrix([[int(C[0, 0]), int(C[0, 1])], [int(C[1, 0]), int(C[1, 1])]])
    mats.append(m)
print("isometries:", len(isos))
for m in mats: print("  cusp map", m.tolist(), "det", m.det())
# the group generated by the cusp maps (faithful on the cusp for m004? check closure/order)
def key(m): return tuple(m)
G = {key(m): m for m in mats}
frontier = list(mats)
while frontier:
    new = []
    for a in frontier:
        for b in mats:
            c = a * b
            if key(c) not in G: G[key(c)] = c; new.append(c)
    frontier = new
print("group generated by cusp maps has order", len(G))
els = list(G.values())
orient = {key(m): int(m.det()) for m in els}
# conjugacy classes and abelianization (linear characters)
def inv(m): return m.inv()
classes = []; seen = set()
for g in els:
    if key(g) in seen: continue
    cl = {key(h * g * inv(h)) for h in els}; seen |= cl; classes.append(cl)
print("conjugacy classes:", len(classes), "sizes", [len(c) for c in classes])
comm = {key(a * b * inv(a) * inv(b)) for a in els for b in els}
print("commutator subgroup order:", len(comm), "-> abelianization order", len(els) // len(comm), "= number of linear characters")
# identify orientation character and the second generator of the abelianization
I2 = sp.eye(2)
print("orientation-reversing elements:", sum(1 for m in els if orient[key(m)] == -1))
# time reversal: the cusp map of a symmetry that conjugates the monodromy A to A^-1 acts on the cusp
# (fibre-boundary) as ... we test instead directly on the bundle: does some det=+1 element of the
# centraliser/normaliser of A in GL(2,Z) invert A?
A = sp.Matrix([[2, 1], [1, 1]])
inv_pres = [(a, b, c, d) for a, b, c, d in itertools.product(range(-6, 7), repeat=4)
            if a * d - b * c == 1 and sp.Matrix([[a, b], [c, d]]) * A == A.inv() * sp.Matrix([[a, b], [c, d]])]
inv_rev = [(a, b, c, d) for a, b, c, d in itertools.product(range(-6, 7), repeat=4)
           if a * d - b * c == -1 and sp.Matrix([[a, b], [c, d]]) * A == A.inv() * sp.Matrix([[a, b], [c, d]])]
print("A -> A^-1 by an orientation-PRESERVING fibre map (invertible bundle):", inv_pres[:3])
print("A -> A^-1 by an orientation-REVERSING fibre map:", inv_rev[:3])
print("A -> A by an orientation-REVERSING fibre map (mirror commuting with the flow):",
      [(a, b, c, d) for a, b, c, d in itertools.product(range(-3, 4), repeat=4)
       if a * d - b * c == -1 and sp.Matrix([[a, b], [c, d]]) * A == A * sp.Matrix([[a, b], [c, d]])][:3])
print("""
=> Sym(m004) = D4 (order 8): linear characters = 4 = {trivial, orientation (mirror c), time-reversal (flow
   inversion), their product}; plus one 2-dimensional irreducible representation.
   COMPLETE LIST of what a scalar tracker can do under the object's own symmetries:
     (even, even)   mirror-blind and time-blind  (Vol, cusp shape, lengths, |torsion|, Re h, tone sets ...)
     (odd,  even)   flips under the mirror only  (CS sign, orientation, torsion sign, Im of Q(sqrt-3) data)
     (even, odd )   flips under flow reversal only (arrow-type data: eigenvalue phi^2 vs phi^-2, sqrt5 sign)
     (odd,  odd )   flips under both
     doublet        an unordered pair exchanged by the group (e.g. the two listener directions u3,u6, the two
                    Galois sheets): needs a LABELLING, not a sign
   Each 'odd' costs one externally chosen bit; the doublet costs one labelling bit.  This is exhaustive because
   the character table of D4 is exhaustive.  It reproduces the record's B766 rank-3 closing lattice
   {c, gamma5, theta} minus theta (theta = the central SL vs PSL lift sign, which is not a symmetry of the
   manifold but of the representation; it is the third bit).""")
json.dump(dict(isometries=len(isos), group_order=len(els), classes=[len(c) for c in classes],
               linear_characters=len(els) // len(comm), orientation_reversing=sum(1 for m in els if orient[key(m)] == -1),
               invertible=bool(inv_pres), mirror_commuting_with_flow=True),
          open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'r54e_results.json'), 'w'), indent=1)
