#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
B739 Stage-B recompute — TOMB-L252 (tombstone K-K, speculations/TOMBSTONES.md:L252)

BANKED CLAIM (killed): "gap-labeling spectral rank equals the composition period k of the
seed geodesic."
BANKED KILL (fact_basis=asserted, no arc/script): "A period-`k` geodesic is a `2x2` matrix
= a 2-letter substitution = **always rank 2**, independent of `k`."
(Parenthetical banked fact: golden Fibonacci was first mislabeled "rank 1"; it is rank 2.)

DISCRIMINATING FACT to recompute (E19: compute, don't cite):
  For period-k geodesic words W in {R,L}^k, the gap-labeling group of the induced 2-letter
  substitution subshift has Z-rank (= dim_Q of its Q-span) equal to 2 for EVERY k — while
  the killed claim predicts rank = k.  Value-mismatch for every k != 2.

DECLARED CONVENTIONS (E1 — the arc left them implicit; choices declared here):
  C1. R = [[1,1],[0,1]], L = [[1,0],[1,1]]  (the repo convention, e.g.
      frontier/B139_firewall_cartography/probe.py lines 44-45; seed = RL = [[2,1],[1,1]],
      per S001/S061 "phi_1^2 = [[2,1],[1,1]]").
  C2. "Period-k geodesic" = conjugacy class of a primitive (non-power) word of LETTER
      length k in {R,L}, both letters present (k=1 is parabolic, trace 2 — no closed
      hyperbolic geodesic; excluded).  The alternative "k = number of R^a L^b blocks"
      reading is covered by the same family (the computed rank is word-independent, so it
      refutes rank=k under either counting).
  C3. Matrix -> substitution realization (the kill's "2x2 matrix = 2-letter substitution"):
      rho_R: a->a, b->ab   and   rho_L: a->ba, b->b, composed left-to-right
      (sigma_W = rho_{w1} o ... o rho_{wk}).  Abelianization convention M[i][j] = number of
      occurrences of letter i in sigma(letter j); then M(rho_R)=R, M(rho_L)=L and
      M(sigma_W) = M_{w1}...M_{wk} = M_W exactly (asserted in-script per word).
  C4. "Gap-labeling spectral rank" = rank over Q (dimension of the Q-linear span) of the
      gap-labeling group, i.e. the Z-module generated by the unique-ergodic-measure values
      mu([w]) of all cylinder sets [w] (Bellissard gap-labeling: the trace image of K0 is
      exactly this module for a subshift).  Computed here from exact n-block frequencies
      for n = 1..4, closed for ALL n by the field bound (every mu([w]) lies in Q(sqrt(D)),
      a degree-2 field — see the a-priori argument printed at the end).
  C5. Deterministic word family: all primitive binary necklace representatives
      (lexicographically minimal rotation) with both letters, sorted, per k:
      k=2,3,4 all; k=5,6,7 first 3; k=8 first 2.  Plus the golden Fibonacci substitution
      (a->ab, b->a) for the parenthetical rank-1-mislabel check.

METHOD (all exact, stdlib-only: fractions; no floats in any verdict-bearing number;
no wall-clock, no randomness, no network):
  1. M_W = product of the word's matrices; T = tr, det = 1; lambda = (T + sqrt(T^2-4))/2,
     an exact element of Q(sqrt(D)) (D = squarefree part of T^2-4).
  2. sigma_W built by C3; abelianization asserted == M_W.
  3. Language of the subshift: unions of n-factors of sigma_W^m('a') until stable
     (primitive substitution => this union is the language).
  4. For n=1..4: the induced n-block substitution matrix M_n (Queffelec construction:
     sigma_n(w) = the first |sigma(w[0])| n-blocks of sigma(w)); primitivity of M_n
     verified by matrix powering; the Perron property of lambda verified by exact
     nullspace of (M_n - lambda*I) over Q(sqrt(D)) (nullity 1) plus strict positivity of
     the eigenvector (Perron-Frobenius: a positive eigenvector belongs only to the Perron
     root).  Frequencies = eigenvector normalized to sum 1.
  5. Cross-checks: marginal consistency freq_{n-1}(v) = sum of freq_n over n-blocks with
     prefix v (exact equality); empirical counts on a >=20000-letter deterministic
     substitution word (tolerance 2e-2; diagnostic only).
  6. Rank over Q of all block frequencies (as (p,q) coordinates in basis {1, sqrt(D)}),
     cumulatively in n.  Compare with the killed claim's prediction rank = k.

Gate 5: pure mathematics only — no SM quantities anywhere.
"""

from fractions import Fraction
import itertools
import math

# ----------------------------------------------------------------------------
# Exact arithmetic in Q(sqrt(D)), D > 0 squarefree (represented p + q*sqrt(D))
# ----------------------------------------------------------------------------

class QF:
    __slots__ = ("p", "q", "D")

    def __init__(self, p, q, D):
        self.p = Fraction(p)
        self.q = Fraction(q)
        self.D = int(D)

    def _chk(self, o):
        assert isinstance(o, QF) and o.D == self.D, "field mismatch"

    def __add__(self, o):
        self._chk(o)
        return QF(self.p + o.p, self.q + o.q, self.D)

    def __sub__(self, o):
        self._chk(o)
        return QF(self.p - o.p, self.q - o.q, self.D)

    def __neg__(self):
        return QF(-self.p, -self.q, self.D)

    def __mul__(self, o):
        self._chk(o)
        return QF(self.p * o.p + self.q * o.q * self.D,
                  self.p * o.q + self.q * o.p, self.D)

    def inv(self):
        n = self.p * self.p - self.q * self.q * self.D  # field norm (nonzero unless 0)
        assert n != 0, "division by zero in Q(sqrt(D))"
        return QF(self.p / n, -self.q / n, self.D)

    def __truediv__(self, o):
        self._chk(o)
        return self * o.inv()

    def is_zero(self):
        return self.p == 0 and self.q == 0

    def __eq__(self, o):
        return isinstance(o, QF) and o.D == self.D and self.p == o.p and self.q == o.q

    def sign(self):
        p, q, D = self.p, self.q, self.D
        if p == 0 and q == 0:
            return 0
        if p >= 0 and q >= 0:
            return 1
        if p <= 0 and q <= 0:
            return -1
        t = p * p - q * q * D  # compare magnitudes exactly
        assert t != 0, "impossible: sqrt(D) rational"
        if p > 0:                      # q < 0
            return 1 if t > 0 else -1
        return -1 if t > 0 else 1      # p < 0, q > 0

    def __repr__(self):
        if self.q == 0:
            return str(self.p)
        if self.p == 0:
            return "(%s)*sqrt(%d)" % (self.q, self.D)
        return "%s + (%s)*sqrt(%d)" % (self.p, self.q, self.D)


def squarefree_split(n):
    """n = f^2 * D with D squarefree; return (f, D)."""
    assert n > 0
    f, D, m = 1, 1, n
    d = 2
    while d * d <= m:
        e = 0
        while m % d == 0:
            m //= d
            e += 1
        f *= d ** (e // 2)
        if e % 2:
            D *= d
        d += 1
    D *= m
    return f, D


# ----------------------------------------------------------------------------
# Words, matrices, substitutions
# ----------------------------------------------------------------------------

MAT = {"R": ((1, 1), (0, 1)), "L": ((1, 0), (1, 1))}   # repo convention (B139 probe.py)
RHO = {"R": {"a": "a", "b": "ab"}, "L": {"a": "ba", "b": "b"}}  # abelianizations R, L


def mat_mul(A, B):
    return tuple(tuple(sum(A[i][t] * B[t][j] for t in range(2)) for j in range(2))
                 for i in range(2))


def word_matrix(word):
    M = ((1, 0), (0, 1))
    for ch in word:
        M = mat_mul(M, MAT[ch])
    return M


def apply_sub(sub, w):
    return "".join(sub[c] for c in w)


def compose(word):
    """sigma_W = rho_{w1} o rho_{w2} o ... o rho_{wk} (rightmost applied first)."""
    sub = {"a": "a", "b": "b"}
    for ch in word:  # left to right accumulation of the OUTER composition
        r = RHO[ch]
        sub = {c: apply_sub(sub, r[c]) for c in "ab"}
    return sub


def abelianization(sub):
    return tuple(tuple(sub[c].count(l) for c in "ab") for l in "ab")


def is_primitive_word(w):
    k = len(w)
    for d in range(1, k):
        if k % d == 0 and w == w[:d] * (k // d):
            return False
    return True


def necklace_reps(k):
    reps = set()
    for bits in itertools.product("LR", repeat=k):
        w = "".join(bits)
        if "R" not in w or "L" not in w or not is_primitive_word(w):
            continue
        reps.add(min(w[i:] + w[:i] for i in range(k)))
    return sorted(reps)


# ----------------------------------------------------------------------------
# Language (factor sets) of the substitution subshift
# ----------------------------------------------------------------------------

def languages_and_longword(sub, n_max, min_len=20000, max_len=2_000_000):
    """Return ({n: sorted list of n-factors}, long deterministic word).
    For a primitive substitution the language of the subshift equals the increasing
    union over m of the factor sets of sigma^m('a')."""
    unions = {n: set() for n in range(1, n_max + 1)}
    w = "a"
    stable = 0
    for _ in range(200):
        w = apply_sub(sub, w)
        changed = False
        for n in range(1, n_max + 1):
            for i in range(len(w) - n + 1):
                f = w[i:i + n]
                if f not in unions[n]:
                    unions[n].add(f)
                    changed = True
        if not changed and len(w) >= min_len:
            stable += 1
        else:
            stable = 0
        if stable >= 2 or len(w) > max_len:
            break
    return {n: sorted(unions[n]) for n in unions}, w


# ----------------------------------------------------------------------------
# n-block induced substitution and exact Perron frequencies
# ----------------------------------------------------------------------------

def nblock_matrix(sub, Ln, n):
    idx = {w: i for i, w in enumerate(Ln)}
    m = len(Ln)
    M = [[0] * m for _ in range(m)]
    for j, w in enumerate(Ln):
        s = apply_sub(sub, w)
        p = len(sub[w[0]])
        assert len(s) >= p - 1 + n
        for t in range(p):
            blk = s[t:t + n]
            assert blk in idx, "n-block image outside language: %r -> %r" % (w, blk)
            M[idx[blk]][j] += 1
    return M


def int_matrix_primitive(M):
    m = len(M)
    A = [row[:] for row in M]
    for _ in range(max(1, m * m)):
        if all(A[i][j] > 0 for i in range(m) for j in range(m)):
            return True
        A = [[sum(A[i][t] * M[t][j] for t in range(m)) for j in range(m)]
             for i in range(m)]
    return all(A[i][j] > 0 for i in range(m) for j in range(m))


def nullspace_QF(A, D):
    """Exact nullspace basis of square QF-matrix A over Q(sqrt(D))."""
    m = len(A)
    B = [row[:] for row in A]
    piv_cols, r = [], 0
    for c in range(m):
        piv = None
        for i in range(r, m):
            if not B[i][c].is_zero():
                piv = i
                break
        if piv is None:
            continue
        B[r], B[piv] = B[piv], B[r]
        inv = B[r][c].inv()
        B[r] = [x * inv for x in B[r]]
        for i in range(m):
            if i != r and not B[i][c].is_zero():
                f = B[i][c]
                B[i] = [x - f * y for x, y in zip(B[i], B[r])]
        piv_cols.append(c)
        r += 1
    free = [c for c in range(m) if c not in piv_cols]
    basis = []
    for fc in free:
        v = [QF(0, 0, D) for _ in range(m)]
        v[fc] = QF(1, 0, D)
        for i, pc in enumerate(piv_cols):
            v[pc] = -B[i][fc]
        basis.append(v)
    return basis


def rank_Q(vecs):
    """Rank over Q of vectors (p, q) in Q^2 (coordinates in basis {1, sqrt(D)})."""
    rows = [list(v) for v in vecs]
    r = 0
    for col in range(2):
        piv = None
        for i in range(r, len(rows)):
            if rows[i][col] != 0:
                piv = i
                break
        if piv is None:
            continue
        rows[r], rows[piv] = rows[piv], rows[r]
        pr = rows[r]
        for i in range(len(rows)):
            if i != r and rows[i][col] != 0:
                f = Fraction(rows[i][col], 1) / pr[col]
                rows[i] = [a - f * b for a, b in zip(rows[i], pr)]
        r += 1
    return r


# ----------------------------------------------------------------------------
# One full case
# ----------------------------------------------------------------------------

N_MAX = 4


def run_case(label, sub, M, claimed_k):
    """Return dict with exact results for one substitution case."""
    T = M[0][0] + M[1][1]
    det = M[0][0] * M[1][1] - M[0][1] * M[1][0]
    D0 = T * T - 4 * det
    assert D0 > 0, "not hyperbolic-type: T^2-4det <= 0"
    f, D = squarefree_split(D0)
    assert D > 1, "lambda rational -> periodic subshift (excluded by hyperbolicity)"
    lam = QF(Fraction(T, 2), Fraction(f, 2), D)
    # verify the characteristic polynomial exactly: lam^2 - T*lam + det = 0
    chk = lam * lam - QF(T, 0, D) * lam + QF(det, 0, D)
    assert chk.is_zero(), "lambda fails char poly"

    langs, longw = languages_and_longword(sub, N_MAX)
    zero, one = QF(0, 0, D), QF(1, 0, D)

    freqs_by_n = {}
    all_pq = []
    ranks_cum = []
    complexity = []
    emp_max_dev = 0.0
    # float sqrt used ONLY for the DIAGNOSTIC empirical comparison; never verdict-bearing
    sqrtD = math.sqrt(D)

    for n in range(1, N_MAX + 1):
        Ln = langs[n]
        complexity.append(len(Ln))
        Mn = nblock_matrix(sub, Ln, n)
        assert int_matrix_primitive(Mn), "n-block matrix not primitive"
        A = [[QF(Mn[i][j], 0, D) - (lam if i == j else zero)
              for j in range(len(Ln))] for i in range(len(Ln))]
        basis = nullspace_QF(A, D)
        assert len(basis) == 1, "Perron eigenspace not 1-dimensional (nullity=%d)" % len(basis)
        v = basis[0]
        s = zero
        for x in v:
            s = s + x
        assert not s.is_zero()
        freq = [x / s for x in v]
        # strict positivity => (Perron-Frobenius) lambda IS the Perron root of Mn
        for x in freq:
            assert x.sign() == 1, "eigenvector not strictly positive"
        # sum check (exact, by construction but asserted)
        s2 = zero
        for x in freq:
            s2 = s2 + x
        assert s2 == one
        freqs_by_n[n] = dict(zip(Ln, freq))
        # marginal consistency with level n-1 (exact)
        if n >= 2:
            for vprev, fv in freqs_by_n[n - 1].items():
                acc = zero
                for w, fw in freqs_by_n[n].items():
                    if w[:n - 1] == vprev:
                        acc = acc + fw
                assert acc == fv, "marginal inconsistency at n=%d" % n
        # empirical cross-check (diagnostic only)
        total = len(longw) - n + 1
        for w, fw in freqs_by_n[n].items():
            # overlapping occurrence count (str.count is non-overlapping; unsafe for
            # self-overlapping blocks like 'aaa')
            cnt = 0
            start = 0
            while True:
                i = longw.find(w, start)
                if i < 0:
                    break
                cnt += 1
                start = i + 1
            emp = cnt / total
            ex = float(fw.p) + float(fw.q) * sqrtD
            emp_max_dev = max(emp_max_dev, abs(emp - ex))
        # cumulative rank of the gap-label module generated so far
        for x in freq:
            all_pq.append((x.p, x.q))
        ranks_cum.append(rank_Q(all_pq))

    assert emp_max_dev < 2e-2, "empirical frequencies disagree (max dev %.3g)" % emp_max_dev

    fa = freqs_by_n[1]["a"]
    assert fa.q != 0, "letter frequency rational -> not aperiodic"
    return {
        "label": label, "k": claimed_k, "M": M, "T": T, "det": det, "D": D,
        "lam": lam, "freq_a": fa, "complexity": complexity,
        "ranks_cum": ranks_cum, "rank": ranks_cum[-1], "emp_dev": emp_max_dev,
    }


# ----------------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------------

def main():
    print("=" * 78)
    print("B739 Stage-B recompute — TOMB-L252 (K-K: gap-labeling rank = composition period)")
    print("=" * 78)
    print(__doc__.split("METHOD")[0].strip())
    print("-" * 78)

    per_k_cap = {2: None, 3: None, 4: None, 5: 3, 6: 3, 7: 3, 8: 2}
    cases = []

    for k in sorted(per_k_cap):
        reps = necklace_reps(k)
        cap = per_k_cap[k]
        chosen = reps if cap is None else reps[:cap]
        print("k=%d: %d primitive both-letter necklaces; testing %s"
              % (k, len(reps), chosen))
        for word in chosen:
            M = word_matrix(word)
            sub = compose(word)
            assert abelianization(sub) == M, "abelianization mismatch for %s" % word
            cases.append(run_case(word, sub, M, k))

    # the seed itself, in its S001/S061 form RL = [[2,1],[1,1]] (rotation of the k=2 rep)
    seed = run_case("RL(seed)", compose("RL"), word_matrix("RL"), 2)
    cases.append(seed)

    # parenthetical banked fact: golden Fibonacci is rank 2, not rank 1
    fib_sub = {"a": "ab", "b": "a"}
    fib = run_case("Fibonacci(a->ab,b->a)", fib_sub, abelianization(fib_sub), None)

    print("-" * 78)
    print("PER-CASE RESULTS (rank = dim_Q of Q-span of all n-block frequencies, n=1..%d)"
          % N_MAX)
    print("-" * 78)
    hdr = "%-14s %2s %5s %6s %-26s %-12s %-10s %s"
    print(hdr % ("word", "k", "tr", "D", "freq(a) exact", "complexity",
                 "rank@n=1..4", "claim k -> verdict"))
    mismatches = 0
    for c in cases:
        verdict = ("MATCH (coincidence at k=2)" if c["rank"] == c["k"]
                   else "MISMATCH %d != %d" % (c["rank"], c["k"]))
        if c["rank"] != c["k"]:
            mismatches += 1
        print(hdr % (c["label"], c["k"], c["T"], c["D"], repr(c["freq_a"]),
                     ",".join(map(str, c["complexity"])),
                     ",".join(map(str, c["ranks_cum"])), verdict))
    print(hdr % (fib["label"], "-", fib["T"], fib["D"], repr(fib["freq_a"]),
                 ",".join(map(str, fib["complexity"])),
                 ",".join(map(str, fib["ranks_cum"])),
                 "banked 'rank 2 not 1' -> computed rank %d" % fib["rank"]))

    ranks = sorted(set(c["rank"] for c in cases))
    ks = sorted(set(c["k"] for c in cases))
    print("-" * 78)
    print("A-PRIORI CLOSURE FOR ALL DEPTHS n (completing 'nothing internal raises the")
    print("rank above 2'): every n-block frequency was computed EXACTLY inside the")
    print("quadratic field Q(sqrt(D)) — it solves (M_n - lambda*I)x = 0, a linear system")
    print("over Q(lambda) with lambda of algebraic degree 2 (root of x^2 - T x + det,")
    print("T^2 - 4det nonsquare; asserted per case).  Hence EVERY cylinder measure lies")
    print("in the 2-dimensional Q-vector space Q(sqrt(D)), so the gap-label module has")
    print("rank <= 2 at every depth n, for every k; and rank >= 2 because freq(a) has a")
    print("nonzero sqrt(D)-coordinate (asserted per case).  Rank = 2 exactly, always.")
    print("-" * 78)
    print("SUMMARY")
    print("  cases (period-k geodesic words): %d, k in %s" % (len(cases), ks))
    print("  computed gap-labeling rank, every case: %s" % ranks)
    print("  killed claim predicts rank = k: mismatch in %d/%d cases (all k != 2);"
          % (mismatches, len(cases)))
    print("  the sole k=2 'match' is the seed coincidence (2 = 2) that does not")
    print("  generalize — exactly the banked kill's content.")
    print("  Fibonacci parenthetical: computed rank %d (banked: 'it is rank 2') -> upheld."
          % fib["rank"])
    ok = (ranks == [2]) and (fib["rank"] == 2) and mismatches > 0
    print("VERDICT: %s" % ("RECONFIRMED — the banked kill's discriminating fact "
                           "(rank 2, independent of k) is recomputed true."
                           if ok else "NOT REPRODUCED — see table"))
    assert ok


if __name__ == "__main__":
    main()
