#!/usr/bin/env python3
"""B1525 -- GENESIS v1.5: every item v1.5 carries or adds, checked with the SM seat's own code before it is written.

C1  sm:B1521's two checks re-run (P is the swap's class and fixes rho_q; the audit lane's AR3-AR6), each output compared
    byte for byte with its banked record. They carry FK9's sentence on P, FK12's B130 scope, §7's AR6 sentence and §9's
    four rows. The scripts are loaded from their own files and write into a temporary directory, not over the records.
C2  The levels (sm:B1522), by a third route that shares no code with its two routes or its post-run checks. The characters
    of T_n = coker(Phi^n - 1), Phi = LR, are enumerated as integer row vectors w mod D = |T_n| with w (Phi^n - 1) = 0 mod D,
    and each is tested against the count-odd maps of M_n directly:
      - the count-odd maps are the lifts with det -1 on the fibre (they invert the fibre boundary, main's one-bit rule on
        m004): the reflections +-Phi^k S (the base reversed; S = [[1,1],[0,-1]], S Phi S = Phi^-1) and the rotations
        +-G^(2k+1) (the base kept; G = [[0,1],[1,1]], G^2 = Phi), k < n;
      - off the unit circle the meridian value lambda forces the base reversed, so a vacuum is fixed exactly when a
        reflection h sends its twist to the inverse, w h = -w mod D; on the circle a rotation with the twist conjugated
        also fixes it, w h = w, which the sign +-h turns into w h = -w.
    The 24 counts of M1..M12 and M13's two are compared with B1522's records (census.json, lemma_f_beyond.json), Lemma F's
    closed forms and |T_n| = L_2n - 2 are checked, and the 196 firing members (P8, X3) and the post-run checks are read.
C3  The word states (sm:B1523), by own word code: the 758 states and 536 manifolds; each manifold's kinds (rev, swap,
    swaprev) from its word, against the record; main's one-bit rule on every isometry the record lists (eps = -1 exactly
    when the fibre boundary is inverted); the 262 mirror-broken manifolds (131 per sign, 482 states; 220 chiral, 42
    swaprev-only) are exactly those whose word has neither rev nor swap; the first by length; the 14 golden manifolds by
    trace (the squarefree part of t^2 - 4 is 5), of which exactly +-L4RL3R2 and +-L4RLR3LR2 are mirror-broken.
C4  The bar's null contract (sm:B1524): its record's checks, and docs/THE_BAR.md's PASSED, Bonferroni and contract.
C5  The audit lane's GAP3 refinement, from its relay as received (byte-identical to its blob at 24c039c8 where that commit
    is in the clone): its sentences, against v1.5's GAP3.
C6  v1.5 against main's v1.4, regenerated by merge_genesis_v15.py:
      - main's words are kept except eleven listed edits, all but two of them punctuation where a marked sentence is
        appended: the version number, the word "A" of GAP3's rewritten sentence, and "frame" made "frame's counts";
      - every changed block carries a [v1.5] mark or is the header's;
      - earlier marks unchanged and 16 [v1.5] marks; sections 0-10 in order; every table well formed;
      - no status changed: every table row of v1.4 is kept verbatim but four, whose leading cells are kept;
      - no Gate 5-Q word (Q5's three, whole words, encoded here), vendor word or private term; and the received v1.3 does
        carry Q5's third word, the slip v1.5 removes, so the check can fire.
Usage: python3 genesis_v15_checks.py   (writes genesis_v15_checks.json and prints it; about 20 s)"""
import base64
import collections
import contextlib
import difflib
import hashlib
import importlib.util
import io
import itertools
import json
import re
import subprocess
import sys
import tempfile
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
ARC = HERE.parent
ROOT = ARC.parents[1]
REC = ARC / "received"
V14 = REC / "GENESIS_v1_4_main.md"
V13 = REC / "GENESIS_v1_3_sm.md"
RELAY = REC / "CODEX_TO_CC_AND_SM_2026-10-03_HARVEST_REPLY_AND_ADMISSION_SCOPE.md"
SHA = {V14.name: "d32456b67ae2cb55e036de57c2a8619a8e546b7656144c1cf7ab008615bd557a",
       V13.name: "d675c0fd663c354ebed70fa3ea80e3232b2829f3d9c9c03e55953c85ce1c77c0",
       RELAY.name: "a6975527c7443f690184ad1c5e66b60a394fdac4f1f24217f2f4815dc19e3307"}
MARK = "**[v1.5]**"


def sha(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()


def norm(t):
    return re.sub(r"\s+", " ", t).strip()


# ------------------------------------------------------------------------------------------------ C1
def c1():
    ver = ROOT / "frontier" / "B1521_genesis_v13" / "verification"
    out = {}
    with tempfile.TemporaryDirectory() as tmp:
        for name in ("which_class_is_P", "audit_corrections"):
            spec = importlib.util.spec_from_file_location("b1521_" + name, ver / (name + ".py"))
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            mod.HERE = Path(tmp)                     # write into the temporary directory, never over the record
            with contextlib.redirect_stdout(io.StringIO()):
                mod.main()
            fresh = (Path(tmp) / (name + ".json")).read_bytes()
            out[name + ".json byte-identical to the record"] = fresh == (ver / (name + ".json")).read_bytes()
    w = json.loads((ver / "which_class_is_P.json").read_text(encoding="utf-8"))
    a = json.loads((ver / "audit_corrections.json").read_text(encoding="utf-8"))
    out["P is the swap's class (conjugator found) and +1 on H1"] = (
        w["P_class"]["P' = inner o swap, conjugator"] is not None and w["P_transported"]["H1_images"] == [1, 1])
    out["rho_q o P = rho_q and not rho_q^* at q = 2, 3, 1/5, 7/3"] = all(
        r["Hom(rho_q, rho_q o P)"]["invertible_member"] and r["Hom(rho_q^*, rho_q o P)"]["dim"] == 0
        for r in w["ballas"] if r["q"] != "1")
    out["AR3: B37's and B20's predicates flip under a vacuous rewriting"] = (
        a["AR3"]["B37 predicate fires on T"] is False and a["AR3"]["B37 predicate fires on the rewritten T'"] is True
        and a["AR3"]["B20 predicate fires on T"] is False and a["AR3"]["B20 predicate fires on T'"] is True)
    out["AR4: an isolated component the elimination cannot see; B130's m = 2 ideal zero"] = (
        a["AR4"]["countermodel elimination ideal in k"] == [] and a["AR4"]["Jacobian rank at the isolated point (1, 0)"] == 2
        and a["AR4"]["B130 m = 2 elimination ideal in kappa (reproduced)"] == [])
    out["AR5: m = 1, 4, 11 share Q(sqrt 5)"] = a["AR5"]["fields shared by several m"].get("5") == [1, 4, 11]
    out["AR6: conjugation moves sqrt(-3); B723's banner carries B942 and B957"] = (
        a["AR6"]["complex conjugation sends sqrt(-3) to -sqrt(-3)"] is True and all(a["AR6"]["B723 banner carries"].values()))
    out["passed"] = all(out.values())
    return out


# ------------------------------------------------------------------------------------------------ C2
def mul(A, B):
    return [[A[0][0] * B[0][0] + A[0][1] * B[1][0], A[0][0] * B[0][1] + A[0][1] * B[1][1]],
            [A[1][0] * B[0][0] + A[1][1] * B[1][0], A[1][0] * B[0][1] + A[1][1] * B[1][1]]]


def mpow(A, k):
    R = [[1, 0], [0, 1]]
    for _ in range(k):
        R = mul(R, A)
    return R


def neg(A):
    return [[-x for x in r] for r in A]


def det(A):
    return A[0][0] * A[1][1] - A[0][1] * A[1][0]


L_, R_ = [[1, 0], [1, 1]], [[1, 1], [0, 1]]
PHI = mul(L_, R_)                      # m004 = LR
G = [[0, 1], [1, 1]]                   # the golden matrix: G^2 = PHI, det -1, eigenvalues phi and -1/phi
S = [[1, 1], [0, -1]]                  # det -1, an involution, S PHI S = PHI^-1
PHI_INV = [[2, -1], [-1, 1]]


def characters(n):
    """the dual of T_n = Z^2/(PHI^n - 1)Z^2: row vectors w mod D with w (PHI^n - 1) = 0 mod D, D = |det(PHI^n - 1)|.
    w = u adj(A) mod D runs over them as u runs over a box of index D; the image lies in the dual (w A = u det(A) = 0)
    and its size is checked to be D, so it is the whole dual."""
    P = mpow(PHI, n)
    A = [[P[0][0] - 1, P[0][1]], [P[1][0], P[1][1] - 1]]
    D = abs(det(A))
    adj = [[A[1][1], -A[0][1]], [-A[1][0], A[0][0]]]
    g = gcd_(A[0][0], A[1][0])
    out = {((x * adj[0][0] + y * adj[1][0]) % D, (x * adj[0][1] + y * adj[1][1]) % D)
           for x in range(g) for y in range(D // g)}
    assert len(out) == D, (n, len(out), D)
    for w in itertools.islice(out, 50):
        assert (w[0] * A[0][0] + w[1] * A[1][0]) % D == 0 and (w[0] * A[0][1] + w[1] * A[1][1]) % D == 0
    return D, out


def gcd_(a, b):
    a, b = abs(a), abs(b)
    while b:
        a, b = b, a % b
    return a


def level_counts(n):
    D, chars = characters(n)
    refl, rot = [], []
    for k in range(n):
        h = mul(mpow(PHI, k), S)
        refl += [h, neg(h)]
        r = mpow(G, 2 * k + 1)
        rot += [r, neg(r)]
    assert all(det(h) == -1 for h in refl + rot)
    # a reflection is an involution inverting PHI (the base reversed); a rotation commutes with PHI (the base kept)
    assert all(mul(h, h) == [[1, 0], [0, 1]] and mul(mul(h, PHI), h) == PHI_INV for h in refl)
    assert all(mul(r, PHI) == mul(PHI, r) for r in rot)

    def inverted_by(w, hs):
        return any((w[0] * h[0][0] + w[1] * h[1][0] + w[0]) % D == 0 and (w[0] * h[0][1] + w[1] * h[1][1] + w[1]) % D == 0
                   for h in hs)
    off = sum(1 for w in chars if not inverted_by(w, refl))
    on = sum(1 for w in chars if not inverted_by(w, refl) and not inverted_by(w, rot))
    return D, off, on


def lucas(n):
    a, b = 2, 1
    for _ in range(n):
        a, b = b, a + b
    return a


def c2():
    ver = ROOT / "frontier" / "B1522_the_golden_choice" / "verification"
    census = json.loads((ver / "census.json").read_text(encoding="utf-8"))
    readout = json.loads((ver / "read_out.json").read_text(encoding="utf-8"))
    post = json.loads((ver / "post_run_check.json").read_text(encoding="utf-8"))
    beyond = json.loads((ver / "lemma_f_beyond.json").read_text(encoding="utf-8"))
    # the matrices: S and G as stated
    assert mul(G, G) == PHI and det(G) == -1 and det(S) == -1 and mul(S, S) == [[1, 0], [0, 1]]
    assert mul(mul(S, PHI), S) == [[2, -1], [-1, 1]] and mul([[2, -1], [-1, 1]], PHI) == [[1, 0], [0, 1]]
    rec = {lv["n"]: lv for lv in census["levels"]}
    rows, agree = {}, True
    for n in range(1, 14):
        D, off, on = level_counts(n)
        row = {"|T_n|": D, "unfixed off the circle": off, "unfixed on it": on, "L_2n - 2": lucas(2 * n) - 2}
        if n in rec:
            row["the record agrees"] = (rec[n]["order"] == D and rec[n]["unfixed at generic lam"] == off
                                        and rec[n]["unfixed at unitary lam"] == on)
        else:
            row["the record agrees"] = (beyond["n"] == 13 and beyond["characters"] == D
                                        and beyond["unfixed off the circle"] == off and beyond["unfixed on the circle"] == on)
        agree &= row["the record agrees"] and D == lucas(2 * n) - 2
        rows[str(n)] = row
    lemma_f = {}
    for n in (5, 7, 11, 13):
        p = lucas(n)
        lemma_f[str(n)] = {"p = L_n": p, "(p-1)(p+1-2n)": (p - 1) * (p + 1 - 2 * n), "(p-1)(p-1-2n)": (p - 1) * (p - 1 - 2 * n),
                           "match": rows[str(n)]["unfixed off the circle"] == (p - 1) * (p + 1 - 2 * n)
                           and rows[str(n)]["unfixed on it"] == (p - 1) * (p - 1 - 2 * n)}
    share = {str(n): round(rows[str(n)]["unfixed off the circle"] / rows[str(n)]["|T_n|"], 2) for n in range(5, 13)}
    first_off = min(n for n in range(1, 13) if rows[str(n)]["unfixed off the circle"])
    first_on = min(n for n in range(1, 13) if rows[str(n)]["unfixed on it"])
    pred = readout["predictions"]
    out = {
        "levels (third route)": rows,
        "all 26 counts agree with the records, and |T_n| = L_2n - 2": agree,
        "Lemma F closed forms": lemma_f,
        "shares off the circle, M5..M12": share,
        "breaks first: off the circle, on it": [first_off, first_on],
        "M12: unfixed off the circle of all": [rows["12"]["unfixed off the circle"], rows["12"]["|T_n|"]],
        "the 196 firing members fixed (P8 and X3, from the records)": pred["P8"]["read"] == [196, 196]
        and post["X3"]["fixed"] == 196 and post["X3"]["members"] == 196 and post["X3"]["unfixed"] == [],
        "the sealed golden form holds (record)": readout["golden reading"][
            "sealed form holds (criterion route F = route R on n <= 12; criterion bypassed by X2 on n <= 6)"] is True,
        "post-run checks X1-X4 passed (record)": post["all passed"] is True,
        "nine of nine held (record)": readout["held"] == 9 and readout["outcome"] == "B",
    }
    out["passed"] = (agree and all(v["match"] for v in lemma_f.values()) and [first_off, first_on] == [5, 6]
                     and share == {"5": 0.17, "6": 0.3, "7": 0.53, "8": 0.61, "9": 0.77, "10": 0.8, "11": 0.89, "12": 0.91}
                     and out["M12: unfixed off the circle of all"] == [93936, 103680]
                     and all(out[k] for k in ("the 196 firing members fixed (P8 and X3, from the records)",
                                              "the sealed golden form holds (record)",
                                              "post-run checks X1-X4 passed (record)", "nine of nine held (record)")))
    return out


# ------------------------------------------------------------------------------------------------ C3
SW = str.maketrans("LR", "RL")


def cyc(w):
    return min(w[i:] + w[:i] for i in range(len(w)))


def primitive(w):
    return not any(len(w) % d == 0 and w == w[:d] * (len(w) // d) for d in range(1, len(w)))


def word_trace(w):
    M = [[1, 0], [0, 1]]
    for ch in w:
        M = mul(M, L_ if ch == "L" else R_)
    return M[0][0] + M[1][1]


def squarefree(d):
    core, p = 1, 2
    while p * p <= d:
        while d % (p * p) == 0:
            d //= p * p
        if d % p == 0:
            core *= p
            d //= p
        p += 1
    return core * d


def c3():
    rec = json.loads((ROOT / "frontier" / "B1523_the_flexible_states" / "verification" / "read_out.json")
                     .read_text(encoding="utf-8"))
    states = {}
    for n in range(2, 13):
        for t in itertools.product("LR", repeat=n):
            w = "".join(t)
            if "L" in w and "R" in w and primitive(w):
                st = min(cyc(w), cyc(w.translate(SW)))
                man = min(st, cyc(w[::-1]), cyc(w[::-1].translate(SW)))
                for s in "+-":
                    states[(s, st)] = (s, man)
    mans = collections.defaultdict(list)
    for k, m in states.items():
        mans[m].append(k)
    rows = {r["manifold"]: r for r in rec["rows"]}
    kinds_agree = rule_on_every_isometry = broken_is_word_rule = state_counts_agree = True
    broken, golden = [], []
    for (s, w), sts in mans.items():
        r = rows[s + w]
        c = cyc(w)
        rev, swap, swaprev = cyc(w[::-1]) == c, cyc(w.translate(SW)) == c, cyc(w[::-1].translate(SW)) == c
        kinds_agree &= r["kinds"] == {"rev": rev, "swap": swap, "swaprev": swaprev}
        rule_on_every_isometry &= all((iso["eps"] == -1) == iso["inverts"] for iso in r["isometries"])
        broken_is_word_rule &= r["dualising isometry"] == (rev or swap)
        state_counts_agree &= len(r["states"]) == len(sts)
        t = word_trace(w)
        if squarefree(t * t - 4) == 5:
            golden.append(s + w)
        if not r["dualising isometry"]:
            broken.append((len(w), s + w, len(sts), "none" if not (rev or swap or swaprev) else
                           "swaprev only" if swaprev and not (rev or swap) else "other"))
    broken.sort()
    out = {
        "states, manifolds": [len(states), len(mans)],
        "the record lists every manifold": sorted(rows) == sorted(s + w for (s, w) in mans),
        "kinds from the words agree with the record on all 536": kinds_agree,
        "one-bit rule: eps = -1 exactly when the fibre boundary is inverted, every isometry of the record":
            rule_on_every_isometry,
        "mirror-broken exactly when the word has neither rev nor swap": broken_is_word_rule,
        "states per manifold agree": state_counts_agree,
        "mirror-broken manifolds, per sign, states": [len(broken), dict(collections.Counter(b[1][0] for b in broken)),
                                                       sum(b[2] for b in broken)],
        "by kind": dict(collections.Counter(b[3] for b in broken)),
        "by length": {str(k): v for k, v in sorted(collections.Counter(b[0] for b in broken).items())},
        "first mirror-broken": [b[1] for b in broken if b[0] == broken[0][0]],
        "first chiral": [b[1] for b in broken if b[3] == "none"][:2],
        "golden manifolds": len(golden),
        "golden mirror-broken": sorted(g for g in golden if g in {b[1] for b in broken}),
        "with a dualising isometry": sum(1 for r in rec["rows"] if r["dualising isometry"]),
        "rigid; fibre boundary rigid (record)": [rec["counts"]["rigid"], rec["counts"]["fibre boundary rigid"]],
    }
    out["passed"] = (out["states, manifolds"] == [758, 536] and out["the record lists every manifold"] and kinds_agree
                     and rule_on_every_isometry and broken_is_word_rule and state_counts_agree
                     and out["mirror-broken manifolds, per sign, states"] == [262, {"+": 131, "-": 131}, 482]
                     and out["by kind"] == {"none": 220, "swaprev only": 42}
                     and list(out["by length"].values()) == [2, 2, 8, 14, 36, 62, 138]
                     and out["first mirror-broken"] == ["+LLRLRR", "-LLRLRR"]
                     and out["first chiral"] == ["+LLLRLRR", "-LLLRLRR"]
                     and out["golden manifolds"] == 14
                     and out["golden mirror-broken"] == ["+LLLLRLLLRR", "+LLLLRLRRRLRR", "-LLLLRLLLRR", "-LLLLRLRRRLRR"]
                     and out["with a dualising isometry"] == 274
                     and out["rigid; fibre boundary rigid (record)"] == [536, 536])
    return out


# ------------------------------------------------------------------------------------------------ C4
def c4():
    rec = json.loads((ROOT / "frontier" / "B1524_the_bars_null_contract" / "verification" / "null_contract.json")
                     .read_text(encoding="utf-8"))
    bar = (ROOT / "docs" / "THE_BAR.md").read_text(encoding="utf-8")
    need = ("## The null contract (B1524, 2026-10-03)", "| **PASSED** |", "Then Bonferroni over every look",
            "PASSED is a rarity grade", "So PASSED is necessary for DERIVED and never sufficient",
            "never sufficient for it, never a physical admission")
    out = {"record: all checks pass": all(rec["checks"].values()) and len(rec["checks"]) == 7,
           "THE_BAR carries": {s: s in bar for s in need},
           "THE_BAR no longer grades DERIVED or corrects by Sidak": "| **DERIVED** |" not in bar
           and "Then Šidák over every look" not in bar}
    out["passed"] = out["record: all checks pass"] and all(out["THE_BAR carries"].values()) and \
        out["THE_BAR no longer grades DERIVED or corrects by Sidak"]
    return out


# ------------------------------------------------------------------------------------------------ C5
def c5(v15):
    relay = RELAY.read_text(encoding="utf-8")
    out = {"received copy sha-256": sha(RELAY) == SHA[RELAY.name]}
    try:
        blob = subprocess.run(["git", "-C", str(ROOT), "show",
                               "24c039c8:reports/physical_bridge_2026_09_05/relays/" + RELAY.name],
                              capture_output=True, check=True).stdout
        out["byte-identical to the audit lane's blob at 24c039c8"] = blob == RELAY.read_bytes()
    except (subprocess.CalledProcessError, FileNotFoundError):
        out["byte-identical to the audit lane's blob at 24c039c8"] = "not checkable: the commit is not in this clone"
    r = norm(relay)
    theirs = ("Please refine main GENESIS GAP3: our results do not prove 'a one-ended state can get the third only from a "
              "relation'.",
              "They prove a specified flat counted configuration needs an admitted source/end flux or a change of hypotheses.",
              "Whether a generated relation supplies it is still FK8/ FK12.",
              "R77's added fields do not settle their genesis origin.",
              "This retains the owner's act-with-register priority without installing its solution.")
    out["the relay says"] = {s: s in r for s in theirs}
    g = norm(v15[v15.index("- **GAP3, the source.**"):v15.index("- **GAP4, selection and coincidence.**")])
    ours = ("The audit lane's results do not prove that a one-ended state can get the third only from a relation.",
            "They prove that a specified flat counted configuration needs an admitted source or end flux, or a change of "
            "hypotheses.",
            "Whether a generated relation supplies it stays open (FK8, FK12), and R77's added fields do not settle their "
            "genesis origin.",
            "The audit lane refined main's v1.3 wording here (its relay at `24c039c8`); the refinement keeps the owner's "
            "act-and-register priority (FK12) without installing its solution.")
    out["v1.5's GAP3 says"] = {s: s in g for s in ours}
    out["v1.5 no longer asserts it"] = "A one-ended state can get the third only from a relation" not in v15
    out["passed"] = (out["received copy sha-256"] and out["byte-identical to the audit lane's blob at 24c039c8"] is not False
                     and all(out["the relay says"].values()) and all(out["v1.5's GAP3 says"].values())
                     and out["v1.5 no longer asserts it"])
    return out


# ------------------------------------------------------------------------------------------------ C6
EXPECTED_DELETIONS = [
    "1.4",
    "`frontier/B1456_genesis_v1_2_verified_and_the_seats_reconciled/received/GENESIS_v1_2.md`).",
    "sm:B1520)",
    "sign. A",
    "relation** (FK8).",
    "DERIVED,",
    "relation",
    "L241",
    "frame",
    "levels;",
    "root.",
]
Q5 = [base64.b64decode(t).decode() for t in ("cXVhbGlh", "YXdhcmU=", "c2Vlcw==")]   # Gate 5-Q's three words, encoded


def tables(text):
    """each table as a list of rows (a row: a line starting with '|'), split on blank or non-table lines"""
    out, cur = [], []
    for line in text.split("\n"):
        if line.startswith("|"):
            cur.append(line)
        elif cur:
            out.append(cur)
            cur = []
    if cur:
        out.append(cur)
    return out


def cells(row):
    return [c.strip() for c in row.strip().strip("|").split("|")]


def diff_report(v14, v15):
    """main's words deleted or re-punctuated (token diff), and the changed blocks of lines that carry no [v1.5] mark
    (the version line and §10's own entry excepted: log entries carry no mark)"""
    ta, tb = re.findall(r"\S+", v14), re.findall(r"\S+", v15)
    ops = difflib.SequenceMatcher(None, ta, tb, autojunk=False).get_opcodes()
    deleted = [" ".join(ta[i1:i2]) for op, i1, i2, j1, j2 in ops if op in ("replace", "delete")]
    la, lb = v14.split("\n"), v15.split("\n")
    unmarked = []
    for op, i1, i2, j1, j2 in difflib.SequenceMatcher(None, la, lb, autojunk=False).get_opcodes():
        if op == "equal" or j1 == j2:
            if op != "equal":
                unmarked.append((j1 + 1, ["(lines of v1.4 removed)"] + la[i1:i1 + 1]))
            continue
        block = lb[j1:j2]
        version_line = j1 < 3 and i1 < len(la) and "** " in la[i1] and \
            block == ["**Version 1.5 · 2026-10-03 · canonical.** " + la[i1].split("** ", 1)[1]]
        log_entry = block[0].startswith("- **v1.5 · 2026-10-03 · sm:B1525.**")
        if not any(MARK in b for b in block) and not version_line and not log_entry:
            unmarked.append((j1 + 1, block[:1]))
    return deleted, unmarked


def c6():
    v14 = V14.read_text(encoding="utf-8")
    with tempfile.TemporaryDirectory() as tmp:
        gen = Path(tmp) / "v15.md"
        subprocess.run([sys.executable, str(HERE / "merge_genesis_v15.py"), str(V14), str(gen)], check=True,
                       capture_output=True)
        v15 = gen.read_text(encoding="utf-8")
    cur = (ROOT / "GENESIS.md").read_text(encoding="utf-8")
    out = {"received sha-256": {p.name: sha(p) == SHA[p.name] for p in (V14, V13)},
           "sha-256 of the generated v1.5": hashlib.sha256(v15.encode("utf-8")).hexdigest(),
           "GENESIS.md is the generated v1.5": cur == v15}
    deleted, unmarked = diff_report(v14, v15)
    out["main's words deleted or re-punctuated"] = deleted
    out["exactly the listed edits"] = deleted == EXPECTED_DELETIONS
    out["changed blocks without a mark"] = unmarked
    # marks and sections
    out["earlier marks unchanged"] = {m: [v14.count(m), v15.count(m)] for m in
                                      ("**[v1.1]**", "**[v1.2]**", "**[v1.3]**", "**[v1.4]**")}
    out["[v1.5] marks"] = v15.count(MARK)
    heads = [h for h in re.findall(r"(?m)^## (\d+)\. ", v15)]
    out["sections in order"] = heads == [str(i) for i in range(11)] and \
        re.findall(r"(?m)^## .*$", v15) == re.findall(r"(?m)^## .*$", v14)
    # tables well formed; statuses kept
    bad = []
    for t in tables(v15):
        n = len(cells(t[0]))
        bad += [r[:60] for r in t if len(cells(r)) != n]
    out["malformed table rows"] = bad
    rows14 = [r for t in tables(v14) for r in t]
    rows15 = [r for t in tables(v15) for r in t]
    by_first15 = {cells(r)[0]: r for r in rows15}
    changed = []
    for r in rows14:
        if r in rows15:
            continue
        r15 = by_first15.get(cells(r)[0])
        c14, c15 = cells(r), cells(r15) if r15 else []
        changed.append({"row": c14[0][:40], "kept leading cells": bool(r15) and c15[:3] == c14[:3]
                        and len(c15) == len(c14), "marked": bool(r15) and MARK in r15})
    out["v1.4 rows changed (leading cells kept, marked)"] = changed
    new_rows = [cells(r)[0][:50] for r in rows15 if r not in rows14 and cells(r)[0] not in {cells(x)[0] for x in rows14}]
    out["rows new in v1.5"] = new_rows
    fk = {cells(r)[0]: cells(r)[2] for r in rows15 if re.fullmatch(r"FK\d+( \*\*\[v1\.2\]\*\*)?", cells(r)[0])}
    fk14 = {cells(r)[0]: cells(r)[2] for r in rows14 if re.fullmatch(r"FK\d+( \*\*\[v1\.2\]\*\*)?", cells(r)[0])}
    out["fork statuses unchanged"] = fk == fk14 and len(fk) == 12
    # hygiene, with the check shown able to fire
    tokens = [base64.b64decode(t).decode() for t in ("Y2xhdWRl", "YW50aHJvcGlj", "b3B1cw==", "c29ubmV0", "ZmFibGU=")]
    private = bytes([98, 114, 97, 118, 101]).decode()

    def q5(text):
        """Q5's words found, by their place in Q5's list (1-3), so the record never writes them"""
        return [i + 1 for i, w in enumerate(Q5) if re.search(r"\b" + w + r"\b", text, re.I)]
    out["Q5's words found, by place in its list: v1.5, v1.4, the SM seat's v1.3"] = [
        q5(v15), q5(v14), q5(V13.read_text(encoding="utf-8"))]
    out["vendor words or the private term in v1.5"] = [w for w in tokens if re.search(re.escape(w), v15, re.I)] + \
        ([private] if private in v15.lower() else [])
    out["passed"] = (all(out["received sha-256"].values()) and out["exactly the listed edits"] and not unmarked
                     and all(a == b for a, b in out["earlier marks unchanged"].values()) and out["[v1.5] marks"] == 16
                     and out["sections in order"] and not bad
                     and len(changed) == 4 and all(c["kept leading cells"] and c["marked"] for c in changed)
                     and len(new_rows) == 4 and out["fork statuses unchanged"]
                     and out["Q5's words found, by place in its list: v1.5, v1.4, the SM seat's v1.3"] == [[], [], [3]]
                     and not out["vendor words or the private term in v1.5"])
    return out, v15


def main():
    t0 = time.time()
    res = {}
    res["C1 sm:B1521's checks re-run"] = c1()
    res["C2 the levels (sm:B1522), a third route"] = c2()
    res["C3 the word states (sm:B1523), own word code"] = c3()
    res["C4 the bar's null contract (sm:B1524)"] = c4()
    c6res, v15 = c6()
    res["C5 the audit lane's GAP3 refinement"] = c5(v15)
    res["C6 v1.5 against main's v1.4"] = c6res
    res["checks"] = {k.split(" ")[0]: v["passed"] for k, v in res.items() if isinstance(v, dict) and "passed" in v}
    res["GENESIS.md is the generated v1.5"] = c6res["GENESIS.md is the generated v1.5"]
    res["seconds"] = round(time.time() - t0, 1)
    (HERE / "genesis_v15_checks.json").write_text(json.dumps(res, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps(res, indent=1, ensure_ascii=False))
    print("ALL CHECKS PASS" if all(res["checks"].values()) else "A CHECK FAILED", res["checks"],
          "| GENESIS.md is the generated v1.5:", res["GENESIS.md is the generated v1.5"])


if __name__ == "__main__":
    main()
