#!/usr/bin/env python3
"""R07 blind recompute, part 3 — knot-group side of B955.

Claims to check:
 (1) H1(m004) = Z (knot complement abelianization is infinite cyclic).
     Recomputed two ways: snappy homology, and my own Smith-normal-form of the
     abelianized relator matrix from the fundamental-group presentation.
 (2) THEOREM: every quotient of a group with cyclic abelianization has cyclic
     abelianization (surjection G->>Q induces surjection G^ab ->> Q^ab).
     Checked concretely: brute-force enumeration of homs pi_1(m004) -> Z3 x Z3:
     expect ZERO surjective.
 (3) CONTROL (instrument can find planted non-abelian images): banked claim
     says A4, D5, S5 images of pi_1(m004) exist. Brute-force homs into A4,
     D5 (dihedral order 10), S5; count surjective ones. Expect > 0 for each.
"""
import itertools
from sympy import Matrix
from sympy.matrices.normalforms import smith_normal_form
import snappy

M = snappy.Manifold("m004")
G = M.fundamental_group()
gens = G.generators()
rels = G.relators()
print(f"[1] m004 pi_1 presentation: gens {gens}, relators {rels}")
print(f"[1] snappy homology: {M.homology()}")

# my own abelianization via SNF
def exponent_vector(word, gens):
    v = [0]*len(gens)
    idx = {g: i for i, g in enumerate(gens)}
    for ch in word:
        lo = ch.lower()
        v[idx[lo]] += 1 if ch.islower() else -1
    return v

Rel = Matrix([exponent_vector(r, gens) for r in rels])
snf = smith_normal_form(Rel)
print(f"[1] relator exponent matrix: {Rel.tolist()}")
print(f"[1] Smith normal form: {snf.tolist()}")
# abelianization = Z^g / rowspace; invariant factors from SNF
diag = [snf[i, i] for i in range(min(snf.shape))]
nonzero = [d for d in diag if d != 0]
free_rank = len(gens) - len(nonzero)
tors = [d for d in nonzero if abs(d) != 1]
print(f"[1] MY abelianization: Z^{free_rank} x " +
      ("x".join(f"Z/{abs(d)}" for d in tors) if tors else "(no torsion)"))
assert free_rank == 1 and not tors, "H1(m004) != Z ?!"
print("[1] H1(m004) = Z  CONFIRMED (independent SNF computation)")

# theorem check (symbolic reasoning stated, concrete verification below):
print("[2] Theorem: G ->> Q surjective => G^ab ->> Q^ab surjective; Z ->> cyclic only.")

def hom_search(group_elems, mult, inv, identity, gens, rels, elems_list):
    """Enumerate maps gens -> group; keep those satisfying all relators.
    Returns (n_homs, n_surjective)."""
    def ev(word, assign):
        x = identity
        for ch in word:
            g = assign[ch.lower()]
            x = mult(x, g if ch.islower() else inv(g))
        return x
    n_h = n_s = 0
    for combo in itertools.product(elems_list, repeat=len(gens)):
        assign = dict(zip(gens, combo))
        if all(ev(r, assign) == identity for r in rels):
            n_h += 1
            # subgroup generated by images
            S = {identity}
            frontier = set(combo)
            S |= frontier
            while frontier:
                new = set()
                for a in S:
                    for b in list(frontier):
                        for c in (mult(a, b), mult(b, a)):
                            if c not in S:
                                new.add(c)
                S |= new
                frontier = new
            if len(S) == len(group_elems):
                n_s += 1
    return n_h, n_s

# --- permutation-group machinery (tuples as permutations) ---
def perm_mult(p, q):  # (p*q)(i) = p[q[i]]
    return tuple(p[i] for i in q)
def perm_inv(p):
    r = [0]*len(p)
    for i, v in enumerate(p):
        r[v] = i
    return tuple(r)

def sym(n):
    return [tuple(p) for p in itertools.permutations(range(n))]
def is_even(p):
    seen = [False]*len(p); parity = 0
    for i in range(len(p)):
        if not seen[i]:
            j = i; ln = 0
            while not seen[j]:
                seen[j] = True; j = p[j]; ln += 1
            parity ^= (ln - 1) & 1
    return parity == 0

S4 = sym(4); A4 = [p for p in S4 if is_even(p)]
S5 = sym(5)
# dihedral of order 10 as permutations of Z5: x -> x+1, x -> -x
D5 = []
for a in range(5):
    D5.append(tuple((i + a) % 5 for i in range(5)))       # rotations
    D5.append(tuple((-i + a) % 5 for i in range(5)))      # reflections
D5 = list(dict.fromkeys(D5))
assert len(D5) == 10

# Z3 x Z3 as additive pairs
Z33 = [(a, b) for a in range(3) for b in range(3)]
def z33_mult(x, y): return ((x[0]+y[0]) % 3, (x[1]+y[1]) % 3)
def z33_inv(x): return ((-x[0]) % 3, (-x[1]) % 3)

n_h, n_s = hom_search(Z33, z33_mult, z33_inv, (0, 0), gens, rels, Z33)
print(f"[2] homs pi_1(m004) -> Z3xZ3: {n_h} total, {n_s} surjective  (claim: 0 surjective)")
assert n_s == 0

ident4 = tuple(range(4)); ident5 = tuple(range(5))
n_h, n_s = hom_search(A4, perm_mult, perm_inv, ident4, gens, rels, A4)
print(f"[3] CONTROL homs -> A4:  {n_h} total, {n_s} surjective  (claim: >0)")
a4_surj = n_s
n_h, n_s = hom_search(D5, perm_mult, perm_inv, ident5, gens, rels, D5)
print(f"[3] CONTROL homs -> D5 (order 10): {n_h} total, {n_s} surjective  (claim: >0)")
d5_surj = n_s
n_h, n_s = hom_search(S5, perm_mult, perm_inv, ident5, gens, rels, S5)
print(f"[3] CONTROL homs -> S5:  {n_h} total, {n_s} surjective  (claim: >0)")
s5_surj = n_s
# also check the D5 image is consistent with cyclic abelianization:
# D5^ab = Z2 (cyclic) — fine; Z3xZ3^ab = Z3xZ3 (non-cyclic) — excluded. A4^ab = Z3 cyclic. S5^ab = Z2 cyclic.
print("[3] consistency: A4^ab=Z3, D5^ab=Z2, S5^ab=Z2 all cyclic (allowed); (Z3xZ3)^ab non-cyclic (forbidden)")
print(f"[done] surjective counts: Z3xZ3=0, A4={a4_surj}, D5={d5_surj}, S5={s5_surj}")
