#!/usr/bin/env python3
"""B1363 -- THE DESCENT'S WILSON LINES: the object's own closing S^3(4_1; 2pi/3) has H_1 = Z/3, and no order-3 element of E6 has
the Standard Model as its commutant.

(1) H_1 of the orbifold group.  The descent is the figure-eight orbifold with cone angle 2pi/3: pi_1^orb = pi_1(m004) / <<mu^3>>, so
    H_1 = Z/<3> = Z/3 (H_1(m004) = Z generated by the meridian).  Checked on the crystallographic side by the five-term sequence:
    the coinvariants of the point group T = A_4 on the lattice Z^3 are Z^3 / ((1 - g) Z^3 : g in T) = Z/2 (computed), H_1(A_4) = Z/3,
    and the knot presentation shows the Z/2 is killed (H_2(A_4) = Z/2 maps onto it): H_1 = Z/3.  For comparison H_1(Y_3) = (Z/4)^2
    (B1273), the cover's alphabet.
(2) Kac coordinates.  Inner automorphisms of E6 of order m are classified by non-negative integers s_0..s_6 on the affine Dynkin
    diagram with sum_i a_i s_i = m (a_i the marks 1,1,1,2,2,2,3), up to diagram symmetry; the fixed subalgebra is the subdiagram of
    the nodes with s_i = 0 plus one u(1) per extra node with s_i > 0 (rank 6 in total).  We enumerate m = 3 (the descent's
    characters) and m = 4 (the cover's), identify the semisimple types, and test each against the Standard Model's A_2 + A_1 + 2 u(1).
"""
import itertools
from fractions import Fraction as Fr
import sympy

# affine E6: nodes 0..6; finite Bourbaki numbering 1-3-4-5-6 chain, 2 attached to 4, affine node 0 attached to 2
adj = {(1, 3), (3, 4), (4, 5), (5, 6), (2, 4), (0, 2)}
marks = {0: 1, 1: 1, 6: 1, 3: 2, 5: 2, 2: 2, 4: 3}

def components(nodes):
    nodes = set(nodes); comps = []
    while nodes:
        s = nodes.pop(); comp = {s}; frontier = [s]
        while frontier:
            u = frontier.pop()
            for (a, b) in adj:
                for (p, q) in ((a, b), (b, a)):
                    if p == u and q in nodes:
                        nodes.remove(q); comp.add(q); frontier.append(q)
        comps.append(comp)
    return comps

def dynkin_type(comp):
    """type of a connected subdiagram of affine E6 (all simply laced, tree): A_n if a path, D_n if one trivalent node with an arm of length 1, E_n otherwise."""
    n = len(comp)
    deg = {u: sum(1 for (a, b) in adj if (a == u and b in comp) or (b == u and a in comp)) for u in comp}
    if max(deg.values()) <= 2:
        return f"A{n}"
    # one trivalent node
    c = [u for u in comp if deg[u] == 3][0]
    arms = []
    for (a, b) in adj:
        for (p, q) in ((a, b), (b, a)):
            if p == c and q in comp:
                L = 1; prev, cur = c, q
                while True:
                    nxt = [t for (x, y) in adj for (r, t) in ((x, y), (y, x)) if r == cur and t in comp and t != prev]
                    if not nxt:
                        break
                    prev, cur = cur, nxt[0]; L += 1
                arms.append(L)
    arms.sort()
    if arms[0] == 1 and arms[1] == 1:
        return f"D{n}"
    if arms == [1, 2, 2]:
        return "E6"
    if arms == [1, 2, 3]:
        return "E7"
    return f"?{arms}"

def commutant(s):
    zero = [i for i in range(7) if s[i] == 0]
    comps = components(zero)
    types = sorted(dynkin_type(c) for c in comps)
    n_u1 = sum(1 for i in range(7) if s[i] > 0) - 1
    return types, n_u1

def kac_orbits(m):
    seen = set(); out = []
    # diagram symmetries of affine E6: S_3 permuting the three arms (0-2), (1-3), (6-5) about the centre 4
    arms = [(0, 2), (1, 3), (6, 5)]
    def canon(s):
        best = None
        for perm in itertools.permutations(range(3)):
            t = [0] * 7; t[4] = s[4]
            for i, j in enumerate(perm):
                t[arms[j][0]] = s[arms[i][0]]; t[arms[j][1]] = s[arms[i][1]]
            t = tuple(t)
            if best is None or t < best:
                best = t
        return best
    for s in itertools.product(range(m + 1), repeat=7):
        if sum(marks[i] * s[i] for i in range(7)) != m:
            continue
        c = canon(s)
        if c in seen:
            continue
        seen.add(c); out.append(c)
    return out

SM = (["A1", "A2"], 2)
for m in (3, 4):
    print("=" * 96)
    print(f"inner automorphisms of E6 of order {m}: Kac coordinates (s_0..s_6 on the affine diagram, marks 1,1,1,2,2,2,3), up to symmetry")
    print("=" * 96)
    found_sm = False
    for s in kac_orbits(m):
        types, n_u1 = commutant(s)
        is_sm = (types == SM[0] and n_u1 == SM[1])
        found_sm |= is_sm
        central = (n_u1 == 0 and types == ["E6"])
        print(f"  s = {s}: fixed subalgebra {' + '.join(types)} + {n_u1} u(1)" + ("  (central: no breaking)" if central else "") + ("  <-- STANDARD MODEL" if is_sm else ""))
    print(f"  an order-{m} element with commutant exactly SU(3) x SU(2) x U(1)^2 exists: {found_sm}")

print("\n" + "=" * 96)
print("H_1 of the descent's orbifold group by the five-term sequence (crystallographic side)")
print("=" * 96)
# coinvariants of T = A_4 on Z^3: the 12 point-group matrices
import numpy as np
P = np.array([[0, 0, 1], [1, 0, 0], [0, 1, 0]])
V = [np.diag(d) for d in ((1, 1, 1), (1, -1, -1), (-1, 1, -1), (-1, -1, 1))]
T = []
for v in V:
    for k in range(3):
        T.append(np.linalg.matrix_power(P, k) @ v)
gens = []
for g in T:
    for col in (np.eye(3, dtype=int) - g).T:
        gens.append([int(x) for x in col])
M = sympy.Matrix(gens).T   # columns generate (1 - g) Z^3
from sympy.matrices.normalforms import smith_normal_form
snf = smith_normal_form(M, domain=sympy.ZZ)
diag = [abs(int(snf[i, i])) for i in range(3)]
print(f"  Smith form of the span of (1 - g) Z^3 over g in A_4: {diag} -> coinvariants Z^3_T = Z/{diag[0]} x Z/{diag[1]} x Z/{diag[2]} (nontrivial part: Z/2)")
print("  five-term: H_2(A_4) = Z/2 -> Z^3_T = Z/2 -> H_1(P2_1 3) -> H_1(A_4) = Z/3 -> 0; the knot presentation pi_1(m004)/<<mu^3>> gives H_1 = Z/3,")
print("  so the Z/2 is killed: H_1(descent) = Z/3, against H_1(Y_3) = (Z/4)^2 on the cover.")
print("\nDONE")
