#!/usr/bin/env python3
"""R09 blind recomputation: scale cluster.

(a) Hom(G, R+) = 0 for the six banked groups: constructed from scratch,
    orders + abelianizations computed by brute-force group theory.
(b) Vol(m004) to 50 dps two independent ways + snappy cross-check + CS.
(c) c = 6*sigma both ways (Brown-Henneaux algebra; Sugawara for (E6)_1
    with h_dual(E6) recomputed from a from-scratch E6 root system).

No file from the arc's verification/ or tests/ was read before this ran.
"""
import itertools, json
from fractions import Fraction

import mpmath as mp
import sympy as sp

OUT = {}

# ----------------------------------------------------------------------
# Generic finite-group machinery over hashable elements
# ----------------------------------------------------------------------

def closure(gens, mul):
    """BFS closure of generators under multiplication."""
    elems = set(gens)
    frontier = list(gens)
    while frontier:
        new = []
        for a in frontier:
            for g in gens:
                p = mul(a, g)
                if p not in elems:
                    elems.add(p)
                    new.append(p)
        frontier = new
    return elems

def commutator_subgroup(elems, mul, inv):
    """[G,G] as closure of all commutators (feasible for our sizes)."""
    elems = list(elems)
    comms = set()
    for a in elems:
        ia = inv(a)
        for b in elems:
            comms.add(mul(mul(a, b), mul(ia, inv(b))))
    return closure(comms, mul)

# ---- matrix groups over Z/n as tuples --------------------------------

def mat_mul_mod(n):
    def mul(A, B):
        (a, b, c, d), (e, f, g, h) = A, B
        return ((a*e + b*g) % n, (a*f + b*h) % n,
                (c*e + d*g) % n, (c*f + d*h) % n)
    return mul

def mat_inv_mod(n):
    def inv(A):
        a, b, c, d = A
        det = (a*d - b*c) % n
        di = pow(det, -1, n)
        return ((d*di) % n, (-b*di) % n, (-c*di) % n, (a*di) % n)
    return inv

def SL2(n):
    els = set()
    for a, b, c, d in itertools.product(range(n), repeat=4):
        if (a*d - b*c) % n == 1:
            els.add((a, b, c, d))
    return els

def group_report(name, elems, mul, inv):
    order = len(elems)
    D = commutator_subgroup(elems, mul, inv)
    ab_order = order // len(D)
    # Hom(G, R+): R+ is torsion-free abelian, so Hom(G,R+) = Hom(G^ab, R+);
    # G^ab is finite (order ab_order), every element has finite order,
    # and the only finite-order element of R+ is 1.  Hence Hom = 0.
    # The computational content we verify: G is finite and G^ab is finite.
    rep = dict(order=order, derived_order=len(D), abelianization_order=ab_order,
               hom_to_Rplus="0 (finite group -> torsion-free R+)")
    OUT.setdefault("groups", {})[name] = rep
    print(f"{name:16s} |G|={order:6d}  |[G,G]|={len(D):6d}  |G^ab|={ab_order}")
    return rep

print("=== (a) the six groups ===")

# Klein four = Gal(L/Q(i)): elements of (Z/2)^2
kmul = lambda a, b: ((a[0]+b[0]) % 2, (a[1]+b[1]) % 2)
kinv = lambda a: a
klein = closure({(1, 0), (0, 1)}, kmul)
group_report("Gal(L/Q(i))", klein, kmul, kinv)

# 2I = binary icosahedral = SL(2,5)
m5, i5 = mat_mul_mod(5), mat_inv_mod(5)
sl25 = SL2(5)
group_report("2I=SL(2,5)", sl25, m5, i5)

# PSL(2,7): SL(2,7) mod {+-1}; represent by canonical coset rep
m7, i7 = mat_mul_mod(7), mat_inv_mod(7)
def canon7(A):
    B = tuple((-x) % 7 for x in A)
    return min(A, B)
pmul = lambda A, B: canon7(m7(A, B))
pinv = lambda A: canon7(i7(A))
psl27 = {canon7(A) for A in SL2(7)}
group_report("PSL(2,7)", psl27, pmul, pinv)

# 2I x Z/3
m3mul = lambda a, b: (m5(a[0], b[0]), (a[1] + b[1]) % 3)
m3inv = lambda a: (i5(a[0]), (-a[1]) % 3)
prod = {(g, z) for g in sl25 for z in range(3)}
group_report("2I x Z/3", prod, m3mul, m3inv)

# SL(2, Z/15)
m15, i15 = mat_mul_mod(15), mat_inv_mod(15)
sl215 = SL2(15)
group_report("SL(2,Z/15)", sl215, m15, i15)
# CRT sanity: |SL(2,15)| should equal |SL(2,3)|*|SL(2,5)|
assert len(sl215) == len(SL2(3)) * len(sl25)

# W(E6): generated by simple reflections in the root basis (integer matrices).
# Cartan matrix of E6 (Bourbaki numbering).
E6_CARTAN = [
    [ 2,  0, -1,  0,  0,  0],
    [ 0,  2,  0, -1,  0,  0],
    [-1,  0,  2, -1,  0,  0],
    [ 0, -1, -1,  2, -1,  0],
    [ 0,  0,  0, -1,  2, -1],
    [ 0,  0,  0,  0, -1,  2],
]
A = E6_CARTAN
n = 6
# simple reflection s_i acts on root coordinates x (v = sum x_j alpha_j):
# s_i(alpha_j) = alpha_j - A[i][j] alpha_i  => (s_i x)_k = x_k - delta_{k,i} * sum_j A[i][j] x_j
def refl_matrix(i):
    M = [[1 if r == c else 0 for c in range(n)] for r in range(n)]
    for j in range(n):
        M[i][j] -= A[i][j]
    return tuple(tuple(r) for r in M)

def mmul6(X, Y):
    return tuple(tuple(sum(X[r][k]*Y[k][c] for k in range(n)) for c in range(n))
                 for r in range(n))

gens6 = [refl_matrix(i) for i in range(n)]
we6 = closure(set(gens6), mmul6)
order_we6 = len(we6)
print(f"W(E6)            |G|={order_we6}")
# abelianization of a Weyl group with connected diagram: all reflections
# conjugate => G^ab = Z/2 (determinant).  Verify via commutators of generators
# closure (full commutator set too big; use normal closure of gen commutators,
# which equals [G,G] since G is generated by gens):
def minv6(M):
    # all elements have finite order; find inverse by power (order divides |G|)
    X = M
    prev = None
    ident = tuple(tuple(1 if r == c else 0 for c in range(n)) for r in range(n))
    while X != ident:
        prev = X
        X = mmul6(X, M)
    return prev if prev is not None else ident
# [G,G] = normal closure of {[gi,gj]}; compute by conjugating and closing
comms = set()
for gi in gens6:
    for gj in gens6:
        comms.add(mmul6(mmul6(gi, gj), mmul6(minv6(gi), minv6(gj))))
# normal closure: close under multiplication and conjugation by generators
D = set(comms)
frontier = list(comms)
while frontier:
    newf = []
    for x in frontier:
        cands = [mmul6(x, y) for y in comms]
        for g in gens6:
            cands.append(mmul6(mmul6(g, x), minv6(g)))
        for c in cands:
            if c not in D:
                D.add(c); newf.append(c)
    # also close under multiplication within D (approximate by re-closing at end)
    frontier = newf
D = closure(D, mmul6)
ab_we6 = order_we6 // len(D)
print(f"W(E6)            |[G,G]|={len(D)}  |G^ab|={ab_we6}")
OUT["groups"]["W(E6)"] = dict(order=order_we6, derived_order=len(D),
                              abelianization_order=ab_we6,
                              hom_to_Rplus="0 (finite group -> torsion-free R+)")

# ----------------------------------------------------------------------
# (b) Vol(m004) to 50 dps, two ways
# ----------------------------------------------------------------------
print("\n=== (b) Vol(m004) ===")
mp.mp.dps = 60

def lobachevsky(theta):
    """Lambda(theta) = -int_0^theta log|2 sin t| dt = (1/2) Im Li2(e^{2 i theta})."""
    return mp.im(mp.polylog(2, mp.e**(2j*theta))) / 2

# independent series check of Lambda(pi/6): sum sin(2 n theta)/(2 n^2)
def lob_series(theta, N=200000):
    return mp.nsum(lambda k: mp.sin(2*k*theta)/(2*k**2), [1, mp.inf])

L6 = lobachevsky(mp.pi/6)
L6s = lob_series(mp.pi/6)
assert mp.almosteq(L6, L6s, abs_eps=mp.mpf(10)**-55), (L6, L6s)

vol_way1 = 4 * L6      # regular ideal tetrahedron = 2*Lambda(pi/6); m004 = 2 tets
print("way1  4*Lambda(pi/6)          =", mp.nstr(vol_way1, 51))

# way 2: 9*sqrt(3)*zeta_K(2)/pi^2, K = Q(sqrt-3), computed via
# zeta_K(s) = zeta(s) * L(s, chi_-3), L(s,chi_-3) = 3^-s (zeta(s,1/3) - zeta(s,2/3))
Lchi = 3**mp.mpf(-2) * (mp.zeta(2, mp.mpf(1)/3) - mp.zeta(2, mp.mpf(2)/3))
# independent slow check of L(2, chi_-3)
Lchi_slow = mp.nsum(lambda k: (1 if k % 3 == 1 else (-1 if k % 3 == 2 else 0))/mp.mpf(k)**2,
                    [1, mp.inf])
assert mp.almosteq(Lchi, Lchi_slow, abs_eps=mp.mpf(10)**-40)
zetaK2 = mp.zeta(2) * Lchi
vol_way2 = 9 * mp.sqrt(3) * zetaK2 / mp.pi**2
print("way2  9*sqrt3*zetaK(2)/pi^2   =", mp.nstr(vol_way2, 51))
diff12 = abs(vol_way1 - vol_way2)
print("  |way1-way2| =", mp.nstr(diff12, 3))

banked = mp.mpf("2.029883212819307250042405108549")
print("banked (30 dps)               =", mp.nstr(banked, 31))
print("  |way1-banked| =", mp.nstr(abs(vol_way1 - banked), 3))

OUT["vol_m004"] = dict(
    way1_4Lambda_pi6=mp.nstr(vol_way1, 51),
    way2_9sqrt3_zetaK2_over_pi2=mp.nstr(vol_way2, 51),
    agree_between_ways=str(diff12 < mp.mpf(10)**-55),
    banked="2.029883212819307250042405108549",
    L_chi_minus3_2=mp.nstr(Lchi, 51),
)

# snappy cross-check + Chern-Simons
import snappy
M = snappy.Manifold("m004")
vol_snappy = M.volume()
cs = M.chern_simons()
print("snappy Vol(m004) =", vol_snappy, "  CS =", cs)
Mh = M.high_precision()
vol_hp = Mh.volume()
cs_hp = Mh.chern_simons()
print("snappy high-precision Vol =", vol_hp)
print("snappy high-precision CS  =", cs_hp)
OUT["snappy"] = dict(vol=str(vol_hp), cs=str(cs_hp),
                     cs_convention="snappy chern_simons(): CS mod 1/2 in units where "
                                   "vol+i*2*pi^2*cs is the complex volume")

# ----------------------------------------------------------------------
# (c) c = 6*sigma both ways
# ----------------------------------------------------------------------
print("\n=== (c) c = 6*sigma ===")
l, G, sigma = sp.symbols("l G sigma", positive=True)
c_BH = 3*l/(2*G)
c_sub = sp.simplify(c_BH.subs(G, l/(4*sigma)))
print("Brown-Henneaux c = 3l/(2G), G = l/(4 sigma)  =>  c =", c_sub)
assert c_sub == 6*sigma
OUT["brown_henneaux"] = str(c_sub)

# E6 root system from scratch: close simple roots under simple reflections
def refl_coord(x, i):
    s = sum(A[i][j]*x[j] for j in range(n))
    y = list(x)
    y[i] -= s
    return tuple(y)

simple = [tuple(1 if j == i else 0 for j in range(n)) for i in range(n)]
roots = set(simple)
frontier = list(simple)
while frontier:
    newf = []
    for r in frontier:
        for i in range(n):
            rr = refl_coord(r, i)
            if rr not in roots:
                roots.add(rr); newf.append(rr)
    frontier = newf
nroots = len(roots)          # should be 72 (positive+negative)
dim_e6 = nroots + n          # 78
highest = max((r for r in roots), key=lambda r: sum(r))
height_h = sum(highest)       # coefficients of highest root
coxeter_h = height_h + 1      # h = height(highest root) + 1
# dual Coxeter number: 1 + sum of comarks; E6 simply-laced => comarks = marks
h_dual = 1 + sum(highest)
print(f"#roots={nroots}  dim E6={dim_e6}  highest root coeffs={highest}")
print(f"Coxeter h={coxeter_h}  dual Coxeter h_dual={h_dual}")
assert nroots == 72 and dim_e6 == 78 and h_dual == 12
# cross-check: for simply-laced, h = #roots/rank
assert nroots // n == coxeter_h == 12

k = 1
c_sugawara = Fraction(dim_e6 * k, k + h_dual)
print(f"Sugawara c((E6)_1) = {dim_e6}*{k}/({k}+{h_dual}) = {c_sugawara} = {float(c_sugawara)}")
assert c_sugawara == 6
OUT["sugawara"] = dict(dim=dim_e6, h_dual=h_dual, k=1, c=str(c_sugawara))
# so c = 6 = 6*sigma with sigma = 1 (deficiency/defect count sigma=1) -- algebraic identity c=6 verified

with open("/home/user/origin-axiom/reports/fresh_physics_seat_2026-09-01/recompute/R09_scale_cluster/blind_output.json", "w") as f:
    json.dump(OUT, f, indent=2)
print("\nwrote blind_output.json")
