#!/usr/bin/env python3
"""B1497 -- every connected cover of a word state to degree D, with its fibration structure read from the permutation
representation: base degree k (the orbits of the fibre group), fibre degree d/k, the fibre's punctures (orbits of the
puncture loop on one fibre orbit), the fibre genus g = (2 + d/k - punctures)/2, the cover's cusps, b1, and the room at the
trivial line n(1) = b1 - cusps.  The fibre group = the kernel of the base map pi_1 -> Z (generated by the generators of
t-exponent 0 and the conjugates of the others' combinations); the puncture loop = the peripheral combination with
t-exponent 0.  Subgroups by sympy's low-index algorithm; covers built by SnapPy's cover(perms) (the coset table's right
action; checked against SnapPy's own covers(d) homologies).  Usage: fibre_census.py <name> <D>"""
import sys, json, math, pathlib, itertools, collections
import snappy, sympy as sp
from sympy.combinatorics.free_groups import free_group
from sympy.combinatorics.fp_groups import FpGroup, low_index_subgroups
from sympy.matrices.normalforms import smith_normal_decomp
HERE = pathlib.Path(__file__).resolve().parent


def exp_vec(w, gens): return [sum((1 if ch.islower() else -1) for ch in w if ch.lower() == g) for g in gens]


def base_map(G):
    gens = G.generators(); E = sp.Matrix([exp_vec(r, gens) for r in G.relators()]); S, U, V = smith_normal_decomp(E, sp.ZZ)
    n = len(gens); d = [int(S[i, i]) if i < min(S.shape) else 0 for i in range(n)]; free = [i for i in range(n) if d[i] == 0]
    assert len(free) == 1; i0 = free[0]; return gens, [int(V[j, i0]) for j in range(n)]


def word_perm(w, gens, perms, d):
    """the permutation of the cosets induced by a word (right action: apply letters left to right)"""
    p = list(range(d))
    for ch in w:
        j = gens.index(ch.lower()); q = perms[j] if ch.islower() else inverse(perms[j])
        p = [q[x] for x in p]
    return p


def inverse(p):
    q = [0] * len(p)
    for i, x in enumerate(p): q[x] = i
    return q


def orbits(perm_list, d):
    seen = [False] * d; out = []
    for s in range(d):
        if seen[s]: continue
        orb = {s}; frontier = [s]; seen[s] = True
        while frontier:
            x = frontier.pop()
            for p in perm_list:
                for y in (p[x], inverse(p)[x]):
                    if not seen[y]: seen[y] = True; orb.add(y); frontier.append(y)
        out.append(sorted(orb))
    return out


def census(name, D):
    M = snappy.Manifold(name); G = M.fundamental_group(); gens, exps = base_map(G); rels = G.relators(); (mu, lam) = G.peripheral_curves()[0]
    emu, elam = sum(e * x for e, x in zip(exps, exp_vec(mu, gens))), sum(e * x for e, x in zip(exps, exp_vec(lam, gens)))
    g_ = math.gcd(abs(emu), abs(elam)); a_, b_ = (-elam // g_, emu // g_)            # puncture loop = mu^a lam^b with t-exponent 0
    puncture = (mu if a_ > 0 else "".join(ch.swapcase() for ch in reversed(mu))) * abs(a_) + (lam if b_ > 0 else "".join(ch.swapcase() for ch in reversed(lam))) * abs(b_)
    assert sum(e * x for e, x in zip(exps, exp_vec(puncture, gens))) == 0
    # fibre group generators (enough for orbits): generators with exponent 0, and for the others g_i g_j^-1-type words with zero exponent, conjugated by t-powers
    zero = [g for g, e in zip(gens, exps) if e == 0]; tgen = [g for g, e in zip(gens, exps) if e != 0]
    fibre_words = list(zero)
    for i, g in enumerate(tgen):
        for h in tgen[i + 1:]:
            ei, eh = exps[gens.index(g)], exps[gens.index(h)]; fibre_words.append(g * eh + "".join(ch.swapcase() for ch in h) * ei)   # g^eh h^-ei
    conj = []
    for w in fibre_words:
        for k in range(0, D + 1):
            t = tgen[0]; conj.append(t * k + w + t.swapcase() * k); conj.append(t.swapcase() * k + w + t * k)
    F, *fg = free_group(" ".join(gens)); fp = FpGroup(F, [sp.sympify(0)] if False else [])
    # build sympy relators
    gen_syms = dict(zip(gens, fg))
    def to_word(w):
        out = None
        for ch in w:
            x = gen_syms[ch.lower()] if ch.islower() else gen_syms[ch.lower()] ** -1
            out = x if out is None else out * x
        return out
    fp = FpGroup(F, [to_word(r) for r in rels])
    rows = []
    all_tables = low_index_subgroups(fp, D)
    for d in range(1, D + 1):
        reps = []
        for T in all_tables:
            ct = T.table; n = len(ct)
            if n != d: continue
            # ct[i] = [image of coset i under g1, g1^-1, g2, g2^-1, ...]
            perms = [[ct[i][2 * j] for i in range(n)] for j in range(len(gens))]
            reps.append(perms)
        if d == 1: reps = [[[0] for _ in gens]]
        for perms in reps:
            C = M.cover(perms) if d > 1 else M
            fibre_perms = [word_perm(w, gens, perms, d) for w in conj]; orbs = orbits(fibre_perms, d); k = len(orbs); fd = d // k
            O = orbs[0]; pp = word_perm(puncture, gens, perms, d)
            # punctures on the fibre component O: orbits of <puncture loop> restricted to O
            punct = len(orbits([pp], d)); punct_O = len([o for o in orbits([pp], d) if o[0] in O or set(o) & set(O)])
            genus = (2 + fd - punct_O) // 2
            H = C.homology(); rows.append(dict(degree=d, base_degree=k, fibre_degree=fd, punctures=punct_O, fibre_genus=genus, cusps=C.num_cusps(), H1=str(H), b1=H.betti_number(), room=H.betti_number() - C.num_cusps(), isosig=C.triangulation_isosig()))
            print(rows[-1]["degree"], "base", k, "fibre deg", fd, "punct", punct_O, "genus", genus, "cusps", C.num_cusps(), "H1", H, "room", rows[-1]["room"], flush=True)
    return rows


if __name__ == "__main__":
    name, D = sys.argv[1], int(sys.argv[2]); rows = census(name, D)
    json.dump(rows, open(HERE / f"fibre_census_{name}_D{D}.json", "w"), indent=1)
    print("covers:", len(rows), "room>0:", [(r["degree"], r["fibre_genus"], r["room"]) for r in rows if r["room"] > 0], "genus>=2:", sum(1 for r in rows if r["fibre_genus"] >= 2))
    print("room > 0 ==> genus >= 2:", all(r["fibre_genus"] >= 2 for r in rows if r["room"] > 0), "; genus >= 2 ==> room > 0:", all(r["room"] > 0 for r in rows if r["fibre_genus"] >= 2))
