"""B1294 -- THE CHIRALITY BIT: harvest of the three seats' 2026-09-06 work (sm:B1277-addendum /
B1278 / B1279, fc:R69 / R70), with the load-bearing claims RE-COMPUTED here rather than accepted,
plus the one statement none of the seats made and this bench adds:

    every isometry g of m004 has Lefschetz number  L(g) = 1 - s_mu(g)  in {0, 2},
    because H_1(m004) = Z<mu> and the longitude is null-homologous; so chi(Fix g) in {0, 2}
    for all eight -- the object counts 2 or nothing at every fixed locus, by H_1 = Z alone.

Sections:
  A  m004's eight isometries from SnapPy: cusp maps, orders, orientation, s_mu, L, Fix, which
     fillings each extends to (only the orientation-preserving V4 extends to any QHS filling).
  B  fc R69's sentence as a theorem: on a closed QHS, L = 1 - deg  (0 orientation-preserving,
     2 orientation-reversing); the arc-closing combinatorics; and the component count derived
     INDEPENDENTLY of fc's pairing from Montesinos + H_1(-;F_2): 1 + [p even].
  C  H_1(Y_n) for the cyclic branched covers from the Alexander companion matrix (SNF), n = 2..12;
     the seat's Z/4^2, Z/8+Z/40, Z/76^2 at n = 3, 6, 9.
  D  the deck action on the 19-torsion of Y_9: eigenvalues 6, 16 = phi^{+-2} mod 19.
  E  E6 coweight spectra on the 27 (Bourbaki, machinery from B1293): omega_1^v is chiral and NOT
     theta-even (it is MIXED, not theta-odd -- fc's conclusion stands, the eigenvector wording is
     sharpened); every theta-even direction has a q -> -q symmetric spectrum.
  F  the seat scripts re-run on this bench (recorded numbers; their machinery is not on main).
Prints SELFTEST: PASS and writes chirality_bit.json.
"""
import json, sys, os, itertools, collections
from fractions import Fraction as F
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
if not (ROOT / "frontier").exists():                      # drafted outside the tree: OA_ROOT names the repo
    ROOT = Path(os.environ.get("OA_ROOT", ROOT))
sys.path.insert(0, str(ROOT / "frontier" / "B1293_seat_harvest_2026-09-06" / "verification"))
import harvest as H  # noqa: E402  (B1293's E6 machinery: Bourbaki Cartan, W27, simple_coords)

OUT = {}
def ok(cond, msg):
    print(("  ok   " if cond else "  FAIL ") + msg)
    if not cond:
        raise SystemExit("SELFTEST: FAIL -- " + msg)

# ----------------------------------------------------------------------------------------------
print("=== A. m004's eight isometries (SnapPy) ===")
import snappy
M = snappy.Manifold("m004")
G = M.symmetry_group()
isos = G.isometries()
ok(G.order() == 8 and G.is_dihedral() and G.is_amphicheiral(), "Isom(m004) = D4, order 8, amphicheiral")
ok(str(M.homology()) == "Z", "H_1(m004) = Z")

# H_1 from the presentation: exponent sums of the relator and the peripheral words
Gp = M.fundamental_group()
gens, rels = Gp.generators(), Gp.relators()
def expsum(word):
    v = [0] * len(gens)
    for ch in word:
        i = gens.index(ch.lower()); v[i] += 1 if ch.islower() else -1
    return v
rel_sums = [expsum(r) for r in rels]
(mer, lon), = Gp.peripheral_curves()
ok(len(gens) == 2 and len(rels) == 1, f"presentation <{','.join(gens)} | {rels[0]}>")
# H_1 = Z^2 / <relator exponent sums>; with one relator of exponent sum (1,0) the class of b generates
r = rel_sums[0]
ok(sorted(map(abs, r)) == [0, 1], f"relator exponent sums {r}: H_1 = Z generated by the other letter")
killed = r.index(1) if 1 in r else r.index(-1)
def h1class(word):                     # image in Z = Z^2 / <e_killed>
    v = expsum(word); return v[1 - killed]
ok(abs(h1class(mer)) == 1, f"meridian {mer} generates H_1 (class {h1class(mer)})")
ok(h1class(lon) == 0, f"longitude {lon} is null-homologous (class {h1class(lon)})")

# cusp maps, orientation, orders
def cm(iso):
    m = iso.cusp_maps()[0]
    return [[int(m[i, j]) for j in range(2)] for i in range(2)]
maps = [cm(i) for i in isos]
ok(all(m[0][1] == 0 and m[1][0] == 0 and abs(m[0][0]) == 1 and abs(m[1][1]) == 1 for m in maps),
   "all eight cusp maps are diagonal +-1 (m004's (mu, lambda) basis is symmetric-adapted)")
# identity element
ident = next(i for i in range(8) if all(G.multiply_elements(i, j) == j for j in range(8)))
def order(i):
    k, x = 1, i
    while x != ident:
        x = G.multiply_elements(x, i); k += 1
    return k
orders = [order(i) for i in range(8)]
ok(collections.Counter(orders) == {1: 1, 2: 5, 4: 2}, f"element orders {sorted(orders)} (D4: 1 + five involutions + two of order 4)")

table = []
for i, m in enumerate(maps):
    s_mu, s_lam = m[0][0], m[1][1]
    det = s_mu * s_lam
    L = 1 - s_mu                       # Lefschetz: H_0 = Q, H_1 = Q<mu>, H_2 = H_3 = 0 (b_2 = 0 since chi = 0)
    table.append(dict(index=i, s_mu=s_mu, s_lam=s_lam, orientation="preserving" if det == 1 else "REVERSING",
                      order=orders[i], lefschetz=L))
# the classification (argument in FINDINGS): L = chi(Fix) for isometries; Fix is totally geodesic;
# no closed essential surface in the 4_1 complement (small knot) and no essential surface of
# meridional slope => no 2-dimensional fixed component; orientation-reversing elements have no
# fixed circles; hence:
for row in table:
    if row["order"] == 1:
        row["fix"] = "all of M (chi 0)"
    elif row["s_mu"] == 1 and row["s_lam"] == 1:
        row["fix"] = "one closed geodesic, the period-2 axis (chi 0)"
    elif row["s_mu"] == 1 and row["s_lam"] == -1:
        row["fix"] = "EMPTY (free; the Gieseking-type glide)"
    elif row["s_mu"] == -1 and row["s_lam"] == -1:
        row["fix"] = "two arcs, four corners on the cusp (chi 2)"
    else:
        row["fix"] = "exactly TWO isolated interior points on the period-2 axis (chi 2)"
    print(f"   iso {row['index']}: (s_mu, s_lam) = ({row['s_mu']:+d}, {row['s_lam']:+d}), {row['orientation']:>10}, "
          f"order {row['order']}, L = {row['lefschetz']}  ->  Fix = {row['fix']}")
ok(all(r["order"] == 4 for r in table if (r["s_mu"], r["s_lam"]) == (-1, 1)) and
   sum(1 for r in table if (r["s_mu"], r["s_lam"]) == (-1, 1)) == 2,
   "the two order-4 elements are exactly the (s_mu, s_lam) = (-1, +1) glides (the SM addendum's 'GLIDE along lam, order 4')")
ok(all(r["order"] == 2 for r in table if (r["s_mu"], r["s_lam"]) == (1, -1)),
   "the (+1, -1) glides have order 2 (the SM addendum's 'GLIDE along mu, order 2')")
ok(set(r["lefschetz"] for r in table) == {0, 2}, "L(g) = 1 - s_mu takes exactly the values {0, 2}: never 1, never 3")
# squares of the order-4 elements are the period-2 rotation (cusp map I, not the identity)
rot = [i for i in range(8) if maps[i] == [[1, 0], [0, 1]] and i != ident]
ok(len(rot) == 1, "exactly one non-identity element with trivial cusp map (the period-2 rotation)")
for i in range(8):
    if orders[i] == 4:
        ok(G.multiply_elements(i, i) == rot[0], f"iso {i}^2 = the period-2 rotation (so Fix(iso {i}) lies on its axis)")
# which fillings each isometry extends to: A(p,q) = +-(p,q)
def extends(m, p, q):
    v = (m[0][0] * p, m[1][1] * q)
    return v == (p, q) or v == (-p, -q)
slopes = [(p, q) for p in range(-9, 10) for q in range(0, 10) if (p, q) != (0, 0)
          and __import__("math").gcd(abs(p), q) == 1 and (q > 0 or p > 0)]
qhs = [(p, q) for (p, q) in slopes if p != 0 and q != 0]      # p != 0: QHS ; q != 0: not the trivial S^3 filling
ext_counts = {}
for row, m in zip(table, maps):
    n_ext = sum(1 for (p, q) in qhs if extends(m, p, q))
    ext_counts[row["index"]] = n_ext
    row["extends_to_QHS_fillings"] = n_ext
ok(all((ext_counts[r["index"]] == len(qhs)) == (r["orientation"] == "preserving") for r in table),
   f"exactly the orientation-preserving V4 extends to every non-trivial QHS filling ({len(qhs)} slopes tested); "
   "the orientation-reversing four extend to NONE (A(p,q) = +-(p,q) forces pq = 0)")
OUT["A_isometries"] = table

# ----------------------------------------------------------------------------------------------
print("=== B. fc R69 as a Lefschetz statement; the filling loops ===")
# closed QHS N, isometry g: L(g) = tr H_0 - tr H_1 + tr H_2 - tr H_3 = 1 - 0 + 0 - deg(g)
lef_closed = {"orientation-preserving": 1 - 1, "orientation-reversing": 1 - (-1)}
print(f"   closed QHS: L = 1 - deg  =>  chi(Fix) = {lef_closed}")
print(f"   cusped m004: L = 1 - s_mu: the '2' of the two arcs is  1 - tr(theta_* | H_1) = 1 - (-1); "
      "every filling with p != 0 kills b_1, and with it the term.")
# fc's pairing (R69 section 3): M's arcs join 0 <-> tau/2 and 1/2 <-> 1/2 + tau/2 with tau along lambda,
# i.e. corners paired across the lambda-direction: {(0,0),(0,1/2)} and {(1/2,0),(1/2,1/2)} in (mu, lambda) halves.
# solid torus of slope (p,q): its inversion's arcs join 0 <-> (p mod 2, q mod 2) and the other two.
def components(pairing_M, p, q):
    pts = [(0, 0), (1, 0), (0, 1), (1, 1)]           # (mu-half, lambda-half)
    a = (p % 2, q % 2)
    rest = [x for x in pts if x not in ((0, 0), a)]
    pairing_S = {(0, 0): a, a: (0, 0), rest[0]: rest[1], rest[1]: rest[0]}
    seen, comps = set(), 0
    for s in pts:
        if s in seen: continue
        comps += 1; x = s
        while True:
            seen.add(x); y = pairing_M[x]; seen.add(y); x = pairing_S[y]
            if x == s: break
    return comps
fc_pairing = {(0, 0): (0, 1), (0, 1): (0, 0), (1, 0): (1, 1), (1, 1): (1, 0)}
alt_pairing = {(0, 0): (1, 1), (1, 1): (0, 0), (1, 0): (0, 1), (0, 1): (1, 0)}
loops = {}
for (p, q) in qhs:
    c_fc, c_alt = components(fc_pairing, p, q), components(alt_pairing, p, q)
    # the INDEPENDENT count: M(p/q) is the double branched cover of S^3 along Fix/iota (Montesinos);
    # a double branched cover along a c-component link has dim H_1(-;F_2) = c - 1; H_1(M(p/q)) = Z/p.
    c_ind = 1 + (1 if p % 2 == 0 else 0)
    loops[(p, q)] = (c_fc, c_alt, c_ind)
ok(all(v[0] == v[2] for v in loops.values()), "fc's pairing reproduces the independent count 1 + [p even] on every slope")
ok(any(v[1] != v[2] for v in loops.values()), "the alternative pairing (corners paired across mu+lambda) CONTRADICTS Smith/Montesinos on odd slopes -- so the geometric pairing is fc's, derived here without their script")
ok(all(v[0] in (1, 2) for v in loops.values()), "closed loops only: chi(Fix) = 0 on every filling, for either pairing")
ex = {s: loops[s][0] for s in [(1, 1), (5, 1), (2, 1), (3, 2), (4, 1), (7, 3)]}
print(f"   loops by slope (p,q): {ex}   rule: 1 if p odd, 2 if p even")
OUT["B_filling_loops"] = {f"{p}/{q}": v[0] for (p, q), v in loops.items()}
OUT["B_closed_QHS_lefschetz"] = lef_closed

# ----------------------------------------------------------------------------------------------
print("=== C. H_1 of the cyclic branched covers Y_n from the Alexander companion matrix ===")
from sympy import Matrix, eye, ZZ, symbols, resultant, Poly
from sympy.matrices.normalforms import smith_normal_form
t = symbols("t")
Delta = t**2 - 3 * t + 1                                  # Alexander polynomial of 4_1
C = Matrix([[0, -1], [1, 3]])                            # companion matrix of Delta (acts as t on Z^2 = Z[t]/(Delta))
ok(C.charpoly(t).as_expr().expand() == Delta.expand(), "companion matrix has characteristic polynomial t^2 - 3t + 1")
h1 = {}
for n in range(2, 13):
    Mn = C**n - eye(2)
    snf = smith_normal_form(Mn, domain=ZZ)
    d = [abs(int(snf[i, i])) for i in range(2)]
    d = sorted(x for x in d if x != 1) or []
    res = abs(int(resultant(Poly(Delta, t), Poly(t**n - 1, t))))
    ok(abs(int(Mn.det())) == res, f"n={n}: |det(C^n - I)| = |Res(Delta, t^n - 1)| = {res}")
    h1[n] = d
    print(f"   H_1(Y_{n}) = " + (" + ".join(f"Z/{x}" for x in d) if d else "0") + f"   (|H_1| = {res})")
# the golden form of the table: Delta's roots are phi^{+-2}, so |H_1(Y_n)| = L_n^2 (n odd) and 5 F_n^2 (n even),
# and the GROUPS are (Z/L_n)^2 for odd n, Z/F_n + Z/5F_n for even n -- the 19 of Y_9 is L_9/L_3 = 76/4 = L_6 + 1
Fib = [0, 1]; Luc = [2, 1]
for _ in range(14):
    Fib.append(Fib[-1] + Fib[-2]); Luc.append(Luc[-1] + Luc[-2])
ok(all(h1[n] == [Luc[n], Luc[n]] for n in range(3, 13, 2)), f"odd n: H_1(Y_n) = (Z/L_n)^2, L = {Luc[3:13:2]}")
ok(all(h1[n] == [x for x in sorted([Fib[n], 5 * Fib[n]]) if x != 1] for n in range(2, 13, 2)), f"even n: H_1(Y_n) = Z/F_n + Z/5F_n, F = {Fib[2:13:2]}")
ok(Luc[9] // Luc[3] == 19 and Luc[6] + 1 == 19, "the 19 of the three-generation closing Y_9 is L_9/L_3 = L_6 + 1 = 19")
ok(h1[3] == [4, 4], "H_1(Y_3) = Z/4 + Z/4  (seat: 'Y_3: H_1 = Z/4 + Z/4'; B298's Z/4+Z/4+Z is the UNbranched cover)")
ok(h1[6] == [8, 40], "H_1(Y_6) = Z/8 + Z/40 (seat)")
ok(h1[9] == [76, 76], "H_1(Y_9) = Z/76 + Z/76 (seat); 76 = 4 * 19")
OUT["C_H1_Yn"] = {str(k): v for k, v in h1.items()}

# ----------------------------------------------------------------------------------------------
print("=== D. the deck action on the 19-torsion of Y_9 ===")
roots19 = [x for x in range(19) if (x * x - 3 * x + 1) % 19 == 0]
ok(roots19 == [6, 16], f"roots of t^2 - 3t + 1 mod 19: {roots19} (seat: [6, 16])")
sq5 = [x for x in range(19) if (x * x) % 19 == 5]
phi = [(1 + s) * pow(2, -1, 19) % 19 for s in sq5]
ok(set((p * p) % 19 for p in phi) == {6, 16}, f"phi = (1 + sqrt5)/2 mod 19 in {phi}; phi^2 mod 19 in {set((p*p)%19 for p in phi)} = the two eigenvalues")
ok((6 * 16) % 19 == 1 and (6 + 16) % 19 == 3, "eigenvalue product 1 and sum 3 mod 19 (as t^2 - 3t + 1 demands)")
# distinct eigenvalues => exactly two t-invariant lines in (Z/19)^2; 18 generators each => 36 order-19 'family' classes
ok(2 * 18 == 36, "two eigenlines x 18 generators = the seat's 36 order-19 classes (of the 360 order-19 elements of (Z/19)^2)")
OUT["D_mod19"] = {"roots": roots19, "phi_mod_19": phi}

# ----------------------------------------------------------------------------------------------
print("=== E. E6 coweight spectra on the 27 (Bourbaki; B1293's machinery) ===")
ok(len(H.W27) == 27 and len(H.ROOTS) == 72, "27 weights, 72 roots")
def charges(cow):                       # cow = coefficients of omega_i^v ; <cow, w> = sum cow_i * (alpha_i-coordinate of w)
    out = collections.Counter()
    for w in H.W27:
        sc = H.simple_coords(w)
        out[sum(F(c) * sc[i] for i, c in enumerate(cow))] += 1
    return dict(sorted(out.items()))
def show(name, cow):
    ch = charges(cow); half = {k / 2: v for k, v in ch.items()}
    print(f"   {name:<22} raw {{{', '.join(f'{k}: {v}' for k, v in ch.items())}}}   half-normalised {{{', '.join(f'{k}: {v}' for k, v in half.items())}}}")
    return ch
e = lambda *idx: [1 if (i + 1) in idx else 0 for i in range(6)]
c1 = show("omega_1^v (SO(10))", e(1))
c6 = show("omega_6^v", e(6))
c2 = show("omega_2^v (theta-even)", e(2))
c4 = show("omega_4^v (theta-even)", e(4))
c16 = show("omega_1^v+omega_6^v", e(1, 6))
c35 = show("omega_3^v+omega_5^v", e(3, 5))
ok(c1 == {F(-2, 3): 10, F(1, 3): 16, F(4, 3): 1}, "omega_1^v on the 27: 1_{4/3} + 16_{1/3} + 10_{-2/3}  (fc's 1_{2/3}+16_{1/6}+10_{-1/3} is the half normalisation)")
ok(c6 == {-k: v for k, v in c1.items()}, "omega_6^v spectrum on the 27 is the NEGATIVE of omega_1^v's (the flip sends 27 -> 27bar)")
sym = lambda ch: all(ch.get(-k, 0) == v for k, v in ch.items())
ok(all(sym(c) for c in (c2, c4, c16, c35)), "every theta-even direction has a q -> -q symmetric 27-spectrum (forced: theta-even u, theta: 27 -> 27bar)")
ok(not sym(c1), "omega_1^v's spectrum is NOT symmetric: the only chiral abelian direction among these")
ok(c2 == {F(-1): 6, F(0): 15, F(1): 6}, "omega_2^v: 15_0 + 6_{+-1} (fc's 15 + 6bar_{+-1/2})")
ok(c16 == {F(-2): 1, F(-1): 8, F(0): 9, F(1): 8, F(2): 1}, "omega_1^v+omega_6^v: 9_0 + 8_{+-1} + 1_{+-2} (fc's 9 + 8_{+-1/2} + 1_{+-1})")
# theta = the diagram automorphism on the coweight lattice: swaps 1<->6, 3<->5
sigma = lambda v: [v[5], v[1], v[4], v[3], v[2], v[0]]
ok(sigma(e(1)) == e(6) and sigma(e(1)) != e(1) and sigma(e(1)) != [-x for x in e(1)],
   "omega_1^v is NOT theta-even and NOT theta-odd: it is MIXED, even part (omega_1^v+omega_6^v)/2, odd part (omega_1^v-omega_6^v)/2")
even_part = charges([F(1, 2) * (a + b) for a, b in zip(e(1), e(6))])
ok(even_part == {k / 2: v for k, v in c16.items()}, "its theta-even projection is the D4 + u(1)^2 direction: spectrum 9_0 + 8_{+-1/2} + 1_{+-1}, vector-like")
OUT["E_E6_spectra"] = {"omega1": {str(k): v for k, v in c1.items()}, "omega6": {str(k): v for k, v in c6.items()},
                       "omega2": {str(k): v for k, v in c2.items()}, "omega1+omega6": {str(k): v for k, v in c16.items()},
                       "omega4": {str(k): v for k, v in c4.items()}, "omega3+omega5": {str(k): v for k, v in c35.items()}}

# ----------------------------------------------------------------------------------------------
print("=== F. the seat scripts as re-run on this bench 2026-09-06 (recorded; not re-derivable on main) ===")
F_RUNS = {
    "sm:B1277-addendum arcs_and_corners.py": {"rc": 0, "leading_allowed_orbit": "(+-2, 0)", "chi_dplus": 0, "coefficient_computed": False},
    "sm:B1279 symmetries_on_the_lines.py": {"rc": 0, "outer_classes": 8, "group_on_Y9": 72, "deck_on_C1_C2": [6, 16], "SM_lines": 706464, "orbits": 19624, "seconds": 261},
    "sm:B1278 six_fold_closing.py 3,6": {"rc": 0, "Y3_control": True, "Y6_three_generation_SM_lines": 0},
    "sm:B1278 six_fold_closing.py 9": {"rc": 0, "H1": "Z/76 + Z/76", "H1_order": 5776, "h1_distribution": {0: 5629, 1: 147},
                                       "three_generation_alphabet_K3": 145, "extra_classes": {"38": 108, "19": 36},
                                       "SU5_breaking_three_generation_lines": 737568, "SM_vacua": 706464, "full_spectrum": 568656,
                                       "distinct_spectra": 16, "seconds_h1_sweep": 149},
    "fc:R69 r69_arcs_cut_corners.py": {"rc": 0, "net_on_Fix_theta": "+-2 or 0", "fillings": "loops, chi 0"},
    "fc:R70 r70_what_two_of.py / r70b_true_theta.py": {"rc": 0, "omega1_half_charges": {"-1/3": 10, "1/6": 16, "2/3": 1}, "theta_F4_fixed_cartan_dim": 4, "conj_fixed_cartan_dim": 1},
}
for k, v in F_RUNS.items():
    print(f"   {k}: {v}")
ok(F_RUNS["sm:B1278 six_fold_closing.py 9"]["SM_vacua"] == F_RUNS["sm:B1279 symmetries_on_the_lines.py"]["SM_lines"] == 706464,
   "Y_9: the B1278 SM-vacuum count re-run here (706464) is the B1279 input")
ok(F_RUNS["sm:B1278 six_fold_closing.py 9"]["H1_order"] == 76 * 76 == 5776 and h1[9] == [76, 76],
   "Y_9: |H_1| = 5776 = 76^2 from the seat's Fox calculus equals the SNF of C^9 - I computed here")
ok(5629 + 147 == 5776 and 108 + 36 + 3 == 147, "Y_9: h^1 distribution {0: 5629, 1: 147}; 147 = 3 family + 108 order-38 + 36 order-19")
ok(706464 % 19624 == 0 and 706464 // 19624 == 36, "706464 / 19624 = 36: average orbit size 36 under a group of order 72 (average stabiliser 2)")
OUT["F_seat_runs"] = F_RUNS

(HERE / "chirality_bit.json").write_text(json.dumps(OUT, indent=1, default=str), encoding="utf-8")
print("\nTHE SENTENCE: the object counts 2 at every fixed locus -- L(g) = 1 - s_mu in {0, 2} on the cusped object,"
      " L = 1 - deg in {0, 2} on every closed QHS closing; 3 appears only through the Z/3 descent (3 | n), and the descent is vector-like.")
print("\nSELFTEST: PASS")
