#!/usr/bin/env python3
"""Generate navigation views from arc metadata. GOVERNANCE §12 clause two.

    "Freeze the substrate; generate the views; govern by metadata."   -- GOVERNANCE.md:243

Clause one (frozen substrate) has been enforced since 2026-07-16. Clause two was never
executed: every navigation surface was hand-maintained, and on 2026-07-29 a day of sweeps
found four drift classes, ALL of them hand-maintained views -- a lost knowledge index, stale
navigation, dangling path citations, and verdicts hand-copied into tests. This is clause two.

SOURCES (never edited by this script):
  frontier/<arc>/arc_verdict.json                  -- the authored judgement layer (W1)
  frontier/B738_pathfinder_compiler/kill_graph.json -- the kill metadata (217 records)
  frontier/<arc>/FINDINGS.md                        -- AUTO fields (title, size, tests)

OUTPUTS are written under docs/views/ with a do-not-edit header. They are DERIVED: editing
them by hand is the exact failure this exists to end.

Note on the filename `arc_verdict.json`: `verdict.json` was already taken by
B440_foreign_vacuum_control with an unrelated schema -- a collision the W1 pilot caught.
"""
import json
import os
import re
import subprocess
import sys
from collections import Counter

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = os.path.join(ROOT, "docs", "views")
HEADER = ("<!-- GENERATED by scripts/views/generate.py -- DO NOT EDIT BY HAND.\n"
          "     Source of truth: frontier/<arc>/arc_verdict.json + kill_graph.json.\n"
          "     Hand-editing a generated view reintroduces exactly the drift it prevents. -->\n\n")


def _title(h1):
    b = h1.lstrip("# ").strip()
    b = re.sub(r"^FINDINGS\s*[—:\-–]+\s*", "", b, flags=re.I)
    return re.sub(r"^B\d+[a-zA-Z]?\s*[—:\-–(]*\s*", "", b).strip()


def collect():
    """Every arc, with whatever layers exist for it. Missing layers are reported, not faked."""
    arcs = []
    fdir = os.path.join(ROOT, "frontier")
    for d in sorted(os.listdir(fdir)):
        fp = os.path.join(fdir, d, "FINDINGS.md")
        if not os.path.isfile(fp):
            continue
        m = re.match(r"(B\d+)[a-zA-Z]?_", d)
        if not m:
            continue
        text = open(fp, encoding="utf-8").read()
        h1 = next((l for l in text.splitlines() if l.startswith("# ")), "")
        a = {"id": m.group(1), "n": int(m.group(1)[1:]), "dir": d,
             "title": _title(h1), "words": len(text.split()),
             "tests": sorted(set(re.findall(r"tests/(test_[A-Za-z0-9_]+\.py)", text))),
             "has_verdict_block": bool(re.search(r"^#{2,3}\s*Verdict", text, re.M | re.I))}
        vp = os.path.join(fdir, d, "arc_verdict.json")
        a["verdict_record"] = json.load(open(vp, encoding="utf-8")) if os.path.isfile(vp) else None
        arcs.append(a)
    kgp = os.path.join(fdir, "B738_pathfinder_compiler", "kill_graph.json")
    kills = json.load(open(kgp, encoding="utf-8")) if os.path.isfile(kgp) else []
    return arcs, kills


def view_coverage(arcs, kills):
    """The view that must exist first: how much of the record is actually projected."""
    n = len(arcs)
    authored = [a for a in arcs if a["verdict_record"]]
    kg_ids = {r["id"] for r in kills}
    arc_ids = {a["id"] for a in arcs}
    L = [HEADER, "# Coverage of the generated views\n",
         "How much of the record these views actually project. This view exists so that no other\n"
         "view can quietly imply completeness it does not have.\n",
         "| layer | count | of | share |", "|---|---|---|---|",
         f"| arcs with `FINDINGS.md` | **{n}** | — | 100 % |",
         f"| arcs with an authored verdict (W1) | **{len(authored)}** | {n} | {len(authored)/n*100:.1f} % |",
         f"| classified in `kill_graph` | **{len(kills)}** | — | — |",
         f"| kill records resolving to an arc | **{len(kg_ids & arc_ids)}** | {len(kills)} | {len(kg_ids & arc_ids)/len(kills)*100:.0f} % |",
         f"| kill records with no arc directory | **{len(kg_ids - arc_ids)}** | {len(kills)} | {len(kg_ids - arc_ids)/len(kills)*100:.0f} % |",
         ""]
    # the honest gap: negatives the kill graph does not carry
    unreg = [a["id"] for a in authored
             if a["verdict_record"]["verdict"] == "NEGATIVE" and a["id"] not in kg_ids]
    if unreg:
        L += ["## Negatives absent from `kill_graph`\n",
              "Found among the authored arcs only, so this is a **lower bound**: `kill_graph`'s "
              "217 records are not a census of the corpus's negatives.\n",
              "".join(f"- `{i}`\n" for i in sorted(unreg)), ""]
    strata = Counter("A_verdict_block" if a["has_verdict_block"]
                     else ("C_neither" if len(a["title"]) < 22
                           or a["title"].lower().startswith("findings") else "B_informative_title")
                     for a in arcs)
    L += ["## Classifiability strata\n",
          "Measured, not assumed. The W1 pilot's original premise — that malformed titles mark the\n"
          "hard arcs — was **refuted**: 83 % of uninformative-title arcs carry an explicit `## Verdict`\n"
          "block against 19 % of the rest, so the title heuristic *anti*-correlates with difficulty.\n",
          "| stratum | meaning | count | share |", "|---|---|---|---|"]
    for k, lab in (("A_verdict_block", "explicit `## Verdict` block — directly extractable"),
                   ("B_informative_title", "no block, but the title carries the verdict"),
                   ("C_neither", "neither — genuinely hard, needs a full read")):
        L.append(f"| **{k[0]}** | {lab} | {strata[k]} | {strata[k]/n*100:.1f} % |")
    return "\n".join(L) + "\n"


def view_claims(arcs):
    """The claim ledger, grouped by verdict. Generated -- so it cannot drift from the arcs."""
    authored = [a for a in arcs if a["verdict_record"]]
    L = [HEADER, "# Arc verdict ledger (generated)\n",
         f"{len(authored)} of {len(arcs)} arcs carry an authored verdict. "
         "Arcs without one are absent from this ledger by construction, not by judgement.\n"]
    order = ["PROVED", "NEGATIVE", "OPEN", "RETRACTED"]
    by = {k: [] for k in order}
    for a in authored:
        by.setdefault(a["verdict_record"]["verdict"], []).append(a)
    for k in order:
        rows = sorted(by.get(k, []), key=lambda a: a["n"])
        if not rows:
            continue
        L += [f"\n## {k} ({len(rows)})\n", "| arc | claim | instrument | locks |", "|---|---|---|---|"]
        for a in rows:
            v = a["verdict_record"]
            L.append(f"| `{a['id']}` | {v['claim_one_line']} | "
                     f"{'yes' if v.get('instrument') else ''} | {len(a['tests'])} |")
    return "\n".join(L) + "\n"


def view_closed_doors(arcs, kills):
    """The negatives, indexed by the MECHANISM that shut them -- the reviewer-legible asset."""
    byform = {}
    for r in kills:
        byform.setdefault(r["kill_form"], []).append(r)
    L = [HEADER, "# The closed-door map (generated)\n",
         f"{len(kills)} classified closures, indexed by the mechanism that shut them rather than by\n"
         "arc number. A programme whose firewall works is mostly negatives; this is the shape of them.\n",
         "| mechanism | doors | facts not computed |", "|---|---|---|"]
    for form, rs in sorted(byform.items(), key=lambda kv: -len(kv[1])):
        unc = sum(1 for r in rs if not r["fact_computed"])
        L.append(f"| `{form}` | {len(rs)} | {unc or ''} |")
    unc = [r for r in kills if not r["fact_computed"]]
    L += ["", f"## Closures whose discriminating fact was not computed ({len(unc)})\n",
          "The standing rule is that a negative is only as sound as the in-sandbox computation of\n"
          "its discriminating fact. **B799 resolved all of these** — see "
          "`frontier/B799_uncomputed_doors/`.\n",
          "| arc | claim killed | mechanism |", "|---|---|---|"]
    for r in unc:
        L.append(f"| `{r['id']}` | {r['claim_killed'][:110]} | `{r['kill_form']}` |")
    return "\n".join(L) + "\n"


def main():
    arcs, kills = collect()
    os.makedirs(OUT, exist_ok=True)
    views = {"COVERAGE.md": view_coverage(arcs, kills),
             "VERDICT_LEDGER.md": view_claims(arcs),
             "CLOSED_DOORS.md": view_closed_doors(arcs, kills)}
    changed = []
    for name, body in views.items():
        p = os.path.join(OUT, name)
        old = open(p, encoding="utf-8").read() if os.path.isfile(p) else None
        if old != body:
            open(p, "w", encoding="utf-8").write(body)
            changed.append(name)
    print(f"arcs={len(arcs)}  authored={sum(1 for a in arcs if a['verdict_record'])}  "
          f"kills={len(kills)}")
    print(f"views written to docs/views/: {', '.join(views)}")
    print(f"changed this run: {', '.join(changed) if changed else 'none (already current)'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
