#!/usr/bin/env python3
"""THE SPINE — the programme's true build order, generated from what never lost track.

Joins three sources nobody had joined: git's birth date of every test lock, each arc's
own claim_one_line, and the lock's filename. One line per verified step, chronological.
Regenerate: python3 scripts/views/spine.py  ->  docs/views/THE_SPINE.md
Born 2026-08-19 from the owner's question: "maybe the 4000 tests carry the order of how
the framework gets built, and by revisiting them we can retrieve lost breakthroughs."
They do, and this is the retrieval."""
import subprocess, json, os, re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

def main():
    out = subprocess.run(["git","log","--diff-filter=A","--format=%ad|%H","--date=short",
                          "--name-only","--","tests/"], cwd=ROOT, capture_output=True, text=True).stdout
    born, cur = {}, None
    for line in out.splitlines():
        if "|" in line and re.match(r"\d{4}-\d{2}-\d{2}\|", line):
            cur = line.split("|")[0]
        elif line.startswith("tests/") and line.endswith(".py"):
            born.setdefault(line, cur)
    verdicts = {}
    fdir = os.path.join(ROOT, "frontier")
    for d in sorted(os.listdir(fdir)):
        p = os.path.join(fdir, d, "arc_verdict.json")
        if os.path.exists(p):
            try:
                j = json.load(open(p, encoding="utf-8"))
                verdicts[j.get("id", d.split("_")[0])] = (j.get("verdict","?"),
                    (j.get("claim_one_line") or j.get("title") or "").strip())
            except Exception:
                pass
    rows = []
    for tf, date in born.items():
        if not os.path.exists(os.path.join(ROOT, tf)):
            continue  # deleted locks stay out of the living spine (history keeps them)
        m = re.search(r"b(\d{2,4})", os.path.basename(tf))
        arc = f"B{m.group(1)}" if m else None
        v = verdicts.get(arc, ("", ""))
        head = re.split(r"\s*--\s*|(?<=[a-z)])\.\s", v[1])[0][:150] if v[1] else ""
        rows.append((date or "????-??-??", arc or "", v[0], head, os.path.basename(tf)))
    rows.sort(key=lambda r: (r[0], r[1] or "zzz", r[4]))
    lines = ["# THE SPINE — the build order, from the locks that never lost track",
             "",
             "*One line per living test lock, in git birth order. The claim head comes from the",
             "arc's own verdict file; drill down: the arc's FINDINGS, then CHANGELOG at that date.",
             f"Generated by `scripts/views/spine.py` — {len(rows)} locks. Regenerated with the views.*",
             ""]
    day = None
    for date, arc, verd, head, tf in rows:
        if date != day:
            lines.append(f"\n## {date}\n")
            day = date
        tag = f"**{arc}**" if arc else "—"
        vt = f" `{verd}`" if verd else ""
        lines.append(f"- {tag}{vt} `{tf}` {('— ' + head) if head else ''}")
    open(os.path.join(ROOT, "docs", "views", "THE_SPINE.md"), "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print(f"THE_SPINE.md: {len(rows)} locks across {len(set(r[0] for r in rows))} build days")

if __name__ == "__main__":
    main()
