#!/usr/bin/env python3
"""B1466 follow-up (2026-10-04, the audit lane's R83 proof request): an actual irreducibility certificate for the fused
module at q0 and q0'.  Commutant = C and 'no invariant line' do not certify irreducibility of a non-semisimple module;
Burnside does: the module is absolutely irreducible iff the algebra generated by rho(m), rho(n) is all of M_5(C), i.e.
the span of the words has dimension 25.  Also the span's dimension when restricted to the split module S = A (+) 1
(a control that must be < 25: S is reducible) and for W (reducible, non-split: also < 25)."""
import sys, json, pathlib, itertools
HERE = pathlib.Path(__file__).resolve().parent
sys.argv = [sys.argv[0]]
import two_orders as TO, c3b_mixed_module as C
from two_orders import jo, REL, TOL
from mpmath import mp, mpf, mpc, matrix, eye, zeros, inverse, sqrt, svd_c, nstr, norm
mp.dps = 60


def generated_algebra_dim(g, maxlen=6):
    """dimension of span{rho(w) : |w| <= maxlen} inside M_n(C), with the singular-value gap"""
    n = g["m"].rows; mats = [eye(n)]
    letters = ["m", "n", "M", "N"]
    for L in range(1, maxlen + 1):
        for w in itertools.product(letters, repeat=L):
            mats.append(jo.word("".join(w), g))
    rows = matrix(len(mats), n * n)
    for i, A in enumerate(mats):
        for a in range(n):
            for b in range(n): rows[i, a * n + b] = A[a, b]
    U, S, Vh = svd_c(rows)
    k = sum(1 for i in range(len(S)) if abs(S[i]) > TOL * max(1, abs(S[0])))
    gap = (nstr(abs(S[k - 1]), 4), nstr(abs(S[k]), 4) if k < len(S) else "none")
    return k, gap, len(mats)


def fused_module(q, mu, eps=mpf("0.1")):
    """the fused module as c3b builds it (second order + Gauss-Newton), returned as matrices"""
    g = jo.ballas(q, mu); S = TO.blockS(g)
    reps_up, _, _ = jo.cocycles(g); reps_dn, _, _ = TO.cocycles_down(g)
    c1 = {"m": matrix([reps_up[0][i] for i in range(4)]), "n": matrix([reps_up[0][4 + i] for i in range(4)])}
    c2 = {"m": matrix([[reps_dn[0][i] for i in range(4)]]), "n": matrix([[reps_dn[0][4 + i] for i in range(4)]])}
    Sinv = {k: inverse(S[k]) for k in "mn"}; N1 = {k: zeros(5, 5) for k in "mn"}; N2 = {k: zeros(5, 5) for k in "mn"}
    for k in "mn":
        for i in range(4): N1[k][i, 4] = c1[k][i]; N2[k][4, i] = c2[k][0, i]
    phi = {k: Sinv[k] * (N1[k] + N2[k]) for k in "mn"}
    D = TO.d1_matrix(S); M0, M1, M2 = TO.series_word(REL, S, phi); ob = matrix([M2[a, b] for a in range(5) for b in range(5)])
    psi_vec, rk = C.lstsq_min_norm(D, -ob); psi = {"m": matrix(5, 5), "n": matrix(5, 5)}
    for k_i, k in enumerate("mn"):
        for i in range(5):
            for j in range(5): psi[k][i, j] = psi_vec[k_i * 25 + i * 5 + j]
    g_eps = {k: S[k] * (eye(5) + eps * phi[k] + eps * eps * psi[k]) for k in "mn"}
    for it in range(40):
        r = C.relator_vec(g_eps)
        if norm(r) < mpf(10) ** (-45): break
        J = C.jacobian(g_eps); dx, k = C.lstsq_min_norm(J, -r)
        for k_i, kk in enumerate("mn"):
            for i in range(5):
                for j in range(5): g_eps[kk][i, j] += dx[k_i * 25 + i * 5 + j]
    return g_eps, S, jo.ext(g, c1), nstr(norm(C.relator_vec(g_eps)), 4)


if __name__ == "__main__":
    s2 = sqrt(mpf(2)); out = []
    for q, label in ((17 + 12 * s2, "q0 = 17 + 12 sqrt2"), (17 - 12 * s2, "q0' = 17 - 12 sqrt2")):
        g_eps, S, W, res = fused_module(q, mpc(-1))
        row = dict(label=label, relator_residual=res)
        for name, M in (("fused", g_eps), ("split S = A (+) 1 (control, reducible)", S), ("W (control, reducible non-split)", W)):
            k, gap, nw = generated_algebra_dim(M); row[name] = dict(generated_algebra_dim=k, gap=gap, words=nw)
            print(label, "|", name, "| dim of generated algebra =", k, "of 25 | gap", gap, flush=True)
        out.append(row)
    json.dump(out, open(HERE / "c3c_burnside.json", "w"), indent=1, default=str)
