#!/usr/bin/env python3
"""The base rate of the E6 entry point, computed exactly: for each of the first 400 one-cusped orientable census manifolds
(census order), the number of surjections pi_1 -> SL(2,3) up to Aut(SL(2,3)), by brute force over generator images with the
relators checked in the group's multiplication table. Reports the fraction with >= 1 surjection, the fraction with exactly
m004's count, m004's count, the tie list, and the denominator by generator count."""
import itertools, json, sys, time
import numpy as np, snappy

# SL(2,3) as 2x2 matrices over F_3
els = []
for a, b, c, d in itertools.product(range(3), repeat=4):
    if (a * d - b * c) % 3 == 1: els.append((a, b, c, d))
assert len(els) == 24
idx = {e: i for i, e in enumerate(els)}
def mul(x, y):
    a, b, c, d = x; e, f, g, h = y
    return ((a*e + b*g) % 3, (a*f + b*h) % 3, (c*e + d*g) % 3, (c*f + d*h) % 3)
MT = np.zeros((24, 24), dtype=np.int64)
for i, x in enumerate(els):
    for j, y in enumerate(els): MT[i, j] = idx[mul(x, y)]
ID = idx[(1, 0, 0, 1)]
INV = np.zeros(24, dtype=np.int64)
for i in range(24):
    for j in range(24):
        if MT[i, j] == ID: INV[i] = j
# automorphisms of SL(2,3): bijections preserving the table (brute force via generators: SL(2,3) is generated by two elements)
def generated(gens):
    S = {ID}; frontier = [ID]
    while frontier:
        nxt = []
        for s in frontier:
            for g in gens:
                t = int(MT[s, g])
                if t not in S: S.add(t); nxt.append(t)
        frontier = nxt
    return S
gen_pair = next((g1, g2) for g1 in range(24) for g2 in range(24) if len(generated([g1, g2])) == 24)
# express every element as a word in the pair (BFS), then an automorphism is determined by the images of the pair
words = {ID: []}; frontier = [ID]
while frontier:
    nxt = []
    for s in frontier:
        for k, g in enumerate(gen_pair):
            t = int(MT[s, g])
            if t not in words: words[t] = words[s] + [k]; nxt.append(t)
    frontier = nxt
def image_map(i1, i2):
    m = {}
    for e, w in words.items():
        v = ID
        for k in w: v = int(MT[v, (i1, i2)[k]])
        m[e] = v
    return m
AUTS = []
for i1 in range(24):
    for i2 in range(24):
        if len(generated([i1, i2])) != 24: continue
        m = image_map(i1, i2)
        if len(set(m.values())) == 24 and all(m[int(MT[x, y])] == int(MT[m[x], m[y]]) for x in range(24) for y in range(24)):
            AUTS.append(tuple(m[e] for e in range(24)))
AUTS = sorted(set(AUTS)); assert len(AUTS) == 24, len(AUTS)   # Aut(SL(2,3)) = S4

def word_to_int(w, gens, imgs):
    v = ID
    for ch in w:
        g = imgs[gens.index(ch.lower())]
        v = int(MT[v, g if ch.islower() else INV[g]])
    return v

def count_surjections(M):
    G = M.fundamental_group(); gens = list(G.generators()); rels = list(G.relators())
    n = len(gens); found = set()
    for imgs in itertools.product(range(24), repeat=n):
        if all(word_to_int(r, gens, imgs) == ID for r in rels) and len(generated(list(imgs))) == 24:
            found.add(imgs)
    # orbits under Aut
    seen = set(); classes = 0
    for h in found:
        if h in seen: continue
        classes += 1
        for A in AUTS: seen.add(tuple(A[g] for g in h))
    return n, len(found), classes

def main(N=400):
    t0 = time.time(); rows = []
    for M in snappy.OrientableCuspedCensus(cusps=1):
        n, homs, classes = count_surjections(M)
        rows.append(dict(name=M.name(), volume=float(M.volume()), gens=n, surjections=homs, classes=classes))
        if len(rows) % 50 == 0: print(f"  {len(rows)} done ({round(time.time()-t0)} s)", flush=True)
        if len(rows) >= N: break
    m004 = next(r for r in rows if r["name"] == "m004")
    tot = len(rows); with_any = sum(1 for r in rows if r["classes"] >= 1); same = sum(1 for r in rows if r["classes"] == m004["classes"])
    by_gens = {}
    for r in rows: by_gens[r["gens"]] = by_gens.get(r["gens"], 0) + 1
    tie = [r["name"] for r in rows if r["classes"] == m004["classes"]][:12]
    dist = {}
    for r in rows: dist[r["classes"]] = dist.get(r["classes"], 0) + 1
    out = dict(N=tot, denominator_by_generator_count=by_gens, m004_classes=m004["classes"], with_at_least_one=with_any, frac_any=with_any / tot,
               exactly_m004_count=same, frac_same=same / tot, distribution_of_classes=dist, tie_list_first_12=tie, seconds=round(time.time() - t0), rows=rows)
    json.dump(out, open("sl23_baserate.json", "w"), indent=1)
    print(json.dumps({k: v for k, v in out.items() if k != "rows"}, indent=1))

if __name__ == "__main__":
    main(int(sys.argv[1]) if len(sys.argv) > 1 else 400)
