#!/usr/bin/env python3
"""B1463 -- the audit lane's two corrections of main's early arcs (its ACT_REGISTER AR3 and AR4; carried into GENESIS v1.3
by the SM seat, sm:B1521 C2-C3), re-derived on main with main's own code and main's own files (lead L243 (a)).

AR3 (B37, B20).  B37's "self-model predicate" is, in its own probe.py, `any(component.has(I))` for a symbol I that
    never occurs in the trace map; it is a test of literal symbol presence.  Shown here: (i) read from B37's file;
    (ii) the predicate is False on EVERY map written in x, y, z, so it could not fail on its domain (MB12 / the E82
    class); (iii) the audit lane's rewriting T'(x, y, z, r) = (z, x, 2xz - y + (r - I), r) equals T on the record
    graph r = I and preserves the graph, yet the predicate fires on it; (iv) the opposite control: a map that reads r
    off the graph (z' = 2xz - y + r) changes an orbit when r != I.  So B37's "never reads" rests on a detector that
    cannot detect reading; whether the trace map reads kappa in the reads-and-branches sense is not settled by B37.
AR4 (B130).  B130 inferred "kappa free, no forced choice" from the k-elimination ideal of the fixed locus being zero.
    Shown here: (i) the countermodel x(x - 1) = 0, xk = 0 -- a line and an isolated point with k free -- eliminates to
    the zero ideal in k, so the inference is invalid in general; (ii) B130's own m = 2 elimination reproduced (zero
    ideal); (iii) at m = 2 the fixed ideal is generated by two polynomials, so by Krull no component is 0-dimensional;
    (iv) at m = 2, 3, 4 the Hilbert dimension of the fixed locus is 1 (leading monomials of a grevlex basis); (v) the
    primary decomposition in Sage/Singular (`b130_components.sage`, output `b130_components_sage.out`, recorded; Sage is
    not the test environment) has every component of dimension 1 at m = 2, 3, 4: B130's CONCLUSION holds on its
    domain, by a valid argument now.  The sp.solve "points" with kappa = -6, -158/21 (m = 2), 2/3 and 13/2 (m = 4) are
    singular points of curve components, not isolated points.
Exit 1 on any failure."""
import sys, json, pathlib, itertools, re
import sympy as sp
HERE = pathlib.Path(__file__).resolve().parent; ROOT = HERE.parents[2]
x, y, z, r, k = sp.symbols("x y z r k")

def ar3():
    out = {}
    src = open(ROOT / "frontier" / "B37_operational_feedback_quarantine" / "probe.py").read()
    out["b37_predicate_is_literal"] = "any(component.has(i_symbol) for component in trace_map)" in src and 'i_symbol = sp.symbols("I")' in src
    I = sp.symbols("I"); inv = x**2 + y**2 + z**2 - 2 * x * y * z - 1
    T = sp.Matrix([z, x, 2 * x * z - y])
    pred = lambda M: any(c.has(I) for c in M)
    # (ii) universal vacuity: the predicate is False for every polynomial map in x, y, z (I is a fresh symbol); a random sample
    import random; random.seed(3)
    sample = [sp.Matrix([sum(random.randint(-3, 3) * m for m in (1, x, y, z, x * y, y * z, x * z, x * y * z)) for _ in range(3)]) for _ in range(50)]
    out["predicate_false_on_every_map_in_xyz"] = all(not pred(M) for M in sample) and not pred(T)
    out["predicate_false_on_T"] = not pred(T)
    # (iii) the audit lane's rewriting
    Tp = sp.Matrix([z, x, 2 * x * z - y + (r - inv), r])
    on_graph_equal = sp.simplify(Tp.subs(r, inv)[:3, :] - T) == sp.zeros(3, 1)
    inv_after = sp.expand(inv.subs({x: Tp[0], y: Tp[1], z: Tp[2]}, simultaneous=True).subs(r, inv) - inv) == 0
    out["Tprime_equals_T_on_the_graph_and_keeps_it"] = bool(on_graph_equal and inv_after)
    out["predicate_fires_on_Tprime"] = any(c.has(r) for c in Tp[:3, :])
    # (iv) the opposite control
    Tg = sp.Matrix([z, x, 2 * x * z - y + r, r]); p0 = {x: sp.Rational(1, 2), y: sp.Rational(1, 3), z: sp.Rational(2, 5)}; I0 = inv.subs(p0)
    out["genuine_read_changes_the_orbit_off_the_graph"] = Tg.subs({**p0, r: I0}) != Tg.subs({**p0, r: I0 + 1})
    out["vacuous_rewriting_matches_T_on_the_graph"] = list(Tp.subs({**p0, r: I0})[:3, :]) == list(T.subs(p0))
    return out

Ta = lambda t: (t[0], t[2], t[0] * t[2] - t[1]); Tb = lambda t: (t[2], t[1], t[1] * t[2] - t[0])
def phi(m, t):
    for _ in range(m): t = Tb(t)
    for _ in range(m): t = Ta(t)
    return t
kap = lambda t: t[0]**2 + t[1]**2 + t[2]**2 - t[0] * t[1] * t[2] - 2
def k_elimination(eqs):
    G = sp.groebner(eqs + [k - kap((x, y, z))], x, y, z, k, order="lex")
    return [g.as_expr() for g in G.polys if g.free_symbols <= {k}]
def hilbert_dim(eqs):
    G = sp.groebner(eqs, x, y, z, order="grevlex"); lms = [sp.Poly(g.as_expr(), x, y, z).monoms(order="grevlex")[0] for g in G.polys]
    best = -1
    for rr in range(4):
        for S in itertools.combinations(range(3), rr):
            if all(any(e[i] > 0 for i in range(3) if i not in S) for e in lms): best = max(best, rr)
    return best

def ar4():
    out = {}
    # (i) the countermodel: V(x(x-1), xk) = the line x = 0 (k free) U the point (1, 0); eliminating x leaves nothing in k
    Gc = sp.groebner([x * (x - 1), x * k], x, k, order="lex"); out["countermodel_k_elimination"] = [str(g.as_expr()) for g in Gc.polys if g.free_symbols <= {k}]
    Gp = sp.groebner([x - 1, x * k], x, k, order="lex"); out["point_alone_k_elimination"] = [str(g.as_expr()) for g in Gp.polys if g.free_symbols <= {k}]
    out["countermodel_isolated_point_regular"] = sp.Matrix([x * (x - 1), x * k]).jacobian([x, k]).subs({x: 1, k: 0}).rank() == 2
    # (ii)-(iv) B130's fixed loci
    for m in (2, 3, 4):
        f = phi(m, (x, y, z)); eqs = [sp.expand(f[i] - v) for i, v in enumerate((x, y, z))]
        d = dict(k_elimination=[str(e) for e in k_elimination(eqs)] if m == 2 else "not recomputed (B130 recorded zero)", hilbert_dimension=hilbert_dim(eqs))
        if m == 2:
            G2 = sp.groebner(eqs, x, y, z, order="lex"); d["lex_basis"] = [str(sp.factor(g.as_expr())) for g in G2.polys]
            d["krull_no_zero_dim_component"] = len(G2.polys) == 2        # two generators in three variables: every component has dim >= 1
        out["m%d" % m] = d
    # (v) the Sage/Singular primary decomposition, recorded
    sage = open(HERE / "b130_components_sage.out").read()
    comps = {int(m): re.findall(r"component dim (\d)", block) for m, block in re.findall(r"m = (\d)  dim V\(J\) = \d(.*?)(?=m = \d|\Z)", sage, re.S)}
    out["sage_components"] = {m: dict(n=len(c), dims=sorted(set(int(v) for v in c))) for m, c in comps.items()}
    out["sage_no_zero_dim_component_m234"] = all(set(int(v) for v in comps[m]) == {1} and len(comps[m]) >= 2 for m in (2, 3, 4))
    return out

def main():
    a3, a4 = ar3(), ar4()
    ok3 = all(a3[kk] for kk in a3)
    ok4 = (a4["countermodel_k_elimination"] == [] and a4["point_alone_k_elimination"] == ["k"] and a4["countermodel_isolated_point_regular"]
           and a4["m2"]["k_elimination"] == [] and a4["m2"]["krull_no_zero_dim_component"] and all(a4["m%d" % m]["hilbert_dimension"] == 1 for m in (2, 3, 4))
           and a4["sage_no_zero_dim_component_m234"])
    out = dict(AR3=a3, AR4=a4, verdict="PASS" if ok3 and ok4 else "FAIL")
    json.dump(out, open(HERE / "two_corrections.json", "w"), indent=1, default=str)
    print(json.dumps(out, indent=1, default=str)[:3000]); print("VERDICT two-corrections: %s" % out["verdict"]); return 0 if ok3 and ok4 else 1

if __name__ == "__main__":
    sys.exit(main())
