#!/usr/bin/env python3
"""OI-031 -- B399 e3 exact (the depth-5 triple cubic t^3 - (1/48) t - e3).

The depth-5 (level-1215) m=1 singles support has 24 cells: 12 cells exactly 1/12
(the frozen line) + a Z/3 triple (three values, 4 cells each; one class mod 135,
splitting into classes {121,256,391} mod 405).  Banked (B399/phase-1a): e1 = 0
EXACT, e2 = -1/48 EXACT; e3 (the product of the three triple values) OPEN after
two failed CRT passes (6-prime and 10-prime reach; triple_cubic.json stamped
UNSTABLE -- denominator/prime collision, the under-determined-CRT artifact).

THIS CELL: reconstruct e3 exactly from the full banked 20-prime residue data
(frontier/B399_wall_scale/singles_1215*.json, all generated by one engine with
the deterministic primitive_root embedding), via CRT + LLL over a ladder of
real subfields of Q(zeta_4860), with
  (i)   structural gates on every prime (support, 1/12 line, e1, e2),
  (ii)  batch-split stability (primes 1-10 alone vs 11-20 alone vs all 20),
  (iii) both-direction verification: the closed form re-evaluated mod every
        prime through the same embedding, AND against an INDEPENDENT complex
        floating-point recomputation of the level-1215 cells (direct iterated
        powers of the exact unitary W1; a different method, different
        arithmetic), AND an exact cyclotomic factorization in Q[z]/Phi_27.

Sealed criterion: exact closed form in the banked field verified both
directions => RESOLVED-A; provably not at swept height => RESOLVED-B.

Re-runnable end-to-end:  python3 compute.py   (pyenv python3; needs sympy+numpy;
reads only the banked JSONs from frontier/B399_wall_scale/).
"""
import json, math, os, sys, time
from fractions import Fraction as F
from math import gcd

HERE = os.path.dirname(os.path.abspath(__file__))
B399 = os.path.normpath(os.path.join(HERE, "..", "..", "..", "B399_wall_scale"))

N, O1 = 1215, 1620          # level and single-seed order (engine constants)
T0 = time.time()
def log(*a):
    print(f"[{time.time()-T0:8.1f}s]", *a, flush=True)

# ---------------------------------------------------------------- data ------
FILES = ["singles_1215.json", "singles_1215_p3.json", "singles_1215_p456.json",
         "singles_1215_p7_10.json", "singles_1215_p11_20.json",
         "singles_1215_p14_20.json"]
DATA = {}
for f in FILES:
    DATA.update(json.load(open(os.path.join(B399, f))))
PRIMES = sorted(int(p) for p in DATA)
log("loaded", len(PRIMES), "primes:", PRIMES)
assert len(PRIMES) == 20, "expected the 20 banked primes"

def primitive_root(p):      # identical algorithm to census_big.primitive_root
    fac, n, d = [], p - 1, 2
    while d * d <= n:
        if n % d == 0:
            fac.append(d)
            while n % d == 0: n //= d
        d += 1
    if n > 1: fac.append(n)
    g = 2
    while True:
        if all(pow(g, (p - 1) // f, p) != 1 for f in fac): return g
        g += 1

# ------------------------------------------------- per-prime gates + e_i ---
E3 = {}                     # p -> e3 mod p
TRIPLE = {}                 # p -> {class mod 405: value}
for p in PRIMES:
    cells = {int(a): int(v) for a, v in DATA[str(p)].items()}
    assert len(cells) == 24, (p, len(cells))
    assert all(a % 45 == 31 for a in cells), ("mod-45 gate", p)
    inv12 = pow(12, p - 2, p)
    line = sorted(a for a, v in cells.items() if v == inv12)
    trip = sorted(a for a in cells if a not in line)
    assert len(line) == 12 and len(trip) == 12, ("line/triple split", p)
    # the triple: classes {121,256,391} mod 405, 4 cells each, constant per class
    byclass = {}
    for a in trip:
        byclass.setdefault(a % 405, set()).add(cells[a])
    assert sorted(byclass) == [121, 256, 391], ("triple classes", p, sorted(byclass))
    assert all(len(v) == 1 for v in byclass.values()), ("class constancy", p)
    v1, v2, v3 = (byclass[c].pop() for c in (121, 256, 391))
    e1 = (v1 + v2 + v3) % p
    e2 = (v1 * v2 + v1 * v3 + v2 * v3) % p
    assert e1 == 0, ("e1 gate", p, e1)
    assert e2 == (-pow(48, p - 2, p)) % p, ("e2 gate", p)
    E3[p] = v1 * v2 * v3 % p
    TRIPLE[p] = {121: v1, 256: v2, 391: v3}
log("all 20 primes pass the structural gates: 24 cells, mod-45=31, "
    "12x(1/12) line, triple constant on {121,256,391} mod 405, e1=0, e2=-1/48")

# ---------------------------------------------------------------- CRT ------
def crt(primes, vals):
    M = 1
    for p in primes: M *= p
    r = 0
    for v, p in zip(vals, primes):
        Mi = M // p
        r = (r + v * Mi * pow(Mi, -1, p)) % M
    return r, M

BATCHES = {"B1(primes 1-10)": PRIMES[:10],
           "B2(primes 11-20)": PRIMES[10:],
           "ALL(20)": PRIMES}

# ------------------------------------- embeddings of the real subfields ----
# All basis elements are explicit polynomials in zeta_m := g^((p-1)/m), the SAME
# deterministic embedding the data engine used (zN = g^((p-1)/1215) etc.), so
# every identity transfers prime-by-prime.  Numeric twins use the standard
# embedding zeta_m -> exp(2*pi*i/m), matching the float recomputation below.
def embed(p):
    g = primitive_root(p)
    z = lambda m: pow(g, (p - 1) // m, p)
    inv = lambda x: pow(x, p - 2, p)
    z5, z4, z3 = z(5), z(4), z(3)
    s5 = (z5 - pow(z5, 2, p) - pow(z5, 3, p) + pow(z5, 4, p)) % p   # sqrt5
    sm3 = (z3 - pow(z3, 2, p)) % p                                  # sqrt(-3)
    s3 = sm3 * inv(z4) % p                                          # sqrt3
    s15 = s5 * s3 % p                                               # sqrt15
    assert pow(s5, 2, p) == 5 and pow(s3, 2, p) == 3 and pow(s15, 2, p) == 15
    cosd = {}
    for m in (9, 15, 27, 45):
        zm = z(m)
        cosd[m] = (zm + inv(zm)) % p                                # 2cos(2pi/m)
    return dict(s5=s5, s3=s3, s15=s15, **{f"c{m}": cosd[m] for m in (9, 15, 27, 45)})

EMB = {p: embed(p) for p in PRIMES}
log("embedding gates pass on all primes (s5^2=5, s3^2=3, s15^2=15)")

TWO_PI = 2 * math.pi
NUMV = dict(s5=math.sqrt(5), s3=math.sqrt(3), s15=math.sqrt(15),
            **{f"c{m}": 2 * math.cos(TWO_PI / m) for m in (9, 15, 27, 45)})

def powbasis(sym, kmax):        # [(label, modfun, numval)] for sym^1..sym^kmax
    out = []
    for k in range(1, kmax + 1):
        out.append((f"{sym}^{k}" if k > 1 else sym,
                    (lambda p, s=sym, k=k: pow(EMB[p][s], k, p)),
                    NUMV[sym] ** k))
    return out

def prodbasis(sa, ea, sb, eb):  # sa^ea * sb^eb
    return (f"{sa}^{ea}*{sb}^{eb}",
            (lambda p, sa=sa, ea=ea, sb=sb, eb=eb:
             pow(EMB[p][sa], ea, p) * pow(EMB[p][sb], eb, p) % p),
            NUMV[sa] ** ea * NUMV[sb] ** eb)

FIELDS = [
    ("Q",                []),
    ("Q(sqrt5)",         powbasis("s5", 1)),
    ("Q(sqrt3)",         powbasis("s3", 1)),
    ("Q(sqrt15)",        powbasis("s15", 1)),
    ("Q(sqrt3,sqrt5)",   powbasis("s5", 1) + powbasis("s3", 1) + powbasis("s15", 1)),
    ("Q(zeta9)+",        powbasis("c9", 2)),
    ("Q(zeta15)+",       powbasis("c15", 3)),
    ("Q(zeta9)+*sqrt5",  powbasis("c9", 2) + powbasis("s5", 1)
                         + [prodbasis("s5", 1, "c9", k) for k in (1, 2)]),
    ("Q(zeta27)+",       powbasis("c27", 8)),
    ("Q(zeta45)+",       powbasis("c45", 11)),
    ("Q(zeta27)+*sqrt5", powbasis("c27", 8) + powbasis("s5", 1)
                         + [prodbasis("s5", 1, "c27", k) for k in range(1, 9)]),
]

# ----------------------------------------------------------------- LLL -----
# engine: python-flint fmpz_mat.lll (exact integer LLL); sympy DomainMatrix.lll
# as fallback (NB sympy 1.14's rational LLL hits an internal assertion on some
# of these 150-digit lattices -- flint is the primary engine).
try:
    import flint as _flint
    def lll_rows(rows):
        red = _flint.fmpz_mat([[int(x) for x in r] for r in rows]).lll()
        return [[int(red[i, j]) for j in range(red.ncols())]
                for i in range(red.nrows())]
    log("LLL engine: python-flint", _flint.__version__)
except ImportError:
    from sympy import ZZ
    from sympy.polys.matrices import DomainMatrix
    def lll_rows(rows):
        n, m = len(rows), len(rows[0])
        dm = DomainMatrix([[ZZ(int(x)) for x in r] for r in rows], (n, m), ZZ)
        return [[int(x) for x in r] for r in dm.lll().to_list()]
    log("LLL engine: sympy DomainMatrix.lll")

def hunt(field, basis, primes):
    """LLL-reconstruct e3 = (a0 + sum ai*bi)/den from the primes' residues.
    Returns (a0, [ai], den, vecnorm) or None.  Verifies on the given primes."""
    R, M = crt(primes, [E3[p] for p in primes])
    k = len(basis)
    B = [crt(primes, [bf(p) for p in primes])[0] for _, bf, _ in basis]
    rows = [[M] + [0] * (k + 1)]
    for i, b in enumerate(B):
        rows.append([b] + [1 if j == i else 0 for j in range(k)] + [0])
    rows.append([(-R) % M] + [0] * k + [1])
    red = lll_rows(rows)
    best = None
    for v in red:
        den = v[-1]
        if den == 0: continue
        a0, ai = -v[0], list(v[1:-1])
        if den < 0: a0, ai, den = -a0, [-x for x in ai], -den
        g = den
        for x in [a0] + ai: g = gcd(g, x)
        if g > 1: a0, ai, den = a0 // g, [x // g for x in ai], den // g
        ok = all((a0 + sum(a * bf(p) for a, (_, bf, _) in zip(ai, basis))
                  - den * E3[p]) % p == 0 for p in primes)
        if not ok: continue
        nrm = max(abs(x) for x in [a0, den] + ai)
        if best is None or nrm < best[3]: best = (a0, ai, den, nrm)
    return best

def fmt(a0, ai, den, basis):
    terms = ([f"{a0}"] if a0 or not ai else []) + \
            [f"{a:+d}*{lab}" for a, (lab, _, _) in zip(ai, basis) if a]
    return "(" + " ".join(terms or ["0"]) + f") / {den}"

def numval(a0, ai, den, basis):
    return (a0 + sum(a * nv for a, (_, _, nv) in zip(ai, basis))) / den

# --------------------------------------------------------- the hunt --------
log("=== field-ladder hunt (LLL on CRT residues) ===")
HIT = None
SWEEP = []          # (field, dim, per-batch results) for the bounded negative
for name, basis in FIELDS:
    dim = len(basis) + 2
    res = {}
    for bname, bp in BATCHES.items():
        t = time.time()
        r = hunt(name, basis, bp)
        res[bname] = r
        log(f"  {name:>18s} dim={dim:2d} {bname:16s} "
            f"{'MISS' if r is None else fmt(*r[:3], basis) + f'  (norm {r[3]})'}"
            f"  [{time.time()-t:.1f}s]")
    SWEEP.append((name, dim, res))
    r_all = res["ALL(20)"]
    if r_all is not None:
        a0, ai, den, nrm = r_all
        # margin: an honest hit must sit far below the lattice's noise floor
        Mall = 1
        for p in PRIMES: Mall *= p
        floor = int(Mall ** (1.0 / dim))
        stable = all(res[b] is not None and res[b][:3] == (a0, ai, den)
                     for b in BATCHES)
        collide = any(den % p == 0 for p in PRIMES)
        log(f"    candidate in {name}: norm {nrm:.3g} vs noise floor ~{floor:.3g}; "
            f"batch-stable={stable}; den/prime collision={collide}")
        if stable and not collide and nrm < floor / 10**6:
            HIT = (name, basis, a0, ai, den)
            log(f"    => ACCEPTED (batch-stable, collision-free, >6 orders below floor)")
            break
        log("    => rejected (fails the stability/collision/margin guard)")

# ------------------------------------------------ independent numeric leg --
# Independent engine: exact-unitary W1 over C, the FULL finite Fourier sum
# v_a = (1/1620) sum_k zeta_1620^{-ak} tr(R W1^k) by direct iterated powers
# (no eigendecomposition -- eigenvalue-binning was measured UNSTABLE at ~1e-7:
# LAPACK phase errors on the 1620th-root spectrum amplified by k~1600; the
# direct product of unitaries is stable to ~1e-13).  Error witnesses:
# W1^1620 = I (independent binary-powering probe), trs[1620-k] = conj(trs[k]),
# spot traces at assorted k via binary powering (a second computation order),
# the 4-cell class spreads, the 1/12 line, and the sum rule.
log("=== independent complex recomputation (direct powers of unitary W1) ===")
import numpy as np
j = np.arange(N)
zrow = np.exp(2j * np.pi * (j % N) / N)
K = (np.outer(j, j)) % N
Fm = zrow[K]
Dd = zrow[(j * (j - 1) // 2) % N]
Fi = np.conj(Fm) / N
WR = (Fm * np.conj(Dd)[None, :]) @ Fi
W1 = WR * Dd[None, :]
uerr = np.abs(W1 @ W1.conj().T - np.eye(N)).max()
log(f"unitarity |W1 W1* - I|_max = {uerr:.2e}")

def matpow(A, k):               # binary powering (independent order of ops)
    Q = np.eye(N, dtype=complex); B = A.copy()
    while k:
        if k & 1: Q = Q @ B
        B = B @ B; k >>= 1
    return Q

log(f"|W1^1620 - I|_max = {np.abs(matpow(W1, O1) - np.eye(N)).max():.2e} "
    "(the order-1620 claim, binary powering)")
ridx = (-j) % N
trs = np.empty(O1, dtype=complex)
P = np.eye(N, dtype=complex)
for k in range(O1):
    trs[k] = P[ridx, j].sum()   # tr(R W1^k)
    P = P @ W1
    if (k + 1) % 400 == 0: log(f"  {k+1}/{O1} powers")
log(f"|P_1620 - I|_max = {np.abs(P - np.eye(N)).max():.2e} (end-of-run drift)")
log(f"conj-symmetry max |trs[k] - conj(trs[1620-k])| = "
    f"{np.abs(trs[1:] - np.conj(trs[1:][::-1])).max():.2e}")
for k in (1, 5, 100, 777, 1619):
    d = abs(trs[k] - matpow(W1, k)[ridx, j].sum())
    log(f"  trace spot-check k={k:5d} (iterated vs binary powering): {d:.2e}")
vals = np.fft.fft(trs) / O1     # v_a = (1/O1) sum_k trs[k] e^{-2pi i a k/O1}
sup = sorted(int(a) for a in np.nonzero(np.abs(vals) > 1e-6)[0])
log(f"numeric support: {len(sup)} cells; equals F_p support: "
    f"{sup == sorted(int(a) for a in map(int, DATA[str(PRIMES[0])]))}")
imax = np.abs(vals.imag)[np.abs(vals) > 1e-6].max()
log(f"max |Im| on support = {imax:.2e}  (values are real)")
line_dev = max(abs(vals[a].real - 1 / 12) for a in sup if a % 405 not in (121, 256, 391))
log(f"1/12-line max deviation = {line_dev:.2e}")
tvals, tspread = [], 0.0
for c in (121, 256, 391):
    cs = [vals[a].real for a in sup if a % 405 == c]
    assert len(cs) == 4
    tvals.append(float(np.mean(cs)))
    tspread = max(tspread, max(cs) - min(cs))
log(f"triple values (4-cell class means, spread {tspread:.2e}):")
for c, v in zip((121, 256, 391), tvals): log(f"   class {c}: {v:+.15f}")
e1n = sum(tvals)
e2n = tvals[0]*tvals[1] + tvals[0]*tvals[2] + tvals[1]*tvals[2]
e3n = tvals[0]*tvals[1]*tvals[2]
log(f"numeric e1 = {e1n:+.3e} (banked 0)")
log(f"numeric e2 = {e2n:+.15f} vs -1/48 = {-1/48:+.15f}  (diff {abs(e2n + 1/48):.2e})")
log(f"numeric e3 = {e3n:+.18f}")
ssum = float(np.sum(vals[sup].real))
log(f"sum rule Sigma_support = {ssum:.15f} (banked 1)")
# the roots themselves: cos(2 pi k / 27)/6 for k = 10, 19, 1 (classes 121/256/391)
ROOTK = {121: 10, 256: 19, 391: 1}
rootdev = max(abs(tv - math.cos(TWO_PI * ROOTK[c] / 27) / 6)
              for tv, c in zip(tvals, (121, 256, 391)))
log(f"root identification: class c -> cos(2*pi*k/27)/6, k = {ROOTK}; "
    f"max |numeric - root| = {rootdev:.2e}")

# --------------------------- exact cyclotomic factorization (sympy, exact) --
# In Q[z]/Phi_27(z) (z = zeta_27, Phi_27 = z^18 + z^9 + 1), verify EXACTLY:
#   prod_{k in {1,10,19}} (t - (z^k + z^{27-k})/12)
#      =  t^3 - (1/48) t - (z^3 + z^{24})/1728,
# i.e. the triple {2cos(2pi k/27)/12} has e1 = 0, e2 = -1/48,
# e3 = 2cos(2pi/9)/1728 as an algebraic identity (not a float statement).
log("=== exact cyclotomic factorization check (Q[z]/Phi_27) ===")
import sympy as sp
zs = sp.symbols('z')
PHI = sp.Poly(zs**18 + zs**9 + 1, zs, domain=sp.QQ)
def red(expr):
    return sp.Poly(sp.expand(expr), zs, domain=sp.QQ).rem(PHI)
rz = {k: (zs**k + zs**(27 - k)) for k in (1, 10, 19)}    # 12 * root_k
S1 = red(sum(rz.values()))
S2 = red(rz[1]*rz[10] + rz[1]*rz[19] + rz[10]*rz[19])
S3 = red(rz[1]*rz[10]*rz[19])
c9_z = zs**3 + zs**24                                     # 2cos(2pi/9) as z-poly
ok1 = S1.is_zero
ok2 = red(S2.as_expr() + 3*sp.Integer(1)).is_zero         # e2*144 = -3 -> e2 = -1/48
ok3 = red(S3.as_expr() - c9_z).is_zero                    # e3*1728 = 2cos(2pi/9)
log(f"sum(12t_k) == 0:                 {ok1}")
log(f"e2 = -3/144 = -1/48 exactly:     {ok2}  (sum of pair products of 12t_k = -3)")
log(f"e3 = 2cos(2pi/9)/1728 exactly:   {ok3}  (product of 12t_k = z^3 + z^-3)")
EXACT_FACT = ok1 and ok2 and ok3

# ------------------------------------------------------------- verdict -----
log("=== verdict ===")
summary = dict(cell="OI-031", primes=PRIMES,
               e1="0 (regated on 20 primes + numeric)",
               e2="-1/48 (regated on 20 primes + numeric)")
if HIT:
    name, basis, a0, ai, den = HIT
    form = fmt(a0, ai, den, basis)
    ev = numval(a0, ai, den, basis)
    diff = abs(ev - e3n)
    digits = -math.log10(diff / abs(e3n)) if diff else 18
    log(f"e3 = {form}   in {name}")
    log(f"closed form numerically = {ev:+.18f}")
    log(f"independent float e3    = {e3n:+.18f}")
    log(f"agreement: {diff:.2e} absolute, ~{digits:.1f} significant digits")
    # both directions, direction 2 restated: form -> residues on all 20 primes
    okall = all((a0 + sum(a * bf(p) for a, (_, bf, _) in zip(ai, basis))
                 - den * E3[p]) % p == 0 for p in PRIMES)
    log(f"form reproduces all 20 prime residues: {okall}")
    # the cubic's discriminant: three real roots demand |e3| < 1/864
    log(f"|e3| = {abs(ev):.6e} < 1/864 = {1/864:.6e} (real-triple bound): "
        f"{abs(ev) < 1/864}")
    log(f"exact cyclotomic factorization of the cubic: {EXACT_FACT}")
    verdict = ("RESOLVED-A" if (okall and digits >= 10 and EXACT_FACT)
               else "UNRESOLVED")
    summary.update(verdict=verdict, field=name, e3=form,
                   e3_closed_form="2*cos(2*pi/9)/1728 = cos(2*pi/9)/864",
                   triple_roots="t_c = cos(2*pi*k/27)/6, k=10,19,1 for "
                                "classes c=121,256,391 (exact, root_dev "
                                f"{rootdev:.1e})",
                   exact_factorization=EXACT_FACT,
                   e3_numeric=e3n, e3_form_value=ev, agree_digits=round(digits, 1))
else:
    # bounded negative: report the per-field swept heights
    log("no closed form found; swept heights (guaranteed-recovery coefficient "
        "bounds ~ M^(1/dim)/2^((dim-1)/2), M = 20-prime modulus):")
    Mall = 1
    for p in PRIMES: Mall *= p
    neg = {}
    for name, dim, _ in SWEEP:
        bound = int(Mall ** (1.0 / dim) / 2 ** ((dim - 1) / 2))
        neg[name] = f"1e{len(str(bound)) - 1}"
        log(f"   {name:>18s} dim {dim:2d}: height < ~{bound:.2e}")
    verdict = "RESOLVED-B"
    summary.update(verdict=verdict, swept=neg, e3_numeric=e3n)
log("VERDICT:", verdict)
print(json.dumps(summary, indent=1, default=str))
