"""B1135 lock -- THE GAUGE CLOSING: the factor-preserving branch closes into E6(-14)
(compact heart so(10)); B1119's checksum set is a functional taxonomy of the five real forms.
Verified two-bench; results pinned in b1135_results.json (regenerated by
verify_gauge_closing.py; full independent sweep re-runs under OA_SLOW)."""
import json
import os
import subprocess
import sys
from pathlib import Path
import pytest

ARC = Path(__file__).resolve().parents[1] / "frontier" / "B1135_gauge_closing"
RESULTS = ARC / "b1135_results.json"
CHECKSUM = {6, 2, -14, -26, -78}  # the five real forms of e6 (B1119)


def _load():
    return json.loads(RESULTS.read_text(encoding="utf-8"))


def test_counts():
    d = _load()
    assert d["n_factor_preserving_involutions"] == 128
    assert d["n_inW"] == 64 and d["n_outer"] == 64
    assert d["n_pairs_total"] == 2000
    assert d["elements_with_no_lift"] == 0


def test_full_menu_exact():
    d = _load()
    assert d["menu"] == {
        "((5, 3), (5, 3), (5, 3))|+6": 1000,
        "((4, 4), (4, 4), (4, 4))|+2": 729,
        "((4, 4), (0, 8), (4, 4))|-14": 81,
        "((0, 8), (4, 4), (4, 4))|-14": 81,
        "((0, 8), (0, 8), (4, 4))|+2": 9,
        "((4, 4), (4, 4), (0, 8))|-14": 81,
        "((4, 4), (0, 8), (0, 8))|+2": 9,
        "((0, 8), (4, 4), (0, 8))|+2": 9,
        "((0, 8), (0, 8), (0, 8))|-78": 1,
    }


def test_w_coset_sterile():
    d = _load()
    # no compact slot without the diagram flip
    assert d["w_coset_sterile_tally"] == {"((5, 3), (5, 3), (5, 3))|+6": 1000}


def test_flip_factorization_and_character_map():
    d = _load()
    # global form is a function of the compact-slot count alone (binomial C(3,k)*9^(3-k))
    assert d["compact_count_to_char"] == {"(0, 2)": 729, "(1, -14)": 243, "(2, 2)": 27, "(3, -78)": 1}
    # the physics row: one compact slot -> E6(-14), 243 of them
    assert d["compact_count_to_char"]["(1, -14)"] == 243
    assert 729 + 243 + 27 + 1 == 1000


def test_checksum_is_the_five_form_taxonomy():
    d = _load()
    seen = {int(k) for k in d["checksum_chars_witnessed"]}
    assert seen <= CHECKSUM                 # no instrument break
    assert -26 not in seen                  # needs the swap; F-1 disjoint from B1134
    assert d["checksum_compact_dim_mismatches"] == 0   # compact dim = the form's, on every pair


def test_findings_states_theorem_and_fences():
    f = " ".join((ARC / "FINDINGS.md").read_text(encoding="utf-8").split())
    assert "GAUGE CLOSING" in f
    assert "E₆(−14)" in f and "so(10)" in f
    assert "functional taxonomy" in f or "five things an observer" in f
    assert "FRAME CHOICE" in f or "frame choice" in f
    assert "Gate 5 untouched" in f


@pytest.mark.skipif(not os.environ.get("OA_SLOW"),
                    reason="full factor-preserving e6 sweep ~320s; set OA_SLOW=1 to run")
def test_full_sweep_reproduces_OA_SLOW():
    r = subprocess.run([sys.executable, str(ARC / "verify_gauge_closing.py")],
                       cwd=str(ARC), capture_output=True, text=True, timeout=1800)
    assert r.returncode == 0, r.stderr[-3000:]
    d = _load()
    assert d["compact_count_to_char"]["(1, -14)"] == 243
    assert d["menu"]["((0, 8), (0, 8), (0, 8))|-78"] == 1
