"""B739 lock -- character-rigidity of m004's continuous spectrum: the Fourier-restriction coset sum,
the covering-invariant residue triangle, and the single-cusp exhaustion scaffold. Pure math (Gate 5).
"""
import mpmath as mp
import pytest
mp.mp.dps = 40

def test_fourier_restriction_coset_character_sum():
    # Lambda = Z + 2sqrt(-3)Z inside O = Z[w]; O/Lambda = Z/4 (index 4, generated by w).
    # For mu in O^dual (dual basis coords), the coset sum over r in O/Lambda of e(<mu, r>) = 4*[mu in O^dual-of-O],
    # i.e. characters nontrivial on the Z/4 coset group sum to ZERO -> pullback Fourier support stays in O^dual.
    # Model the coset group by k=0..3 (r = k*w mod Lambda); a dual class acts as i^{k*m} for m=0,1,2,3.
    for m in range(4):
        ssum = sum(mp.expjpi(mp.mpf(k*m)/2) for k in range(4))   # e^{2pi i km/4} = e^{i pi km/2}
        if m == 0:
            assert abs(ssum - 4) < mp.mpf("1e-30")  # trivial on the cosets: survives (support in O^dual)
        else:
            assert abs(ssum) < mp.mpf("1e-30")      # nontrivial: annihilated -> no room for level characters

def test_residue_triangle_covering_invariant():
    snappy = pytest.importorskip("snappy")
    vol = mp.mpf(str(snappy.ManifoldHP("m004").volume()))
    def L3(s): return 3**(-mp.mpf(s))*(mp.zeta(s, mp.mpf(1)/3) - mp.zeta(s, mp.mpf(2)/3))
    zK2 = mp.zeta(2)*L3(2)
    res_phi = 2*mp.pi**2/(9*zK2)
    vol_orb = 3**mp.mpf(1.5)*zK2/(4*mp.pi**2)
    # the triangle: analytic = base-geometric = cover-geometric  (covol(cusp)/vol is covering-invariant)
    assert abs(res_phi - (mp.sqrt(3)/6)/vol_orb) < mp.mpf("1e-25")
    assert abs(res_phi - 2*mp.sqrt(3)/vol) < mp.mpf("1e-15")
    assert abs(vol/vol_orb - 12) < mp.mpf("1e-12")     # degree 12 = 4 (cusp lattice) x 3 (rotation)

def test_single_cusp_single_channel():
    snappy = pytest.importorskip("snappy")
    M = snappy.Manifold("m004")
    assert len([c for c in M.cusp_info() if c.is_complete]) == 1
    # multiplicity of the continuous spectrum = #cusps = 1 (Sarnak p.264 / Friedman Lemma 2.1):
    # ONE Eisenstein channel -> phi is 1x1 -> carries Lambda_K(s-1)/Lambda_K(s) and nothing else.
