"""B1356 lock (about a minute): on the flat Y_3 the deck fixes exactly one closed geodesic and the descent orbifold P2_1 3 has one cone
circle and no 2-fold axes; the local group along the knot generated by the E_6 fibre 2T and the deck is 2T x Z_3 of order 72 inside
SU(3), with two A_2 loci and McKay ages 15 / 5 (b_2 - b_4 = 10 = 6 + 2 + 2); the sum-zero lattice has no deck invariants and the
deck orbit of (1,1,-2) is 3 x the weights of the 3-bar; the -1 of an E_6 point on S^4/Gamma fixes the antipode and only +-1 of 2T acts
trivially on the twistor fibre of CP^2."""
import sys, subprocess
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
VER = ROOT / "frontier" / "B1356_the_three_on_y3" / "verification"


def test_the_deck_fixes_the_knot_only_and_the_descent_forces_two_a2_loci_with_ages_15_5():
    out = subprocess.run([sys.executable, str(VER / "three_on_y3.py")], capture_output=True, text=True, timeout=1500).stdout
    assert "order-2 linear parts: 3 screws (2_1), 0 rotations  -> Pi torsion-free and no 2-fold cone axes: True" in out
    assert "V_4-orbits of these circles = components of Fix(sigma) on Y_3: 1" in out
    assert "Pi^-orbits of the axes = singular circles of the orbifold R^3/Pi^: 1" in out
    assert "r in 2O with r^3 in 2T (so that the deck has order 3 modulo the fibre group): 24 of 48, all in 2T: True" in out
    assert "the same group for every admissible r (the fibre group absorbs r): True" in out
    assert "group = fibre x <central order-3 element>: True" in out
    assert "every element is C-linear for J and has det 1 (the group lies in SU(3) = Stab_G2(e)): True" in out
    assert "G-orbits of the fibre planes = number of A_2 loci through the knot: 2 (sizes [4, 4])" in out
    assert "ages: {Fraction(0, 1): 1, Fraction(1, 1): 15, Fraction(2, 1): 5}" in out
    assert "non-compact exceptional divisors b_2 - b_4 = 10 = 6 (E_6) + 2 (A_2) + 2 (A_2): True" in out
    assert "generates a group of order 24 in the first Sp(1): 2T itself (True)" in out
    assert "invariants of the deck inside the sum-zero lattice A_2: 0" in out
    assert "equals the orbit as a set: True" in out
    assert "fixed subspace of R^5 has dimension 1" in out
    assert "acting trivially on the twistor fibre P(C^2) of CP^2: 2 " in out
    assert "stage D (antipode; no E_6 on CP^2/Gamma): True" in out
