"""The paper's chain table must stay equal to the ledger it summarises.

Two external referees demanded the 43 links be enumerated rather than described. They now are,
generated from docs/THEOREM_LEDGER.md. These tests keep the generated table and the paper's prose
claims tied to the ledger, so the shape can never again be asserted without its contents.
"""
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "checks" / "paper_chain_table.py"
PAPER = ROOT / "papers" / "P3_THE_PAPER" / "main.tex"


def _run(*a):
    return subprocess.run([sys.executable, str(SCRIPT), *a],
                          capture_output=True, text=True, cwd=str(ROOT))


def test_forty_three_links_with_the_stated_tally():
    out = _run().stdout
    assert "links parsed: 43" in out, out
    for frag in ("'THEOREM': 26", "'IDENTITY': 6", "'NO-GO': 5",
                 "'AXIOM': 4", "'CENSUS': 1", "'COROLLARY': 1"):
        assert frag in out, (frag, out)
    assert "forced: 39" in out, out


def test_the_axiom_free_stretch_is_real():
    """The paper's strongest structural claim, checked against the ledger not the prose."""
    out = _run().stdout
    assert "axioms at: [3, 4, 5, 18]" in out, out
    assert "axioms inside C6-C17: NONE" in out, out


def test_generator_emits_no_unicode_that_kills_the_build():
    """A U+2084 from a link title produced a fatal LaTeX error once; the generator now
    translates and raises loudly rather than emitting an unbuildable character."""
    r = _run("--tex")
    assert r.returncode == 0, r.stdout + r.stderr
    assert all(ord(c) < 128 for c in r.stdout), "non-ASCII escaped into the generated table"


def test_paper_carries_the_generated_table_not_a_stale_copy():
    tex = PAPER.read_text(encoding="utf-8")
    assert "GENERATED by scripts/checks/paper_chain_table.py" in tex
    gen = _run("--tex").stdout
    rows = [l for l in gen.splitlines() if re.match(r"^\d+ & ", l)]
    assert len(rows) == 43, len(rows)
    for row in rows[:6] + rows[-3:]:
        assert row in tex, f"chain table is stale, regenerate: {row[:60]}"
