"""B1525 lock -- GENESIS v1.5 (2026-10-03; not sealed: every item checks a claim the record already fixes).
Main's v1.4 (B1458) is the head; the SM seat's v1.3 (sm:B1521) is answered by its line; the levels (sm:B1522), the word states
(sm:B1523), the bar's null contract (sm:B1524) and the audit lane's GAP3 refinement (24c039c8) are added. Locked here:
- the received texts by sha-256, and the audit lane's relay against its git blob where that commit is in the clone;
- GENESIS.md regenerated byte for byte from main's v1.4 by the arc's generator;
- the record (genesis_v15_checks.json): C1-C6 pass, with their numbers, before and after GENESIS.md was written;
- live: C2's third route on M1..M8 against B1522's census, and C3-C6 in full (C1 re-runs sm:B1521's scripts, which
  sm:B1521's own lock runs live);
- GENESIS v1.5's text: version, marks, the added sentences, the statuses, and the qualifier on B1522's criterion;
- Gate 5-Q's three words (encoded here), vendor words and the private term: absent from GENESIS.md and the arc's text, with a
  control in each direction (the check finds the third word in the received v1.3);
- the arc's text and ledgers: FINDINGS, verdict, ERROR_LEDGER, RELAY_LEDGER, the relay, OPEN_LEADS, B1522's note.
Since v1.6 (sm:B1526, 2026-10-03) GENESIS.md is main's v1.5 plus marked [v1.6] changes. v1.5's text is kept byte-identical in
B1526's arc as received (`received/GENESIS_v1_5_sm.md`), and the tests below that read v1.5 read it there; B1526's lock
checks GENESIS.md."""
import base64
import hashlib
import importlib.util
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ARC = ROOT / "frontier" / "B1525_genesis_v15"
VER = ARC / "verification"
REC = ARC / "received"
V14, V13 = REC / "GENESIS_v1_4_main.md", REC / "GENESIS_v1_3_sm.md"
RELAY_IN = REC / "CODEX_TO_CC_AND_SM_2026-10-03_HARVEST_REPLY_AND_ADMISSION_SCOPE.md"
RELAY_OUT = ROOT / "SM_TO_CC_AND_CODEX_2026-10-03_GENESIS_V1_5.md"
V15_KEPT = ROOT / "frontier" / "B1526_genesis_v16" / "received" / "GENESIS_v1_5_sm.md"
MARK = "**[v1.5]**"
Q5 = [base64.b64decode(t).decode() for t in ("cXVhbGlh", "YXdhcmU=", "c2Vlcw==")]
VENDOR = [base64.b64decode(t).decode() for t in ("Y2xhdWRl", "YW50aHJvcGlj", "b3B1cw==", "c29ubmV0", "ZmFibGU=")]
PRIVATE = bytes([98, 114, 97, 118, 101]).decode()


def _chk():
    """the arc's checks, loaded from their own file (a module of the same name elsewhere must not shadow them)"""
    spec = importlib.util.spec_from_file_location("b1525_genesis_v15_checks", VER / "genesis_v15_checks.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _sha(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()


def _q5(text):
    return [i + 1 for i, w in enumerate(Q5) if re.search(r"\b" + w + r"\b", text, re.I)]


def _norm(text):
    return " ".join(text.split())


# ------------------------------------------------------------------------------------------------- the received texts
def test_the_received_texts():
    assert _sha(V14) == "d32456b67ae2cb55e036de57c2a8619a8e546b7656144c1cf7ab008615bd557a"
    assert _sha(V13) == "d675c0fd663c354ebed70fa3ea80e3232b2829f3d9c9c03e55953c85ce1c77c0"
    assert _sha(RELAY_IN) == "a6975527c7443f690184ad1c5e66b60a394fdac4f1f24217f2f4815dc19e3307"
    # the git blob ids, which any clone can recompute
    blob = lambda p: subprocess.run(["git", "hash-object", str(p)], capture_output=True, text=True, check=True).stdout.strip()
    assert blob(V14) == "fb43bc77aa9e2779662d7d576b3ea9935ae9a860"
    assert blob(V13) == "8b2b57f65c592c5c2d36b06df65e2f4b87aebe36"
    assert blob(RELAY_IN) == "a5b4ecafcbff3cad84b4470cea098e13094d950d"


def test_genesis_is_the_generator_output(tmp_path):
    out = tmp_path / "G.md"
    r = subprocess.run([sys.executable, str(VER / "merge_genesis_v15.py"), str(V14), str(out)],
                       capture_output=True, text=True, timeout=120)
    assert r.returncode == 0, r.stderr
    assert out.read_bytes() == V15_KEPT.read_bytes()
    assert _sha(V15_KEPT) == "3e3b3d7bcfdf2eac3155419a45fd8a32f07c1e79588f74fa4e2a16082ca1b6f3"
    assert "[v1.5] marks: 16" in r.stdout


# ------------------------------------------------------------------------------------------------- the record
def test_the_record():
    d = json.loads((VER / "genesis_v15_checks.json").read_text(encoding="utf-8"))
    assert d["checks"] == {f"C{i}": True for i in range(1, 7)} and d["GENESIS.md is the generated v1.5"] is True
    pre = (VER / "genesis_v15_checks_prewrite_run.txt").read_text(encoding="utf-8")
    post = (VER / "genesis_v15_checks_run.txt").read_text(encoding="utf-8")
    assert "ALL CHECKS PASS" in pre and "GENESIS.md is the generated v1.5: False" in pre
    assert "ALL CHECKS PASS" in post and "GENESIS.md is the generated v1.5: True" in post
    c1 = d["C1 sm:B1521's checks re-run"]
    assert c1["which_class_is_P.json byte-identical to the record"] and c1["audit_corrections.json byte-identical to the record"]
    c2 = d["C2 the levels (sm:B1522), a third route"]
    rows = c2["levels (third route)"]
    want = {5: (121, 20, 0), 6: (320, 96, 96), 7: (841, 448, 392), 11: (39601, 35244, 34848), 12: (103680, 93936, 93936),
            13: (271441, 257920, 256880)}
    for n, (D, off, on) in want.items():
        r = rows[str(n)]
        assert (r["|T_n|"], r["unfixed off the circle"], r["unfixed on it"]) == (D, off, on) and r["the record agrees"]
    assert all(rows[str(n)]["unfixed off the circle"] == 0 for n in range(1, 5))
    assert c2["breaks first: off the circle, on it"] == [5, 6] and c2["shares off the circle, M5..M12"]["12"] == 0.91
    c3 = d["C3 the word states (sm:B1523), own word code"]
    assert c3["mirror-broken manifolds, per sign, states"] == [262, {"+": 131, "-": 131}, 482]
    assert c3["golden mirror-broken"] == ["+LLLLRLLLRR", "+LLLLRLRRRLRR", "-LLLLRLLLRR", "-LLLLRLRRRLRR"]
    c6 = d["C6 v1.5 against main's v1.4"]
    assert c6["main's words deleted or re-punctuated"] == _chk().EXPECTED_DELETIONS
    assert c6["[v1.5] marks"] == 16 and c6["changed blocks without a mark"] == []
    assert c6["Q5's words found, by place in its list: v1.5, v1.4, the SM seat's v1.3"] == [[], [], [3]]


# ------------------------------------------------------------------------------------------------- live
def test_c2_the_levels_live():
    chk = _chk()
    census = json.loads((ROOT / "frontier" / "B1522_the_golden_choice" / "verification" / "census.json")
                        .read_text(encoding="utf-8"))
    rec = {lv["n"]: lv for lv in census["levels"]}
    for n in range(1, 9):
        D, off, on = chk.level_counts(n)
        assert (D, off, on) == (rec[n]["order"], rec[n]["unfixed at generic lam"], rec[n]["unfixed at unitary lam"]), n
        assert D == chk.lucas(2 * n) - 2
    for n, p in ((5, 11), (7, 29)):
        D, off, on = chk.level_counts(n)
        assert (off, on) == ((p - 1) * (p + 1 - 2 * n), (p - 1) * (p - 1 - 2 * n))


def test_c6_catches_what_it_is_for():
    """planted controls for C6's diff: an unmarked insertion, a changed word of main's and a removed line are each caught"""
    chk = _chk()
    v14, v15 = V14.read_text(encoding="utf-8"), V15_KEPT.read_text(encoding="utf-8")
    deleted, unmarked = chk.diff_report(v14, v15)
    assert deleted == chk.EXPECTED_DELETIONS and unmarked == []
    head = "## 2. The grammar: what a description is made of"
    assert v15.count(head) == 1
    assert chk.diff_report(v14, v15.replace(head, "A planted unmarked sentence.\n\n" + head))[1] != []
    word = "Every legal state belongs to the state space"
    assert v15.count(word) == 1
    assert chk.diff_report(v14, v15.replace(word, "Every legal state lies in the state space"))[0] != chk.EXPECTED_DELETIONS
    lines = v15.split("\n")
    del lines[100]
    d, u = chk.diff_report(v14, "\n".join(lines))
    assert d != chk.EXPECTED_DELETIONS and u != []


def test_c3_to_c6_live():
    chk = _chk()
    assert chk.c3()["passed"] and chk.c4()["passed"]
    c6, v15 = chk.c6()
    assert c6["passed"] and v15 == V15_KEPT.read_text(encoding="utf-8")
    assert chk.c5(v15)["passed"]


# ------------------------------------------------------------------------------------------------- GENESIS v1.5
def test_genesis_v15_text():
    raw = V15_KEPT.read_text(encoding="utf-8")
    g = _norm(raw)
    v14 = V14.read_text(encoding="utf-8")
    assert raw.startswith("# GENESIS — the foundations of origin-axiom")
    assert "**Version 1.5 · 2026-10-03 · canonical.**" in raw and raw.count(MARK) == 16
    for m in ("**[v1.1]**", "**[v1.2]**", "**[v1.3]**", "**[v1.4]**"):
        assert raw.count(m) == v14.count(m), m
    for s in ("v1.5 (sm:B1525) takes main's head, v1.4, as main asked of its v1.3.",
              "breaks from M₅ on, off the unit circle exactly where no golden Galois reflection fixes the twist",
              "off the circle it breaks exactly where no golden Galois reflection fixes the twist",
              "on 262 of the 536 manifolds no isometry dualises it (sm:B1523)",
              "so near the hyperbolic point B1455's symmetry argument cannot force the count to zero there (Lemma T, a local statement)",
              "of the 14 manifolds with golden monodromy field exactly ±L⁴RL³R² and ±L⁴RLR³LR² are mirror-broken",
              "graded DERIVED (**[v1.5]** PASSED since sm:B1524: a rarity screen, not a derivation)",
              "renames the top grade PASSED",
              "The audit lane's results do not prove that a one-ended state can get the third only from a relation.",
              "B1297's period-2 symmetry P is the swap's class and fixes ρ_q",
              "an elimination that cannot exclude isolated components (the audit lane's AR4)",
              "the experiential question, an explicit hypothesis held under Gate 5-Q",
              "the class index on the projective family of a mirror-broken word state, first ±LLRLRR and ±L³RLR²",
              "- **v1.5 · 2026-10-03 · sm:B1525.**",
              "Not carried: the SM seat's quotation of main's B1455 §5 at FK12.",
              "Left to main: its B1459",
              "- **v1.4 · 2026-10-03 · main B1458.**"):
        assert _norm(s) in g, s
    assert "A one-ended state can get the third only from a relation" not in raw
    # no status changed: the fork table's first three cells are main's
    fk = lambda text: [l.split("|")[1:4] for l in text.splitlines() if re.match(r"\| FK\d+", l)]
    assert fk(raw) == fk(v14) and len(fk(raw)) == 12
    for row in ("| FK9 | Selection: what makes a state physical | OPEN |", "| FK11 | The dictionary (I-26) | UNEARNED |"):
        assert row in raw


def test_firewall_with_controls_both_ways():
    raw = V15_KEPT.read_text(encoding="utf-8")
    assert _q5(raw) == [] and _q5(V14.read_text(encoding="utf-8")) == []
    assert _q5(V13.read_text(encoding="utf-8")) == [3]          # the check can fire: the slip v1.5 removes
    assert _q5("the count " + Q5[2] + " only") == [3] and _q5("seesaw") == []
    assert not any(re.search(re.escape(w), raw, re.I) for w in VENDOR) and PRIVATE not in raw.lower()


def test_hygiene():
    files = [ARC / "FINDINGS.md", ARC / "arc_verdict.json", RELAY_OUT] + sorted(VER.glob("*.py")) + \
        sorted(VER.glob("*.json")) + sorted(VER.glob("*.txt"))
    for f in files:
        t = f.read_text(encoding="utf-8")
        assert _q5(t) == [], f.name
        assert not any(re.search(re.escape(w), t, re.I) for w in VENDOR), f.name
        assert PRIVATE not in t.lower(), f.name


# ------------------------------------------------------------------------------------------------- the arc's text and ledgers
def test_findings_and_verdict():
    f = (ARC / "FINDINGS.md").read_text(encoding="utf-8")
    assert f.startswith("# B1525 — GENESIS v1.5: MAIN'S v1.4 AS THE HEAD")
    sec = re.search(r"(?ms)^##[^\n]*Seen first[^\n]*\n(.*?)(?=^## |\Z)", f)
    assert sec and "sweep" in sec.group(1).lower() and "literature" in sec.group(1).lower()
    t = _norm(f)
    for s in ("**Verdict: PROVED.**", "**Not sealed.**", "**creates_law is false.**", "0 of 19", "I-26 stays UNEARNED",
              "## 2. The SM seat's v1.3 (sm:B1521), answered by its line", "### 4.1 Q5's third word at GENESIS FK12",
              "### 4.2 B1522's criterion without its qualifier (E53 class)", "**Standing: RE-DERIVED.**",
              "| 13 | 271 441 | 257 920 | 256 880 | equal (X5, `lemma_f_beyond.json`) |"):
        assert _norm(s) in t, s
    v = json.loads((ARC / "arc_verdict.json").read_text(encoding="utf-8"))
    assert v["id"] == "B1525" and v["verdict"] == "PROVED" and v["creates_law"] is False and v["identifications"] == []
    assert v["prior_work"]["standing"] == "RE-DERIVED" and v["scope"]["reach"] == "general"
    assert "|" not in v["claim_one_line"] and "0 of 19" in v["claim_one_line"]
    sys.path.insert(0, str(ROOT / "scripts" / "checks"))
    import prior_work
    assert prior_work.validate(v["prior_work"]) == []


def test_ledgers_and_surfaces():
    err = (ROOT / "docs" / "ERROR_LEDGER.md").read_text(encoding="utf-8")
    assert "| E84 instance (main's class, the CITED-ABSENT CHECK; 2026-10-03, sm:B1521's lock and GENESIS v1.3)" in err
    assert "| E53 instance (2026-10-03, sm:B1522's headline)" in err
    rl = (ROOT / "docs" / "RELAY_LEDGER.md").read_text(encoding="utf-8")
    assert "| `CC_TO_SM_2026-10-02_GENESIS_V1_3_AND_YOUR_FOUR_ARCS.md` | BANKED | 2026-10-03 |" in rl
    assert "| `CODEX_TO_CC_AND_SM_2026-10-03_HARVEST_REPLY_AND_ADMISSION_SCOPE.md` | BANKED | 2026-10-03 |" in rl
    assert "| `SM_TO_CC_AND_CODEX_2026-10-03_GENESIS_V1_5.md` | OPEN | 2026-10-03 |" in rl
    relay = _norm(RELAY_OUT.read_text(encoding="utf-8"))
    for s in ("Your v1.4 is the head.", "Off the unit circle it breaks exactly where no golden Galois reflection fixes the twist",
              "Your B1459", "GENESIS GAP3"):
        assert s in relay, s
    leads = _norm((ROOT / "docs" / "OPEN_LEADS.md").read_text(encoding="utf-8"))
    assert "[2026-10-03, sm:B1525] GENESIS v1.5." in leads
    assert "Galois reflection fixes the twist [2026-10-03, sm:B1525: off the unit circle;" in leads
    b1522 = (ROOT / "frontier" / "B1522_the_golden_choice" / "FINDINGS.md").read_text(encoding="utf-8")
    assert "*Note (2026-10-03, sm:B1525).* The title's" in b1522
    reg = (ROOT / "docs" / "THEOREM_REGISTRY.md").read_text(encoding="utf-8")
    assert "*[2026-10-03, sm:B1525: off the unit circle; on it the golden rotations also act, as (C) states.]*" in reg
