"""The cascade rungs are Levi subalgebras, and their types are forced by root count.

Closes the proof auditor's D1 downstream half.  The upstream half -- that the charge
algebra C is TORAL, not merely abelian -- is proved in the paper (Lemma "abelian fixed
algebras are toral") and needs no computation.  Given it, every centralizer z(S) for
S contained in C is a Levi subalgebra of e6, so

    dim z(S) = 6 + |Phi_S|,   Phi_S = Phi intersect S-perp,

and Phi_S is W-conjugate to the subsystem generated by a subset of the simple roots.
Enumerating all 2^6 = 64 such subsets therefore enumerates every rung that can occur.

What this test establishes:

  * at root counts 40, 24, 20 and 8 -- dimensions 46, 30, 26 and 14 -- exactly one Levi
    isomorphism type occurs, so the terminus A2+A1 is FORCED by classification and the
    exact computation contributes only the integer 14;
  * at root counts 6, 12 and 14 -- dimensions 12, 18 and 20 -- two types occur, so the
    paper does NOT claim a type at any of them.  This test pins all three so no later
    draft can quietly assert one.  ## The dim-20 case was MISSED by an earlier draft,
    which named only 12 and 18, even though the enumeration below had printed both types
    at 14 roots the whole time -- the claim and its own warrant had drifted apart, which
    is the failure mode this campaign exists to catch.  It is also the sharpest of the
    three: A3+A1 has rank 4 and 2A2+A1 has rank 5, so two Levis of DIFFERENT RANK share
    the centralizer dimension 20;
  * the set of attainable rung dimensions is exactly
    {6,8,10,12,14,16,18,20,26,28,30,36,46,78}.  Dimensions 22, 24, 32, 34, 38-44 and
    EVERY value in 47-77 are IMPOSSIBLE for any rung whatsoever -- a theorem about E6,
    unlike the non-attainment of 26 at real points, which is a census over directions.

Root system and Cartan matrix come from the exact integral Chevalley e6 of B351; no
floats anywhere.
"""
import importlib.util
import itertools
import pathlib
from collections import Counter

_PATH = (pathlib.Path(__file__).resolve().parents[1] / "frontier"
         / "B351_exact_e6_chevalley" / "exact_e6.py")
_spec = importlib.util.spec_from_file_location("b351_levi", _PATH)
b351 = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(b351)

ROOTS = [tuple(r) for r in b351.ROOTS]
A = b351.A
SIMPLES = [tuple(1 if i == j else 0 for i in range(6)) for j in range(6)]


def _subsystem(support):
    """Roots supported on the given subset of simple-root coordinates."""
    keep = set(support)
    return [r for r in ROOTS if all(r[i] == 0 for i in range(6) if i not in keep)]


def _components(support):
    adj = {i: {j for j in support if j != i and A[i][j] != 0} for i in support}
    comps, seen = [], set()
    for i in support:
        if i in seen:
            continue
        stack, comp = [i], set()
        while stack:
            x = stack.pop()
            if x in seen:
                continue
            seen.add(x)
            comp.add(x)
            stack.extend(adj[x] - seen)
        comps.append((comp, adj))
    return comps


def _type_name(support):
    """Cartan type of the sub-diagram on `support`, as a sorted multiset string."""
    if not support:
        return "empty"
    if len(support) == 6:
        return "E6"                      # the full diagram; branch test alone misnames it
    names = []
    for comp, adj in _components(support):
        n = len(comp)
        maxdeg = max(len(adj[i] & comp) for i in comp)
        if n >= 4 and maxdeg == 3:
            names.append(f"D{n}")
        elif n == 5 and maxdeg == 3:
            names.append("D5")
        else:
            names.append(f"A{n}")
    cnt = Counter(names)
    return "+".join(k if v == 1 else f"{v}{k}" for k, v in sorted(cnt.items()))


def _types_by_root_count():
    table = {}
    for bits in itertools.product((0, 1), repeat=6):
        support = tuple(i for i in range(6) if bits[i])
        n = len(_subsystem(support))
        table.setdefault(n, set()).add(_type_name(support))
    return table


TABLE = _types_by_root_count()

# The rungs the paper actually reports, as (dimension, root count).
PAPER_LADDER = [78, 46, 30, 18, 14, 12]


def test_root_system_is_the_expected_e6():
    assert len(ROOTS) == 72
    assert all(s in ROOTS for s in SIMPLES)


def test_unique_levi_type_at_the_four_forcing_dimensions():
    """46, 30, 26, 14 each admit exactly one Levi type -- so the type is forced."""
    expected = {40: "D5", 24: "D4", 20: "A4", 8: "A1+A2"}
    for nroots, name in expected.items():
        assert TABLE[nroots] == {name}, (nroots, TABLE[nroots])
        assert 6 + nroots in (46, 30, 26, 14)


def test_the_terminus_is_forced_by_classification_not_by_certificate():
    """dim 14 => 8 roots => A2+A1, with no alternative."""
    assert TABLE[8] == {"A1+A2"}
    assert 6 + 8 == 14


def test_dimensions_18_12_AND_20_are_genuinely_ambiguous():
    """The paper must not assign a type at any of these; this pins all three.

    The 20 case was MISSED by an earlier draft, which named only 12 and 18 -- although
    this file's own enumeration had printed the two types at 14 roots all along.  It is
    the sharpest of the three: A3+A1 has rank 4 and 2A2+A1 has rank 5, so two Levis of
    DIFFERENT RANK share the centralizer dimension 20.  "The dimension pins the type" is
    therefore false in general and true only where it is invoked.
    """
    assert TABLE[12] == {"2A2", "A3"}          # dim 18
    assert TABLE[6] == {"3A1", "A2"}           # dim 12
    assert TABLE[14] == {"A1+2A2", "A1+A3"}    # dim 20
    for nroots in (6, 12, 14):
        assert len(TABLE[nroots]) == 2


def test_the_uniqueness_claims_are_not_accidentally_broader():
    """Exactly three root counts are ambiguous; every other attained count is unique."""
    ambiguous = sorted(n for n, t in TABLE.items() if len(t) > 1)
    assert ambiguous == [6, 12, 14]
    assert sorted(6 + n for n in ambiguous) == [12, 18, 20]


def test_attainable_rung_dimensions_are_exactly_this_set():
    dims = sorted(6 + n for n in TABLE)
    assert dims == [6, 8, 10, 12, 14, 16, 18, 20, 26, 28, 30, 36, 46, 78]


def test_certain_dimensions_are_impossible_for_any_rung():
    """A theorem about E6 -- stronger than the census that 26 is unattained."""
    dims = {6 + n for n in TABLE}
    for d in (22, 24, 32, 34, 38, 39, 40, 41, 42, 43, 44):
        assert d not in dims, f"dimension {d} must be unattainable"


def test_the_reported_ladder_is_consistent_with_the_classification():
    dims = {6 + n for n in TABLE}
    for d in PAPER_LADDER:
        assert d in dims, f"reported rung {d} is not a Levi dimension"


def test_26_is_a_possible_levi_dimension_so_its_absence_is_a_census():
    """Guards the paper's honesty clause: 26 is unattained, not impossible."""
    dims = {6 + n for n in TABLE}
    assert 26 in dims
    assert TABLE[20] == {"A4"}
