"""B728 lock — the Stokes resummation does NOT close the Born phase: zeta5 is IMPORTED.

The coherent whole (the B722-rigid Stokes connection between sigma0,sigma1,sigma2) has intrinsic
arithmetic Q (+) Q(sqrt-3); Q(zeta5) is ruled out by the C4 != C2xC2 theorem (positive refutation)
+ the base-rate trap. Structural/arithmetic only (Gate 5). Two-seat: cc2 ran it, cc verified.
"""
import sympy as sp

x = sp.Symbol('x')


def test_gal_Q_zeta5_is_cyclic_C4_unique_quadratic_subfield():
    # Gal(Q(zeta5)/Q) = (Z/5)^* is CYCLIC of order 4 -> a UNIQUE quadratic subfield (Q(sqrt5)).
    zeta5 = sp.exp(2*sp.pi*sp.I/5)
    assert sp.degree(sp.minimal_polynomial(zeta5, x), x) == 4        # [Q(zeta5):Q]=4
    # (Z/5)^* generated by 2: 2,4,3,1 -> order 4, cyclic
    orbit, v = [], 1
    for _ in range(4):
        v = (v*2) % 5
        orbit.append(v)
    assert orbit == [2, 4, 3, 1]                                     # a single 4-cycle => C4 cyclic
    assert len(set(orbit)) == 4
    # the unique quadratic subfield of Q(zeta5) is Q(sqrt5) (cos(2pi/5) in Q(sqrt5))
    assert sp.nsimplify(sp.cos(2*sp.pi/5)) == sp.Rational(-1, 4) + sp.sqrt(5)/4


def test_gal_biquadratic_is_klein_four_three_quadratic_subfields():
    # Gal(Q(sqrt-3,sqrt5)/Q) = C2 x C2 -> THREE quadratic subfields: Q(sqrt-3), Q(sqrt5), Q(sqrt-15).
    # the compositum has degree 4; its three quadratic subfields come from the three order-2 subgroups.
    # being * hearing = meeting: sqrt-3 * sqrt5 = sqrt-15 (the genus/meeting field, B698/B699)
    assert sp.simplify(sp.sqrt(-3) * sp.sqrt(5) - sp.sqrt(-15)) == 0
    subfields = {sp.sqrt(-3), sp.sqrt(5), sp.sqrt(-15)}
    assert len(subfields) == 3                                       # Klein-four has 3 order-2 subgroups


def test_crux_zeta5_not_in_biquadratic_compositum():
    # CRUX (positive refutation): both fields are degree 4, but C4 (cyclic) != C2xC2 (Klein) =>
    # Q(zeta5) != Q(sqrt-3,sqrt5) and zeta5 is NOT in the compositum of the two bare faces.
    zeta5 = sp.exp(2*sp.pi*sp.I/5)
    # discriminating count: unique quadratic subfield (1) vs three (3) -> the fields are unequal.
    n_subfields_zeta5 = 1        # C4 has one subgroup of order 2
    n_subfields_biquad = 3       # C2xC2 has three
    assert n_subfields_zeta5 != n_subfields_biquad                  # different groups -> different fields
    # concretely: zeta5 (degree 4, cyclic) cannot lie in the Klein-four field of the same degree.
    # verify zeta5 is genuinely complex and degree 4 (not reducible into the biquadratic's generators)
    assert sp.im(zeta5) != 0
    assert sp.minimal_polynomial(zeta5, x) == x**4 + x**3 + x**2 + x + 1
    # the biquadratic's primitive element sqrt-3+sqrt5 has a DIFFERENT quartic minimal polynomial
    alpha = sp.sqrt(-3) + sp.sqrt(5)
    mp_alpha = sp.minimal_polynomial(alpha, x)
    assert sp.degree(mp_alpha, x) == 4
    assert mp_alpha != x**4 + x**3 + x**2 + x + 1                   # NOT the 5th cyclotomic => distinct fields


def test_born_content_ledger_only_two_pieces_forced_native():
    # The final ledger: FORM=Q(sqrt-3) and WEIGHTS=Q(sqrt5) are forced-native to the object;
    # AMPLITUDES=quartic Q(sqrt phi) OPEN; PHASE=Q(zeta5) IMPORTED (overlay). Lock the field degrees.
    phi = (1 + sp.sqrt(5))/2
    assert sp.degree(sp.minimal_polynomial(sp.sqrt(-3), x), x) == 2      # FORM: being, quadratic
    assert sp.degree(sp.minimal_polynomial(sp.sqrt(5), x), x) == 2       # WEIGHTS: hearing, quadratic
    D = sp.sqrt(2 + phi)
    assert sp.degree(sp.minimal_polynomial(1/D, x), x) == 4              # AMPLITUDES: real quartic Q(sqrt phi)
    assert sp.degree(sp.minimal_polynomial(sp.exp(2*sp.pi*sp.I/5), x), x) == 4  # PHASE: Q(zeta5), cyclic quartic
    # forced-native (the object's trace/monodromy fields) = the two QUADRATICS; the quartics are open/imported
