"""B1521 lock -- GENESIS v1.3 (2026-10-02): the audit lane's corrections carried (AR3-AR6, re-derived), the deciding test's
outcome on both benches with B1297's P identified as the swap's class (it fixes rho_q; the inversion dualises it), and the
owner's priorities of 2026-10-02.

Locks:
- C1 live: the explicit isomorphism between SnapPy's presentation of pi_1(m004) and Ballas', proved by free-group reduction;
  P transported; P = conj(nM) o s in the faithful holonomy; rho_q o P isomorphic to rho_q and not to rho_q^* (exact).
- C2-C4 live: B20/B37's literal detectors under a vacuous rewriting, with the opposite control; the countermodel and B130's
  m = 2 elimination; the field label; B723's banner.
- GENESIS v1.3 regenerated byte-for-byte from the kept v1.2 by the generator; marks, strings, no status change, firewall words.
- The arc's text and ledgers: FINDINGS ("Seen first"), verdict, B1520's addendum, ERROR_LEDGER, OPEN_PROBLEMS gate A, kill
  graph scope notes, OPEN_LEADS sL-10, relays.
"""
import base64
import importlib.util
import json
import re
import subprocess
import sys
from fractions import Fraction as F
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
ARC = ROOT / "frontier" / "B1521_genesis_v13"
VER = ARC / "verification"
PRIVATE = bytes([98, 114, 97, 118, 101]).decode()
VENDOR = re.compile(r"\b(" + "|".join(base64.b64decode(b).decode() for b in
                                     (b"Y2xhdWRl", b"YW50aHJvcGlj", b"b3B1cw==", b"c29ubmV0", b"ZmFibGU=")) + r")\b", re.I)


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _norm(text):
    return " ".join(re.sub(r"[*`>]", "", text).split())


# ------------------------------------------------------------------------------------------------- C1
def test_c1_record():
    d = json.loads((VER / "which_class_is_P.json").read_text(encoding="utf-8"))
    assert d["snappy"]["relators"] == ["aaabABBAb"] and d["snappy"]["meridian"] == "ab"
    iso = d["iso"]
    assert (iso["m"], iso["n"], iso["a_in_mn"], iso["b_in_mn"]) == ("ab", "aabA", "MnmN", "nMNmm")
    fp = iso["free_group_proof"]
    assert fp["psi(phi(m)) m^-1"] == "" and fp["= u v with u, v cyclic conjugates of R'^+-1"] == ["mNMnmNmnMN", "MnmNMnMNmn"]
    assert d["P_transported"] == {"P(m)": "MnmNm", "P(n)": "nmN", "H1_images": [1, 1]}
    assert d["P_class"] == {"P' = inner o swap, conjugator": "nM", "P' = inner (identity class), conjugator": None}
    rows = {r["q"]: r for r in d["ballas"]}
    for q in ("2", "3", "1/5", "7/3"):
        r = rows[q]
        assert r["Hom(rho_q, rho_q o P)"] == {"dim": 1, "invertible_member": True}
        assert r["Hom(rho_q^*, rho_q o P)"] == {"dim": 0, "invertible_member": False}
        assert r["Hom(rho_q o inversion, rho_q o P)"]["dim"] == 0
    assert all(v == {"dim": 1, "invertible_member": True} for k, v in rows["1"].items() if k != "q")


def test_c1_free_group_proof_live():
    """the isomorphism by words alone: psi(phi(m)) = m freely, psi(phi(n)) = n R'-conjugate, psi(R) = u v"""
    def inv(w):
        return "".join(c.swapcase() for c in reversed(w))

    def red(w):
        out = []
        for c in w:
            if out and out[-1] == c.swapcase():
                out.pop()
            else:
                out.append(c)
        return "".join(out)

    def sub(w, im):
        return red("".join(im[c] if c.islower() else inv(im[c.lower()]) for c in w))

    def cyc(w):
        w = red(w)
        while len(w) >= 2 and w[0] == w[-1].swapcase():
            w = w[1:-1]
        return w

    def rots(w):
        return {w[i:] + w[:i] for i in range(len(w))}
    Rp, R = "mnMNmNMnmN", "aaabABBAb"
    conj = rots(Rp) | rots(inv(Rp))
    phi, psi = {"m": "ab", "n": "aabA"}, {"a": "MnmN", "b": "nMNmm"}
    assert red(sub(sub("m", phi), psi) + "M") == ""
    assert cyc(red(sub(sub("n", phi), psi) + "N")) in conj
    cw = cyc(sub(R, psi))
    assert any((cw[i:] + cw[:i])[:k] in conj and (cw[i:] + cw[:i])[k:] in conj for i in range(len(cw)) for k in range(1, len(cw)))
    # P transported is a word map that sends Ballas' relator to itself up to the group (checked on Ballas exactly below)
    Pab = {"a": "A", "b": "aaab"}
    Pm = sub(sub("ab", Pab), psi)
    Pn = sub(sub("aabA", Pab), psi)
    assert (Pm, Pn) == ("MnmNm", "nmN")


def _ballas(q):
    t = q / 2
    m = [[F(1), F(0), F(1), t - 1], [F(0), F(1), F(1), t], [F(0), F(0), F(1), t + F(1, 2)], [F(0), F(0), F(0), F(1)]]
    n = [[F(1), F(0), F(0), F(0)], [2 + 1 / t, F(1), F(0), F(0)], [F(2), F(1), F(1), F(0)], [F(1), F(1), F(0), F(1)]]
    return m, n


def test_c1_ballas_live():
    """exact at q = 2 and 1/5: Hom(rho_q, rho_q o P) is a line with an invertible member; Hom(rho_q^*, rho_q o P) = 0"""
    src = (VER / "which_class_is_P.py").read_text(encoding="utf-8")
    ns = {"F": F, "__name__": "lin"}  # the script's exact linear algebra only (its top imports SnapPy)
    exec(compile(src.split("# ---------- exact 4x4 linear algebra over Q ----------")[1], "lin", "exec"), ns)
    for q in (F(2), F(1, 5)):
        m, n = _ballas(q)
        R = {"m": m, "n": n, "M": ns["inv"](m), "N": ns["inv"](n)}

        def ev(w):
            X = ns["eye"]()
            for c in w:
                X = ns["mul"](X, R[c])
            return X
        assert ev("mnMNmNMnmN") == ns["eye"]()
        img = {"m": ev("MnmNm"), "n": ev("nmN")}
        same = ns["intertwiners"]({"m": m, "n": n}, img)
        dual = ns["intertwiners"]({"m": ns["tr"](ns["inv"](m)), "n": ns["tr"](ns["inv"](n))}, img)
        assert len(same) == 1 and ns["det"](same[0]) != 0 and dual == []


@pytest.mark.slow
def test_c1_snappy_reproduces():
    out = subprocess.run([sys.executable, str(VER / "which_class_is_P.py")], cwd=VER, capture_output=True, text=True, timeout=600)
    assert out.returncode == 0, out.stderr[-2000:]
    assert "P (main's B1297 period-2 symmetry) is the swap's class" in out.stdout


# ------------------------------------------------------------------------------------------------- C2-C4
def test_c2_c4_live():
    A = _load("b1521_audit_corrections", VER / "audit_corrections.py")
    ar3 = A.ar3()
    assert ar3["B37 predicate fires on T"] is False and ar3["B37 predicate fires on the rewritten T'"] is True
    assert ar3["B20 predicate fires on T"] is False and ar3["B20 predicate fires on T'"] is True
    assert ar3["opposite control: a genuine read (z' += r) changes the orbit off the graph"] is True
    assert ar3["kappa - 2 - 4 I (Fricke X = 2x)"] == "0"
    ar4 = A.ar4()
    assert ar4["countermodel elimination ideal in k"] == [] and ar4["Jacobian rank at the isolated point (1, 0)"] == 2
    assert ar4["point-only control elimination ideal in k"] == ["k"]
    assert ar4["B130 m = 2 elimination ideal in kappa (reproduced)"] == []
    ar5 = A.ar5()
    assert ar5["fields shared by several m"][5] == [1, 4, 11]
    ar6 = A.ar6()
    assert ar6["B723 banner carries"] == {"B942": True, "B957": True}
    rec = json.loads((VER / "audit_corrections.json").read_text(encoding="utf-8"))
    assert rec["AR4"]["B130 m = 2 elimination ideal in kappa (reproduced)"] == [] and rec["AR5"]["fields shared by several m"]["5"] == [1, 4, 11]


# ------------------------------------------------------------------------------------------------- GENESIS v1.3
def test_genesis_v13_is_the_generator_output(tmp_path):
    out = tmp_path / "G.md"
    r = subprocess.run([sys.executable, str(VER / "merge_genesis_v13.py"), str(ARC / "received" / "GENESIS_v1_2.md"), str(out)],
                       capture_output=True, text=True, timeout=120)
    assert r.returncode == 0, r.stderr
    assert out.read_bytes() == (ROOT / "GENESIS.md").read_bytes()


def test_genesis_v13_text():
    raw = (ROOT / "GENESIS.md").read_text(encoding="utf-8")
    v12 = (ARC / "received" / "GENESIS_v1_2.md").read_text(encoding="utf-8")
    g = " ".join(raw.split())
    assert raw.startswith("# GENESIS — the foundations of origin-axiom")
    assert "**Version 1.3 · 2026-10-02 · canonical.**" in raw
    # the earlier marks are all kept; v1.3's are additive
    for mark in ("[v1.1]", "**[v1.1]**", "**[v1.2]**", "[v1.2]"):
        assert raw.count(mark) == v12.count(mark), mark
    assert (raw.count("[v1.1]"), raw.count("**[v1.1]**"), raw.count("**[v1.2]**")) == (21, 15, 22)
    assert raw.count("**[v1.3]**") == 12
    for s in ("v1.3 (sm:B1521) carries the audit lane's corrections of three old results",
              "B723 is cited with the two retractions on its own banner. B942: complex conjugation is not in Gal(K^ab/K)",
              "B957: the values clause too",
              "Run on both benches the same day by routes that share no code (main's B1455; sm:B1520)",
              "The three lemmas are B1297's (main's B1455 addendum).",
              "The dualising symmetry is the inversion, not B1297's period-2 symmetry P: P is the swap's class and fixes ρ_q (sm:B1521 C1).",
              "and the levels stay open (main's L242 (b))",
              "\"choice might be golden\", is registered here and tested only in forms sealed before computing",
              "That holds in B37's literal sense only",
              "B130 shows that κ takes a continuum of values on the fixed locus, but its reading that a unit is internally fork-free",
              "On m004's family it does for half of the symmetries, one kind of mirror among them, and never for a count-odd one",
              "the primitive may be an act of distinction together with the relation that registers it",
              "at the group layer the record has one, a chirality-registering measurement as B599's pairing datum",
              "the experiential question, an explicit hypothesis held under Gate 5-Q",
              "A vacuum, being a direct sum, forgets the order",
              "the fixed loci of the metallic trace maps component by component",
              "m = 1, 4 and 11 share ℚ(√5)",
              "- **v1.3 · 2026-10-02 · sm:B1521.**",
              # v1.2 and v1.1 lines kept
              "- **v1.2 · 2026-10-02 · sm:B1519.** Main's v1.1 taken as the head, as main asked; every one of its 23 changes accepted.",
              "| F-MC **[v1.1]** | McKay cascade frame |"):
        assert " ".join(s.split()) in g, s
    # no status changed
    for row in ("| FK9 | Selection: what makes a state physical | OPEN |", "| FK10 | The end law | OPEN |",
                "| FK12 **[v1.2]** | The observer: are its closings part of the genesis, or inputs beyond it?",
                "| GM5c | The record swap P is a legal move | OPEN |", "| FK11 | The dictionary (I-26) | UNEARNED |"):
        assert row in raw, row
    fk12 = next(l for l in raw.splitlines() if l.startswith("| FK12 "))
    assert "| OPEN |" in fk12
    # firewall: the experiential vocabulary stays in the governed rooms (Gate 5-Q, Q5); no private or vendor word
    low = raw.lower()
    for w in ("qualia", "conscious", PRIVATE):
        assert w not in low, w
    assert not VENDOR.search(raw)


# ------------------------------------------------------------------------------------------------- the arc's text and ledgers
def test_findings_and_verdict():
    f = (ARC / "FINDINGS.md").read_text(encoding="utf-8")
    assert f.startswith("# B1521 — GENESIS v1.3")
    sec = re.search(r"(?ms)^##[^\n]*Seen first[^\n]*\n(.*?)(?=^## |\Z)", f)
    assert sec and "sweep" in sec.group(1).lower() and "literature" in sec.group(1).lower()
    t = _norm(f)
    for s in ("Verdict: PROVED", "Not sealed.", "creates_law is false", "0 of 19", "I-26 stays UNEARNED",
              "58 of 1327 arcs on main match (NEGATIVE 17, OPEN 2, PROVED 39)", "B1279 (2026-09-06)",
              "So ρ_q ∘ P ≅ ρ_q, and not", "for q ≠ 1. The addendum's sentence holds for the inversion θ", "Main's L242 (b) is therefore open.",
              "The test changes under a vacuous rewriting", "Its reading that a unit is internally fork-free needs a componentwise proof",
              "Standing: RE-DERIVED", "No status changes."):
        assert s in t, s
    v = json.loads((ARC / "arc_verdict.json").read_text(encoding="utf-8"))
    assert v["id"] == "B1521" and v["verdict"] == "PROVED" and v["creates_law"] is False and v["identifications"] == []
    assert v["prior_work"]["standing"] == "RE-DERIVED" and "b1521-tmp" not in v["prior_work"]["repo"]["heads"]
    assert v["prior_work"]["repo"]["heads"]["origin/main"] == "8d1c1329"
    for p in [ARC / "FINDINGS.md", ARC / "arc_verdict.json"] + list(VER.glob("*.py")) + list(VER.glob("*.json")):
        text = p.read_text(encoding="utf-8")
        assert PRIVATE not in text.lower(), p.name
        assert not VENDOR.search(text), p.name


def test_ledgers_and_surfaces():
    add = (ROOT / "frontier" / "B1520_the_deciding_test" / "ADDENDUM_2026-10-02_the_lemmas_are_B1297s_and_P_is_s.md").read_text(
        encoding="utf-8")
    assert "P = conj(nM) ∘ s" in add and "the earlier source of all three is B1297" in add
    err = (ROOT / "docs" / "ERROR_LEDGER.md").read_text(encoding="utf-8")
    assert "| E54 instance (2026-10-02, B1520's Seen first) — the three lemmas credited to two arcs of the same day, not to B1297 |" in err
    op = (ROOT / "docs" / "OPEN_PROBLEMS.md").read_text(encoding="utf-8")
    assert "Scope of B130's part (2026-10-02, sm:B1521; the audit lane's ACT_REGISTER AR4 and AR5" in op
    leads = _norm((ROOT / "docs" / "OPEN_LEADS.md").read_text(encoding="utf-8"))
    assert "Done 2026-10-02 as sm:B1521 (PROVED): GENESIS v1.3." in leads
    assert "5. The metallic fixed loci, component by component (sm:B1521; the audit lane's AR4)." in leads
    g = json.loads((ROOT / "frontier" / "B738_pathfinder_compiler" / "kill_graph.json").read_text(encoding="utf-8"))
    d = {r.get("id"): r for r in g if isinstance(r, dict)}
    for k in ("B20", "B37", "B130"):
        assert "SCOPE (2026-10-02, sm:B1521" in d[k]["note"], k
        assert d[k]["kill_form"] == "unrouted-unclassified" and d[k]["fact_computed"] is None and d[k]["priority"] == "UNTRIAGED"
    for name in ("SM_TO_CC_2026-10-02_P_IS_THE_SWAP_AND_GENESIS_V1_3.md", "SM_TO_CODEX_2026-10-02_ACT_REGISTER_ANSWERED_GENESIS_V1_3.md"):
        text = (ROOT / name).read_text(encoding="utf-8")
        assert "B1521" in text and PRIVATE not in text.lower() and not VENDOR.search(text), name
