"""P5 Draft v1 — locks the disciplines the lit-gate made binding.

These are not style checks. Each one guards a claim that would be false or pre-empted without it.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
D = ROOT / "papers" / "P5_monoid" / "DRAFT_v1.md"


def _t():
    """Normalised text: strip blockquote markers and emphasis before joining.

    A first version joined raw whitespace and missed two phrases because markdown `>` continuation
    markers interleaved mid-sentence ("would be > false"). Same class as the bolded-value miscount
    in B845 -- a lock defeated by formatting rather than by content.
    """
    raw = D.read_text(encoding="utf-8")
    lines = [re.sub(r"^\s*>\s?", "", ln) for ln in raw.splitlines()]
    return " ".join(" ".join(lines).replace("**", "").split())


def test_the_Q2_row_is_TWO_cells_not_one():
    """The failure mode: 'atoroidal, hence hyperbolic by Mutanguha' collapses evidence into proof."""
    t = _t()
    assert "EVIDENCE" in t and "HYPOTHESIS VERIFIED" in t
    assert "NO." in t, "the hypothesis cell must say NO"
    assert "117 cyclic classes" in t, "the bound must be stated, not the conclusion"
    assert "would be false" in t, "the collapsed form must be named as false"


def test_the_toral_floor_is_cited_not_claimed():
    """Gate E: SL2(N) freely generated by L,R is classical and would pre-empt a careless draft."""
    t = _t()
    assert "generated FREELY by L and R" in t
    assert "Reutenauer" in t and "Northshield" in t
    assert "CITED, not claimed" in t


def test_the_novelty_is_scoped_to_the_non_invertible_sector():
    """Gate C: Cantat-Dujardin own the automorphism action on this exact object."""
    t = _t()
    assert "Cantat" in t
    assert "non-invertible sector" in t
    assert "Stratum 1 is their territory" in t


def test_the_drift_ledger_claims_the_LEDGER_not_the_method():
    """Gate D: the Fourier/Mahler computation is textbook."""
    t = _t()
    assert "METHOD is classical" in t
    assert "not the technique that evaluates them" in t


def test_every_section_carries_a_reproducer_and_a_level():
    t = D.read_text(encoding="utf-8")
    assert t.count("**Reproducer:**") >= 4, "each computational section needs its reproducer"
    for lvl in ("`End(F₂)`", "`trace-map`", "`toral`"):
        assert lvl in t, f"the {lvl} level must be used explicitly"


def test_the_physics_names_stay_firewalled():
    t = _t()
    assert "speculations/S063" in t
    for verb in ("decoherence", "renormalization"):
        # they may appear ONLY in the firewall sentence, never as a claim
        assert t.count(verb) <= 1, f"'{verb}' appears more than once -- it must stay firewalled"
