"""B1341 - the object's least-action principle exists only at the double tick.

These recompute the load-bearing facts rather than asserting them from the arc's text, so the test
fails if the mathematics is ever wrong: the half step reverses orientation (hence has no discrete
Lagrangian), the double step preserves it, and the genesis morphism carries the SAME bit with the
same characteristic polynomial. The scope fence is locked too -- the object's leaf is I = -1, the
Markov surface, NOT the I = 0 leaf on which the explicit action was computed.
"""
import json
import pathlib

import sympy as sp

ROOT = pathlib.Path(__file__).resolve().parents[1]
ARC = ROOT / "frontier" / "B1341_the_action_of_the_object"

x, y, z = sp.symbols("x y z")
T = sp.Matrix([z, x, 2 * x * z - y])                     # B37's trace map, verbatim
I = x ** 2 + y ** 2 + z ** 2 - 2 * x * y * z - 1         # Fricke-Vogt
SUB = {x: T[0], y: T[1], z: T[2]}


def test_arc_is_banked():
    assert (ARC / "FINDINGS.md").exists()
    v = json.loads((ARC / "arc_verdict.json").read_text(encoding="utf-8"))
    assert v["id"] == "B1341" and v["verdict"] == "PROVED"


def test_fricke_vogt_is_invariant():
    assert sp.simplify(I.subs(SUB, simultaneous=True) - I) == 0


def test_the_half_step_reverses_orientation_and_the_square_restores_it():
    """B21, recomputed. det -1 is the whole obstruction: an orientation-reversing map of a surface
    preserves no area form, so it is generated by no discrete Lagrangian."""
    J = T.jacobian([x, y, z])
    assert sp.simplify(J.det()) == -1
    T2 = T.subs(SUB, simultaneous=True)
    assert sp.simplify(T2.jacobian([x, y, z]).det()) == 1


def test_the_obstruction_reaches_every_leaf_including_the_object_s():
    """T pulls the Gelfand-Leray area form dx ^ dy / I_z back to MINUS itself on every leaf."""
    Iz, Iy = sp.diff(I, z), sp.diff(I, y)
    ratio = sp.simplify((Iy / Iz) / Iz.subs(SUB, simultaneous=True) * Iz)
    assert sp.simplify(ratio + 1) == 0, "the theorem must not depend on which leaf"


def test_no_quadratic_discrete_lagrangian_for_the_half_step():
    """the DEL relation always has a and c sharing a coefficient; the recursion needs them opposite.

    sympy's subs is NOT simultaneous: {a: b, b: c} applied sequentially collapses L to a function
    of c alone and silently zeroes the second term, which returns the right answer for the wrong
    reason. Placeholders keep the two slots distinct."""
    a, b, c, p, q, r, k = sp.symbols("a b c p q r k")
    u_, v_ = sp.symbols("u_ v_")
    L = p * u_ ** 2 + q * u_ * v_ + r * v_ ** 2
    d1L = lambda U, V: sp.diff(L, u_).subs({u_: U, v_: V}, simultaneous=True)
    d2L = lambda U, V: sp.diff(L, v_).subs({u_: U, v_: V}, simultaneous=True)
    DEL = sp.expand(d2L(a, b) + d1L(b, c))
    assert DEL.coeff(a) == DEL.coeff(c) == q, f"a and c must share a coefficient; got {DEL}"
    assert DEL.coeff(b) == 2 * (p + r) and DEL != 0, "the second DEL term must not vanish"
    sol = sp.solve([sp.Poly(DEL - k * (c - b - a), a, b, c).coeff_monomial(m) for m in (a, b, c)],
                   [p, q, r, k], dict=True)
    assert not [s for s in sol if s.get(k, k) != 0], "no quadratic L may reproduce the half step"


def test_the_genesis_carries_the_same_bit():
    """L.P (the genesis morphism) and the linearised half step: same det AND same trace."""
    Lm, P = sp.Matrix([[1, 1], [0, 1]]), sp.Matrix([[0, 1], [1, 0]])
    LP, half = Lm * P, sp.Matrix([[0, 1], [1, 1]])
    assert Lm.det() == 1 and P.det() == -1
    assert LP.det() == -1 == half.det()
    assert LP.trace() == half.trace() == 1
    assert (LP ** 2).det() == 1 and (half ** 2).det() == 1
    lam = sp.symbols("lam")
    assert sp.expand(LP.charpoly(lam).as_expr()) == sp.expand(half.charpoly(lam).as_expr()) \
        == lam ** 2 - lam - 1, "the golden characteristic polynomial, on both"


def test_the_object_s_leaf_is_markov_not_the_one_the_action_was_built_on():
    """SCOPE FENCE. B1248: the once-punctured-torus fibre of m004 has kappa = -2, and
    I = (kappa - 2)/4, so the object sits at I = -1 -- the Markov surface."""
    X, Y, Z = sp.symbols("X Y Z")
    kappa = X ** 2 + Y ** 2 + Z ** 2 - X * Y * Z - 2
    assert sp.simplify(sp.expand((kappa.subs({X: 2 * x, Y: 2 * y, Z: 2 * z}) - 2) / 4) - I) == 0
    I_obj = sp.Rational(-2 - 2, 4)
    assert I_obj == -1, "the object is NOT on the I = 0 leaf the explicit action was built on"
    al, be, ga = sp.symbols("alpha beta gamma")
    leaf = sp.expand(I - I_obj).subs({x: sp.Rational(3, 2) * al, y: sp.Rational(3, 2) * be,
                                      z: sp.Rational(3, 2) * ga})
    markov = al ** 2 + be ** 2 + ga ** 2 - 3 * al * be * ga
    assert sp.simplify(sp.expand(leaf) - sp.Rational(9, 4) * markov) == 0, "the leaf is Markov's"


def test_row_4_is_not_claimed_to_be_solved():
    """the arc must keep its own fence: a discrete action is not a 4d field action."""
    t = (ARC / "FINDINGS.md").read_text(encoding="utf-8")
    assert "not a 4d Lorentzian field action" in t or "is not a field theory" in t
    assert "row 4's requirement is untouched" in t.lower() or "row 4's requirement is untouched" in t
