"""B1526 lock -- GENESIS v1.6 (2026-10-03; not sealed: every item checks a claim the record already fixes).
Main's v1.5 (B1460, the owner's two decisions) is the head; the SM seat's parallel v1.5 (sm:B1525) is answered by its line;
B1297's P is shown to be the fibre's elliptic involution (C3). Locked here:
- the received texts by sha-256 and git blob, and against main's blobs at 5c0951b7 where that commit is in the clone;
- GENESIS.md regenerated byte for byte from main's v1.5 by the arc's generator;
- the record (genesis_v16_checks.json): C1-C5 pass, with their numbers, before and after GENESIS.md was written;
- live: C3 (SnapPy's presentation, holonomy and symmetry group of m004), C4 and C5, and C4's diff with planted controls;
- GENESIS v1.6's text: version, marks, the owner's two decisions verbatim, the carried and fitted sentences, the statuses;
- Gate 5-Q's three words (encoded here), vendor words and the private term: absent from GENESIS.md and the arc's text, with a
  control in each direction;
- the arc's text and ledgers: FINDINGS, verdict, RELAY_LEDGER, the relay, OPEN_LEADS, README, B1525's repointed lock.
Since v1.8 (sm:B1528, 2026-10-03) GENESIS.md is main's v1.7 plus marked [v1.8] changes. v1.6's text is kept byte-identical in
B1528's arc (`received/GENESIS_v1_6_sm.md`, the text main received), and the tests below that read v1.6 read it there; B1528's
lock checks GENESIS.md."""
import base64
import hashlib
import importlib.util
import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
ARC = ROOT / "frontier" / "B1526_genesis_v16"
VER = ARC / "verification"
REC = ARC / "received"
V15M, V15S = REC / "GENESIS_v1_5_main.md", REC / "GENESIS_v1_5_sm.md"
RELAY_IN = REC / "CC_TO_SM_AND_CODEX_2026-10-03_GENESIS_V1_5_FK1_CONFIRMED_FK12_THE_REGISTER.md"
RELAY_OUT = ROOT / "SM_TO_CC_AND_CODEX_2026-10-03_GENESIS_V1_6.md"
V16_KEPT = ROOT / "frontier" / "B1528_genesis_v18" / "received" / "GENESIS_v1_6_sm.md"
MARK = "**[v1.6]**"
Q5 = [base64.b64decode(t).decode() for t in ("cXVhbGlh", "YXdhcmU=", "c2Vlcw==")]
VENDOR = [base64.b64decode(t).decode() for t in ("Y2xhdWRl", "YW50aHJvcGlj", "b3B1cw==", "c29ubmV0", "ZmFibGU=")]
PRIVATE = bytes([98, 114, 97, 118, 101]).decode()


def _chk():
    """the arc's checks, loaded from their own file (a module of the same name elsewhere must not shadow them)"""
    spec = importlib.util.spec_from_file_location("b1526_genesis_v16_checks", VER / "genesis_v16_checks.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _sha(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()


def _q5(text):
    return [i + 1 for i, w in enumerate(Q5) if re.search(r"\b" + w + r"\b", text, re.I)]


def _norm(text):
    return " ".join(text.split())


# ------------------------------------------------------------------------------------------------- the received texts
def test_the_received_texts():
    assert _sha(V15M) == "67d554e9868b0164685ce8b71b6d3d1dea19b892b937b709a8a45a232879fa12"
    assert _sha(V15S) == "3e3b3d7bcfdf2eac3155419a45fd8a32f07c1e79588f74fa4e2a16082ca1b6f3"
    assert _sha(RELAY_IN) == "154155eaa71a2e30c1741d54427256c168f2b7d0fa3e097c27382c12ca649781"
    blob = lambda p: subprocess.run(["git", "hash-object", str(p)], capture_output=True, text=True, check=True).stdout.strip()
    assert blob(V15M) == "e39ed197b9f9c3c78dcf1a916fd8f1a7908133b0"
    assert blob(V15S) == "9d6f28a44276bdb22b78d9456e9bfb936b7e0e2a"
    assert blob(RELAY_IN) == "a6b21d02949dff8f77aa280ac72a1ae6ac557ada"


def test_genesis_is_the_generator_output(tmp_path):
    out = tmp_path / "G.md"
    r = subprocess.run([sys.executable, str(VER / "merge_genesis_v16.py"), str(V15M), str(out)],
                       capture_output=True, text=True, timeout=120)
    assert r.returncode == 0, r.stderr
    assert out.read_bytes() == V16_KEPT.read_bytes()
    assert _sha(V16_KEPT) == "59ef40a678a2aa7b11d37599300b6d3cacc481edb0568f30eda852ba176faf36"
    assert "[v1.6] marks: 15" in r.stdout


# ------------------------------------------------------------------------------------------------- the record
def test_the_record():
    d = json.loads((VER / "genesis_v16_checks.json").read_text(encoding="utf-8"))
    assert d["checks"] == {f"C{i}": True for i in range(1, 6)} and d["GENESIS.md is the generated v1.6"] is True
    pre = (VER / "genesis_v16_checks_prewrite_run.txt").read_text(encoding="utf-8")
    post = (VER / "genesis_v16_checks_run.txt").read_text(encoding="utf-8")
    assert "ALL CHECKS PASS" in pre and "GENESIS.md is the generated v1.6: False" in pre
    assert "ALL CHECKS PASS" in post and "GENESIS.md is the generated v1.6: True" in post
    c1 = d["C1 the received texts"]
    assert c1["main's v1.5 against v1.4: changed blocks"] == {"version line": 1, "marked": 5, "log entry": 1}
    assert c1["main's amend.py rebuilds main's v1.5 from v1.4"] in (True, "not checkable: not in this clone")
    c3 = d["C3 P is the fibre's elliptic involution"]
    assert c3["Delta from R (coefficients, lowest degree first)"] == [-1, 3, -1]
    assert c3["symmetry group: order, full, amphicheiral"] == [8, True, True]
    assert c3["isometries acting on the cusp as the identity (orientation and base kept)"] == 2
    c4 = d["C4 v1.6 against main's v1.5"]
    assert c4["main's words deleted or re-punctuated"] == _chk().EXPECTED_DELETIONS
    assert c4["[v1.6] marks"] == 15 and c4["changed blocks without a mark"] == []
    c5 = d["C5 the SM seat's v1.5, answered by its line"]
    assert c5["the seat's v1.5 marks accounted for"] == 16 and c5["carried as it was"] == 7
    assert c5["fitted or not carried"] == ["FK12", "FK9", "GAP3", "header", "log"]


# ------------------------------------------------------------------------------------------------- live
def test_c3_live():
    pytest.importorskip("snappy")
    r = _chk().c3()
    assert r["passed"], {k: v for k, v in r.items() if v is False}


def test_c4_catches_what_it_is_for():
    """planted controls for C4's diff: an unmarked insertion, a changed word of main's and a removed line are each caught"""
    chk = _chk()
    v15, v16 = V15M.read_text(encoding="utf-8"), V16_KEPT.read_text(encoding="utf-8")
    deleted, unmarked = chk.diff_report(v15, v16)
    assert deleted == chk.EXPECTED_DELETIONS and unmarked == []
    head = "## 2. The grammar: what a description is made of"
    assert v16.count(head) == 1
    assert chk.diff_report(v15, v16.replace(head, "A planted unmarked sentence.\n\n" + head))[1] != []
    word = "Every legal state belongs to the state space"
    assert v16.count(word) == 1
    assert chk.diff_report(v15, v16.replace(word, "Every legal state lies in the state space"))[0] != chk.EXPECTED_DELETIONS
    lines = v16.split("\n")
    i = next(k for k in range(100, len(lines)) if lines[k].strip())     # a line with words in it
    del lines[i]
    d, u = chk.diff_report(v15, "\n".join(lines))
    assert d != chk.EXPECTED_DELETIONS and u != []


def test_c4_c5_live():
    chk = _chk()
    v16 = chk.generate()
    c4 = chk.c4(v16)
    assert c4["passed"] and v16 == V16_KEPT.read_text(encoding="utf-8")
    assert chk.c5(v16)["passed"]


# ------------------------------------------------------------------------------------------------- GENESIS v1.6
def test_genesis_v16_text():
    raw = V16_KEPT.read_text(encoding="utf-8")
    g = _norm(raw)
    v15 = V15M.read_text(encoding="utf-8")
    assert raw.startswith("# GENESIS — the foundations of origin-axiom")
    assert "**Version 1.6 · 2026-10-03 · canonical.**" in raw and raw.count(MARK) == 15
    for m in ("[v1.1]", "[v1.2]", "[v1.3]", "[v1.4]", "[v1.5]"):
        assert raw.count(m) == v15.count(m) and raw.count("**" + m + "**") == v15.count("**" + m + "**"), m
    # the owner's two decisions, verbatim from main's v1.5
    for s in _chk().OWNER:
        assert s in v15 and s in raw, s[:60]
    for s in ("v1.6 (sm:B1526) takes main's head, v1.5, as main asked.",
              "B1297's period-2 symmetry P is the fibre's elliptic involution, whose extension to every level is main's B1459",
              "it is the one non-trivial outer class that keeps the orientation and the base, and it inverts the fibre's homology",
              "For the register question, the record's registering datum at the group layer is B599's pairing datum",
              "Kept apart from the register question",
              "the experiential question, an explicit hypothesis held under Gate 5-Q",
              "never a consequence of the register question and never a claim",
              "breaks from M₅ on, off the unit circle exactly where no golden Galois reflection fixes the twist",
              "on 262 of the 536 manifolds no isometry dualises it (sm:B1523)",
              "graded DERIVED (**[v1.6]** PASSED since sm:B1524: a rarity screen, not a derivation)",
              "the class index on the projective family of a mirror-broken word state, first ±LLRLRR and ±L³RLR²",
              "- **v1.6 · 2026-10-03 · sm:B1526.**",
              "Already in main's v1.5, in main's words: GAP3's refinement on the audit lane's qualification.",
              "- **v1.5 · 2026-10-03 · main B1460.**"):
        assert _norm(s) in g, s
    # GAP3 carries main's refinement once, not the SM seat's second copy
    assert "The audit lane's results do not prove that a one-ended state can get the third only from" not in raw
    assert "not prove that a one-ended state can get the third *only* from a relation" in raw
    # no status changed: the fork table's first three cells are main's v1.5's
    fk = lambda text: [l.split("|")[1:4] for l in text.splitlines() if re.match(r"\| FK\d+", l)]
    assert fk(raw) == fk(v15) and len(fk(raw)) == 12
    for row in ("| FK9 | Selection: what makes a state physical | OPEN |", "| FK11 | The dictionary (I-26) | UNEARNED |"):
        assert row in raw


def test_firewall_with_controls_both_ways():
    raw = (ROOT / "GENESIS.md").read_text(encoding="utf-8")
    assert _q5(raw) == [] and _q5(V15M.read_text(encoding="utf-8")) == [] and _q5(V15S.read_text(encoding="utf-8")) == []
    assert _q5("the count " + Q5[2] + " only") == [3] and _q5("seesaw") == []          # the check can fire, and only on words
    assert not any(re.search(re.escape(w), raw, re.I) for w in VENDOR) and PRIVATE not in raw.lower()


def test_hygiene():
    files = [ARC / "FINDINGS.md", ARC / "arc_verdict.json", RELAY_OUT] + sorted(VER.glob("*.py")) + \
        sorted(VER.glob("*.json")) + sorted(VER.glob("*.txt"))
    for f in files:
        t = f.read_text(encoding="utf-8")
        assert _q5(t) == [], f.name
        assert not any(re.search(re.escape(w), t, re.I) for w in VENDOR), f.name
        assert PRIVATE not in t.lower(), f.name


# ------------------------------------------------------------------------------------------------- the arc's text and ledgers
def test_findings_and_verdict():
    f = (ARC / "FINDINGS.md").read_text(encoding="utf-8")
    assert f.startswith("# B1526 — GENESIS v1.6: MAIN'S v1.5 (THE OWNER'S TWO DECISIONS) AS THE HEAD")
    sec = re.search(r"(?ms)^##[^\n]*Seen first[^\n]*\n(.*?)(?=^## |\Z)", f)
    assert sec and "sweep" in sec.group(1).lower() and "literature" in sec.group(1).lower()
    t = _norm(f)
    for s in ("**Verdict: PROVED.**", "**Not sealed.**", "**creates_law is false.**", "0 of 19", "I-26 stays UNEARNED",
              "## 2. The SM seat's v1.5 (sm:B1525), answered by its line", "**C3, P is the fibre's elliptic involution.**",
              "**Standing: RE-DERIVED.**", "Exactly two isometries act on the cusp as the identity."):
        assert _norm(s) in t, s
    v = json.loads((ARC / "arc_verdict.json").read_text(encoding="utf-8"))
    assert v["id"] == "B1526" and v["verdict"] == "PROVED" and v["creates_law"] is False and v["identifications"] == []
    assert v["prior_work"]["standing"] == "RE-DERIVED" and v["scope"]["reach"] == "general"
    assert "|" not in v["claim_one_line"] and "0 of 19" in v["claim_one_line"]
    sys.path.insert(0, str(ROOT / "scripts" / "checks"))
    import prior_work
    assert prior_work.validate(v["prior_work"]) == []


def test_ledgers_and_surfaces():
    rl = (ROOT / "docs" / "RELAY_LEDGER.md").read_text(encoding="utf-8")
    assert "| `CC_TO_SM_AND_CODEX_2026-10-03_GENESIS_V1_5_FK1_CONFIRMED_FK12_THE_REGISTER.md` | BANKED | 2026-10-03 |" in rl
    assert "| `SM_TO_CC_AND_CODEX_2026-10-03_GENESIS_V1_6.md` | OPEN | 2026-10-03 |" in rl
    assert "| main @ 77714caf → 5c0951b7 (2026-10-03;" in rl
    relay = _norm(RELAY_OUT.read_text(encoding="utf-8"))
    for s in ("Your v1.5 is the head.", "exactly one non-trivial class that keeps the orientation and the base",
              "A seat that builds a GENESIS version on an older head renames it when it reads the newer one"):
        assert _norm(s) in relay, s
    leads = _norm((ROOT / "docs" / "OPEN_LEADS.md").read_text(encoding="utf-8"))
    assert "[2026-10-03, sm:B1526] GENESIS v1.6." in leads
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    assert re.search(r"\[`GENESIS\.md`\]\(GENESIS\.md\) v1\.(6|8) is canonical on this branch", readme)   # v1.8 since sm:B1528
    assert "v1.2 is canonical" not in readme
    lock = (ROOT / "tests" / "test_b1525_genesis_v15.py").read_text(encoding="utf-8")
    assert 'V15_KEPT = ROOT / "frontier" / "B1526_genesis_v16" / "received" / "GENESIS_v1_5_sm.md"' in lock
