"""Cell 4 -- every load-bearing paper claim must stay traceable and re-runnable.

The paper's appendix asserts that an automated check covers every row and that the check is
adversarially controlled. These tests are that assertion. If a claim's backing decays -- an arc
retyped, a lock deleted, a reproducer removed -- the paper is making an unsupported statement,
and that is a defect in the paper, not in the record.
"""
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "checks" / "paper_provenance.py"


def _run(*a):
    return subprocess.run([sys.executable, str(SCRIPT), *a],
                          capture_output=True, text=True, cwd=str(ROOT))


def test_no_paper_claim_is_unsupported():
    r = _run()
    assert r.returncode == 0, r.stdout + r.stderr
    m = re.search(r"DEFECTS: (\d+)", r.stdout)
    assert m and m.group(1) == "0", r.stdout


def test_generator_can_fail():
    """MB12: a claim pointed at a non-existent arc MUST be reported. An appendix that
    certifies whatever it is handed certifies nothing."""
    r = _run("--selftest")
    assert r.returncode == 0, r.stdout + r.stderr
    assert "reported: True" in r.stdout, r.stdout
    assert "CONTROLS PASS" in r.stdout, r.stdout


def test_every_claim_carries_a_lock():
    out = _run().stdout
    for line in out.splitlines():
        if line.startswith(("OK ", "!! ")):
            assert "locks=0" not in line, f"claim with no test lock: {line}"


def test_open_arcs_are_declared_not_inferred():
    """An OPEN arc may back a claim only when explicitly declared 'computed' AND shipping a
    reproducer -- so the honest case and the sloppy case cannot be confused."""
    out = _run().stdout
    for line in out.splitlines():
        if " OPEN " in line:
            assert "[computed]" in line and "repro=y" in line, line


def test_appendix_in_paper_is_the_generated_one():
    tex = (ROOT / "papers" / "P3_THE_PAPER" / "main.tex").read_text(encoding="utf-8")
    assert "GENERATED by scripts/checks/paper_provenance.py" in tex
    assert "Appendix: where each claim is verified" in tex
    gen = _run("--tex").stdout
    # the table body must match what the generator emits now
    for row in [l for l in gen.splitlines() if l.endswith(r"\\") and " & " in l][:5]:
        assert row in tex, f"appendix is stale, regenerate: {row[:70]}"
