"""
w2_inputverify.py -- cc2's INPUT-VERIFICATION CELL for PREREG_W2
(Origin Axiom, GENERATION-LEG wave 2, seat cc2).

INDEPENDENCE STATEMENT: this script shares no code and no intermediate
data with cc's Molien cell (frontier/B674_generation_leg/cellES/). It was
written having read ONLY: PREREG_W2.md, W2_DESIGN_NOTE_GAMMA5.md,
FINDINGS.md and CROSSCHECK_W2_CC2.md / GENERATION_LEG_PLAN_CC2.md (the
route-1 kill narrative, NOT cellES's scripts/data), frontier/B644_*
(the congruence-shadow character computation), and the banked
golden-rotation law as recorded in docs/LAW_MAP.md row 26. cellES/ was
never opened.

TASK: derive, from the holonomy/Fox side alone, the exact eigenvalue
distribution of W = sigma(A_1) (order 10, eigenvalues e^{+-i pi/5}) on
the graded pieces of:
  PRIMARY  V  = the graded module generated by the vector-valued
                weight-1/5 doublet (F1, F2) over the ring (+) M_k(Gamma(5))
  CONTROL     = the plain weight tower (+) M_k(Gamma(5))
through grade 40 (grade == q-power, so this bounds q^40 in Sym(V)).

ALL eigenvalues are 10th roots of unity zeta_10 = e^{i pi/5}; every one
is carried EXACTLY as an integer exponent j in Z/10 (zeta_10^j). This is
an exact representation -- no floating point ever enters a verdict path.
sympy is used only (a) for symbolic identity checks of the closed-form
derivation (done once, structurally, over a symbolic degree d) and (b)
to render traces as exact elements of Z[phi] = Z[sqrt5] for the
human-facing log/report.

======================================================================
DERIVATION CHAIN (each step names its provenance)
======================================================================

STEP 0 -- banked/given facts (cited, NOT re-derived here)
----------------------------------------------------------
(0a) [GIVEN, task/PREREG_W2 geometric setup + standard modular-curve
     theory] X(5) = Gamma(5)\\H* is genus 0 (=P^1), with c = 12 cusps;
     Gamma(5) is torsion-free, -I not in Gamma(5), all cusps regular.
     [index of Gamma(5) in PSL(2,Z) is 60 = |PSL(2,F_5)|, standard.]
(0b) [BANKED LAW -- frontier/B674_generation_leg/FINDINGS.md +
     docs/LAW_MAP.md row 26 ("THE GOLDEN-ROTATION LAW"), CITED not
     re-derived] The canonical modular lift of the monodromy A_1
     through the weight-1/5 slash action is elliptic of order 10:
     tr sigma(A_1) = phi EXACTLY, eigenvalues e^{+-i pi/5} = zeta_10^{+-1}.
(0c) [BANKED -- frontier/B644_mckay_comparison, exact sympy character
     computation in b644_character_check.py / b644_mckay.py, CITED not
     re-derived] In SL(2,5), trace phi = 2cos(pi/5) identifies the
     order-10 conjugacy class "(10,False)" -- Galois-conjugate (under
     sqrt5 -> -sqrt5) to class "(10,True)" of trace -1/phi = 2cos(3pi/5).
     This is the exact class-selection argument the task calls for:
     the trace picks the SL(2)-eigenvalue angle theta = pi/5, and for an
     elliptic Mobius map the LOCAL rotation angle at a fixed point is
     2*theta (standard fact: trace 2cos(theta) <-> local multiplier
     e^{2 i theta}), so theta=pi/5 gives local multiplier e^{2 pi i/5}
     = zeta_5 -- the "72-degree" class, as opposed to the OTHER order-5
     class (144 degrees, zeta_5^2) that trace -1/phi would select.
(0d) [GIVEN, task] the shadow's image acts on X(5)=P^1 as an order-5
     (PSL) rotation with EXACTLY TWO fixed points (a Mobius map of
     P^1, finite order > 2, is always conjugate to z -> zeta z, which
     has exactly the 2 fixed points {0, infinity}). Since Gamma(5) is
     torsion-free (no elliptic points in H), these 2 fixed points must
     be among the 12 CUSPS: 12 = 2 (fixed) + 5 + 5 (two order-5 orbits).

STEP 1 -- Riemann-Roch: dim M_k(Gamma(5)) (derived here, standard
algebraic geometry of modular curves, not from any walled-off source)
----------------------------------------------------------------------
Weight-2 forms <-> holomorphic differentials on X(5) with at most
simple poles at the cusps: deg(omega^2) = 2g-2+c (no elliptic-point
correction terms since torsion-free). With g=0, c=12: deg(omega^2)=10,
so deg(omega) = 5 -- an INTEGER because c is even, so there is no
parity obstruction to defining omega itself (this is where "regular
cusps + torsion-free" does the work: no half-integer corrections of
any kind enter, for ANY k, even or odd). Hence
    deg(omega^k) = 5k   for every integer k >= 0,
matching the task's own formula deg = k(2g-2+c)/2 = k*10/2 = 5k.
Because all cusps are regular, weight-k forms (any parity of k) are
literally global holomorphic sections of the single line bundle
omega^k on X(5) = P^1 -- there is no case split by parity of k (that
is precisely what "all cusps regular" buys: an irregular cusp would
force half-integer-power q-expansions for odd k and break this
uniformity; it is excluded by hypothesis). Since X(5)=P^1,
    dim M_k(Gamma(5)) = h^0(P^1, O(5k)) = 5k + 1   for all k >= 0.
[Sanity check against public classical knowledge, not used as an
input: dim M_1(Gamma(5)) = 6, the classical six weight-1 icosahedral
Eisenstein series for Gamma(5) -- matches 5*1+1=6.]

STEP 2 -- the closed form for W on a graded piece (derived here;
equivariant line-bundle / Atiyah-Bott holomorphic-Lefschetz theory)
----------------------------------------------------------------------
W acts on X(5)=P^1 as z -> zeta z (zeta = zeta_5, from 0c/0d), fixing
0 and infinity, with local derivative zeta at 0 and zeta^{-1} at
infinity. Writing sections of O(d) as degree-<=d polynomials f(z) (z
the affine coordinate away from infinity), and defining the lift
(W . f)(z) := chi_0 * f(zeta z) for a fiber character chi_0 in mu_10 at
z=0, the monomial z^m (m=0..d) is an eigenvector:
        W . z^m = chi_0 * zeta^m * z^m.
Converting to the w=1/z chart shows the fiber character at infinity is
chi_inf = chi_0 * zeta^d (derived below, verified symbolically).

STRUCTURAL FACT (ring automorphism / multiplicativity): W must act
compatibly with the ring product M_{k1} x M_{k2} -> M_{k1+k2}, forcing
chi_0(k) to be a HOMOMORPHISM in k: chi_0(k1+k2) = chi_0(k1) chi_0(k2),
i.e. chi_0(k) = mu^k for a single base character mu = chi_0(1) in
mu_10 (a 10th root of unity, since chi_0(k)^5 must be the "W^5 = global
scalar" sign, itself a 10th-root-of-unity constraint -- see the W^5
gate below). CLOSED FORM at grade k:
    eigenvalues of W on M_k(Gamma(5)) = { mu^k * zeta_5^m : m = 0..5k }.

RESIDUAL AMBIGUITY (FLAGGED, not resolved by dimension-count or
group-structure consistency alone -- exactly as anticipated by the
task): dimension count (= 5k+1 values regardless of mu) and W^10=1,
W^5=+-1 (both automatic for ANY mu in mu_10) do NOT pin mu. What DOES
pin it, under one extra structural ASSUMPTION stated here explicitly
as a CONVENTION: automorphy factors of a FIXED elliptic matrix are
exponential in the weight parameter (j(gamma,z)^k = exp(k log j)), so
chi_0(k) = exp(i*k*phase) for a SINGLE fixed real phase, i.e. chi_0
extends to a one-parameter (in the weight variable) character. Anchoring
this exponential law at the BANKED grade w=1/5 value (the doublet
eigenvalue e^{+i pi/5}, taken as the "+1" representative) gives
phase = pi (uniquely -- the anchoring is at w=1/5 and w=1/5 * phase =
pi/5 (mod 2pi) forces phase = pi (mod 2pi) after multiplying back by 5,
with NO residual branch ambiguity, since 5 * 2*pi*integer/5 = 2*pi*integer
either way). Hence mu = e^{i pi} = -1, i.e.
    chi_0(k) = (-1)^k = zeta_10^{5k}          [CONTROL, FLAGGED CONVENTION]
THIS EXPONENTIAL-CONTINUITY ASSUMPTION IS THE ONE PLACE THIS
DERIVATION CANNOT INDEPENDENTLY VERIFY WITHOUT ROUTE 1's INTERNAL
COCYCLE (walled off in cellES); it is flagged, not silently assumed.

STEP 3 -- PRIMARY: tensor with the banked doublet
----------------------------------------------------------------------
The (F1,F2) system is a genuine 2-DIMENSIONAL multiplier representation
at weight 1/5 (not a single character) -- the banked law (0b) gives its
eigenvalues DIRECTLY as {e^{+i pi/5}, e^{-i pi/5}} = {zeta_10^{+1},
zeta_10^{-1}}. Per the task (step 4): "its graded pieces are
(F1,F2)-multiples of M_k pieces" -- i.e. grade n of V (weight n+1/5)
is, AS A VECTOR SPACE, F1 x M_n(Gamma(5)) (+) F2 x M_n(Gamma(5))
[ASSUMPTION, FLAGGED: this module is FREE of rank 2 over the ring
through grade 40, i.e. no linear relations among the (F1,F2)-multiples
of M_n in this range -- the natural/generic reading of "the graded
module generated by (F1,F2)"]. The induced eigenvalues on grade n are
the TENSOR product of grade n's CONTROL eigenvalues with the banked
doublet:
    { zeta_10^{5n+2m} * zeta_10^{+-1} : m = 0..5n }
    = { zeta_10^{(5n+2m+1) mod 10}, zeta_10^{(5n+2m-1) mod 10} : m=0..5n }
[NOTE: this is NOT the same as naively extending the CONTROL
exponential law chi_0(k)=(-1)^k to the fractional weight w=n+1/5 as a
SINGLE character -- that would wrongly give dimension 5n+2 rather than
the correct 2(5n+1); the doublet is genuinely 2-dimensional and must be
tensored in, not folded into a single chi_0(w).]

STEP 4 -- verification gates (all implemented below)
----------------------------------------------------------------------
GATE 1 (dimension sum): per grade, multiplicities sum to dim M_n(Gamma(5))
   = 5n+1 [CONTROL] / 2(5n+1) [PRIMARY], matching STEP 1's R-R count.
GATE 2 (trace, two independent ways): (a) direct sum of the eigenvalue
   list; (b) the holomorphic-Lefschetz closed form
       tr(W|H^0) = chi_0/(1-dg_0) + chi_inf/(1-dg_inf)  [dg_0=zeta_5,
       dg_inf=zeta_5^{-1}, chi_inf = chi_0*zeta_5^d]
   computed independently (no term-by-term sum), both reduced exactly
   in Z[zeta_10] and compared.
GATE 3 (W^5 = global scalar): the "multiplier sign" fact -- for every
   grade, ALL stored eigenvalues raised to the 5th power must agree
   (W^5 covers the identity on the base P^1, hence acts as one global
   scalar on the whole graded piece).
GATE 4 (Galois consistency): applying the field automorphism
   sqrt5 -> -sqrt5 (which lifts to j -> 3j mod 10 on zeta_10, the
   coset in Gal(Q(zeta_10)/Q) = (Z/10)* = {1,3,7,9} not fixing
   Q(sqrt5) = {1,9}) to every exponent in a grade's table must
   reproduce EXACTLY the table obtained by using the OTHER (conjugate)
   SL(2,5) class from (0c) -- i.e. by re-running the whole
   construction with zeta_5 -> zeta_5^{-1} (trace phi -> -1/phi).
   This is the task's "component-swap" stability check.
SUPPLEMENTARY (not one of the 4 official gates; reported for context):
   non-centrality of W on V (the vacuity-gate's own criterion) is
   confirmed directly: already at grade 1, CONTROL's 6 eigenvalues are
   NOT all equal.
"""

import json
import os
import sympy as sp

HERE = os.path.dirname(os.path.abspath(__file__))
MAXGRADE = 40  # bounds q^40 in Sym(V)

# ----------------------------------------------------------------------
# exact symbolic setup (sympy, used only for identity checks / display)
# ----------------------------------------------------------------------
I = sp.I
PI = sp.pi
ZETA10 = sp.exp(I * PI / 5)          # = e^{i pi/5}, primitive 10th root
PHI = (1 + sp.sqrt(5)) / 2


def zeta10_pow(j):
    """Exact symbolic value of zeta_10^j, j any integer (reduced mod 10)."""
    j = j % 10
    return sp.exp(I * PI * j / 5)


# ----------------------------------------------------------------------
# STRUCTURAL IDENTITY CHECK (once, symbolically, for general d):
# eigenvalue-sum == holomorphic-Lefschetz closed form, with
# chi_inf := chi_0 * zeta^d, dg_0 = zeta, dg_inf = 1/zeta.
# ----------------------------------------------------------------------
def _verify_lefschetz_identity_symbolic(dmax=6):
    """Symbolic sanity check of the closed-form derivation in STEP 2,
    for a symbolic chi_0, zeta and each concrete d = 0..dmax. Returns
    True iff the two formulas agree exactly (sympy simplify to 0) for
    every d tested. This is executed once at import/run time as a
    structural self-test of the derivation, independent of any
    specific grade's numbers computed later."""
    chi0, zeta = sp.symbols('chi0 zeta', complex=True)
    ok = True
    for d in range(0, dmax + 1):
        term_sum = sum(chi0 * zeta**m for m in range(d + 1))
        chi_inf = chi0 * zeta**d
        lefschetz = chi0 / (1 - zeta) + chi_inf / (1 - 1 / zeta)
        diff = sp.simplify(sp.together(term_sum - lefschetz))
        if diff != 0:
            ok = False
            print(f"  [STRUCTURAL CHECK FAILED] d={d}: residual {diff}",
                  flush=True)
    return ok


# ----------------------------------------------------------------------
# exact eigenvalue tables (integers only: exponents j in Z/10)
# ----------------------------------------------------------------------
def control_exponents(k):
    """Eigenvalue exponents (list of ints mod 10) of W on M_k(Gamma(5)),
    for the '+72 degree' class (zeta_5 = zeta_10^2), chi_0(k)=(-1)^k
    = zeta_10^{5k}. Returns the raw list (length 5k+1, with repeats)."""
    d = 5 * k
    chi0_exp = (5 * k) % 10
    return [(chi0_exp + 2 * m) % 10 for m in range(d + 1)]


def control_exponents_conjugate(k):
    """Same, but using the GALOIS-CONJUGATE SL(2,5) class (0c): trace
    -1/phi, i.e. zeta_5 -> zeta_5^{-1} (= zeta_10^{-2}). chi_0(k) is
    UNCHANGED (it is pinned by the (F1,F2) doublet anchor, which does
    not depend on which order-5 class is used for the base rotation --
    see FINDINGS_RAW.md for why this is the correct convention for the
    swap check)."""
    d = 5 * k
    chi0_exp = (5 * k) % 10
    return [(chi0_exp - 2 * m) % 10 for m in range(d + 1)]


def primary_exponents(n):
    """Eigenvalue exponents of W on V_n = F1*M_n (+) F2*M_n (PRIMARY,
    weight n+1/5), '+72 degree' class. Length 2*(5n+1)."""
    base = control_exponents(n)
    return [(e + 1) % 10 for e in base] + [(e - 1) % 10 for e in base]


def primary_exponents_conjugate(n):
    """The GALOIS-CONJUGATE PRIMARY construction. IMPORTANT CORRECTION
    (caught by gate 4 on the first run, documented in FINDINGS_RAW.md):
    the (F1,F2) doublet's OWN eigenvalues zeta_10^{+-1} are algebraic
    data subject to the SAME Galois automorphism sigma_3: j -> 3j as
    everything else -- sigma_3(zeta_10^{+-1}) = zeta_10^{+-3}, matching
    sigma_3(phi) = -1/phi (2cos(pi/5)=phi -> 2cos(3pi/5)=-1/phi). So the
    conjugate doublet shift is +-3, NOT +-1 (keeping it at +-1 while
    only flipping the base rotation was the bug: it silently assumed
    the doublet was Galois-fixed, which it is not)."""
    base = control_exponents_conjugate(n)
    return [(e + 3) % 10 for e in base] + [(e - 3) % 10 for e in base]


def bucket(exps):
    """List of 10 counts, mult[j] = multiplicity of zeta_10^j."""
    m = [0] * 10
    for e in exps:
        m[e % 10] += 1
    return m


def galois_relabel(mult):
    """Apply j -> 3j mod 10 (the sqrt5 -> -sqrt5 lift) to a
    multiplicity vector, returning the relabeled multiplicity vector."""
    out = [0] * 10
    for j, c in enumerate(mult):
        out[(3 * j) % 10] += c
    return out


def conj_relabel(mult):
    """Apply j -> -j mod 10 (complex conjugation) -- used only for an
    internal self-consistency spot check."""
    out = [0] * 10
    for j, c in enumerate(mult):
        out[(-j) % 10] += c
    return out


# ----------------------------------------------------------------------
# exact trace via sympy (Z[phi] display) -- for gate 2
# ----------------------------------------------------------------------
def trace_from_mult(mult):
    """Exact trace = sum_j mult[j] * zeta_10^j, returned as a simplified
    sympy expression (expected to land in Z[phi] once combined with its
    Galois conjugate; individual grade traces may be non-real Z[zeta_10]
    elements -- reported exactly either way)."""
    val = sum(c * zeta10_pow(j) for j, c in enumerate(mult))
    return sp.nsimplify(sp.expand_complex(sp.simplify(val)), [sp.sqrt(5)],
                         rational=False)


def trace_lefschetz(k, chi0_exp, zeta_exp_at_0):
    """Independent closed-form (no term-by-term sum): the
    holomorphic-Lefschetz fixed point trace, for CONTROL grade k, with
    the given fiber character exponent at 0 (chi0_exp, mod 10) and base
    rotation exponent at 0 (zeta_exp_at_0, i.e. zeta = zeta_10^{zeta_exp_at_0}).
    chi_inf = chi_0 * zeta^d, dg_0 = zeta, dg_inf = 1/zeta."""
    d = 5 * k
    chi0 = zeta10_pow(chi0_exp)
    zeta = zeta10_pow(zeta_exp_at_0)
    chi_inf = chi0 * zeta**d
    val = chi0 / (1 - zeta) + chi_inf / (1 - 1 / zeta)
    return sp.nsimplify(sp.expand_complex(sp.simplify(val)), [sp.sqrt(5)],
                         rational=False)


# ----------------------------------------------------------------------
# main run
# ----------------------------------------------------------------------
def main():
    print("=" * 70, flush=True)
    print("W2 INPUT-VERIFICATION CELL -- holonomy-side eigenvalue "
          "distribution", flush=True)
    print("=" * 70, flush=True)

    print("\n[structural check] symbolic Lefschetz-identity self-test "
          "(d=0..6)...", flush=True)
    struct_ok = _verify_lefschetz_identity_symbolic(6)
    print(f"  identity holds for all tested d: {struct_ok}", flush=True)
    if not struct_ok:
        print("ABORT: closed-form derivation itself is inconsistent.",
              flush=True)
        return

    control_table = {}
    primary_table = {}
    gate1 = {"control": {}, "primary": {}, "all_pass": True}
    gate2 = {"control": {}, "all_pass": True}
    gate3 = {"control": {}, "primary": {}, "all_pass": True}
    gate4 = {"control": {}, "primary": {}, "all_pass": True}

    for k in range(0, MAXGRADE + 1):
        exps = control_exponents(k)
        mult = bucket(exps)
        dim_expected = 5 * k + 1
        control_table[k] = {"dim": dim_expected, "mult": mult}

        # GATE 1: dimension sum
        s = sum(mult)
        ok1 = (s == dim_expected)
        gate1["control"][k] = ok1
        gate1["all_pass"] &= ok1

        # GATE 2: trace two ways (control only -- primary trace is the
        # doublet-tensor of the same two numbers, so is implied)
        t_sum = trace_from_mult(mult)
        chi0_exp = (5 * k) % 10
        t_lef = trace_lefschetz(k, chi0_exp, 2)  # zeta_5 = zeta_10^2
        diff = sp.simplify(t_sum - t_lef)
        ok2 = (diff == 0)
        gate2["control"][k] = {
            "trace_eigsum": str(t_sum),
            "trace_lefschetz": str(t_lef),
            "match": ok2,
        }
        gate2["all_pass"] &= ok2

        # GATE 3: W^5 = global scalar (all exponents*5 mod 10 agree)
        fifth = {(5 * e) % 10 for e in exps}
        ok3c = (len(fifth) == 1)
        gate3["control"][k] = {"w5_scalar_exponents": sorted(fifth),
                                "pass": ok3c}
        gate3["all_pass"] &= ok3c

        # GATE 4: Galois consistency (control)
        relabeled = galois_relabel(mult)
        conj_exps = control_exponents_conjugate(k)
        conj_mult = bucket(conj_exps)
        ok4c = (relabeled == conj_mult)
        # internal spot check: table is complex-conjugation-symmetric
        selfconj_ok = (conj_relabel(mult) == mult)
        gate4["control"][k] = {"pass": ok4c,
                                "self_conjugate_symmetric": selfconj_ok}
        gate4["all_pass"] &= ok4c

        # ---- PRIMARY ----
        pexps = primary_exponents(k)
        pmult = bucket(pexps)
        pdim_expected = 2 * (5 * k + 1)
        primary_table[k] = {"dim": pdim_expected, "mult": pmult}

        ps = sum(pmult)
        ok1p = (ps == pdim_expected)
        gate1["primary"][k] = ok1p
        gate1["all_pass"] &= ok1p

        fifth_p = {(5 * e) % 10 for e in pexps}
        ok3p = (len(fifth_p) == 1)
        gate3["primary"][k] = {"w5_scalar_exponents": sorted(fifth_p),
                                "pass": ok3p}
        gate3["all_pass"] &= ok3p

        prelabeled = galois_relabel(pmult)
        pconj_exps = primary_exponents_conjugate(k)
        pconj_mult = bucket(pconj_exps)
        ok4p = (prelabeled == pconj_mult)
        gate4["primary"][k] = {"pass": ok4p}
        gate4["all_pass"] &= ok4p

        print(f"grade {k:2d}: CONTROL dim={dim_expected:4d} mult={mult} "
              f"| PRIMARY dim={pdim_expected:4d} mult={pmult}", flush=True)
        print(f"          gate1(dim) C={ok1} P={ok1p} | "
              f"gate2(trace) {ok2} | gate3(W^5 scalar) C={ok3c} P={ok3p} | "
              f"gate4(Galois) C={ok4c} P={ok4p}", flush=True)

    # ---- supplementary: vacuity / non-centrality check ----
    noncentral_grade1 = len(set(control_table[1]["mult"])) > 1 or \
        sum(1 for c in control_table[1]["mult"] if c > 0) > 1
    print(f"\n[supplementary] non-centrality at CONTROL grade 1: "
          f"{noncentral_grade1} (mult vector {control_table[1]['mult']})",
          flush=True)

    print("\n" + "=" * 70, flush=True)
    print("GATE SUMMARY", flush=True)
    print("=" * 70, flush=True)
    print(f"GATE 1 (dimension sums match Riemann-Roch, every grade): "
          f"{gate1['all_pass']}", flush=True)
    print(f"GATE 2 (trace: eigenvalue-sum == holomorphic-Lefschetz, "
          f"every grade): {gate2['all_pass']}", flush=True)
    print(f"GATE 3 (W^5 acts as one global scalar per grade): "
          f"{gate3['all_pass']}", flush=True)
    print(f"GATE 4 (Galois consistency: sqrt5->-sqrt5 == conjugate-class "
          f"swap): {gate4['all_pass']}", flush=True)

    all_gates_pass = (gate1["all_pass"] and gate2["all_pass"] and
                       gate3["all_pass"] and gate4["all_pass"])
    print(f"\nALL GATES PASS: {all_gates_pass}", flush=True)

    # ---- write JSON ----
    out = {
        "meta": {
            "task": "PREREG_W2 cc2 cell -- holonomy-side eigenvalue "
                    "distribution of W = sigma(A_1), independent of "
                    "cc's Molien cell (cellES never read)",
            "max_grade": MAXGRADE,
            "banked_facts_used": {
                "golden_rotation_law": "tr sigma(A_1) = phi EXACTLY, "
                    "eigenvalues e^{+-i pi/5}; source: "
                    "frontier/B674_generation_leg/FINDINGS.md, "
                    "docs/LAW_MAP.md row 26 (cited, not re-derived)",
                "sl2_5_class_selection": "trace phi = 2cos(pi/5) "
                    "identifies SL(2,5) class (10,False), Galois-"
                    "conjugate to (10,True) [trace -1/phi]; source: "
                    "frontier/B644_mckay_comparison "
                    "(b644_mckay.py / b644_character_check.py)",
                "curve_geometry": "X(5)=P^1, genus 0, 12 cusps, "
                    "torsion-free, -I not in Gamma(5), all cusps "
                    "regular, order-5 rotation with exactly 2 fixed "
                    "points -- given in the task/PREREG_W2 setup + "
                    "standard modular curve theory",
            },
            "flagged_conventions": [
                {
                    "name": "chi_0(k) exponential-continuity pin",
                    "statement": "chi_0(k) = (-1)^k = zeta_10^{5k} for "
                        "the CONTROL tower's fiber character at the "
                        "z=0 fixed point, obtained by ASSUMING the "
                        "fiber character is exponential in the weight "
                        "parameter (chi_0(w) = e^{i*w*phase} for a "
                        "SINGLE fixed phase) and anchoring at the "
                        "banked doublet value chi_0(1/5)=e^{i pi/5}. "
                        "Dimension-count and the W^5/W^10 group-"
                        "structure constraints alone do NOT pin "
                        "chi_0(k) -- any mu in mu_10 satisfies them. "
                        "This exponential-continuity assumption cannot "
                        "be independently verified from the holonomy "
                        "side without route 1's internal cocycle data "
                        "(cellES, deliberately not read). FLAGGED, not "
                        "silently resolved.",
                },
                {
                    "name": "module freeness of (F1,F2) over the ring",
                    "statement": "PRIMARY V_n is assumed FREE of rank 2 "
                        "over M_n(Gamma(5)) (V_n = F1*M_n (+) F2*M_n, "
                        "dimension 2*(5n+1)) through grade 40 -- i.e. "
                        "no linear relations among the (F1,F2)-"
                        "multiples of M_n forms in this range. This is "
                        "the natural/generic reading of 'the graded "
                        "module generated by (F1,F2)' but is an "
                        "assumption, not proved here.",
                },
                {
                    "name": "which SL(2,5) class is '+72 degrees'",
                    "statement": "zeta_5 = zeta_10^2 (angle +2pi/5) is "
                        "chosen as the base rotation multiplier at the "
                        "z=0 fixed point for the class selected by "
                        "trace=phi; the opposite assignment (z=0 <-> "
                        "z=infinity swapped) would relabel m -> d-m "
                        "within each grade but does not change any "
                        "multiplicity table (verified: the tables are "
                        "symmetric under complex conjugation j -> -j, "
                        "see gate 4's self-consistency spot check), so "
                        "this choice is convention-free in its effect "
                        "on the reported multiplicities.",
                },
            ],
            "self_correction_log": [
                "First run of this script: gate 4 (Galois consistency) "
                "FAILED for PRIMARY at every grade (CONTROL passed). "
                "Root cause: primary_exponents_conjugate() initially kept "
                "the (F1,F2) doublet shift fixed at {+1,-1} while only "
                "flipping the base-rotation exponent, silently assuming "
                "the doublet's own eigenvalues zeta_10^{+-1} were "
                "Galois-fixed. They are not: sigma_3 (j -> 3j, the lift "
                "of sqrt5 -> -sqrt5) sends zeta_10^{+-1} -> zeta_10^{+-3} "
                "(matching sigma_3(phi) = -1/phi = 2cos(3 pi/5)). Fixed "
                "by using shift {+3,-3} for the conjugate doublet; gate 4 "
                "then passes at every grade 0..40. Reported here as "
                "evidence the gate is a live check, not a rubber stamp.",
            ],
        },
        "control": {str(k): v for k, v in control_table.items()},
        "primary": {str(k): v for k, v in primary_table.items()},
        "gates": {
            "gate1_dimension_sum": gate1,
            "gate2_trace_two_ways": gate2,
            "gate3_w5_global_scalar": gate3,
            "gate4_galois_consistency": gate4,
            "all_gates_pass": all_gates_pass,
            "supplementary_noncentrality_grade1": noncentral_grade1,
        },
    }
    json_path = os.path.join(HERE, "w2_eigendist.json")
    with open(json_path, "w") as f:
        json.dump(out, f, indent=2)
    print(f"\nwrote {json_path}", flush=True)
    print("\nW2_INPUTVERIFY DONE", flush=True)


if __name__ == "__main__":
    main()
