"""B149 -- EXACT irreducibility classification over F_p (sage-python). The floating-point Schur commutant is
unreliable (it false-flags the provably-reducible Q=0 stratum as irreducible). Over F_p (p = 1 mod 3, so w in F_p)
the commutant dimension is EXACT. For each fixed-Q slice we find genuine (det != 0) F_p-points of the defining ideal,
and tabulate [commutant dim == 1  (irreducible)]  vs  [M^4=L holds (all E[i,j] == 0)].

Decisive: the (irreducible AND M^4=L fails) cell must be EMPTY for "M^4=L on the whole irreducible locus".
Run: ~/.local/bin/sage-python -u frontier/B149_sl4_ideal_completeness/classify_fp.py
"""
import collections
import sys

from sage.all import (GF, AlarmInterrupt, PolynomialRing, alarm, cancel_alarm,
                      diagonal_matrix, identity_matrix, matrix, vector)

P = int(sys.argv[1]) if len(sys.argv) > 1 else 1000003     # default 1000003 = 1 mod 3 -> w exists in F_p
ALLOWED = {(0, 0), (0, 1), (1, 0), (1, 1), (2, 3), (3, 2)}
SLICES = {
    "rankQ2 (Q=I2,B89)":    {(0, 2): 1, (0, 3): 0, (1, 2): 0, (1, 3): 1},
    "rankQ1 [[1,0],[0,0]]": {(0, 2): 1, (0, 3): 0, (1, 2): 0, (1, 3): 0},
    "rankQ1 [[1,1],[0,0]]": {(0, 2): 1, (0, 3): 1, (1, 2): 0, (1, 3): 0},
    "rankQ1 [[0,1],[0,0]]": {(0, 2): 0, (0, 3): 1, (1, 2): 0, (1, 3): 0},
    "rankQ0 (Q=0)":         {(0, 2): 0, (0, 3): 0, (1, 2): 0, (1, 3): 0},
}


def omega(K):
    R = PolynomialRing(K, "x")
    x = R.gen()
    return min((x**2 + x + 1).roots(multiplicities=False))


def algebra_dim(A, B, K):
    """dim of the associative algebra generated by {I,A,B}, EXACT over K, via SPAN CLOSURE (not naive BFS): keep a
    row-reduced basis (<=16 elts); left-multiply each new basis element by A,B; add only linearly-independent results
    until closure. Burnside: the rep is ABSOLUTELY IRREDUCIBLE <=> this dim = 16. (The commutant/Schur test is NOT a
    valid irreducibility test -- a reducible non-semisimple rep can have commutant = scalars; Burnside is the right one.)"""
    I4 = matrix.identity(K, 4)
    rows = [list(I4.list())]
    M = matrix(K, rows)
    queue = [I4]
    while queue:
        X = queue.pop()
        for G in (A, B):
            Y = G * X
            M2 = M.stack(matrix(K, [list(Y.list())]))
            if M2.rank() > M.rank():
                M = M2
                queue.append(Y)
                if M.rank() == 16:
                    return 16
    return M.rank()


def points_on_slice(K, w, qsub, want=12, tries=40):
    """Genuine (det != 0) F_p-points of the slice defining ideal: saturate by det, cut to 0-dim with random
    hyperplanes, take rational points."""
    pinned = {p: v for p, v in qsub.items() if v is not None}
    keep = [(i, j) for i in range(4) for j in range(4) if (i, j) not in pinned]
    R = PolynomialRing(K, ["t%d%d" % (i, j) for (i, j) in keep])
    var = {p: R(n) for p, n in zip(keep, R.gens())}
    ent = lambda i, j: R(pinned[(i, j)]) if (i, j) in pinned else var[(i, j)]
    t = matrix(R, 4, 4, lambda i, j: ent(i, j))
    A = diagonal_matrix(R, [R(1), R(1), R(w), R(w**2)])
    I = R.ideal([(t * A * t)[i, j] for i in range(4) for j in range(4) if (i, j) not in ALLOWED])
    det = t.determinant()
    Isat = I.saturation(R.ideal([det]))[0]
    if Isat.dimension() < 0:
        return []
    d = Isat.dimension()
    pts = []
    import sage.all as sg
    for _ in range(tries):
        lins = [sum(K.random_element() * g for g in R.gens()) + K.random_element() for _ in range(d)]
        J = Isat + R.ideal(lins)
        try:
            alarm(120); V = J.variety(); cancel_alarm()
        except (AlarmInterrupt, Exception):                  # noqa: BLE001
            cancel_alarm(); continue
        for sol in V:
            tt = matrix(K, 4, 4, lambda i, j: K(pinned[(i, j)]) if (i, j) in pinned else sol[var[(i, j)]])
            if tt.determinant() != 0:
                pts.append(tt)
        if len(pts) >= want:
            break
    return pts


def main():
    K = GF(P)
    w = omega(K)
    A = diagonal_matrix(K, [K(1), K(1), w, w**2])
    A2 = diagonal_matrix(K, [K(1), K(1), w**2, w])
    grand = collections.Counter()
    per_stratum = {}
    print("EXACT over F_%d (w^2+w+1=0):  [irreducible?] x [M^4=L?]\n" % P)
    for name, qsub in SLICES.items():
        tab = collections.Counter()
        for tt in points_on_slice(K, w, qsub):
            B = A.inverse()**2 * tt * A * tt.inverse()       # B = A^-2 t A t^-1 (exact over F_p)
            irr = algebra_dim(A, B, K) == 16                 # Burnside: dim algebra = 16 <=> absolutely irreducible
            mu = A.inverse() * tt
            L = A * B * A.inverse() * B.inverse()
            M = L * (mu.inverse())**4
            m4 = all(M[i, j] == (M[0, 0] if i == j else 0) for i in range(4) for j in range(4)) and \
                M[0, 0] == M[1, 1] == M[2, 2] == M[3, 3]
            tab[("irr" if irr else "red", "M4=L" if m4 else "M4!=L")] += 1
        grand.update(tab)
        per_stratum[name] = {"irr&M4=L": tab[("irr", "M4=L")], "irr&M4!=L": tab[("irr", "M4!=L")],
                             "red&M4=L": tab[("red", "M4=L")], "red&M4!=L": tab[("red", "M4!=L")], "n": sum(tab.values())}
        print("  %-24s  irr&M4=L:%-3d irr&M4!=L:%-3d red&M4=L:%-3d red&M4!=L:%-3d  (n=%d)"
              % (name, tab[("irr", "M4=L")], tab[("irr", "M4!=L")], tab[("red", "M4=L")], tab[("red", "M4!=L")],
                 sum(tab.values())))
    bad = grand[("irr", "M4!=L")]
    print("\n  DECISIVE CELL (irreducible AND M^4=L fails), EXACT over F_p: %d" % bad)
    print("  => %s" % ("CLEAN: over F_p, every irreducible genuine rep satisfies M^4=L; all violations reducible (MB7)."
                       if bad == 0 else "an irreducible rep violates M^4=L over F_p -- genuine outcome (b)."))
    import json
    import pathlib
    art = {"prime": P, "test": "Burnside algebra-dim=16 <=> absolutely irreducible (validated vs the symbolic Q=0 "
           "reducibility exhibit and B89's known irreducibility)", "per_stratum": per_stratum,
           "decisive_cell_irreducible_and_M4L_fails": int(bad),
           "total_irreducible_satisfying_M4L": int(grand[("irr", "M4=L")]),
           "only_stratum_with_irreducible_reps": [n for n, s in per_stratum.items() if s["irr&M4=L"] or s["irr&M4!=L"]],
           "verdict": "CLEAN" if bad == 0 else "outcome_b"}
    pathlib.Path(__file__).resolve().parent.joinpath("irreducibility_fp.json").write_text(json.dumps(art, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
