#!/usr/bin/env python3
"""
B739 Stage-B recompute -- TOMB-L258 (K-M, speculations/TOMBSTONES.md:L258).

BANKED KILL (K-M): the "measurable gap-labeling-rank prediction" built on K-K/K-L
(an observable rank tracking composition period k or SL(n) tower depth n) is DEAD;
it falls with its premises, and "the *correct* rank statement is field-multiplicity
(S023 / L16), not period or tower depth."

THE DISCRIMINATING FACT (what, if true, kills the claim): the candidate rank
observables are CONSTANT while the claimed independent variables (composition
period k, tower depth n) vary -- so no rank observable tracks k or n, and the
prediction has no measurable content.  Concretely:
  (F1) [K-K premise] for EVERY period-k L/R geodesic word, the gap-labeling
       frequency-module rank is 2, independent of k  (killed claim: rank = k);
  (F2) [K-L premise] the SL(n) tower eigenvalues of the golden seed are all
       integer powers of phi^2, so the multiplicative free rank is 1 at every n
       (killed claim: rank = n);
  (F3) [the epitaph's replacement] rank DOES respond to field multiplicity:
       rank = 1 + #distinct quadratic fields (single golden seed -> 2,
       golden+silver -> 3, golden m=1 + m=4 same-field -> 2).
The tombstone ASSERTS these (fact_basis=asserted); here each is re-derived as an
actual computation from the arc's own declared conventions (compute-not-cite, E19,
both directions: F1/F2 are probed for ANY climbing rank observable -- frequency-
module rank, eigenvalue-field degree, multiplicative eigenvalue rank).

CONVENTIONS (arc-declared where they exist; E1 declarations where they do not):
 - [arc, S023/L16, Johnson-Moser] gap-labeling group of a 1D substitution
   operator = the frequency module; single metallic seed m: ZZ + ZZ*alpha_m with
   alpha_m = (sqrt(m^2+4)-m)/2 = 1/mu_m (mu_m the metallic mean); rank = ZZ-rank
   = dim_QQ of the QQ-span of the generators.
 - [E1-declared] modular L/R coding of closed geodesics: L=[[1,0],[1,1]],
   R=[[1,1],[0,1]]; a "period-k geodesic" is (the conjugacy class of) a length-k
   word in {L,R} containing both letters (both letters <=> trace >= 3 <=>
   hyperbolic); its 2-letter substitution has abelianization = the word matrix,
   and the fixed-point letter frequencies are the Perron right-eigenvector of
   that matrix normalized to sum 1 (standard; only the abelianization enters
   the frequency module).
 - [E1-declared] golden seed matrix A = RL = [[2,1],[1,1]] (trace 3, the arc's
   kappa=3 golden seed; eigenvalues phi^{+-2}); "SL(n) tower" = the n-dim
   irreducible Sym^{n-1} of SL(2) acting on degree-(n-1) binary forms in basis
   {x^{n-1-j} y^j}, (x,y) |-> (a x + c y, b x + d y) (the substitution that
   makes Sym a homomorphism -- verified in-run; eigenvalues are convention-
   independent since the alternative is Sym of the similar matrix A^T).
 - [E1-declared] "multiplicative free rank" of a finite set S of nonzero real
   algebraic numbers, all of the form phi^e (e integer): rank of the subgroup
   of RR^x generated by S = rank of the ZZ-lattice of exponents (phi is not a
   root of unity, so phi^ZZ is infinite cyclic).
 - Deterministic: exact sympy arithmetic; mpmath PSLQ at fixed 60 dps as a
   numeric cross-check only; no wall-clock, no randomness, no network.

VERDICT LOGIC: the banked kill is RECONFIRMED iff F1 gives rank 2 for every word
at every k in 2..8 (and never k for k>=3), F2 gives multiplicative rank 1 and
field degree 2 at every n in 2..10 (never n), and F3 gives 2/3/2 as stated.
Any climbing rank found -> REVIVED.
"""

import sys
from fractions import Fraction
from itertools import product as iproduct

import sympy as sp
import mpmath

mpmath.mp.dps = 60  # fixed precision, deterministic

x = sp.Symbol('x')
S5 = sp.sqrt(5)
PHI = (1 + S5) / 2

L = sp.Matrix([[1, 0], [1, 1]])
R = sp.Matrix([[1, 1], [0, 1]])


def word_matrix(word):
    M = sp.eye(2)
    for c in word:
        M = M * (L if c == 'L' else R)
    return M


def freq_module_rank_and_degree(M):
    """Exact letter frequencies of the substitution with abelianization M
    (Perron right-eigenvector, normalized to sum 1); return
    (rank of ZZ<1, alpha_a, alpha_b>, deg of min poly of alpha_a, alpha_a)."""
    t = sp.trace(M)
    assert t >= 3, "not hyperbolic"
    lam = (t + sp.sqrt(t * t - 4)) / 2          # Perron eigenvalue
    # right eigenvector: (M - lam I) v = 0
    if M[0, 1] != 0:
        v = sp.Matrix([M[0, 1], lam - M[0, 0]])
    else:
        v = sp.Matrix([lam - M[1, 1], M[1, 0]])
    alpha = sp.radsimp(sp.cancel(v[0] / (v[0] + v[1])))   # freq of letter a
    alpha = sp.simplify(alpha)
    minpoly = sp.minimal_polynomial(alpha, x)
    deg = sp.degree(minpoly, x)
    # module ZZ<1, alpha, 1-alpha> = ZZ<1, alpha>; rank = dim_QQ span{1,alpha}
    rank = 1 if deg == 1 else 2
    return rank, deg, alpha


def sym_rep(M, n):
    """Sym^{n-1}(M): action on degree-(n-1) binary forms, basis x^{m-j} y^j."""
    m = n - 1
    xx, yy = sp.symbols('xx yy')
    a, b, c, d = M[0, 0], M[0, 1], M[1, 0], M[1, 1]
    X, Y = a * xx + c * yy, b * xx + d * yy
    S = sp.zeros(m + 1, m + 1)
    for j in range(m + 1):
        p = sp.Poly(sp.expand(X ** (m - j) * Y ** j), xx, yy)
        for i in range(m + 1):
            S[i, j] = p.coeff_monomial(xx ** (m - i) * yy ** i)
    return S


def zz_rank_of_reals(gens, basis_syms):
    """Exact ZZ-rank (= QQ-dim of span) of algebraic reals written in the
    QQ-basis {1} ∪ basis_syms."""
    rows = []
    for g in gens:
        g = sp.expand(sp.radsimp(sp.sympify(g)))
        row = []
        rest = g
        for s in basis_syms:
            coef = rest.coeff(s)
            row.append(sp.nsimplify(coef))
            rest = sp.expand(rest - coef * s)
        row.insert(0, sp.nsimplify(rest))  # rational part
        assert all(q.is_rational for q in row), (g, row)
        rows.append(row)
    return sp.Matrix(rows).rank()


def main():
    print("=" * 78)
    print("TOMB-L258 recompute: K-M 'measurable gap-labeling-rank prediction'")
    print("=" * 78)

    # ----------------------------------------------------------------- F1
    print("\n[F1] K-K premise: gap-labeling frequency-module rank vs composition")
    print("     period k, over ALL length-k L/R words containing both letters.")
    print("     Killed claim predicts rank = k.\n")
    all_ok = True
    coincidences = []
    total_words = 0
    per_k = {}
    for k in range(2, 9):
        ranks, degs = set(), set()
        n_words = 0
        for bits in iproduct('LR', repeat=k):
            word = ''.join(bits)
            if 'L' not in word or 'R' not in word:
                continue  # parabolic powers L^k, R^k: no closed geodesic
            M = word_matrix(word)
            rank, deg, _ = freq_module_rank_and_degree(M)
            ranks.add(rank)
            degs.add(int(deg))
            n_words += 1
            if rank == k:
                coincidences.append((k, word))
        total_words += n_words
        per_k[k] = (n_words, sorted(ranks), sorted(degs))
        print(f"  k={k}: {n_words:3d} words | frequency-module ranks {sorted(ranks)}"
              f" | eigenvalue-field degrees {sorted(degs)}"
              f" | rank==k on {sum(1 for kk,_ in coincidences if kk==k)} words")
        if sorted(ranks) != [2] or sorted(degs) != [2]:
            all_ok = False
    print(f"\n  TOTAL {total_words} words, k=2..8: frequency-module rank = 2 on ALL"
          if all_ok else "\n  DEVIATION FOUND -- see above")
    n_k2 = sum(1 for kk, _ in coincidences if kk == 2)
    n_k_ge3 = sum(1 for kk, _ in coincidences if kk >= 3)
    print(f"  'rank = k' holds on {n_k2} words at k=2 (the 2=2 collision, the"
          f" 3=3-artifact shape)\n  and on {n_k_ge3} of"
          f" {total_words - n_k2} words with k>=3  -> NOT a law.")
    f1_pass = all_ok and n_k_ge3 == 0

    # spot-check the golden seed itself
    A = word_matrix('RL')
    rank_g, deg_g, alpha_g_word = freq_module_rank_and_degree(A)
    print(f"  Golden seed RL = {A.tolist()}, trace {sp.trace(A)}:"
          f" rank {rank_g}, alpha = {sp.nsimplify(alpha_g_word)}")
    print("  (K-K's own erratum recomputed: golden is rank 2, not rank 1.)")

    # ----------------------------------------------------------------- F2
    print("\n[F2] K-L premise: SL(n) tower of the golden seed A = RL = "
          f"{A.tolist()} (eigenvalues phi^2, phi^-2).")
    print("     Killed claim predicts (a rank) = n. Computed per n:\n")
    # rep sanity: Sym is a homomorphism at n=4
    n_test = 4
    hom_ok = sp.simplify(sym_rep(L, n_test) * sym_rep(R, n_test)
                         - sym_rep(L * R, n_test)) == sp.zeros(n_test, n_test)
    print(f"  [sanity] Sym^{n_test-1}(L)Sym^{n_test-1}(R) == Sym^{n_test-1}(LR): {hom_ok}")
    f2_pass = hom_ok
    cumulative_exponents = set()
    for n in range(2, 11):
        m = n - 1
        S = sym_rep(A, n)
        detS = sp.simplify(S.det())
        p = S.charpoly(x).as_expr()
        exps = [2 * (m - 2 * j) for j in range(m + 1)]  # proposed phi-exponents
        roots_ok = all(sp.expand(p.subs(x, PHI ** e)).equals(0) for e in exps)
        trace_ok = sp.expand(sp.trace(S) - sum(PHI ** e for e in exps)).equals(0)
        nonzero = [e for e in exps if e != 0]
        g = sp.igcd(*[abs(e) for e in nonzero])
        mult_rank = 1 if nonzero else 0     # subgroup of phi^ZZ =~ ZZ
        cumulative_exponents.update(exps)
        # eigenvalue-field degree: max degree of phi^e over QQ
        fdeg = max(int(sp.degree(sp.minimal_polynomial(PHI ** e, x), x))
                   for e in exps)
        ok = roots_ok and trace_ok and detS == 1 and len(set(exps)) == n
        print(f"  n={n:2d}: det={detS}, eigenvalues = phi^{{{sorted(exps, reverse=True)}}}"
              f" (all {n} verified as char-poly roots: {roots_ok};"
              f" trace matches: {trace_ok})")
        print(f"        multiplicative free rank = {mult_rank} (exponent lattice"
              f" = {g}*ZZ), eigenvalue-field degree = {fdeg}")
        if not ok or mult_rank != 1 or fdeg != 2:
            f2_pass = False
    cum_nonzero = [e for e in cumulative_exponents if e != 0]
    cum_g = sp.igcd(*[abs(e) for e in cum_nonzero])
    print(f"\n  Cumulative tower group (all n=2..10): generated by phi^{cum_g}"
          f" -> free rank 1. The rank does NOT climb with n.")

    # ----------------------------------------------------------------- F3
    print("\n[F3] The epitaph's replacement statement (S023/L16): rank responds to")
    print("     FIELD MULTIPLICITY, rank = 1 + #distinct quadratic fields.")
    print("     alpha_m = (sqrt(m^2+4)-m)/2 (Johnson-Moser rotation number).\n")

    def alpha_m(m):
        return (sp.sqrt(m * m + 4) - m) / 2

    a1, a2, a4 = alpha_m(1), alpha_m(2), alpha_m(4)
    basis = [sp.sqrt(5), sp.sqrt(2)]
    r_single = zz_rank_of_reals([1, a1], basis)
    r_distinct = zz_rank_of_reals([1, a1, a2], basis)
    r_samefield = zz_rank_of_reals([1, a1, a4], basis)
    rel = sp.simplify(-1 + 2 * a1 - a4)
    print(f"  single golden seed (m=1, QQ(sqrt5)):        rank ZZ<1,a1>    = {r_single}"
          f"  (= 1 + 1 field)")
    print(f"  golden+silver (m=1,2; QQ(sqrt5),QQ(sqrt2)): rank ZZ<1,a1,a2> = {r_distinct}"
          f"  (= 1 + 2 fields)")
    print(f"  golden m=1 + m=4 (both QQ(sqrt5), Pell):    rank ZZ<1,a1,a4> = {r_samefield}"
          f"  (= 1 + 1 field; exact relation -1+2*a1-a4 = {rel})")
    # PSLQ numeric cross-check (fixed 60 dps)
    fa1, fa2, fa4 = (mpmath.mpf(1) * mpmath.sqrt(5) - 1) / 2, mpmath.sqrt(2) - 1, \
        mpmath.sqrt(20) / 2 - 2
    rel_same = mpmath.pslq([mpmath.mpf(1), fa1, fa4], maxcoeff=10 ** 6)
    rel_dist = mpmath.pslq([mpmath.mpf(1), fa1, fa2], maxcoeff=10 ** 6)
    print(f"  PSLQ cross-check (60 dps, maxcoeff 1e6): [1,a1,a4] -> {rel_same}"
          f" (dependent); [1,a1,a2] -> {rel_dist} (independent)")
    f3_pass = (r_single == 2 and r_distinct == 3 and r_samefield == 2
               and rel == 0 and rel_same is not None and rel_dist is None)

    # ------------------------------------------------------------ verdict
    print("\n" + "=" * 78)
    print("DISCRIMINATING-FACT SYNTHESIS (K-M):")
    print("  A 'measurable gap-labeling-rank prediction' needs a rank observable")
    print("  that VARIES with composition period k or tower depth n.")
    print(f"  Computed spread of frequency-module rank over k=2..8 ({total_words} words):"
          f" {{2}} (spread 0)")
    print("  Computed spread of eigenvalue-field degree over the same words: {2}")
    print("  Computed spread of multiplicative eigenvalue rank over n=2..10: {1}")
    print("  Computed spread of eigenvalue-field degree over n=2..10: {2}")
    print("  Every candidate rank observable is CONSTANT in k and in n; rank moves")
    print("  only with #distinct quadratic fields (2 -> 3 -> 2 above).")
    print("=" * 78)
    if f1_pass and f2_pass and f3_pass:
        print("VERDICT: RECONFIRMED -- the banked kill of K-M is upheld by direct")
        print("computation: no observable rank tracks composition period or tower")
        print("depth; the correct rank statement is field multiplicity (2/3/2).")
    else:
        print("VERDICT COMPONENT FAILURE:",
              dict(F1=f1_pass, F2=f2_pass, F3=f3_pass))
        print("-> examine above; a climbing rank would mean REVIVED.")
    return 0 if (f1_pass and f2_pass and f3_pass) else 1


if __name__ == '__main__':
    sys.exit(main())
