#!/usr/bin/env python3
"""
Phase 4
Build a LaTeX table snippet summarising the external-cosmo host age–corridor kernel
for inclusion in the Phase 4 FRW toy paper.

Input:
  - stage2/external_cosmo_host/outputs/tables/stage2_external_cosmo_host_phase4_constraints_v1.csv

Output:
  - phase4/outputs/tables/phase4_external_host_kernel_constraints_v1.tex

The CSV is expected to have a single row with columns:
  kernel_name, n_theta, theta_min, theta_max,
  omega_lambda_repo_mean, omega_lambda_repo_min, omega_lambda_repo_max,
  Omega_lambda_host_mean, Omega_lambda_host_min, Omega_lambda_host_max,
  age_Gyr_repo_mean, age_Gyr_repo_min, age_Gyr_repo_max,
  age_Gyr_host_mean, age_Gyr_host_min, age_Gyr_host_max,
  mech_baseline_A0_mean, mech_baseline_A0_min, mech_baseline_A0_max
"""

from __future__ import annotations

import pandas as pd
from pathlib import Path


def main() -> None:
    # __file__ = repo_root/phase4/src/build_phase4_external_host_kernel_table_v1.py
    # parents[0] = .../phase4/src
    # parents[1] = .../phase4
    # parents[2] = .../origin-axiom  <-- we want this
    repo_root = Path(__file__).resolve().parents[2]

    in_path = (
        repo_root
        / "stage2"
        / "external_cosmo_host"
        / "outputs"
        / "tables"
        / "stage2_external_cosmo_host_phase4_constraints_v1.csv"
    )
    out_path = (
        repo_root
        / "phase4"
        / "outputs"
        / "tables"
        / "phase4_external_host_kernel_constraints_v1.tex"
    )

    print("[phase4_host_kernel_table] Repo root:", repo_root)
    print("[phase4_host_kernel_table] Input CSV:", in_path)

    if not in_path.is_file():
        raise FileNotFoundError(
            f"[phase4_host_kernel_table] Constraints CSV not found: {in_path}"
        )

    df = pd.read_csv(in_path)
    if len(df) != 1:
        raise RuntimeError(
            f"[phase4_host_kernel_table] Expected exactly 1 row in constraints CSV, "
            f"found {len(df)}."
        )

    row = df.iloc[0]

    # Extract and round for presentation
    n_theta = int(row["n_theta"])

    theta_min = float(row["theta_min"])
    theta_max = float(row["theta_max"])

    omega_repo_mean = float(row["omega_lambda_repo_mean"])
    omega_repo_min = float(row["omega_lambda_repo_min"])
    omega_repo_max = float(row["omega_lambda_repo_max"])

    Omega_host_mean = float(row["Omega_lambda_host_mean"])
    Omega_host_min = float(row["Omega_lambda_host_min"])
    Omega_host_max = float(row["Omega_lambda_host_max"])

    age_repo_mean = float(row["age_Gyr_repo_mean"])
    age_repo_min = float(row["age_Gyr_repo_min"])
    age_repo_max = float(row["age_Gyr_repo_max"])

    age_host_mean = float(row["age_Gyr_host_mean"])
    age_host_min = float(row["age_Gyr_host_min"])
    age_host_max = float(row["age_Gyr_host_max"])

    mech_mean = float(row["mech_baseline_A0_mean"])
    mech_min = float(row["mech_baseline_A0_min"])
    mech_max = float(row["mech_baseline_A0_max"])

    # Simple formatted strings (LaTeX-safe numbers)
    def fnum(x: float, ndigits: int = 3) -> str:
        return f"{x:.{ndigits}f}"

    theta_range = fnum(theta_min, 3) + "\\,–\\," + fnum(theta_max, 3)
    omega_repo_range = fnum(omega_repo_min, 3) + "\\,–\\," + fnum(omega_repo_max, 3)
    omega_host_range = fnum(Omega_host_min, 3) + "\\,–\\," + fnum(Omega_host_max, 3)

    age_repo_range = fnum(age_repo_min, 3) + "\\,–\\," + fnum(age_repo_max, 3)
    age_host_range = fnum(age_host_min, 3) + "\\,–\\," + fnum(age_host_max, 3)

    mech_range = fnum(mech_min, 5) + "\\,–\\," + fnum(mech_max, 5)

    lines: list[str] = []
    lines.append("% Auto-generated by phase4/src/build_phase4_external_host_kernel_table_v1.py")
    lines.append("% Do not edit by hand; rerun the script instead.")
    lines.append("\\begin{table}[t]")
    lines.append("  \\centering")
    lines.append("  \\caption{External-cosmo host age--corridor kernel used as a")
    lines.append("   Phase~4 alignment check. The kernel is the set of grid points")
    lines.append("   where the Phase~4 FRW toy is FRW-viable, lies inside its")
    lines.append("   internal corridor, and an external flat-$\\Lambda$CDM host")
    lines.append("   assigns a Universe-like age.}")
    lines.append("  \\label{tab:external_host_kernel}")
    lines.append("  \\begin{tabular}{lcc}")
    lines.append("    \\hline")
    lines.append("    Quantity & Value & Notes\\\\")
    lines.append("    \\hline")
    lines.append(
        f"    Kernel size $n_\\theta$ & {n_theta} & "
        "points on Stage~2 joint grid\\\\"
    )
    lines.append(
        f"    $\\theta$ range & ${theta_range}$ & "
        "kernel span in $\\theta$ space\\\\"
    )
    lines.append(
        f"    Toy $\\Omega_\\Lambda$ range & "
        f"${omega_repo_range}$ & from Phase~4 toy grid\\\\"
    )
    lines.append(
        f"    Host $\\Omega_\\Lambda$ range & "
        f"${omega_host_range}$ & external flat-$\\Lambda$CDM host\\\\"
    )
    lines.append(
        f"    Toy age range & "
        f"${age_repo_range}~\\mathrm{{Gyr}}$ & "
        "Phase~4 FRW toy background\\\\"
    )
    lines.append(
        f"    Host age range & "
        f"${age_host_range}~\\mathrm{{Gyr}}$ & "
        "external host background\\\\"
    )
    lines.append(
        f"    Mechanism band & "
        f"${mech_range}$ & \\texttt{{mech\\_baseline\\_A0}} on kernel\\\\"
    )
    lines.append("    \\hline")
    lines.append("  \\end{tabular}")
    lines.append("\\end{table}")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))

    print("[phase4_host_kernel_table] Wrote LaTeX table to:", out_path)


if __name__ == "__main__":
    main()
