r"""P3 — THE LINE-OPERATOR SPECTRUM OF [SU(3)xSU(2)xU(1)]/Z6.

WHY THIS ARC EXISTS
-------------------
The prediction register carries P3 as the framework's sharpest distinguishing
claim, and grades it "TESTABLE, not yet tested", with the falsifier stated as

    "a line-operator spectrum inconsistent with the Z6 quotient."

That is not yet a prediction. It names a KIND of evidence without naming a
single object whose observation would kill the claim. B862's own wording --
"falsifiable in principle via line-operator spectra" -- is honest about the
gap: IN PRINCIPLE is where the claim stopped.

This arc closes that gap by enumerating the spectrum. Afterwards P3 reads as a
finite list of objects that must not exist.

THE STRUCTURE, and it is elementary once set up
-----------------------------------------------
For a gauge group G = Gtilde/Gamma with Gamma central, line operators split:

  ELECTRIC (Wilson) : labelled by reps of Gtilde that are TRIVIAL on Gamma.
                      Quotienting REMOVES lines.
  MAGNETIC ('t Hooft): labelled by pi_1(G) = Gamma.
                      Quotienting ADDS lines.

So the quotient trades electric lines for magnetic ones, and the two sides are
locked together by Dirac quantisation. That lock is the content: a global form
is not a choice of "which lines to keep" but a single consistent lattice.

B862 derives Gamma = Z6, generated by

    z = ( w.I3 , -I2 , e^{i pi/3} ),        w = e^{2 pi i/3}

An irrep with colour triality t, weak duality d, hypercharge Y picks up the
phase exp(2 pi i [t/3 + d/2 + Y]) under z, so the ELECTRIC condition is

    e(t,d,Y) := t/3 + d/2 + Y  ==  0   (mod 1)                            (*)

and the MAGNETIC charges are the six co-weights dual to z's powers, class n
carrying (colour, weak, hypercharge) flux = (n/3 mod 1, n/2 mod 1, n/6).

WHAT DISTINGUISHES THE FOUR GLOBAL FORMS -- the point of the whole exercise
--------------------------------------------------------------------------
Tong (1705.01853) observes that the SM's own PARTICLE content leaves
Gamma in {1, Z2, Z3, Z6} ambiguous. This arc reproduces that ambiguity and
then locates exactly where it breaks: the observed matter satisfies the
STRONGEST condition (*), hence all the weaker ones, so particles cannot decide.
The LINES can, and the sharpest signature is magnetic:

    Gamma = 1  : no monopole carries colour or weak flux
    Gamma = Z2 : monopoles carry weak flux, NEVER colour flux
    Gamma = Z3 : monopoles carry colour flux, NEVER weak flux
    Gamma = Z6 : a monopole carries BOTH -- and it is the MINIMAL one

That is a discriminating list, and it is what P3 should have said.

Gate 5-Q. Structure only. Every quantity below is a representation label or a
lattice class; nothing is compared to a measured value, and no coupling,
mass, or scale appears.
"""
from fractions import Fraction as F

# --------------------------------------------------------------- the SM matter
# (name, colour triality t, weak duality d, hypercharge Y), Q = T3 + Y
SM = [
    ('Q    (3,2)',    1, 1, F(1, 6)),
    ('u^c  (3bar,1)', 2, 0, F(-2, 3)),
    ('d^c  (3bar,1)', 2, 0, F(1, 3)),
    ('L    (1,2)',    0, 1, F(-1, 2)),
    ('e^c  (1,1)',    0, 0, F(1)),
    ('nu^c (1,1)',    0, 0, F(0)),
    ('H    (1,2)',    0, 1, F(1, 2)),
]

# candidate WILSON LINES -- probe charges, not dynamical fields. A line may sit
# in any rep of the covering group; the quotient is what forbids some of them.
PROBES = [
    ('bare colour triplet     (3,1)_0',     1, 0, F(0)),
    ('bare weak doublet       (1,2)_0',     0, 1, F(0)),
    ('bare hypercharge unit   (1,1)_{1/6}', 0, 0, F(1, 6)),
    ('quark-like              (3,2)_{1/6}', 1, 1, F(1, 6)),
    ('colour triplet          (3,1)_{1/3}', 1, 0, F(1, 3)),
    ('weak doublet            (1,2)_{1/2}', 0, 1, F(1, 2)),
    ('adjoint / gluon         (8,1)_0',     0, 0, F(0)),
]

# the four global forms the SM's data cannot distinguish (Tong 1705.01853).
# Each is <z^k> inside the Z6; the condition is that z^k acts trivially.
FORMS = {
    'Gamma = 1   (no quotient)': 1,   # trivial subgroup
    'Gamma = Z2  (= <z^3>)':     2,
    'Gamma = Z3  (= <z^2>)':     3,
    'Gamma = Z6  (= <z>)  DERIVED, B862': 6,
}


def e_charge(t, d, Y):
    """The Z6 phase exponent of an irrep: t/3 + d/2 + Y."""
    return F(t, 3) + F(d, 2) + Y


def descends(t, d, Y, order):
    """Does the irrep descend to Gtilde/<z^(6/order)>?

    z^(6/order) acts by exp(2 pi i * (6/order) * e), so descent needs
    (6/order)*e to be an integer.
    """
    return (F(6, order) * e_charge(t, d, Y)).denominator == 1


def magnetic_classes(order):
    """Magnetic ('t Hooft) classes of Gtilde/Gamma, as (colour, weak, hyper) flux.

    pi_1(Gtilde/Gamma) = Gamma, so there are `order` classes. Class j is the
    co-weight dual to z^(j*6/order); its components are read off z itself.
    """
    step = 6 // order
    out = []
    for j in range(order):
        n = j * step
        out.append((n, F(n, 3) % 1, F(n, 2) % 1, F(n, 6)))
    return out


# ---------------------------------------------------------------- the sections
def section_electric():
    print('\n' + '=' * 74)
    print('  1. THE ELECTRIC SIDE — why PARTICLES cannot fix the global form')
    print('=' * 74)
    print('\n  Every observed multiplet must satisfy (*) for the DERIVED form.')
    print(f'\n  {"multiplet":16} {"t":>2} {"d":>2} {"Y":>6} {"e = t/3+d/2+Y":>15}   descends to Z6?')
    for n, t, d, Y in SM:
        v = e_charge(t, d, Y)
        ok = descends(t, d, Y, 6)
        assert ok, f'{n} must descend to the Z6 quotient'
        print(f'  {n:16} {t:>2} {d:>2} {str(Y):>6} {str(v):>15}   YES')

    print('\n  AND THAT IS EXACTLY THE PROBLEM. e is an INTEGER for every')
    print('  multiplet, so it is 0 mod 1, mod 1/2, and mod 1/3 alike:\n')
    print(f'  {"global form":38}  all SM matter descends?')
    for name, order in FORMS.items():
        allok = all(descends(t, d, Y, order) for _, t, d, Y in SM)
        assert allok, 'SM matter descends to every one of the four forms'
        print(f'  {name:38}  YES')
    print('\n  ==> the observed PARTICLE spectrum is consistent with ALL FOUR.')
    print('      This reproduces Tong 1705.01853 from the descent condition')
    print('      alone, and it is why P3 needs LINES, not particles.')


def section_wilson():
    print('\n' + '=' * 74)
    print('  2. WILSON LINES — the quotient REMOVES electric lines')
    print('=' * 74)
    print('\n  A line operator may carry ANY rep of the cover; only the quotient')
    print('  forbids. So the forms differ here even though the matter does not.\n')
    print(f'  {"probe line":36} {"e":>6}   {"G=1":>5} {"G=Z2":>5} {"G=Z3":>5} {"G=Z6":>5}')
    forbidden = {name: [] for name in FORMS}
    for nm, t, d, Y in PROBES:
        v = e_charge(t, d, Y)
        row = []
        for name, order in FORMS.items():
            ok = descends(t, d, Y, order)
            row.append('ok' if ok else 'NO')
            if not ok:
                forbidden[name].append(nm)
        print(f'  {nm:36} {str(v):>6}   ' + ' '.join(f'{r:>5}' for r in row))

    print('\n  FORBIDDEN WILSON LINES, by global form:')
    for name, order in FORMS.items():
        f = forbidden[name]
        print(f'    {name:38} {len(f)} forbidden')
        for x in f:
            print(f'        - {x}')
    # the Z6 form must forbid strictly the most
    counts = [len(forbidden[n]) for n in FORMS]
    assert counts == sorted(counts), 'stronger quotient must forbid at least as much'
    assert counts[-1] > counts[0], 'Z6 must forbid strictly more than the cover'


def section_magnetic():
    print('\n' + '=' * 74)
    print('  3. \'t HOOFT LINES — the quotient ADDS magnetic lines. THE TEST.')
    print('=' * 74)
    print('\n  pi_1(G) = Gamma, so there are |Gamma| magnetic classes. Class n')
    print('  carries flux (colour, weak, hypercharge) read off z^n.\n')

    for name, order in FORMS.items():
        cls = magnetic_classes(order)
        has_colour = any(c for _, c, _, _ in cls)
        has_weak = any(w for _, _, w, _ in cls)
        has_both = any(c and w for _, c, w, _ in cls)
        print(f'  {name}   —   {order} magnetic class{"es" if order > 1 else ""}')
        print(f'    {"n":>3} {"colour":>8} {"weak":>6} {"hyper":>7}')
        for n, c, w, y in cls:
            tag = ''
            if c and w:
                tag = '   <== BOTH colour AND weak flux'
            elif c:
                tag = '   colour only'
            elif w:
                tag = '   weak only'
            print(f'    {n:>3} {str(c):>8} {str(w):>6} {str(y):>7}{tag}')
        print(f'    any monopole with colour flux? {"YES" if has_colour else "no":<4}'
              f'  with weak flux? {"YES" if has_weak else "no":<4}'
              f'  with BOTH? {"YES" if has_both else "no"}')
        print()

    # the discriminator, asserted rather than asserted-in-prose
    def sig(order):
        cls = magnetic_classes(order)
        return (any(c for _, c, _, _ in cls),
                any(w for _, _, w, _ in cls),
                any(c and w for _, c, w, _ in cls))
    sigs = {n: sig(o) for n, o in FORMS.items()}
    assert len(set(sigs.values())) == 4, 'the four forms must have four distinct signatures'
    print('  ALL FOUR SIGNATURES ARE DISTINCT. The magnetic spectrum SEPARATES')
    print('  the global forms that the particle spectrum cannot. That is P3.')


def section_minimality():
    print('\n' + '=' * 74)
    print('  4. THE MINIMAL MONOPOLE, and its Dirac signature')
    print('=' * 74)
    print('\n  The n=1 monopole pairs with an electric state of charge (t,d,Y) by')
    print('  exp(2 pi i * e(t,d,Y)). The pairing INTEGER is e itself:\n')
    print(f'  {"multiplet":16} {"Dirac pairing with n=1":>24}')
    ones = []
    for nm, t, d, Y in SM:
        v = e_charge(t, d, Y)
        assert v.denominator == 1
        if v != 0:
            ones.append(nm)
        print(f'  {nm:16} {str(v):>24}')
    # MINIMALITY, stated as the gcd rather than by appeal to "saturation".
    # If every pairing were divisible by k > 1, a magnetic charge 1/k times
    # this one would still be local against all matter, and n=1 would not be
    # the smallest admissible monopole. The gcd is what decides it.
    from math import gcd
    g = 0
    for _, t, d, Y in SM:
        g = gcd(g, int(e_charge(t, d, Y)))
    print(f'\n  gcd of the pairings over the whole generation = {g}')
    assert g == 1, 'a gcd > 1 would admit a smaller monopole'
    print('  Because the gcd is 1, NO smaller magnetic charge stays local')
    print('  against all observed matter. The n=1 class is minimal in the')
    print('  strict sense, not merely first in the listing.')
    print(f'  (it pairs nontrivially with {len(ones)} of {len(SM)} multiplets, d^c among them)')
    assert 'd^c  (3bar,1)' in ones

    print('\n  MUTUAL LOCALITY — every allowed electric line against every')
    print('  magnetic class, all six:')
    bad = 0
    for nm, t, d, Y in SM:
        for n, _, _, _ in magnetic_classes(6):
            if (n * e_charge(t, d, Y)) % 1 != 0:
                bad += 1
    assert bad == 0
    print(f'    {len(SM)} x 6 = {len(SM)*6} pairings, all integral. CONSISTENT SPECTRUM.')

    print('\n  And the converse bites. A Wilson line the quotient forbids is')
    print('  NON-LOCAL with respect to the minimal monopole:')
    for nm, t, d, Y in PROBES:
        if not descends(t, d, Y, 6):
            v = e_charge(t, d, Y)
            print(f'    {nm:36} e = {str(v):>4}  pairing with n=1 = {str(v % 1):>4}  NOT integral')
    print("""
  P2 AND P3 ARE TWO FACES OF ONE LATTICE — but NOT the same claim, and the
  distinction matters for how the register counts evidence.

    P2 (charge quantisation of observed matter) holds in ALL FOUR global
       forms, as section 1 showed. It is CONFIRMED and WEAK.
    P3 (the form is Z6 exactly) is fixed only by the LINE spectrum. It is
       UNTESTED and STRONG.

  Therefore: P2's confirmation lends NO evidential support to P3. Observing
  quantised charges is consistent with Gamma = 1. The register lists both
  among its eight and calls two "distinguishing"; that is right, but the two
  must not be read as mutually reinforcing. They share a lattice, not a test.""")


def section_falsifiers():
    print('\n' + '=' * 74)
    print('  5. THE FALSIFIER LIST — objects that must not exist')
    print('=' * 74)
    print("""
  P3 previously read: "a line-operator spectrum inconsistent with the Z6
  quotient." Replace it with these. Any ONE of them kills the derived form.

  MAGNETIC (the discriminating ones)
    F1. a monopole of minimal hypercharge magnetic charge carrying NO colour
        flux           -> excludes Z6 and Z3; consistent with 1 or Z2
    F2. a monopole of minimal hypercharge magnetic charge carrying NO weak
        flux           -> excludes Z6 and Z2; consistent with 1 or Z3
    F3. ANY monopole whose (colour, weak, hypercharge) flux is not one of the
        six rows of the n-table -- e.g. colour flux 1/3 paired with hypercharge
        1/2 (the table forces 1/3 <-> 1/6 and 1/2 <-> 1/2)
    F4. a pure-hypercharge monopole at hypercharge magnetic charge BELOW 1
        (the Z6 form permits one only at n = 0 mod 6)

  ELECTRIC
    F5. a genuine bare colour-triplet Wilson line (3,1)_0 -- an unscreened
        probe of triality 1 and zero hypercharge. Forbidden by Z6 and Z3.
    F6. a bare weak-doublet line (1,2)_0. Forbidden by Z6 and Z2.
    F7. an isolated state of hypercharge 1/6 with no colour -- forbidden by Z6
        (this is the P2 statement, restated as a line)

  WHAT WOULD CONFIRM RATHER THAN KILL
    C1. observation that the minimal monopole carries colour AND weak flux
        together. NO other global form permits this. It is the unique positive
        signature of Z6, and it is the thing to look for.

  HONEST SCOPE, stated because the register must not overstate again:
    * no monopole has been observed, so none of F1-F4 is currently TESTED.
      P3 moves from "TESTABLE in principle" to "TESTABLE, with a stated list"
      -- it does NOT move to CONFIRMED, and no status column here says so.
    * F5-F7 concern line operators, which are probes rather than particles;
      "observing" them means a lattice/theoretical determination of the
      spectrum, not a detector event.
    * the derivation of Gamma = Z6 itself rests on B862, which this arc takes
      as given and does not re-prove.
""")


def main():
    print('P3 — THE LINE-OPERATOR SPECTRUM OF [SU(3)xSU(2)xU(1)]/Z6')
    print('     turning "falsifiable in principle" into a list of objects')
    section_electric()
    section_wilson()
    section_magnetic()
    section_minimality()
    section_falsifiers()
    print('=' * 74)
    print('  ALL ASSERTIONS PASSED.')
    print('=' * 74)


if __name__ == '__main__':
    main()
