#!/usr/bin/env python3
"""THE SYMMETRIES OF THE CLOSING ON ITS STANDARD-MODEL LINES (L206), and how the object's mirror acts on the
nine-fold closing.

(a) The eight isometries of the object as automorphisms of its own presentation pi_1(m004) = <a, b | a w B w^-1>
    (w = b A B a), found by a word search (a -> u, b -> v, the relator preserved in the geometric holonomy -- Riley's
    representation a = [[1,1],[0,1]], b = [[1,0],[e^{i pi/3},1]]), each identified with its isometry by the conjugator
    N (rho o phi = N rho N^-1, or with the complex-conjugate holonomy for the orientation-reversing ones), brought
    back to the cusp at infinity and read as an affine map of the cusp torus; the horoball dictionary of the
    holonomy decides membership in Gamma.  Cross-check: the same eight affine maps as B1277's addendum.
(b) Their lifts to the branched covers Y_n (n = 3, 6, 9), as automorphisms of H_1(Y_n) by Reidemeister-Schreier
    rewriting of the images of the Schreier generators, together with the deck generator t = Ad(a); the induced action
    on the character group (psi -> psi o phi_*), checked well-defined on every character.
(c) On Y_9: the action on the three family characters, on the two order-19 subgroups C_1, C_2 carrying the new
    classes (preserved or swapped, inverted or not), on the three-generation alphabet, and on the 706 464
    Standard-Model lines (B1278): the ORBITS under the group generated by the deck Z/9 and the lifts of D_4 -- the
    number of inequivalent SM vacua of the closing -- and the lines fixed or inverted by the orientation-reversing
    lifts (the CP face's data).
"""
from __future__ import annotations
import sys, math, cmath, itertools, collections, pathlib, time
from fractions import Fraction as F
import numpy as np
import sympy as sp
import mpmath as mp

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[2]
for arc in ('B1267_spectrum_law_rebuilt', 'B1268_cusped_net_chirality_bound', 'B1269_transport_computed',
            'B1273_the_three_fold_closing', 'B1274_the_tower_and_its_doubles', 'B1275_the_cubic_made_explicit',
            'B1276_the_relations_the_chain_forces', 'B1277_the_vacuum_manifold_of_the_closing',
            'B1278_the_six_fold_closing'):
    sys.path.insert(0, str(ROOT / 'frontier' / arc / 'verification'))
import spectrum_law as S
import three_fold_closing as Y3
import tower_and_doubles as TW
import six_fold_closing as SF
import cubic_explicit as C
import relations as R
import vacuum_manifold as VM

# ------------------------------------------------------------------------------------------------ the geometric holonomy
U = cmath.exp(1j * math.pi / 3)
RHO = {1: np.array([[1, 1], [0, 1]], dtype=complex), 2: np.array([[1, 0], [U, 1]], dtype=complex)}
RHO[-1], RHO[-2] = np.linalg.inv(RHO[1]), np.linalg.inv(RHO[2])


def ev(word, rho=RHO):
    out = np.eye(2, dtype=complex)
    for L in word:
        out = out @ rho[L]
    return out


def subst(word, u, v):
    """the word with a -> u, b -> v (u, v words in +-1, +-2)"""
    out = []
    for L in word:
        img = u if abs(L) == 1 else v
        out += img if L > 0 else [-x for x in reversed(img)]
    return out


def reduced_words(maxlen):
    words = [[]]
    out = []
    for length in range(1, maxlen + 1):
        nxt = []
        for w in words:
            for g in (1, -1, 2, -2):
                if w and w[-1] == -g:
                    continue
                nxt.append(w + [g])
        out += nxt
        words = nxt
    return out


# ------------------------------------------------------------------------------------------------ (a)
def part_a():
    T_MU = 1.0
    LAM = ev(S.LONG)
    t_lam = LAM[0, 1] / LAM[0, 0]
    assert abs(LAM[1, 0]) < 1e-12 and abs(t_lam.real) < 1e-9
    print(f"  Riley holonomy: a = translation by 1, longitude translation {t_lam:.6f} (|t_lam| = 2 sqrt 3: {abs(abs(t_lam) - 2 * math.sqrt(3)) < 1e-9}); relator: {np.allclose(ev(S.REL), np.eye(2))}")
    # the horoball dictionary (words to length 9): gamma(infinity) mod the lattice, sizes 1/|c|^2
    def reduce(z):
        return (z.real / T_MU) % 1.0, (z.imag / t_lam.imag) % 1.0
    dictionary = {}
    frontier = [([], np.eye(2, dtype=complex))]
    for length in range(1, 10):
        nxt = []
        for w, X in frontier:
            for g in (1, -1, 2, -2):
                if w and w[-1] == -g:
                    continue
                Y = X @ RHO[g]
                nxt.append((w + [g], Y))
                c = Y[1, 0]
                if abs(c) > 1e-9:
                    x, y = reduce(Y[0, 0] / c)
                    key = (round(x, 4) % 1.0, round(y, 4) % 1.0, round(1.0 / abs(c) ** 2, 5))
                    if key not in dictionary:
                        dictionary[key] = Y
        frontier = nxt
    sizes = sorted({k[2] for k in dictionary}, reverse=True)
    pattern = collections.defaultdict(list)
    for (x, y, s) in dictionary:
        pattern[s].append((x, y))

    def close(p, q):
        return abs((p[0] - q[0] + 0.5) % 1.0 - 0.5) < 2e-3 and abs((p[1] - q[1] + 0.5) % 1.0 - 0.5) < 2e-3

    def in_gamma(h, depth=0):
        c = h[1, 0]
        if abs(c) < 1e-9:
            t = h[0, 1] / h[0, 0]
            m1, m2 = t.real / T_MU, t.imag / t_lam.imag
            return abs(m1 - round(m1)) < 1e-6 and abs(m2 - round(m2)) < 1e-6 and abs(abs(h[0, 0]) - 1) < 1e-6 and abs(h[0, 0].imag) < 1e-6
        z = h[0, 0] / c
        x, y = reduce(z)
        size = 1.0 / abs(c) ** 2
        key = next((k for k in dictionary if abs(k[2] - size) < 1e-4 * size and close((k[0], k[1]), (x, y))), None)
        if key is None or depth > 2:
            return None
        w = dictionary[key]
        d = z - w[0, 0] / w[1, 0]
        m1, m2 = round(d.real / T_MU), round(d.imag / t_lam.imag)
        Tm = np.array([[1, m1 * T_MU + m2 * t_lam], [0, 1]], dtype=complex)
        return in_gamma(np.linalg.inv(Tm @ w) @ h, depth + 1)

    # the automorphism search
    words = reduced_words(4)
    mats = {tuple(w): ev(w) for w in words}
    trA, trB, trAB = 2.0, 2.0, np.trace(ev([1, 2]))
    found = []
    for u in words:
        Mu_ = mats[tuple(u)]
        if abs(np.trace(Mu_) - 2) > 1e-9 and abs(np.trace(Mu_) + 2) > 1e-9:
            continue                                   # a meridian's image is parabolic
        for v in words:
            Mv = mats[tuple(v)]
            if abs(np.trace(Mv) - 2) > 1e-9 and abs(np.trace(Mv) + 2) > 1e-9:
                continue
            tab = np.trace(Mu_ @ Mv)
            orient = None
            if abs(tab - trAB) < 1e-9:
                orient = +1
            elif abs(tab - np.conj(trAB)) < 1e-9:
                orient = -1
            else:
                continue
            Rimg = ev(subst(S.REL, u, v))
            if not (np.allclose(Rimg, np.eye(2), atol=1e-8) or np.allclose(Rimg, -np.eye(2), atol=1e-8)):
                continue
            found.append((u, v, orient))
    print(f"  endomorphisms a -> u, b -> v (words to length 4) preserving the relator and the character (or its conjugate): {len(found)}")
    # the conjugator N with rho o phi = N (rho or rhobar) N^-1, then brought to fix infinity: the affine map
    def conjugator(u, v, orient):
        X1, X2 = RHO[1], RHO[2]
        if orient < 0:
            X1, X2 = X1.conj(), X2.conj()
        Y1, Y2 = ev(u), ev(v)
        # solve N X = s Y N for both generators with signs s1, s2 in {+-1}: linear in the 4 entries of N
        best = None
        for s1 in (1, -1):
            for s2 in (1, -1):
                rows = []
                for X, Y, s in ((X1, Y1, s1), (X2, Y2, s2)):
                    # (N X - s Y N)_{ij} = sum_k N_{ik} X_{kj} - s sum_k Y_{ik} N_{kj}
                    for i in range(2):
                        for j in range(2):
                            row = np.zeros(4, dtype=complex)
                            for k in range(2):
                                row[2 * i + k] += X[k, j]
                                row[2 * k + j] -= s * Y[i, k]
                            rows.append(row)
                Mx = np.array(rows)
                uu, ss, vh = np.linalg.svd(Mx)
                if ss[-1] < 1e-7:
                    n = vh[-1].conj()
                    N = n.reshape(2, 2)
                    d = np.linalg.det(N)
                    if abs(d) > 1e-12:
                        N = N / cmath.sqrt(d)
                        best = N
        return best

    affine_of = []
    for (u, v, orient) in found:
        N = conjugator(u, v, orient)
        if N is None:
            affine_of.append(None); continue
        # bring N(infinity) back to infinity by a group element
        if abs(N[1, 0]) > 1e-9:
            z = N[0, 0] / N[1, 0]
            x, y = reduce(z)
            key = next((k for k in dictionary if close((k[0], k[1]), (x, y)) and abs(k[2] - 1.0 / abs(N[1, 0]) ** 2) < 1e-3), None)
            if key is None:
                affine_of.append(None); continue
            w = dictionary[key]
            d = z - w[0, 0] / w[1, 0]
            m1, m2 = round(d.real / T_MU), round(d.imag / t_lam.imag)
            Tm = np.array([[1, m1 * T_MU + m2 * t_lam], [0, 1]], dtype=complex)
            N = np.linalg.inv(Tm @ w) @ N
        assert abs(N[1, 0]) < 1e-7, N
        alpha, beta = N[0, 0] / N[1, 1], N[0, 1] / N[1, 1]
        s = 1 if abs(alpha - 1) < 1e-7 else (-1 if abs(alpha + 1) < 1e-7 else None)
        assert s is not None, alpha
        bx, by = (beta.real / T_MU) % 1.0, (beta.imag / t_lam.imag) % 1.0
        # the cusp map: holomorphic z -> s z + beta: (s_mu, s_lam) = (s, s); antiholomorphic z -> s zbar + beta: (s, -s)
        smu, slam = (s, s) if orient > 0 else (s, -s)
        affine_of.append(((smu, slam), (round(bx, 3) % 1.0, round(by, 3) % 1.0), orient))
    classes = {}
    for (u, v, orient), aff in zip(found, affine_of):
        if aff is None:
            continue
        key = (aff[0], aff[1])
        if key not in classes or len(u) + len(v) < len(classes[key][0]) + len(classes[key][1]):
            classes[key] = (u, v, orient)
    print(f"  distinct outer classes found (cusp map, translation part (b_mu, b_lam)): {len(classes)}")
    W = {1: 'a', -1: 'A', 2: 'b', -2: 'B'}
    for key in sorted(classes):
        u, v, orient = classes[key]
        print(f"     {key[0]}, b = {key[1]}: a -> {''.join(W[x] for x in u)}, b -> {''.join(W[x] for x in v)}   ({'orientation-preserving' if orient > 0 else 'orientation-REVERSING'})")
    assert len(classes) == 8, len(classes)
    return classes, t_lam


# ------------------------------------------------------------------------------------------------ (b)
def action_on_cover(u, v, n):
    """the matrix Phi (gens x gens) of the automorphism a -> u, b -> v on the abelianized Schreier generators of Y_n:
    Phi[k][j] = exponent sum of generator j in the rewritten image of generator k."""
    gens, rels = TW.presentation(n, branched=True)
    words = TW.gen_words(n)
    Phi = np.zeros((len(gens), len(gens)), dtype=int)
    for k, g in enumerate(gens):
        img = subst(words[g], u, v)
        rw, kk = TW.rewrite(img, n, 0)
        assert kk == 0, (g, kk)
        for L in rw:
            Phi[k][abs(L) - 1] += (1 if L > 0 else -1)
    return Phi


def deck_action(n):
    gens, rels = TW.presentation(n, branched=True)
    words = TW.gen_words(n)
    Phi = np.zeros((len(gens), len(gens)), dtype=int)
    for k, g in enumerate(gens):
        img = [1] + words[g] + [-1]
        rw, kk = TW.rewrite(img, n, 0)
        assert kk == 0
        for L in rw:
            Phi[k][abs(L) - 1] += (1 if L > 0 else -1)
    return Phi


# ------------------------------------------------------------------------------------------------ main
def main():
    t0 = time.time()
    print("=== (a) the eight isometries as automorphisms of the presentation ===")
    classes, t_lam = part_a()
    print("\n=== (b) the lifts to Y_n: actions on the character groups ===")
    wts, rep = C.load()
    lab, hy, wts2 = R.sm_labels()
    sub, Yv, rts, Mf, ip, a1, a2 = VM.descent_data()
    sm_roots = sorted(set(a2) | {a1, tuple(-x for x in a1)})
    results = {}
    for n in (3, 6, 9):
        gens, rels = TW.presentation(n, branched=True)
        Rm = SF.relation_matrix(gens, rels)
        D, Uu, V = SF.smith_with_transforms(Rm)
        inv = [int(D[j, j]) for j in range(min(D.shape))]
        tors = sorted(d for d in inv if d not in (0, 1))
        m = 1
        for d in tors:
            m = m * d // math.gcd(m, d)
        chars, coords, moduli = SF.characters(D, V, m, with_coords=True)
        cidx = {a: i for i, a in enumerate(chars)}
        N = len(chars)
        # the actions
        acts = {}
        for key, (u, v, orient) in classes.items():
            Phi = action_on_cover(u, v, n)
            perm = np.zeros(N, dtype=int)
            for i, a in enumerate(chars):
                a2_ = tuple(int(x) % m for x in (Phi @ np.array(a)))
                assert a2_ in cidx, "the action is not well defined on the characters"
                perm[i] = cidx[a2_]
            acts[key] = perm
        Phi_t = deck_action(n)
        perm_t = np.zeros(N, dtype=int)
        for i, a in enumerate(chars):
            a2_ = tuple(int(x) % m for x in (Phi_t @ np.array(a)))
            perm_t[i] = cidx[a2_]
        acts['t'] = perm_t
        # the group generated (as permutations of the characters)
        group = {tuple(range(N))}
        frontier = [np.arange(N)]
        gens_p = list(acts.values())
        while frontier:
            nxt = []
            for p in frontier:
                for q in gens_p:
                    r_ = q[p]
                    tr = tuple(r_)
                    if tr not in group:
                        group.add(tr); nxt.append(r_)
            frontier = nxt
        print(f"  Y_{n}: H_1 = {' + '.join(f'Z/{d}' for d in tors)}; the actions of the eight lifts and of the deck t on the {N} characters are well defined; the group they generate has order {len(group)}")
        # the family characters and the h^1 = 1 set (numeric sweep, certified exactly in B1278)
        mp.mp.dps = 30
        h1 = {a: SF.h1_numeric(gens, rels, a, m)[0] for a in chars}
        chis = SF.family_characters(n, gens, m)
        pos = [a for a in chars if h1[a] > 0]
        chi_idx = [cidx[c] for c in chis]
        for key, perm in acts.items():
            img = [chars[perm[i]] for i in chi_idx]
            fam = all(x in chis for x in img)
            print(f"     {key}: family characters -> {'permuted among themselves' if fam else 'NOT preserved'} ({[chis.index(x) + 1 if x in chis else None for x in img]}); h^1 = 1 set preserved: {all(h1[chars[perm[cidx[a]]]] == 1 for a in pos)}")
        results[n] = dict(chars=chars, coords=coords, moduli=moduli, cidx=cidx, acts=acts, group=group, h1=h1, chis=chis, pos=pos, gens=gens, m=m)
    print(f"  ({time.time() - t0:.0f} s)")
    # ------------------------------------------------------------------------------------------ (c) Y_9
    print("\n=== (c) Y_9: the mirror on the new classes, and the orbits of the Standard-Model lines ===")
    d9 = results[9]
    chars, coords, moduli, cidx, acts, group, h1, chis, pos, gens, m = (d9[k] for k in ('chars', 'coords', 'moduli', 'cidx', 'acts', 'group', 'h1', 'chis', 'pos', 'gens', 'm'))
    N = len(chars)
    add = lambda x, y: tuple((p + q) % m for p, q in zip(x, y))
    neg = lambda x: tuple((-p) % m for p in x)
    order_of = lambda a: max([m // math.gcd(int(x), m) for x in a] + [1])
    # the two order-19 subgroups: the order-19 characters with h^1 = 1 and their generated subgroups
    o19 = [a for a in pos if order_of(a) == 19]
    subgroups = []
    for a in o19:
        sg = {tuple([0] * len(gens))}
        x = a
        for k in range(19):
            sg.add(x); x = add(x, a)
        sg = frozenset(sg)
        if sg not in subgroups:
            subgroups.append(sg)
    assert len(subgroups) == 2 and all(len(s) == 19 for s in subgroups)
    C1, C2 = subgroups
    print(f"  the 36 order-19 classes generate two cyclic subgroups C_1, C_2 of order 19 (as B1278 read them): {len(subgroups) == 2}")
    powers = {}
    for key, perm in acts.items():
        imgC1 = frozenset(chars[perm[cidx[a]]] for a in C1)
        which = 'C_1' if imgC1 == C1 else ('C_2' if imgC1 == C2 else 'neither')
        kp = []
        for Cc in (C1, C2):
            a = next(iter(a for a in Cc if any(a)))
            img = chars[perm[cidx[a]]]
            kp.append(next((k for k in range(19) if img == tuple((k * x) % m for x in a)), None))
        powers[key] = (which, tuple(kp))
        desc = {1: 'identity', 18: 'INVERSION'}
        print(f"     {key}: C_1 -> {which}; the generators of (C_1, C_2) map to their powers {tuple(kp)}" + (f" ({desc.get(kp[0], 'a Galois twist')}, {desc.get(kp[1], 'a Galois twist')})" if which == 'C_1' else " (the two eigenlines are SWAPPED)"))
    # the deck generator's eigenvalues on the two eigenlines are the roots of the golden polynomial modulo 19
    kt = powers['t'][1]
    roots19 = sorted(x for x in range(19) if (x * x - 3 * x + 1) % 19 == 0)
    print(f"  the deck t acts on (C_1, C_2) by the powers {kt}; the roots of t^2 - 3t + 1 modulo 19 are {roots19}: {sorted(kt) == roots19}  (C_1, C_2 are the golden eigenlines phi^(+-2) mod 19)")
    assert sorted(kt) == roots19
    # the SM lines (B1278's construction, vectorized): K3 triples -> nu -> the component characters
    G = np.zeros(N, dtype=np.int64)
    for i, a in enumerate(chars):
        G[i] = sum(h1[chars[cidx[add(c, a)]]] for c in chis)
    K3 = [i for i in range(N) if G[i] >= 3]
    Rm_sm = sp.Matrix([list(a) for a in sm_roots])
    D2, U2, V2 = SF.smith_with_transforms(Rm_sm)
    dprime = [int(D2[j, j]) for j in range(min(D2.shape))]
    rank = sum(1 for d in dprime if d != 0)
    free = list(range(rank, 6))
    VT = V2.T
    coeff = {i: [int(x) for x in (VT * sp.Matrix(list(wts[i])))] for i in range(27)}
    comp = {l: next(i for i in range(27) if lab[i] == l) for l in ('Q', 'u^c', 'd^c', 'L', 'e^c', 'H_u', 'H_d', 'D', 'Dbar', 'S', 'nu^c')}
    Cm = sp.Matrix([[coeff[comp[l]][j] for j in free] for l in ('Q', 'u^c', 'L')])
    det = int(Cm.det()); adj = Cm.adjugate()
    assert abs(det) == 1
    # characters as coordinate vectors (Z/76)^2; tables for addition/scaling through exponent tuples would be slow: use coords
    cvec = np.array(coords, dtype=np.int64)
    mods = np.array(moduli, dtype=np.int64)
    ckey = lambda arr: arr[:, 0] * 1 + arr[:, 1] * moduli[0]
    key2idx = np.full(int(np.prod(moduli)), -1, dtype=np.int64)
    for i, c in enumerate(coords):
        key2idx[c[0] + c[1] * moduli[0]] = i
    Kc = cvec[K3]
    K = len(K3)
    iQ, iu, iL = np.meshgrid(np.arange(K), np.arange(K), np.arange(K), indexing='ij')
    iQ, iu, iL = iQ.ravel(), iu.ravel(), iL.ravel()
    psi = [Kc[iQ], Kc[iu], Kc[iL]]
    nu = []
    for j in range(3):
        acc = np.zeros_like(psi[0])
        for k in range(3):
            acc = acc + int(adj[j, k]) * psi[k]
        nu.append((acc * det) % mods)               # det = +-1
    def psi_of(coef):
        acc = np.zeros_like(psi[0])
        for j, f in enumerate(free):
            if coef[f]:
                acc = acc + coef[f] * nu[j]
        return acc % mods
    comp_chars = {l: psi_of(coeff[comp[l]]) for l in comp}
    gcount = lambda arr: G[key2idx[ckey(arr)]]
    three = np.ones(len(iQ), dtype=bool)
    for l in ('Q', 'u^c', 'd^c', 'L', 'e^c'):
        three &= gcount(comp_chars[l]) >= 3
    vac = three.copy()
    for l in ('S', 'nu^c', 'H_u', 'H_d'):
        vac &= gcount(comp_chars[l]) >= 1
    broken = ~(np.all(comp_chars['Q'] == comp_chars['u^c'], axis=1) & np.all(comp_chars['u^c'] == comp_chars['e^c'], axis=1))
    sm = np.where(vac & broken)[0]
    print(f"  Standard-Model lines (B1278): {len(sm)} (three generations of Q, u^c, d^c, L, e^c; <N>, <nu^c>, H_u, H_d available; SU(5) broken)")
    assert len(sm) == 706464
    # the symmetry group acting on the lines: each element acts on the three characters (psi_Q, psi_u, psi_L) by the same permutation
    triples = np.stack([key2idx[ckey(comp_chars['Q'][sm])], key2idx[ckey(comp_chars['u^c'][sm])], key2idx[ckey(comp_chars['L'][sm])]], axis=1)
    enc = lambda tr: tr[:, 0] + N * tr[:, 1] + N * N * tr[:, 2]
    best = enc(triples)
    elems = [np.array(p) for p in group]
    for p in elems:
        img = p[triples]
        best = np.minimum(best, enc(img))
    orbits = len(set(best.tolist()))
    print(f"  the group generated by the deck Z/9 and the eight lifts has order {len(elems)}; the {len(sm)} SM lines fall into {orbits} orbits (inequivalent SM vacua of the closing)")
    # the CP face: lines inverted by the orientation-reversing lifts (psi o phi_* = psi^-1 on the three characters)
    inv_idx = np.array([cidx[neg(a)] for a in chars])
    for key, perm in acts.items():
        if key == 't':
            continue
        orient = classes[key][2]
        # all nine lifts phi t^j
        counts = []
        p = perm.copy()
        for j in range(9):
            q = p if j == 0 else acts['t'][q] if False else p
            fixed = np.all(p[triples] == triples, axis=1).sum()
            inverted = np.all(p[triples] == inv_idx[triples], axis=1).sum()
            counts.append((int(fixed), int(inverted)))
            p = acts['t'][p]
        print(f"     {key} ({'orientation-preserving' if orient > 0 else 'orientation-REVERSING'}): over its nine lifts (fixed lines, inverted lines) = {counts}")
    return dict(orbits=orbits, group=len(elems), n_sm=len(sm), powers=powers, roots19=roots19)


if __name__ == "__main__":
    out = main()
    ok = out['n_sm'] == 706464 and out['orbits'] > 0
    print("\nSELFTEST:", "PASS" if ok else "FAIL")
    sys.exit(0 if ok else 1)
