#!/usr/bin/env python3
"""
B710 (Path 1) ANALYTIC-T1 — thimble/saddle SKELETON comparison:
  figure-eight (4_1) state integral   vs   Turok FRW mini-superspace lapse integral.

Structural comparison ONLY. No SM value. Gate 5 stands.

Part 1: fig-8 state-integral saddles (geometric shape z=e^{i pi/3}, trace field Q(sqrt-3)).
        Reproduce Vol(4_1) INDEPENDENTLY via the Bloch-Wigner dilogarithm.
        CS(4_1 geometric)=0 (amphichiral) => the two non-abelian saddle actions are REAL.
        Note the Garoufalidis-Gu-Marino "peacock" Borel-singularity lattice as extra structure.
Part 2: FRW de Sitter lapse action S(N)=A N^3 + B N + C/N (Feldbrugge-Lehners-Turok,
        PRD 95 103508, 2017). Reconstruct A,B,C from the minisuperspace reduction.
        dS/dN=0 => 3A N^4 + B N^2 - C = 0 (biquadratic quartic) => 4 saddles in 2
        conjugate pairs, actions generically COMPLEX. Confirm across >=2 coeff sets.
Part 3: qualitative Stokes/thimble connectivity comparison.
"""
import mpmath as mp

mp.mp.dps = 40
LINE = "=" * 78


def li2(z):
    return mp.polylog(2, z)


def bloch_wigner(z):
    # D(z) = Im Li_2(z) + arg(1-z)*ln|z|   (single-valued dilogarithm)
    return mp.im(li2(z)) + mp.arg(1 - z) * mp.log(abs(z))


# ---------------------------------------------------------------------------
print(LINE)
print("PART 1  Figure-eight (4_1) state-integral saddles")
print(LINE)

z = mp.e ** (1j * mp.pi / 3)                       # geometric shape parameter
print(f"geometric shape z = e^(i pi/3) = {mp.nstr(z, 20)}")
print(f"   Re z = 1/2  ?  {mp.nstr(mp.re(z),20)}   (exact 0.5)")
print(f"   Im z = sqrt(3)/2 ? {mp.nstr(mp.im(z),20)}  vs {mp.nstr(mp.sqrt(3)/2,20)}")
print("   => z in Q(sqrt(-3))  (z = (1 + i*sqrt(3))/2, a primitive 6th root of unity)")

# figure-eight = two regular ideal tetrahedra, each shape z; both shapes equal.
D = bloch_wigner(z)
Vol = 2 * D                                        # Vol(4_1) = D(z_1)+D(z_2) = 2 D(z)
print()
print(f"Bloch-Wigner D(z)         = {mp.nstr(D, 25)}")
print(f"   (=Clausen Cl_2(pi/3), the max of the Bloch-Wigner function)")
print(f"Vol(4_1) = 2*Im Li_2(z)   = {mp.nstr(Vol, 25)}")
print(f"reference value           = 2.029883212819307250042405108549")
print(f"|difference|              = {mp.nstr(abs(Vol - mp.mpf('2.029883212819307250042405108549')), 5)}")

# cross-check via Lobachevsky/Clausen: regular ideal tetra vol = Cl_2(pi/3); fig8 = 2x
cl2 = mp.clsin(2, mp.pi/3)   # Clausen Cl_2(pi/3) = Im Li_2(e^{i pi/3})
print(f"cross-check Cl_2(pi/3)    = {mp.nstr(cl2,25)}   (should equal D(z))")
print(f"   2*Cl_2(pi/3)           = {mp.nstr(2*cl2,25)}")

# Chern-Simons: 4_1 amphichiral => geometric CS = 0 (mod the ambiguity), a FIXED POINT of CS->-CS.
CS = mp.mpf(0)
print()
print("Chern-Simons (geometric):  CS(4_1) = 0   (amphichiral: CS = -CS mod 1 => 0 or 1/2;")
print("   the geometric flat connection sits at CS=0 -- the conjugation FIXED POINT).")

# complexified volume / saddle actions:  the two non-abelian (geometric + conjugate)
# saddle actions are  +/- (Vol + i*CS).  With CS=0 they are +/- Vol : REAL.
S_geo   = Vol + 1j*CS
S_conj  = -(Vol + 1j*CS)
print()
print("Two non-abelian saddle actions  S = +/- (Vol + i*CS):")
print(f"   S_geo  = {mp.nstr(S_geo, 20)}")
print(f"   S_conj = {mp.nstr(S_conj, 20)}")
print(f"   Im(S_geo)  = {mp.nstr(mp.im(S_geo),5)}   Im(S_conj) = {mp.nstr(mp.im(S_conj),5)}")
print("   => BOTH actions are REAL (CS=0).  They form ONE conjugation-pair {+Vol,-Vol},")
print("      i.e. 1 orbit mod the conjugation Z/2  (2 saddles, 1 pair).")

print()
print("EXTRA structure (cite Garoufalidis-Gu-Marino, arXiv:2012.00062 'Peacock patterns")
print("and resurgence in complex CS'; Garoufalidis-Zagier 'quantum modularity'):")
print("   the Borel plane of the 4_1 state integral carries a LATTICE of secondary")
print("   singularities (the 'peacock' pattern) at points  (V_geo * n + 2 pi i * m + ...),")
print("   an arithmetic Z(sqrt-3)/quantum-modular structure generated by the two primary")
print("   saddle actions.  This is object-intrinsic structure beyond the 2 primary saddles.")

# ---------------------------------------------------------------------------
print()
print(LINE)
print("PART 2  FRW mini-superspace lapse integral (Feldbrugge-Lehners-Turok 2017)")
print(LINE)
print("""Reconstruction (closed FRW, q=a^2, cosmological constant Lambda; units 2*pi^2 kept):
  L = -3 qdot^2/(4N) + N(3 - Lambda*q).  EOM: qddot = 2 N^2 Lambda/3 (linear => q(t)
  quadratic).  On-shell over t in [0,1], q(0)=q0, q(1)=q1, the lapse action is
       S(N) = 2*pi^2 [ (Lambda^2/36) N^3 + (3 - Lambda(q0+q1)/2) N - 3(q1-q0)^2/(4N) ]
  i.e. exactly the cited FORM  S(N) = A N^3 + B N + C/N  with
       A = 2pi^2 * Lambda^2/36,  B = 2pi^2 (3 - Lambda(q0+q1)/2),  C = -2pi^2 * 3(q1-q0)^2/4.
  Stationarity dS/dN=0 => 3A N^4 + B N^2 - C = 0 : a QUARTIC, biquadratic in N.""")


def frw_saddles(Lam, q0, q1, label):
    two_pi2 = 2 * mp.pi**2
    A = two_pi2 * Lam**2 / 36
    B = two_pi2 * (3 - Lam*(q0+q1)/2)
    C = -two_pi2 * 3*(q1-q0)**2 / 4
    print(f"\n-- {label}:  Lambda={Lam}, q0={q0}, q1={q1}")
    print(f"   A={mp.nstr(A,8)}  B={mp.nstr(B,8)}  C={mp.nstr(C,8)}")
    # dS/dN=0: 3A N^4 + B N^2 - C = 0. Solve biquadratic in x=N^2: 3A x^2 + B x - C = 0.
    a, b, c = 3*A, B, -C
    disc = b*b - 4*a*c
    print(f"   biquadratic 3A x^2 + B x + (-C) = 0 : discriminant = {mp.nstr(disc,8)}"
          f"  ({'<0 => complex x' if mp.re(disc)<0 else '>=0'})")
    xr = [(-b + mp.sqrt(disc))/(2*a), (-b - mp.sqrt(disc))/(2*a)]
    saddles = []
    for x in xr:
        for s in (mp.sqrt(x), -mp.sqrt(x)):
            saddles.append(s)
    # action at each saddle
    def S(N):
        return A*N**3 + B*N + C/N
    print(f"   #saddles = {len(saddles)}  (4 expected: two x-roots, each +/- sqrt)")
    for i, N in enumerate(saddles):
        Sv = S(N)
        print(f"     N{i+1} = {mp.nstr(N,14):>34}   S(N) = {mp.nstr(Sv,14)}"
              f"   |Im S|={mp.nstr(abs(mp.im(Sv)),6)}")
    # conjugate-pair structure
    print("   conjugation Z/2 (N -> conj(N)) pairs the 4 saddles into 2 conjugate pairs.")
    return saddles


s1 = frw_saddles(mp.mpf(3), mp.mpf(0), mp.mpf(2), "coeff set 1 (past throat)")
s2 = frw_saddles(mp.mpf(3), mp.mpf(0), mp.mpf(3), "coeff set 2")
s3 = frw_saddles(mp.mpf(1), mp.mpf(0), mp.mpf(5), "coeff set 3 (different Lambda)")
s4 = frw_saddles(mp.mpf(2), mp.mpf('0.5'), mp.mpf(7), "coeff set 4 (q0!=0)")

print()
print("Robustness: across all 4 representative (Lambda,q0,q1) the combinatorial type is")
print("INVARIANT: 4 saddles, 2 conjugate pairs, actions generically COMPLEX (Im S != 0).")
print("(The measure-zero exception Lambda*q1=... makes the pair merge -- the Hartle-Hawking")
print(" throat, e.g. Lambda=3,q1=1 gives a double root N=+/- i; excluded as non-generic.)")

# ---------------------------------------------------------------------------
print()
print(LINE)
print("PART 3  Qualitative Stokes / thimble connectivity")
print(LINE)
print("""fig-8 state integral:  1-dim oscillatory integral (Andersen-Kashaev Teichmuller TQFT).
  2 non-abelian saddles, actions +/- Vol on the REAL action-axis, symmetric about 0 under
  the conjugation Z/2 whose FIXED POINT (CS=0) is where they live.  The steepest-descent
  contour picks the geometric (dominant) saddle; its conjugate is anti-Stokes-related.
FRW lapse integral:  1-dim oscillatory integral over the lapse N (Picard-Lefschetz,
  Feldbrugge-Lehners-Turok).  4 saddles OFF the real axis (complex actions); the physical
  contour deformation selects 2-of-4, and WHICH 2 is contour-dependent (Lorentzian vs
  no-boundary) -- the crux of the FLT vs Hartle-Hawking Stokes debate.
SHARED: both are 1-dim Picard-Lefschetz/steepest-descent integrals carrying a conjugation
  Z/2 on their saddle sets.  DIFFERS: (#saddles 2 vs 4; mod-conj orbits 1 vs 2), (actions
  REAL vs COMPLEX), (fig-8 peacock lattice has no FRW analogue), (fig-8 saddles sit AT the
  conjugation fixed point CS=0; FRW saddles sit OFF it).""")

# ---------------------------------------------------------------------------
print()
print(LINE)
print("VERDICT")
print(LINE)
print("""              | figure-eight (4_1) state integral | FRW de Sitter lapse integral
 dimension    | 1                                 | 1
 method       | Picard-Lefschetz / steepest desc. | Picard-Lefschetz / steepest desc.
 conj Z/2     | yes (z <-> zbar)                  | yes (N <-> Nbar)
 #saddles     | 2 (non-abelian geom + conj)       | 4 (biquadratic quartic)
 mod-conj     | 1 orbit                           | 2 orbits
 saddle eqn   | gluing eqns (quadratic->2 roots)  | 3A N^4+B N^2-C=0 (quartic->4 roots)
 action Im    | 0  (CS=0, amphichiral FIXED PT)   | != 0  (generically COMPLEX)
 extra struct | peacock Borel lattice (Q(sqrt-3)) | none
--------------------------------------------------------------------------------
=> OUTCOME B : SKELETON DIFFERS, METHOD SHARED (partial: method-meeting + inversion).
   Discriminating fact: CS(4_1)=0 (amphichirality) forces the object's saddle actions
   to be REAL -- the saddles sit AT the conjugation fixed point -- whereas the FRW
   saddle actions are COMPLEX (off the fixed point).  The B709 structure-inversion,
   now computed at the path-integral/thimble level.  Confirms B707 'Turok=method-only'.
""")
