#!/usr/bin/env python3
"""B1385 -- the states together: can several states of the generated architecture X_gen supply jointly what m004 withholds?

The question is the owner's (2026-09-27): once the genesis is read as generating an architecture rather than selecting an
object (B1384, philosophy/P022), can more generated states be used together to supply the Standard-Model ingredients the
object withholds (docs/THE_VERDICT_OF_THE_OBJECT_2026-09-16.md: a chiral generation surviving the Higgs sector, which in the
seat's frame needs a *free cusp* -- a cusp whose peripheral image in H_1(M; Q) has rank below b_1 -- B1368/B1369)?

Own code: SnapPy for triangulations, shapes and covers; PARI (cypari) for algebraic recognition; no Sage.

  S1 no word state has a free cusp.  For every mixed cyclic word w in L, R up to length N and both signs, the orientable
     once-punctured-torus bundle b+(+-)w has one cusp, b_1 = 1 and a peripheral image of rank 1 in H_1(M; Q) (computed from
     SnapPy's presentation).  General reason: H_1 = Z + Z^2/(phi - I), det(phi - I) = 2 - tr(phi) != 0, the fibre's boundary is
     a commutator and the meridian maps onto the base.  Concatenation (the fibre sum of two bundles) and the fibre-cyclic
     covers M(w^k) stay word states, so no word-level join creates a free cusp.
  S2 the swap is the mirror.  M(swap w) is M(w) with its orientation reversed (isometric, Chern-Simons negated), and M(w) is
     amphichiral iff swap(w) ~ w or swap(w) ~ rev(w) cyclically -- the combinatorial criterion agrees with SnapPy's symmetry
     groups on every state.
  S3 the invariant trace field of every orientable word state, as the shape field (Neumann-Reid: for a cusped manifold kM is
     generated by the shapes of any ideal triangulation), recognised at high precision with PARI: a primitive element's
     minimal polynomial (algdep + factor), polredabs, the field discriminant; every shape is verified to lie in the field,
     and tr^2 of the trace ring's generators (every product of distinct generators of SnapPy's presentation, length <= 3:
     Horowitz) is verified to be an algebraic integer of the field -- so every trace is integral.
  S4 the divide.  The word states whose field is Q(sqrt-3) -- the field of the founding ratio g = -RL^-1, m004's field --
     are exactly the swap-symmetric +-(LR)^k: no chiral word state up to length N is commensurable with m004 (the invariant
     trace field is a commensurability invariant).  The arithmetic word states (imaginary quadratic field; traces are
     integral on every word state, S3) are listed with their Bianchi discriminant.
  S5 where free cusps are.  The covers of degree <= D of m004, m003 (the Eisenstein class) and of m009, m010 (the first
     rung of the ladder, Q(sqrt-7)): cusps, b_1, free cusps, amphichirality.  Free cusps enter only through covers that are
     not fibre-cyclic -- the refinement arrows -- and each cover stays in its parent's commensurability class.
  S6 the golden face alone.  The word states whose monodromy field is Q(sqrt5) (trace a Lucas number L_2n) include chiral
     ones (L^5 R at length 6); their invariant trace fields are not Q(sqrt-3).  The two faces of B1270 meet, among the word
     states, only on the swap-symmetric powers of LR.
Usage: python3 states_together.py [N] [D]   (defaults N = 7, D = 4; a few minutes)"""
import itertools
import random
import sys
import warnings

warnings.filterwarnings("ignore")
import snappy
import cypari

pari = cypari.pari


class pari_precision:
    """set PARI's default real precision for a block and restore it afterwards (no global side effect on import: other code in the
    same process -- a test worker, SnapPy -- keeps its own precision)"""

    def __init__(self, digits):
        self.digits = digits

    def __enter__(self):
        self.old = pari.set_real_precision(self.digits)
        return self

    def __exit__(self, *exc):
        pari.set_real_precision(self.old)
        return False


_STACK_RAISED = []


def _allow_stack_growth():
    """let the PARI stack grow on demand (large polredbest calls); the current size is kept, only the ceiling is raised, once"""
    if not _STACK_RAISED:
        pari.allocatemem(0, 2 * 10 ** 9, silent=True)
        _STACK_RAISED.append(True)
BITS = 2200                     # shapes and holonomy at ~660 decimal digits
MAXDEG = 16                     # the largest invariant-trace-field degree certified; larger fields are reported as such


# ------------------------------------------------------------------------------------------------ the words
def canon(w):
    return min(w[i:] + w[:i] for i in range(len(w)))


def swap(w):
    return w.translate(str.maketrans("LR", "RL"))


def primitive_root(w):
    n = len(w)
    for d in range(1, n + 1):
        if n % d == 0 and w[:d] * (n // d) == w:
            return w[:d], n // d
    return w, 1


def mixed_cyclic_words(N):
    out = set()
    for n in range(2, N + 1):
        for t in itertools.product("LR", repeat=n):
            w = "".join(t)
            if "L" in w and "R" in w:
                out.add(canon(w))
    return sorted(out, key=lambda x: (len(x), x))


def swap_symmetric(w):
    """amphichirality criterion for the bundle of the cyclic word w: swap(w) ~ w or swap(w) ~ rev(w) (up to rotation)"""
    return canon(swap(w)) == canon(w) or canon(swap(w)) == canon(w[::-1])


def matrix(w):
    L, R = ((1, 1), (0, 1)), ((1, 0), (1, 1))
    M = ((1, 0), (0, 1))
    for ch in w:
        X = L if ch == "L" else R
        M = tuple(tuple(sum(M[i][k] * X[k][j] for k in range(2)) for j in range(2)) for i in range(2))
    return M


# ------------------------------------------------------------------------------------------------ homology
def abelianise(word, gens):
    v = [0] * len(gens)
    for ch in word:
        i = gens.index(ch.lower())
        v[i] += 1 if ch.islower() else -1
    return v


def rank(rows):
    """rank over Q by fraction-free elimination"""
    from fractions import Fraction
    A = [[Fraction(x) for x in r] for r in rows if any(r)]
    if not A:
        return 0
    m, n, r = len(A), len(A[0]), 0
    for c in range(n):
        piv = next((i for i in range(r, m) if A[i][c] != 0), None)
        if piv is None:
            continue
        A[r], A[piv] = A[piv], A[r]
        for i in range(m):
            if i != r and A[i][c] != 0:
                f = A[i][c] / A[r][c]
                A[i] = [a - f * b for a, b in zip(A[i], A[r])]
        r += 1
    return r


def peripheral_ranks(M):
    """b_1 and, per cusp, the rank of the peripheral image in H_1(M; Q) (B1369's definition of a free cusp: rank < b_1)"""
    G = M.fundamental_group()
    gens = list(G.generators())
    rels = [abelianise(r, gens) for r in G.relators()]
    r0 = rank(rels)
    b1 = len(gens) - r0
    ranks = []
    for mu, lam in G.peripheral_curves():
        ranks.append(rank(rels + [abelianise(mu, gens), abelianise(lam, gens)]) - r0)
    return b1, ranks


# ------------------------------------------------------------------------------------------------ fields
def to_pari(z):
    return pari(z)


def height_digits(f):
    return max(len(str(abs(int(c)))) for c in pari.Vec(f))


def minpoly(x, digits, maxdeg=MAXDEG):
    """the minimal polynomial of the number x (known to `digits` decimal digits) over Q, or None.  A factor f of PARI's algdep output
    is accepted only when it is *certified*: it vanishes at x to within 10^-(digits - 60) and (deg f + 1) * (height of f in digits)
    <= 0.6 * digits, so the relation is strongly overdetermined and cannot be an LLL artefact of the working precision."""
    budget = 0.6 * digits
    for d in range(1, maxdeg + 1):
        try:
            p = pari.algdep(x, d)
        except cypari._pari.PariError:              # PARI refuses degree 1 for a non-real x
            continue
        fac = pari.factor(p)
        for i in range(int(pari.matsize(fac)[0])):
            f = fac[0][i]
            n = int(pari.poldegree(f))
            if (n + 1) * height_digits(f) > budget:
                continue
            if abs(pari.subst(f, "x", x)) < pari("1e-%d" % (digits - 60)) * (1 + abs(x)) ** n:
                return f
    return None


def in_field(z, theta, n, digits):
    """z in Q(theta), [Q(theta):Q] = n: a certified integer relation c0 z + sum c_i theta^i = 0 with c0 != 0"""
    vec = [z] + [theta ** i for i in range(n)]
    rel = pari.lindep(vec)
    c0 = int(rel[0])
    if c0 == 0:
        return False
    res = sum(rel[i] * vec[i] for i in range(len(vec)))
    h = max(len(str(abs(int(c)))) for c in rel)
    return abs(res) < pari("1e-%d" % (digits - 60)) and (n + 1) * h <= 0.6 * digits


def shape_field(M, levels=((2200, 700), (7000, 2150))):
    """the invariant trace field of the cusped manifold M as its shape field: (reduced polynomial, degree, discriminant,
    signature (r1, r2), working digits), every shape certified to lie in it.  The primitive element is tried as z0, then z0 + z_j,
    then z0 + 2 z_j + 3 z_k; the polynomial is reduced by polredbest (polredabs and the field discriminant for degree <= 6).  A state
    whose field is not certified at 700 digits is retried at 2150; if still uncertified -- in practice a field of degree > 16 --
    None (reported as such, never guessed)."""
    _allow_stack_growth()
    for bits, digits in levels:
        shapes = [to_pari(z) for z in M.tetrahedra_shapes("rect", bits_prec=bits)]
        n_t = len(shapes)
        trials = [[1] + [0] * (n_t - 1)]
        trials += [[1 if i in (0, j) else 0 for i in range(n_t)] for j in range(1, n_t)]
        trials += [[1 if i == 0 else (2 if i == j else (3 if i == k else 0)) for i in range(n_t)]
                   for j in range(1, n_t) for k in range(j + 1, n_t)][:6]
        for ti, coeffs in enumerate(trials):
            theta = sum(c * z for c, z in zip(coeffs, shapes))
            f = minpoly(theta, digits)
            if f is None:
                if ti == 0:          # z0 alone has no certified relation of degree <= MAXDEG: the field is larger (or needs precision)
                    break
                continue
            n = int(pari.poldegree(f))
            if all(in_field(z, theta, n, digits) for z in shapes):
                try:
                    g = pari.polredabs(f) if n <= 6 else pari.polredbest(f)
                except cypari._pari.PariError:
                    g = f
                disc = int(pari.nfdisc(g)) if n <= 6 else None
                r1 = int(pari.polsturm(g))
                return dict(poly=str(g), degree=n, disc=disc, signature=(r1, (n - r1) // 2), digits=digits)
    return None


def in_eisenstein(M, digits=700):
    """every shape of M lies in Q(omega) = Q(sqrt-3): a certified relation c0 z + c1 + c2 omega = 0 with c0 != 0 for each shape"""
    with pari_precision(digits):
        omega = pari("exp(2*Pi*I/3)")                              # computed at the working precision, then kept
    for z in M.tetrahedra_shapes("rect", bits_prec=2200):
        z = to_pari(z)
        rel = pari.lindep([z, 1, omega])
        if int(rel[0]) == 0:
            return False
        res = rel[0] * z + rel[1] + rel[2] * omega
        if not (abs(res) < pari("1e-%d" % (digits - 60)) and max(len(str(abs(int(c)))) for c in rel) <= 100):
            return False
    return True


def horowitz_words(gens):
    """the traces of these words generate the trace ring of a group on the given generators (Horowitz 1972; Procesi): every product
    of distinct generators in increasing order, of length at most 3"""
    out = []
    for k in (1, 2, 3):
        for combo in itertools.combinations(gens, k):
            out.append("".join(combo))
    return out


def tr2_integral_in_field(M, poly):
    """tr^2 of the trace-ring generators of the (polished, PSL2) holonomy: each an algebraic integer lying in the field of poly.  Then
    every trace is integral (tr is a root of x^2 - tr^2), and the whole trace ring is integral."""
    G = M.polished_holonomy(bits_prec=BITS, lift_to_SL2=False)
    K = pari.nfinit(pari.subst(pari(poly), "x", "y"))             # the field in y; the factored polynomial stays in x
    ok = True
    for w in horowitz_words(G.generators()):
        t2 = to_pari(G(w).trace()) ** 2
        f = minpoly(t2, 700)
        if f is None:
            return False
        lead = abs(int(pari.pollead(f)))
        # integrality: the minimal polynomial is monic up to sign; membership: it has a root in K
        ok &= lead == 1 and int(pari.poldegree(pari.nffactor(K, f)[0][0])) == 1
    return ok


# ------------------------------------------------------------------------------------------------ S1-S4, S6
LUCAS_EVEN = {3, 7, 18, 47, 123, 322, 843, 2207}        # traces of golden monodromies: t^2 - 4 = 5 k^2


def census(N, verbose=False):
    rows = []
    for w in mixed_cyclic_words(N):
        (a, b), (c, d) = matrix(w)
        tr = a + d
        for sign in "+-":
            name = "b+%s%s" % (sign, w)
            M = snappy.Manifold(name)
            b1, ranks = peripheral_ranks(M)
            amph = M.symmetry_group().is_amphicheiral()
            cs = float(M.chern_simons())
            vol = float(M.volume())
            try:
                ident = str(M.identify()[0]).split("(")[0]
            except Exception:
                ident = "-"
            fld = shape_field(M)
            eis = in_eisenstein(M)
            if verbose:
                print("   .. %s%s %s deg %s" % (sign, w, ident, (fld["degree"], fld["digits"]) if fld else "uncertified"), flush=True)
            rows.append(dict(word=sign + w, primitive=primitive_root(w), trace=tr if sign == "+" else -tr, ident=ident,
                             cusps=M.num_cusps(), H1=str(M.homology()), b1=b1, peripheral_ranks=ranks,
                             free_cusps=sum(1 for r in ranks if r < b1), swap_symmetric=swap_symmetric(w),
                             amphichiral=amph, CS=cs, vol=vol, field=fld, eisenstein=eis, golden=abs(tr) in LUCAS_EVEN))
    return rows


def s1_no_free_cusp(rows):
    for r in rows:
        assert r["cusps"] == 1 and r["b1"] == 1 and r["peripheral_ranks"] == [1] and r["free_cusps"] == 0, r
        (a, b), (c, d) = matrix(r["word"][1:])
        tr = a + d
        assert (2 - tr if r["word"][0] == "+" else 2 + tr) != 0          # det(+-phi - I) != 0: coker finite, b_1 = 1
    return {"states": len(rows), "one cusp, b1 = 1, peripheral rank 1": len(rows), "free cusps": 0}


def s2_swap_is_mirror(rows, N):
    by = {r["word"]: r for r in rows}
    agree = sum(1 for r in rows if r["amphichiral"] == r["swap_symmetric"])
    assert agree == len(rows), [r["word"] for r in rows if r["amphichiral"] != r["swap_symmetric"]]
    pairs = 0
    for w in mixed_cyclic_words(N):
        if swap_symmetric(w):
            continue
        for sign in "+-":
            A, B = snappy.Manifold("b+%s%s" % (sign, w)), snappy.Manifold("b+%s%s" % (sign, swap(w)))
            assert A.is_isometric_to(B)
            cs_sum = (float(A.chern_simons()) + float(B.chern_simons())) % 0.5
            assert min(cs_sum, 0.5 - cs_sum) < 1e-9                                    # CS(swap w) = -CS(w) mod 1/2
            pairs += 1
    return {"criterion agrees with SnapPy": "%d/%d" % (agree, len(rows)), "mirror pairs checked (w, swap w)": pairs}


def s3_fields(rows, check_traces=True):
    cert = [r for r in rows if r["field"] is not None]
    unc = [(r["word"], r["ident"]) for r in rows if r["field"] is None]
    tr_ok = None
    if check_traces:
        tr_ok = 0
        for r in cert:
            if r["field"]["degree"] <= 8:
                M = snappy.Manifold("b+%s%s" % (r["word"][0], r["word"][1:]))
                assert tr2_integral_in_field(M, r["field"]["poly"]), r["word"]
                tr_ok += 1
    degs = {}
    for r in cert:
        degs[r["field"]["degree"]] = degs.get(r["field"]["degree"], 0) + 1
    # consistency: one manifold, one field degree (w and its rotations/reversals name the same state)
    by_ident = {}
    for r in cert:
        by_ident.setdefault(r["ident"], set()).add(r["field"]["degree"])
    assert all(len(v) == 1 for v in by_ident.values()), {k: v for k, v in by_ident.items() if len(v) > 1}
    return {"fields certified": "%d/%d" % (len(cert), len(rows)), "degree histogram": dict(sorted(degs.items())),
            "uncertified at 2150 digits (degree > %d)" % MAXDEG: unc,
            "trace ring integral (tr^2 of the Horowitz generators; certified states of degree <= 8)": tr_ok}


def s4_divide(rows):
    eis = [r for r in rows if r["eisenstein"]]
    for r in eis:
        prim, k = r["primitive"]
        assert canon(prim) == "LR" and r["swap_symmetric"] and r["amphichiral"], r["word"]
        assert r["field"] is not None and (r["field"]["degree"], r["field"]["disc"]) == (2, -3)
    chiral = [r for r in rows if not r["amphichiral"]]
    assert not any(r["eisenstein"] for r in chiral)
    arith = {}
    for r in rows:
        if r["field"] is not None and r["field"]["degree"] == 2 and r["field"]["disc"] < 0:
            arith.setdefault(r["field"]["disc"], []).append((r["word"], r["ident"], "amph" if r["amphichiral"] else "chiral"))
    return {"Q(sqrt-3) states (every shape in Q(omega))": [(r["word"], r["ident"]) for r in eis], "chiral states": len(chiral),
            "chiral states in m004's class": 0, "arithmetic states by discriminant": arith}


def bianchi_covolume(disc):
    """vol(H^3 / PSL(2, O_K)) = |D|^(3/2) zeta_K(2) / (4 pi^2) for K = Q(sqrt(disc)) (Humbert), with PARI's Dedekind zeta"""
    pol = {-3: "x^2+x+1", -4: "x^2+1", -7: "x^2+x+2", -8: "x^2+2", -11: "x^2+x+3"}[disc]
    z2 = pari.lfun(pari.lfuncreate(pari(pol)), 2)
    return float(abs(disc) ** 1.5 * z2 / (4 * pari("Pi") ** 2))


def s3b_volume_ratios(rows):
    """an arithmetic state is commensurable with PSL(2, O_d): its volume is a rational multiple of the Bianchi covolume --
    here an integer on every arithmetic word state (an independent check of S3's recognition)"""
    out = {}
    for r in rows:
        f = r["field"]
        if f is not None and f["degree"] == 2 and f["disc"] < 0:
            q = r["vol"] / bianchi_covolume(f["disc"])
            assert abs(q - round(q)) < 1e-9, (r["word"], q)
            out[r["word"]] = (r["ident"], f["disc"], int(round(q)))
    return out


def s6_golden(rows):
    gold = [r for r in rows if r["golden"]]
    out = []
    for r in gold:
        f = r["field"]
        out.append((r["word"], r["ident"], "amph" if r["amphichiral"] else "chiral", f["degree"] if f else "uncertified",
                    f["disc"] if f else None, "Q(sqrt-3)" if r["eisenstein"] else "not Q(sqrt-3)"))
    both = [r for r in gold if r["eisenstein"]]
    assert all(canon(r["primitive"][0]) == "LR" for r in both)
    return {"golden-monodromy states": out, "golden and Q(sqrt-3) together": [r["word"] for r in both]}


# ------------------------------------------------------------------------------------------------ S5 covers
def s5_covers(D, parents=("m004", "m003", "m009", "m010")):
    out = {}
    for name in parents:
        P = snappy.Manifold(name)
        rows = []
        for d in range(2, D + 1):
            for C in P.covers(d):
                b1, ranks = peripheral_ranks(C)
                cyc = C.cover_info()["type"] == "cyclic" and C.num_cusps() == 1
                try:
                    amph = C.symmetry_group().is_amphicheiral()
                except Exception:
                    amph = None
                rows.append(dict(degree=d, type=C.cover_info()["type"], cusps=C.num_cusps(), H1=str(C.homology()), b1=b1,
                                 free=sum(1 for r in ranks if r < b1), amphichiral=amph))
        fibre_cyclic = [r for r in rows if r["cusps"] == 1 and r["b1"] == 1]
        assert all(r["free"] == 0 for r in fibre_cyclic)
        out[name] = dict(covers=len(rows), multi_cusped=sum(1 for r in rows if r["cusps"] > 1),
                         with_free_cusp=sum(1 for r in rows if r["free"] > 0),
                         free_and_chiral=sum(1 for r in rows if r["free"] > 0 and r["amphichiral"] is False),
                         rows=rows)
    return out


if __name__ == "__main__":
    N = int(sys.argv[1]) if len(sys.argv) > 1 else 7
    D = int(sys.argv[2]) if len(sys.argv) > 2 else 4
    rows = census(N, verbose=True)
    print("=== the word states up to length %d (both signs, orientable) ===" % N)
    for r in rows:
        f = r["field"]
        print("  %-10s %-8s tr %5d  H1 %-14s cusps %d b1 %d free %d  %s  CS %+.6f  vol %.6f  kM %s%s%s" % (
            r["word"], r["ident"], r["trace"], r["H1"], r["cusps"], r["b1"], r["free_cusps"],
            "amph  " if r["amphichiral"] else "chiral", r["CS"], r["vol"],
            ("deg %2d disc %s %s" % (f["degree"], f["disc"], f["poly"] if f["degree"] <= 4 else "")) if f else "uncertified",
            "  Q(sqrt-3)" if r["eisenstein"] else "", "  golden" if r["golden"] else ""))
    print("S1 no word state has a free cusp:", s1_no_free_cusp(rows))
    print("S2 the swap is the mirror:", s2_swap_is_mirror(rows, N))
    print("S3 invariant trace fields:", s3_fields(rows))
    print("S3b volume / Bianchi covolume on the arithmetic states (an integer each):", s3b_volume_ratios(rows))
    print("S4 the divide:", s4_divide(rows))
    print("S6 the golden face alone:", s6_golden(rows))
    cov = s5_covers(D)
    for name, c in cov.items():
        print("S5 covers of %s up to degree %d: %d covers, %d multi-cusped, %d with a free cusp, %d with a free cusp and chiral" % (
            name, D, c["covers"], c["multi_cusped"], c["with_free_cusp"], c["free_and_chiral"]))
        for r in c["rows"]:
            if r["free"] > 0:
                print("     degree %d %-9s cusps %d H1 %-18s b1 %d free %d %s" % (
                    r["degree"], r["type"], r["cusps"], r["H1"], r["b1"], r["free"],
                    "amph" if r["amphichiral"] else ("chiral" if r["amphichiral"] is False else "?")))
    print("DONE")
