"""B1011 phase 3 -- the quaternion model of 2T x 2I, exact character table, and the
class-by-class match against <R,L>'s exact characters. Then C4/C5/C6."""
import itertools, json, os
HERE = os.path.dirname(os.path.abspath(__file__))
from fractions import Fraction as F
from b1011_exact import Z60, DEG   # reuse the exact field

# sqrt5 = 1 + 2(zeta_5 + zeta_5^4)  in Q(zeta_60): zeta_5 = zeta_60^12
z5 = Z60.zeta(12)
SQRT5 = Z60.one() + (z5 + Z60.zeta(48)).scale(F(2))
HALF = F(1, 2)
PHI = (Z60.one() + SQRT5).scale(HALF)          # golden ratio, exact

# quaternions as 4-tuples of Z60 (real coeffs in Q(sqrt5) subfield)
def qmul(a, b):
    a0, a1, a2, a3 = a; b0, b1, b2, b3 = b
    return (a0*b0 - a1*b1 - a2*b2 - a3*b3,
            a0*b1 + a1*b0 + a2*b3 - a3*b2,
            a0*b2 - a1*b3 + a2*b0 + a3*b1,
            a0*b3 + a1*b2 - a2*b1 + a3*b0)
def qneg(a): return tuple((-x) for x in a)
ONEQ = (Z60.one(), Z60.zero(), Z60.zero(), Z60.zero())

def close_group(gens):
    seen = {tuple(x.c for x in ONEQ): ONEQ}
    frontier = [ONEQ]
    while frontier:
        nxt = []
        for M in frontier:
            for g in gens:
                Mg = qmul(M, g)
                k = tuple(x.c for x in Mg)
                if k not in seen:
                    seen[k] = Mg; nxt.append(Mg)
        frontier = nxt
    return list(seen.values())

# 2T: generated by i and (1+i+j+k)/2 ; 2I: by i and (phi + phi^-1 i + j)/2? use standard icosian gens
zero, one = Z60.zero(), Z60.one()
qi = (zero, one, zero, zero)
w24 = (one.scale(HALF), one.scale(HALF), one.scale(HALF), one.scale(HALF))
T24 = close_group([qi, w24])
print("|2T| =", len(T24))
PHIINV = PHI - Z60.one()          # 1/phi = phi - 1
icos = (PHI.scale(HALF), PHIINV.scale(HALF), one.scale(HALF), zero)
I120 = close_group([qi, icos])
print("|2I| =", len(I120))
assert len(T24) == 24 and len(I120) == 120

def qconj_classes(G):
    idx = {tuple(x.c for x in g): g for g in G}
    inv = {}
    for g in G:
        gc = (g[0], *[(-x) for x in g[1:]])   # unit quaternion inverse = conjugate
        inv[tuple(x.c for x in g)] = gc
    unassigned = set(idx.keys())
    classes = []
    while unassigned:
        k = next(iter(unassigned)); M = idx[k]
        orb = set()
        for gk, g in idx.items():
            c = qmul(qmul(g, M), inv[gk])
            orb.add(tuple(x.c for x in c))
        unassigned -= orb
        classes.append((idx[next(iter(orb))], len(orb)))
    return classes

CT = qconj_classes(T24); CI = qconj_classes(I120)
print("#classes 2T =", len(CT), " #classes 2I =", len(CI))
tr = lambda q: q[0].scale(F(2))          # tr V2 = 2*Re
# chi: the Z3 character of 2T with kernel Q8: A in Q8 -> 1; the two order-6/3 families -> omega, omega^2.
# Determine chi on classes via cube: chi(A) = omega^k with A^3 in Q8-coset... compute via the
# quotient 2T/Q8 = Z3: representative's image = number of w24-factors mod 3. Practical exact rule:
# chi(A) = 1 if tr(A) in {2,-2,0}; for tr = ±1 classes, chi = omega or omega^2 -- fixed by
# multiplicativity, verified below on ALL 576 pairs.
OMEGA = Z60.zeta(20)                      # e^{2pi i/3}
Q8set = {tuple(x.c for x in q) for q in close_group([qi, (zero, zero, one, zero)])}
print("|Q8| =", len(Q8set))
def chi_of(A):
    if tuple(x.c for x in A) in Q8set: return Z60.one()
    # A has order 3 or 6; chi(A) determined by which coset: use A * w24^-1 in Q8 => chi = omega etc.
    w_inv = (w24[0], *[(-x) for x in w24[1:]])
    B = A
    for k in (1, 2):
        B = qmul(B, w_inv)
        if tuple(x.c for x in B) in Q8set:
            return OMEGA if k == 1 else OMEGA * OMEGA
    raise RuntimeError("not in any coset")
# verify chi multiplicative on ALL 24x24 = 576 pairs (chat1's step 2), exactly:
ok = all((chi_of(qmul(a, b)) == chi_of(a) * chi_of(b)) for a in T24 for b in T24)
print("chi multiplicative on all 576 pairs:", ok)

# model character table: 63 rows (cT, cI): size, ch_odd = chi(A)*tr(B) [odd 2-dim],
# ch_even = tr(A)*tr(B)
model = []
for (A, szT) in CT:
    for (B, szI) in CI:
        model.append({"size": szT * szI,
                      "odd": chi_of(A) * tr(B),
                      "even": tr(A) * tr(B),
                      "trA": tr(A), "trB": tr(B), "chi": chi_of(A)})
print("model rows:", len(model))

import json as _json
from fractions import Fraction as _F
def _z60(vec): return Z60([_F(x) for x in vec])
rows = [{"word": r["word"], "size": r["size"],
         "tr_odd": _z60(r["tr_odd"]), "tr_even": _z60(r["tr_even"])}
        for r in _json.load(open(os.path.join(HERE, "class_chars.json")))]
# match: bijection with (size, odd, even) all equal
used = [False] * 63
matched = 0
for r in rows:
    hit = None
    for i, m in enumerate(model):
        if used[i]: continue
        if m["size"] == r["size"] and m["odd"] == r["tr_odd"] and m["even"] == r["tr_even"]:
            hit = i; break
    if hit is not None:
        used[hit] = True; matched += 1
print(f"CLASS-BY-CLASS MATCH: {matched}/63 (size, chi_odd, chi_even) all exact")
assert matched == 63
print(">>> rho_6 has EXACTLY the character of (chi (x) V2(2I)) (+) (V2(2T) (x) V2(2I)) on a")
print(">>> size-preserving class bijection -- the McKay tensor factorization holds EXACTLY.")

# C4: trace sets, exact
trT_set = {tuple(m["trA"].c) for m in model}
trI_set = {tuple(m["trB"].c) for m in model}
print("|trace set 2T| =", len(trT_set), " |trace set 2I| =", len(trI_set))
# name the 2I set against the golden closed forms:
names = {tuple((Z60.one().scale(F(v))).c): str(v) for v in (2, -2, 1, -1, 0)}
names[tuple(PHI.c)] = "phi"; names[tuple(qneg((PHI,))[0].c) if False else tuple((-PHI).c)] = "-phi"
names[tuple(PHIINV.c)] = "1/phi"; names[tuple((-PHIINV).c)] = "-1/phi"
labels = sorted(names.get(t, "?") for t in trI_set)
print("2I trace set =", labels)
assert "?" not in labels
# C5: forced-coupling counts by inclusion-exclusion, from the model's subgroup data:
kerchi, ZI, ZT = 8, 2, 2
odd_forced = kerchi * 120 + 24 * ZI - kerchi * ZI
even_forced = ZT * 120 + 24 * ZI - ZT * ZI
print("forced counts: odd =", odd_forced, " even =", even_forced)
assert odd_forced == 992 and even_forced == 284
# C5b: B856's tones = |Re chi * (1/2) tr B| value set, exact:
tones = set()
for m in model:
    val = (m["chi"] + m["chi"].conj()).scale(F(1, 2)) * m["trB"].scale(F(1, 2))  # Re(chi)*trB/2
    tones.add(tuple(val.c))
tone_names = []
half = Z60.one().scale(F(1,2))
named = {tuple(Z60.zero().c): "0", tuple(Z60.one().c): "1", tuple((-Z60.one()).c): "-1",
         tuple(half.c): "1/2", tuple((-half).c): "-1/2",
         tuple(PHI.scale(F(1,2)).c): "phi/2", tuple((-PHI.scale(F(1,2))).c): "-phi/2",
         tuple(PHIINV.scale(F(1,2)).c): "1/(2phi)", tuple((-PHIINV.scale(F(1,2))).c): "-1/(2phi)",
         tuple(Z60.one().scale(F(1,4)).c): "1/4", tuple((-Z60.one().scale(F(1,4))).c): "-1/4",
         tuple(PHI.scale(F(1,4)).c): "phi/4", tuple((-PHI.scale(F(1,4))).c): "-phi/4",
         tuple(PHIINV.scale(F(1,4)).c): "1/(4phi)", tuple((-PHIINV.scale(F(1,4))).c): "-1/(4phi)"}
tone_labels = sorted({named.get(t, "OTHER:" + str(t[:3])) for t in tones})
print("odd-side value set (Re chi * trB/2):", tone_labels)
# C6: the mirror law's value set (1/2 trA * 1/2 trB), exact:
mirror = set()
for m in model:
    mirror.add(tuple((m["trA"].scale(F(1,2)) * m["trB"].scale(F(1,2))).c))
mir_labels = sorted({named.get(t, "OTHER") for t in mirror})
print("even/MIRROR value set (trA/2 * trB/2):", mir_labels)
