"""B141 -- split S031: the phi-fixed tower is REDUCIBLE (Q8 finiteness); the phi^2-geometric tower is IRREDUCIBLE.

Third reconciliation pass on S031 (one layer past B140); a substantive correction to B140's reframe. Verify-don't-
trust: re-derive in-sandbox before banking. MATH tier; firewalled; nothing to CLAIMS.md; P1-P16, B85, merged
B124-B140 untouched. B129's banked conclusions are PRESERVED (a framing / object-identity correction).

  ============================================================================================================
  ITEM 1 (RIGOROUS, all n) -- the principal phi-fixed point is REDUCIBLE at every SL(n), n>=3.
      The unique IRREDUCIBLE SL(2) phi-fixed point is (0,0,0) (kappa=tr[A,B]=-2 != 2). Its rep is the QUATERNION
      GROUP Q8: A=diag(i,-i), B=[[0,1],[-1,0]] => A^2=B^2=-I, AB=-BA. Q8 is FINITE with irrep dims {1,1,1,1,2}
      (sum dim^2 = 8), MAX irrep dim 2. So Sym^{n-1} (dim n) of the 2-dim irrep is REDUCIBLE for all n>=3.
      => there is NO irreducible principal phi-fixed point anywhere in the SL(n) tower (n>=3). SL(2) is the only
      level where it is irreducible. (Corrects B140's "rigidity of the principal IRREDUCIBLE fixed point".)

  ITEM 2 (RIGOROUS, all n) -- the phi^2-geometric tower is IRREDUCIBLE at every SL(n), in Q(sqrt-3).
      The figure-eight phi^2-geometric holonomy (B129's S1a object): A=[[1,1],[0,1]], B=[[1,0],[-omega,1]],
      omega=1/2+sqrt(-3)/2 -- Zariski-DENSE in SL(2,C). Sym^{n-1} stays irreducible (algebra dim = n^2); traces
      in Q(sqrt-3).

  ITEM 3 (SOLID) -- the structural key: FINITENESS vs DENSITY. Finite image (Q8) -> reducible tower; dense image
      (fig-8) -> irreducible tower. S031 conflated the two: it took irreducibility+Q(sqrt-3) from the phi^2 (dense)
      object and "fixed point" from the phi (finite) object -- no single object has both.

  ITEM 4 (STRONG EVIDENCE / CONJECTURE, open n>=4) -- the SL(3) phi-fixed locus appears ENTIRELY reducible.
      Intertwiner search (converges, unlike B129's saddle-flee): phi-fixed <=> g A g^-1 = A g^-1 A g with
      B = g^-1 A g; fix A=diag(1,-1,-1), solve for g, classify <A,B> reducibility. Handoff: 150/150 reducible,
      0 irreducible. Necessary condition: A ~ B ~ AB (mutually conjugate). Rigorous proof = symbolic elimination
      (the SL(4) route); not attempted here.
"""
from __future__ import annotations

import itertools
import os
import sys

import numpy as np
import sympy as sp

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from frontier.B138_s031_principal_lemma.probe import sym_power  # noqa: E402

I = sp.I


# ----------------------------------------------------------------------------------------------------------------
# algebra dimension (exact, sympy): dim of the matrix algebra generated by `gens` (BFS over words, rank-capped n^2).
# ----------------------------------------------------------------------------------------------------------------
def algebra_dim_exact(gens, n, max_depth=8):
    mats = [sp.eye(n)]
    frontier = [sp.eye(n)]
    dim = 1
    for _ in range(max_depth):
        nf = []
        for M in frontier:
            for g in gens:
                nf.append(sp.expand(M * g))
        mats.extend(nf)
        frontier = nf
        dim = sp.Matrix([list(m) for m in mats]).rank()
        if dim == n * n:
            break
    return int(dim)


# ----------------------------------------------------------------------------------------------------------------
# ITEM 1 -- the Q8 phi-fixed rep and its reducible Sym tower.
# ----------------------------------------------------------------------------------------------------------------
def q8_rep():
    A = sp.Matrix([[I, 0], [0, -I]])
    B = sp.Matrix([[0, 1], [-1, 0]])
    return A, B


def q8_relations():
    A, B = q8_rep()
    return {"A2_eq_-I": A * A == -sp.eye(2), "B2_eq_-I": B * B == -sp.eye(2),
            "AB_eq_-BA": A * B == -(B * A), "detA": A.det(), "detB": B.det()}


def q8_group_order():
    """The group generated by A,B (order should be 8 = Q8)."""
    A, B = q8_rep()
    seen, frontier = {sp.ImmutableMatrix(sp.eye(2))}, [sp.eye(2)]
    for _ in range(10):
        nf = []
        for M in frontier:
            for g in (A, B):
                P = sp.ImmutableMatrix(sp.expand(M * g))
                if P not in seen:
                    seen.add(P); nf.append(P)
        frontier = nf
        if not nf:
            break
    return len(seen)


def phi_fixed_tower_reducible(nmax=7):
    A2, B2 = q8_rep()
    rows = {}
    for n in range(2, nmax + 1):
        A, B = sym_power(A2, n - 1), sym_power(B2, n - 1)
        d = algebra_dim_exact([A, B], n)
        rows[n] = {"alg_dim": d, "n2": n * n, "irreducible": d == n * n}
    return {"rows": rows, "reducible_for_all_n_ge_3": all(not r["irreducible"] for n, r in rows.items() if n >= 3),
            "irreducible_only_at_n2": rows[2]["irreducible"]}


def q8_sym2_character():
    """Cross-check: chi_{Sym^2 V} = (3,3,-1,-1,-1) = chi_a + chi_b + chi_c on classes (1,-1,i,j,k)."""
    A2, B2 = q8_rep()
    reps = {"1": sp.eye(2), "-1": -sp.eye(2), "i": A2, "j": B2, "k": A2 * B2}
    chi = {cls: sp.simplify(sym_power(g, 2).trace()) for cls, g in reps.items()}
    return {"chi_Sym2": chi, "is_3_3_-1_-1_-1": [chi[c] for c in ("1", "-1", "i", "j", "k")] == [3, 3, -1, -1, -1]}


# ----------------------------------------------------------------------------------------------------------------
# ITEM 2 -- the phi^2-geometric fig-8 holonomy tower (B129's S1a object): irreducible all n, in Q(sqrt-3).
# ----------------------------------------------------------------------------------------------------------------
def fig8_holonomy():
    omega = sp.Rational(1, 2) + sp.sqrt(-3) / 2
    return sp.Matrix([[1, 1], [0, 1]]), sp.Matrix([[1, 0], [-omega, 1]])


def _in_q3(z):
    z = sp.expand(sp.simplify(z))
    return bool(sp.simplify(sp.re(z)).is_rational and sp.simplify(sp.im(z) / sp.sqrt(3)).is_rational)


def phi2_tower_irreducible(nmax=5):
    A2, B2 = fig8_holonomy()
    rows = {}
    for n in range(2, nmax + 1):
        A, B = sym_power(A2, n - 1), sym_power(B2, n - 1)
        d = algebra_dim_exact([A, B], n)
        traces_q3 = all(_in_q3(sp.simplify((A ** i * B ** j).trace()))
                        for i, j in itertools.product(range(1, 3), repeat=2))
        rows[n] = {"alg_dim": d, "n2": n * n, "irreducible": d == n * n, "traces_in_Q3": traces_q3}
    return {"rows": rows, "irreducible_all_n": all(r["irreducible"] for r in rows.values()),
            "all_traces_in_Q3": all(r["traces_in_Q3"] for r in rows.values())}


# ----------------------------------------------------------------------------------------------------------------
# ITEM 3 -- finiteness vs density: Q8 image finite (order 8); fig-8 image infinite (A^k=[[1,k],[0,1]] unbounded).
# ----------------------------------------------------------------------------------------------------------------
def finiteness_vs_density():
    A2, _ = fig8_holonomy()
    A10 = A2 ** 10
    return {"q8_image_order": q8_group_order(),
            "fig8_A_order_infinite": A10 == sp.Matrix([[1, 10], [0, 1]]),
            "note": "finite image (Q8) -> reducible tower; dense image (fig-8) -> irreducible tower."}


# ----------------------------------------------------------------------------------------------------------------
# ITEM 4 -- intertwiner search (numpy): SL(3) phi-fixed locus appears entirely reducible. CONJECTURE.
# phi-fixed: g A g^-1 = A g^-1 A g, B = g^-1 A g. Fix A=diag(1,-1,-1); solve for g; classify <A,B>.
# ----------------------------------------------------------------------------------------------------------------
def _alg_dim_num(mats, n, tol=1e-7):
    basis, frontier = [np.eye(n, dtype=complex)], [np.eye(n, dtype=complex)]
    for _ in range(8):
        nf = []
        for M in frontier:
            for g in mats:
                nf.append(M @ g)
        cand = basis + nf
        flat = np.array([m.flatten() for m in cand])
        s = np.linalg.svd(flat, compute_uv=False)
        rank = int((s > tol * max(1.0, s[0])).sum())
        frontier = nf
        if rank == len(basis):                     # stabilised
            return rank
        basis = cand
        if rank == n * n:
            return n * n
    flat = np.array([m.flatten() for m in basis])
    s = np.linalg.svd(flat, compute_uv=False)
    return int((s > tol * max(1.0, s[0])).sum())


def phi_fixed_search_sl3(starts=60, seed=20260609, A_eigs=(1.0, -1.0, -1.0)):
    rng = np.random.default_rng(seed)
    A = np.diag(np.array(A_eigs, dtype=complex))
    n = 3

    def resid(v):
        g = (v[:9] + 1j * v[9:]).reshape(3, 3)
        try:
            gi = np.linalg.inv(g)
        except np.linalg.LinAlgError:
            return np.ones(18) * 1e3
        M = g @ A @ gi - A @ gi @ A @ g
        return np.concatenate([M.real.flatten(), M.imag.flatten()])

    from scipy.optimize import least_squares
    irreducible = 0
    converged = 0
    for _ in range(starts):
        v0 = rng.standard_normal(18)
        sol = least_squares(resid, v0, method="lm", max_nfev=400)
        if sol.cost > 1e-12:
            continue
        g = (sol.x[:9] + 1j * sol.x[9:]).reshape(3, 3)
        if abs(np.linalg.det(g)) < 1e-6:
            continue
        converged += 1
        B = np.linalg.inv(g) @ A @ g
        if _alg_dim_num([A, B], n) == 9:
            irreducible += 1
    return {"A_eigs": A_eigs, "starts": starts, "converged": converged, "irreducible_found": irreducible,
            "all_reducible": irreducible == 0}


def main():
    print("=" * 100)
    print("B141 -- split S031: phi-fixed REDUCIBLE (Q8) vs phi^2-geometric IRREDUCIBLE (dense fig-8)")
    print("=" * 100)

    print("\n[Item 1: the phi-fixed (0,0,0) rep is Q8; its Sym tower is reducible for n>=3]")
    print(f"    Q8 relations: {q8_relations()}")
    print(f"    group order: {q8_group_order()}  (Q8 = 8)")
    t = phi_fixed_tower_reducible()
    for n, r in t["rows"].items():
        print(f"      SL({n}) Sym^{n-1}: alg_dim={r['alg_dim']:>2}  n^2={r['n2']:>2}  {'IRRED' if r['irreducible'] else 'reducible'}")
    print(f"    reducible for all n>=3: {t['reducible_for_all_n_ge_3']}; irreducible only n=2: {t['irreducible_only_at_n2']}")
    print(f"    chi_Sym2 cross-check: {q8_sym2_character()}")

    print("\n[Item 2: the phi^2-geometric fig-8 tower is irreducible all n, in Q(sqrt-3)]")
    t2 = phi2_tower_irreducible()
    for n, r in t2["rows"].items():
        print(f"      SL({n}) Sym^{n-1}: alg_dim={r['alg_dim']:>2}  n^2={r['n2']:>2}  {'IRRED' if r['irreducible'] else 'red'}  traces in Q(sqrt-3): {r['traces_in_Q3']}")
    print(f"    irreducible all n: {t2['irreducible_all_n']}; all traces in Q(sqrt-3): {t2['all_traces_in_Q3']}")

    print("\n[Item 3: finiteness vs density]")
    print(f"    {finiteness_vs_density()}")

    print("\n[Item 4: SL(3) phi-fixed intertwiner search -- appears entirely reducible (CONJECTURE)]")
    s = phi_fixed_search_sl3()
    print(f"    A=diag(1,-1,-1): converged {s['converged']}/{s['starts']}, irreducible found {s['irreducible_found']} "
          f"-> all reducible: {s['all_reducible']}")


if __name__ == "__main__":
    main()
