r"""Are the cusp's RING class group and L113's RAY class group the same Z/2?

Two Z/2s were found from opposite directions:

  * RING class group of the order of conductor 4 -- the CUSP'S OWN LATTICE,
    Z + 4Z[omega] (this branch, from the boundary geometry);
  * RAY class group mod (4) of Q(sqrt-3) -- recorded by L113 from the BC/CMR
    question, i.e. from arithmetic, with no geometry involved.

Both are Z/2. This decides whether they are THE SAME Z/2.

METHOD. Since Cl(Q(sqrt-3)) = 1, both groups are quotients of (O_K/4)^*:

    Cl_4(K)   = (O_K/4)^* / image(O_K^*)                    [ray]
    Cl(O_4)   = (O_K/4)^* / < image(O_K^*), image((Z/4)^*) > [ring]

so they coincide exactly when (Z/4)^* lands inside the image of the unit group.
Everything is computed explicitly in Z[omega]/4 -- 16 elements, no formula
quoted, no table consulted.

Gate 5-Q. Structure only.
"""
import itertools

N = 4                                     # the modulus / conductor


# Z[omega]/4 as pairs (a, b) = a + b*omega, with omega^2 = -1 - omega
def mul(x, y):
    a, b = x
    c, d = y
    return ((a * c - b * d) % N, (a * d + b * c - b * d) % N)


ONE = (1, 0)
ALL = [(a, b) for a in range(N) for b in range(N)]


def is_unit(x):
    return any(mul(x, y) == ONE for y in ALL)


def generated(gens):
    """The subgroup of the unit group generated by gens."""
    S = {ONE}
    frontier = [ONE]
    while frontier:
        nxt = []
        for s in frontier:
            for g in gens:
                p = mul(s, g)
                if p not in S:
                    S.add(p)
                    nxt.append(p)
        frontier = nxt
    return S


def cosets(U, H):
    """Left cosets of H in U (U abelian, so left = right)."""
    seen, out = set(), []
    for u in U:
        if u in seen:
            continue
        c = frozenset(mul(u, h) for h in H)
        out.append(c)
        seen |= c
    return out


def main():
    print('THE TWO Z/2s — ring class vs ray class, at 4')
    print('=' * 62)

    U = [x for x in ALL if is_unit(x)]
    print(f'  |Z[omega]/4|      = {len(ALL)}')
    print(f'  |(Z[omega]/4)^*|  = {len(U)}')

    # the global units of Z[omega]: +-1, +-omega, +-omega^2 = -1-omega
    w = (0, 1)
    w2 = ((-1) % N, (-1) % N)
    units_K = [ONE, ((-1) % N, 0), w, ((0, -1)[0], (-1) % N), w2,
               ((1) % N, (1) % N)]
    UK = generated([w, ((-1) % N, 0)])          # <omega, -1> = all six units
    print(f'  image of O_K^* = <omega, -1>       : order {len(UK)}')
    assert len(UK) == 6, 'the six global units must stay distinct mod 4'

    # (Z/4)^* = {1, 3} embedded as rational integers
    RAT = generated([(3 % N, 0)])
    print(f'  image of (Z/4)^* = <3>             : order {len(RAT)}  {sorted(RAT)}')

    RAY = cosets(U, UK)
    BOTH = generated(list(UK) + list(RAT))
    RING = cosets(U, BOTH)

    print()
    print(f'  RAY class group  Cl_4(K)  = |U| / |O_K^*|        '
          f'= {len(U)}/{len(UK)} = {len(RAY)}')
    print(f'  RING class group Cl(O_4)  = |U| / |<O_K^*,(Z/4)^*>| '
          f'= {len(U)}/{len(BOTH)} = {len(RING)}')

    same = RAT.issubset(UK)
    print()
    print(f'  is (Z/4)^* contained in the image of O_K^* ?   {same}')
    print(f'    (Z/4)^* = {sorted(RAT)}  and  -1 = {((-1) % N, 0)} is a global unit)')
    print(f'  therefore <O_K^*, (Z/4)^*> = O_K^* ?          {BOTH == UK}')

    assert len(RAY) == 2 and len(RING) == 2
    assert BOTH == UK, 'the two subgroups must coincide'
    assert set(map(frozenset, RAY)) == set(map(frozenset, RING))

    print()
    print('  VERDICT: the ring class group of the cusp order and the ray class')
    print('  group mod (4) are THE SAME GROUP, not merely isomorphic --')
    print('  identical cosets. They coincide because (Z/4)^* = {+-1} is')
    print('  ALREADY inside the global units of Z[omega].')
    print()
    print('  So the Z/2 the boundary geometry produces and the Z/2 L113 found')
    print('  from the BC/CMR side are ONE Z/2, reached from two directions.')
    print('=' * 62)


if __name__ == '__main__':
    main()
