#!/usr/bin/env python3
"""B739 Stage B recompute -- target WALL-1 (docs/LAW_MAP.md #E entry 1).

BANKED KILL (the claim killed): "the solo object yields no Standard-Model
value (masses/mixings/couplings) by itself" -- the hardened top-level
negative (wall 1).  Stage A found fact_basis = asserted: the row itself
attaches NO computation; it is an umbrella leaning on the corpus
(same-section walls 9/10/11 + B307): the equivariance wall (B650/B644),
the dimensionful no-go (B660/S3 upgraded by B666 cell S), the
kind-mismatch (B706/B704/B730), the generation wall (B307).

E19 (compute-not-cite, both directions): this script RE-DERIVES the
umbrella's discriminating conjunction in-sandbox from the cited arcs' own
declared conventions, as independent computations (fresh implementations,
not re-runs of the original artifacts).

THE DISCRIMINATING FACT: an "SM value" is (a) dimensionful (mass, VEV,
dimensionful coupling), (b) a continuous dimensionless parameter (mixing
angle, coupling), or (c) a generation-symmetric value structure.  The
kill holds iff every kind is barred by mechanism:
  LEG 1 (bars (a)): each of the six banked solo-output stabilizers is
     FINITE with finite-torsion abelianization => Hom(G, R_+) = {1}
     (the scale group R_+ is torsion-free): no dimensionful value is
     equivariantly emittable.  [#E wall 10; B666 cell S's declared list:
     Gal(L/Q(i)) = V4, 2I = SL(2,5), PSL(2,7), 2I x Z/3, SL(2,Z/15), W(E6).]
  LEG 2 (bars linear value transport): the Sylvester intertwiner
     T.A1 = M_hear.T has ONLY T = 0 -- disjoint spectra (hyperbolic
     phi^{+-2} off the unit circle vs the order-10 congruence shadow on
     it).  [#E wall 9; B650 W2-G1: A1 eigenvalues phi^{+-2}; target
     tr = -1/phi, det = 1, order 10.  Computed for BOTH members of the
     golden Galois pair of order-10 targets (tr = -1/phi and tr = +phi,
     the B674 lift), so the wall is realization-independent.]
  LEG 3 (bars (b)): the solo object's total value-selecting freedom is a
     FINITE F2-space (the multiquadratic seam; forced faces {-3, 5, -15}
     = V4, full seam basis {-3, 5, -7} => (F_2)^3, 8 points, exponent 2)
     -- a finite discrete set carries no continuous real parameter.
     [#E wall 11 / B706 rung 2 + B704/B730.]
  LEG 4 (bars (c)): no hyperbolic knot has a C3 (cyclic cubic) trace
     field -- a Galois cubic has odd group order, so complex conjugation
     is trivial and the field is totally real, while a hyperbolic trace
     field has a complex place; the object's own shape field, recomputed
     from the gluing equation, is Q(sqrt-3): degree 2, signature (0,1).
     [B307; Neumann-Reid shape field = invariant trace field, the banked
     convention of LAW_MAP section C row 1.]
  LEG 5 (revival-hypothesis check, B735 emittance/spectral face -- the
     face no pre-B735 negative consulted): the banked heartbeat traces
     (3+-sqrt(-3))/2 and 1+-sqrt(-3) are algebraic INTEGERS generating
     the SAME being field Q(sqrt-3) -- the new face opens no new
     value-channel kind (and Gate 5 bars SM values on any face).

CONVENTIONS DECLARED (E1) where the arcs left them implicit:
  * A1 = [[2,1],[1,1]] (the cat map: tr 3, det 1, disc 5 -- the corpus's
    disc(A1) = 5 monodromy).  Conjugation-invariant conclusions.
  * The order-10 targets realized as COMPANION matrices of their banked
    invariants (tr = -1/phi and tr = +phi, det = 1); order 10 VERIFIED,
    not assumed.
  * SL(2,Z/n) generated by S = [[0,-1],[1,0]], T = [[1,1],[0,1]]
    (SL(2,Z) surjects; standard).  2I = SL(2,F5) (B640/B699).
  * W(E6) = reflection group in the simple-root basis of the Bourbaki E6
    Cartan matrix; W^ab derived from det-surjectivity + all-generators-
    conjugate (every E6 bond has m = 3), not assumed.
  * V4 = Gal(L/Q(i)) realized by the banked B662-cellD automorphisms
    sigma: s -> -s, tau: s -> 4i/s.
  * Derived subgroups = normal closure of generator commutators
    (equals [G,G]: the quotient by it is abelian, and it sits in [G,G]).
  * Fig-8 gluing (Thurston two-tetrahedron, both shapes equal):
    completeness equation (z(1-z))^2 = 1, Im z > 0.
  * Cyclic cubic instances derived in-script from Gaussian periods
    (conductors 7, 9, 13); Galois-ness read off disc = square.
  * "Every solo output is stabilized by a finite/profinite structure" is
    the cited arcs' own theorem-by-assembly premise (B666 cell S); the
    six declared instances are recomputed exactly, not the universal
    quantifier over unenumerated outputs.

GATE 5 absolute: no SM quantity appears anywhere below -- only
impossibility structure (orders, exponents, resultants, nullspaces,
minimal polynomials).  Deterministic: no wall-clock, no randomness,
no network, no snappy dependency.
"""

import sys
from math import lcm

import sympy as sp
from sympy import sqrt

FAILURES = []
NCHECKS = 0


def check(label, ok, extra=""):
    global NCHECKS
    NCHECKS += 1
    tag = "PASS" if ok else "FAIL"
    if not ok:
        FAILURES.append(label)
    print(f"  [{tag}] {label}" + (f"  {extra}" if extra else ""))
    return ok


def log(msg=""):
    print(msg)


# ----------------------------------------------------------------------
# generic finite-group machinery (independent implementation)
# ----------------------------------------------------------------------

def bfs_group(gens, mul, ident):
    """Subgroup generated by gens: closure of {e} under right
    multiplication (finite group: positive words contain inverses)."""
    seen = {ident}
    frontier = [ident]
    while frontier:
        nxt = []
        for a in frontier:
            for g in gens:
                b = mul(a, g)
                if b not in seen:
                    seen.add(b)
                    nxt.append(b)
        frontier = nxt
    return seen


def elem_order(a, mul, ident):
    k, b = 1, a
    while b != ident:
        b = mul(b, a)
        k += 1
    return k


def elem_inv(a, mul, ident):
    b = ident
    for _ in range(elem_order(a, mul, ident) - 1):
        b = mul(b, a)
    return b


def derived_subgroup(gens, mul, ident):
    """[G,G] = normal closure of {[g_i, g_j]}.  Conjugation closure by
    generators suffices (conj by g^-1 = an iterate of conj by g on a
    finite conj-closed set)."""
    ginv = {g: elem_inv(g, mul, ident) for g in gens}
    seed = set()
    for a in gens:
        for b in gens:
            c = mul(mul(a, b), mul(ginv[a], ginv[b]))
            if c != ident:
                seed.add(c)
    if not seed:
        return {ident}
    while True:
        D = bfs_group(sorted(seed), mul, ident)
        new = {c for h in D for g in gens
               if (c := mul(mul(g, h), ginv[g])) not in D}
        if not new:
            return D
        seed |= new


def abelianization(G, gens, mul, D):
    """(|G^ab|, exponent(G^ab)); abelian exponent = lcm of generator
    orders in G/[G,G]."""
    n_ab = len(G) // len(D)
    exps = []
    for g in gens:
        k, b = 1, g
        while b not in D:
            b = mul(b, g)
            k += 1
        exps.append(k)
    return n_ab, (lcm(*exps) if exps else 1)


def scale_hom_trivial(name, exp_ab):
    """Hom(G, R_+) factors through G^ab; x^e = 1 over positive reals
    has only x = 1."""
    xx = sp.symbols("xx", positive=True)
    sols = sp.solveset(xx**exp_ab - 1, xx,
                       domain=sp.Interval.open(0, sp.oo))
    return check(f"{name}: x^{exp_ab} = 1 over R_+ only at x = 1  "
                 f"=>  Hom(G, R_+) = {{1}}", sols == sp.FiniteSet(1))


def mat2_mul_mod(n):
    def mul(X, Y):
        (a, b), (c, d) = X
        (e, f), (g, h) = Y
        return (((a * e + b * g) % n, (a * f + b * h) % n),
                ((c * e + d * g) % n, (c * f + d * h) % n))
    return mul


ID2 = ((1, 0), (0, 1))


def sl2_gens(n):
    return ((0, n - 1), (1, 0)), ((1, 1), (0, 1))


# ======================================================================
log("=" * 72)
log("B739 Stage B recompute -- WALL-1 (LAW_MAP #E entry 1: 'No SM value")
log("from the solo object').  Compute-not-cite, both directions (E19).")
log(f"python {sys.version.split()[0]}, sympy {sp.__version__}")
log("=" * 72)

# ----------------------------------------------------------------------
log("\nLEG 1 -- the scale-torsor no-go (#E wall 10; B660/S3 + B666 cell S)")
log("-" * 72)

# A. Gal(L/Q(i)) via the banked automorphisms
log("A. Gal(L/Q(i)) -- banked B662-cellD: sigma: s->-s, tau: s->4i/s")
s = sp.symbols("s")


def compose(f, g):
    return sp.cancel(f.subs(s, g))


idm, sig, tau = s, -s, 4 * sp.I / s
sigtau = compose(sig, tau)
elems4 = [idm, sig, tau, sigtau]
closure_ok = all(
    any(sp.cancel(compose(f, g) - e) == 0 for e in elems4)
    for f in elems4 for g in elems4)
check("closure of {id, sigma, tau, sigma.tau} under composition", closure_ok)
check("sigma^2 = tau^2 = (sigma.tau)^2 = id and sigma.tau = tau.sigma",
      all(sp.cancel(compose(f, f) - idm) == 0 for f in (sig, tau, sigtau))
      and sp.cancel(compose(sig, tau) - compose(tau, sig)) == 0)
check("|G| = 4 noncyclic => Klein four; G^ab = (Z/2)^2, exponent 2",
      len(set(map(sp.srepr, map(sp.cancel, elems4)))) == 4)
scale_hom_trivial("Gal(L/Q(i)) = V4", 2)

# B. 2I = SL(2,5)
log("\nB. 2I = SL(2,5) -- the hearing image ker(det) (B640/B644)")
mul5 = mat2_mul_mod(5)
S5, T5 = sl2_gens(5)
G5 = bfs_group([S5, T5], mul5, ID2)
D5 = derived_subgroup([S5, T5], mul5, ID2)
n_ab, e_ab = abelianization(G5, [S5, T5], mul5, D5)
check("|SL(2,5)| = 120; PERFECT: |[G,G]| = 120, G^ab trivial",
      len(G5) == 120 and len(D5) == 120 and (n_ab, e_ab) == (1, 1),
      f"|G|={len(G5)}, |[G,G]|={len(D5)}, |G^ab|={n_ab}, exp={e_ab}")
scale_hom_trivial("2I = SL(2,5)", e_ab)

# C. PSL(2,7)
log("\nC. PSL(2,7) -- the kappa=14 stage shadow (B646 / B666 cell 3)")
mul7 = mat2_mul_mod(7)


def canon7(M):
    (a, b), (c, d) = M
    return min(M, (((-a) % 7, (-b) % 7), ((-c) % 7, (-d) % 7)))


def mulp7(X, Y):
    return canon7(mul7(X, Y))


S7, T7 = (canon7(m) for m in sl2_gens(7))
IDP7 = canon7(ID2)
G7 = bfs_group([S7, T7], mulp7, IDP7)
D7 = derived_subgroup([S7, T7], mulp7, IDP7)
n_ab, e_ab = abelianization(G7, [S7, T7], mulp7, D7)
check("|PSL(2,7)| = 168; PERFECT: |[G,G]| = 168, G^ab trivial",
      len(G7) == 168 and len(D7) == 168 and (n_ab, e_ab) == (1, 1),
      f"|G|={len(G7)}, |[G,G]|={len(D7)}, |G^ab|={n_ab}, exp={e_ab}")
scale_hom_trivial("PSL(2,7)", e_ab)

# D. 2I x Z/3
log("\nD. 2I x Z/3 -- the full level-15 hearing image im(rho) (B640)")


def mulD(X, Y):
    return (mul5(X[0], Y[0]), (X[1] + Y[1]) % 3)


gensD = [(S5, 0), (T5, 0), (ID2, 1)]
IDD = (ID2, 0)
GD = bfs_group(gensD, mulD, IDD)
DD = derived_subgroup(gensD, mulD, IDD)
n_ab, e_ab = abelianization(GD, gensD, mulD, DD)
check("|2I x Z/3| = 360; [G,G] = 2I x {0} (120); G^ab = Z/3, exponent 3",
      len(GD) == 360 and len(DD) == 120 and (n_ab, e_ab) == (3, 3),
      f"|G|={len(GD)}, |[G,G]|={len(DD)}, |G^ab|={n_ab}, exp={e_ab}")
scale_hom_trivial("2I x Z/3", e_ab)

# E. SL(2,Z/15)
log("\nE. SL(2,Z/15) -- the mod-conductor shadow group (B640)")
mul15 = mat2_mul_mod(15)
S15, T15 = sl2_gens(15)
G15 = bfs_group([S15, T15], mul15, ID2)
D15 = derived_subgroup([S15, T15], mul15, ID2)
n_ab, e_ab = abelianization(G15, [S15, T15], mul15, D15)
check("|SL(2,Z/15)| = 2880 = 24*120; |[G,G]| = 960; G^ab = Z/3, exp 3",
      len(G15) == 2880 and len(D15) == 960 and (n_ab, e_ab) == (3, 3),
      f"|G|={len(G15)}, |[G,G]|={len(D15)}, |G^ab|={n_ab}, exp={e_ab}")
scale_hom_trivial("SL(2,Z/15)", e_ab)

# F. W(E6)
log("\nF. W(E6) -- reflections in the simple-root basis (Bourbaki E6)")
E6_EDGES = [(0, 2), (1, 3), (2, 3), (3, 4), (4, 5)]
N = 6
C = [[2 if i == j else 0 for j in range(N)] for i in range(N)]
for (i, j) in E6_EDGES:
    C[i][j] = C[j][i] = -1


def reflection(i):
    rows = []
    for k in range(N):
        if k != i:
            rows.append(tuple(1 if j == k else 0 for j in range(N)))
        else:
            rows.append(tuple(-1 if j == i else -C[j][i] for j in range(N)))
    return tuple(rows)


def mat6_mul(A, B):
    Bcols = tuple(zip(*B))
    return tuple(tuple(sum(a * b for a, b in zip(row, col))
                       for col in Bcols) for row in A)


ID6 = tuple(tuple(1 if i == j else 0 for j in range(N)) for i in range(N))
gens6 = [reflection(i) for i in range(N)]
check("each s_i is an involution (6/6)",
      all(mat6_mul(g, g) == ID6 for g in gens6))
seen = {ID6: 1}
frontier = [ID6]
while frontier:
    nxt = []
    for a in frontier:
        da = seen[a]
        for g in gens6:
            b = mat6_mul(a, g)
            if b not in seen:
                seen[b] = -da
                nxt.append(b)
    frontier = nxt
n_plus = sum(1 for d in seen.values() if d == 1)
check("|W(E6)| = 51840 with det split 25920 / 25920 (det surjective)",
      len(seen) == 51840 and n_plus == 25920,
      f"|W|={len(seen)}, det=+1: {n_plus}, det=-1: {len(seen) - n_plus}")
conj_ok = all(
    mat6_mul(mat6_mul(mat6_mul(gens6[i], gens6[j]), gens6[i]),
             mat6_mul(gens6[j], gens6[i])) == gens6[j]
    for (i, j) in E6_EDGES)
check("(s_i s_j) s_i (s_i s_j)^-1 = s_j exactly on all 5 bonds (m = 3)",
      conj_ok)
comp, stack = {0}, [0]
adj = {k: set() for k in range(N)}
for (i, j) in E6_EDGES:
    adj[i].add(j)
    adj[j].add(i)
while stack:
    v = stack.pop()
    for w in adj[v]:
        if w not in comp:
            comp.add(w)
            stack.append(w)
check("E6 diagram connected => all 6 generators conjugate => W^ab cyclic,"
      " gen by an involution; det >= 2 => W^ab = Z/2, exponent 2",
      comp == set(range(N)))
scale_hom_trivial("W(E6)", 2)

log("\nLEG 1 CONCLUSION: six/six banked stabilizers finite, G^ab torsion")
log("(orders 4, 120, 168, 360, 2880, 51840; |G^ab| = 4, 1, 1, 3, 3, 2):")
log("Hom(G, R_+) = {1} in every case.  The sign channel exists (det:")
log("W(E6) ->> {+-1} -- the banked sign laws) but the SCALE channel is")
log("exactly zero: no mass, VEV, or dimensionful coupling is emittable.")

# ----------------------------------------------------------------------
log("\nLEG 2 -- the equivariance wall (#E wall 9; B650 W2-G1)")
log("-" * 72)
phi = (1 + sqrt(5)) / 2
x = sp.symbols("x")
A1 = sp.Matrix([[2, 1], [1, 1]])
f = x**2 - 3 * x + 1
check("A1 = [[2,1],[1,1]]: tr 3, det 1, disc = 5; spec = {phi^2, phi^-2}",
      A1.trace() == 3 and A1.det() == 1
      and sp.simplify(f.subs(x, phi**2)) == 0
      and sp.simplify(f.subs(x, phi**-2)) == 0)
check("|phi^{+-2}| != 1 (hyperbolic, off the unit circle)",
      float(phi**2) > 1 and 0 < float(phi**-2) < 1,
      f"phi^2 = {float(phi**2):.11f}, phi^-2 = {float(phi**-2):.11f}")


def sylvester_wall(tr_target, label, res_expected):
    log(f"\n  target {label}: companion of x^2 - ({sp.radsimp(tr_target)})x + 1")
    M = sp.Matrix([[0, -1], [1, sp.radsimp(tr_target)]])
    check(f"{label}: trace and det match the banked invariants",
          sp.simplify(M.trace() - tr_target) == 0
          and sp.simplify(M.det()) == 1)
    m5 = sp.simplify(M**5)
    m10 = sp.simplify(M**10)
    smaller = [k for k in range(1, 10) if sp.simplify(M**k) == sp.eye(2)]
    check(f"{label}: M^5 = -I, M^10 = I, no smaller power = I "
          f"=> order EXACTLY 10",
          m5 == -sp.eye(2) and m10 == sp.eye(2) and smaller == [])
    disc = sp.radsimp(tr_target**2 - 4)
    check(f"{label}: disc = tr^2 - 4 < 0 with det 1 => non-real "
          f"unit-circle pair", disc.evalf() < 0, f"disc = {disc}")
    g = sp.expand(x**2 - tr_target * x + 1)
    res = sp.radsimp(sp.resultant(f, g, x))
    check(f"{label}: Res(char A1, char M) = {sp.radsimp(res_expected)} != 0 "
          f"(spectra DISJOINT)",
          sp.simplify(res - res_expected) == 0 and res != 0,
          f"numerically {float(res):.9f}")
    t = sp.symbols("t0 t1 t2 t3")
    T = sp.Matrix(2, 2, t)
    eqs = [sp.expand(e) for e in (T * A1 - M * T)]
    Mc, rhs = sp.linear_eq_to_matrix(eqs, list(t))
    detM = sp.radsimp(Mc.det())
    sol = sp.linsolve((Mc, rhs), list(t))
    check(f"{label}: |det(Sylvester operator)| = Res != 0 and the ONLY "
          f"solution of T.A1 = M.T is T = 0",
          (sp.simplify(detM - res) == 0 or sp.simplify(detM + res) == 0)
          and sol == sp.FiniteSet((0, 0, 0, 0)),
          f"det = {detM}, solutions = {sol}")
    return res


res_hear = sylvester_wall(-1 / phi, "rho_hear(RL) [B650: tr = -1/phi]",
                          5 * phi**2)
res_lift = sylvester_wall(phi, "sigma(A1) lift [B674: tr = +phi]",
                          5 * phi**-2)
check("Galois-pair product: Res(-1/phi-target) * Res(+phi-target) = 25 "
      "= disc(A1)^2",
      sp.simplify(res_hear * res_lift - 25) == 0)

log("\nLEG 2 CONCLUSION: T = 0 is the unique equivariant map for BOTH")
log("order-10 golden targets (Res = 5 phi^2 and 5 phi^-2, product 25):")
log("no nonzero linear monodromy-equivariant classical -> stage map")
log("exists; no linear channel transports a solo value across.")

# ----------------------------------------------------------------------
log("\nLEG 3 -- the kind mismatch (#E wall 11; B706 rung 2 + B704/B730)")
log("-" * 72)


def sqfree_kernel(n):
    sign = -1 if n < 0 else 1
    k = 1
    for p, e in sp.factorint(abs(n)).items():
        if e % 2:
            k *= p
    return sign * k


def is_fund_disc(d):
    if d % 4 == 1:
        return sp.ntheory.factor_.core(abs(d), 2) == abs(d)
    if d % 4 == 0:
        m = d // 4
        return (sp.ntheory.factor_.core(abs(m), 2) == abs(m)
                and m % 4 in (2, 3))
    return False


check("-3, 5, -15 all fundamental discriminants; (-3)(5) = -15 mod squares",
      all(is_fund_disc(d) for d in (-3, 5, -15))
      and sqfree_kernel(-15) == -15 and sqfree_kernel(-3 * 5) == -15)
v4 = {1, -3, 5, -15}
check("{1, -3, 5, -15} closed under multiplication mod squares "
      "=> the forced faces = V4 (4 points, exponent 2)",
      all(sqfree_kernel(a * b) in v4 for a in v4 for b in v4))
prods = {"-3": -3, "5": 5, "-7": -7, "(-3)(5)": -15, "(-3)(-7)": 21,
         "(5)(-7)": -35, "(-3)(5)(-7)": 105}
check("seam basis {-3, 5, -7} F2-independent: 7/7 subset products "
      "nonsquare => seam = (F_2)^3: 8 points, exponent 2",
      all(sqfree_kernel(v) != 1 for v in prods.values()),
      f"kernels = { {k: sqfree_kernel(v) for k, v in prods.items()} }")
scale_hom_trivial("the seam (F_2)^3", 2)
check("8 = |F_2^3| is exceeded by 9 distinct rationals 1/2..1/10 in (0,1)"
      " => no surjection of the seam onto ANY real interval",
      len({sp.Rational(1, m) for m in range(2, 11)}) == 9 and 9 > 8)

log("\nLEG 3 CONCLUSION: the solo object's entire value-selecting freedom")
log("is 3 F2-bits (8 points, exponent 2): dimension-0 discrete.  The SM")
log("freedom is a continuous ~19-26-real-parameter moduli space (B706's")
log("banked COUNT -- cited structure, no SM value computed, Gate 5).")
log("A finite discrete space carries no continuous parameter: KIND")
log("mismatch recomputed.")

# ----------------------------------------------------------------------
log("\nLEG 4 -- the generation wall (B307): no C3 trace field")
log("-" * 72)
cases = [
    ("conductor 7 (Q(zeta7)+)", 2 * sp.cos(2 * sp.pi / 7)),
    ("conductor 9 (Q(zeta9)+)", 2 * sp.cos(2 * sp.pi / 9)),
    ("conductor 13 (Gaussian period)",
     2 * sp.cos(2 * sp.pi / 13) + 2 * sp.cos(10 * sp.pi / 13)),
]
for name, gen in cases:
    p = sp.minimal_polynomial(gen, x)
    d = sp.discriminant(p, x)
    nreal = len(sp.real_roots(p))
    check(f"C3 instance {name}: minpoly {p}, disc {d} = {sp.sqrt(d)}^2 "
          f"(square => Galois C3), {nreal}/3 real roots => TOTALLY REAL",
          sp.Poly(p, x).degree() == 3 and int(sp.sqrt(d))**2 == d
          and nreal == 3)
pc = x**3 - x**2 + 1
check("control (5_2's cubic) x^3 - x^2 + 1: disc -23 nonsquare (S3), "
      "1 real root => signature (1,1), NOT C3",
      sp.discriminant(pc, x) == -23 and len(sp.real_roots(pc)) == 1)
log("  lemma: |Gal| = 3 is odd => complex conjugation (order 2) is")
log("  trivial => every C3 field is totally real; a hyperbolic trace")
log("  field has a complex place => NO hyperbolic knot has a C3 field.")
z = sp.symbols("z")
sols = sp.solve(z**2 * (1 - z)**2 - 1, z)
zpos = [w for w in sols if sp.im(w).evalf() > 0]
z0 = sp.simplify(zpos[0]) if len(zpos) == 1 else None
pz = sp.minimal_polynomial(z0, x) if z0 is not None else None
check("fig-8 gluing (z(1-z))^2 = 1: unique Im>0 solution z = e^{i pi/3},"
      " minpoly z^2 - z + 1, disc -3 => shape field Q(sqrt-3), degree 2,"
      " signature (0,1) -- complex place, degree != 3: not C3",
      z0 is not None and sp.expand(pz - (x**2 - x + 1)) == 0
      and sp.discriminant(pz, x) == -3
      and sp.simplify(z0 - sp.exp(sp.I * sp.pi / 3).rewrite(sp.cos)) == 0)

log("\nLEG 4 CONCLUSION: the C3 route to three symmetric generations is")
log("closed for every hyperbolic knot, and the object's own shape field")
log("(= invariant trace field, Neumann-Reid) is Q(sqrt-3): disc -3.")

# ----------------------------------------------------------------------
log("\nLEG 5 -- revival-hypothesis check (B735 emittance/spectral face)")
log("-" * 72)
hb = [((3 + sqrt(-3)) / 2, x**2 - 3 * x + 3),
      (1 + sqrt(-3), x**2 - 2 * x + 4)]
for val, expected in hb:
    p = sp.minimal_polynomial(val, x)
    d = sp.discriminant(p, x)
    check(f"heartbeat trace {val}: minpoly {p} monic-integer "
          f"(algebraic INTEGER), disc {d}, kernel {sqfree_kernel(d)} "
          f"=> generates Q(sqrt-3) = the BEING field",
          sp.expand(p - expected) == 0 and sqfree_kernel(d) == -3)
log("  => the newly-consulted spectral face's banked arithmetic lands in")
log("     Z[omega] inside the being field already consulted: no new")
log("     value-channel KIND appears (legs 1-3 quantify over stabilizer/")
log("     seam structure, which the emittance face shares -- B735 'same")
log("     walls'); Gate 5 bars SM comparison on any face regardless.")

# ----------------------------------------------------------------------
log("\n" + "=" * 72)
log("ASSEMBLY -- the umbrella's discriminating conjunction")
log("=" * 72)
log("""dimensionful values  -> LEG 1 (Hom(G, R_+) = {1}, six/six exact)
linear transport     -> LEG 2 (T = 0 unique, both Galois targets)
continuous params    -> LEG 3 (freedom = 3 F2-bits, dimension 0)
generation structure -> LEG 4 (no C3 trace field; object's field Q(sqrt-3))
spectral-face revival-> LEG 5 (same being field, no new kind)
""")
npass = NCHECKS - len(FAILURES)
log(f"CHECKS: {npass}/{NCHECKS} PASS" if not FAILURES
    else f"CHECKS: {npass}/{NCHECKS} PASS; FAILURES = {FAILURES}")
if FAILURES:
    log("VERDICT SIGNAL: REVIVED-candidate (some discriminating fact "
        "failed to recompute).")
    sys.exit(1)
log("VERDICT SIGNAL: RECONFIRMED -- every leg of the umbrella's")
log("discriminating fact recomputes TRUE from the arcs' own declared")
log("conventions: no Standard-Model value (mass / mixing / coupling) is")
log("derivable from the solo object.")
