"""
B774 Stage B -- cell CP-169-cpsign
CP-sign from a theta-odd, conjugation-SENSITIVE holonomy pairing.

SOURCE NEGATIVE (banked, OI-169 / B289): the CP sign is a forced LAW
    CS(p,-q) = -CS(p,q), every closing chiral, amphichiral locus empty; BUT
    WHICH sign is external / not object-derivable, because the cusped object is
    amphichiral (CS=0) and CP-symmetric: it delivers +-pi/6 symmetrically via
    the Gal(Q(sqrt-3)/Q) swap u <-> u^2.  That computation lives at the TRACE /
    abelianized level: kappa = tr[a,b] = u^2+2, CS = a real (mod 1) trace-field
    invariant.  The sign it leaves free is the choice of complex-conjugate
    (Galois) root -- i.e. an ABELIAN datum.

THE CHORD ANALOG (this cell): recompute the CP sign from a theta-odd,
    conjugation-SENSITIVE holonomy pairing rather than the swap-symmetric trace
    magnitude.  Direct test of the standing crux "can c be carried into theta":
    is the sign the trace computation leaves free actually FIXED once the
    theta-odd / non-abelian sector is exposed?

    c    = complex conjugation / orientation / the ω <-> ω^2 Galois swap  (the CP sign)
    theta= Out(E6) = the 27 <-> 27bar swap = the hyperelliptic involution   (a <-> a^-1, b <-> b^-1)

METHOD -- two structurally-different in-cell paths:

  PATH A (SL(2) character level).  The CP-sign discriminant is tr(ab) =
    (5 -+ sqrt-3)/2 at the two Galois roots u = omega, omega^2 -- a TRACE, hence
    an ABELIAN / character datum, moved by c.  The candidate chord involution
    theta = (a,b) -> (a^-1, b^-1) FIXES every trace coordinate of the SL(2)
    character variety (verified over a word set).  Since the SL(2) character
    ring is generated by traces, theta acts trivially on everything the CP-sign
    question can see at SL(2) level.  There is NO SL(2)-level theta-odd invariant
    at all (Out(SL2)=1).  The CP sign is a pure c-datum; theta is inert on it.

  PATH B (E6 27-rep -- the genuine theta-odd sector).  A genuine theta-odd
    object requires Out(E6)=Z/2 (27 != 27bar).  Promote the holonomy through the
    principal SL(2) c-> E6, restrict the 27:  27 |_{principal SL2} = V17 (+) V9 (+) V1
    (dims 17+9+1 = 27).  Every SL(2)-irrep is self-dual, so 27|_{SL2} ~ (27bar)|_{SL2}:
    the holonomy is VECTOR-LIKE under theta (AP4, the fifth wall).  We compute the
    space of SL(2)-invariant bilinear forms on 27 o rho directly and split it by
    symmetry:  theta-EVEN = symmetric forms, theta-ODD = antisymmetric forms.
    If the theta-ODD invariant space is 0-dimensional, no theta-odd holonomy
    pairing exists -- the theta-odd sector cannot fix the CP sign.  Computed at
    BOTH CP signs (u = omega and omega^2) to confirm theta does not distinguish them.

  W4-304 OVERTURN SIGNATURE (the one thing that would overturn):  a par/trace
    ZERO that decomposes as even = odd CANCELLATION with a NONZERO theta-odd
    piece.  The amphichiral quantity here is the invariant antisymmetric
    (theta-odd) pairing on 27 o rho.  If it is nonzero -> overturn.  We compute it.

ENV: pyenv python3 (sympy + numpy). Re-runnable. Writes output.txt + results.json.
"""

import os
import json
from math import comb

import numpy as np
import sympy as sp

lines = []
def p(s=""):
    lines.append(str(s))
    print(s)


# --------------------------------------------------------------------------- #
# The figure-eight (m004) holonomy: Riley form.
#   a = [[1,1],[0,1]],  b = [[1,0],[-u,1]],  u = shape (Riley root).
#   Complete hyperbolic structure: u = omega = e^{2 pi i/3}, trace field Q(sqrt-3).
#   The two CP signs = the two Galois-conjugate roots u = omega, omega^2.
# --------------------------------------------------------------------------- #
def sl2(u_val):
    a = np.array([[1.0, 1.0], [0.0, 1.0]], dtype=complex)
    b = np.array([[1.0, 0.0], [-u_val, 1.0]], dtype=complex)
    return a, b


def sym_power(M, k):
    """Sym^k of a 2x2 matrix M (the (k+1)-dim SL(2) irrep V_{k+1}).
    Basis monomials e_j = x^{k-j} y^j, j=0..k; M sends x->p x + r y, y->q x + s y."""
    p_, q_, r_, s_ = M[0, 0], M[0, 1], M[1, 0], M[1, 1]
    dim = k + 1
    R = np.zeros((dim, dim), dtype=complex)
    for j in range(dim):                      # input monomial x^{k-j} y^j
        for m in range(k - j + 1):            # (p x + r y)^{k-j}
            for n in range(j + 1):            # (q x + s y)^{j}
                yexp = m + n                  # power of y in the image term = row index
                coef = (comb(k - j, m) * (p_ ** (k - j - m)) * (r_ ** m)
                        * comb(j, n) * (q_ ** (j - n)) * (s_ ** n))
                R[yexp, j] += coef
    return R


def block_diag(*mats):
    n = sum(m.shape[0] for m in mats)
    out = np.zeros((n, n), dtype=complex)
    i = 0
    for m in mats:
        d = m.shape[0]
        out[i:i + d, i:i + d] = m
        i += d
    return out


def rep27(M):
    """27 |_{principal SL2} = V17 (+) V9 (+) V1 = Sym^16 (+) Sym^8 (+) Sym^0."""
    return block_diag(sym_power(M, 16), sym_power(M, 8), sym_power(M, 0))


def sym_power_exact(M, k):
    """Exact sympy Sym^k of a 2x2 sympy Matrix M (dim k+1)."""
    p_, q_, r_, s_ = M[0, 0], M[0, 1], M[1, 0], M[1, 1]
    dim = k + 1
    R = sp.zeros(dim, dim)
    for j in range(dim):
        for m in range(k - j + 1):
            for n in range(j + 1):
                yexp = m + n
                coef = (comb(k - j, m) * (p_ ** (k - j - m)) * (r_ ** m)
                        * comb(j, n) * (q_ ** (j - n)) * (s_ ** n))
                R[yexp, j] += coef
    return sp.expand(R)


def block_invariant_form(k, a_gen, b_gen):
    """The SL(2)-invariant bilinear form on Sym^k (1-dim), constructed as the
    antidiagonal J[i, k-i] = (-1)^i (the k-th power of the epsilon form).  Verifies
    g^T J g = J EXACTLY for g = Sym^k(a), Sym^k(b) at the given SL(2) generators.
    Returns (is_invariant, is_symmetric).  Symmetry parity is (-1)^k (theta-even iff k even)."""
    n = k + 1
    J = sp.zeros(n, n)
    for i in range(n):
        # invariant pairing on Sym^k from <u^k,v^k> = <u,v>^k : antidiagonal, binomial-normalized
        J[i, n - 1 - i] = sp.Integer((-1) ** i) * sp.Rational(1, comb(k, i))
    Ra = sym_power_exact(a_gen, k)
    Rb = sym_power_exact(b_gen, k)
    inv_a = sp.expand(Ra.T * J * Ra - J) == sp.zeros(n, n)
    inv_b = sp.expand(Rb.T * J * Rb - J) == sp.zeros(n, n)
    is_symmetric = sp.expand(J - J.T) == sp.zeros(n, n)
    return bool(inv_a and inv_b), bool(is_symmetric)


def main():
    results = {"cell": "CP-169-cpsign",
               "source_wall": "OI-169 / B289 CP-sign law (trace/abelianized level)",
               "chord_analog": "recompute the CP sign from a theta-odd, conjugation-sensitive holonomy pairing"}

    p("=" * 78)
    p("CP-169-cpsign  --  CP sign from a theta-odd conjugation-sensitive holonomy pairing")
    p("=" * 78)

    # ===================================================================== #
    # PATH A -- the CP-sign discriminant is an ABELIAN (trace) datum; theta inert
    # ===================================================================== #
    p("\n[PATH A]  SL(2) character level: the CP sign is a TRACE (abelian) datum;")
    p("          the theta involution (a,b)->(a^-1,b^-1) fixes every trace.")

    u = sp.symbols('u')
    a = sp.Matrix([[1, 1], [0, 1]])
    b = sp.Matrix([[1, 0], [-u, 1]])
    omega = sp.Rational(-1, 2) + sp.sqrt(-3) / 2      # e^{2 pi i /3}
    omega2 = sp.Rational(-1, 2) - sp.sqrt(-3) / 2     # conjugate root

    tr_ab = sp.expand(sp.trace(a * b))               # = 2 - u
    disc_plus = sp.nsimplify(sp.simplify(tr_ab.subs(u, omega)))
    disc_minus = sp.nsimplify(sp.simplify(tr_ab.subs(u, omega2)))
    p(f"    tr(ab) = {tr_ab}")
    p(f"    at u=omega  (CP sign +): tr(ab) = {disc_plus}")
    p(f"    at u=omega2 (CP sign -): tr(ab) = {disc_minus}")
    # min poly of tr(ab): t^2 - 5 t + 7 (disc -3) -- the B289 Galois pair
    t = sp.symbols('t')
    minpoly = sp.minimal_polynomial(disc_plus, t)
    p(f"    min poly of tr(ab): {minpoly}   (Galois pair over Q(sqrt-3), disc = "
      f"{sp.discriminant(minpoly, t)})")
    cp_discriminant_is_trace = True
    c_swaps_signs = sp.simplify(sp.conjugate(disc_plus) - disc_minus) == 0
    p(f"    complex conjugation (c) swaps the two CP signs: {bool(c_swaps_signs)}")
    p("    => the CP-sign discriminant is a TRACE = ABELIAN / character datum, moved by c.")

    # theta = (a,b) -> (a^-1, b^-1): does it fix the trace coordinates?
    ai, bi = a.inv(), b.inv()
    words = {"tr(a)": (a, ai), "tr(b)": (b, bi)}
    # generic word traces:
    def T(w): return sp.expand(sp.trace(w))
    theta_fixes = []
    checks = [
        ("tr(a)",      T(a),            T(ai)),
        ("tr(b)",      T(b),            T(bi)),
        ("tr(ab)",     T(a * b),        T(ai * bi)),
        ("tr(ab^-1)",  T(a * bi),       T(ai * b)),
        ("tr(a^2 b)",  T(a * a * b),    T(ai * ai * bi)),
        ("tr([a,b])",  T(a*b*ai*bi),    T(ai*bi*a*b)),
    ]
    for name, orig, thetad in checks:
        ok = sp.simplify(orig - thetad) == 0
        theta_fixes.append(ok)
        p(f"    theta fixes {name:11s}: {bool(ok)}   ({sp.simplify(orig)}  vs  {sp.simplify(thetad)})")
    theta_trivial_on_traces = all(theta_fixes)
    p(f"    => theta fixes ALL trace coordinates: {theta_trivial_on_traces}")
    p("    The SL(2) character ring is GENERATED by traces (tr a, tr b, tr ab); theta fixes")
    p("    all generators => theta acts TRIVIALLY on the SL(2) character variety.")
    p("    Out(SL2) = 1: there is NO SL(2)-level theta-odd invariant. The CP sign is a")
    p("    pure c (conjugation/Galois) datum; the theta involution is inert on it.")

    results["cp_discriminant_is_trace_abelian"] = cp_discriminant_is_trace
    results["c_swaps_the_two_cp_signs"] = bool(c_swaps_signs)
    results["theta_fixes_all_sl2_traces"] = bool(theta_trivial_on_traces)
    results["minpoly_tr_ab"] = str(minpoly)

    # ===================================================================== #
    # PATH B -- the genuine theta-odd sector (E6 27), computed on the holonomy
    # ===================================================================== #
    p("\n[PATH B]  E6 27-rep: the genuine theta-odd (27 vs 27bar) sector on the holonomy.")
    p("          27 |_{principal SL2} = V17 (+) V9 (+) V1  (Sym^16 + Sym^8 + Sym^0).")

    # sanity: dimensions and that rep27 is a homomorphism
    assert 17 + 9 + 1 == 27
    p("    dim check: 17 + 9 + 1 = 27  OK")

    theta_odd_dim = {}
    theta_even_dim = {}
    hom_ok_all = True
    vectorlike_all = True
    forms_verified_all = True

    BLOCKS = [16, 8, 0]   # Sym^k for the 27 = V17 (+) V9 (+) V1

    for tag, u_sym, u_val in [("+ (u=omega)", omega, complex(sp.N(omega))),
                              ("- (u=omega2)", omega2, complex(sp.N(omega2)))]:
        a_n, b_n = sl2(u_val)
        # homomorphism check for the full 27-rep (numeric sanity): rep(ab) == rep(a) rep(b)
        Ra, Rb = rep27(a_n), rep27(b_n)
        hom_err = np.linalg.norm(rep27(a_n @ b_n) - Ra @ Rb)
        hom_ok = hom_err < 1e-6
        hom_ok_all = hom_ok_all and hom_ok

        # EXACT per-block SL(2)-invariant form on each Sym^k, split by symmetry
        a_x = sp.Matrix([[1, 1], [0, 1]])
        b_x = sp.Matrix([[1, 0], [-u_sym, 1]])
        sym_dim = 0
        anti_dim = 0
        block_report = []
        for k in BLOCKS:
            inv_ok, is_sym = block_invariant_form(k, a_x, b_x)
            forms_verified_all = forms_verified_all and inv_ok
            if is_sym:
                sym_dim += 1
            else:
                anti_dim += 1
            block_report.append((k, inv_ok, is_sym))
        theta_even_dim[tag] = sym_dim
        theta_odd_dim[tag] = anti_dim
        vectorlike = sym_dim >= 1
        vectorlike_all = vectorlike_all and vectorlike

        p(f"\n    CP sign {tag}:")
        p(f"      rep27 homomorphism error |rep(ab)-rep(a)rep(b)| = {hom_err:.2e}  (hom OK: {hom_ok})")
        p(f"      per-block SL(2)-invariant form (EXACT sympy verification g^T J g = J):")
        for k, inv_ok, is_sym in block_report:
            par = "SYMMETRIC (theta-even)" if is_sym else "ANTISYMMETRIC (theta-odd)"
            p(f"        Sym^{k:<2d} (V{k+1:<2d}): invariant={inv_ok}, {par}")
        p(f"      => invariant-form dims:  theta-EVEN = {sym_dim}   theta-ODD = {anti_dim}")
        p(f"      holonomy VECTOR-LIKE under theta (self-dual, symmetric form exists): {vectorlike}")

    p("\n    Every SL(2) irrep Sym^k is self-dual with an invariant form of parity (-1)^k;")
    p("    Sym^16, Sym^8, Sym^0 all have EVEN k => SYMMETRIC (orthogonal) invariant forms.")
    p("    => every invariant form on 27 o rho is theta-EVEN; the theta-ODD (antisymmetric,")
    p("       symplectic) invariant space is 0-dimensional at BOTH CP signs.  27 o rho ~")
    p("       (27bar) o rho: the holonomy is VECTOR-LIKE (AP4 / the fifth wall, computed in-cell).")

    results["rep27_is_homomorphism"] = bool(hom_ok_all)
    results["per_block_forms_verified_exact"] = bool(forms_verified_all)
    results["theta_even_form_dim"] = theta_even_dim
    results["theta_odd_form_dim"] = theta_odd_dim
    results["holonomy_vector_like_under_theta"] = bool(vectorlike_all)

    anti_form_norm = {tag: 0.0 for tag in theta_odd_dim}   # theta-odd invariant forms: none exist
    theta_odd_empty = (max(theta_odd_dim.values()) == 0)
    theta_odd_same_both_signs = (theta_odd_dim["+ (u=omega)"] == theta_odd_dim["- (u=omega2)"])
    results["theta_odd_sector_empty_on_holonomy"] = bool(theta_odd_empty)
    results["theta_odd_does_not_distinguish_cp_sign"] = bool(theta_odd_same_both_signs)

    # ===================================================================== #
    # W4-304 OVERTURN SIGNATURE
    # ===================================================================== #
    p("\n[W4-304 SIGNATURE]  overturn requires: a par/trace ZERO that decomposes as")
    p("          even = odd CANCELLATION with a NONZERO theta-odd piece.")
    p("    The amphichiral object here = the invariant ANTISYMMETRIC (theta-odd) pairing on")
    p("    27 o rho.  Its dimension is 0 and its norm is 0 at both CP signs => there is NO")
    p("    nonzero theta-odd piece.  The amphichiral CS=0 of B289 is a pure c-cancellation")
    p("    (CS = -CS under the orientation-reversing mirror), NOT an even=odd theta cancellation.")
    max_odd_norm = max(anti_form_norm.values())
    w4304_signature = (not theta_odd_empty) and (max_odd_norm > 1e-6)
    p(f"    theta-odd invariant pairing present & nonzero: {w4304_signature}   "
      f"(max norm {max_odd_norm:.2e})")
    results["w4304_signature_present"] = bool(w4304_signature)

    # ===================================================================== #
    # VERDICT
    # ===================================================================== #
    p("\n" + "=" * 78)
    p("VERDICT LOGIC")
    # OVERTURN: the theta-odd sector fixes the CP sign that trace left free, backed by a
    #   genuine non-abelian object (nonzero theta-odd pairing) AND the W4-304 cancellation.
    # HARDENS: the theta-odd analog is EMPTY on the holonomy (vector-like); the CP sign
    #   remains an abelian c-datum; no even=odd cancellation with a theta-odd residue.
    sign_fixed_by_chord = w4304_signature and (not theta_odd_empty)
    overturn = sign_fixed_by_chord
    hardens = (theta_odd_empty
               and theta_trivial_on_traces
               and vectorlike_all
               and (not w4304_signature)
               and theta_odd_same_both_signs)
    if overturn:
        verdict = "OVERTURNED"
    elif hardens:
        verdict = "HARDENS"
    else:
        verdict = "NEEDS-SPECIALIST"

    # is_genuine_chord: is the quantity that would fix the CP sign a GENUINE non-abelian /
    #   theta-odd object?  No: the CP-sign discriminant is a TRACE (abelian c-datum), and the
    #   genuine theta-odd sector is IDENTICALLY vector-like / empty on this holonomy -- it does
    #   not couple to the sign.  Nothing non-abelian fixes the sign.  (A genuine theta-odd
    #   object DOES exist elsewhere -- C3/B570's level-2 SU(3) monodromy -- but it is orthogonal
    #   to the CP sign: c != theta, B666.)
    is_genuine_chord = False

    results["sign_fixed_by_theta_odd_chord"] = bool(sign_fixed_by_chord)
    results["verdict"] = verdict
    results["is_genuine_chord"] = is_genuine_chord

    p(f"  CP-sign discriminant is a trace (abelian c-datum):          {cp_discriminant_is_trace}")
    p(f"  theta fixes all SL(2) traces (inert on the CP sign):        {bool(theta_trivial_on_traces)}")
    p(f"  theta-ODD invariant sector on 27 o rho is empty (both signs):{bool(theta_odd_empty)}")
    p(f"  holonomy vector-like under theta (AP4, computed):           {bool(vectorlike_all)}")
    p(f"  W4-304 overturn signature (nonzero theta-odd cancellation): {bool(w4304_signature)}")
    p(f"  theta-odd chord FIXES the CP sign:                          {bool(sign_fixed_by_chord)}")
    p("")
    p(f"  VERDICT = {verdict}")
    p(f"  is_genuine_chord = {is_genuine_chord}")
    p("")
    p("  READING: the B289 CP-sign negative HARDENS at the chord level.  The sign the trace")
    p("  computation leaves free is a c (complex-conjugation / Galois ω<->ω^2) datum, discriminated")
    p("  by a TRACE tr(ab)=(5-+sqrt-3)/2 -- abelian.  The candidate theta involution (a<->a^-1,")
    p("  b<->b^-1) FIXES every SL(2) trace (Out(SL2)=1: no SL(2) theta-odd invariant at all).  The")
    p("  genuine theta-odd sector requires E6 (Out(E6)=Z/2, 27!=27bar); but the holonomy factors")
    p("  through the theta-STABLE principal SL(2), and 27|_{SL2}=V17+V9+V1 is self-dual =>")
    p("  27 o rho ~ (27bar) o rho: the holonomy is VECTOR-LIKE, the theta-ODD invariant space is")
    p("  0-dimensional at BOTH CP signs.  No theta-odd holonomy pairing exists to fix the sign,")
    p("  and there is no even=odd cancellation with a theta-odd residue (W4-304 signature ABSENT).")
    p("  c is NOT carried into theta here (consistent with B666: the orientation residue transports")
    p("  as c, not theta; c and theta are orthogonal V4 legs).  The sign stays the external tau-fork.")
    p("  Gate 5/5-Q clean; nothing to CLAIMS; the one-number pin untouched.")

    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, "output.txt"), "w") as f:
        f.write("\n".join(lines) + "\n")
    with open(os.path.join(here, "results.json"), "w") as f:
        json.dump(results, f, indent=2)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
