#!/usr/bin/env python3
"""sm:B1550 -- the controls, run before the seal (and again, in part, by identity.py).

  K1  an independent rank method: every member orbit of population.json and the first two non-member orbits of every state
      in the census, re-read in both routes with ranks by complex SVD (mpmath) instead of elimination (sm:B1549's K1
      reader, copied here); (h1, r1, n) must equal the census's.
  K2  the readings seen before the seal, and one banked reading: on the root's tetrahedral cover the two sign-orbit
      representatives [0,0,0,0,1,1] and [0,0,0,1,0,1] (as sign exponents) read (-1, -1) in both routes (seen in the
      exploration that found the cover; disclosed in the seal's section 0); on L8a15 (sm:B1549's banked +LLLR cover,
      main's B1492) the sign member reads (-1, -1). Both routes, one draw.
  K3  the A4 action, exact: on every state's tetrahedral cover, at orders 2 and 4, the permutation group generated by the
      deck group and the golden map has order 12 with A4's element orders {1: 1, 2: 3, 3: 8}; phi mod 2 has order 3; the
      cover has four cusps for exactly one class wbar; the twist c satisfies phi_3 = phi^3 o Ad(c).
  K4  the read-out on synthetic rows: its verdicts and refutations.
  K5  n(1) = 0 on every tetrahedral cover, exact (sm:B1538's reader at the trivial character, two primes): h1 = 4 = the
      cusps.
  K6  the minimality below the root's tetrahedral cover: m004, its levels M_2 and M_3, the root's 4-fold (Z/2)^2 cover
      (not regular), and the six fibre-direction double covers of M_3 carry no sign member, in both routes. The order-4
      members of these covers are recorded, not checked.

    python3 controls.py   ->  controls.json beside this file"""
import json
import random
import time
from collections import Counter

import mpmath as mp

import read_out as RO
import tetra_lib as L

T = L.T
HERE = L.HERE


# ------------------------------------------------------------------------------------------------ K1: SVD ranks
def svd_rank(A, ncols):
    if not A or ncols == 0:
        return 0
    M = mp.matrix(A)
    s = [abs(x) for x in mp.svd_c(M, compute_uv=False)]
    smax = max(s)
    return sum(1 for x in s if smax and x / smax > T.REL)


def svd_structure(mod, P):
    """h1, r1, n with SVD ranks (no elimination); sm:B1549's controls.svd_structure"""
    e, ng = mod.e, P.ngen
    fox = T.vstack(*[mod.fox(r, ng)[0] for r in P.rels])
    rk = svd_rank(fox, ng * e)
    I = T.eye(e)
    dg = T.vstack(*[[[mod.M[j][i][k] - I[i][k] for k in range(e)] for i in range(e)] for j in range(ng)])
    h0 = e - svd_rank(dg, e)
    h1 = ng * e - rk - (e - h0)
    M = mp.matrix(fox)
    U, S, V = mp.svd_c(M, full_matrices=True)
    s = [abs(x) for x in S]
    smax = max(s) if s else 0
    r = sum(1 for x in s if smax and x / smax > T.REL)
    Z = [[mp.conj(V[r + j, i]) for i in range(ng * e)] for j in range(ng * e - r)]
    rowsR, BPb = [], []
    for (w1, w2) in P.periph:
        F1, W1 = mod.fox(w1, ng)
        F2, W2 = mod.fox(w2, ng)
        rowsR += [F1, F2]
        BPb.append(T.vstack([[W1[i][k] - I[i][k] for k in range(e)] for i in range(e)],
                            [[W2[i][k] - I[i][k] for k in range(e)] for i in range(e)]))
    nc = len(P.periph)
    BP = [[mp.mpc(0)] * (e * nc) for _ in range(2 * e * nc)]
    for c, b in enumerate(BPb):
        for i in range(2 * e):
            for k in range(e):
                BP[2 * e * c + i][e * c + k] = b[i][k]
    R = T.vstack(*rowsR)
    rBP = svd_rank(BP, e * nc)
    if Z:
        RZ = [[mp.fsum(R[i][l] * z[l] for l in range(ng * e)) for z in Z] for i in range(len(R))]
        r1 = svd_rank(T.hstack(BP, RZ), e * nc + len(Z)) - rBP
    else:
        r1 = 0
    return {"h1": h1, "r1": r1, "n": h1 - r1}


def K1():
    pop = json.loads((HERE / "population.json").read_text())
    import census as CEN
    census = [json.loads(x) for p in (0, 1, 2) for x in CEN._lines(HERE / f"census_{p}.jsonl") if x.strip()]
    order = {sw: i for i, sw in enumerate(L.STATES)}
    census.sort(key=lambda r: (order[r["state"]], r["orbit"]))
    picks = [r for r in census if r["P"]["n"] > 0 or r["S"]["n"] > 0]
    per_state = Counter()
    for r in census:
        if r["P"]["n"] == 0 and r["S"]["n"] == 0 and per_state[r["state"]] < 2:
            picks.append(r)
            per_state[r["state"]] += 1
    bad, n = [], 0
    for r in picks:
        wl, C = L.tetra_cover(r["state"])
        s3 = L.level3(r["state"])
        c = r["orbit"][0]
        ez, es = tuple(c[:-1]), c[-1]
        Pr, P = T.presentation_P(C)
        sP = svd_structure(T.Mod(T.module_P(s3, C, Pr, ez, es, L.M_ORDER)), P)
        PS, _ = T.presentation_S(C.st)
        sS = svd_structure(T.Mod(T.ind_blocks(s3, C, ez, es, L.M_ORDER)), PS)
        n += 1
        for name, got, want in (("P", sP, r["P"]), ("S", sS, r["S"])):
            if (got["h1"], got["r1"], got["n"]) != (want["h1"], want["r1"], want["n"]):
                bad.append([r["state"], c, name, got, want])
    return {"orbits re-read": n, "member orbits among them": len(pop["member orbits"]), "disagreements": bad,
            "holds": not bad}


# ------------------------------------------------------------------------------------------------ K2: seen and banked
def count_at(sw, C, ch, route, tag):
    ez, es = tuple(ch[:-1]), ch[-1]
    rng = random.Random(f"B1550|{tag}|{sw}|{route}|{ch}")
    r = (T.read_P if route == "P" else T.read_S)(sw, C, ez, es, 4, [rng])
    return {"structure": r["structure"], "interior dimension": r["interior dimension"],
            "count": r["draws"][0]["count"] if r["draws"] else None}


def run_K2():
    wl, N = L.tetra_cover("+LR")
    cases = [("+LRLRLR", N, [0, 0, 0, 0, 2, 2], [-1, -1], "seen: the root's tetrahedral cover, sign orbit A's representative"),
             ("+LRLRLR", N, [0, 0, 0, 2, 0, 2], [-1, -1], "seen: the root's tetrahedral cover, sign orbit B's representative"),
             ("+LLLR", T.PC.Cover(T.PC.State("+LLLR"), (1, 0, 3), 0), [0, 2, 0, 2, 0], [-1, -1],
              "banked: sm:B1549 and main's B1492, a sign member of L8a15")]
    out = []
    for sw, C, ch, expect, src in cases:
        for route in ("P", "S"):
            t0 = time.time()
            r = count_at(sw, C, ch, route, "K2")
            out.append({"state": sw, "character": ch, "route": route, "expect": expect, "source": src, "got": r["count"],
                        "structure": r["structure"], "holds": r["count"] == expect,
                        "seconds": round(time.time() - t0, 1)})
    return out


# ------------------------------------------------------------------------------------------------ K3: the A4 action
def K3():
    rows, ok = [], True
    for sw in L.STATES:
        wl, C = L.tetra_cover(sw)
        c = L.twist(sw)
        for m in (2, 4):
            chars = L.characters(C, m)
            idx = {x: i for i, x in enumerate(chars)}
            gens = [tuple(idx[T.deck_action(C, x[0], x[1], m)[d]] for x in chars) for d in range(C.d)]
            gens.append(tuple(idx[L.golden_action(sw, C, x[0], x[1], m)] for x in chars))
            ident = tuple(range(len(chars)))
            G, front = {ident}, [ident]
            while front:
                nxt = []
                for g in front:
                    for h in gens:
                        k = tuple(h[g[i]] for i in range(len(chars)))
                        if k not in G:
                            G.add(k)
                            nxt.append(k)
                front = nxt

            def order(g):
                k, x = 1, g
                while x != ident:
                    x = tuple(g[x[i]] for i in range(len(chars)))
                    k += 1
                return k
            prof = dict(sorted(Counter(order(g) for g in G).items()))
            good = len(G) == 12 and prof == {1: 1, 2: 3, 3: 8} and L.phi_mod2_order(sw) == 3 and len(C.cusps) == 4
            rows.append({"state": sw, "m": m, "characters": len(chars), "group order": len(G),
                         "element orders": {str(k): v for k, v in prof.items()}, "phi mod 2 order": L.phi_mod2_order(sw),
                         "wbar": wl, "cusps": len(C.cusps), "twist": c, "H1 free rank": C.free_rank,
                         "H1 torsion": C.torsion, "holds": good})
            ok = ok and good
    return {"rows": rows, "holds": ok}


# ------------------------------------------------------------------------------------------------ K4: the read-out
def synthetic(pop, root4=(-1, 0), partner=(-1, -2), root2=(-1, -1)):
    gap = [[0.01, 1e-50]] * 4
    rows = []
    for orb in pop["member orbits"]:
        for ch in orb["orbit"]:
            mem = orb["members"][json.dumps(ch)]
            cnt = root2 if (orb["state"] == "+LR" and orb["order"] == 2) else \
                (root4 if orb["state"] == "+LR" else partner)
            n = orb["P"]["n"]
            for route in ("P", "S"):
                reads = {k: {"h0": 0, "h1": 1, "r1": 0, "n": 1, "gaps": gap} for k in ("W1", "W1*", "L2", "L2*")}
                rows.append({"route": route, "state": orb["state"], "character": ch, "order": orb["order"],
                             "m_A": mem["m_A"], "m_A (this character)": mem["m_A"],
                             "structure": {"h0": 0, "h1": orb[route]["h1"], "r1": orb[route]["r1"], "n": n,
                                           "gaps": gap},
                             "interior dimension": n, "draws": [{"count": list(cnt), "reads": reads} for _ in range(3)]})
    return rows


def K4():
    pop = json.loads((HERE / "population.json").read_text())
    ctl = {"all hold": True}
    cases = {}
    out, _ = RO.evaluate(synthetic(pop), pop, ctl, True)
    cases["as expected: PROVED, P6-P9 hold"] = out["verdict"] == "PROVED" and all(out[p] for p in ("P6", "P7", "P8", "P9"))
    out, _ = RO.evaluate(synthetic(pop, partner=(-1, -1)), pop, ctl, True)
    cases["the partner generation-shaped: P9 false, still PROVED"] = out["P9"] is False and out["verdict"] == "PROVED"
    out, _ = RO.evaluate(synthetic(pop, root4=(-1, -1)), pop, ctl, True)
    cases["a root order-4 member generation-shaped: P7, P8 false, NEGATIVE"] = (out["P7"] is False and out["P8"] is False
                                                                              and out["verdict"] == "NEGATIVE")
    out, _ = RO.evaluate(synthetic(pop, root2=(-1, 0)), pop, ctl, True)
    cases["the root's sign members not generation-shaped: P6, P8 false, NEGATIVE"] = (out["P6"] is False and
                                                                                     out["P8"] is False and
                                                                                     out["verdict"] == "NEGATIVE")
    r = synthetic(pop)
    r[-1]["draws"][0]["count"] = [-1, -1]
    out, _ = RO.evaluate(r, pop, ctl, True)
    cases["draws disagree: P5 false, OPEN"] = out["P5"] is False and out["verdict"] == "OPEN"
    r = synthetic(pop)[:-1]
    out, _ = RO.evaluate(r, pop, ctl, True)
    cases["a missing task: incomplete, OPEN"] = out["complete"] is False and out["verdict"] == "OPEN"
    r = synthetic(pop)
    r.append(dict(r[0]))
    out, _ = RO.evaluate(r, pop, ctl, True)
    cases["a duplicated task: incomplete, OPEN"] = out["complete"] is False and out["verdict"] == "OPEN"
    r = synthetic(pop)
    r[1]["interior dimension"] = r[1]["structure"]["n"] = r[1]["structure"]["n"] + 1
    out, _ = RO.evaluate(r, pop, ctl, True)
    cases["routes disagree on structure: P2 false, OPEN"] = out["P2"] is False and out["verdict"] == "OPEN"
    r = synthetic(pop)
    for d in r[0]["draws"]:
        d["count"] = [-2, -1]
    out, _ = RO.evaluate(r, pop, ctl, True)
    cases["below the cap: P4 false, OPEN"] = out["P4"] is False and out["verdict"] == "OPEN"
    out, _ = RO.evaluate(synthetic(pop), pop, {"all hold": False}, True)
    cases["a control failed: P1 false, OPEN"] = out["P1"] is False and out["verdict"] == "OPEN"
    r = synthetic(pop)
    r[0]["structure"]["gaps"] = [[1e-28, 1e-40]]
    out, _ = RO.evaluate(r, pop, ctl, True)
    cases["a murky gap: P4 false, OPEN"] = out["P4"] is False and out["verdict"] == "OPEN"
    return {"cases": cases, "holds": all(cases.values())}


# ------------------------------------------------------------------------------------------------ K5: n(1) = 0
def K5():
    rows, ok = [], True
    for sw in L.STATES:
        wl, C = L.tetra_cover(sw)
        Pr = T.RP.Presentation(C)
        ez = tuple([0] * C.n)
        reads = [T.RP.read(Pr, ez, 0, 2, p) for p in (1000003, 998244353)]
        same = reads[0] == reads[1]
        rows.append({"state": sw, "h1": reads[0]["h1"], "r1": reads[0]["r1"], "n(1)": reads[0]["n"], "primes agree": same})
        ok = ok and same and reads[0]["n"] == 0 and reads[0]["h1"] == 4
    return {"covers": rows, "holds": ok}


# ------------------------------------------------------------------------------------------------ K6: below the cover
def K6():
    covers = [("+LR", (1, 0, 1), 0, "m004"), ("+LRLR", (1, 0, 1), 0, "M_2"), ("+LRLRLR", (1, 0, 1), 0, "M_3"),
              ("+LR", (2, 0, 2), 0, "the root's 4-fold (Z/2)^2 cover")]
    st3 = T.PC.State("+LRLRLR")
    for lat in T.PC.lattices(st3.M, 2, 2):
        for wl in range(2):
            covers.append(("+LRLRLR", tuple(lat), wl, "a double cover of M_3"))
    rows, ok = [], True
    for sw, lat, wl, name in covers:
        C = T.PC.Cover(T.PC.State(sw), lat, wl)
        tab = Counter()
        sign_members = 0
        for ez in C.characters(4):
            for es in range(4):
                o = T.char_order((ez, es), 4)
                P = T.read_P(sw, C, ez, es, 4)["structure"]
                S = T.read_S(sw, C, ez, es, 4)["structure"]
                agree = (P["h1"], P["r1"], P["n"]) == (S["h1"], S["r1"], S["n"])
                tab[(o, P["n"], S["n"], agree)] += 1
                if o <= 2 and (P["n"] or S["n"]):
                    sign_members += 1
                ok = ok and agree
        rows.append({"cover": name, "state": sw, "lattice": list(lat), "wbar": wl, "cusps": len(C.cusps),
                     "(order, n in P, n in S, routes agree): characters": {str(list(k)): v for k, v in sorted(tab.items())},
                     "sign members": sign_members})
        ok = ok and sign_members == 0
    return {"covers": rows, "holds": ok}


def main():
    t0 = time.time()
    out = {"K1": K1(), "K2": run_K2(), "K3": K3(), "K4": K4(), "K5": K5(), "K6": K6()}
    out["all hold"] = (out["K1"]["holds"] and all(x["holds"] for x in out["K2"]) and out["K3"]["holds"] and
                       out["K4"]["holds"] and out["K5"]["holds"] and out["K6"]["holds"])
    out["seconds"] = round(time.time() - t0, 1)
    (HERE / "controls.json").write_text(json.dumps(out, indent=1) + "\n")
    print(json.dumps({"K1": out["K1"]["holds"], "K2": [(x["character"], x["route"], x["got"]) for x in out["K2"]],
                      "K3": out["K3"]["holds"], "K4": out["K4"]["cases"],
                      "K5": [(x["state"], x["n(1)"]) for x in out["K5"]["covers"]],
                      "K6": [(x["cover"], x["lattice"], x["wbar"], x["sign members"]) for x in out["K6"]["covers"]],
                      "all hold": out["all hold"]}, indent=1))


if __name__ == "__main__":
    main()
