r"""ROW 3 — is charge quantisation a CONSEQUENCE of B862's Z6?

The content ledger graded charge quantisation as CONSEQUENCE-UNCLAIMED: it
appears to follow from the derived global form, and no arc writes the
implication down. This writes it down and checks it.

THE STATEMENT

B862 derives the gauge group as the QUOTIENT

        G = [SU(3) x SU(2) x U(1)] / Z6

The Z6 is generated by the element

        z = ( w*I3 , -I2 , e^{i pi/3} ),      w = e^{2 pi i/3}

A representation of the covering group SU(3)xSU(2)xU(1) descends to G if and
only if z acts on it as the identity. For an irrep labelled by

        t = colour TRIALITY  (0 for singlets, 1 for 3, 2 for 3bar)
        d = weak DUALITY     (0 for integer isospin, 1 for half-integer)
        Y = hypercharge

z acts by the phase  exp(2 pi i [ t/3 + d/2 + Y ]),  so descent requires

        t/3 + d/2 + Y  ==  0   (mod 1)                       (*)

(*) IS CHARGE QUANTISATION. In the UNQUOTIENTED group SU(3)xSU(2)xU(1),
hypercharge is an arbitrary real label -- nothing forbids a colour singlet,
weak singlet with Y = sqrt(2). Under the quotient, Y is DETERMINED MODULO 1 by
the colour and weak representations. Charges cannot be arbitrary; they lie on a
lattice fixed by (t, d).

TESTED: every Standard Model multiplet must satisfy (*), and a deliberately
non-quantised charge must fail it.

Gate 5-Q. Structure only; the hypercharge values below are REPRESENTATION
LABELS in the standard normalisation, not measured quantities -- no measurement
enters and nothing is compared to data.
"""
from fractions import Fraction as F

# (name, colour triality t, weak duality d, hypercharge Y) -- one generation,
# standard normalisation Q = T3 + Y
SM = [
    ('Q   (3,2)',    1, 1, F(1, 6)),
    ('u^c (3bar,1)', 2, 0, F(-2, 3)),
    ('d^c (3bar,1)', 2, 0, F(1, 3)),
    ('L   (1,2)',    0, 1, F(-1, 2)),
    ('e^c (1,1)',    0, 0, F(1)),
    ('nu^c(1,1)',    0, 0, F(0)),
    ('H   (1,2)',    0, 1, F(1, 2)),      # the Higgs doublet
]

# controls: representations that are FINE in the covering group but FORBIDDEN
# by the quotient. If (*) is really charge quantisation these must fail.
BAD = [
    ('a colour/weak singlet with Y = 1/2',  0, 0, F(1, 2)),
    ('a colour/weak singlet with Y = 1/3',  0, 0, F(1, 3)),
    ('a quark doublet with Y = 1/3',        1, 1, F(1, 3)),
]


def descends(t, d, Y):
    """Does the irrep descend to the Z6 quotient?  t/3 + d/2 + Y in Z."""
    return (F(t, 3) + F(d, 2) + Y).denominator == 1


def main():
    print('ROW 3 — CHARGE QUANTISATION FROM THE Z6 QUOTIENT')
    print('=' * 66)
    print('  descent condition:  t/3 + d/2 + Y  ==  0  (mod 1)\n')
    print(f'  {"multiplet":16} {"t":>2} {"d":>2} {"Y":>6}   {"t/3+d/2+Y":>10}  descends?')
    ok = True
    for n, t, d, Y in SM:
        v = F(t, 3) + F(d, 2) + Y
        good = descends(t, d, Y)
        ok &= good
        print(f'  {n:16} {t:>2} {d:>2} {str(Y):>6}   {str(v):>10}  {"YES" if good else "NO"}')
    assert ok, 'every SM multiplet must descend'
    print('\n  ALL SEVEN SM MULTIPLETS DESCEND. The SM matter content is exactly')
    print('  a representation of the QUOTIENT, not merely of the cover.\n')

    print('  CONTROLS — allowed in the cover, forbidden by the quotient:')
    for n, t, d, Y in BAD:
        v = F(t, 3) + F(d, 2) + Y
        good = descends(t, d, Y)
        assert not good, f'{n} should NOT descend'
        print(f'    {n:36} -> {str(v):>6}   FORBIDDEN')

    print('\n' + '=' * 66)
    print('  So the quotient is not bookkeeping. It says:')
    print()
    print('     given the colour and weak representations, HYPERCHARGE IS')
    print('     DETERMINED MODULO 1.  Y cannot be an arbitrary real number.')
    print()
    print('  That IS charge quantisation. In the unquotiented group nothing')
    print('  forbids Y = sqrt(2) on a singlet; under Z6 it is excluded.')
    print()
    print('  B862 derives the quotient (kernel computed exactly, order 6).')
    print('  Charge quantisation therefore FOLLOWS -- and no arc says so.')
    print('=' * 66)


if __name__ == '__main__':
    main()
