"""B247 -- adjudication of the chat1/chat2 V1 "E6 -> SM gauge group" handoffs (2026-06-28).

FIREWALL: this is Lie theory + SL(2,C) character-variety arithmetic (MATH). The physics reading -- "E6 breaks
to the Standard-Model gauge group via the figure-eight's holonomy" -- is NOT a claim here; it is firewalled as a
rhyme (see PAPER sec.5.4). Nothing to CLAIMS.md. The point of this probe is the OPPOSITE of a physics claim: it
verifies the math and shows the object-specific physics bridge does NOT close.

THE TWO HANDOFF CLAIMS, ADJUDICATED:

(V1) "the centralizer of the geometric holonomy SU(2)_long in E6 contains the SM gauge group, = SU(3)xSU(2)xU(1)^2"
  VERDICT: the centralizer structure both chats gave is WRONG (verify-don't-trust catch).
  Sage-verified branchings (E6 -> A2xG2; G2 -> A1xA1 = SO(4); E6 -> A1xA5):
    78 of E6  ->  (8,1) + (8,7) + (1,14)   under SU(3) x G2     [resolves chat1's "64/78" -- the (8,7)=56 piece]
    7  of G2  ->  (1,1) + (2,0)            under A1 x A1
    14 of G2  ->  (2,0) + (3,1) + (0,2)    under A1 x A1
  Embedding indices (from the adjoint, G2 index 2h^v=8): factor-2 A1 = LONG (index 1), factor-1 A1 = SHORT (index 3).
  Centralizer dims (= singlet multiplicity of 78 under that A1):
    C_E6(SU(2)_long,  index 1) = 35 = SU(6)        (rank 5)  -- the A5 of the Borel-de Siebenthal E6 ⊃ A1xA5
    C_E6(SU(2)_short, index 3) = 11 = SU(3)xSU(2)  (rank 3)  -- NO U(1)
  NEITHER is SU(3)xSU(2)xU(1)^2 (dim 13). The long case DOES contain the SM (SU(6) ⊃ SU(5) ⊃ SM) but as a textbook
  SU(6) GUT -- generic, not object-specific. The short case has no hypercharge U(1) at all. Chat2's "dim 13 from
  rank = 6-1 = 5" fails: the rank formula does not hold for the index-3 embedding, and even at index 1 the group is
  SU(6), not SU(3)xSU(2)xU(1)^2.

(BRIDGE) "the figure-eight's geometric holonomy lives in SU(2)_long" -- the load-bearing, object-specific claim.
  VERDICT: FALSE as stated (chat2 right, decisive). The discrete faithful (geometric) holonomy is irreducibly
  SL(2,C): its word traces are genuinely complex (Test 1). The non-abelian SU(2) reps that COULD break E6 exist
  (Test 2) but are a different family on the character variety -- and carry a different trace field:
     geometric component : meridian trace 2, u = e^{+-i pi/3},  field Q(sqrt-3)  -> 2T -> E6
     SU(2) arc at x=0    : u = -(2+-sqrt5)/2 in Q(sqrt5),  tr(ab) = phi or -1/phi  -> 2I -> E8
  So the connection that SELECTS E6 (Q(sqrt-3)) is provably NOT the connection that could BREAK it (SU(2),
  Q(sqrt5)); they are different points with different McKay images (E6 vs E8). No canonical identification of the
  two is known (default: none). => the breaking VEV is a CHOICE, not a geometric consequence; V1 is "E6 (or SU(6))
  GUT with a knot-shaped motivation." Firewall holds, sharply located.

Run: python adjudication.py (pyenv; sympy+numpy). The Sage branchings are regenerated by e6_branchings_sage.py.
"""
import cmath

import numpy as np
import sympy as sp

# ---- V1: centralizer dims from the Sage-verified A1xA1 decompositions of the G2 reps ----
# data: each G2 irrep -> list of (a, b) coroot labels under A1_factor1 x A1_factor2  (Sage 'extended' rule)
SEVEN_A1A1 = [(1, 1), (2, 0)]                 # dims (2*2) + (3*1) = 7
FOURTEEN_A1A1 = [(2, 0), (3, 1), (0, 2)]      # dims (3*1)+(4*2)+(1*3) = 14
# 78 of E6 -> A2 x G2
E6_A2G2 = {"(8,1)": (8, "trivial"), "(8,7)": (8, "7"), "(1,14)": (1, "14")}


def a1_dim(label):           # dim of A1 coroot-label irrep
    return label + 1


def a1_index(label):         # Dynkin index of A1 irrep (normalized: adjoint/triplet -> 4)
    return label * (label + 1) * (label + 2) // 6


def embedding_index(factor):
    """index of A1 'factor' (1 or 2) computed from the G2 adjoint (G2 index = 2*h^v = 8)."""
    total = 0
    for a, b in FOURTEEN_A1A1:
        lab = a if factor == 1 else b
        mult_other = a1_dim(b if factor == 1 else a)
        total += mult_other * a1_index(lab)
    return total // 8


def singlets(decomp, factor):
    """number of A1_factor singlets in a G2 rep with given A1xA1 decomposition."""
    s = 0
    for a, b in decomp:
        lab = a if factor == 1 else b
        if lab == 0:
            s += a1_dim(b if factor == 1 else a)
    return s


def centralizer_dim(factor):
    """singlet multiplicity of 78 under A1 'factor' = dim of the E6-centralizer."""
    s7 = singlets(SEVEN_A1A1, factor)
    s14 = singlets(FOURTEEN_A1A1, factor)
    return 8 * 1 + 8 * s7 + 1 * s14            # from (8,1)+(8,7)+(1,14)


# ---- TEST 1: the geometric holonomy has complex word-traces (not SU(2)-conjugable) ----
# NOTE (verify-don't-trust catch): chat2's handoff gave rho(b)=[[1,0],[-e^{i pi/3},1]], i.e. Riley parameter
# u=e^{i pi/3} -- a root of u^2-u+1, NOT of the figure-eight's parabolic Riley polynomial u^2+u+1 (roots
# e^{+-2 i pi/3}). So chat2's *explicit matrices* are NOT a valid 4_1 representation (wrong cyclotomic root). The
# CONCLUSION survives -- the correct discrete-faithful rep (u=e^{2 i pi/3}) also has complex traces, and SnapPy
# confirms it independently -- but we use the CORRECT matrices here.
def test1_traces():
    u = cmath.exp(2j * cmath.pi / 3)               # correct figure-eight cusp parameter (root of u^2+u+1)
    a = np.array([[1, 1], [0, 1]], dtype=complex)
    b = np.array([[1, 0], [-u, 1]], dtype=complex)
    tr = lambda M: M[0, 0] + M[1, 1]
    return {"ab": tr(a @ b), "[a,b]": tr(a @ b @ np.linalg.inv(a) @ np.linalg.inv(b))}


def chat2_matrices_are_invalid_rep():
    """chat2's stated u=e^{i pi/3} is NOT a root of the figure-eight Riley poly u^2+u+1 (the correct one)."""
    bad = cmath.exp(1j * cmath.pi / 3)
    return abs(bad ** 2 + bad + 1) > 1e-9          # True => chat2's matrices fail the relation


# ---- TEST 2: the figure-eight Riley polynomial; geometric (Q(sqrt-3)) vs SU(2) arc (Q(sqrt5)) ----
def riley_roots(meridian_eig):
    s, u = sp.symbols('s u')
    a = sp.Matrix([[s, 1], [0, 1 / s]])
    b = sp.Matrix([[s, 0], [-u, 1 / s]])
    w = a * b.inv() * a.inv() * b                 # 4_1 relation: w a = b w
    rel = sp.numer(sp.together((w * a - b * w)[0, 1])) * s ** 2
    return sp.solve(sp.Eq(rel.subs(s, meridian_eig), 0), u)


if __name__ == "__main__":
    print("=== V1 (corrected): E6 centralizers ===")
    for f in (1, 2):
        idx = embedding_index(f)
        dim = centralizer_dim(f)
        kind = "LONG" if idx == 1 else "SHORT"
        grp = {35: "SU(6)  ⊃ SU(5) ⊃ SM (generic GUT)", 11: "SU(3)×SU(2)  (rank 3, NO U(1))"}[dim]
        print(f"  factor {f}: index {idx} ({kind})  ->  C_E6 dim {dim} = {grp}")
    assert centralizer_dim(2) == 35 and embedding_index(2) == 1     # long -> SU(6)
    assert centralizer_dim(1) == 11 and embedding_index(1) == 3     # short -> SU(3)xSU(2)
    print("  => neither is SU(3)×SU(2)×U(1)^2 (dim 13): both handoffs' centralizer is wrong.")

    print("\n=== TEST 1: geometric holonomy word-traces (complex => not SU(2)) ===")
    for name, t in test1_traces().items():
        print(f"  tr({name}) = {t.real:+.4f} {t.imag:+.4f}i   complex: {abs(t.imag) > 1e-9}")
    assert all(abs(t.imag) > 1e-9 for t in test1_traces().values())

    print("\n=== TEST 2: Riley polynomial -- geometric Q(sqrt-3) vs SU(2) arc Q(sqrt5) ===")
    print(f"  meridian eig s=1 (x=2, geometric): u = {riley_roots(1)}   (e^(i pi/3), field Q(sqrt-3) -> E6)")
    r0 = riley_roots(sp.I)
    print(f"  meridian eig s=i (x=0, SU(2) arc): u = {r0}   (field Q(sqrt5) -> E8)")
    # the x=0 reps are SU(2): tr(ab) = -2-u is golden and in [-2,2]
    for r in r0:
        tab = complex(-2 - r)
        print(f"     u={complex(r):+.4f} -> tr(ab)={tab.real:+.4f} (real, in[-2,2]: {abs(tab.imag)<1e-9 and -2<=tab.real<=2}; golden)")
    print("\nVERDICT: gauge math real but generic (SU(6) GUT); object-specific bridge FAILS -- the E6-selecting")
    print("         connection (SL(2,C), Q(sqrt-3)) is NOT the SU(2) one that could break it (Q(sqrt5)). Firewall holds.")
    print("ALL CHECKS PASS")
