"""B137 -- S031 sealing extended to m=2 (silver, SL(3), Q(i)) + the reducible-filter method note (MB7).

A "push further" increment on the S031 capstone (the SL(n) sealing: the metallic trace map fixes only the Sym^{n-1}
image of its SL(2) fixed point). B129 verified the sealing for m=1 at SL(3) (figure-eight, Q(sqrt-3)); it explicitly
left "per-m bulk search for m>=2" undone. This stage closes the m=2 gap (silver, Q(i)) -- and, en route, catches a
reducible-locus artifact (a verify-don't-trust correction to the naive search) that becomes a standing method note.

ONE-LINE RESULT. The SL(3) tower is sealed in K_m for BOTH arithmetic metallic members: m=1 in Q(sqrt-3) (B129,
reproduced) and m=2 in Q(i) (NEW) -- among IRREDUCIBLE off-sublocus fixed points there are ZERO escapes from the SL(2)
trace field (2 seeds each). Strengthens S031 from {m=1} to {m=1, m=2}; the theorem-version (all m, all n) stays open.

  ============================================================================================================
  METHOD NOTE (MB7 -- the reducible-locus escape artifact; -> REPRODUCIBILITY.md SCAN):
    A naive off-sublocus search that counts ANY converged fixed point with trace far from K_m as an "escape"
    OVER-COUNTS: the REDUCIBLE locus (algebra dim < 9) carries degenerate points whose commutator trace kappa is
    NOT constrained to K_m, faking escapes. B129's m=1 search did not expose this (its reducible points happen to be
    rational, hence in Q(sqrt-3)); at m=2 the reducible points have messy non-Q(i) kappa, faking ~15-20 "escapes"
    that are all reducible (algdim 7, trA=-1, |eig|=1, well-converged). GUARD: count an escape only among GENUINE
    IRREDUCIBLE fixed points (algebra generated by A,B = M_3, dim 9). With that filter the m=2 escapes vanish ->
    sealing holds. (Sibling of K-G/K-H/MB2: a surprising "escape" that is a degenerate artifact -- run the
    irreducibility classification before counting.)
  ============================================================================================================
  Method: off-sublocus root-find tcoords(A,B)=tcoords(A^m B, A) (B129 convention; A gauge-fixed diagonal with
  distinct eigenvalues, B generic SL(3,C)); converged fixed points classified by algebra dim; among irreducible
  ones (algdim=9), the max distance of any of Lawton's 9 trace coordinates to K_m.
"""
from __future__ import annotations

import math
from fractions import Fraction

# Verified records (in-sandbox, 2 seeds each). (irreducible_count, irreducible_escapes, reducible_artifacts_ignored).
SEALING_RECORD = {
    (1, "Q(sqrt-3)"): {"seed_20260608": (36, 0, 0), "seed_424242": (33, 0, 0)},
    (2, "Q(i)"):      {"seed_20260608": (23, 0, 22), "seed_424242": (25, 0, 13)},
}


def _isr(t, md=100):
    return abs(float(Fraction(float(t)).limit_denominator(md)) - t)


def _dist(z, field):
    if field == "Q(i)":
        return max(_isr(z.real), _isr(z.imag))
    return max(_isr(z.real), _isr(z.imag / math.sqrt(3)))     # Q(sqrt-3)


def sealing_search(m, field, seed=20260608, starts=160):
    """Off-sublocus SL(3) sealing search with the IRREDUCIBILITY filter (MB7). Returns the irreducible-escape count."""
    try:
        import numpy as np
        from scipy.optimize import least_squares
    except Exception:
        return None

    def tcoords(A, B):
        Ai, Bi = np.linalg.inv(A), np.linalg.inv(B)
        AB = A @ B
        return np.array([np.trace(A), np.trace(B), np.trace(Ai), np.trace(Bi), np.trace(AB),
                         np.trace(Bi @ Ai), np.trace(A @ Bi), np.trace(Ai @ B), np.trace(A @ B @ Ai @ Bi)],
                        dtype=complex)

    def unpack(x):
        zc = x[0::2] + 1j * x[1::2]
        a, b = zc[0], zc[1]
        A = np.diag([a, b, 1.0 / (a * b)])
        B = zc[2:11].reshape(3, 3)
        return A, B / np.linalg.det(B) ** (1 / 3)

    def res(x):
        A, B = unpack(x)
        Am = np.linalg.matrix_power(A, m)
        r = tcoords(A, B) - tcoords(Am @ B, A)                  # phi_m(A,B) = (A^m B, A)
        return np.concatenate([r.real, r.imag])

    def algdim(A, B):
        mats, fr = [np.eye(3)], [np.eye(3)]
        for _ in range(6):
            nf = []
            for M in fr:
                for g in (A, B):
                    nf.append(M @ g); mats.append(M @ g)
            fr = nf
            if np.linalg.matrix_rank(np.array([mm.flatten() for mm in mats]), tol=1e-6) >= 9:
                return 9
        return int(np.linalg.matrix_rank(np.array([mm.flatten() for mm in mats]), tol=1e-6))

    rng = np.random.default_rng(seed)

    def rx():
        z = rng.normal(size=11) + 1j * rng.normal(size=11)
        o = np.empty(22); o[0::2], o[1::2] = z.real, z.imag
        return o

    irred = esc_irred = red_ignored = 0
    maxd = 0.0
    for _ in range(starts):
        sol = least_squares(res, rx(), method="trf", ftol=1e-14, xtol=1e-14, gtol=1e-14, max_nfev=6000)
        if np.linalg.norm(sol.fun) > 1e-7:
            continue
        A, B = unpack(sol.x)
        d = max(_dist(z, field) for z in tcoords(A, B))
        if d > 1e-5:                                            # polish candidate (MB2)
            pol = least_squares(res, sol.x, method="trf", ftol=1e-15, xtol=1e-15, gtol=1e-15, max_nfev=20000)
            A, B = unpack(pol.x)
            d = max(_dist(z, field) for z in tcoords(A, B))
        if algdim(A, B) == 9:                                  # MB7: only irreducible points count
            irred += 1
            maxd = max(maxd, d)
            if d > 1e-4:
                esc_irred += 1
        elif d > 1e-4:
            red_ignored += 1
    return {"m": m, "field": field, "irreducible": irred, "irreducible_escapes": esc_irred,
            "max_dist_irred": round(maxd, 8), "reducible_artifacts_ignored": red_ignored, "sealed": esc_irred == 0}


def main():
    print("=" * 96)
    print("B137 -- S031 sealing extended to m=2 (SL(3), Q(i)) + the reducible-filter method note (MB7)")
    print("=" * 96)
    for m, field in [(1, "Q(sqrt-3)"), (2, "Q(i)")]:
        r = sealing_search(m, field)
        print("\n", ("scipy absent -- records stand: " + str(SEALING_RECORD)) if r is None else r)
    print("\nSEALED in K_m among irreducible off-sublocus fixed points for m=1 (Q(sqrt-3)) and m=2 (Q(i)).")
    print("The reducible 'escapes' are degenerate artifacts (MB7: filter algdim==9 before counting). S031 strengthened.")


if __name__ == "__main__":
    main()
