"""INDEPENDENT check of codex R021, and a GENERALIZATION found while checking it.

Codex proves: the Gieseking manifold N has two Pin- structures, m004 has two spin structures, and
the affine restriction map is CONSTANT because its linear part p^*: H^1(N;F2) -> H^1(M;F2) is zero,
citing the abelianization H1(N) = Z<t> with the cover's generators landing on 2t.

Checked here -- and the reason is more general than the computation suggests.
"""
import snappy, sympy as sp

N, M = snappy.Manifold("m000"), snappy.Manifold("m004")
print(f"N = Gieseking ({N.name()}): orientable {N.is_orientable()}, H1 = {N.homology()}")
print(f"M = ({M.name()}):          orientable {M.is_orientable()}, H1 = {M.homology()}")
assert not N.is_orientable() and M.is_orientable()
assert any(c.is_isometric_to(M) for c in N.covers(2)), "m004 must be the double cover"
print("    m004 IS a degree-2 cover of the Gieseking: confirmed by isometry.")

print("\n=== 1. H^1(N; F2) has rank ONE ===")
G = N.fundamental_group()
gens = [g.lower() for g in G.generators()]
def expsum(word):
    return {g: sum((1 if ch.islower() else -1) for ch in word if ch.lower() == g) for g in gens}
rel = G.relators()[0]
print(f"    pi_1(N) = <{','.join(gens)} | {rel}>, exponent sums {expsum(rel)}")
Rm = sp.Matrix([[expsum(r)[g] for g in gens] for r in G.relators()])
from sympy.matrices.normalforms import smith_normal_form
print(f"    Smith normal form {smith_normal_form(Rm).tolist()}  ->  H1(N) = Z")
print("    so H^1(N; F2) = Hom(H1(N), F2) = F2: RANK ONE, generated by a single class.")

print("\n=== 2. that single class IS w1, and p^* w1 = 0 always ===")
print("    N is nonorientable, so w1 != 0 in H^1(N; F2); with rank 1, H^1(N; F2) = <w1>.")
print("    The orientation double cover is BY DEFINITION the cover on which w1 pulls back to 0.")
print("    Hence p^* kills a generator of the whole group => p^* = 0 => the linear part of the")
print("    affine restriction vanishes => THE RESTRICTION IS CONSTANT.  Codex's theorem, CONFIRMED.")

print("\n=== 3. the same statement, in codex's coordinates (their stated engine) ===")
print("    The double cover corresponds to the index-2 subgroup ker(pi_1(N) -> H1(N) = Z -> Z/2),")
print("    i.e. the words of EVEN exponent sum. Their images in H1(N) = Z<t> therefore lie in 2Z --")
print("    which is exactly codex's 'a = b = 2t'. Same fact, read off the covering's definition.")

print("""
=== THE GENERALIZATION (this bench's addition) ===
    Nothing in the argument used the Gieseking manifold. The theorem is:

      For ANY nonorientable manifold N with H^1(N; F2) of rank 1, the restriction of
      Pin- structures to the orientation double cover is CONSTANT.

    Because rank 1 forces H^1(N;F2) = <w1>, and p^* w1 = 0 on the orientation cover by
    construction. The Gieseking (H1 = Z, hence H^1(-;F2) = F2) is one instance.

    CONTROL -- the hypothesis is doing work: a nonorientable N with rank >= 2 has classes
    other than w1 that need NOT die, so the restriction need not be constant. The rank-1
    condition is therefore not decorative, and codex's certificate is checking the right thing.

    CONSEQUENCE for the residual codex flags: the constant image is unnamed in their cert and
    NAMING it still needs their tangent-frame Pin- lift and the comparison to B1141's
    beat-selected sign. The generalization does not touch that half -- it explains why the map
    is constant, not which structure it is constant AT.""")
print("VERIFIED (topological half; the Pin- convention half is codex's, cited not re-run)")
