#!/usr/bin/env python3
"""B1532 -- THE READ-OUT: the subgroup sums, the census of counts on every abelian cover, and the run's checks.

    python3 read_out.py [--record]   ->  read_out.json (and read_out_log.txt)

Inputs: terms_T.jsonl and terms_L.jsonl (run_terms.py), part0_T.json and part0_L.json.  Each route is read on its own data; the
census is formed in each route and the two censuses are compared.

The subgroups.  T_n^ is the group of labels (a, b) in (Q/Z)^2 under addition (a character's exponents).  Every subgroup B is
generated by at most two elements (T_n has rank <= 2); all of them are found by closure, and their number is checked against
Toth's count for Z/m x Z/n, s(m, n) = sum over a | m, b | n of gcd(a, b), with (m, n) the invariant factors read from the labels.

The sums (Lemma S).  For a member nu and a class c: S(B) = sum over chi in B of the term T(nu, chi, c), for W1 and Lambda^2 W1.
  - one-class members: the class c1;
  - two-class members: the interior class, the generic class, and every special class x; at x a chi whose special set
    contains x contributes its special term and every other chi its generic term (Lemma J).  Special points are compared and
    merged per member by their exact value in the route's own coordinate; the coincidence structure (which (chi, family) share
    a class) is compared between the routes, and the census uses the structure both routes show.
A count is generation-shaped when S_W = S_L2 != 0; it carries N = -S_W generations (sm:B1515's dictionary).  The W2 order counts
the negatives at the conjugate classes (Lemma D), so |N| is what the question reads.

Checks (each listed with its count of failures):
  D1  Part 0 passed in both routes;
  D2  at every generic class the four pencils predict h^1 of E, E*, Lambda^2 E, (Lambda^2 E)*: h^1 = k + h0(S) - rank delta0
      + m - r, with rank delta0 = h0(Q) - (h0(M) - h0(S)) (a deficiency-one presentation);
  D3  at every rational special point the flagged family's h^1 is above its generic value;
  D4  gen2 = gen wherever gen2 was read;
  D5  route T = route L term by term (the one-class terms, the interior and generic terms, the multiset of special readings and
      the pencils' (m, k, rank, number of points)) under route L's signature;
  D6  conjugation (Lemma D): T(-nu, -chi) = T(nu, chi) at the one-class, interior and generic classes, in each route;
  D7  the design-time theorems, term by term (any failure is a bug): every term is at or above its lower bound
      (1 - h^1(nu chi rho), 1 - h^1(nu^-3 chi rho)); at the interior class a W term with nu chi simple and a Lambda^2 term with
      nu^-3 chi simple are 0 (Corollary I); at a boundary-type class a simple W term lies in [0, 1 - [chi = nu^4]] and a simple
      Lambda^2 term in [0, 1].  The h^1 are sm:B1515's banked census values.
The predictions P1-P8 are read as the PREREGISTRATION's section 7 states them (P1 from route_c_run.json, P2 after adjudicate.py)."""
import argparse
import itertools
import json
import math
import sys
import time
from collections import Counter, defaultdict
from fractions import Fraction as Fr
from pathlib import Path

HERE = Path(__file__).resolve().parent
FAMS = ("E", "E*", "L2E", "L2E*")
H1POS = {"E": (0, 1, 2), "E*": (0, 5, 6), "L2E": (1, 1, 2), "L2E*": (1, 5, 6)}    # (module, h0 index, h1 index) in a term


# ============================================================================================ loading
def load(path):
    """rows of complete members only: the rows that precede each member's done marker"""
    buf, out = defaultdict(list), {}
    if not path.exists():
        return out
    for line in path.read_text(encoding="utf-8").splitlines():
        r = json.loads(line)
        key = (r["n"], r["nu"])
        if r.get("done"):
            rows = buf.pop(key, [])
            assert len(rows) >= r["rows"], ("short member", key)
            for row in rows[-r["rows"]:]:
                out[(row["n"], row["nu"], row["chi"])] = row
        else:
            buf[key].append(r)
    return out


def lab_pair(lab):
    a, b = lab.split(",")
    return (Fr(a) % 1, Fr(b) % 1)


def lab_str(pr):
    return f"{pr[0]},{pr[1]}"


def neg(lab):
    a, b = lab_pair(lab)
    return lab_str(((-a) % 1, (-b) % 1))


def to_lsig(route, t):
    """route L's signature [I, a0, h1, t0, n, b0, h1*, s0, n*] of a term half (route T's r1, q1 -> n = a1 - r1, n* = b1 - q1)"""
    if route == "L":
        return list(t)
    I, a0, a1, t0, r1, b0, b1, s0, q1 = t
    return [I, a0, a1, t0, a1 - r1, b0, b1, s0, b1 - q1]


def sig(route, term):
    return [to_lsig(route, term[0]), to_lsig(route, term[1])]


# ============================================================================================ subgroups
def subgroups(labels):
    """every subgroup of the label group, as frozensets of labels: <g1, g2> over one generator of each pair of cyclic
    subgroups (every subgroup of a group of rank <= 2 is generated by two elements)"""
    elems = [lab_pair(x) for x in labels]
    eset = set(elems)

    def closure(gens):
        zero = (Fr(0), Fr(0))
        S, frontier = {zero}, [zero]
        while frontier:
            x = frontier.pop()
            for g in gens:
                y = ((x[0] + g[0]) % 1, (x[1] + g[1]) % 1)
                if y not in S:
                    S.add(y)
                    frontier.append(y)
        return frozenset(S)
    cyc = {}
    for g in elems:
        cyc.setdefault(closure([g]), g)
    out = set(cyc)
    gens = list(cyc.values())
    for g1, g2 in itertools.combinations(gens, 2):
        out.add(closure([g1, g2]))
    for s in out:
        assert s <= eset
    return [frozenset(lab_str(x) for x in s) for s in out]


def invariant_factors(labels):
    """(m, n) with T^ = Z/m x Z/n, m | n: n = the exponent, m = |T| / n"""
    order = len(labels)
    expo = 1
    for x in labels:
        a, b = lab_pair(x)
        o = math.lcm(a.denominator, b.denominator)
        expo = math.lcm(expo, o)
    return order // expo, expo


def toth(m, n):
    """Toth (2014): the number of subgroups of Z/m x Z/n is sum over a | m, b | n of gcd(a, b)"""
    dm = [d for d in range(1, m + 1) if m % d == 0]
    dn = [d for d in range(1, n + 1) if n % d == 0]
    return sum(math.gcd(a, b) for a in dm for b in dn)


def banked_h1(root):
    """sm:B1515's banked h^1(psi (x) rho) at every lam = 1 character, by label (route T's first prime of each level)"""
    rec = json.loads((root / "frontier/B1515_the_hyperbolic_point/verification/census_t_run.txt").read_text(encoding="utf-8"))
    out = defaultdict(dict)
    for r in rec["A"]:
        first = rec["primes"]["M%d" % r["level"]][0]
        if r["lam"] == "1" and r["field"] == f"GF({first})":
            out[r["level"]][",".join(r["char"])] = r["row"]["h1"]["V"]
    return out


def shift(lab, other, k=1):
    a, b = lab_pair(lab)
    c, d = lab_pair(other)
    return lab_str(((a + k * c) % 1, (b + k * d) % 1))


def scale(lab, k):
    a, b = lab_pair(lab)
    return lab_str(((k * a) % 1, (k * b) % 1))


def d7(route, R, h1, fails):
    """the design-time theorems term by term"""
    for (n, nu, chi), r in R.rows.items():
        hW = h1[n][shift(nu, chi)]
        hL = h1[n][shift(scale(nu, -3), chi)]
        nu4 = scale(nu, 4) == chi
        readings = [("c1", r["c"])] if r["kind"] == "one" else \
            [("int", r["int"]), ("gen", r["gen"][1])] + [("special", t) for pt, f, t in r["special"]]
        for cname, t in readings:
            w, l = t[0][0], t[1][0]
            if w < 1 - hW or l < 1 - hL:
                fails["D7"].append((route, (n, nu, chi), cname, "lower bound", w, l, hW, hL))
            if cname == "int":
                if (hW == 1 and w != 0) or (hL == 1 and l != 0):
                    fails["D7"].append((route, (n, nu, chi), cname, "Corollary I", w, l))
            else:
                if (hW == 1 and not 0 <= w <= 1 - nu4) or (hL == 1 and not 0 <= l <= 1):
                    fails["D7"].append((route, (n, nu, chi), cname, "simple range", w, l))


# ============================================================================================ one route's tables
class Route:
    def __init__(self, name, rows):
        self.name, self.rows = name, rows
        self.levels = sorted({k[0] for k in rows})
        self.members = defaultdict(set)
        self.chars = defaultdict(set)
        for (n, nu, chi) in rows:
            self.members[n].add(nu)
            self.chars[n].add(chi)

    def term_I(self, term):
        return (term[0][0], term[1][0])

    def checks(self, fails):
        """D2, D3, D4 within the route"""
        for key, r in self.rows.items():
            if r["kind"] != "two":
                continue
            gen = r["gen"][1]
            for fam in FAMS:
                m, k, rank, pts, h0S, h0Q = r["pencils"][fam]
                mod, i0, i1 = H1POS[fam]
                h0M, h1M = gen[mod][i0], gen[mod][i1]
                d0 = h0Q - (h0M - h0S)
                pred = k + h0S - d0 + m - rank
                if pred != h1M:
                    fails["D2"].append((self.name, key, fam, pred, h1M))
            for pt, fams, term in r["special"]:
                if pt[0] != "r":
                    continue
                for fam in fams:
                    mod, i0, i1 = H1POS[fam]
                    if not term[mod][i1] > gen[mod][i1]:
                        fails["D3"].append((self.name, key, pt, fam, term[mod][i1], gen[mod][i1]))
            if "gen2" in r and r["gen2"][1] != r["gen"][1]:
                fails["D4"].append((self.name, key))

    def conjugation(self, fails):
        for (n, nu, chi), r in self.rows.items():
            c = self.rows.get((n, neg(nu), neg(chi)))
            if c is None:
                fails["D6"].append((self.name, (n, nu, chi), "missing conjugate"))
                continue
            if r["kind"] != c["kind"]:
                fails["D6"].append((self.name, (n, nu, chi), "kind differs from the conjugate's"))
            elif r["kind"] == "one":
                if self.term_I(r["c"]) != self.term_I(c["c"]):
                    fails["D6"].append((self.name, (n, nu, chi)))
            else:
                if self.term_I(r["int"]) != self.term_I(c["int"]) or self.term_I(r["gen"][1]) != self.term_I(c["gen"][1]):
                    fails["D6"].append((self.name, (n, nu, chi)))

    def special_classes(self, n, nu):
        """{point: {chi: (fams, (I_W, I_L2))}} for a two-class member"""
        out = defaultdict(dict)
        for chi in self.chars[n]:
            r = self.rows[(n, nu, chi)]
            for pt, fams, term in r["special"]:
                out[tuple(pt)][chi] = (tuple(fams), self.term_I(term))
        return out

    def census(self, subs, coincidence_ok=None):
        """every (n, nu, class, B) -> (S_W, S_L2); returns the histogram and the generation-shaped list"""
        hist, shaped = Counter(), []
        self.degree_law = {"holds": 0, "fails": 0}
        for n in self.levels:
            groups = subs[n]
            for nu in sorted(self.members[n]):
                r0 = self.rows[(n, nu, "0,0")]
                if r0["kind"] == "one":
                    classes = {"c1": {chi: self.term_I(self.rows[(n, nu, chi)]["c"]) for chi in self.chars[n]}}
                    specials = {}
                else:
                    classes = {"int": {chi: self.term_I(self.rows[(n, nu, chi)]["int"]) for chi in self.chars[n]},
                               "gen": {chi: self.term_I(self.rows[(n, nu, chi)]["gen"][1]) for chi in self.chars[n]}}
                    specials = self.special_classes(n, nu)
                for cname, tab in classes.items():
                    for B in groups:
                        sw = sum(tab[chi][0] for chi in B)
                        sl = sum(tab[chi][1] for chi in B)
                        law = (sw, sl) == (len(B) * tab["0,0"][0], len(B) * tab["0,0"][1])
                        self.degree_law["holds" if law else "fails"] += 1
                        hist[(n, cname, sw, sl)] += 1
                        if sw == sl != 0:
                            shaped.append({"n": n, "nu": nu, "class": cname, "B": sorted(B), "|B|": len(B), "N": -sw})
                gen = classes.get("gen")
                for pt, spec in specials.items():
                    for B in groups:
                        hit = [chi for chi in spec if chi in B]
                        if not hit:
                            continue
                        sw = sum(gen[chi][0] for chi in B) + sum(spec[chi][1][0] - gen[chi][0] for chi in hit)
                        sl = sum(gen[chi][1] for chi in B) + sum(spec[chi][1][1] - gen[chi][1] for chi in hit)
                        base = spec["0,0"][1] if "0,0" in spec else gen["0,0"]
                        law = (sw, sl) == (len(B) * base[0], len(B) * base[1])
                        self.degree_law["holds" if law else "fails"] += 1
                        hist[(n, "special", sw, sl)] += 1
                        if sw == sl != 0:
                            shaped.append({"n": n, "nu": nu, "class": ["special", list(pt), sorted(hit)], "B": sorted(B),
                                           "|B|": len(B), "N": -sw})
        return hist, shaped


# ============================================================================================ the comparison (D5)
def row_signature(route, r):
    """the route-independent content of one (n, nu, chi) row, under route L's signature: the one-class term; or the interior and
    generic terms, the pencils' (m, k, rank, number of points, h0(S), h0(Q)) and the multiset of special readings (a conjugate
    pair counts twice)"""
    if r["kind"] == "one":
        return json.dumps(["one", sig(route, r["c"])])
    pen = {f: r["pencils"][f][:3] + [sum(1 if q[0] == "r" else 2 for q in r["pencils"][f][3])] + r["pencils"][f][4:]
           for f in FAMS}
    spec = sorted(json.dumps([sorted(fm), sig(route, t)]) for pt, fm, t in r["special"] for _ in range(1 if pt[0] == "r" else 2))
    return json.dumps(["two", sig(route, r["int"]), sig(route, r["gen"][1]), pen, spec], sort_keys=True)


def compare(T_, L_, fails):
    for key in sorted(set(T_.rows) | set(L_.rows)):
        a, b = T_.rows.get(key), L_.rows.get(key)
        if a is None or b is None:
            fails["D5"].append((key, "missing in one route"))
        elif row_signature("T", a) != row_signature("L", b):
            fails["D5"].append((key, "differ"))


def coincidence_structure(R, n, nu):
    """the multiset of {(chi, fams)} over the member's special classes (route-independent)"""
    sc = R.special_classes(n, nu)
    out = Counter()
    for pt, spec in sc.items():
        out[tuple(sorted((chi, f) for chi, (f, _) in spec.items()))] += 1 if pt[0] == "r" else 2
    return out


# ============================================================================================ main
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--record", action="store_true")
    ap.add_argument("--dir", default=str(HERE))
    a = ap.parse_args()
    d = Path(a.dir)
    t0 = time.time()
    lines = []

    def log(msg):
        print(msg, flush=True)
        lines.append(msg)
    out = {"D1 Part 0": {}}
    for route in ("T", "L"):
        p0 = d / f"part0_{route}.json"
        out["D1 Part 0"][route] = json.loads(p0.read_text())["passed"] if p0.exists() else None
    R = {route: Route(route, load(d / f"terms_{route}.jsonl")) for route in ("T", "L")}
    fails = defaultdict(list)
    subs, sub_info = {}, {}
    for n in sorted(set(R["T"].levels) | set(R["L"].levels)):
        labels = sorted(R["T"].chars[n] or R["L"].chars[n])
        S = subgroups(labels)
        m_, n_ = invariant_factors(labels)
        subs[n] = S
        sub_info[n] = {"|T_n|": len(labels), "invariant factors": [m_, n_], "subgroups": len(S), "Toth": toth(m_, n_),
                       "orders": dict(sorted(Counter(len(s) for s in S).items()))}
        if len(S) != toth(m_, n_):
            fails["subgroups"].append((n, len(S), toth(m_, n_)))
    out["subgroups"] = sub_info
    ROOT = Path(__import__("os").environ.get("ORIGIN_AXIOM_ROOT", HERE.parents[2]))
    h1 = banked_h1(ROOT)
    for route in ("T", "L"):
        R[route].checks(fails)
        R[route].conjugation(fails)
        d7(route, R[route], h1, fails)
    compare(R["T"], R["L"], fails)
    coinc = []
    for n in R["T"].levels:
        for nu in R["T"].members[n]:
            if R["T"].rows[(n, nu, "0,0")]["kind"] == "two":
                if coincidence_structure(R["T"], n, nu) != coincidence_structure(R["L"], n, nu):
                    coinc.append((n, nu))
    out["coincidence structure differs (members)"] = coinc
    cens = {}
    for route in ("T", "L"):
        hist, shaped = R[route].census(subs)
        cens[route] = {"histogram": {f"{k}": v for k, v in sorted(hist.items())}, "generation-shaped": shaped,
                       "degree law (S = |B| T(nu, 1, c))": dict(R[route].degree_law),
                       "N values": dict(sorted(Counter(s["N"] for s in shaped).items())),
                       "|N| = 3": [s for s in shaped if abs(s["N"]) == 3]}
    out["census"] = {r: {k: v for k, v in c.items() if k != "histogram"} for r, c in cens.items()}
    out["histogram"] = cens["T"]["histogram"]
    def canon(s):
        cl = s["class"] if isinstance(s["class"], str) else ("special", tuple(s["class"][2]))
        return json.dumps([s["n"], s["nu"], cl, s["B"], s["N"]])
    ct, cl_ = Counter(map(canon, cens["T"]["generation-shaped"])), Counter(map(canon, cens["L"]["generation-shaped"]))
    out["censuses agree"] = ct == cl_
    out["census differences (first 10)"] = [list((ct - cl_).items())[:10], list((cl_ - ct).items())[:10]]
    # ---------------------------------------------------------------------------------------- the predictions (section 7)
    shT = cens["T"]["generation-shaped"]
    pred = {}
    rc = d / "route_c_run.json"
    pred["P1 route C = route T"] = json.loads(rc.read_text())["all agree"] if rc.exists() else "route_c_run.json missing"
    adj = d / "adjudicate.json"
    pred["P2 no unresolved D5 disagreement"] = (len(fails["D5"]) == 0) if not adj.exists() else \
        json.loads(adj.read_text())["unresolved"] == 0
    pred["P3 no generation-shaped count on M2-M5"] = not any(x["n"] < 6 for x in shT)
    pred["P4 a generation-shaped count on M6"] = any(x["n"] == 6 for x in shT)
    pred["P5 |N| = 3 on M6"] = any(x["n"] == 6 and abs(x["N"]) == 3 for x in shT)
    pred["P6 an order-8 two-class member generation-shaped at c_int, B = 1"] = any(
        x["class"] == "int" and x["B"] == ["0,0"] for x in shT)
    p7 = []
    for (n, nu, chi), r in R["T"].rows.items():
        if r["kind"] != "two":
            continue
        for fam in FAMS:
            if r["pencils"][fam][3]:
                ok = (fam == "E" and h1[n][shift(nu, chi)] >= 2) or (fam == "L2E*" and h1[n][shift(scale(nu, -3), chi)] >= 2)
                if not ok:
                    p7.append((n, nu, chi, fam))
    pred["P7 special points only at E with nu chi in NS and (L2E)* with nu^-3 chi in NS"] = not p7
    out["P7 exceptions (first 10)"] = p7[:10]
    p8 = []
    for (n, nu, chi), r in R["T"].rows.items():
        if h1[n][shift(scale(nu, -3), chi)] != 1:
            continue
        readings = [r["c"]] if r["kind"] == "one" else [r["gen"][1]] + [t for pt, f, t in r["special"]]
        if any(t[1][0] != 0 for t in readings):
            p8.append((n, nu, chi))
    pred["P8 simple Lambda^2 terms 0 at boundary-type classes"] = not p8
    pred["P9 the degree law at every (nu, c, B)"] = cens["T"]["degree law (S = |B| T(nu, 1, c))"]["fails"] == 0
    out["P8 exceptions (first 10)"] = p8[:10]
    out["predictions"] = pred
    out["checks"] = {k: len(v) for k, v in fails.items()}
    out["check failures (first 10 each)"] = {k: v[:10] for k, v in fails.items()}
    out["seconds"] = round(time.time() - t0, 1)
    log(json.dumps({k: v for k, v in out.items() if k not in ("histogram", "census")}, indent=1, default=str))
    log(json.dumps({r: {"N values": c["N values"], "|N| = 3": len(c["|N| = 3"])} for r, c in out["census"].items()}, indent=1))
    log(json.dumps(out["predictions"], indent=1))
    if a.record:
        (d / "read_out.json").write_text(json.dumps(out, indent=1, default=str) + "\n", encoding="utf-8")
        (d / "d5_failures.json").write_text(json.dumps(fails["D5"], default=str) + "\n", encoding="utf-8")
        (d / "read_out_log.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out


if __name__ == "__main__":
    main()
