#!/usr/bin/env python3
"""B1532 -- route C: the cover read whole.  Library; nothing sealed is computed on import.

For a subgroup B of T_n^ (characters trivial on the cusp) with generators chi_1, ..., chi_r, let psi = (chi_1, ..., chi_r):
Gamma_n -> A = psi(Gamma_n), a finite abelian group with A^ = B and psi(P) = 1.  The regular cover M_A carries the pullback p*E,
and by Shapiro (Kedlaya, Lemma 3.2.3) with the tensor identity Ind(Res E) = E (x) C[A] and Mackey on the cusps (|A| cusps, each
with peripheral group P since psi(P) = 1):
    H*(M_A; p*E) = H*(M_n; E (x) C[A]),   H*(cusps of M_A; p*E) = H*(P; E (x) C[A]),
compatibly with restriction.  So the interior index of the pulled-back member on the cover is I_{M_n}(E (x) C[A]), read here with
C[A] the regular PERMUTATION module (g acts by translation by psi(g)), never split into characters.  Route T splits it (Lemma S);
route C does not, so their agreement checks the splitting and every character's exponents.  It uses route T's index (sm:B1515's
A.ix) on the larger module."""
import cover_lib_t as CT
from sympy.polys.matrices import DomainMatrix

RT, T = CT.RT, CT.T


def image_group(LT, chis):
    """A = psi(Gamma) for psi = (chi_1, ..., chi_r), as exponent tuples mod K, with psi on the generators"""
    exps = [LT.exponents(ab) for ab in chis]
    psi = {g: tuple(e[g] % LT.K for e in exps) for g in LT.gens}
    zero = tuple(0 for _ in exps)
    elems, frontier, seen = [zero], [zero], {zero}
    while frontier:
        x = frontier.pop()
        for g in LT.gens:
            for s in (1, -1):
                y = tuple((a + s * b) % LT.K for a, b in zip(x, psi[g]))
                if y not in seen:
                    seen.add(y)
                    elems.append(y)
                    frontier.append(y)
    return elems, psi


def kron(X, Y):
    xr, xc = X.shape
    yr, yc = Y.shape
    dom = X.domain
    Xl, Yl = X.to_list(), Y.to_list()
    rows = [[dom.zero] * (xc * yc) for _ in range(xr * yr)]
    for i in range(xr):
        for j in range(xc):
            a = Xl[i][j]
            if a == dom.zero:
                continue
            for k in range(yr):
                for l in range(yc):
                    b = Yl[k][l]
                    if b != dom.zero:
                        rows[i * yr + k][j * yc + l] = a * b
    return DomainMatrix(rows, (xr * yr, xc * yc), dom)


def induced(LT, rep, elems, psi):
    """rep (x) C[A]: g -> rep(g) (x) (the permutation x -> x + psi(g))"""
    idx = {x: i for i, x in enumerate(elems)}
    n, dom = len(elems), LT.dom
    out = {}
    for g in rep.gens:
        rows = [[dom.zero] * n for _ in range(n)]
        for x in elems:
            y = tuple((a + b) % LT.K for a, b in zip(x, psi[g]))
            rows[idx[y]][idx[x]] = dom.one
        out[g] = kron(rep.M[g], DomainMatrix(rows, (n, n), dom))
    return T.DMRep(rep.gens, out)


def generators(LT, B):
    """at most two labels generating the subgroup B (a set of labels)"""
    from fractions import Fraction as Fr
    pairs = {lab: tuple(Fr(x) % 1 for x in lab.split(",")) for lab in B}

    def close(gs):
        zero = (Fr(0), Fr(0))
        S, fr = {zero}, [zero]
        while fr:
            x = fr.pop()
            for g in gs:
                y = ((x[0] + g[0]) % 1, (x[1] + g[1]) % 1)
                if y not in S:
                    S.add(y)
                    fr.append(y)
        return S
    target = set(pairs.values())
    labs = sorted(B)
    for a in labs:
        if close([pairs[a]]) == target:
            return [a]
    for i, a in enumerate(labs):
        for b in labs[i + 1:]:
            if close([pairs[a], pairs[b]]) == target:
                return [a, b]
    raise AssertionError("not generated by two elements")


def ab_of(LT, lab):
    from fractions import Fraction as Fr
    a, b = (Fr(x) for x in lab.split(","))
    return (int(a * LT.N) % LT.N, int(b * LT.N) % LT.N)


def cover_index(LT, member, c, B):
    """(I of W1(c) (x) C[A], I of Lambda^2 W1(c) (x) C[A]) and their B1297 data, for the subgroup B (labels)"""
    gens = generators(LT, B)
    elems, psi = image_group(LT, [ab_of(LT, x) for x in gens])
    assert len(elems) == len(B), ("|A| != |B|", len(elems), len(B))
    W = member.W1(c)
    E, L2 = induced(LT, W, elems, psi), induced(LT, T.wedge2_rep(W), elems, psi)
    return [CT.compact(LT.ix(E)), CT.compact(LT.ix(L2))]
