#!/usr/bin/env python3
"""Exact count of the order-4 elements of the torus exp(u(1)_Y + u(1)_gamma) c SU(6) c E6 and which of them leave exactly the
SM roots of su(6) unbroken (B1364/B1365: twelve order-4 elements, four reaching the SM, all squaring to one triplet-type involution).
Also Kac's order-4 classes modulo the diagram automorphism (B1363: eleven)."""
import itertools, numpy as np, sympy as sp
from fractions import Fraction as Fr
exec(open(__import__('pathlib').Path(__file__).with_name('e6_own.py')).read().replace("np.linspace(0,2*np.pi,721)[:-1]","[]"))
# exact rational charges: Y(r) and gamma(r) with gamma scaled so charges are rational: gamma_unit = (1,1,1,1,1,-sqrt3*?)... compute gamma exactly: orthogonal to SM roots, Y, beta -> gamma ∝ (1,1,1,1,1, -5/sqrt3)?? check numerically
g=gamma/gamma[0]; print('gamma/gamma0 =', np.round(g,6), ' g5*sqrt3 =', g[5]*np.sqrt(3))
# so gamma ∝ (1,1,1,1,1,-5/sqrt3). Use integer charges: Ycharge = 6*Y(r) (integer), Gcharge = <r, (1,1,1,1,1,-5/sqrt3)>*? for spinor roots: sum(±1/2)*1 + (±sqrt3/2)(-5/sqrt3) = (k/2) ∓ 5/2 -> half-integers; take 2*<r,gv>.
gv=np.array([1,1,1,1,1,-5/np.sqrt(3)])
def charges(v):
    a=6*(v@Y); b=6*(v@gv); assert abs(a-round(a))<1e-9 and abs(b-round(b))<1e-9, (a,b); return (int(round(a)), int(round(b)))
allw=np.vstack([R,W27])
Lgen=[charges(v) for v in allw]
# lattice L generated by the charge pairs; torus elements of order dividing 4 = Hom(L, Z/4); enumerate homomorphisms via a basis of L (Smith form)
Mrows=sp.Matrix(list({c for c in Lgen}))
from sympy.matrices.normalforms import smith_normal_form
# find a Z-basis of L: use HNF via sympy on the transpose
H=sp.Matrix(Lgen).T  # 2 x N
# lattice basis by integer column reduction: compute the Smith decomposition M = U D V
D=smith_normal_form(H,domain=sp.ZZ); print('Smith diag of the charge lattice generators:', [D[i,i] for i in range(2)])
# Simpler: an element is a pair (a,b) in (Q/Z)^2 with a*Yc + b*Gc in Z for the generators lattice... use characters chi(v)=exp(2 pi i (a*Yc(v)+b*Gc(v))); order 4 <=> 4(a Yc + b Gc) in Z for all v; parametrise a,b in (1/4N) Z with N = lattice index... brute force a,b in {k/48: k=0..47}
sols=[]
for ka in range(144):
    for kb in range(144):
        a=Fr(ka,144); b=Fr(kb,144)
        ph=[(a*yc+b*gc) for yc,gc in Lgen]
        if all((4*p).denominator==1 for p in ph) and not all((2*p).denominator==1 for p in ph):
            sols.append((a,b))
# distinct torus elements = distinct character tables on the generators
uniq={}
for a,b in sols:
    key=tuple(((a*yc+b*gc)%1) for yc,gc in Lgen)
    uniq[key]=(a,b)
print('order-4 elements of the torus (acting faithfully on roots+27):', len(uniq))
non=[r for r in perp if not any(np.allclose(r,s) for s in SMroots)]
reach=[]; squares={}
for key,(a,b) in uniq.items():
    fixed_non=sum(1 for r in non if ((a*charges(r)[0]+b*charges(r)[1])%1)==0)
    fixed_all=sum(1 for r in R if ((a*charges(r)[0]+b*charges(r)[1])%1)==0)
    sq=tuple(((2*(a*yc+b*gc))%1) for yc,gc in Lgen)
    if fixed_non==0: reach.append((a,b,fixed_all)); squares[sq]=squares.get(sq,0)+1
print('elements fixing NO non-SM root of su(6):', len(reach), ' (their fixed E6 roots counts:', sorted({x[2] for x in reach}),')')
print('distinct squares among the SM-reaching elements:', len(squares))
# the square: which roots does it fix? (triplet-type involution: fixes ... ) list fixed E6 roots count of the square
for sq in squares:
    fixed=[r for r,(yc,gc) in zip(allw[:72],Lgen[:72]) if sq[Lgen.index((yc,gc))]==0]
    print('  square fixes', len(fixed), 'E6 roots')
# Kac order-4 classes modulo the diagram Z/2 (swap 1<->5, 2<->4)
marks={0:1,1:1,2:2,3:3,4:2,5:1,6:2}; swap={0:0,1:5,2:4,3:3,4:2,5:1,6:6}
sol=set()
for s in itertools.product(range(5),repeat=7):
    if sum(marks[i]*s[i] for i in range(7))==4: sol.add(s)
orbits=set()
for s in sol:
    t=tuple(s[swap[i]] for i in range(7)); orbits.add(min(s,t))
print('Kac order-4 solutions', len(sol), 'modulo the diagram automorphism', len(orbits))
sol3={s for s in itertools.product(range(4),repeat=7) if sum(marks[i]*s[i] for i in range(7))==3}
print('Kac order-3 solutions', len(sol3), 'modulo the diagram automorphism', len({min(s,tuple(s[swap[i]] for i in range(7))) for s in sol3}))
print('--- the SM-reaching elements (a,b) with a in units of Y/6-charge, b of the 2<r,gv>-charge, their squares, and inverse pairing:')
def key_of(a,b): return tuple(((a*yc+b*gc)%1) for yc,gc in Lgen)
for a,b,fa in reach:
    inv=key_of(-a,-b); partner=[(a2,b2) for a2,b2,_ in reach if key_of(a2,b2)==inv]
    sq=tuple(((2*(a*yc+b*gc))%1) for yc,gc in Lgen)
    # which 27 weights does the square fix (charge classes)?
    fixed27=sum(1 for w in W27 if ((2*(a*charges(w)[0]+b*charges(w)[1]))%1)==0)
    print(f'  (a,b)=({a},{b}) inverse in set: {bool(partner)}  square fixes {fixed27} of the 27 weights; square id {hash(sq)%10000}')
