#!/usr/bin/env python3
"""Resolve Paper I's m=12 proper-versus-improper form-class discrepancy.

This is an exact finite reduction calculation using only the Python standard
library.  Proper cycles are generated by the classical rho operation.  Full
GL(2,Z) equivalence additionally quotients them by the determinant-minus-one
variable swap (x,y)->(y,x), sending (a,b,c) to (c,b,a).
"""

from math import gcd, isqrt


def primitive_reduced_forms(discriminant):
    root = isqrt(discriminant)
    forms = []
    for a in range(-root-2, root+3):
        if a == 0:
            continue
        for b in range(-root-2, root+3):
            if (b*b-discriminant) % (4*a):
                continue
            c = (b*b-discriminant)//(4*a)
            if gcd(gcd(abs(a), abs(b)), abs(c)) != 1:
                continue
            if b*b-4*a*c != discriminant:
                continue
            if not (0 < b <= root):
                continue
            if not (root-b < 2*abs(a) < root+b):
                continue
            forms.append((a,b,c))
    return forms


def rho(form, discriminant):
    a,b,c = form
    root = isqrt(discriminant)
    if abs(c) > root:
        bp = -b + 2*abs(c)*((b+abs(c))//(2*abs(c)))
    else:
        bp = -b + 2*abs(c)*((root+b)//(2*abs(c)))
    return (c,bp,(bp*bp-discriminant)//(4*c))


def proper_cycles(discriminant):
    forms = primitive_reduced_forms(discriminant)
    form_set = set(forms)
    cycles = []
    owner = {}
    for form in forms:
        if form in owner:
            continue
        cycle=[]
        current=form
        while current not in cycle:
            assert current in form_set
            cycle.append(current)
            current=rho(current,discriminant)
        assert current == form
        index=len(cycles)
        cycles.append(tuple(cycle))
        for member in cycle:
            assert member not in owner
            owner[member]=index
    assert set(owner)==form_set
    return cycles,owner


def gl_classes(discriminant):
    cycles,owner=proper_cycles(discriminant)
    parent=list(range(len(cycles)))

    def find(i):
        while parent[i] != i:
            parent[i]=parent[parent[i]]
            i=parent[i]
        return i

    def union(i,j):
        i,j=find(i),find(j)
        if i != j:
            parent[j]=i

    swaps=[]
    for index,cycle in enumerate(cycles):
        a,b,c=cycle[0]
        swapped=(c,b,a)
        # The reduced inequalities are symmetric in |a| and |c| here.
        assert swapped in owner
        mate=owner[swapped]
        swaps.append((index,mate,cycle[0],swapped))
        union(index,mate)
    classes={find(i) for i in range(len(cycles))}
    return cycles,swaps,len(classes)


proper_counts=[]
full_gl_counts=[]
for m in range(1,13):
    discriminant=m*m+4
    cycles,swaps,count=gl_classes(discriminant)
    proper_counts.append(len(cycles))
    full_gl_counts.append(count)

assert proper_counts == [1,1,1,1,1,2,1,1,2,2,1,3]
assert full_gl_counts == [1,1,1,1,1,2,1,1,2,2,1,2]

cycles,swaps,count=gl_classes(148)
representatives=[cycle[0] for cycle in cycles]
assert len(cycles)==3 and count==2

# Exhibit the missed improper equivalence explicitly:
# -7*x^2+6*x*y+4*y^2 -> 4*x^2+6*x*y-7*y^2 under x<->y.
assert (-7,6,4) in representatives
first=next(i for i,cycle in enumerate(cycles) if (-7,6,4) in cycle)
second=next(i for i,cycle in enumerate(cycles) if (4,6,-7) in cycle)
principal=next(i for i,cycle in enumerate(cycles) if (1,12,-1) in cycle)
assert first != second
assert any(i==first and mate==second for i,mate,_,_ in swaps)
assert any(i==principal and mate==principal for i,mate,_,_ in swaps)

print("proper class counts m=1..12:", proper_counts)
print("full GL class counts m=1..12:", full_gl_counts)
print("D=148 proper-cycle representatives:", representatives)
print("improper swap: (-7,6,4) -> (4,6,-7)")
print("swap matrix determinant: -1")
print("D=148 verdict: 3 proper SL classes, 2 full GL classes")
print("PAPER-I m=12 DISCREPANCY RESOLVED")
