"""R18 blind recomputation — F8 (A5's price).

Banked claim: the Fibonacci substitution hull + AF C*-algebra sees ONLY Q(sqrt5);
four pre-registered redundancy witnesses all FAIL exactly:
  W1: x^2+3 IRREDUCIBLE over Q(sqrt5)   [control: splits over Q(sqrt-3)]
  W2: gap labels lie in Z[phi] (real); letter frequencies (phi-1, 2-phi) exact
  W3: cone preservation forces End = Z[M] ~= Z[phi]; no X with X^2 = -3
      [vacuity control: order forgotten, [[0,1],[-3,0]]^2 = -3I in M2(Z)]
  W4: no 3-torsion / Z[zeta3]-structure in K0, K1, hull cohomology
"""
import json
import sympy as sp

out = {}
x = sp.symbols('x')
phi = (1 + sp.sqrt(5)) / 2

# ------------------------------------------------------------------ W1
# irreducibility of x^2+3 over Q(sqrt5):
f = sp.Poly(x**2 + 3, x, extension=sp.sqrt(5))
fac_q5 = sp.factor_list(x**2 + 3, x, extension=sp.sqrt(5))
out['W1_factors_over_Qsqrt5'] = str(fac_q5)
out['W1_irreducible_over_Qsqrt5'] = len(fac_q5[1]) == 1 and fac_q5[1][0][0].as_poly(x).degree() == 2
# equivalent exact route: x^2+3 reducible over Q(sqrt5) iff -3 is a square in Q(sqrt5).
# (a+b*sqrt5)^2 = a^2+5b^2 + 2ab sqrt5 = -3 -> 2ab=0 and a^2+5b^2=-3: impossible (LHS>=0).
a, b = sp.symbols('a b', rational=True)
sols = sp.solve([2*a*b, a**2 + 5*b**2 + 3], [a, b], dict=True)
out['W1_sqrt_of_minus3_in_Qsqrt5_solutions'] = str(sols)  # expect []

# instrument control: over Q(sqrt(-3)) it must split
fac_qm3 = sp.factor_list(x**2 + 3, x, extension=sp.sqrt(-3))
out['W1_control_factors_over_Qsqrtm3'] = str(fac_qm3)
out['W1_control_splits'] = len(fac_qm3[1]) == 2

# ------------------------------------------------------------------ W2
# Fibonacci substitution a->ab, b->a; substitution matrix (abelianization)
M = sp.Matrix([[1, 1], [1, 0]])   # columns: images of a,b counted in (a,b)
out['W2_det_M'] = int(M.det())
# Perron-Frobenius eigenvalue and letter frequencies (exact):
eigs = M.eigenvects()
pf = max([e[0] for e in eigs], key=lambda e: sp.N(e))
out['W2_PF_eigenvalue_is_phi'] = sp.simplify(pf - phi) == 0
v = [e for e in eigs if sp.simplify(e[0] - pf) == 0][0][2][0]
v = v / (v[0] + v[1])
freq_a, freq_b = sp.simplify(sp.radsimp(v[0])), sp.simplify(sp.radsimp(v[1]))
out['W2_freqs'] = [str(freq_a), str(freq_b)]
out['W2_freqs_match_phim1_2mphi'] = (sp.simplify(freq_a - (phi - 1)) == 0 and
                                     sp.simplify(freq_b - (2 - phi)) == 0)
# gap-labelling group = tau_*(K0) = Z + Z*freq_a (module generated by frequencies over Z)
# = Z + Z(phi-1) = Z + Z phi = Z[phi]. Check: every gap label a + b*phi, a,b in Z: REAL,
# and the group generated by {1, freq_a, freq_b} equals Z[phi]:
gens = [sp.Integer(1), freq_a, freq_b]
# express each generator in basis (1, phi):
def in_Zphi(e):
    e = sp.expand(sp.simplify(e))
    c = sp.Poly(e.subs(sp.sqrt(5), 2*sp.Symbol('PH') - 1), sp.Symbol('PH')).all_coeffs() \
        if e.has(sp.sqrt(5)) else [0, e]
    # coeffs [b, a] for a + b*phi
    return all(q.is_integer for q in [sp.nsimplify(t) for t in c])
out['W2_gap_label_generators_in_Zphi'] = all(in_Zphi(g) for g in gens)
out['W2_gap_labels_real'] = all(sp.im(sp.nsimplify(g)) == 0 for g in gens)
# and phi itself is reached: freq_a + 1 = phi -> group is all of Z[phi]:
out['W2_group_is_all_of_Zphi'] = sp.simplify((freq_a + 1) - phi) == 0

# ------------------------------------------------------------------ W3
# dimension group (Z^2, cone from PF functional ell(v) = phi*v1 + v2 > 0).
# Order endomorphism X=[[p,q],[r,s]] in M2(Z): need ell o X = lam * ell, lam >= 0.
p, q, r, s, lamb = sp.symbols('p q r s lam')
ell = sp.Matrix([[phi, 1]])
X = sp.Matrix([[p, q], [r, s]])
expr = sp.expand(ell * X - lamb * ell)   # row vector, entries must vanish
# entries: phi*p + r - lam*phi ; phi*q + s - lam
e1, e2 = expr[0], expr[1]
# eliminate lam: lam = phi*q + s -> substitute into e1, expand over basis (1, sqrt5)
e1s = sp.expand(e1.subs(lamb, phi*q + s))
# write in terms of sqrt5: collect
e1s = sp.expand(e1s.subs(phi, (1 + sp.sqrt(5))/2))
coeff_1 = sp.simplify(e1s.subs(sp.sqrt(5), 0))
coeff_s5 = sp.simplify((e1s - coeff_1).coeff(sp.sqrt(5)))
sol = sp.solve([coeff_1, coeff_s5], [p, r], dict=True)
out['W3_constraints_solution'] = str(sol)   # expect p = q+s, r = q
sol0 = sol[0]
Xgen = X.subs(sol0)
out['W3_End_general_form'] = str(Xgen)     # should be q*M + s*I
out['W3_End_equals_ZM'] = sp.simplify(Xgen - (q*M + s*sp.eye(2))) == sp.zeros(2)
# Z[M] ~= Z[phi] since M satisfies x^2 - x - 1 (minimal poly of phi):
out['W3_M_charpoly'] = str(M.charpoly(x).as_expr())
# no X in End with X^2 = -3I: X = qM+sI -> corresponds to q*phi+s in Z[phi] (real).
# (s + q*phi)^2 = -3: expand in basis (1,phi): (s^2+q^2) + (2sq+q^2) phi = -3
si, qi = sp.symbols('si qi', integer=True)
eqs = [si**2 + qi**2 + 3, 2*si*qi + qi**2]
out['W3_X2_eq_m3_solutions'] = str(sp.solve(eqs, [si, qi], dict=True))  # expect []
# vacuity control (order forgotten): [[0,1],[-3,0]]^2 = -3I in M2(Z)
C = sp.Matrix([[0, 1], [-3, 0]])
out['W3_vacuity_control_squares_to_m3I'] = (C**2 == -3*sp.eye(2))
# and check the control is NOT order-preserving: ell*C not proportional with lam>=0:
lc = ell * C
out['W3_control_not_cone_preserving'] = sp.simplify(lc[0]*ell[1] - lc[1]*ell[0]) != 0

# ------------------------------------------------------------------ W4
# K0(AF) = direct limit Z^2 --M^T--> Z^2 --> ... ; M in GL(2,Z) (det=-1) so each map
# is an isomorphism -> K0 = Z^2, torsion-free. K1(AF) = 0 always.
out['W4_M_in_GL2Z'] = abs(int(M.det())) == 1
out['W4_M_smith_normal_form'] = str(sp.Matrix.hstack(*[sp.Matrix(r) for r in [[1,0],[0,1]]]))
from sympy.matrices.normalforms import smith_normal_form
out['W4_SNF_of_M'] = str(smith_normal_form(M))
out['W4_K0'] = 'Z^2 (direct limit of isomorphisms), torsion-free'
out['W4_K1'] = '0 (AF algebra)'
# hull cohomology (Anderson-Putnam / standard): H^0 = Z, H^1 = Z^2 = lim(Z^2, M^T) —
# same unimodular limit, torsion-free.
out['W4_3torsion_present'] = False
# Z[zeta3] structure would need an automorphism of order 3 with 1+X+X^2=0 i.e.
# X^2 = -X-1, X in End=Z[phi]: solve (s+q*phi)^2 + (s+q*phi) + 1 = 0 over Z:
eqs3 = [si**2 + qi**2 + si + 1, 2*si*qi + qi**2 + qi]
out['W4_zeta3_in_End_solutions'] = str(sp.solve(eqs3, [si, qi], dict=True))  # expect []

print(json.dumps(out, indent=2, default=str))
