#!/usr/bin/env python3
"""B1384 -- the web seat's corrective handoff of 2026-09-27, checked on this bench with this seat's own code.

The handoff's thirteen verifiers were re-run unchanged (record `rerun_record.txt`); this file re-derives the load-bearing
claims independently: own Reidemeister-Schreier covers of m004, own induction, own E8 roots, and B1374's index library
(`index_lib.py`: the one-cusped index I = n(V) - n(V*), n = a1 - r1, main's B1297 definition, over prime fields).

  S0 the signed state: -I = (L^2 R^-1)^2 in the group generated by the two shears (m003 = -LR is reachable once inverses are)
  S1 the common SL5 (handoff item A): in the E8 root system, with ws:R40's two orthogonal A4's (gauge: e0-e1, e1-e2, e2-e3,
     e3-e4; structure: e6-e7, e5-e6, e6+e7, -(e0+...+e7)/2), the roots commuting with SU3 x SU2 x U1_Y placed in the gauge
     A4 are exactly the 20 structure-A4 roots; an E6 through the gauge A4 (adjoin x, z) has 72 roots and SM-centraliser
     {+-beta}, beta = e6+e7; the structure A4 is sl2_beta + A2_family (6 roots) + 12 mixed roots with beta-weight +-1
  S2 the parabolic lemma (item E): for G = [[A, X], [0, B]] in P_{2,3}, G N(Y) G^-1 = N(A Y B^-1) -- X cancels; and a
     g in SL5 normalising n_+ preserves the 2-plane U (so N(n_+) = P_{2,3}), checked on random elements
  S3 one versus three is Shapiro and Mackey (items B, C): own covers M2 and M6 of m004 (index 2 and 6 in pi_1 = <a, b |
     abABaBAbaB>, transversal a^k); Gamma6 is normal of index 3 in Gamma2 with a^2 generating the quotient and lying on the
     cusp, so the cusp stays connected; for rank-2 non-split seeds V on M6, Ind V on M2 has exactly V's five numbers
     (a0, a1, t0, t1, r1), for V and V*, hence the same index; the coset generator T = Ind V(a^2) has T^3 = diag(rho(mu6))
     three times -- non-trivial unipotent exactly when V is non-split at the cusp, with (T^3 - 1)^2 = 0
  S4 the Sym^4 control and its order-5 twists on M2 (items F, G): Sym^4(rho_geo) is self-dual, so I = 0; the cusp-trivial
     order-5 characters chi of M2 give V = Sym^4(rho_geo) (x) chi with (a0, a1, t0, t1, r1) = (0, 1, 1, 2, 1) for V and V*,
     so I = 0 -- over three primes
Usage: python3 handoff_checks.py"""
import importlib.util
import itertools
import random
from fractions import Fraction as Fr
from pathlib import Path

HERE = Path(__file__).resolve().parent
_LIB = HERE.parents[1] / "B1374_the_class_index_in_the_sm_frame" / "verification" / "index_lib.py"
_spec = importlib.util.spec_from_file_location("b1374_index_lib", _LIB)
IL = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(IL)

RELATOR = "abABaBAbaB"            # pi_1(m004) with two meridians a, b (B1141 / B1382)
LONGITUDE = "bABaaBAb"            # commutes with the meridian a (B1382 S6)
PRIMES = (601, 1201, 1321)        # p = 1 mod 120: cube roots of unity, fifth roots, 40th roots


# ----------------------------------------------------------------------------------------------------------- S0
def s0_signed_state():
    def mm(X, Y):
        return [[sum(X[i][k] * Y[k][j] for k in range(2)) for j in range(2)] for i in range(2)]
    L, R, Rinv = [[1, 0], [1, 1]], [[1, 1], [0, 1]], [[1, -1], [0, 1]]
    w = mm(mm(L, L), Rinv)
    assert mm(w, w) == [[-1, 0], [0, -1]]
    return "(L^2 R^-1)^2 = -I"


# ----------------------------------------------------------------------------------------------------------- S1
def e8_roots():
    roots = []
    for i, j in itertools.combinations(range(8), 2):
        for si, sj in itertools.product((1, -1), repeat=2):
            v = [0] * 8
            v[i], v[j] = si, sj
            roots.append(tuple(Fr(x) for x in v))
    for signs in itertools.product((1, -1), repeat=8):
        if signs.count(-1) % 2 == 0:
            roots.append(tuple(Fr(s, 2) for s in signs))
    assert len(roots) == 240
    return roots


def ip(u, v):
    return sum(x * y for x, y in zip(u, v))


def e(i, s=1):
    v = [Fr(0)] * 8
    v[i] = Fr(s)
    return v


def vadd(*vs):
    return tuple(sum(c) for c in zip(*vs))


def cartan(simple):
    return [[int(ip(a, b)) for b in simple] for a in simple]


A4_CARTAN = [[2, -1, 0, 0], [-1, 2, -1, 0], [0, -1, 2, -1], [0, 0, -1, 2]]


def span_roots(roots, basis):
    """roots lying in the Q-span of the basis vectors (exact Gaussian elimination on the Gram system)"""
    from sympy import Matrix
    Bm = Matrix([[x for x in b] for b in basis]).T
    out = []
    for r in roots:
        aug = Bm.row_join(Matrix([x for x in r]))
        if aug.rank() == Bm.rank():
            out.append(r)
    return out


def s1_common_sl5():
    R = e8_roots()
    gauge = [vadd(e(0), e(1, -1)), vadd(e(1), e(2, -1)), vadd(e(2), e(3, -1)), vadd(e(3), e(4, -1))]
    struct = [vadd(e(6), e(7, -1)), vadd(e(5), e(6, -1)), vadd(e(6), e(7)), tuple(Fr(-1, 2) for _ in range(8))]
    assert all(r in R for r in gauge + struct)
    assert cartan(gauge) == A4_CARTAN and sorted(map(sorted, cartan(struct))) == sorted(map(sorted, A4_CARTAN))
    assert all(ip(g, s) == 0 for g in gauge for s in struct)
    gauge_roots = span_roots(R, gauge)
    struct_roots = span_roots(R, struct)
    assert len(gauge_roots) == 20 and len(struct_roots) == 20
    # the Standard Model inside the gauge A4: colour e0-e1, e1-e2; weak e3-e4; hypercharge along (2,2,2,-3,-3,0,0,0)
    colour = [gauge[0], gauge[1], vadd(gauge[0], gauge[1])]
    weak = [gauge[3]]
    Y = tuple(Fr(x) for x in (2, 2, 2, -3, -3, 0, 0, 0))
    sm_roots = colour + weak
    centraliser = [r for r in R if ip(r, Y) == 0 and all(ip(r, s) == 0 for s in sm_roots)]
    assert sorted(centraliser) == sorted(struct_roots)                   # exactly the structure A4's 20 roots
    # the Cartan part commuting with the SM: the orthogonal complement of the SM roots in R^8 (rank 8 - 3 = 5) = Y + 4
    # an E6 through the gauge A4
    x = tuple(Fr(v) for v in (0, 0, 0, 0, 1, 1, 0, 0))
    z = tuple(Fr(v, 2) for v in (-1, -1, -1, 1, 1, -1, 1, 1))
    assert x in R and z in R
    e6_basis = gauge + [x, z]
    from sympy import Matrix
    gram = Matrix([[ip(a, b) for b in e6_basis] for a in e6_basis])
    e6_roots = span_roots(R, e6_basis)
    assert gram.det() == 3 and len(e6_roots) == 72
    e6_centraliser = [r for r in e6_roots if ip(r, Y) == 0 and all(ip(r, s) == 0 for s in sm_roots)]
    beta = vadd(e(6), e(7))
    assert sorted(e6_centraliser) == sorted([beta, tuple(-c for c in beta)]) and beta in struct_roots
    fam = [r for r in struct_roots if ip(r, beta) == 0]
    mixed = [r for r in struct_roots if ip(r, beta) in (1, -1)]
    assert len(fam) == 6 and len(mixed) == 12 and len(fam) + len(mixed) + 2 == 20
    # the family roots form an A2: pick two with inner product -1
    a1, a2 = next((u, v) for u, v in itertools.combinations(fam, 2) if ip(u, v) == -1)
    assert cartan([a1, a2]) == [[2, -1], [-1, 2]]
    return {"centraliser_roots": len(centraliser), "e6_roots": len(e6_roots), "family": len(fam), "mixed": len(mixed)}


# ----------------------------------------------------------------------------------------------------------- S2
def s2_parabolic_lemma(trials=60, seed=5):
    import sympy as sp
    A = sp.Matrix(2, 2, sp.symbols("a0:4"))
    B = sp.Matrix(3, 3, sp.symbols("b0:9"))
    X = sp.Matrix(2, 3, sp.symbols("x0:6"))
    Yv = sp.Matrix(2, 3, sp.symbols("y0:6"))
    G = sp.BlockMatrix([[A, X], [sp.zeros(3, 2), B]]).as_explicit()
    Ginv = sp.BlockMatrix([[A.inv(), -A.inv() * X * B.inv()], [sp.zeros(3, 2), B.inv()]]).as_explicit()
    assert sp.simplify(G * Ginv - sp.eye(5)) == sp.zeros(5, 5)
    N = sp.BlockMatrix([[sp.zeros(2, 2), Yv], [sp.zeros(3, 2), sp.zeros(3, 3)]]).as_explicit()
    lhs = sp.simplify(G * N * Ginv)
    rhs = sp.BlockMatrix([[sp.zeros(2, 2), A * Yv * B.inv()], [sp.zeros(3, 2), sp.zeros(3, 3)]]).as_explicit()
    assert sp.simplify(lhs - rhs) == sp.zeros(5, 5)                   # the block X cancels identically
    # N(n_+) = P_{2,3}: a random g preserving U normalises n_+; a random g moving U does not
    rng = random.Random(seed)
    def rand_int_matrix(n, m):
        return sp.Matrix(n, m, lambda i, j: rng.randint(-3, 3))
    basis = []
    for i in range(2):
        for j in range(3):
            Eij = sp.zeros(5, 5)
            Eij[i, 2 + j] = 1
            basis.append(Eij)
    def in_nplus(M):
        return all(M[i, j] == 0 for i in range(5) for j in range(5) if not (i < 2 and j >= 2))
    ok_p = ok_np = 0
    while ok_p < trials // 2 or ok_np < trials // 2:
        g = rand_int_matrix(5, 5)
        if g.det() == 0:
            continue
        preserves_U = all(g[i, j] == 0 for i in range(2, 5) for j in range(2))
        normalises = all(in_nplus(g * Eb * g.inv()) for Eb in basis)
        assert preserves_U == normalises
        if preserves_U:
            ok_p += 1
        else:
            ok_np += 1
        if ok_p < trials // 2 and rng.random() < 0.5:          # also feed in parabolic elements deliberately
            g = rand_int_matrix(5, 5)
            for i in range(2, 5):
                for j in range(2):
                    g[i, j] = 0
            if g.det() != 0:
                assert all(in_nplus(g * Eb * g.inv()) for Eb in basis)
                ok_p += 1
    return {"X cancels": True, "normaliser = P_{2,3} on": trials}


# ----------------------------------------------------------------------------------------------------------- S3
LETTERS = "cdefghijk"            # y_0, y_1, ... ; 'z' is a^n


def rs_cover(n):
    """Reidemeister-Schreier for the n-fold cyclic cover (a, b -> 1 in Z/n), transversal a^k.  Generators: z = a^n and
    y_k = a^k b a^-(k+1) (k < n-1), y_{n-1} = a^(n-1) b.  Returns (gens, words-in-a,b of the generators, rewrite)."""
    gens = ["z"] + [LETTERS[k] for k in range(n)]
    words = {"z": "a" * n}
    for k in range(n):
        words[LETTERS[k]] = "a" * k + "b" + ("A" * (k + 1) if k < n - 1 else "")

    def rewrite(w, k=0):
        out = []
        for ch in w:
            if ch == "a":
                if k == n - 1:
                    out.append("z")
                k = (k + 1) % n
            elif ch == "A":
                if k == 0:
                    out.append("Z")
                k = (k - 1) % n
            elif ch == "b":
                out.append(LETTERS[k])
                k = (k + 1) % n
            elif ch == "B":
                k = (k - 1) % n
                out.append(LETTERS[k].upper())
        return "".join(out), k

    rels = []
    for k in range(n):
        r, kk = rewrite(RELATOR, k)
        assert kk == k
        rels.append(r)
    mu, k1 = rewrite("a" * n)
    lam, k2 = rewrite(LONGITUDE)
    assert k1 == 0 and k2 == 0 and mu == "z"
    return gens, words, rewrite, rels, mu, lam


def geometric(F, n):
    """rho_geo on the n-fold cover's generators: A = [[1,1],[0,1]], B = [[1,0],[-w,1]] over GF(p)"""
    w = F.root_of_unity(3)
    A, B = [[1, 1], [0, 1]], [[1, 0], [(-w) % F.p, 1]]
    base = IL.Rep(F, ["a", "b"], {"a": A, "b": B})
    assert base.check_relators([RELATOR])
    gens, words, rewrite, rels, mu, lam = rs_cover(n)
    return {g: base.word(words[g]) for g in gens}, (gens, words, rewrite, rels, mu, lam)


def characters_via_smith(gens, rels, N):
    """all characters pi -> Z/N of a finitely presented group, via an integer Smith decomposition S = U E V"""
    from sympy import Matrix
    from sympy.matrices.normalforms import smith_normal_decomp
    E = Matrix([[IL.abelian_exponents(r, gens)[g] for g in gens] for r in rels])
    S, U, V = smith_normal_decomp(E)
    ranges = []
    for i in range(len(gens)):
        s = abs(S[i, i]) if i < min(S.shape) else 0
        from math import gcd
        step = N // gcd(s, N) if s else 1
        ranges.append([t * step % N for t in range(N // step)] if s else list(range(N)))
    chars = []
    for kp in itertools.product(*ranges):
        k = V * Matrix(kp)
        chars.append({g: int(k[i]) % N for i, g in enumerate(gens)})
    return chars


def induce(F, V6, cover6, cover2):
    """Ind_{Gamma6}^{Gamma2} V on M2's generators; coset representatives r_i = a^(2i), i = 0, 1, 2"""
    gens6, words6, rewrite6, *_ = cover6
    gens2, words2, *_ = cover2
    d = len(V6.M[gens6[0]])
    rep6 = V6
    out = {}
    for g in gens2:
        wg = words2[g]
        eg = sum(1 if ch.islower() else -1 for ch in wg)
        assert eg % 2 == 0
        M = F.zeros(3 * d, 3 * d)
        for i in range(3):
            j = (i + eg // 2) % 3
            h = "A" * (2 * j) + wg + "a" * (2 * i)
            hw, kk = rewrite6(h, 0)
            assert kk == 0
            blk = rep6.word(hw)
            for r in range(d):
                for c in range(d):
                    M[j * d + r][i * d + c] = blk[r][c]
        out[g] = M
    return IL.Rep(F, gens2, out)


def s3_shapiro_mackey(p=601, N=40, want_firing=6, want_quiet=24, seed=3, cap=40000):
    """seeds: rank-2 non-split rho_chi (chi with H^1(M6; chi^2) = 1) twisted by a character psi, V = rho_chi (x) psi;
    about one pair in twenty has I != 0 on M6 (B1375), so pairs are drawn until both kinds are represented"""
    F = IL.GF(p)
    zeta = F.root_of_unity(N)
    _, cover6 = geometric(F, 6)
    _, cover2 = geometric(F, 2)
    gens6, _, _, rels6, mu6, lam6 = cover6
    gens2, _, _, rels2, mu2, lam2 = cover2
    assert len(gens6) == 7 and len(gens2) == 3
    chars = characters_via_smith(gens6, rels6, N)
    assert len(chars) == 12800                                            # H_1(M6) = Z/8 + Z/40 + Z (B1375)
    rng = random.Random(seed)
    seeds = []
    for chi in chars:
        chi_val = {g: pow(zeta, chi[g], p) for g in gens6}
        sq = {g: chi_val[g] * chi_val[g] % p for g in gens6}
        h1, ct = IL.h1_and_cocycle(F, gens6, rels6, mu6, lam6, sq)
        if ct is not None:
            seeds.append(IL.Rep(F, gens6, IL.reducible_rep(F, gens6, chi_val, ct)))
    assert len(seeds) == 640                                              # B1375: 639 non-trivial loci, all h^1 = 1
    tested = nonzero = unip = draws = 0
    quiet = 0
    while (nonzero < want_firing or quiet < want_quiet) and draws < cap:
        draws += 1
        rho = rng.choice(seeds)
        psi = rng.choice(chars)
        psi_val = {g: pow(zeta, psi[g], p) for g in gens6}
        V = IL.Rep(F, gens6, IL.module(F, gens6, rho.M, 1, psi_val))
        assert V.check_relators(rels6)
        I6pre = IL.index(V, rels6, mu6, lam6)[0]
        if I6pre == 0 and quiet >= want_quiet:
            continue
        if I6pre != 0 and nonzero >= want_firing:
            continue
        quiet += I6pre == 0
        Ind = induce(F, V, cover6, cover2)
        assert Ind.check_relators(rels2)
        d6 = IL.cohomology_data(V, rels6, mu6, lam6)
        d6s = IL.cohomology_data(V.dual(), rels6, mu6, lam6)
        d2 = IL.cohomology_data(Ind, rels2, mu2, lam2)
        d2s = IL.cohomology_data(Ind.dual(), rels2, mu2, lam2)
        assert d6 == d2 and d6s == d2s, (d6, d2, d6s, d2s)                    # Shapiro + Mackey: all five numbers
        I6 = IL.index(V, rels6, mu6, lam6)[0]
        I2 = IL.index(Ind, rels2, mu2, lam2)[0]
        assert I6 == I2
        # the coset generator T = Ind(a^2): T^3 = Ind(a^6) = rho(mu6) on each block
        T = Ind.M["z"]
        T3 = F.mul(F.mul(T, T), T)
        Rm = V.word(mu6)
        dd = len(Rm)
        for i in range(3):
            for r in range(dd):
                for c in range(dd):
                    assert T3[i * dd + r][i * dd + c] == Rm[r][c]
        eye = F.eye(3 * dd)
        N3 = F.sub(T3, eye)
        if Rm != F.eye(dd) and all(Rm[i][i] == 1 for i in range(dd)):         # non-trivial unipotent at the cusp
            assert F.mul(N3, N3) == F.zeros(3 * dd, 3 * dd)
            unip += 1
        tested += 1
        nonzero += I6 != 0
    assert nonzero >= want_firing and quiet >= want_quiet and unip > 0
    return {"seeds": tested, "with I != 0": nonzero, "unipotent T^3 != 1 with (T^3-1)^2 = 0": unip, "draws": draws}


# ----------------------------------------------------------------------------------------------------------- S4
def s4_sym4_twists():
    out = {}
    for p in PRIMES:
        F = IL.GF(p)
        geo2, cover2 = geometric(F, 2)
        gens2, _, _, rels2, mu2, lam2 = cover2
        S4 = {g: IL.sym_power(F, geo2[g], 4) for g in gens2}
        V0 = IL.Rep(F, gens2, S4)
        assert V0.check_relators(rels2)
        I0, d0, d0s = IL.index(V0, rels2, mu2, lam2)
        assert I0 == 0                                                        # self-dual: I = 0
        zeta5 = F.root_of_unity(5)
        chars = IL.characters(F, gens2, rels2, 5)
        cusp_trivial = [c for c in chars if any(c.values())
                        and IL.char_value(F, zeta5, c, mu2) == 1 and IL.char_value(F, zeta5, c, lam2) == 1]
        assert len(cusp_trivial) == 4                                         # the four non-trivial characters of Z/5
        rows = set()
        for c in cusp_trivial:
            psi_val = {g: pow(zeta5, c[g], p) for g in gens2}
            V = IL.Rep(F, gens2, {g: F.scale(psi_val[g], S4[g]) for g in gens2})
            assert V.check_relators(rels2)
            dv = IL.cohomology_data(V, rels2, mu2, lam2)
            dvs = IL.cohomology_data(V.dual(), rels2, mu2, lam2)
            I = IL.index(V, rels2, mu2, lam2)[0]
            assert dv == (0, 1, 1, 2, 1) and dvs == (0, 1, 1, 2, 1) and I == 0
            rows.add((dv, dvs, I))
        out[p] = {"Sym4 untwisted I": I0, "twists": sorted(rows)}
    return out


if __name__ == "__main__":
    print("S0 ", s0_signed_state(), "-> -LR (m003) is generated once inverses are admitted")
    print("S1  common SL5:", s1_common_sl5(), "-> c_E8(SM) = structure A4 + u1_Y; in an E6 through the gauge A4 the SM"
          " centraliser is {+-beta}, and the structure A4 = sl2_beta + A2_family + 12 mixed")
    print("S2  parabolic lemma:", s2_parabolic_lemma())
    print("S3  Shapiro + Mackey on own covers (p = 601, characters of order dividing 40):", s3_shapiro_mackey())
    for p, row in s4_sym4_twists().items():
        print("S4  p = %d: Sym^4(rho_geo) on M2 has I = %d; its four cusp-trivial order-5 twists: %s" % (p, row["Sym4 untwisted I"], row["twists"]))
    print("DONE")
