#!/usr/bin/env python3
"""B1526 -- GENESIS v1.6: every item v1.6 carries, checked with the SM seat's own code before it is written.

C1  The received texts, by sha-256 and git blob: main's v1.5 (its GENESIS.md at 5c0951b7), the SM seat's v1.5 (this branch's
    GENESIS.md before the arc) and main's relay of 2026-10-03. Main's v1.5 is main's v1.4 (kept in sm:B1525's received/)
    plus exactly seven changed blocks, each carrying main's [v1.5] mark except the version line and the log entry; and,
    where commit 5c0951b7 is in the clone, main's own amend.py, read from its blob into a temporary directory and never
    run against this tree, rebuilds main's v1.5 from that v1.4 byte for byte.
C2  sm:B1525's checks C1-C4 re-run from their own file: P is the swap's class and fixes rho_q, the audit lane's AR3-AR6
    (sm:B1521's scripts, byte-identical records), the levels by a third route, the word states by own word code, the
    bar's null contract. They carry the same sentences in v1.6 as in v1.5.
C3  P is the fibre's elliptic involution (the precision v1.6 makes at FK9). In SnapPy's presentation <a, b | R> of m004
    (R = aaabABBAb), B1297's P (a -> a^-1, b -> a^3 b):
      - is an involution of the free group and sends R to 1 in the holonomy (an automorphism of pi_1);
      - keeps the base (b's exponent generates H1 = Z, a has exponent 0) and the orientation (traces of rho o P equal
        those of rho, with a non-real one among them, so rho o P is conjugate to rho and not to its complex conjugate);
      - acts on the fibre's homology F^ab = Z[t^+-1]/(Delta), generated by [a], as -1, while an inner automorphism acts as
        t^k; Delta, from R by Fox calculus, is t^2 - 3t + 1 up to a unit, whose roots are positive, so -1 is no t^k and
        P is not inner.
    SnapPy's symmetry group of m004 (order 8, the full group): exactly two isometries act on the cusp as the identity,
    i.e. keep the orientation and the base (the cusp maps are the four sign pairs, twice each). So Out(pi_1 m004) has
    exactly one class that keeps the orientation and the base and is not trivial. P is in it; so is the fibre's elliptic
    involution (orientation and base kept, -1 on the fibre's homology, not inner by the same argument), whose extension
    to every level is main's B1459 involution. In Ballas' presentation <m, n> the same holds of sm:B1512's Lemma I map
    and of the swap (each sends the fibre's generator mn^-1 to its inverse and keeps the base), by free-group words.
C4  v1.6 against main's v1.5, regenerated by merge_genesis_v16.py:
      - main's words are kept except the listed edits (the version number; punctuation where a marked sentence is
        appended; "frame" made "frame's counts");
      - every changed block carries a [v1.6] mark, except the version line and §10's own entry;
      - earlier marks unchanged (bold and plain), 15 [v1.6] marks; sections 0-10 in order; every table well formed;
      - every fork status as in main's v1.5, and the owner's two decisions (FK1's row, FK12's framing, the decided
        paragraph and §1's header) verbatim;
      - no Gate 5-Q word (Q5's three, whole words, encoded here), vendor word or private term.
C5  The SM seat's v1.5 answered by its line, computed: each block v1.5 changed against main's v1.4 is either found in v1.6
    with its mark renamed (carried as it was), or is one of the listed blocks fitted or not carried (the header, GAP3,
    FK9's P sentence, FK12's carried text, the log entry), each with its reason.
Usage: python3 genesis_v16_checks.py   (writes genesis_v16_checks.json and prints it; about 30 s)"""
import base64
import collections
import difflib
import hashlib
import importlib.util
import json
import re
import subprocess
import sys
import tempfile
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
ARC = HERE.parent
ROOT = ARC.parents[1]
REC = ARC / "received"
V15M = REC / "GENESIS_v1_5_main.md"
V15S = REC / "GENESIS_v1_5_sm.md"
RELAY = REC / "CC_TO_SM_AND_CODEX_2026-10-03_GENESIS_V1_5_FK1_CONFIRMED_FK12_THE_REGISTER.md"
V14 = ROOT / "frontier" / "B1525_genesis_v15" / "received" / "GENESIS_v1_4_main.md"
SHA = {V15M.name: "67d554e9868b0164685ce8b71b6d3d1dea19b892b937b709a8a45a232879fa12",
       V15S.name: "3e3b3d7bcfdf2eac3155419a45fd8a32f07c1e79588f74fa4e2a16082ca1b6f3",
       RELAY.name: "154155eaa71a2e30c1741d54427256c168f2b7d0fa3e097c27382c12ca649781",
       V14.name: "d32456b67ae2cb55e036de57c2a8619a8e546b7656144c1cf7ab008615bd557a"}
BLOB = {V15M.name: "e39ed197b9f9c3c78dcf1a916fd8f1a7908133b0", V15S.name: "9d6f28a44276bdb22b78d9456e9bfb936b7e0e2a",
        RELAY.name: "a6b21d02949dff8f77aa280ac72a1ae6ac557ada"}
MARK = "**[v1.6]**"
Q5 = [base64.b64decode(t).decode() for t in ("cXVhbGlh", "YXdhcmU=", "c2Vlcw==")]   # Gate 5-Q's three words, encoded
VENDOR = [base64.b64decode(t).decode() for t in ("Y2xhdWRl", "YW50aHJvcGlj", "b3B1cw==", "c29ubmV0", "ZmFibGU=")]
PRIVATE = bytes([98, 114, 97, 118, 101]).decode()


def sha(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()


def blob(p):
    return subprocess.run(["git", "hash-object", str(p)], capture_output=True, text=True, check=True).stdout.strip()


def norm(t):
    return re.sub(r"\s+", " ", t).strip()


def git_show(rev_path):
    try:
        return subprocess.run(["git", "-C", str(ROOT), "show", rev_path], capture_output=True, check=True).stdout
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def line_blocks(a, b):
    """the changed blocks of lines from a to b: (index in b, the new lines, the old lines)"""
    la, lb = a.split("\n"), b.split("\n")
    out = []
    for op, i1, i2, j1, j2 in difflib.SequenceMatcher(None, la, lb, autojunk=False).get_opcodes():
        if op != "equal":
            out.append((j1, lb[j1:j2], la[i1:i2]))
    return out


# ------------------------------------------------------------------------------------------------ C1
def c1():
    out = {"sha-256": {p.name: sha(p) == SHA[p.name] for p in (V15M, V15S, RELAY, V14)},
           "git blob": {p.name: blob(p) == BLOB[p.name] for p in (V15M, V15S, RELAY)}}
    for p, rev in ((V15M, "5c0951b7:GENESIS.md"),
                   (RELAY, "5c0951b7:docs/handoffs/" + RELAY.name)):
        b = git_show(rev)
        out["byte-identical to " + rev] = (b == p.read_bytes()) if b is not None else "not checkable: not in this clone"
    v14, v15 = V14.read_text(encoding="utf-8"), V15M.read_text(encoding="utf-8")
    blocks = line_blocks(v14, v15)
    kinds = []
    for j, new, old in blocks:
        if new and new[0].startswith("**Version 1.5 · 2026-10-03 · canonical.**"):
            kinds.append("version line")
        elif new and new[0].startswith("- **v1.5 · 2026-10-03 · main B1460.**"):
            kinds.append("log entry")
        elif any("[v1.5]" in x for x in new):
            kinds.append("marked")
        else:
            kinds.append("UNMARKED")
    out["main's v1.5 against v1.4: changed blocks"] = dict(collections.Counter(kinds))
    out["main's seven changes, as its B1460 lists them"] = kinds.count("version line") == 1 and \
        kinds.count("log entry") == 1 and kinds.count("marked") == 5 and "UNMARKED" not in kinds and len(blocks) == 7
    # main's own generator, from its blob, where the commit is here: it must rebuild main's v1.5 from the received v1.4
    src = git_show("5c0951b7:frontier/B1460_genesis_v1_5_the_owners_two_decisions/adoption/amend.py")
    if src is None:
        out["main's amend.py rebuilds main's v1.5 from v1.4"] = "not checkable: not in this clone"
    else:
        with tempfile.TemporaryDirectory() as tmp:
            t = Path(tmp)
            (t / "a" / "b" / "adoption").mkdir(parents=True)
            (t / "a" / "b" / "received").mkdir(parents=True)
            (t / "a" / "b" / "received" / "GENESIS_v1_4_main.md").write_bytes(V14.read_bytes())
            (t / "a" / "b" / "adoption" / "amend.py").write_bytes(src)
            spec = importlib.util.spec_from_file_location("main_b1460_amend", t / "a" / "b" / "adoption" / "amend.py")
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)          # defines build(); main() is not called, so nothing is written
            out["main's amend.py rebuilds main's v1.5 from v1.4"] = mod.build() == v15 and len(mod.CHANGES) == 7
    out["passed"] = (all(out["sha-256"].values()) and all(out["git blob"].values())
                     and all(v is not False for k, v in out.items() if k.startswith("byte-identical"))
                     and out["main's seven changes, as its B1460 lists them"]
                     and out["main's amend.py rebuilds main's v1.5 from v1.4"] is not False)
    return out


# ------------------------------------------------------------------------------------------------ C2
def b1525():
    spec = importlib.util.spec_from_file_location(
        "b1525_genesis_v15_checks", ROOT / "frontier" / "B1525_genesis_v15" / "verification" / "genesis_v15_checks.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def c2():
    m = b1525()
    r = {"C1 (sm:B1521's checks: P is the swap's class; AR3-AR6)": m.c1()["passed"],
         "C2 (the levels, third route)": m.c2()["passed"],
         "C3 (the word states, own word code)": m.c3()["passed"],
         "C4 (the bar's null contract)": m.c4()["passed"]}
    return {"sm:B1525's checks re-run": r, "passed": all(r.values())}


# ------------------------------------------------------------------------------------------------ C3
def inv(w):
    return "".join(c.swapcase() for c in reversed(w))


def red(w):
    out = []
    for c in w:
        if out and out[-1] == c.swapcase():
            out.pop()
        else:
            out.append(c)
    return "".join(out)


def sub(w, img):
    return red("".join(img[c] if c.islower() else inv(img[c.lower()]) for c in w))


def exponent(w, x):
    return w.count(x) - w.count(x.upper())


def fox_a_at(w, t):
    """the Fox derivative d w / d a, abelianised by a -> 1, b -> t (a has exponent 0 in H1, b generates it): an integer
    Laurent polynomial in t, as a dict exponent -> coefficient"""
    poly, deg = collections.Counter(), 0          # deg: the abelianised exponent of the prefix
    for c in w:
        if c == "a":
            poly[deg] += 1
        elif c == "A":
            poly[deg] -= 1                       # d(a^-1)/da = -a^-1, and a -> 1 leaves the prefix's degree
        if c in "bB":
            deg += 1 if c == "b" else -1
    return {k: v for k, v in poly.items() if v}


def c3():
    import mpmath as mp
    import snappy
    mp.mp.dps = 60
    out = {}

    def num(x):
        """SnapPy's high-precision number (about 64 digits) as an mpmath complex, through its decimal string"""
        return mp.mpc(mp.mpf(str(x.real()).replace(" ", "")), mp.mpf(str(x.imag()).replace(" ", "")))
    M = snappy.ManifoldHP("m004")
    G = M.fundamental_group()
    gens, rels = G.generators(), G.relators()
    out["SnapPy presentation of m004"] = [gens, rels]
    R = rels[0]
    ok_pres = gens == ["a", "b"] and len(rels) == 1 and R == "aaabABBAb"
    P = {"a": "A", "b": "aaab"}                  # B1297's P: a -> a^-1, b -> a^3 b
    out["P is an involution of the free group"] = sub(sub("a", P), P) == "a" and sub(sub("b", P), P) == "b"

    def mat(w, sign_a):
        X = mp.eye(2)
        for c in w:
            g = G.SL2C(c.lower())
            g = mp.matrix([[num(g[i, j]) for j in range(2)] for i in range(2)])
            if c.lower() == "a":
                g = g * sign_a
            X = X * (g if c.islower() else mp.inverse(g))
        return X
    # SnapPy's lift sends R to -1 or +1; a has exponent 1 in R, so a -> -a turns it into a genuine lift
    rR = mat(R, 1)
    sign_a = 1 if mp.norm(rR - mp.eye(2)) < 1e-40 else -1
    out["the lift: a -> -a needed"] = sign_a == -1
    err = lambda X, Y: float(mp.norm(X - Y))
    out["rho(R) = I (genuine lift)"] = err(mat(R, sign_a), mp.eye(2)) < 1e-40
    PR = sub(R, P)
    out["rho(P(R)) = I: P is an automorphism"] = err(mat(PR, sign_a), mp.eye(2)) < 1e-40
    words = ["a", "b", "ab", "aB", "aab", "abb", "aabb", "abAB"]
    tr = {w: complex(mp.re(mat(w, sign_a)[0, 0] + mat(w, sign_a)[1, 1]), mp.im(mat(w, sign_a)[0, 0] + mat(w, sign_a)[1, 1]))
          for w in words}
    trP = {w: complex(mp.re(mat(sub(w, P), sign_a)[0, 0] + mat(sub(w, P), sign_a)[1, 1]),
                      mp.im(mat(sub(w, P), sign_a)[0, 0] + mat(sub(w, P), sign_a)[1, 1])) for w in words}
    out["traces of rho o P equal those of rho"] = all(abs(tr[w] - trP[w]) < 1e-30 for w in words)
    out["a non-real trace among them (so not the complex conjugate)"] = max(abs(tr[w].imag) for w in words) > 0.1
    out["traces of rho o P differ from the conjugate's"] = any(abs(trP[w] - tr[w].conjugate()) > 0.1 for w in words)
    # the base: H1 = Z, generated by b; a has exponent 0
    out["exponents of R in a, b"] = [exponent(R, "a"), exponent(R, "b")]
    out["P keeps the base: exponent of P(b) in b"] = exponent(sub("b", P), "b")
    # the fibre's homology: F = <<a>>, F^ab = Z[t^+-1]/(Delta), Delta = dR/da at a -> 1, b -> t
    fa = fox_a_at(R, None)
    lo = min(fa)
    delta = [fa.get(k, 0) for k in range(lo, max(fa) + 1)]
    out["Delta from R (coefficients, lowest degree first)"] = delta
    roots = [complex(r) for r in mp.polyroots(list(reversed(delta)))]
    out["Delta = t^2 - 3t + 1 up to a unit"] = delta in ([1, -3, 1], [-1, 3, -1])
    out["roots of Delta are real and positive (so -1 is no power of t on F^ab)"] = all(
        abs(r.imag) < 1e-30 and r.real > 0 for r in roots)
    # P on F^ab: [a] -> [a^-1] = -[a]; and P commutes with t up to F, since P(b) = a^3 b with a in F
    out["P([a]) = -[a]"] = sub("a", P) == "A"
    out["P(b) = (element of F) b"] = sub("b", P)[-1] == "b" and exponent(sub("b", P)[:-1], "b") == 0
    # SnapPy's symmetry group
    S = M.symmetry_group()
    maps = [tuple(tuple(int(iso.cusp_maps()[0][i, j]) for j in range(2)) for i in range(2)) for iso in S.isometries()]
    out["symmetry group: order, full, amphicheiral"] = [S.order(), S.is_full_group(), S.is_amphicheiral()]
    out["cusp maps"] = {str(k): v for k, v in sorted(collections.Counter(maps).items())}
    ident = ((1, 0), (0, 1))
    out["isometries acting on the cusp as the identity (orientation and base kept)"] = maps.count(ident)
    out["each of the four sign pairs twice (main's B1456)"] = sorted(collections.Counter(maps).values()) == [2, 2, 2, 2] and \
        set(maps) == {((1, 0), (0, 1)), ((-1, 0), (0, -1)), ((1, 0), (0, -1)), ((-1, 0), (0, 1))}
    # Ballas' presentation <m, n>: the fibre is generated (normally) by m n^-1; Lemma I's map and the swap, by words
    lemma_i = {"m": "mnM", "n": "mNmnM"}
    swap = {"m": "n", "n": "m"}
    conj_swap = {"m": red("nM" + "n" + "mN"), "n": red("nM" + "m" + "mN")}       # conj(nM) o s, sm:B1521 C1
    ballas = {}
    for name, img in (("Lemma I", lemma_i), ("swap", swap), ("conj(nM) o swap", conj_swap)):
        f = sub("mN", img)
        ballas[name] = {"image of mN": f, "inverts it up to conjugacy": cyc_eq(f, "nM"),
                        "keeps the base": exponent(img["m"], "m") + exponent(img["m"], "n") == 1
                        and exponent(img["n"], "m") + exponent(img["n"], "n") == 1}
    out["Ballas' presentation"] = ballas
    out["passed"] = (ok_pres and out["P is an involution of the free group"] and out["the lift: a -> -a needed"]
                     and out["rho(R) = I (genuine lift)"] and out["rho(P(R)) = I: P is an automorphism"]
                     and out["traces of rho o P equal those of rho"]
                     and out["a non-real trace among them (so not the complex conjugate)"]
                     and out["traces of rho o P differ from the conjugate's"]
                     and out["exponents of R in a, b"] == [1, 0] and out["P keeps the base: exponent of P(b) in b"] == 1
                     and out["Delta = t^2 - 3t + 1 up to a unit"]
                     and out["roots of Delta are real and positive (so -1 is no power of t on F^ab)"]
                     and out["P([a]) = -[a]"] and out["P(b) = (element of F) b"]
                     and out["symmetry group: order, full, amphicheiral"] == [8, True, True]
                     and out["isometries acting on the cusp as the identity (orientation and base kept)"] == 2
                     and out["each of the four sign pairs twice (main's B1456)"]
                     and all(v["inverts it up to conjugacy"] and v["keeps the base"] for v in ballas.values()))
    return out


def cyc_eq(u, v):
    """u and v conjugate in the free group: equal cyclic reductions up to rotation"""
    def cr(w):
        w = red(w)
        while len(w) >= 2 and w[0] == w[-1].swapcase():
            w = w[1:-1]
        return w
    u, v = cr(u), cr(v)
    return len(u) == len(v) and (u in v + v)


# ------------------------------------------------------------------------------------------------ C4
EXPECTED_DELETIONS = [
    "1.5",
    "sm:B1520)",
    "DERIVED,",
    "relation",
    "L241",
    "frame",
    "levels;",
    "root.",
]
OWNER = ("| FK1 | The principle's single wording (§1) | **[v1.5] CONFIRMED** (the owner, 2026-10-03) | nothing; the measurer is "
         "not in the principle — it is FK12, where it can be computed and paid |",
         "**[v1.5] The register** (the owner's framing, decided 2026-10-03). The genesis generates a word.",
         "**Is the register that keeps the order part of the state, carried by the act, or an input from outside?**",
         "What the record does not show: that the act generates the register rather than receives it.",
         "**[v1.5] Decided by the owner (2026-10-03):** the single wording of the principle (§1, FK1) is confirmed as written",
         "**The single wording (proposed by the SM seat in v1.0; [v1.5] confirmed by the owner 2026-10-03, main B1460):**")


def tables(text):
    out, cur = [], []
    for line in text.split("\n"):
        if line.startswith("|"):
            cur.append(line)
        elif cur:
            out.append(cur)
            cur = []
    if cur:
        out.append(cur)
    return out


def cells(row):
    return [c.strip() for c in row.strip().strip("|").split("|")]


def q5(text):
    """Q5's words found, by their place in Q5's list (1-3), so the record never writes them"""
    return [i + 1 for i, w in enumerate(Q5) if re.search(r"\b" + w + r"\b", text, re.I)]


def diff_report(v15, v16):
    """main's words deleted or re-punctuated (token diff), and the changed blocks of lines that carry no [v1.6] mark
    (the version line and §10's own entry excepted: log entries carry no mark)"""
    ta, tb = re.findall(r"\S+", v15), re.findall(r"\S+", v16)
    ops = difflib.SequenceMatcher(None, ta, tb, autojunk=False).get_opcodes()
    deleted = [" ".join(ta[i1:i2]) for op, i1, i2, j1, j2 in ops if op in ("replace", "delete")]
    la, lb = v15.split("\n"), v16.split("\n")
    unmarked = []
    for op, i1, i2, j1, j2 in difflib.SequenceMatcher(None, la, lb, autojunk=False).get_opcodes():
        if op == "equal" or j1 == j2:
            if op != "equal":
                unmarked.append((j1 + 1, ["(lines of v1.5 removed)"] + la[i1:i1 + 1]))
            continue
        block = lb[j1:j2]
        version_line = j1 < 3 and i1 < len(la) and "** " in la[i1] and \
            block == ["**Version 1.6 · 2026-10-03 · canonical.** " + la[i1].split("** ", 1)[1]]
        log_entry = block[0].startswith("- **v1.6 · 2026-10-03 · sm:B1526.**")
        if not any(MARK in b for b in block) and not version_line and not log_entry:
            unmarked.append((j1 + 1, block[:1]))
    return deleted, unmarked


def generate():
    with tempfile.TemporaryDirectory() as tmp:
        gen = Path(tmp) / "v16.md"
        subprocess.run([sys.executable, str(HERE / "merge_genesis_v16.py"), str(V15M), str(gen)], check=True,
                       capture_output=True)
        return gen.read_text(encoding="utf-8")


def c4(v16):
    v15 = V15M.read_text(encoding="utf-8")
    cur = (ROOT / "GENESIS.md").read_text(encoding="utf-8")
    out = {"sha-256 of the generated v1.6": hashlib.sha256(v16.encode("utf-8")).hexdigest(),
           "GENESIS.md is the generated v1.6": cur == v16}
    deleted, unmarked = diff_report(v15, v16)
    out["main's words deleted or re-punctuated"] = deleted
    out["exactly the listed edits"] = deleted == EXPECTED_DELETIONS
    out["changed blocks without a mark"] = unmarked
    out["earlier marks unchanged (bold, plain)"] = {
        m: [v15.count("**" + m + "**"), v16.count("**" + m + "**"), v15.count(m), v16.count(m)]
        for m in ("[v1.1]", "[v1.2]", "[v1.3]", "[v1.4]", "[v1.5]")}
    out["[v1.6] marks"] = v16.count(MARK)
    out["[v1.6] written only as a mark"] = v16.count("[v1.6]") == v16.count(MARK) + 1   # + the log's "(marked [v1.6])"
    heads = re.findall(r"(?m)^## (\d+)\. ", v16)
    out["sections in order"] = heads == [str(i) for i in range(11)] and \
        re.findall(r"(?m)^## .*$", v16) == re.findall(r"(?m)^## .*$", v15)
    bad = []
    for t in tables(v16):
        n = len(cells(t[0]))
        bad += [r[:60] for r in t if len(cells(r)) != n]
    out["malformed table rows"] = bad
    rows15 = [r for t in tables(v15) for r in t]
    rows16 = [r for t in tables(v16) for r in t]
    by_first16 = {cells(r)[0]: r for r in rows16}
    changed = []
    for r in rows15:
        if r in rows16:
            continue
        r16 = by_first16.get(cells(r)[0])
        c15, c16 = cells(r), cells(r16) if r16 else []
        changed.append({"row": c15[0][:40], "kept leading cells": bool(r16) and c16[:3] == c15[:3]
                        and len(c16) == len(c15), "marked": bool(r16) and MARK in r16})
    out["v1.5 rows changed (leading cells kept, marked)"] = changed
    new_rows = [cells(r)[0][:50] for r in rows16 if r not in rows15 and cells(r)[0] not in {cells(x)[0] for x in rows15}]
    out["rows new in v1.6"] = new_rows
    pat = r"FK\d+( \*\*\[v1\.2\]\*\*)?"
    fk15 = {cells(r)[0]: cells(r)[2] for r in rows15 if re.fullmatch(pat, cells(r)[0])}
    fk16 = {cells(r)[0]: cells(r)[2] for r in rows16 if re.fullmatch(pat, cells(r)[0])}
    out["fork statuses as in main's v1.5"] = fk16 == fk15 and len(fk16) == 12
    out["FK1 CONFIRMED, FK12 OPEN"] = fk16.get("FK1") == "**[v1.5] CONFIRMED** (the owner, 2026-10-03)" and \
        fk16.get("FK12 **[v1.2]**") == "OPEN"
    out["the owner's two decisions verbatim"] = {s[:60]: (s in v15 and s in v16) for s in OWNER}
    out["Q5's words found, by place in its list: v1.6, main's v1.5, the SM seat's v1.5, a planted control"] = [
        q5(v16), q5(v15), q5(V15S.read_text(encoding="utf-8")), q5("the record " + Q5[1] + " of it")]
    out["vendor words or the private term in v1.6"] = [w for w in VENDOR if re.search(re.escape(w), v16, re.I)] + \
        ([PRIVATE] if PRIVATE in v16.lower() else [])
    out["passed"] = (out["exactly the listed edits"] and not unmarked
                     and all(a == b and c == d for a, b, c, d in out["earlier marks unchanged (bold, plain)"].values())
                     and out["[v1.6] marks"] == 15 and out["[v1.6] written only as a mark"]
                     and out["sections in order"] and not bad
                     and len(changed) == 4 and all(c["kept leading cells"] and c["marked"] for c in changed)
                     and len(new_rows) == 4 and out["fork statuses as in main's v1.5"] and out["FK1 CONFIRMED, FK12 OPEN"]
                     and all(out["the owner's two decisions verbatim"].values())
                     and out["Q5's words found, by place in its list: v1.6, main's v1.5, the SM seat's v1.5, a planted control"]
                     == [[], [], [], [2]]
                     and not out["vendor words or the private term in v1.6"])
    return out


# ------------------------------------------------------------------------------------------------ C5
FITTED = {
    "header": "replaced by v1.6's header sentence; the seat's v1.5 kept as received in sm:B1526",
    "GAP3": "already in main's v1.5, in main's words (its [v1.5] qualification); not carried",
    "FK9": "carried, with P named the fibre's elliptic involution (C3)",
    "FK12": "carried, fitted to the owner's framing: the register question; the experiential question kept apart",
    "log": "superseded by v1.6's entry, which says what was carried, fitted and not carried",
}


def c5(v16):
    v14, v15s = V14.read_text(encoding="utf-8"), V15S.read_text(encoding="utf-8")
    g16 = norm(v16)
    rows = []
    for j, new, old in line_blocks(v14, v15s):
        ta, tb = re.findall(r"\S+", "\n".join(old)), re.findall(r"\S+", "\n".join(new))
        added = []
        for op, i1, i2, j1, j2 in difflib.SequenceMatcher(None, ta, tb, autojunk=False).get_opcodes():
            if op in ("insert", "replace"):
                added.append(" ".join(tb[j1:j2]))
        text = " ".join(added)
        first = new[0] if new else ""
        where = ("header" if first.startswith("**Version") or "v1.5 (sm:B1525) takes main's head" in text
                 else "GAP3" if "The audit lane's results do not prove" in "\n".join(new)
                 else "log" if first.startswith("- **v1.5 · 2026-10-03 · sm:B1525.**")
                 else "FK9" if first.startswith("| FK9 |") and "B1297's period-2 symmetry P" in text
                 else "FK12" if first.startswith("| FK12") else None)
        carried = all(norm(seg.replace("**[v1.5]**", MARK)) in g16 for seg in added if seg.strip())
        rows.append({"line in the seat's v1.5": j + 1, "marks": text.count("**[v1.5]**"), "begins": text[:70],
                     "fate": "carried as it was" if carried and where is None else FITTED.get(where, "UNACCOUNTED"),
                     "found verbatim": carried})
    marks = sum(r["marks"] for r in rows)
    out = {"blocks": rows, "the seat's v1.5 marks accounted for": marks,
           "every block accounted for": all(r["fate"] != "UNACCOUNTED" for r in rows),
           "carried as it was": sum(1 for r in rows if r["fate"] == "carried as it was"),
           "fitted or not carried": sorted({k for r in rows for k, v in FITTED.items() if r["fate"] == v})}
    out["passed"] = (marks == 16 and out["every block accounted for"]
                     and out["fitted or not carried"] == sorted(FITTED))
    return out


def main():
    t0 = time.time()
    res = {}
    res["C1 the received texts"] = c1()
    res["C2 sm:B1525's checks re-run"] = c2()
    res["C3 P is the fibre's elliptic involution"] = c3()
    v16 = generate()
    res["C4 v1.6 against main's v1.5"] = c4(v16)
    res["C5 the SM seat's v1.5, answered by its line"] = c5(v16)
    res["checks"] = {k.split(" ")[0]: v["passed"] for k, v in res.items() if isinstance(v, dict) and "passed" in v}
    res["GENESIS.md is the generated v1.6"] = res["C4 v1.6 against main's v1.5"]["GENESIS.md is the generated v1.6"]
    res["seconds"] = round(time.time() - t0, 1)
    (HERE / "genesis_v16_checks.json").write_text(json.dumps(res, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps(res, indent=1, ensure_ascii=False))
    print("ALL CHECKS PASS" if all(res["checks"].values()) else "A CHECK FAILED", res["checks"],
          "| GENESIS.md is the generated v1.6:", res["GENESIS.md is the generated v1.6"])


if __name__ == "__main__":
    main()
