#!/usr/bin/env python3
"""B850 -- the length spectrum as a computable shadow of the foliation algebra's type.

Sealed prereg: PREREGISTRATION.md, f9d13b4d880301f7.

The incoming bundle files the foliation-algebra question as "one sentence to an
operator-algebraist" and calls it the only architecture-changing lead in fifteen rounds. It
matters because B723 Probe 2 found the thermal clock is carried by an EXTERNAL WEIGHT -- and an
imposed weight is not spontaneous. If the algebra is III_1, Connes' theorem makes the modular flow
unique up to inner automorphism, so the weight stops being a choice.

REDUCTION UNDER TEST (a DECLARED CITATION, not verified here):
    additive group generated by the length spectrum DISCRETE -> III_lambda
                                                     DENSE -> III_1

Its weak point is named in the seal: m004's flow is NOT uniformly hyperbolic and the foliation
carries an infinite invariant measure, which is exactly why compact-Anosov => III_lambda does not
transfer. Every verdict here carries CONDITIONAL.

AND THE SEAL PRE-STATES that the DENSE/DISCRETE binary is FORCED by classical theory (mixing
requires a non-lattice length spectrum), so it is a VERIFICATION, not a finding. The arc's real
product is the GENERICITY verdict.

Mathematics scope. Nothing reaches CLAIMS.md.
"""
import itertools
import json
import os

import mpmath as mp
import sympy as sp

HERE = os.path.dirname(os.path.abspath(__file__))
mp.mp.dps = 40

KNOWN_SYSTOLE_M004 = mp.mpf("1.087070144995")     # positive control, fixed in the seal


def gens_m004():
    """Discrete faithful rep of the figure-eight group over Z[omega]. Relator VERIFIED."""
    w = sp.Rational(-1, 2) + sp.sqrt(-3) / 2
    A = sp.Matrix([[1, 1], [0, 1]])
    B = sp.Matrix([[1, 0], [-w, 1]])
    return A, B


def check_relator(A, B):
    """w a == b w with w = a^-1 b a b^-1 -- computed, not cited."""
    wd = sp.simplify(A.inv() * B * A * B.inv())
    return sp.simplify(wd * A - B * wd) == sp.zeros(2, 2)


def lengths_from_group(A, B, maxlen=6):
    """Exact traces -> real translation lengths at 40 dps, with per-length trace multiplicity."""
    alph = {"a": A, "A": A.inv(), "b": B, "B": B.inv()}
    alph = {k: sp.Matrix(2, 2, [sp.expand(x) for x in v]) for k, v in alph.items()}
    traces = set()
    for L in range(1, maxlen + 1):
        for word in itertools.product("aAbB", repeat=L):
            M = sp.eye(2)
            for ch in word:
                M = M * alph[ch]
            traces.add(sp.expand(sp.simplify(M.trace())))

    by_len = {}
    for t in traces:
        tc = mp.mpc(complex(sp.N(t, 40)))
        if abs(tc.imag) < 1e-12 and abs(tc.real) <= 2 + 1e-12:
            continue                                        # elliptic or parabolic: no translation
        lam = (tc + mp.sqrt(tc * tc - 4)) / 2
        if abs(lam) < 1:
            lam = 1 / lam
        ell = 2 * mp.log(abs(lam))
        if ell < mp.mpf("1e-9"):
            continue
        key = mp.nstr(ell, 12)
        by_len.setdefault(key, {"ell": ell, "traces": 0})["traces"] += 1
    out = sorted(by_len.values(), key=lambda d: d["ell"])
    return out


def numeric_group(mat_a, mat_b, maxlen=6):
    """Same enumeration for a NUMERIC (control) group -- floats in, high-precision out."""
    A = mp.matrix(mat_a)
    B = mp.matrix(mat_b)

    def inv(M):
        det = M[0, 0] * M[1, 1] - M[0, 1] * M[1, 0]
        return mp.matrix([[M[1, 1] / det, -M[0, 1] / det], [-M[1, 0] / det, M[0, 0] / det]])

    alph = {"a": A, "A": inv(A), "b": B, "B": inv(B)}

    # DEDUPLICATE TRACES FIRST. The m004 path collects a SET of exact traces; if this path
    # counted words instead, "multiplicity" would compare distinct-traces-per-length against
    # words-per-length -- apples to oranges, and it inflates the control by ~100x. The first
    # version of this function did exactly that and made Cell 4's comparison meaningless.
    traces = {}
    for L in range(1, maxlen + 1):
        for word in itertools.product("aAbB", repeat=L):
            M = mp.eye(2)
            for ch in word:
                M = M * alph[ch]
            t = M[0, 0] + M[1, 1]
            traces[(mp.nstr(t.real, 10), mp.nstr(t.imag, 10))] = t

    by_len = {}
    for t in traces.values():
        if abs(t.imag) < 1e-10 and abs(t.real) <= 2 + 1e-10:
            continue
        lam = (t + mp.sqrt(t * t - 4)) / 2
        if abs(lam) < 1:
            lam = 1 / lam
        ell = 2 * mp.log(abs(lam))
        if ell < mp.mpf("1e-7"):
            continue
        key = mp.nstr(ell, 10)
        by_len.setdefault(key, {"ell": ell, "traces": 0})["traces"] += 1
    return sorted(by_len.values(), key=lambda d: d["ell"])


def ratio_is_rational(l1, l2, maxcoeff=10**6):
    """PSLQ for an integer relation p*l2 + q*l1 = 0. None means no relation within the bound."""
    rel = mp.pslq([l2, l1], maxcoeff=maxcoeff, maxsteps=2000)
    if rel is None:
        return False, None
    p, q = rel
    if p == 0 and q == 0:
        return False, None
    # verify the relation actually holds -- pslq can return a near-relation
    resid = abs(p * l2 + q * l1)
    return (resid < mp.mpf("1e-25")), [int(p), int(q)]


def discreteness(lengths, n_test=12, maxcoeff=10**6):
    """DISCRETE iff EVERY ratio l_i/l_1 is rational. One irrational ratio => DENSE."""
    if len(lengths) < 2:
        return dict(verdict="UNDETERMINED", reason="fewer than two lengths")
    l1 = lengths[0]["ell"]
    irrational, rational = [], []
    for d in lengths[1:n_test + 1]:
        ok, rel = ratio_is_rational(l1, d["ell"], maxcoeff)
        (rational if ok else irrational).append(
            dict(ell=mp.nstr(d["ell"], 14), ratio=mp.nstr(d["ell"] / l1, 14), relation=rel))
    return dict(verdict=("DISCRETE" if not irrational else "DENSE"),
                n_tested=len(rational) + len(irrational),
                n_rational=len(rational), n_irrational=len(irrational),
                first_irrational=irrational[0] if irrational else None,
                maxcoeff=maxcoeff)


def main():
    import warnings
    warnings.filterwarnings("ignore")
    import snappy

    res = {"seal": "f9d13b4d880301f7"}

    # ---- Cell 1: m004, exactly ----
    A, B = gens_m004()
    res["relator_verified"] = bool(check_relator(A, B))
    m004 = lengths_from_group(A, B, maxlen=6)
    systole = m004[0]["ell"]
    control_ok = abs(systole - KNOWN_SYSTOLE_M004) < mp.mpf("1e-9")
    res["cell1"] = dict(n_lengths=len(m004), systole=mp.nstr(systole, 15),
                        known_systole=mp.nstr(KNOWN_SYSTOLE_M004, 15),
                        systole_control_passes=bool(control_ok))

    if not control_ok:
        res["verdict"] = "INSTRUMENT VOID"
        json.dump(res, open(os.path.join(HERE, "results.json"), "w"), indent=1, sort_keys=True)
        print("INSTRUMENT VOID: systole", mp.nstr(systole, 15))
        return 1

    # ---- Cell 2: discrete or dense ----
    res["cell2_m004"] = discreteness(m004)

    # ---- Cell 3: controls ----
    controls = {}
    for name, note in [("m003", "the sister (arithmetic)"),
                       ("m015", "5_2 complement -- NON-arithmetic (m004 is the only "
                                "arithmetic knot complement)")]:
        M = snappy.Manifold(name)
        G = M.fundamental_group()
        gs = G.generators()
        mats = [[[complex(G.SL2C(g)[i, j]) for j in range(2)] for i in range(2)] for g in gs[:2]]
        L = numeric_group(mats[0], mats[1], maxlen=6)
        controls[name] = dict(note=note, n_lengths=len(L),
                              systole=mp.nstr(L[0]["ell"], 12) if L else None,
                              max_traces_per_length=max(d["traces"] for d in L) if L else None,
                              mean_traces_per_length=(float(sum(d["traces"] for d in L) / len(L))
                                                      if L else None),
                              **{k: v for k, v in discreteness(L).items()})
    res["cell3_controls"] = controls

    # ---- Cell 4: multiplicity (exploratory, no verdict) ----
    # The seal says "for m004 AGAINST the non-arithmetic control". The first implementation of
    # this cell measured m004 ALONE -- a number with nothing to compare it to, which is the same
    # narrower-than-the-seal defect B849's Cell 3 hit. Fixed to carry the comparison.
    res["cell4_multiplicity"] = dict(
        m004_max_traces_per_length=max(d["traces"] for d in m004),
        m004_mean=float(sum(d["traces"] for d in m004) / len(m004)),
        controls={k: dict(max=v["max_traces_per_length"], mean=v["mean_traces_per_length"])
                  for k, v in controls.items()},
        m004_exceeds_nonarithmetic_control=bool(
            max(d["traces"] for d in m004) > (controls["m015"]["max_traces_per_length"] or 0)),
        note=("exploratory, no verdict: arithmetic manifolds carry higher length-spectrum "
              "multiplicity (Vigneras). m015 is the non-arithmetic control."))

    # ---- verdicts, read off the SEALED criteria ----
    verdicts = {"m004": res["cell2_m004"]["verdict"]}
    for k, v in controls.items():
        verdicts[k] = v["verdict"]
    all_same = len(set(verdicts.values())) == 1
    res["verdicts"] = verdicts
    res["genericity"] = "GENERIC" if all_same else "OBJECT-SPECIFIC"
    res["type_conditional"] = ("III_1 (CONDITIONAL on the cited reduction)"
                               if verdicts["m004"] == "DENSE" else
                               "III_lambda (CONDITIONAL on the cited reduction)")

    json.dump(res, open(os.path.join(HERE, "results.json"), "w"), indent=1, sort_keys=True)

    print("=" * 78)
    print("B850 -- length spectrum -> foliation type (the computable shadow)")
    print("=" * 78)
    print(f"\n  relator verified over Z[omega] : {res['relator_verified']}")
    print(f"  CELL 1 systole control          : {res['cell1']['systole']} vs known "
          f"{res['cell1']['known_systole']} -> {res['cell1']['systole_control_passes']}")
    print(f"  distinct lengths (words <= 6)   : {res['cell1']['n_lengths']}")

    c2 = res["cell2_m004"]
    print(f"\n  CELL 2 m004: {c2['verdict']}   "
          f"({c2['n_rational']} rational / {c2['n_irrational']} irrational ratios, "
          f"pslq maxcoeff {c2['maxcoeff']})")
    if c2["first_irrational"]:
        fi = c2["first_irrational"]
        print(f"    first irrational ratio: l/l_1 = {fi['ratio']}  (no integer relation found)")

    print(f"\n  CELL 3 controls")
    for k, v in controls.items():
        print(f"    {k:6} {v['verdict']:9} ({v['n_rational']}R/{v['n_irrational']}I, "
              f"{v['n_lengths']} lengths)   {v['note'][:44]}")

    c4 = res["cell4_multiplicity"]
    print(f"\n  CELL 4 multiplicity (exploratory, no verdict)")
    print(f"    m004 (arithmetic)     max {c4['m004_max_traces_per_length']}  "
          f"mean {c4['m004_mean']:.2f}")
    for k, v in c4["controls"].items():
        print(f"    {k:21} max {v['max']}  mean {v['mean']:.2f}")
    print(f"    m004 exceeds the NON-arithmetic control (m015)? "
          f"{c4['m004_exceeds_nonarithmetic_control']}")

    print(f"\n  VERDICTS  : {verdicts}")
    print(f"  GENERICITY: {res['genericity']}")
    print(f"  TYPE      : {res['type_conditional']}")
    print("\n  Per the seal: the DENSE/DISCRETE binary was pre-stated as FORCED by classical")
    print("  theory (mixing requires a non-lattice length spectrum). It is a VERIFICATION,")
    print("  not a finding. The arc's product is the GENERICITY line above.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
