"""B1304 Q3 -- the audit seat's counterexample to B1259's inference, checked with own exact code (DESIGN sealed 866bd71e).
G = (Z/2)^3 acting on R^7 by diagonal signs (-1)^{a.v} on the seven non-zero vectors v of F_2^3 (the coordinates), phi the standard G2
three-form. Predictions: all 8 matrices preserve phi and have det +1; every non-identity element fixes a 3-plane (B1259's lemma);
the common fixed dimension by subgroup order is {1: 7, 2: 3, 4: 1, 8: 0} over all 16 subgroups -> the origin is an isolated
maximal-isotropy stratum although no single element has an isolated fixed point."""
import itertools, json, sys
fails = []
def check(label, ok):
    print(("  [PASS] " if ok else "  [FAIL] ") + label)
    if not ok: fails.append(label)
# coordinates 1..7 <-> non-zero vectors of F_2^3 in the order that makes the standard phi's triples the Fano lines:
# phi = e123 + e145 + e167 + e246 - e257 - e347 - e356 ; assign v1=(1,0,0), v2=(0,1,0), v3=(1,1,0), v4=(0,0,1), v5=(1,0,1), v6=(0,1,1), v7=(1,1,1)
V = {1: (1, 0, 0), 2: (0, 1, 0), 3: (1, 1, 0), 4: (0, 0, 1), 5: (1, 0, 1), 6: (0, 1, 1), 7: (1, 1, 1)}
PHI = {(1, 2, 3): 1, (1, 4, 5): 1, (1, 6, 7): 1, (2, 4, 6): 1, (2, 5, 7): -1, (3, 4, 7): -1, (3, 5, 6): -1}
def xor3(*vs): return tuple(sum(c) % 2 for c in zip(*vs))
check("every triple of phi is a line of the Fano plane under this labelling (v_i + v_j + v_k = 0)", all(xor3(V[i], V[j], V[k]) == (0, 0, 0) for (i, j, k) in PHI))
def sign(a, v): return -1 if sum(x * y for x, y in zip(a, v)) % 2 else 1
G = [tuple(sign(a, V[i]) for i in range(1, 8)) for a in itertools.product((0, 1), repeat=3)]   # 8 diagonal matrices as sign tuples
def preserves_phi(s): return all(s[i - 1] * s[j - 1] * s[k - 1] == 1 for (i, j, k) in PHI)
def det(s):
    d = 1
    for x in s: d *= x
    return d
check("all eight sign matrices preserve phi exactly and have det +1", all(preserves_phi(s) and det(s) == 1 for s in G))
def fixed_dim(elems): return sum(1 for i in range(7) if all(s[i] == 1 for s in elems))
nonid = [s for s in G if any(x == -1 for x in s)]
check("every non-identity element fixes exactly a 3-plane (B1259's lemma holds element by element)", all(fixed_dim([s]) == 3 for s in nonid))
# all subgroups of (Z/2)^3: closed subsets generated by subsets
def mul(s, t): return tuple(x * y for x, y in zip(s, t))
def span(gens):
    H = {G[0]}
    frontier = list(gens)
    while frontier:
        g = frontier.pop()
        if g in H: continue
        H.add(g)
        for h in list(H):
            p = mul(g, h)
            if p not in H: frontier.append(p)
    return frozenset(H)
subgroups = set()
for r in range(0, 4):
    for gens in itertools.combinations(G, r): subgroups.add(span(gens))
table = {}
for H in subgroups: table.setdefault(len(H), []).append(fixed_dim(H))
table = {k: sorted(set(v)) + [len(v)] for k, v in sorted(table.items())}
print("  subgroups by order -> [common fixed dimensions..., count]:", table)
check("16 subgroups: orders 1 (x1) fix 7, 2 (x7) fix 3, 4 (x7) fix 1, 8 (x1) fix 0", table == {1: [7, 1], 2: [3, 7], 4: [1, 7], 8: [0, 1]})
# isotropy at sample points: a generic plane point, an axis point, a free point, the origin
def isotropy_order(x): return sum(1 for s in G if all((s[i] == 1) or (x[i] == 0) for i in range(7)))
pts = {"origin": (0,) * 7, "axis point (only coordinate 1)": (1, 0, 0, 0, 0, 0, 0), "generic point of the 3-plane fixed by a = (0,0,1)": tuple(1 if V[i][2] == 0 else 0 for i in range(1, 8)), "free point": (1, 1, 1, 1, 1, 1, 1)}
iso = {k: isotropy_order(x) for k, x in pts.items()}; print("  isotropy orders:", iso)
check("isotropy orders: plane point 2, axis point 4, free point 1, origin 8 -> the origin is an isolated maximal-isotropy stratum", iso["generic point of the 3-plane fixed by a = (0,0,1)"] == 2 and iso["axis point (only coordinate 1)"] == 4 and iso["free point"] == 1 and iso["origin"] == 8)
# control that the test can fail: a wrong sign matrix (flip one sign) must NOT preserve phi
bad = list(G[1]); bad[0] *= -1; check("control: a wrong sign matrix is rejected by the phi test", not preserves_phi(tuple(bad)))
json.dump(dict(table=table, isotropy=iso, fails=fails), open("b1304_g2_strata.json", "w"), indent=1)
print("Q3:", "PASS" if not fails else f"FAIL ({len(fails)})"); sys.exit(0 if not fails else 1)
