"""B1039 -- two more of B1037's seven clusters restored, re-verified before restoring.

B1037 dispositioned B100-B199: 37 debt rows are 17 statements. B1038 restored the tower. This
restores the two clusters that rest on algebra this sandbox can redo from scratch:

  * phi-fixed reducibility   (B141 + B142)
  * the metallic exponent    (B154 + B198)

Campaign step 5: "restorations bank as arcs -- re-verify the identities before restoring, NEVER
restore from memory."  Re-verifying found TWO defects in what was about to be restored:

  (1) B141 Item 3's slogan "finite image => reducible tower" is FALSE as a general implication.
      Counterexample computed below: the binary tetrahedral group SL(2,3) is finite and its Sym^2
      is IRREDUCIBLE. The true statement -- and all B141 needs -- is bounded by the MAXIMAL IRREP
      DIMENSION, which for Q8 is 2. Restored in the narrowed form.
  (2) B142's Klein-4 chain needs A SEMISIMPLE; spectrum {1,-1,-1} alone does not give A^2 = I.
      Counterexample computed below (a Jordan block at -1). And B142's own probe never verified
      the general lemma -- it exhibited one commuting pair. The lemma is verified here as a
      group-theoretic identity (coset enumeration) for the first time.

Nothing here is numerics-from-memory: the one claim resting on a machine search (B198's SL(5)
o=5 k=2) is re-checked against its BANKED CERTIFICATE, and the grid counterexample that refutes
k = 7-o is re-run in-sandbox.
"""
import json
import pathlib

import mpmath as mp
import numpy as np
import sympy as sp
from sympy import I, Rational

ROOT = pathlib.Path(__file__).resolve().parents[2]
R = {"checks": {}}
xs, ys = sp.symbols("x y")


def chk(name, ok, **d):
    R["checks"][name] = {"pass": bool(ok), **d}
    return ok


# ================================================================= instrument + its own controls
def sym_power(M, d):
    """Sym^d of a 2x2 matrix, on the monomial basis x^(d-i) y^i.

    NOTE the TRANSPOSE. Substituting the coordinates directly -- b(x,y) -> b(Mv) -- makes
    Sym^d an ANTI-homomorphism: Sym^d(MN) = Sym^d(N)Sym^d(M). Acting through M^T restores
    covariance. This is exactly the contravariance bug-class B154 records catching with its
    figure-eight control ("characters transform CONTRAVARIANTLY"), and it was caught here the
    same way -- by the instrument control below, not by a wrong answer downstream.
    """
    basis = [xs**(d - i) * ys**i for i in range(d + 1)]
    nx = M[0, 0] * xs + M[1, 0] * ys
    ny = M[0, 1] * xs + M[1, 1] * ys
    cols = []
    for b in basis:
        p = sp.Poly(sp.expand(b.subs({xs: nx, ys: ny}, simultaneous=True)), xs, ys)
        cols.append([sp.expand(p.coeff_monomial(bb)) for bb in basis])
    return sp.Matrix(cols).T


def algebra_dim(gens, n):
    """Exact dimension of the unital algebra generated by `gens` inside M_n -- the Burnside test:
    the representation is irreducible iff this is n^2."""
    def rank_of(ms):
        return sp.Matrix([list(m) for m in ms]).rank()
    seen, frontier = [sp.eye(n)], [sp.eye(n)]
    cur = 1
    for _ in range(2 * n * n):
        newf = []
        for m in frontier:
            for g in gens:
                p = sp.expand(m * g)
                if rank_of(seen + [p]) > cur:
                    seen = seen + [p]
                    cur = rank_of(seen)
                    newf.append(p)
        if not newf or cur >= n * n:
            break
        frontier = newf
    return cur


def group_closure(gens, cap=400):
    S = {sp.ImmutableMatrix(sp.expand(g)) for g in gens}
    while True:
        new = {sp.ImmutableMatrix(sp.simplify(sp.expand(a * b))) for a in S for b in S}
        if new <= S:
            return S
        S |= new
        if len(S) > cap:
            return S


# control: Sym^d has the right dimension, is functorial, and has the determinant B1038 derived.
# Symbolically to d = 3 (where `expand` suffices -- `simplify` on degree-8 entries is not needed
# for a polynomial identity), then against EXPLICIT matrices at d = 4, 5 -- B1038's own pattern.
Mg = sp.Matrix([[sp.Symbol("p"), sp.Symbol("q")], [sp.Symbol("r"), sp.Symbol("s")]])
Ng = sp.Matrix([[sp.Symbol("u"), sp.Symbol("v")], [sp.Symbol("w"), sp.Symbol("z")]])
EXPL = [sp.Matrix([[2, 1], [1, 1]]), sp.Matrix([[1, 1], [0, 1]]),
        sp.Matrix([[0, 1], [-1, 0]]), sp.Matrix([[3, 2], [4, 3]])]
chk("instrument_control_Sym_is_functorial_and_graded_correctly",
    all(sym_power(Mg, d).shape == (d + 1, d + 1) for d in range(6))
    and all(sp.expand(sym_power(Mg * Ng, d) - sym_power(Mg, d) * sym_power(Ng, d)) == sp.zeros(d + 1)
            for d in range(4))
    and all(sp.expand(sp.factor(sym_power(Mg, d).det())
                      - Mg.det()**(sp.Rational(d * (d + 1), 2))) == 0 for d in range(1, 4))
    and all(sp.expand(sym_power(E, d).det() - E.det()**(sp.Rational(d * (d + 1), 2))) == 0
            for E in EXPL for d in (4, 5))
    and all(sp.expand(sym_power(EXPL[0] * EXPL[1], d)
                      - sym_power(EXPL[0], d) * sym_power(EXPL[1], d)) == sp.zeros(d + 1)
            for d in (4, 5)),
    note="Sym^d(MN) = Sym^d(M)Sym^d(N) and det Sym^d = (det)^{d(d+1)/2} -- B1038's identity, "
         "reused. THIS CONTROL FAILED ON THE FIRST RUN: substituting coordinates directly makes "
         "Sym^d an ANTI-homomorphism, B154's own contravariance bug-class. Fixed by acting "
         "through M^T. Nothing downstream would have looked wrong -- an algebra's opposite has "
         "the same dimension and a group's opposite the same irrep dimensions")

# ======================================================= PART A -- phi-fixed reducibility (B141+B142)

# --------- A1. the two towers are told apart by a DETERMINANT, before any representation is built
# phi (the golden map): A -> AB, B -> A.   phi^2-object (the bundle): sigma_R o sigma_L.
Mphi = sp.Matrix([[1, 1], [1, 0]])          # abelianisation of A->AB, B->A
Mbun = sp.Matrix([[2, 1], [1, 1]])          # abelianisation of A->A^2B, B->AB
phi = (1 + sp.sqrt(5)) / 2
chk("A1_the_split_is_a_determinant_sign",
    Mphi.det() == -1 and Mbun.det() == 1 and Mphi.trace() == 1 and Mbun.trace() == 3
    and sp.simplify(sp.Matrix(Mphi).charpoly().as_expr().subs(sp.Symbol("lambda"), phi)) == 0
    and sorted(sp.nsimplify(v) for v in Mbun.eigenvals()) == sorted([sp.simplify(phi**2),
                                                                    sp.simplify(phi**-2)]),
    det_phi=-1, det_bundle=1,
    note="det = -1 (phi, discrete fixed points) vs det = +1 (phi^2 = R^mL^m, the hyperbolic bundle)")

# --------- A2. the trace map is DERIVED from Cayley-Hamilton, not quoted
pa, pb, pc, pd, pe, pf, pg, ph = sp.symbols("pa pb pc pd pe pf pg ph")
Ag = sp.Matrix([[pa, pb], [pc, pd]])
Bg = sp.Matrix([[pe, pf], [pg, ph]])
onedet = {pd: (1 + pb * pc) / pa, ph: (1 + pf * pg) / pe}


def trg(M):
    return sp.simplify(sp.expand(M.trace()).subs(onedet))


gx, gy, gz = trg(Ag), trg(Bg), trg(Ag * Bg)
chk("A2_the_induced_trace_map_is_derived_not_asserted",
    sp.simplify(trg(Ag * Bg * Ag) - (gx * gz - gy)) == 0,
    trace_map="(x,y,z) -> (z, x, xz - y)",
    note="phi: A->AB, B->A induces (tr A, tr B, tr AB) -> (tr AB, tr A, tr ABA); "
         "tr(ABA) = tr(A^2 B) = xz - y by Cayley-Hamilton, verified on generic det-1 matrices")

# --------- A3. the fixed points, solved exactly -- and the bridge equation reads them
X, Y, Z = sp.symbols("X Y Z")
sols = sp.solve([Z - X, X - Y, X * Z - Y - Z], [X, Y, Z], dict=True)
kappa = X**2 + Y**2 + Z**2 - X * Y * Z - 2
kvals = {(int(s[X]), int(s[Y]), int(s[Z])): sp.simplify(kappa.subs(s)) for s in sols}
chk("A3_exactly_two_phi_fixed_points_in_the_SL2_character_variety",
    set(kvals) == {(0, 0, 0), (2, 2, 2)},
    fixed_points=sorted(kvals))
chk("A3b_the_bridge_equation_picks_out_which_one_is_irreducible",
    kvals[(0, 0, 0)] == -2 and kvals[(2, 2, 2)] == 2,
    kappa_at_000=-2, kappa_at_222=2,
    note="kappa = 2 <=> the cancellation completes <=> reducible. So (2,2,2) is the reducible "
         "fixed point and (0,0,0), with kappa = -2, is the UNIQUE irreducible one -- the founding "
         "sentence doing the selection")

# --------- A4. that unique point IS Q8, built and closed
Aq = sp.Matrix([[I, 0], [0, -I]])
Bq = sp.Matrix([[0, 1], [-1, 0]])
chk("A4_the_irreducible_fixed_point_is_at_(0,0,0)",
    (Aq.trace(), Bq.trace(), (Aq * Bq).trace()) == (0, 0, 0) and Aq.det() == 1 and Bq.det() == 1)
chk("A4b_and_the_group_it_generates_is_Q8",
    sp.simplify(Aq * Aq + sp.eye(2)) == sp.zeros(2)
    and sp.simplify(Bq * Bq + sp.eye(2)) == sp.zeros(2)
    and sp.simplify(Aq * Bq + Bq * Aq) == sp.zeros(2)
    and len(group_closure([Aq, Bq])) == 8,
    order=8, relations="A^2 = B^2 = -I, AB = -BA")

# --------- A5. Q8's maximal irrep dimension is 2 -- DERIVED from order + class count
Q8 = list(group_closure([Aq, Bq]))
classes = []
for g in Q8:
    orb = {sp.ImmutableMatrix(sp.simplify(sp.expand(h * g * h.inv()))) for h in Q8}
    if not any(orb & c for c in classes):
        classes.append(orb)
part = [p for p in sp.utilities.iterables.partitions(8, m=len(classes), k=8)
        if sum(p.values()) == len(classes) and all(sp.sqrt(d) == int(sp.sqrt(d)) for d in p)]
dims = sorted([int(sp.sqrt(d)) for d, c in part[0].items() for _ in range(c)]) if len(part) == 1 else None
chk("A5_Q8_has_five_classes_hence_five_irreps_and_the_dims_are_FORCED",
    len(classes) == 5 and len(part) == 1 and dims == [1, 1, 1, 1, 2],
    n_classes=len(classes), irrep_dims=dims,
    note="sum of squares = |G| = 8 over exactly 5 irreps has the unique solution 1+1+1+1+4; "
         "max irrep dim = 2 is derived here, not quoted from a character table")

# --------- A6. therefore the whole tower is reducible -- for ALL n >= 3, not just the table
tab = {}
for n in range(2, 8):
    tab[n] = algebra_dim([sym_power(Aq, n - 1), sym_power(Bq, n - 1)], n)
chk("A6_the_Q8_Sym_tower_algebra_dimensions_reproduce_B141s_table",
    [tab[n] for n in range(2, 8)] == [4, 3, 4, 4, 4, 4],
    table={n: [tab[n], n * n] for n in tab})
chk("A6b_irreducible_at_n=2_ONLY_by_the_Burnside_criterion",
    tab[2] == 4 and all(tab[n] < n * n for n in range(3, 8)))
chk("A6c_and_the_all_n_step_is_a_dimension_inequality_not_a_search",
    all(sym_power(Aq, n - 1).shape[0] == n and n > 2 for n in range(3, 40)),
    note="dim Sym^{n-1} = n > 2 = max irrep dim of Q8, for every n >= 3. The table is a "
         "cross-check; the theorem is the inequality")

# --------- A7. the character cross-check B141 records
cls_reps = [sp.eye(2), -sp.eye(2), Aq, Bq, sp.simplify(Aq * Bq)]
chi2 = [sp.simplify(sym_power(g, 2).trace()) for g in cls_reps]
inner = sp.simplify(sum(abs(c)**2 for c in chi2) * sp.Rational(1, 8) * 2)   # class sizes 1,1,2,2,2
chk("A7_the_Sym2_character_decomposes_into_three_one_dimensionals",
    chi2 == [3, 3, -1, -1, -1],
    chi=[str(c) for c in chi2],
    note="chi_{Sym^2 V} = (3,3,-1,-1,-1) on classes (1,-1,i,j,k) -- B141's cross-check, reproduced")

# --------- A8. THE CORRECTION: B141 Item 3's slogan is false, and here is the counterexample
Cq = Rational(1, 2) * sp.Matrix([[-1 + I, -1 + I], [1 + I, -1 - I]])
BT = group_closure([Aq, Bq, Cq], cap=60)
bt_sym2 = algebra_dim([sym_power(M, 2) for M in (Aq, Bq, Cq)], 3)
chk("A8_CORRECTION_finite_image_does_NOT_imply_a_reducible_tower",
    Cq.det() == 1 and len(BT) == 24 and bt_sym2 == 9,
    group="binary tetrahedral SL(2,3)", order=len(BT), sym2_algebra_dim=bt_sym2,
    note="SL(2,3) is FINITE (order 24) and its Sym^2 is IRREDUCIBLE (algebra dim 9 = 3^2). "
         "B141 Item 3's 'finite image => reducible tower' is false as stated. Its max irrep dim "
         "is 3, so the tower is reducible only for n > 3 -- the bound is the MAX IRREP DIMENSION, "
         "not finiteness. For Q8 that bound is 2, which is why B141's conclusion survives intact")
chk("A8b_the_narrowed_law_is_the_one_that_is_true",
    3 > 2 and bt_sym2 == 9 and tab[3] < 9,
    law="max irrep dim d  =>  Sym^{n-1} (dim n) is reducible for every n > d",
    note="the two groups sit on opposite sides of their own bound at n = 3: Q8 (d=2) reducible, "
         "SL(2,3) (d=3) irreducible. The bound is sharp, and finiteness alone is not the reason")

# --------- A9. the Klein-4 lemma, verified as a GROUP identity for the first time
from sympy.combinatorics.free_groups import free_group          # noqa: E402
from sympy.combinatorics.fp_groups import FpGroup               # noqa: E402
Ff, fa, fb = free_group("fa fb")
K4 = FpGroup(Ff, [fa**2, fb**2, (fa * fb)**2])
chk("A9_two_involutions_whose_product_is_an_involution_COMMUTE",
    K4.order() == 4 and K4.reduce(fa * fb * fa**-1 * fb**-1) == Ff.identity,
    order=4,
    note="<a,b | a^2, b^2, (ab)^2> has order 4 and trivial commutator -- the Klein 4-group. "
         "B142's own probe exhibited one commuting PAIR; the universally quantified lemma is "
         "verified here by coset enumeration")

# --------- A10. THE SECOND CORRECTION: the chain needs semisimplicity
Dss = sp.diag(1, -1, -1)
Jns = sp.Matrix([[1, 0, 0], [0, -1, 1], [0, 0, -1]])
chk("A10_CORRECTION_spectrum_alone_does_not_give_an_involution",
    sp.simplify(Dss * Dss - sp.eye(3)) == sp.zeros(3)
    and Jns.eigenvals() == {sp.Integer(1): 1, sp.Integer(-1): 2} and Jns.det() == 1
    and sp.simplify(Jns * Jns - sp.eye(3)) != sp.zeros(3),
    note="B142 writes 'principal eigenvalues {1,-1,-1} => A^2 = I'. That needs A SEMISIMPLE: the "
         "Jordan form with a 2x2 block at -1 has the same spectrum and det 1 but is not an "
         "involution. The hypothesis holds at a phi-fixed point (A is conjugate to diag(1,-1,-1) "
         "by fiat) -- but it is a hypothesis, and it was unstated")

# --------- A11. the conjugacy that feeds the lemma is itself pure algebra
gg = sp.Symbol("gg")
chk("A11_the_phi_fixed_condition_forces_A_~_B_~_AB",
    True,
    derivation="g B g^-1 = A  =>  B ~ A ;  g A g^-1 = AB  =>  AB ~ A. Hence A ~ B ~ AB, so all "
               "three are conjugate to diag(1,-1,-1) and all three are involutions",
    note="a rewriting consequence of the phi-fixed system, not a computation -- recorded as the "
         "step that carries the semisimplicity hypothesis of A10 to B and AB")

# --------- A12. commuting involutions in dim 3 cannot be irreducible
K4reps = group_closure([Dss, sp.diag(-1, 1, -1)])
chk("A12_a_Klein_4_group_has_only_one_dimensional_irreps_so_dim_3_is_reducible",
    len(K4reps) == 4 and algebra_dim(list(K4reps), 3) < 9,
    order=4, algebra_dim=algebra_dim(list(K4reps), 3),
    note="abelian => every irrep is 1-dimensional => a 3-dim rep splits. This closes B142's chain")

# --------- A13. the OTHER side of the split: dense image, irreducible tower
om = Rational(1, 2) + Rational(1, 2) * sp.sqrt(-3)
Ad = sp.Matrix([[1, 1], [0, 1]])
Bd = sp.Matrix([[1, 0], [-om, 1]])
dense = {}
for n in range(2, 6):
    dense[n] = algebra_dim([sym_power(Ad, n - 1), sym_power(Bd, n - 1)], n)
kk = sp.Symbol("kk", positive=True, integer=True)
chk("A13_the_phi_squared_geometric_tower_is_irreducible_for_n=2..5",
    all(dense[n] == n * n for n in dense), table=dense)
chk("A13b_and_its_image_is_INFINITE_which_is_why",
    sp.simplify((Ad**3) - sp.Matrix([[1, 3], [0, 1]])) == sp.zeros(2)
    and sp.simplify((Ad**7) - sp.Matrix([[1, 7], [0, 1]])) == sp.zeros(2),
    note="A^k = [[1,k],[0,1]] is unbounded, so the image is infinite -- Zariski-dense in SL(2,C), "
         "and density (not merely infinitude) is what carries irreducibility to every n. The "
         "all-n step is the density theorem, cited; n = 2..5 is computed here")
tr_words = [sp.expand(sp.simplify((Ad**i * Bd**j).trace())) for i in (1, 2) for j in (1, 2)]
chk("A13c_all_word_traces_lie_in_Q(sqrt-3)",
    all(sp.simplify(sp.im(sp.expand(t) / sp.sqrt(3))).is_rational is not False for t in tr_words),
    traces=[str(t) for t in tr_words])

# ======================================================= PART B -- the metallic exponent (B154+B198)

def _red(w):
    out = []
    for gg_ in w:
        if out and out[-1][0] == gg_[0] and out[-1][1] == -gg_[1]:
            out.pop()
        else:
            out.append(gg_)
    return tuple(out)


def _inv(w):
    return _red(tuple((s, -e) for s, e in reversed(w)))


def _mul(*ws):
    out = ()
    for w in ws:
        out = _red(out + w)
    return out


WA, WB = (("A", 1),), (("B", 1),)


def _sub(w, imA, imB):
    out = ()
    for s, e in w:
        im = imA if s == "A" else imB
        out = _red(out + (im if e == 1 else _inv(im)))
    return out


def sig_R(w):
    return _sub(w, WA, _mul(WA, WB))


def sig_L(w):
    return _sub(w, _mul(WA, WB), WB)


def PHI(w, m):
    """phi_m = sigma_R^m o sigma_L^m -- the metallic monodromy on F_2 = <A,B>."""
    for _ in range(m):
        w = sig_L(w)
    for _ in range(m):
        w = sig_R(w)
    return w


def _pow(w, k):
    if k == 0:
        return ()
    return _mul(*([w] * k)) if k > 0 else _inv(_mul(*([w] * (-k))))


def _abel(w):
    return (sum(e for s, e in w if s == "A"), sum(e for s, e in w if s == "B"))


COMM = _mul(WA, WB, _inv(WA), _inv(WB))

# --------- B1. the monodromy words, recomputed
chk("B1_the_figure_eight_and_silver_monodromy_words",
    PHI(WA, 1) == _mul(WA, WA, WB) and PHI(WB, 1) == _mul(WA, WB)
    and PHI(WA, 2) == _mul(_pow(WA, 3), WB, _pow(WA, 2), WB) and PHI(WB, 2) == _mul(_pow(WA, 2), WB),
    m1="A -> A^2 B,  B -> AB", m2="A -> A^3 B A^2 B,  B -> A^2 B")

# --------- B2. abelianisation is the SQUARE of the metallic matrix, for every m checked
ab_ok, ab_tab = True, {}
for m in range(1, 8):
    Mm = sp.Matrix([[m, 1], [1, 0]])
    ca, cb = _abel(PHI(WA, m)), _abel(PHI(WB, m))
    P = sp.Matrix([[ca[0], cb[0]], [ca[1], cb[1]]])
    ab_ok &= (P == Mm * Mm) and (P.trace() == m * m + 2)
    ab_tab[m] = [P.tolist(), int(P.trace())]
chk("B2_abelianisation_of_phi_m_is_M_m_squared_with_trace_m2_plus_2", ab_ok, table=ab_tab,
    note="m=1 gives [[2,1],[1,1]], trace 3 -- the object's own matrix A = LR")

# --------- B3. THE LOAD-BEARING IDENTITY, extended past the two values the arc verified
id_ok = {m: PHI(COMM, m) == _mul(_pow(WA, m), COMM, _pow(WA, -m)) for m in range(1, 11)}
chk("B3_phi_m_of_the_commutator_is_A^m_[A,B]_A^-m_exactly_in_the_free_group",
    all(id_ok.values()), verified_for_m=sorted(id_ok),
    note="an EXACT free-group identity, by word reduction. B154 verified m = 1, 2; this extends "
         "it to m = 1..10. Still not a proof for all m -- the induction was never written down, "
         "and that gap is carried, not closed")

# --------- B4. the meridian, DERIVED from that identity rather than fitted
mu_ok = {}
for m in range(1, 7):
    # mu = A^-m t;  conjugation by t implements phi_m (the mapping-torus relation t X t^-1 = phi(X))
    mu_ok[m] = _mul(_pow(WA, -m), PHI(COMM, m), _pow(WA, m)) == COMM
chk("B4_therefore_mu_equals_A^-m_t_commutes_with_the_longitude",
    all(mu_ok.values()), verified_for_m=sorted(mu_ok),
    derivation="mu [A,B] mu^-1 = A^-m (t [A,B] t^-1) A^m = A^-m phi_m([A,B]) A^m = [A,B]",
    note="the input is the mapping-torus relation t X t^-1 = phi(X), which DEFINES the bundle; "
         "the conclusion is that mu = A^-m t is peripheral -- the cusp meridian")

# --------- B5. and the exponent m in that meridian is FORCED, not chosen
forced = {}
for m in (1, 2, 3):
    forced[m] = [k for k in range(0, 7)
                 if _mul(_pow(WA, m - k), COMM, _pow(WA, k - m)) == COMM]
chk("B5_the_meridians_exponent_is_uniquely_forced_to_m",
    all(forced[m] == [m] for m in forced), table=forced,
    note="A^-k t is peripheral only at k = m. In the free group A^j commutes with [A,B] only for "
         "j = 0, so the m in mu = A^-m t is derived from the monodromy, not fitted to data")

# --------- B6. the banked SL(5) certificate, re-checked rather than re-searched
mp.mp.dps = 40
CERT = json.loads((ROOT / "frontier/B198_metallic_exponent_CAS/cert_sl5o5_rep.json")
                  .read_text(encoding="utf-8"))
o_c, n_c, exps_c = CERT["o"], CERT["n"], CERT["exps"]
tc = mp.matrix([[mp.mpc(mp.mpf(CERT["t"][i][j][0]), mp.mpf(CERT["t"][i][j][1]))
                 for j in range(n_c)] for i in range(n_c)])
zc = mp.exp(2j * mp.pi / o_c)
Ac = mp.diag([zc**k for k in exps_c])
Aic = mp.diag([1 / (zc**k) for k in exps_c])
Bc = Aic * Aic * tc * Ac * (tc**-1)          # m = 1 collapses the system to t alone
muc = Aic * tc
Lc = Ac * Bc * (Ac**-1) * (Bc**-1)


def _nrm(M):
    return float(max(abs(M[i, j]) for i in range(n_c) for j in range(n_c)))


nbr = {k: _nrm(Lc - muc**k) for k in range(0, 5)}
chk("B6_the_certified_SL5_o5_rep_satisfies_[A,B]_=_mu^2_and_no_neighbour",
    nbr[2] < 1e-15 and min(nbr[k] for k in nbr if k != 2) > 1.0,
    residuals={str(k): "%.3e" % v for k, v in nbr.items()},
    note="re-checked from the banked witness at dps=40, NOT re-searched. B198 quotes the "
         "neighbour norms as 3.9 and 8.2; measured here 3.878 and 8.230")
Anp = np.array([[complex(Ac[i, j]) for j in range(n_c)] for i in range(n_c)])
Bnp = np.array([[complex(Bc[i, j]) for j in range(n_c)] for i in range(n_c)])
wordset, cur_w = [np.eye(n_c, dtype=complex)], [np.eye(n_c, dtype=complex)]
for _ in range(6):
    cur_w = [w @ gm for w in cur_w for gm in (Anp, Bnp)]
    wordset += cur_w
burnside = int(np.linalg.matrix_rank(np.array([w.flatten() for w in wordset]), tol=1e-8))
evmu = [complex(e) for e in mp.eig(muc, left=False, right=False)]
loxo = max(abs(abs(e) - 1) for e in evmu)
finite_order = next((d for d in range(1, 121) if max(abs(e**d - 1) for e in evmu) < 1e-6), None)
chk("B6b_and_that_rep_is_irreducible_and_on_the_GEOMETRIC_component",
    burnside == n_c * n_c and loxo > 0.1 and finite_order is None and _nrm(muc - tc) > 1e-6,
    burnside_rank=burnside, max_abs_eig_minus_1="%.4f" % loxo, order_of_mu="INFINITE",
    norm_mu_minus_t="%.4f" % _nrm(muc - tc),
    note="mu loxodromic and of infinite order = the cusped/geometric stratum, where k is an "
         "honest integer. B198 quotes ||mu - t|| = 2.19; measured 2.1876")

# --------- B7. the counterexample that kills the closed form, RE-RUN here (not quoted)
# The arc's own reproducer is invoked rather than reimplemented -- the B1033 pattern. This is the
# slow check (Newton at SL(3) and SL(4)); it is what makes the refutation measured rather than
# remembered, so it is not skipped.
import subprocess  # noqa: E402
import sys         # noqa: E402
import re as _re   # noqa: E402

_out = subprocess.run([sys.executable,
                       str(ROOT / "frontier/B198_metallic_exponent_CAS/meridian_order.py"),
                       "--grid"], capture_output=True, text=True, timeout=3600)
GRID = {}
for _line in _out.stdout.splitlines():
    _m = _re.search(r"o=(\d+) m=(\d+)\s*:.*->\s*(\{.*\})", _line)
    if _m:
        GRID["o=%s,m=%s" % (_m.group(1), _m.group(2))] = eval(_m.group(3))  # noqa: S307
chk("B7_no_closed_form_k(o,m)_survives_o=4_and_o=8_BOTH_give_k=3",
    _out.returncode == 0 and set(GRID) == {"o=4,m=1", "o=8,m=1"}
    and set(GRID["o=4,m=1"]) == set(GRID["o=8,m=1"]) == {3}
    and min(GRID["o=4,m=1"][3], GRID["o=8,m=1"][3]) >= 8,
    grid={k: {str(a): b for a, b in v.items()} for k, v in GRID.items()},
    predicted_by_k_eq_7_minus_o={"o=4": 3, "o=8": -1},
    note="measured here by re-running the arc's own reproducer (numpy Newton, mu-infinite "
         "filter), NOT quoted from B198. k = 7-o predicts 3 and -1, and k = 4-m(o-3) likewise; "
         "both are REFUTED by o=8 giving the same k=3 as o=4 on the geometric stratum")
chk("B7b_and_the_refuted_closed_forms_are_named_so_they_cannot_be_restored",
    True,
    refuted=["k = 4 - m(o-3)  (B157, bronze m=3: (3,4)->3 not 1, (3,6)->1 not -5)",
             "k = 7 - o       (B198 grid: o=8 gives 3, not -1)",
             "the gcd(m,o) lead", "the existence-boundary claim"],
    survives="k is ORDER-determined and RANK-independent: o=3 => k=4 at n=3 and n=4, for m=1,2")

# ======================================================= PART C -- restored, with the scope attached
LAWMAP = (ROOT / "docs/LAW_MAP.md").read_text(encoding="utf-8")
chk("C1_the_phi_fixed_law_is_on_a_curated_surface",
    "FINITENESS VERSUS DENSITY SPLITS THE TOWER" in LAWMAP
    and all(b in LAWMAP for b in ("B141", "B142")))
chk("C1b_and_it_carries_the_NARROWED_form_not_the_false_slogan",
    "max irrep dim" in LAWMAP and "SL(2,3)" in LAWMAP and "semisimple" in LAWMAP)
chk("C2_the_metallic_exponent_law_is_on_a_curated_surface",
    "ORDER-DETERMINED, NOT RANK-DETERMINED" in LAWMAP
    and all(b in LAWMAP for b in ("B154", "B198")))
chk("C2b_and_it_carries_the_two_scope_corrections_that_must_travel",
    "sublocus" in LAWMAP and "REFUTED" in LAWMAP and "complete cusped rep" in LAWMAP,
    note="B199's dim-2 sublocus (~1% of irreducible loxodromic reps; the err<1e-6 filter SELECTED "
         "it, so the '305/305 unanimous' was a filter artifact) and B157's refutation of "
         "k = 4-m(o-3). A restoration that drops either restores an overclaim")

R["carried_by_citation"] = {
    "B142 item B (s776 cartography)": "the magic-manifold identification, volumes, symmetry "
                                      "orders and trace fields need SnapPy + PARI, absent here. "
                                      "It is a TOMBSTONE (K-I) plus the guard MB10, not a "
                                      "positive result, and it is not part of the restored law.",
    "the all-n density step": "Zariski-density in SL(2,C) => Sym^{n-1} irreducible for every n is "
                              "the standard theorem; n = 2..5 is computed here, all n is cited.",
    "B154's 'exactly 2 components'": "the primary decomposition of the silver fixed locus is a "
                                     "Sage/Singular result; sympy has groebner but no primary "
                                     "decomposition. The kappa membership identity is checkable "
                                     "here, the component COUNT is not, and is not restored.",
    "B198's exact SL(3) cells": "SL3 o3 -> k=4 and SL3 o4 -> k=3 by Sage/Singular ideal "
                                "membership over Q(zeta_o). Carried; the sandbox has no CAS that "
                                "finishes that Groebner computation -- which was B157's premise.",
    "B141 Item 4 (the SL(3) locus 'entirely reducible')": "a seeded numerical search (60/60, "
                                                          "0 irreducible). It is a CONJECTURE in "
                                                          "its own arc and is restored as one, "
                                                          "not as the law.",
}

R["all_pass"] = all(v["pass"] for v in R["checks"].values())

if __name__ == "__main__":
    (pathlib.Path(__file__).parent / "results.json").write_text(
        json.dumps(R, indent=1, ensure_ascii=False, default=str))
    for k, v in R["checks"].items():
        print(("PASS " if v["pass"] else "FAIL ") + k)
    print("\nALL PASS:", R["all_pass"], "  checks:", len(R["checks"]))
