#!/usr/bin/env python3
"""THE CHIRALITY PROBE ON THE NON-SELF-DUAL FAMILY SECTOR, COMPLETED AND CLOSED BY A THEOREM: on B71's SL(3) components
W1, W2 -- the object's only non-self-dual irreducible three-dimensional local systems -- no point, no central twist and
no cusped cyclic cover M_n (any n) carries net chirality N(V) = h^1(V) - h^1(V*) != 0.

The frame.  m004 is the mapping torus of the once-punctured torus F = <a, b> with monodromy phi: a -> a^2 b, b -> ab
(B71's convention; boundary conjugator w = a, genuine meridian mu = a^-1 t, longitude lambda = [a, b]); M_n is the
mapping torus of phi^n.  For V irreducible on F the Wang sequence gives h^1(M_n; V) = dim ker(Phi^n - 1 | H^1(F; V)),
dim H^1(F; V) = 3, Phi the monodromy's action on the fibre cohomology ((Phi^-1 f)(x) = T^-1 f(phi(x)), T = rho(t));
the three central twists rho_zeta (t -> zeta t) are the three SL(3)-lifts of one PGL(3) bundle representation.

The exact algebra.
  (i)   B71 (P1): on W1, [A, B] = c mu^3; on W2, [A, B] mu^3 = c; c = 1 exactly (checked): lambda = mu^(+-3).  So the
        peripheral pair shares every eigenvector and lambda v = v <=> the mu-eigenvalue of v is a cube root of unity:
        THE CUSP-FIXED LOCUS OF EVERY COVER M_n AND EVERY TWIST IS ONE CURVE K = {mu has an eigenvalue in mu_3}
        (one twist per point puts it at 1; for 3 | n all three twists keep the fixed vector).  Off K, h^0(dM_n; V) =
        h^0(dM_n; V*) = 0 for every n and twist, and B1268's bound gives N = 0 there.
  (ii)  The SL(3, C) character variety of the free group F = <a, b> is generated by the nine traces tr A, tr B, tr AB,
        tr A^-1, tr B^-1, tr A^-1 B, tr A B^-1, tr A^-1 B^-1, tr [A, B] (Lawton 2007), the ninth satisfying a quadratic
        over the first eight whose two roots are tr [A, B] and tr [B, A].  The two characters over a point of the
        eight-trace locus are rho = (A, B) and rho' = (A^T, B^T): all eight traces agree and tr [A^T, B^T] = tr [B, A].
        And (A^T, B^T) = rho*(a^-1), rho*(b^-1): rho' = tau^* rho* is THE DUAL REPRESENTATION PULLED BACK BY THE
        INVERSION tau: a -> a^-1, b -> b^-1 OF THE FIBRE GROUP -- the hyperelliptic involution of the punctured torus,
        which commutes with the monodromy and is the object's period-2 isometry (B1279's swap T, cusp map (+, +),
        half-translation along the longitude), so it lifts to every cyclic cover M_n and fixes t.
  (iii) The two sheets coincide exactly where tr [A, B] = tr [B, A], i.e. tr lambda = tr lambda^-1, i.e. (by (i))
        tr mu^3 = tr mu^-3, i.e. the spectrum of mu^3 is inversion-symmetric, i.e. some eigenvalue of mu^3 is 1: THE
        BRANCH LOCUS OF THE TWO-SHEETED COORDINATES IS EXACTLY K.  (This is also why Newton's method in (p, q) stalls
        with a square-root law on K: (p, q) are not local coordinates there.)
  (iv)  On K, therefore, rho and tau^* rho* have the same character and, being irreducible, are conjugate:
        V = tau^* V*.  Since tau is a homeomorphism of every M_n, h^1(M_n; V) = h^1(M_n; tau^* V*) = h^1(M_n; V*):
        N(M_n; V) = 0 untwisted; for a twist zeta != 1 either 3 does not divide n (no cusp-fixed vector in that twist,
        N = 0 by the bound) or 3 | n, when every element of pi_1(M_n) has t-exponent divisible by 3 and V_zeta, V
        restrict to the same local system on M_n.
  THEOREM.  N(M_n; V) = 0 for every representation on W1 and W2, every central twist and every n >= 1.
  A second, independent structure along K (checked): on Z^1(F; V) = V + V the matrix of Phi^-1 is
  [[T^-1(1 + A), T^-1 A^2], [T^-1, T^-1 A]] and on B^1 = V it is T^-1, hence tr(Phi^-1 | H^1) = 2 tr(mu^-1) and
  det(Phi^-1 | H^1) = det A = 1; on K (twist with mu v = v) Phi^-1 has the eigenvalue 1 (it acts on H^1(dF; V) by
  mu^-1 and H^1(F; V) -> H^1(dF; V) is onto), so eig Phi^-1 = {1, e, 1/e} with e + 1/e = 2 tr mu - 1: the only points
  of K where any eigenvalue is repeated -- the only points where a Jordan asymmetry between V and V* could have made
  N != 0 -- are tr mu = 3/2 (a triple eigenvalue 1) and tr mu = -1/2 (a double eigenvalue -1).  The theorem predicts
  equal Jordan data on V and V* there; the probe finds these points and checks.

The probe.  (a) Validation: the geometric Sym^2 point; Wang vs direct Fox calculus at generic points; eigenvalue
reciprocity; the trace and determinant identities; c = 1.  (b) K sampled (the representation solved directly in
matrix space, where the coordinates are not branched): eig Phi^-1 = {1, e, 1/e}; tr [A, B] = tr [B, A] on K and not
off it; the two sheets over (p, q) collapse to one character on K; N = 0 for all n <= 9 and all twists.  (c) The
finitely many repeated-eigenvalue points (tr mu = tr mu^-1 = 3/2 and -1/2) on W1 and W2, found from many starts with
the generic fibre count as the completeness control; at each: Jordan data on V and V* (singular values printed),
h^0(dM_n), h^1(M_n; V_zeta), h^1(M_n; V_zeta*), N for n <= 9 and all twists, and direct Fox calculus on M_n as the
independent control.  (d) Verdict: max |N| over everything.
"""
from __future__ import annotations
import sys, math, cmath, pathlib, time
import numpy as np
from scipy.optimize import least_squares

ROOT = pathlib.Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))
from frontier.B71_sl3_apoly import peripheral as per   # realize / monodromy / the components W1, W2, V0

I3 = np.eye(3, dtype=complex)
PHI = {'a': ['a', 'a', 'b'], 'b': ['a', 'b']}          # phi: a -> a^2 b, b -> ab


def roots_of_unity(n):
    return [cmath.exp(2j * math.pi * k / n) for k in range(n)]


def phi_power_words(n):
    wa, wb = ['a'], ['b']
    for _ in range(n):
        wa = [c for x in wa for c in PHI[x]]
        wb = [c for x in wb for c in PHI[x]]
    return wa, wb


def cocycle_of_word(rho, f, word):
    val, pref = np.zeros(3, dtype=complex), I3.copy()
    for c in word:
        val = val + pref @ f[c]
        pref = pref @ rho[c]
    return val


def fibre_action(rho, T):
    """Phi^-1 on H^1(F; V) = Z^1/B^1: (3x3 matrix in an orthonormal basis of the complement of B^1, invariance error, rank B^1)."""
    Ti = np.linalg.inv(T)
    cols = []
    for k in range(6):
        v = np.zeros(6, dtype=complex); v[k] = 1
        f = {'a': v[:3], 'b': v[3:]}
        cols.append(np.concatenate([Ti @ cocycle_of_word(rho, f, PHI['a']), Ti @ cocycle_of_word(rho, f, PHI['b'])]))
    Z = np.array(cols).T
    Bmat = np.vstack([rho['a'] - I3, rho['b'] - I3])
    U, s, Vh = np.linalg.svd(Bmat, full_matrices=True)
    rankB = int(np.sum(s > 1e-9 * max(1.0, s[0])))
    Q = U[:, rankB:]
    P = Q.conj().T
    H = P @ Z @ Q
    inv_err = float(np.max(np.abs(P @ Z @ Bmat))) if rankB else 0.0
    return H, inv_err, rankB


def jordan_data(H, target, tol=1e-6, tol_sv=1e-8):
    """(algebraic multiplicity, geometric multiplicity, singular values of H - target) at the eigenvalue `target`.
    am counts eigenvalues within tol of the target (a Jordan block of size k perturbs them by eps^(1/k), so tol is loose);
    gm counts singular values of H - target below tol_sv * max(1, s_0) -- kept TIGHT and separate: for a non-normal H
    (a Jordan block) sigma_min(H - w) can be far smaller than the distance from w to the spectrum, and a loose kernel
    tolerance counts phantom kernel dimensions at roots of unity far from the spectrum (seen once at 1e-3: a Wang count
    of 2 at n = 9 against the direct Fox count of 1)."""
    ev = np.linalg.eigvals(H)
    am = int(np.sum(np.abs(ev - target) < tol))
    s = np.linalg.svd(H - target * np.eye(H.shape[0]), compute_uv=False)
    gm = int(np.sum(s < tol_sv * max(1.0, s[0])))
    return am, gm, s


def dual(rho, T):
    return {'a': np.linalg.inv(rho['a']).T, 'b': np.linalg.inv(rho['b']).T}, np.linalg.inv(T).T


def analyse_point(A, B, T, n_max=9, tol=1e-6):
    rho = {'a': A, 'b': B}
    rhod, Td = dual(rho, T)
    H, e1, rB = fibre_action(rho, T)
    Hd, e2, rBd = fibre_action(rhod, Td)
    mu = np.linalg.inv(A) @ T
    lam = A @ B @ np.linalg.inv(A) @ np.linalg.inv(B)
    out = dict(ev=np.linalg.eigvals(H), evd=np.linalg.eigvals(Hd), inv_err=max(e1, e2), rankB=(rB, rBd), N={}, h1={}, h0={}, H=H, Hd=Hd, mu=mu, lam=lam)
    for zi, zeta in enumerate(roots_of_unity(3)):
        Hz = H / zeta          # t -> zeta t rescales Phi^-1 by 1/zeta
        Hdz = Hd * zeta        # (V_zeta)* = (V*)_{1/zeta}: Phi*^-1 rescales by zeta
        for n in range(1, n_max + 1):
            h1v = sum(jordan_data(Hz, w, tol)[1] for w in roots_of_unity(n))
            h1d = sum(jordan_data(Hdz, w, tol)[1] for w in roots_of_unity(n))
            muz = zeta * mu
            Sm = np.vstack([np.linalg.matrix_power(muz, n) - I3, lam - I3])
            h0 = 3 - np.linalg.matrix_rank(Sm, tol=1e-6)
            Smd = np.vstack([np.linalg.matrix_power(np.linalg.inv(muz).T, n) - I3, np.linalg.inv(lam).T - I3])
            h0d = 3 - np.linalg.matrix_rank(Smd, tol=1e-6)
            out['N'][(zi, n)] = h1v - h1d
            out['h1'][(zi, n)] = (h1v, h1d)
            out['h0'][(zi, n)] = (h0, h0d)
    return out


# ----------------------------------------------------------------------------------------------- direct Fox control
def fox_h1_mapping_torus(rho, T, n):
    """h^1(M_n; V) by Fox calculus on <a, b, s | s a s^-1 = phi^n(a), s b s^-1 = phi^n(b)>, s = t^n (ranks by singular-value gap)."""
    wa, wb = phi_power_words(n)
    S = np.linalg.matrix_power(T, n)
    full = {'a': rho['a'], 'b': rho['b'], 's': S, 'A': np.linalg.inv(rho['a']), 'B': np.linalg.inv(rho['b']), 'S': np.linalg.inv(S)}

    def inv(w):
        return [c.swapcase() for c in reversed(w)]
    rels = [['s', 'a', 'S'] + inv(wa), ['s', 'b', 'S'] + inv(wb)]

    def fox_matrix(word, x):
        M, pref = np.zeros((3, 3), dtype=complex), I3.copy()
        for c in word:
            if c == x:
                M = M + pref
            elif c == x.upper():
                M = M - pref @ full[c]
            pref = pref @ full[c]
        return M
    gens = ['a', 'b', 's']
    d0 = np.vstack([full[g] - I3 for g in gens])
    d1 = np.block([[fox_matrix(r, g) for g in gens] for r in rels])
    assert np.max(np.abs(d1 @ d0)) < 1e-6 * max(1.0, np.linalg.norm(d1)), "d1 d0 != 0"
    s0 = np.linalg.svd(d0, compute_uv=False)
    s1 = np.linalg.svd(d1, compute_uv=False)
    r0 = int(np.sum(s0 > 1e-7 * s0[0]))
    r1 = int(np.sum(s1 > 1e-7 * s1[0]))
    return (9 - r1) - r0


# ----------------------------------------------------------------------------------------------- solving in matrix space
def traces8(A, B):
    Ai, Bi = np.linalg.inv(A), np.linalg.inv(B)
    return np.array([np.trace(A), np.trace(B), np.trace(A @ B), np.trace(Ai), np.trace(Bi), np.trace(Ai @ B), np.trace(A @ Bi), np.trace(Ai @ Bi)])


def unpack(z):
    a1, a2 = z[0], z[1]
    A = np.diag([a1, a2, 1 / (a1 * a2)]).astype(complex)
    B = z[2:11].reshape(3, 3)
    T = z[11:20].reshape(3, 3)
    p, q = z[20], z[21]
    return A, B, T, p, q


def solve_rep(fn, extra, rng, tries=1, x0=None):
    """a bundle representation on the component fn with two extra complex conditions extra(A, B, T, p, q) -> (2,):
    unknowns (a1, a2, B, T, p, q) in C^22; equations: 8 traces, det B = 1, gauge B01 = B12 = 1, T A T^-1 = A^2 B,
    T B T^-1 = A B (18), det T = 1, extra (2) -- least squares (Levenberg-Marquardt)."""
    def resid(v):
        z = v[:22] + 1j * v[22:]
        A, B, T, p, q = unpack(z)
        e = [traces8(A, B) - np.array(fn(p, q), dtype=complex), [np.linalg.det(B) - 1, B[0, 1] - 1, B[1, 2] - 1],
             (T @ A - A @ A @ B @ T).ravel(), (T @ B - A @ B @ T).ravel(), [np.linalg.det(T) - 1], extra(A, B, T, p, q)]
        e = np.concatenate([np.atleast_1d(np.asarray(x, dtype=complex)) for x in e])
        return np.concatenate([e.real, e.imag])
    for _ in range(tries):
        if x0 is None:
            z0 = rng.standard_normal(22) + 1j * rng.standard_normal(22)
            z0[0:2] = np.exp(1j * rng.uniform(0, 2 * math.pi, 2)) * rng.uniform(0.5, 1.5, 2)
        else:
            z0 = x0
        v0 = np.concatenate([z0.real, z0.imag])
        try:
            res = least_squares(resid, v0, method='lm', xtol=1e-15, ftol=1e-15, gtol=1e-15, max_nfev=1500)
        except Exception:
            continue
        r = np.max(np.abs(resid(res.x)))
        if r < 1e-11:
            z = res.x[:22] + 1j * res.x[22:]
            A, B, T, p, q = unpack(z)
            if np.linalg.matrix_rank(np.vstack([A - I3, B - I3]), tol=1e-8) == 3 and abs(p) < 1e3 and abs(q) < 1e3:
                return A, B, T, p, q, r
    return None


def character9(A, B):
    lam = A @ B @ np.linalg.inv(A) @ np.linalg.inv(B)
    return np.concatenate([traces8(A, B), [np.trace(lam)]])


def distinct_characters(fn, p0, q0, rng, n_starts):
    """the distinct fibre characters (nine traces) over the point (p0, q0) of the component, from n_starts random solves."""
    chars = []
    for _ in range(n_starts):
        out = solve_rep(fn, lambda A, B, T, p, q: np.array([p - p0, q - q0]), rng)
        if out is None:
            continue
        A, B, T, p, q, r = out
        c9 = character9(A, B)
        if not any(np.max(np.abs(c9 - c)) < 1e-6 for c in chars):
            chars.append(c9)
    return [c[8] for c in chars]


def collect(fn, extra, rng, n_starts, key=None):
    """distinct solutions (as SL(3) bundle characters: the nine fibre traces and the meridian spectrum) from n_starts random starts."""
    found = []
    for _ in range(n_starts):
        out = solve_rep(fn, extra, rng)
        if out is None:
            continue
        A, B, T, p, q, r = out
        mu = np.linalg.inv(A) @ T
        sig = np.concatenate([character9(A, B), sorted(np.linalg.eigvals(mu), key=lambda z: (round(z.real, 6), round(z.imag, 6)))])
        if any(np.max(np.abs(sig - s1)) < 1e-6 for (s1, *_ ) in found):
            continue
        found.append((sig, A, B, T, p, q, r))
    return found


def main():
    t0 = time.time()
    rng = np.random.default_rng(2026)
    print("=== (a) validation ===")
    zc = (3 + 1j * math.sqrt(3)) / 2
    x_, y_, z_ = np.conj(zc), zc, zc
    lam_ = (x_ + cmath.sqrt(x_ * x_ - 4)) / 2
    a2 = np.array([[lam_, 0], [0, 1 / lam_]], dtype=complex)
    b11 = (z_ - y_ / lam_) / (lam_ - 1 / lam_); b22 = y_ - b11; b12 = 1.0; b21 = (b11 * b22 - 1) / b12
    b2 = np.array([[b11, b12], [b21, b22]], dtype=complex)

    def sym2(g):
        a, b, c, d = g[0, 0], g[0, 1], g[1, 0], g[1, 1]
        return np.array([[a * a, 2 * a * b, b * b], [a * c, a * d + b * c, b * d], [c * c, 2 * c * d, d * d]], dtype=complex)
    A2, B2 = sym2(a2), sym2(b2)
    T2, res, w = per.monodromy(A2, B2, with_conjugator=True)
    geo = analyse_point(A2, B2, T2)
    print(f"  geometric Sym^2 point: eig Phi^-1 {np.round(geo['ev'], 4)}, eig Phi*^-1 {np.round(geo['evd'], 4)}; invariance error {geo['inv_err']:.1e}; "
          f"N(M_n; V_zeta) all zero: {all(v == 0 for v in geo['N'].values())}; h^1(M_n) n = 1..9 (untwisted): {[geo['h1'][(0, n)][0] for n in range(1, 10)]}; "
          f"|tr Phi^-1 - 2 tr mu^-1| = {abs(np.trace(geo['H']) - 2 * np.trace(np.linalg.inv(geo['mu']))):.1e}; |det Phi^-1 - 1| = {abs(np.linalg.det(geo['H']) - 1):.1e}")
    checks, ident = [], []
    for name, fn, sgn in (("W1", per.W1, -3), ("W2", per.W2, 3)):
        k = 0
        while k < 3:
            p, q = complex(*rng.standard_normal(2)), complex(*rng.standard_normal(2))
            out = per.realize(fn(p, q))
            if out is None:
                continue
            A, B = out
            T, res, w = per.monodromy(A, B, with_conjugator=True)
            if T is None or not np.allclose(w, A):
                continue
            d = analyse_point(A, B, T)
            rho = {'a': A, 'b': B}
            for n in (1, 2, 3):
                checks.append((name, n, d['h1'][(0, n)][0], fox_h1_mapping_torus(rho, T, n)))
            recip = np.allclose(sorted(np.round(1 / d['ev'], 6), key=lambda z: (z.real, z.imag)), sorted(np.round(d['evd'], 6), key=lambda z: (z.real, z.imag)))
            S = d['lam'] @ np.linalg.matrix_power(d['mu'], sgn)
            c = np.trace(S) / 3
            lam = d['lam']
            ident.append((name, abs(np.trace(d['H']) - 2 * np.trace(np.linalg.inv(d['mu']))), abs(np.linalg.det(d['H']) - 1), abs(c - 1), np.max(np.abs(S - c * I3)), recip,
                          all(v == 0 for v in d['N'].values()), abs(np.trace(lam) - np.trace(np.linalg.inv(lam))), np.max(np.abs(traces8(A, B) - traces8(A.T, B.T)))))
            k += 1
    print(f"  Wang count vs direct Fox on M_n, n = 1, 2, 3 (component, n, Wang, Fox): {checks}; agree: {all(c[2] == c[3] for c in checks)}")
    for (name, e_tr, e_det, e_c, e_sc, recip, N0, brdiff, tr8) in ident:
        print(f"  {name} generic point: |tr Phi^-1 - 2 tr mu^-1| = {e_tr:.1e}; |det Phi^-1 - 1| = {e_det:.1e}; lambda = mu^(+-3) c: |c - 1| = {e_c:.1e}, non-scalar part {e_sc:.1e}; "
              f"eig Phi*^-1 = 1/eig Phi^-1: {recip}; N = 0 for all (zeta, n <= 9): {N0}; |tr[A,B] - tr[B,A]| = {brdiff:.3f} (off K: the two sheets differ); "
              f"eight traces of (A^T, B^T) equal those of (A, B): {tr8:.1e}")
    ok_a = all(c[2] == c[3] for c in checks) and all(e[1] < 1e-6 and e[2] < 1e-6 and e[3] < 1e-6 and e[4] < 1e-6 and e[5] and e[6] and e[7] > 1e-3 and e[8] < 1e-9 for e in ident)

    print("\n=== (b) the curve K = {mu has an eigenvalue in mu_3} = the branch locus: eig Phi^-1 = {1, e, 1/e}, one character over (p, q), N = 0 ===")
    ok_b = True
    nK = 0
    for name, fn in (("W1", per.W1), ("W2", per.W2)):
        for p0 in (0.4 + 0.3j, -0.7 + 0.9j, 1.3 - 0.5j):
            sols = collect(fn, lambda A, B, T, p, q: np.array([np.linalg.det(np.linalg.inv(A) @ T - I3), p - p0]), rng, 40)
            for (sig, A, B, T, p, q, r) in sols:
                d = analyse_point(A, B, T, tol=1e-5)
                ev = d['ev']
                i1 = int(np.argmin(np.abs(ev - 1)))
                others = [ev[j] for j in range(3) if j != i1]
                e_prod = abs(others[0] * others[1] - 1)
                s_pred = 2 * np.trace(d['mu']) - 1
                lam = d['lam']
                br = abs(np.trace(lam) - np.trace(np.linalg.inv(lam)))
                # the two sheets over (p, q): solve the representation from random starts at fixed (p, q) and count the distinct
                # fibre characters (nine traces) found -- B71's realize() has a fixed seed and always returns one sheet
                ninth = distinct_characters(fn, p, q, rng, 24)
                ok_pt = abs(ev[i1] - 1) < 1e-6 and e_prod < 1e-6 and abs(others[0] + others[1] - s_pred) < 1e-6 and br < 1e-6 and len(ninth) == 1
                N_all = all(v == 0 for v in d['N'].values())
                ok_b = ok_b and ok_pt and N_all
                nK += 1
                print(f"  {name} p={p0:.2f}: K-point q={q:.6f} (residual {r:.1e}): tr mu = {np.trace(d['mu']):.5f}; eig mu {np.round(np.linalg.eigvals(d['mu']), 5)}; eig Phi^-1 = {np.round(ev, 5)} "
                      f"(|e_1 - 1| = {abs(ev[i1] - 1):.1e}, |e e' - 1| = {e_prod:.1e}, |e + e' - (2 tr mu - 1)| = {abs(others[0] + others[1] - s_pred):.1e}); "
                      f"|tr[A,B] - tr[B,A]| = {br:.1e}; distinct characters over (p, q): {len(ninth)}; h^0(dM_1; V), h^0(dM_1; V*) per twist {[d['h0'][(zi, 1)] for zi in range(3)]}; "
                      f"h^1(M_n; V) untwisted n=1..9 {[d['h1'][(0, n)][0] for n in range(1, 10)]}; N = 0 for all (zeta, n): {N_all}")
    # control: off K two characters over (p, q)
    two = []
    for name, fn in (("W1", per.W1), ("W2", per.W2)):
        p, q = complex(*rng.standard_normal(2)), complex(*rng.standard_normal(2))
        ninth = distinct_characters(fn, p, q, rng, 32)
        two.append(len(ninth))
        print(f"  control, {name} at a generic (p, q): distinct characters (values of tr[A,B]) over the point: {len(ninth)} -> {np.round(ninth, 5)}")
    ok_b = ok_b and all(t == 2 for t in two) and nK > 0
    print(f"  K-points checked: {nK}; structure {{1, e, 1/e}}, branch locus, one character, N = 0 at every one, and two characters off K: {ok_b}")

    print("\n=== (c) the repeated-eigenvalue points of K: tr mu = tr mu^-1 = 3/2 (triple eigenvalue 1) and -1/2 (double eigenvalue -1) ===")
    n_starts = 40
    degrees = {}
    for name, fn in (("W1", per.W1), ("W2", per.W2)):
        degs = []
        for trial in range(2):
            s1, s2 = complex(*rng.standard_normal(2)), complex(*rng.standard_normal(2))
            sols = collect(fn, lambda A, B, T, p, q: np.array([np.trace(np.linalg.inv(A) @ T) - s1, np.trace(np.linalg.inv(T) @ A) - s2]), rng, n_starts)
            degs.append(len(sols))
        degrees[name] = degs
        print(f"  {name}: distinct bundle characters with random (tr mu, tr mu^-1) from {n_starts} starts (the generic fibre count, completeness control): {degs}")
    maxN = 0
    results = []
    for name, fn in (("W1", per.W1), ("W2", per.W2)):
        for label, s, tgt in (("A: triple eigenvalue 1", 1.5, 1.0), ("B: double eigenvalue -1", -0.5, -1.0)):
            sols = collect(fn, lambda A, B, T, p, q: np.array([np.trace(np.linalg.inv(A) @ T) - s, np.trace(np.linalg.inv(T) @ A) - s]), rng, n_starts)
            print(f"  {name}, case {label} (tr mu = {s}): {len(sols)} distinct points (fibre count control {degrees[name]})")
            for (sig, A, B, T, p, q, r) in sols:
                d = analyse_point(A, B, T, tol=1e-3)
                rho = {'a': A, 'b': B}
                rhod, Td = dual(rho, T)
                amV, gmV, sV = jordan_data(d['H'], tgt, 1e-3)
                amD, gmD, sD = jordan_data(d['Hd'], tgt, 1e-3)
                fox = [(fox_h1_mapping_torus(rho, T, n), fox_h1_mapping_torus(rhod, Td, n)) for n in range(1, 10)]
                wang = [d['h1'][(0, n)] for n in range(1, 10)]
                Ns = {n: [d['N'][(zi, n)] for zi in range(3)] for n in range(1, 10)}
                mN = max(abs(x) for v in Ns.values() for x in v)
                maxN = max(maxN, mN)
                lam = d['lam']
                results.append((name, label, p, q, r, (amV, gmV), (amD, gmD), wang, fox, Ns))
                print(f"     point p={p:.8f} q={q:.8f} (residual {r:.1e}): eig mu {np.round(np.linalg.eigvals(d['mu']), 6)}; |tr[A,B] - tr[B,A]| = {abs(np.trace(lam) - np.trace(np.linalg.inv(lam))):.1e}; "
                      f"eig Phi^-1 {np.round(d['ev'], 5)}; eig Phi*^-1 {np.round(d['evd'], 5)}")
                print(f"        Jordan data at {tgt:+.0f}: V (am, gm) = {(amV, gmV)}, singular values of Phi^-1 - ({tgt:+.0f}): {np.array2string(sV, precision=2)}; "
                      f"V* (am, gm) = {(amD, gmD)}, singular values {np.array2string(sD, precision=2)}")
                print(f"        h^0(dM_n; V), h^0(dM_n; V*) per twist, n = 1..9: {[[d['h0'][(zi, n)] for zi in range(3)] for n in range(1, 10)]}")
                print(f"        Wang (h^1(M_n; V), h^1(M_n; V*)) untwisted n = 1..9: {wang}; direct Fox: {fox}; agree: {wang == fox}")
                print(f"        N(M_n; V_zeta) per twist, n = 1..9: {Ns}; max |N| at this point: {mN}")
    print(f"\n=== (d) verdict ===  ({time.time() - t0:.0f} s)")
    print(f"  maximum |N(M_n; V_zeta)| over every repeated-eigenvalue point of W1 and W2, every twist and n <= 9: {maxN}")
    return dict(maxN=maxN, results=results, checks=checks, ident=ident, ok_a=ok_a, ok_b=ok_b, degrees=degrees)


if __name__ == "__main__":
    out = main()
    fox_ok = all(r[7] == r[8] for r in out['results'])
    ok = out['ok_a'] and out['ok_b'] and fox_ok and len(out['results']) > 0 and out['maxN'] == 0
    print("\nSELFTEST:", "PASS" if ok else "FAIL", f"(validation {out['ok_a']}, curve K {out['ok_b']}, Wang = Fox at the repeated-eigenvalue points {fox_ok}, points found {len(out['results'])}, max |N| {out['maxN']})")
    sys.exit(0 if ok else 1)
