#!/usr/bin/env python3
"""The structure of Y_12's 768 one-triplet lines (B1302 addendum): the letters' orders, the image subgroup, the deck orbits."""
import sys, math, json, collections, pathlib
import numpy as np
B1301 = pathlib.Path(__file__).resolve().parents[2] / 'B1301_the_towers_alphabet' / 'verification'
sys.path.insert(0, str(B1301))
import lines_from_support as LS
import six_fold_closing as SF
TW = SF.TW
n = 12
L = LS.load_level(B1301 / 'support_Y12.json', n)
K3, K2, dist = LS.alphabet(L)
H, chi = L['H'], L['chi']
# raw tuples <-> coordinates, for the deck action (the shift of the Schreier generators)
d = json.loads((B1301 / 'support_Y12.json').read_text())
gens, rels = TW.presentation(n, branched=True)
Rm = SF.relation_matrix(gens, rels); D, U, V = SF.smith_with_transforms(Rm)
chars, coords, moduli = SF.characters(D, V, d['m'], with_coords=True)
c2a = {tuple(c): a for a, c in zip(chars, coords)}; a2c = {a: tuple(c) for a, c in zip(chars, coords)}
deck = lambda a: (a[0],) + (a[n],) + tuple(a[1:n])
m = d['m']
order_of = lambda a: max([m // math.gcd(x, m) for x in a] + [1])
K = len(K3)
iu, il = np.meshgrid(np.arange(K), np.arange(K), indexing='ij')
u_all, l_all = K3[iu.ravel()], K3[il.ravel()]
G3 = (0, 1, 2)
solved = []
for iq in range(K):
    q = K3[iq][None, :]
    bits = {}
    for lab in LS.LABELS:
        a, b, c = LS.QUL[lab]
        x = a * q + b * u_all + c * l_all
        bits[lab] = np.stack([H[LS.keys(x + chi[g], L)] for g in G3], axis=1)
    tot = {lab: bits[lab].sum(axis=1) for lab in LS.LABELS}
    three = (tot['d^c'] == 3) & (tot['e^c'] == 3)
    ch = lambda A: LS.keys(LS.QUL[A][0] * q + LS.QUL[A][1] * u_all + LS.QUL[A][2] * l_all, L)
    broken = ~((ch('Q') == ch('u^c')) & (ch('u^c') == ch('e^c')))
    vac = (tot['S'] >= 1) & (tot['nu^c'] >= 1) & (tot['H_u'] >= 1) & (tot['H_d'] >= 1)
    sm = three & broken & vac
    one = sm & (tot['D'] == 1) & (tot['Dbar'] == 1) & (tot['S'] == 1)
    # the six solved patterns: D, Dbar, N in three different generations
    for t in np.where(one)[0]:
        gD = int(np.argmax(bits['D'][t])); gDb = int(np.argmax(bits['Dbar'][t])); gN = int(np.argmax(bits['S'][t]))
        if len({gD, gDb, gN}) == 3 and all(tot[lab][t] == 3 for lab in LS.LABELS if lab not in ('D', 'Dbar', 'S')):
            solved.append((tuple(K3[iq]), tuple(u_all[t]), tuple(l_all[t]), (gD, gDb, gN)))
print("solved lines:", len(solved))
ords = collections.Counter((order_of(c2a[s[0]]), order_of(c2a[s[1]]), order_of(c2a[s[2]])) for s in solved)
print("orders of (psi_Q, psi_u, psi_L):", dict(ords))
# the image subgroup generated by the three characters (as raw tuples, addition mod m): its order
def subgroup_order(gs):
    seen = {tuple([0] * len(gs[0]))}; frontier = [tuple([0] * len(gs[0]))]
    while frontier:
        nxt = []
        for x in frontier:
            for g in gs:
                y = tuple((p + q) % m for p, q in zip(x, g))
                if y not in seen:
                    seen.add(y); nxt.append(y)
        frontier = nxt
    return len(seen)
img = collections.Counter(subgroup_order([c2a[s[0]], c2a[s[1]], c2a[s[2]]]) for s in solved)
print("order of the line's image in the character group:", dict(img))
# relations among the three letters: is psi_L a power of psi_Q times a family character, etc.
rel = collections.Counter()
for s in solved:
    aQ, au, aL = c2a[s[0]], c2a[s[1]], c2a[s[2]]
    # express u and L in terms of Q modulo the family group if possible
    fam = [tuple(c) for c in d['chis']] + [tuple([0] * len(aQ))]
    def in_span(x):
        for k in range(16):
            for f in fam:
                if all((k * p + fq - xq) % m == 0 for p, fq, xq in zip(aQ, f, x)):
                    return k
        return None
    rel[(in_span(au), in_span(aL))] += 1
print("psi_u = psi_Q^k x family, psi_L = psi_Q^k' x family -> (k, k') counts:", dict(rel))
# deck orbits of the solved lines (the deck acts on all three characters at once)
S = {(c2a[s[0]], c2a[s[1]], c2a[s[2]]) for s in solved}
orbits = 0; seen = set()
for x in S:
    if x in seen:
        continue
    orbits += 1; y = x
    for _ in range(n):
        seen.add(y); y = tuple(deck(a) for a in y)
        assert y in S, "the deck does not preserve the solved set"
print("deck orbits of the 768 (the deck permutes D, Dbar, N generations as the 3-cycle):", orbits)
# the whole set of 34752 SM lines: deck orbits and the number of orbits meeting the solved set
gen_pat = collections.Counter(s[3] for s in solved)
print("(generation of D, of Dbar, of N) -> lines:", dict(gen_pat))
