#!/usr/bin/env python3
"""B1536 -- route R: a finite cover read on its OWN Reidemeister-Schreier presentation, over GF(p) at primes different from
route N's, with PARI's elimination -- no FLINT.  Nothing is computed on import.

THE PRESENTATION.  The cover is a transitive right action x^g on X (cover_lib), H = Stab(0).  A breadth-first spanning tree
gives coset words rep(x) with 0^rep(x) = x; the Schreier generators are s_{x,g} = rep(x) g rep(x^g)^-1 for the edges (x, g) off
the tree; the relators are every base relator rewritten from every point; rank check d (ngens - 1) + 1.
THE CUSPS are read here from the orbits of <l, t'> (cover_lib.cusps): at the orbit of x with stabiliser lattice basis
(i1, j1), (i2, j2), the cusp group is generated by rep(x) l^i t'^j rep(x)^-1, i.e. the rewrites of l^i t'^j from x.  So this route
uses the cover's own cusps; route N reads them through Mackey on the base.
LINEAR ALGEBRA: every rank and kernel by PARI over GF(p) (cypari; matrank, matker), products and small inverses by numpy
(sm:B1535's rs_lib) -- route N uses FLINT, so the two routes share no elimination code.
THE MODULES on the cover are the base modules evaluated on the Schreier words; the frame's class is a cocycle of the cover:
  - the pulled-back class: the base cocycle c0 (found here, by this route's own elimination) evaluated on the Schreier words;
  - an own class: a cocycle of the cover found here (route R's own kernel), used for the strata (PREREGISTRATION section 3).
Lambda^2 is built through the tensor square (A (x) A on antisymmetric tensors), not through minors as in route N."""
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
_RS = ROOT / "frontier" / "B1535_the_cap" / "verification"
if str(_RS) not in sys.path:
    sys.path.insert(0, str(_RS))
import rs_lib as RS  # noqa: E402  (banked: minv and mmul over GF(p), p < 2^31)

import cover_lib as CL  # noqa: E402

from cypari import pari  # noqa: E402  (PARI's Fp linear algebra: independent of route N's FLINT)
pari.allocatemem(2 * 10 ** 9, silent=True)


def _pm(M, p):
    M = np.asarray(M, dtype=np.int64) % p
    r, c = M.shape
    return pari.matrix(r, c, [int(x) for x in M.ravel()]) * pari.Mod(1, p)


def prank(M, p):
    """rank over GF(p) (PARI's matrank)"""
    M = np.asarray(M)
    if M.size == 0:
        return 0
    return int(pari.matrank(_pm(M, p)))


def pnull(M, p, ncols):
    """a basis of {x : M x = 0} over GF(p), as rows (PARI's matker)"""
    M = np.asarray(M, dtype=np.int64)
    if M.size == 0:
        return np.eye(ncols, dtype=np.int64)
    K = pari.matker(_pm(M, p))
    k = int(pari.matsize(K)[1])
    if k == 0:
        return np.zeros((0, ncols), dtype=np.int64)
    rows = [[int(pari.lift(K[i, j])) for i in range(ncols)] for j in range(k)]
    return np.array(rows, dtype=np.int64)


def mm(A, B, p):
    return RS.mmul(A, B, p)


# ============================================================================================ the presentation of the cover
class PCover:
    def __init__(self, G, perms):
        self.G, self.gens = G, list(G.gens)
        self.P = CL.with_inverses(perms)
        self.d = len(perms[self.gens[0]])
        self.rep = {0: ""}
        self.tree = set()
        order = [0]
        i = 0
        while i < len(order):
            x = order[i]
            i += 1
            for g in self.gens:
                y = self.P[g][x]
                if y not in self.rep:
                    self.rep[y] = self.rep[x] + g
                    self.tree.add((x, g))
                    order.append(y)
                z = self.P["_inv"][g][x]
                if z not in self.rep:
                    self.rep[z] = self.rep[x] + g.upper()
                    self.tree.add((z, g))
                    order.append(z)
        assert len(self.rep) == self.d
        self.sgens = [(x, g) for x in range(self.d) for g in self.gens if (x, g) not in self.tree]
        self.sidx = {s: i for i, s in enumerate(self.sgens)}
        assert len(self.sgens) == self.d * (len(self.gens) - 1) + 1, "Schreier rank"
        self.rels = []
        for x in range(self.d):
            for r in G.rels:
                w, end = self.rewrite(x, r)
                assert end == x
                self.rels.append(w)
        self.cusp_list = CL.cusps(G, perms)
        self.cusps = []
        for cu in self.cusp_list:
            ws = []
            for (i, j) in cu["lattice"]:
                w, end = self.rewrite(cu["x"], CL.periph_word(G, i, j))
                assert end == cu["x"]
                ws.append(w)
            self.cusps.append(tuple(ws))
        # the base words of the Schreier generators
        self.sword = [self.rep[x] + g + CL.inv_word(self.rep[self.P[g][x]]) for (x, g) in self.sgens]

    def rewrite(self, x, w):
        out = []
        for c in w:
            g = c.lower()
            if c.islower():
                if (x, g) not in self.tree:
                    out.append((self.sidx[(x, g)], 1))
                x = self.P[g][x]
            else:
                x = self.P["_inv"][g][x]
                if (x, g) not in self.tree:
                    out.append((self.sidx[(x, g)], -1))
        return out, x


# ============================================================================================ modules on the cover
class CMod:
    """matrices for the Schreier generators (and inverses), dimension e"""

    def __init__(self, mats, p):
        self.p = p
        self.M = [np.asarray(m, dtype=np.int64) % p for m in mats]
        self.e = self.M[0].shape[0]
        self.Mi = [RS.minv(m, p) for m in self.M]

    def word(self, w):
        X = np.eye(self.e, dtype=np.int64)
        for (j, s) in w:
            X = mm(X, self.M[j] if s == 1 else self.Mi[j], self.p)
        return X

    def dual(self):
        return CMod([m.T.copy() for m in self.Mi], self.p)

    def sub(self, idx):
        idx = np.array(idx)
        return CMod([m[np.ix_(idx, idx)] for m in self.M], self.p)


def base_word(mats, w, p):
    """a base word's matrix from the base generators' matrices (dict g -> e x e)"""
    e = next(iter(mats.values())).shape[0]
    X = np.eye(e, dtype=np.int64)
    inv = {}
    for c in w:
        g = c.lower()
        if c.islower():
            X = mm(X, mats[g], p)
        else:
            if g not in inv:
                inv[g] = RS.minv(mats[g], p)
            X = mm(X, inv[g], p)
    return X


def lift(cov, mats, p):
    """the base module (dict g -> matrix) restricted to the cover: one matrix per Schreier generator"""
    return CMod([base_word(mats, w, p) for w in cov.sword], p)


def fox(mod, w, ng):
    """z(w) = sum_j K_j z(s_j) as an e x (ng e) matrix (left cocycles)"""
    p, e = mod.p, mod.e
    out = np.zeros((e, ng * e), dtype=np.int64)
    Pre = np.eye(e, dtype=np.int64)
    for (j, s) in w:
        if s == 1:
            out[:, j * e:(j + 1) * e] = (out[:, j * e:(j + 1) * e] + Pre) % p
            Pre = mm(Pre, mod.M[j], p)
        else:
            Pre = mm(Pre, mod.Mi[j], p)
            out[:, j * e:(j + 1) * e] = (out[:, j * e:(j + 1) * e] - Pre) % p
    return out


class Coh:
    """h0, h1, the joint restriction to every cusp of the cover, r1, n, t0, h1(dN)"""

    def __init__(self, cov, mod, keep=False):
        p, e, ng = mod.p, mod.e, len(cov.sgens)
        F = np.vstack([fox(mod, r, ng) for r in cov.rels])
        for r in cov.rels:
            assert np.array_equal(mod.word(r) % p, np.eye(e, dtype=np.int64)), "a relator is not 1 on the cover"
        Zrows = pnull(F, p, ng * e)
        self.dimZ = Zrows.shape[0]
        Dg = np.vstack([(m - np.eye(e, dtype=np.int64)) % p for m in mod.M])
        self.a0 = e - prank(Dg, p)
        self.h1 = self.dimZ - (e - self.a0)
        Rs, BPs = [], []
        self.t0, self.h1P = 0, 0
        for (w1, w2) in cov.cusps:
            P1, P2 = mod.word(w1), mod.word(w2)
            D1, D2 = (P1 - np.eye(e, dtype=np.int64)) % p, (P2 - np.eye(e, dtype=np.int64)) % p
            rb = prank(np.vstack([D1, D2]), p)
            self.t0 += e - rb
            self.h1P += (2 * e - prank(np.hstack([(-D2) % p, D1]), p)) - rb
            Rs.append(np.vstack([fox(mod, w1, ng), fox(mod, w2, ng)]))
            BPs.append(np.vstack([D1, D2]))
        nc = len(cov.cusps)
        R = np.vstack(Rs)
        BP = np.zeros((2 * e * nc, e * nc), dtype=np.int64)
        for i, b in enumerate(BPs):
            BP[2 * e * i:2 * e * (i + 1), e * i:e * (i + 1)] = b
        rBP = prank(BP, p)
        RZ = mm(R, Zrows.T, p) if self.dimZ else np.zeros((R.shape[0], 0), dtype=np.int64)
        self.r1 = prank(np.hstack([BP, RZ]), p) - rBP
        self.n = self.h1 - self.r1
        if keep:
            self.Zrows, self.Dg, self.R, self.BP = Zrows, Dg, R, BP


# ============================================================================================ the frame on the cover
def wedge2_tensor(A, p):
    """Lambda^2 A through A (x) A on the antisymmetric tensors, in the basis order SUB + QUO of a 5-dim space"""
    n = A.shape[0]
    order = [(i, j) for j in range(4) for i in range(j)] + [(i, 4) for i in range(4)]
    AA = np.kron(A, A) % p
    out = np.zeros((len(order), len(order)), dtype=np.int64)
    for c, (k, l) in enumerate(order):
        col = (AA[:, k * n + l] - AA[:, l * n + k]) % p      # (A (x) A)(e_k (x) e_l - e_l (x) e_k)
        for r, (i, j) in enumerate(order):
            out[r, c] = col[i * n + j]                         # the coefficient of e_i (x) e_j - e_j (x) e_i, i < j
    return out % p


def frame(cov, rho, chi, c_vals, p):
    """W1 = [[V, c L], [0, L]] on the cover's generators with V = chi rho, L = chi^-4 (chi, rho as base data), c_vals[j] the
    class's value on Schreier generator j; returns the four modules with their split"""
    Vb = {g: rho[g] * chi[g] % p for g in rho}
    Lb = {g: np.array([[pow(int(chi[g]), -4 % (p - 1), p)]], dtype=np.int64) for g in rho}
    V = lift(cov, Vb, p)
    L = lift(cov, Lb, p)
    Ws = []
    for j in range(len(cov.sgens)):
        W = np.zeros((5, 5), dtype=np.int64)
        W[:4, :4] = V.M[j]
        W[:4, 4] = (np.array(c_vals[j], dtype=np.int64) * L.M[j][0, 0]) % p
        W[4, 4] = L.M[j][0, 0]
        Ws.append(W)
    E = CMod(Ws, p)
    L2 = CMod([wedge2_tensor(W, p) for W in Ws], p)
    Es = E.dual().sub([4, 0, 1, 2, 3])
    L2s = L2.dual().sub(list(range(6, 10)) + list(range(6)))
    return {"E": (E, list(range(4)), [4]), "E*": (Es, [0], [1, 2, 3, 4]),
            "L2": (L2, list(range(6)), list(range(6, 10))), "L2*": (L2s, [0, 1, 2, 3], [4, 5, 6, 7, 8, 9])}


def reading(cov, rho, chi, c_vals, p, piece_cache=None):
    mods = frame(cov, rho, chi, c_vals, p)
    C = {}
    for nm, (md, sub, quo) in mods.items():
        C[nm] = Coh(cov, md)
        for part, idx in (("S", sub), ("Q", quo)):
            key = (nm, part)
            if piece_cache is not None and key in piece_cache:
                C[nm + "." + part] = piece_cache[key]
            else:
                C[nm + "." + part] = Coh(cov, md.sub(idx))
                if piece_cache is not None:
                    piece_cache[key] = C[nm + "." + part]
    dual = {"E": "E*", "E*": "E", "L2": "L2*", "L2*": "L2"}
    pd = {("E", "S"): ("E*", "Q"), ("E", "Q"): ("E*", "S"), ("L2", "S"): ("L2*", "Q"), ("L2", "Q"): ("L2*", "S")}
    pd.update({v: k for k, v in pd.items()})

    def ident(A, B):
        Iv = A.n - B.n
        return Iv, (Iv == (A.a0 - B.a0) + B.t0 - A.r1 and A.r1 + B.r1 == A.t0 + B.t0 == A.h1P == B.h1P and
                    Iv == B.h1 - A.h1 + 2 * (A.a0 - B.a0) + B.t0 - A.t0)
    I, ok = {}, True
    for nm in mods:
        I[nm], o = ident(C[nm], C[dual[nm]])
        ok = ok and o
    pieces = {}
    for nm in mods:
        pieces[nm] = []
        for part in ("S", "Q"):
            dn, dp = pd[(nm, part)]
            v, o = ident(C[nm + "." + part], C[dn + "." + dp])
            pieces[nm].append(v)
            ok = ok and o
    les = {}
    for nm in mods:
        S_, Q_, X_ = C[nm + ".S"], C[nm + ".Q"], C[nm]
        rk0 = S_.a0 + Q_.a0 - X_.a0
        les[nm] = {"rk d0": rk0, "rk d1": S_.h1 + Q_.h1 - X_.h1 - rk0, "rk d0_P": S_.t0 + Q_.t0 - X_.t0}
    k, nQ2s, nV, nL, b0 = les["L2"]["rk d0_P"], C["L2*.S"].n, C["E.S"].n, C["E.Q"].n, les["E"]["rk d0"]
    checks = {
        "identities (B1297, annihilator, Lemma E) on every module and piece": ok,
        "I(dual) = -I": I["E*"] == -I["E"] and I["L2*"] == -I["L2"],
        "I(S) = I(Q) = 0 for every piece": all(v == [0, 0] for v in pieces.values()),
        "L2: rk d0 = rk d0* = 0": les["L2"]["rk d0"] == 0 and les["L2*"]["rk d0"] == 0,
        "L2: rk d1 = 0": les["L2"]["rk d1"] == 0,
        "L2*: rk d0_P = 0": les["L2*"]["rk d0_P"] == 0,
        "I(L2) = k - rk d1(L2*)": I["L2"] == k - les["L2*"]["rk d1"],
        "k <= rk d1(L2*) <= k + n((VL)*)": k <= les["L2*"]["rk d1"] <= k + nQ2s,
        "W: rk d0(E*) = 0 and rk d0_P(E*) = 0": les["E*"]["rk d0"] == 0 and les["E*"]["rk d0_P"] == 0,
        "W: rk d0_P(E) = k": les["E"]["rk d0_P"] == k,
        "W: rk d1(E) <= n(V)": les["E"]["rk d1"] <= nV,
        "W: rk d1(E*) <= k + n(L)": les["E*"]["rk d1"] <= k + nL,
        "I(E) = -b0 + k + rk d1(E) - rk d1(E*)": I["E"] == -b0 + k + les["E"]["rk d1"] - les["E*"]["rk d1"],
        "cap: -n((VL)*) <= I(L2) <= 0": -nQ2s <= I["L2"] <= 0,
        "cap: I(E) >= -b0 - n(L)": I["E"] >= -b0 - nL,
    }
    return {"I(W)": I["E"], "I(L2W)": I["L2"], "k": k, "b0": b0, "n((VL)*)": nQ2s, "n(V)": nV, "n(L)": nL,
            "rk d1": {nm: les[nm]["rk d1"] for nm in les}, "rk d1(E*) bound": b0 - k + les["E*"]["rk d1"],
            "pieces": pieces, "checks": checks, "all": all(checks.values())}


# ============================================================================================ the base class, by this route
def base_cocycle(G, mats, p):
    """a cocycle of the base module (dict g -> e x e) representing a non-zero class, found with this route's elimination
    (None if h^1 = 0); returns {g: e-vector}"""
    gens = list(G.gens)
    e = next(iter(mats.values())).shape[0]
    inv = {g: RS.minv(mats[g], p) for g in gens}
    rows = []
    for r in G.rels:
        K = {g: np.zeros((e, e), dtype=np.int64) for g in gens}
        Pre = np.eye(e, dtype=np.int64)
        for c in r:
            g = c.lower()
            if c.islower():
                K[g] = (K[g] + Pre) % p
                Pre = mm(Pre, mats[g], p)
            else:
                Pre = mm(Pre, inv[g], p)
                K[g] = (K[g] - Pre) % p
        rows.append(np.hstack([K[g] for g in gens]))
    Z = pnull(np.vstack(rows), p, len(gens) * e)
    Bm = np.vstack([(mats[g] - np.eye(e, dtype=np.int64)) % p for g in gens])     # columns span B^1
    rB = prank(Bm, p)
    for z in Z:
        if prank(np.hstack([Bm, z.reshape(-1, 1)]), p) > rB:
            return {g: z[i * e:(i + 1) * e] for i, g in enumerate(gens)}
    return None


def cocycle_on_words(G, mats, z, words, p):
    """the values of the base cocycle z (dict g -> vector) on base words (left cocycles: z(uv) = z(u) + u z(v))"""
    out = []
    e = next(iter(mats.values())).shape[0]
    inv = {g: RS.minv(mats[g], p) for g in mats}
    for w in words:
        val = np.zeros(e, dtype=np.int64)
        Pre = np.eye(e, dtype=np.int64)
        for c in w:
            g = c.lower()
            if c.islower():
                val = (val + mm(Pre, z[g].reshape(-1, 1), p).ravel()) % p
                Pre = mm(Pre, mats[g], p)
            else:
                Pre = mm(Pre, inv[g], p)
                val = (val - mm(Pre, z[g].reshape(-1, 1), p).ravel()) % p
        out.append(val)
    return out


# ============================================================================================ the supplies and the own classes
def supplies(cov, rho, chi, p):
    gens = list(rho)
    Veta = {g: rho[g] * pow(int(chi[g]), 5, p) % p for g in gens}
    Lb = {g: np.array([[pow(int(chi[g]), -4 % (p - 1), p)]], dtype=np.int64) for g in gens}
    Q = {g: rho[g] * pow(int(chi[g]), -3 % (p - 1), p) % p for g in gens}
    Ce = Coh(cov, lift(cov, Veta, p))
    Cl = Coh(cov, lift(cov, Lb, p))
    Cq = Coh(cov, lift(cov, Q, p).dual())
    return {"h1(V_eta)": Ce.h1, "n(V_eta)": Ce.n, "b0": Cl.a0, "n(L)": Cl.n, "n((VL)*)": Cq.n,
            "capW": Cl.a0 + Cl.n, "capL2": Cq.n}


def strata_readings(cov, rho, chi, p, trivial, rng, draws=2, piece_cache=None, only=None):
    """route R's own classes: cocycles of V_eta on the cover's presentation; strata by the cusps where chi is trivial
    (`trivial`, a list of booleans in cover_lib.cusps order); returns [(S, [reading, ...])]"""
    import itertools
    gens = list(rho)
    Veta = {g: rho[g] * pow(int(chi[g]), 5, p) % p for g in gens}
    mod = lift(cov, Veta, p)
    C = Coh(cov, mod, keep=True)
    Z = C.Zrows % p                     # rows: cocycles (values on the Schreier generators)
    e, ng, nc = 4, len(cov.sgens), len(cov.cusps)
    T = [i for i in range(nc) if trivial[i]]
    out = []
    for size in range(len(T) + 1):
        for S in itertools.combinations(T, size):
            if only is not None and list(S) not in only:
                continue
            kill = [O for O in T if O not in S]
            if kill:
                # z in span(Z) with R_O z = BP_O v_O for O in kill
                RZ = mm(C.R, Z.T, p)                  # (2 e nc) x dimZ
                A = np.zeros((2 * e * len(kill), Z.shape[0] + e * len(kill)), dtype=np.int64)
                for i, O in enumerate(kill):
                    A[2 * e * i:2 * e * (i + 1), :Z.shape[0]] = RZ[2 * e * O:2 * e * (O + 1)]
                    A[2 * e * i:2 * e * (i + 1), Z.shape[0] + e * i:Z.shape[0] + e * (i + 1)] = \
                        (-C.BP[2 * e * O:2 * e * (O + 1), e * O:e * (O + 1)]) % p
                K = pnull(A, p, Z.shape[0] + e * len(kill))
                coeffs = [k[:Z.shape[0]] for k in K]
            else:
                coeffs = [np.eye(Z.shape[0], dtype=np.int64)[i] for i in range(Z.shape[0])]
            coeffs = [c for c in coeffs if np.any(c % p)]
            if not coeffs:
                continue
            reads = []
            for _ in range(draws):
                w = np.zeros(Z.shape[0], dtype=np.int64)
                for c in coeffs:                       # reduce at every step: p < 2^31, products < 2^62
                    w = (w + (rng.randrange(1, p) * (c % p)) % p) % p
                z = mm(w.reshape(1, -1), Z, p).ravel()
                cv = [z[j * e:(j + 1) * e] for j in range(ng)]
                reads.append(reading(cov, rho, chi, cv, p, piece_cache))
            out.append((list(S), reads))
    return out
