"""B212 -- the HYPERBOLIC-trace-field shadow at the discriminant prime (sage-gated; SnapPy/snap via
sage-python). The B210 analogue: golden's holonomy mod (sqrt-3) -> 2T=E6. What is silver's at 2?

COMPUTED (snap.polished_holonomy, m136 = silver):
  - the GENERATORS a,b,c are NOT Z[i]-integral: tr(a) ~ -1.554-0.644i, |tr(a)|^2 ~ 2*sqrt2 -> the
    FULL trace field is bigger than the invariant field Q(i) (it contains sqrt2, i.e. ~ Q(zeta_8)).
  - the SQUARES have traces in Z[i]:  tr(a^2) = +2i,  tr(b^2) = 2,  tr(c^2) = -2i.
    => invariant trace field = Q(i) (B210), generated by traces of squares.
  - ALL square-traces vanish mod (1+i):  2 = -i(1+i)^2 == 0,  2i = (1+i)^2 == 0  (mod (1+i)).
    => in the residue field Z[i]/(1+i) = F2, every square reduces to a TRACE-0 element of SL(2,F2)=S3
       (identity or an involution) -- NO trace-1 (order-3) element survives.  So the prime-2 hyperbolic
       shadow carries NO McKay-exceptional (order-3) structure: DEGENERATE, now COMPUTED at the trace
       level (vs golden's mod-3 reduction, which gives the FULL order-3-rich 2T=E6).
  - BUT the square-MATRICES are not in SL(2,Z[i]): diagonals are Z[i]-integral, off-diagonals lie in
    Q(zeta_8) (e.g. a^2 = [[-1+2i, 1.554-0.644i],[...]]).  So the holonomy is a QUATERNION ORDER over
    Q(i); the literal "image group in SL(2,F2)=S3" needs the quaternion-order reduction, NOT the naive
    matrix reduction.  => the image-GROUP is a NAMED RESIDUAL (needs the integral quaternion model);
    the COMPUTED, banked fact is the trace-degeneration (no order-3 element mod (1+i)).

So B210's "silver = degenerate prime 2 -> S3 (both sides)" is CORRECTED:
  monodromy side  -> R^2L^2 == I mod 2 (TRIVIAL; the S3 is the <R,L> group, shadow_core.py);
  hyperbolic side -> trace-degenerate (square-traces == 0 mod (1+i), no order-3); image-group residual.

Recorded results (from sage-python snap, bits_prec=300):
"""
SILVER_SQUARE_TRACES = {"a^2": "+2i", "b^2": "2", "c^2": "-2i"}   # all == 0 mod (1+i)
SILVER_GEN_TRACES_NONINTEGRAL = {"|tr(a)|^2": "~2*sqrt2 (not in Q(i))"}
GOLDEN_HYP_SHADOW = "m004 mod (sqrt-3) -> SL(2,F3)=2T=E6 (integral, full; B210)"
SILVER_HYP_SHADOW = ("m136 at (1+i): square-traces 2,+-2i all == 0 mod (1+i) -> NO order-3 element "
                     "(degenerate); holonomy is a quaternion order over Q(i) (off-diags in Q(zeta_8)) "
                     "-> image-group NEEDS the integral quaternion model (named residual)")


def _recompute():  # pragma: no cover -- sage-python only
    import snappy
    from snappy import snap
    M = snappy.Manifold('m136')
    G = M.fundamental_group()
    rho = snap.polished_holonomy(M, bits_prec=300)
    print("m136 (silver) holonomy via snap:")
    for g in G.generators():
        Mg = rho(g)
        print(f"  tr({g}) ~ {complex(Mg.trace()):.4f}   tr({g}^2) ~ {complex((Mg*Mg).trace()):.4f}")
    print("=> square-traces in Z[i] (2, +-2i), all == 0 mod (1+i): trace-degenerate, no order-3.")


if __name__ == "__main__":
    try:
        import snappy  # noqa: F401
        _recompute()
    except ImportError:
        print("SnapPy not available (run under sage-python). Recorded:")
        print("  golden:", GOLDEN_HYP_SHADOW)
        print("  silver:", SILVER_HYP_SHADOW)
        print("  silver square-traces:", SILVER_SQUARE_TRACES, "(all == 0 mod (1+i))")
