#!/usr/bin/env python3
"""B1477, POST-SEAL cell (not a sealed prediction; written after the sealed cells returned, and labelled so):
Theorem B's criterion.  A closed geodesic whose holonomy rotates by pi has a purely imaginary SL(2,C) trace on every
lift.  If a mirror f fixes a spin structure s it cannot map such a geodesic to itself (the trace would have to equal its
own conjugate), nor can any odd power of f; so the group generated by f permutes the rotation-pi geodesics of each
length in orbits of even size.  HENCE: an odd number of rotation-pi geodesics at some length  =>  no spin structure is
fixed by any mirror.  Spin-free, isometry-free, read off the unsigned length spectrum.  Sufficient, not necessary."""
import sys, json, math, pathlib, collections, multiprocessing, warnings; warnings.filterwarnings("ignore")
import snappy
HERE = pathlib.Path(__file__).resolve().parent
CUTOFF = 3.0


def one(name):
    try:
        spec = snappy.Manifold(name).length_spectrum(CUTOFF, grouped=False); c = collections.Counter()
        for g in spec:
            L = complex(g["length"])
            if abs(abs(L.imag) - math.pi) < 1e-6: c[round(L.real, 6)] += 1
        return dict(name=name, geodesics=len(spec), rotation_pi=sum(c.values()), odd_lengths=sorted(l for l, n in c.items() if n % 2))
    except Exception as e:
        return dict(name=name, error=repr(e)[:120])


if __name__ == "__main__":
    spin = {json.loads(l)["name"]: json.loads(l) for l in open(HERE / "range_spin.jsonl") if l.strip()}
    status = {}
    for nm, r in spin.items():
        if isinstance(r.get("torsion_real"), int): status[nm] = ("cusped", r["cs_class"], "NONE" if r["torsion_real"] == 0 else "candidates")
    for f in ("zero_witness_cusped.json", "zero_witness_closed.json"):
        if (HERE / f).exists():
            for nm, v in json.load(open(HERE / f)).items():
                if "verdict" in v: status[nm] = (v["kind"], "zero", {"EXISTS": "EXISTS", "NONE-CERTIFIED": "NONE"}.get(v["verdict"], "candidates") if v["verdict"] != "EXISTS" or True else "EXISTS")
    names = sorted(status)
    with multiprocessing.Pool(5) as pool: res = pool.map(one, names, chunksize=4)
    out = {}
    for r in res: r["kind"], r["cs_class"], r["status"] = status[r["name"]]; out[r["name"]] = r
    json.dump(out, open(HERE / "pi_geodesics.json", "w"), indent=1)
    ok = [r for r in out.values() if "error" not in r]
    tab = collections.Counter((r["kind"], r["cs_class"], r["status"], bool(r["odd_lengths"])) for r in ok)
    for k, v in sorted(tab.items()): print("%-7s CS %-8s %-11s odd rotation-pi count: %-5s : %d" % (*k, v))
    viol = [r["name"] for r in ok if r["status"] == "EXISTS" and r["odd_lengths"]]
    print("THEOREM B VIOLATIONS (a witnessed survivor with an odd count):", viol, "| errors:", len(out) - len(ok))
