import sympy as sp
F=sp.Matrix([[1,1],[1,0]])
def blk(TL,TR,BL,BR): return sp.Matrix(sp.BlockMatrix([[TL,TR],[BL,BR]]))
def cplx(M):  # does M have non-real eigenvalues?
    return any(sp.im(sp.N(e))!=0 for e in M.eigenvals())

print("=== does the ROTATION (complex mode) come from the F/F^2 asymmetry? ===")
cases={
 "M* = [[F,F],[F^2,F]] (the object, asymmetric)": blk(F,F,F*F,F),
 "symmetric [[F,F],[F,F]]":                        blk(F,F,F,F),
 "uncoupled [[F,0],[0,F]]":                        blk(F,sp.zeros(2),sp.zeros(2),F),
 "swapped [[F,F^2],[F,F]] (F^2 up instead)":       blk(F,F*F,F,F),
}
for name,Mx in cases.items():
    ev=[sp.N(e,4) for e in Mx.eigenvals()]
    print(f"  {name}")
    print(f"     eigenvalues {ev}  -> complex mode: {cplx(Mx)}")

print("\n=== so the object's breath/rotation is GENERATED by the copy-inequality F vs F^2 ===")
Ms=blk(F,F,F*F,F)
print("  M* complex eigenvalue gamma, |gamma| =", sp.nsimplify(sp.sqrt(sp.Abs([e for e in Ms.eigenvals() if sp.im(sp.N(e))!=0][0])**2)))

print("\n=== the copy balance (a bonus golden ratio) ===")
phi=(1+sp.sqrt(5))/2; sq=sp.sqrt(phi)
wa,wb,wA,wB=phi,sp.Integer(1),phi*sq,sq
c1=sp.simplify(wa+wb); c2=sp.simplify(wA+wB)
print(f"  copy1 {{a,b}} weight = {c1},  copy2 {{A,B}} weight = {c2}")
print(f"  copy1:copy2 = {sp.simplify(c2/c1)}  == sqrt(phi)? {sp.simplify(c2/c1-sq)==0}")
print("  => the two golden copies stand in ratio 1:sqrt(phi) -- the between-copies constant again.")
