"""
Movement XXIV — "don't be so sure": the re-examination that reopened the doors.

After movements XXI-XXIII I closed all three past-the-gate forward doors with a
confident "three walls, world-empty, confirmed from both sides."  The owner said
"don't be so sure."  They were right -- I over-closed all three.  Re-examined:

  * GAPS (I said: density-trapped, NEEDS-SPECIALIST wall).  RE-CHECK, computed:
    the gap-labeling frequency ℤ-module has RANK 4 (FULL) -- a clean structural
    fact, not a wall.  The object is a genuine full-rank-4 quasicrystal; labels are
    dense in [0,1) BECAUSE the rank is 4, which is exactly why single-N numerical
    labeling can't resolve ranks (my margin~1).  The "combination gap" frame
    (rank-2 vs rank-4) is ill-posed here -- every label is rank-4.  B172 resolved
    rank-3 gaps by exact Sturm counting; rank-4 is harder, NOT fundamentally
    walled.  REVISION: a full rank-4 quasicrystal (a finding); specific realized
    gap labels are computable-but-hard, OPEN -- not "NEEDS-SPECIALIST wall".

  * H6 (I said: near-miss, trap-routed, dismiss).  RE-CHECK: the trace-zero
    Dsigma* spectrum {phi,1,-1/phi}(x){1,om,om^2} in Q(√5,√-3)⊇√-15 is FORCED
    (tau^6=1 at every trace-zero point) and INTRINSIC (the Jacobian spectrum).  I
    tarred it with the numerology TRAP (Z/3=3 generations) -- but the FIELD Q(√-3)
    is arithmetic, not numerology.  The honest distinction is cyclotomic (from the
    order-6 symmetry) vs geometric (the figure-eight's hyperbolic √-3 that carries
    volume): as fields equal, as content different.  REVISION: a GENUINE forced
    two-ended arithmetic in the dynamics (both ends + the seam co-occur),
    cyclotomic-level not geometric-level -- I UNDER-read it, not a dismissible miss.

  * SEAM (I said: generic).  RE-CHECK: I computed "√-15 APPEARS in Q(√5,√-3)" --
    trivial (any golden×Eisenstein pair).  The real K025 question -- does the
    object SELECT a seam among the 14 candidate fields non-generically? -- I did
    NOT test.  B493 shows the object DOES select internally.  REVISION: the
    object-SELECTION question is UNTESTED here (needs the B459-468 seam machinery);
    "generic" was the answer to a trivial sub-question, not the verdict.

HONEST STATUS: the three doors are NOT confirmed walls.  Two are OPEN (rank-4 gap
labels; seam selection) and one was UNDER-read (H6 = genuine two-ended dynamics).
The confident "world-empty, confirmed" was over-closure -- the serial-false-killer
pattern, caught again.  The only clean new FACT here is the rank-4 module; the rest
is the retraction of premature certainty.  Firewalled.
"""
import sympy as sp


def gap_label_module_rank():
    """Q-rank of the ℤ-module <1, f_a, f_b, f_A, f_B> generated by the letter frequencies."""
    s = sp.symbols('s')                                   # s = sqrt(phi), min poly s^4 - s^2 - 1
    minpoly = s**4 - s**2 - 1
    phi = s**2
    wa, wb, wA, wB = phi, sp.Integer(1), phi * s, s        # golden-tensor weights
    Z = sp.expand(wa + wb + wA + wB)
    rows = []
    for e in [Z, wa, wb, wA, wB]:
        p = sp.Poly(sp.rem(sp.expand(e), minpoly, s), s)
        rows.append([sp.Rational(p.coeff_monomial(s**k)) for k in range(4)])
    return sp.Matrix(rows).rank()


if __name__ == "__main__":
    r = gap_label_module_rank()
    print(f"gap-labeling frequency module rank = {r}  (4 = full: a genuine rank-4 quasicrystal)")
    print("\nREVISED verdicts (the owner was right; I over-closed):")
    print("  GAPS : full rank-4 quasicrystal (finding); specific labels computable-but-hard, OPEN -- not a wall")
    print("  H6   : genuine FORCED two-ended arithmetic in the dynamics (cyclotomic, not geometric) -- under-read")
    print("  SEAM : object-selection UNTESTED (I answered the trivial 'does √-15 appear' sub-question)")
    print("\n=> the doors are not confirmed walls. Two OPEN, one under-read. Premature certainty retracted.")
