#!/usr/bin/env python3
"""Self-contained exact E6/27 invariant census for OA-C1072/OA-C1073.

Dependencies: Python 3 and SymPy.  Vendored, SHA-locked source files live beside
this certificate.  All ranks are computed over Q by sparse Fraction elimination.
The selected A2^3 is the exact full-rank frame generated by the simple-root
A2 on nodes 1 and 3 (zero-based 0 and 2) and its two orthogonal A2 components.
"""

from collections import defaultdict
from fractions import Fraction as F
from itertools import combinations_with_replacement
from pathlib import Path


HERE = Path(__file__).resolve().parent
TWISTED_SHA256 = "4a0fb415c7681e052681ab4c1a703d666751776d8fb883edf5ccda44a5cfeba6"
CCB_SHA256 = "5facb27879bd0ea76c7378f6432867be9019a9e6a4ba796e34040d31bb51f9f2"


def sha256(path):
    import hashlib
    return hashlib.sha256(path.read_bytes()).hexdigest()


twisted = HERE / "twisted_double.py"
ccb = HERE / "paper" / "verify" / "check_charge_bracket.py"
assert sha256(twisted) == TWISTED_SHA256
assert sha256(ccb) == CCB_SHA256

# Execute only stages 0--3 of the locked source: exact E6 plus the verified 27.
source = twisted.read_text(encoding="utf-8")
cut = source.index("# ---------------- stage 4")
ns = {"__file__": str(twisted), "__name__": "locked_twisted_prefix"}
exec(compile(source[:cut], str(twisted), "exec"), ns)

N = ns["N"]
DIM = ns["DIM"]
ROOTS = ns["ROOTS"]
rho27_Q = ns["rho27_Q"]
evec = ns["evec"]

CART = (
    (2, 0, -1, 0, 0, 0),
    (0, 2, 0, -1, 0, 0),
    (-1, 0, 2, -1, 0, 0),
    (0, -1, -1, 2, -1, 0),
    (0, 0, 0, -1, 2, -1),
    (0, 0, 0, 0, -1, 2),
)

# Cartan weights of the verified crystal basis.
cartans = []
for i in range(N):
    h = [F(0)] * DIM
    h[i] = F(1)
    cartans.append(rho27_Q(h))
weights = [tuple(cartans[i][a][a] for i in range(N)) for a in range(27)]
zero = (F(0),) * N


def weight_sum(indices):
    return tuple(sum(weights[i][h] for i in indices) for h in range(N))


def sparse_rank(rows):
    """Exact row rank over Q; every retained pivot row is normalized."""
    pivots = {}
    for original in rows:
        row = {int(k): F(v) for k, v in original.items() if v}
        while row:
            pivot = min(row)
            if pivot not in pivots:
                scale = row[pivot]
                row = {k: v / scale for k, v in row.items() if v}
                pivots[pivot] = row
                break
            scale = row[pivot]
            known = pivots[pivot]
            for k, value in known.items():
                new = row.get(k, F(0)) - scale * value
                if new:
                    row[k] = new
                elif k in row:
                    del row[k]
    return len(pivots)


# Root actions: source basis index -> (target basis index, rational coefficient).
root_actions = {}
for root in ROOTS:
    matrix = rho27_Q(evec(root))
    action = {}
    for source_index in range(27):
        hits = [(target, matrix[target][source_index]) for target in range(27)
                if matrix[target][source_index]]
        assert len(hits) <= 1
        if hits:
            action[source_index] = hits[0]
    root_actions[root] = action


def symmetric_basis(degree):
    return [indices for indices in combinations_with_replacement(range(27), degree)
            if weight_sum(indices) == zero]


def symmetric_equations(monomials, roots):
    """Derivation equations for symmetric covariant degree-three tensors."""
    assert monomials and len(monomials[0]) == 3
    position = {monomial: i for i, monomial in enumerate(monomials)}
    rows = {}
    for root in roots:
        action = root_actions[root]
        # Dual-action equations, indexed by target-weight triples.
        for monomial in monomials:
            column = position[monomial]
            counts = {i: monomial.count(i) for i in set(monomial)}
            for source, (target, coefficient) in action.items():
                if target not in counts:
                    continue
                out = list(monomial)
                out.remove(target)
                out.append(source)
                out = tuple(sorted(out))
                key = (root, out)
                row = rows.setdefault(key, {})
                row[column] = row.get(column, F(0)) - counts[target] * coefficient
    return list(rows.values())


def ordered_equations(basis, roots):
    position = {triple: i for i, triple in enumerate(basis)}
    rows = {}
    for root in roots:
        action = root_actions[root]
        for triple, column in position.items():
            for slot in range(3):
                source = triple[slot]
                if source not in action:
                    continue
                target, coefficient = action[source]
                out = list(triple)
                out[slot] = target
                key = (root, tuple(out))
                row = rows.setdefault(key, {})
                row[column] = row.get(column, F(0)) + coefficient
    return list(rows.values())


def inner(left, right):
    return sum(left[i] * CART[i][j] * right[j]
               for i in range(N) for j in range(N))


def selected_a2_cubed():
    a0 = (1, 0, 0, 0, 0, 0)
    a2 = (0, 0, 1, 0, 0, 0)
    span = {tuple(c * a0[k] + d * a2[k] for k in range(N))
            for c in (-1, 0, 1) for d in (-1, 0, 1)}
    first = {root for root in ROOTS if root in span}
    left = {root for root in ROOTS if inner(root, a0) == inner(root, a2) == 0}
    components = []
    while left:
        component = {min(left)}
        changed = True
        while changed:
            changed = False
            for root in sorted(left - component):
                if any(inner(root, member) != 0 for member in component):
                    component.add(root)
                    changed = True
        left -= component
        components.append(component)
    assert len(first) == 6 and sorted(map(len, components)) == [6, 6]
    selected = tuple(sorted(first | components[0] | components[1]))
    assert len(selected) == 18
    return selected


degrees = {degree: symmetric_basis(degree) for degree in range(1, 5)}
zero_counts = {degree: len(basis) for degree, basis in degrees.items()}
assert zero_counts == {1: 0, 2: 0, 3: 45, 4: 0}

full_sym_rows = symmetric_equations(degrees[3], ROOTS)
full_sym_rank = sparse_rank(full_sym_rows)
assert full_sym_rank == 44

selected_roots = selected_a2_cubed()
selected_sym_rows = symmetric_equations(degrees[3], selected_roots)
selected_sym_rank = sparse_rank(selected_sym_rows)
assert selected_sym_rank == 41

ordered_basis = [(i, j, k) for i in range(27) for j in range(27) for k in range(27)
                 if weight_sum((i, j, k)) == zero]
assert len(ordered_basis) == 270
full_ordered_rank = sparse_rank(ordered_equations(ordered_basis, ROOTS))
selected_ordered_rank = sparse_rank(ordered_equations(ordered_basis, selected_roots))
assert full_ordered_rank == 269
assert selected_ordered_rank == 261

print("SELF-CONTAINED E6/27 INVARIANT CENSUS: PASS")
print("symmetric zero-weight monomials d=1,2,3,4:",
      tuple(zero_counts[d] for d in range(1, 5)))
print("symmetric invariant multiplicities d=1,2,3,4: (0, 0, 1, 0)")
print("full E6 ordered tensor cube: basis=270 rank=269 invariants=1")
print("selected A2^3 ordered tensor cube: basis=270 rank=261 invariants=9")
print("selected A2^3 symmetric cube: basis=45 rank=41 invariants=4")
print("scope: exact fixed-representation algebra; no physical Yukawa or value")
