#!/usr/bin/env python3
"""C3 (HANDOFF to the banking seat's i9/64GB): the Kashaev/Ohtsuki asymptotic
ladder for 4_1 at large N and high precision — c1 to >=60 digits, c2 first
recognition.  (C-V2/C-D4's named continuation; the current c1 match is banked
PROVISIONAL at ~30 digits.)

<4_1>_N = sum_{k=0}^{N-1} prod_{j=1}^{k} |1 - zeta_N^j|^2,  zeta_N = e^{2 pi i/N}
        ~ N^{3/2} exp(N Vol/(2 pi)) * c0 * (1 + c1/N + c2/N^2 + ...),
Vol = 2.029883212819...  (the fig-8 volume, computed here from the Lobachevsky
function, not pasted).

PREREGISTERED: c1, c2 are recognized by PSLQ in the ring generated by
{1, pi, 1/pi, sqrt(3), Vol} over Q (the trace-field/volume frame the corpus's
deflation run uses) with integer relation coefficients of height < 10^12 at
100-digit working precision — or NOT RECOGNIZED is banked as the honest
outcome.  IMPORTANT at integration time: align the expansion convention with
the banked DEFLATION_RUN / ASYMPTOTIC_CHANNEL memos before comparing constants.

Run:  python3 c3_ohtsuki_large.py            (~hours; dps and N-ladder below)
Checkpoints in c3_ladder.txt (N, value at full precision), resume-safe.
"""
import os
from mpmath import mp, mpf, mpc, exp, pi, sqrt, log, clsin, pslq

mp.dps = 120
NS = list(range(400, 4001, 200))          # the N-ladder
Vol = 2*clsin(2, pi/3)                    # 2 Lob(pi/6)? fig-8: Vol = 2 * Cl2(pi/3)
print(f"Vol(4_1) = 2 Cl2(pi/3) = {Vol}")

done = {}
if os.path.exists('c3_ladder.txt'):
    for line in open('c3_ladder.txt'):
        n_, v_ = line.split(':'); done[int(n_)] = mpf(v_)

def kashaev(N):
    z = exp(2j*pi/N) if False else None
    # exact-structured float: |1 - zeta^j|^2 = 4 sin^2(pi j / N)
    from mpmath import sin
    total = mpf(0); prod = mpf(1)
    for k in range(N):
        if k > 0:
            sj = 2*sin(pi*k/N)
            prod *= sj*sj
        total += prod
    return total

for N in NS:
    if N in done: continue
    v = kashaev(N)
    done[N] = v
    open('c3_ladder.txt', 'a').write(f"{N}:{v}\n")
    print(f"  N={N}: <4_1>_N computed ({mp.dps} dps)", flush=True)

# strip the leading asymptotics and fit the 1/N series by Richardson-style solves
xs = sorted(done)
def reduced(N):
    return done[N] / (mpf(N)**mpf(1.5) * exp(N*Vol/(2*pi)))
rs = {N: reduced(N) for N in xs}
# c0 = limit; use the tail of the ladder with polynomial fit in 1/N of degree D
D = 6
tail = xs[-(D+2):]
import itertools
# solve Vandermonde: r(N) = sum_{i=0..D} a_i / N^i
A = [[mpf(1)/mpf(N)**i for i in range(D+1)] for N in tail[:D+1]]
b = [rs[N] for N in tail[:D+1]]
from mpmath import lu_solve, matrix
sol = lu_solve(matrix(A), matrix(b))
c0, c1c0, c2c0 = sol[0], sol[1], sol[2]
c1 = c1c0/c0; c2 = c2c0/c0
print(f"\nc0 = {c0}")
print(f"c0 * 3^(1/4) = {c0 * mpf(3)**mpf('0.25')}   (known: c0 = 3^(-1/4) => this is 1)")
print(f"c1 = {c1}")
print(f"c2 = {c2}")

# stability gate: repeat with the ladder shifted by one rung; digits that agree are trusted
A2 = [[mpf(1)/mpf(N)**i for i in range(D+1)] for N in tail[1:D+2]]
b2 = [rs[N] for N in tail[1:D+2]]
sol2 = lu_solve(matrix(A2), matrix(b2))
c1b = sol2[1]/sol2[0]; c2b = sol2[2]/sol2[0]
agree1 = -log(abs(c1 - c1b) + mpf(10)**(-mp.dps), 10)
agree2 = -log(abs(c2 - c2b) + mpf(10)**(-mp.dps), 10)
print(f"stable digits: c1 ~ {float(agree1):.0f}, c2 ~ {float(agree2):.0f}  (gate: >= 60 for recognition)")

# PSLQ recognition in the preregistered frame
basis_names = ['1', 'pi', '1/pi', 'sqrt3', 'Vol', 'Vol/pi', 'pi*sqrt3', 'sqrt3/pi', 'Vol*sqrt3', 'pi^2', '1/pi^2']
basis = [mpf(1), pi, 1/pi, sqrt(mpf(3)), Vol, Vol/pi, pi*sqrt(mpf(3)), sqrt(mpf(3))/pi, Vol*sqrt(mpf(3)), pi**2, 1/pi**2]
for name, val in (('c1', c1), ('c2', c2)):
    rel = pslq([val] + basis, maxcoeff=10**12, maxsteps=10**6)
    print(f"PSLQ({name}): {rel}")
    if rel and rel[0] != 0:
        expr = " + ".join(f"({-r}/{rel[0]})*{n}" for r, n in zip(rel[1:], basis_names) if r != 0)
        print(f"   => {name} = {expr}")
    else:
        print(f"   => {name}: NOT RECOGNIZED in the preregistered frame (bank honestly)")
