#!/usr/bin/env python3
"""A COLORED JONES CALCULATOR, DERIVED AND VALIDATED -- built because arXiv is egress-blocked.

Memo 177 addenda 4/6/7 leave one thing that would settle the open questions: F_K for a CHIRAL
knot whose blocks widen.  The paper supplies A-hat recursions only for the trefoil and the
figure-eight, and Park arXiv:2004.02087 (which reportedly gives F_K for 5_2 and all twist knots)
cannot be fetched from this container.  So the colored Jones is computed here from scratch.

WHAT IS DERIVED RATHER THAN RECALLED.  The braiding on V_N (x) V_N is not transcribed from a
formula.  It is built by decomposing the tensor square into U_q(sl2) summands -- highest-weight
vectors killed by Delta(E) = E(x)1 + K(x)E, then generated by Delta(F) = F(x)K^-1 + 1(x)F -- and
assigning each summand the ribbon eigenvalue  (-1)^J q^{C_J - 2 C_j},  C = j(j+1).

A first attempt DID transcribe the universal R-matrix from memory and was wrong: its coefficient
(q - q^-1)^n / [n]! is not a Laurent polynomial, which showed up as a non-terminating exact
division.  A second attempt had the ribbon exponent halved, which showed up as non-Laurent matrix
entries and a failing braid relation.  Both were caught by the controls below, not by inspection.

CONTROLS (all must fire; the tool reports nothing if any fails):
  C1  braid relation R1R2R1 = R2R1R2 on three strands, and R.R^-1 = id      (N = 2,3,4)
  C2  every matrix entry is a Laurent polynomial                            (N = 2,3,4)
  C3  the unknot's quantum trace is exactly [N]                             (N = 2,3)
  C4  the right trefoil reproduces Habiro's cyclotomic expansion            (N = 2,3,4)
  C5  the figure-eight reproduces Gukov-Manolescu eq (166)                  (N = 2,3,4)
  C6  after framing normalisation, J_n(1) = 1 and the hbar^1 term vanishes,
      and the hbar^2 term is  +(n^2-1) for 4_1 and -(n^2-1) for 3_1 --
      which is GM eq (168)'s own printed line for the figure-eight.

Conventions fixed BY the controls, not assumed: the invariant equals the standard normalised
colored Jones with q_standard = u^8, where u is this file's variable.

Gate 5: exact arithmetic over Q(u).  No measured input anywhere.
"""

from fractions import Fraction as Fr
# Laurent in u, q = u^4
def add(a,b):
    r=dict(a)
    for e,c in b.items():
        r[e]=r.get(e,0)+c
        if r[e]==0: del r[e]
    return r
def mul(a,b):
    r={}
    for e1,c1 in a.items():
        for e2,c2 in b.items():
            k=e1+e2; r[k]=r.get(k,0)+c1*c2
    return {e:c for e,c in r.items() if c}
def neg(a): return {e:-c for e,c in a.items()}
def mono(e,c=1): return {e:Fr(c)} if c else {}
ONE=mono(0)
def scal(a,k): 
    k=Fr(k); return {e:c*k for e,c in a.items() if c*k}
def qpow(m):   # q^m = u^{4m}, m may be a Fraction with denominator dividing 4
    e=Fr(m)*4
    assert e.denominator==1, e
    return mono(int(e))
def qint(m):   # [m] = (q^m - q^-m)/(q - q^-1)
    if m==0: return {}
    sg=1 if m>0 else -1; m=abs(m); r={}
    for k in range(m): r[4*(m-1-2*k)]=r.get(4*(m-1-2*k),0)+sg
    return {e:Fr(c) for e,c in r.items() if c}

def rep(N):
    """E,F,K on V_N: F v_i = v_{i+1}; E v_i = [i][N-i] v_{i-1}; K v_i = q^{N-1-2i} v_i"""
    w=[N-1-2*i for i in range(N)]
    E=[mul(qint(i),qint(N-i)) for i in range(N)]   # E v_i = E[i] v_{i-1}
    return w,E

def tensor_ops(N):
    w,E=rep(N)
    def dE(vec):   # Delta(E) = E (x) 1 + K (x) E
        out={}
        for (i,j),c in vec.items():
            if i>0:
                out[(i-1,j)]=add(out.get((i-1,j),{}), mul(c,E[i]))
            if j>0:
                out[(i,j-1)]=add(out.get((i,j-1),{}), mul(mul(c,qpow(w[i])),E[j]))
        return {k:v for k,v in out.items() if v}
    def dF(vec):   # Delta(F) = F (x) K^{-1} + 1 (x) F
        out={}
        for (i,j),c in vec.items():
            if i<N-1:
                out[(i+1,j)]=add(out.get((i+1,j),{}), mul(c,qpow(-w[j])))
            if j<N-1:
                out[(i,j+1)]=add(out.get((i,j+1),{}), c)
        return {k:v for k,v in out.items() if v}
    return w,dE,dF

def solve_null(rows, ncols):
    """exact nullspace over the fraction field Q(u): rows are lists of Laurent dicts."""
    import sympy as sp
    U=sp.symbols('U')
    def tosp(d): return sum(sp.Rational(c)*U**e for e,c in d.items()) if d else sp.Integer(0)
    M=sp.Matrix([[tosp(x) for x in r] for r in rows]) if rows else sp.zeros(0,ncols)
    return M.nullspace()

def braiding(N):
    """returns dict (i,j) -> {(k,l): Laurent}, the braiding Rcheck, and its inverse"""
    import sympy as sp
    U=sp.symbols('U')
    w,dE,dF=tensor_ops(N)
    basis=[(i,j) for i in range(N) for j in range(N)]
    # weight of (i,j) is w_i + w_j
    Rmat={}
    j_half=Fr(N-1,2)
    Cj=j_half*(j_half+1)
    for J in range(N):                      # summand spin  jj = (N-1) - J
        jj=Fr(N-1-J)
        wt=int(2*jj)
        # highest weight vectors of weight wt killed by dE
        idx=[b for b in basis if w[b[0]]+w[b[1]]==wt]
        if not idx: continue
        tgt=sorted({(i-1,j) for (i,j) in idx if i>0} | {(i,j-1) for (i,j) in idx if j>0})
        rows=[]
        for t in tgt:
            row=[]
            for b in idx:
                v=dE({b:ONE})
                row.append(v.get(t,{}))
            rows.append(row)
        ns=solve_null(rows, len(idx))
        assert len(ns)==1, (N,J,len(ns))
        vec={}
        for a,b in enumerate(idx):
            ex=sp.cancel(sp.together(ns[0][a]))
            if ex!=0: vec[b]=ex
        # generate the summand by dF
        def sp_apply(v):
            out={}
            for (i,jx),c in v.items():
                if i<N-1:
                    k=(i+1,jx); e=-w[jx]
                    out[k]=sp.expand(out.get(k,0)+c*U**(4*e))
                if jx<N-1:
                    k=(i,jx+1)
                    out[k]=sp.expand(out.get(k,0)+c)
            return {k:sp.cancel(v2) for k,v2 in out.items() if sp.simplify(v2)!=0}
        vecs=[vec]
        cur=vec
        for _ in range(int(2*jj)):
            cur=sp_apply(cur)
            if not cur: break
            vecs.append(cur)
        # ribbon eigenvalue on this summand
        CJ=jj*(jj+1)
        lam_exp=Fr(CJ,1)/2 - Cj
        sign=(-1)**int(2*j_half-2*jj) if float(2*j_half-2*jj)==int(2*j_half-2*jj) else 1
        Rmat[J]=(vecs, sign, lam_exp)
    return Rmat

def Rcheck(N):
    """matrix of the braiding in the (i,j) basis, entries as sympy expressions in U"""
    import sympy as sp
    U=sp.symbols('U')
    w,dE,dF=tensor_ops(N)
    R=braiding(N)
    j_half=Fr(N-1,2); Cj=j_half*(j_half+1)
    # collect (vector, eigenvalue) with correct sign (-1)^J
    pieces=[]
    for J,(vecs,_sg,_le) in R.items():
        jj=Fr(N-1-J); CJ=jj*(jj+1)
        e=CJ-2*Cj                          # exponent of q (ribbon: theta_J/theta_j^2)
        lam=sp.Integer((-1)**J)*U**(int(e*4))
        for v in vecs: pieces.append((v,lam))
    basis=[(i,j) for i in range(N) for j in range(N)]
    wt={b: w[b[0]]+w[b[1]] for b in basis}
    M={}
    for W in sorted(set(wt.values())):
        idx=[b for b in basis if wt[b]==W]
        cols=[(v,l) for (v,l) in pieces if v and wt[next(iter(v))]==W]
        assert len(cols)==len(idx), (N,W,len(cols),len(idx))
        A=sp.Matrix([[sp.expand(c[0].get(b,0)) for c in cols] for b in idx])
        Ai=A.inv()
        D=sp.diag(*[c[1] for c in cols])
        B=sp.simplify(A*D*Ai)
        for a,ba in enumerate(idx):
            for b,bb in enumerate(idx):
                ex=sp.cancel(sp.simplify(B[a,b]))
                if ex!=0: M[(bb,ba)]=ex      # Rcheck(bb) has component ex on ba
    return M

def to_dict(ex):
    import sympy as sp
    U=sp.symbols('U')
    ex=sp.cancel(sp.together(sp.expand(ex)))
    num,den=sp.fraction(ex)
    num=sp.expand(num); den=sp.expand(den)
    dp=sp.Poly(den,U)
    assert len(dp.monoms())==1, ('denominator not a monomial', den)
    shift=int(sp.degree(den,U)); lead=dp.coeffs()[0]
    np_=sp.Poly(sp.expand(num/lead),U)
    d={}
    for (e,),c in np_.terms():
        r=sp.Rational(c)
        d[int(e)-shift]=Fr(int(r.p),int(r.q))
    return {e:c for e,c in d.items() if c}

def Rdicts(N):
    import sympy as sp
    M=Rcheck(N)
    Rp={}
    for (src,tgt),ex in M.items():
        Rp.setdefault(src,{})[tgt]=to_dict(ex)
    U=sp.symbols('U')
    w,dE,dF=tensor_ops(N)
    R=braiding(N)
    j_half=Fr(N-1,2); Cj=j_half*(j_half+1)
    pieces=[]
    for J,(vecs,_s,_l) in R.items():
        jj=Fr(N-1-J); CJ=jj*(jj+1); e=CJ-2*Cj
        lam=sp.Integer((-1)**J)*U**(int(e*4))
        for v in vecs: pieces.append((v, 1/lam))
    basis=[(i,j) for i in range(N) for j in range(N)]
    wt={b: w[b[0]]+w[b[1]] for b in basis}
    Rm={}
    for W in sorted(set(wt.values())):
        idx=[b for b in basis if wt[b]==W]
        cols=[(v,l) for (v,l) in pieces if v and wt[next(iter(v))]==W]
        A=sp.Matrix([[sp.expand(c[0].get(b,0)) for c in cols] for b in idx]); Ai=A.inv()
        D=sp.diag(*[c[1] for c in cols]); B=sp.simplify(A*D*Ai)
        for a,ba in enumerate(idx):
            for b,bb in enumerate(idx):
                ex=sp.cancel(sp.simplify(B[a,b]))
                if ex!=0: Rm.setdefault(bb,{})[ba]=to_dict(ex)
    return Rp,Rm
