#!/usr/bin/env python3
"""IS IT RIGHT, JORGENSEN? -- the attribution and the uniqueness, checked.

Owner: "make sure its right jorgensen".

Memo 225 relayed B1345's paraphrase of Callahan and drew an axiom conclusion from
it.  This certificate does two things the previous one did not:

  (1) pins the PRECISE statement, and finds the paraphrase drops a hypothesis;
  (2) TESTS the uniqueness computationally over the orientable cusped census
      instead of only citing it.

The Jorgensen number of a two-generator subgroup G < PSL(2,C):
      J(G) = inf { |tr^2 A - 4| + |tr[A,B] - 2|  :  G = <A,B> }.
Every pair in the search below is reached from (a, b) by NIELSEN MOVES, so it
PROVABLY generates the same group and each value is a genuine UPPER BOUND on J.
"""

from __future__ import annotations

import sys
import warnings

warnings.filterwarnings("ignore")

import numpy as np
import snappy

FAILURES: list[str] = []


def fail(tag: str, msg: str) -> None:
    FAILURES.append(f"{tag}: {msg}")
    print(f"  !! FAIL [{tag}] {msg}")


def rule(t: str) -> None:
    print("\n" + "-" * 78)
    print(t)
    print("-" * 78)


def mat(G, w):
    m = G.SL2C(w)
    return np.array([[complex(m[i, j]) for j in range(2)] for i in range(2)])


def jq(X, Y):
    t = np.trace(X)
    C = X @ Y @ np.linalg.inv(X) @ np.linalg.inv(Y)
    return abs(t * t - 4) + abs(np.trace(C) - 2)


def nielsen_min(A, B, depth):
    """Minimise the Jorgensen quantity over pairs reached from (A,B) by Nielsen
    moves.  Every such pair generates the SAME group, so every value is a valid
    upper bound on J.  Returns (min value, number of distinct pairs seen)."""
    seen, frontier = {}, [(A, B)]
    best = jq(A, B)
    for _ in range(depth):
        nxt = []
        for X, Y in frontier:
            Xi, Yi = np.linalg.inv(X), np.linalg.inv(Y)
            for P, Q in ((Y, X), (Xi, Y), (X, Yi), (X @ Y, Y), (X, X @ Y),
                         (Y @ X, Y), (X, Y @ X)):
                key = (round(np.trace(P).real, 7), round(np.trace(P).imag, 7),
                       round(np.trace(Q).real, 7), round(np.trace(Q).imag, 7),
                       round(np.trace(P @ Q).real, 7), round(np.trace(P @ Q).imag, 7))
                if key in seen:
                    continue
                seen[key] = 1
                v = jq(P, Q)
                if np.isfinite(v) and v < best:
                    best = v
                nxt.append((P, Q))
        frontier = nxt
        if len(seen) > 20000:
            break
    return best, len(seen)


def main() -> int:
    print("=" * 78)
    print(" IS IT RIGHT, JORGENSEN? -- the attribution and the uniqueness, checked")
    print("=" * 78)

    # ---------------------------------------------------------------- the statement
    rule("PART 1 -- the PRECISE statement, and what the paraphrase dropped")
    print("""
    Definition (standard).  A JORGENSEN GROUP is a non-elementary Kleinian group
    THAT CAN BE GENERATED BY TWO ELEMENTS for which EQUALITY holds in Jorgensen's
    inequality.  The Jorgensen number is defined for a TWO-GENERATOR subgroup:

        J(G) = inf { |tr^2 A - 4| + |tr[A,B] - 2|  :  G = <A,B> },
        and J(G) >= 1 for every non-elementary Kleinian G   [Jorgensen 1976].

    Callahan (2009), as the literature states it:
        "THE ONLY TORSION-FREE JORGENSEN GROUP IS THE FIGURE-EIGHT KNOT GROUP."

    B1345 paraphrases this as "the only ORIENTABLE hyperbolic 3-MANIFOLD with
    J = 1 is the figure-eight complement", and memo 225 relayed that paraphrase.

    WHAT THE PARAPHRASE DROPS, and it is the load-bearing hypothesis:
      * "TWO-GENERATOR" is part of the DEFINITION of a Jorgensen group.  A
        manifold whose group needs three generators has no Jorgensen number in
        this sense at all -- it is not in the theorem's domain.
      * "ORIENTABLE" is not an added hypothesis: a KLEINIAN group already sits in
        PSL(2,C), which acts by ORIENTATION-PRESERVING isometries.  m000 is
        outside the domain rather than a counterexample -- which is the same
        conclusion B1345 reached, by a different route.
      * "torsion-free" (no torsion ELEMENTS in the group) is what makes it a
        manifold rather than an orbifold; that part of the gloss is fair.""")

    # ---------------------------------------------------------------- m004
    rule("PART 2 -- reproduce J(m004) = 1 with SnapPy, independently of the exact rep")
    M = snappy.Manifold("m004")
    G = M.fundamental_group()
    print(f"    m004: generators = {G.num_generators()}, relators = {G.relators()}")
    A, B = mat(G, "a"), mat(G, "b")
    print(f"    SnapPy's DEFAULT generators are NOT parabolic: tr a = {np.trace(A):.6f}")
    v4, n4 = nielsen_min(A, B, 4)
    print(f"    Nielsen-minimised over {n4} generating pairs: J <= {v4:.12f}")
    ok4 = abs(v4 - 1.0) < 1e-9
    print(f"    equals 1 to 1e-9 : {ok4}")
    if not ok4:
        fail("M004", f"did not reproduce J(m004) = 1; got {v4}")
    print("""
    This is the same number the exact Z[zeta_6] certificate got from the
    parabolic pair, now from SnapPy's own holonomy and a different search.""")

    # ---------------------------------------------------------------- the census
    rule("PART 3 -- TEST the uniqueness: scan the orientable cusped census")
    print("""
    Callahan's theorem is CITED, not proved here.  But it is FALSIFIABLE on this
    bench: if another TWO-GENERATOR torsion-free orientable cusped manifold
    reaches 1, the statement as relayed is wrong.  Every value below is an UPPER
    BOUND on that manifold's J (Nielsen pairs generate), so a value of 1 is a
    genuine hit and a value above 1 is only a bound.""")
    census = snappy.OrientableCuspedCensus
    N = 350
    rows, below, hits = [], [], []
    for i, Mi in enumerate(census):
        if i >= N:
            break
        try:
            Gi = Mi.fundamental_group()
            if Gi.num_generators() != 2:
                continue
            X, Y = mat(Gi, "a"), mat(Gi, "b")
            v, _ = nielsen_min(X, Y, 3)
        except Exception:
            continue
        rows.append((Mi.name(), v))
        if v < 1 - 1e-6:
            below.append((Mi.name(), v))
        if abs(v - 1) < 1e-6:
            hits.append((Mi.name(), v))

    rows.sort(key=lambda r: r[1])
    print(f"\n    two-generator manifolds scanned : {len(rows)} (of the first {N} in the census)")
    print(f"    the twelve smallest upper bounds:")
    for name, v in rows[:12]:
        star = "   <-- J = 1" if abs(v - 1) < 1e-6 else ""
        print(f"      {name:12} {v:.9f}{star}")

    print(f"\n    manifolds reaching 1 : {[n for n, _ in hits]}")
    uniq = [n for n, _ in hits] == ["m004"]
    print(f"    m004 is the ONLY one : {uniq}")
    if not uniq:
        fail("UNIQUENESS", f"reached 1 on {[n for n,_ in hits]} -- not m004 alone")

    # ---------------------------------------------------------------- control
    rule("CONTROL -- nothing may fall BELOW 1, and the search must be able to move")
    print("""
    Jorgensen's inequality forbids a value below 1 on a generating pair of a
    non-elementary Kleinian group.  A value below 1 here would mean THIS
    COMPUTATION is wrong, not that the theorem is.  That makes it a real check
    on the instrument rather than on the literature.""")
    print(f"    values strictly below 1 : {len(below)} {below[:5]}")
    c_below = not below
    print(f"    CONTROL (>= 1 everywhere) : {'PASS' if c_below else 'FAIL'}")
    if not c_below:
        fail("BELOW", f"{len(below)} manifolds came out below 1 -- instrument error")

    spread = rows[-1][1] - rows[0][1] if rows else 0
    print(f"\n    spread of the bounds: {rows[0][1]:.6f} .. {rows[-1][1]:.6f} "
          f"(range {spread:.3f})")
    c_move = spread > 1
    print(f"    CONTROL (the statistic varies, so 'm004 alone' is not vacuous) : "
          f"{'PASS' if c_move else 'FAIL'}")
    if not c_move:
        fail("SPREAD", "the quantity barely varies; the uniqueness test is vacuous")

    # ---------------------------------------------------------------- verdict
    print("\n" + "=" * 78)
    print(" VERDICT")
    print("=" * 78)
    print(f"   J(m004) = 1 reproduced from SnapPy's holonomy : {ok4}")
    print(f"   m004 alone reaches 1 over {len(rows)} two-generator census manifolds : {uniq}")
    print(f"   nothing below 1 (Jorgensen's inequality holds in this run) : {c_below}")
    print(f"   the quantity varies over the census : {c_move}")
    print("""
   THE CORRECTION THIS RUN FORCES:
     Callahan's hypothesis includes TWO-GENERATOR.  Memo 225 claimed the theorem
     discharges UNIQUENESS_THEOREM's A1 (the two-record substrate).  IT DOES NOT
     -- a two-generator group IS that hypothesis in another language.  The
     theorem ASSUMES the first axiom; it does not derive it.""")
    if FAILURES:
        print("\n  FAILURES:")
        for f in FAILURES:
            print(f"    - {f}")
    print("=" * 78)
    return 1 if FAILURES else 0


if __name__ == "__main__":
    sys.exit(main())
