#!/usr/bin/env python3
"""CELL 1 -- requirement 2 (chirality): does B1163's theorem climb the tower?

Seal: outside_bench/seals/REQUIRE_AND_TEST_CELL1_PREREG.md
      sha256 70bce752b759f090681c53dce2b21243b4a2400474aff47442b08fae871b45d6

THE LEMMA UNDER TEST.  Let M be an orientable finite-volume hyperbolic
3-manifold with an orientation-reversing isometry sigma, and let H <= pi_1(M)
have finite index with its CONJUGACY CLASS fixed by sigma_*.  Then sigma lifts
to an orientation-reversing isometry of M_H, so M_H is amphichiral.

THE FALSIFIABLE COROLLARY (non-circular).  A subgroup cut out by a
CHARACTERISTIC quotient has a sigma_*-fixed class BY CONSTRUCTION -- no
computation, so no circularity.  For a knot complement the degree-n cyclic
cover is ker(pi_1 ->> H_1 = Z ->> Z/n).  Hence EVERY cyclic cover of m004 must
be amphichiral.  ONE CHIRAL CYCLIC COVER REFUTES THE LEMMA.

Instruments reused, not rebuilt:
  outside_bench/certificates/the_mirror_and_the_bulk.py :: mirror, amphichiral_det
    -- the ORIENTATION-AWARE test.  is_isometric_to(mirror) alone is
       orientation-blind (B1235); it is computed here only to show it is wrong.

SnapPy 3.3.2.  No Sage, no GAP (neither is installed in this container).
"""
from __future__ import annotations

import sys
import warnings

warnings.filterwarnings("ignore")

try:
    import snappy
except Exception as exc:  # pragma: no cover
    print("FATAL: snappy unavailable:", exc)
    sys.exit(2)

MAX_CYCLIC_DEGREE = 30          # sealed
VACUITY_COVER_DEGREE = 7        # sealed


def rule(title: str) -> None:
    print("\n" + "-" * 78)
    print(" " + title)
    print("-" * 78)


def mirror(M):
    Mm = M.copy()
    Mm.reverse_orientation()
    return Mm


def amphichiral_det(M):
    """ORIENTATION-AWARE: amphichiral iff some isometry to the mirror has
    cusp-map determinant +1.  True/False, or None if undecidable."""
    try:
        isos = M.is_isometric_to(mirror(M), return_isometries=True)
    except Exception:
        return None
    if not isos:
        return False
    for i in isos:
        try:
            for cm in i.cusp_maps():
                if round(cm[0, 0] * cm[1, 1] - cm[0, 1] * cm[1, 0]) == 1:
                    return True
        except Exception:
            continue
    return False


def naive_amphichiral(M):
    """The ORIENTATION-BLIND test, computed only to exhibit that it differs."""
    try:
        return bool(M.is_isometric_to(mirror(M)))
    except Exception:
        return None


def abelianization_perms(M, n):
    """Permutation rep of pi_1(M) -> Z/n through H_1, as a list of lists.

    Each generator goes to the k-th power of the n-cycle, k its exponent sum
    in the abelianization.  For m004 the relator aaabABBAb has exponent sums
    (a, b) = (1, 0), so H_1 = Z is generated by b and a maps to 0 -- which is
    why the naive [n-cycle, n-cycle] rep fails to satisfy the relator.
    """
    G = M.fundamental_group()
    gens = G.generators()
    rels = G.relators()

    # exponent sums of each generator in each relator
    def expsum(word, g):
        return sum(1 if ch == g else (-1 if ch == g.upper() else 0) for ch in word)

    # Solve for a Z-valued map killing every relator, over the generators.
    # For a knot complement H_1 = Z; find the primitive integer kernel vector.
    import itertools
    rows = [[expsum(r, g) for g in gens] for r in rels]
    # brute-force a small primitive solution (generators are few)
    best = None
    for vec in itertools.product(range(-3, 4), repeat=len(gens)):
        if all(v == 0 for v in vec):
            continue
        if all(sum(row[i] * vec[i] for i in range(len(gens))) == 0 for row in rows):
            from math import gcd
            g0 = 0
            for v in vec:
                g0 = gcd(g0, abs(v))
            if g0 == 1:
                best = vec
                break
    if best is None:
        return None, None
    cyc = [(i + 1) % n for i in range(n)]

    def power(p, k):
        k %= n
        out = list(range(n))
        for _ in range(k):
            out = [p[x] for x in out]
        return out

    return [power(cyc, k) for k in best], best


def cyclic_cover(M, n):
    perms, vec = abelianization_perms(M, n)
    if perms is None:
        return None, None
    try:
        return M.cover(perms), vec
    except Exception:
        return None, vec


def main() -> int:
    print("=" * 78)
    print(" CELL 1 -- REQUIREMENT 2 (CHIRALITY): DOES B1163'S THEOREM CLIMB?")
    print("=" * 78)
    print("""
    seal  outside_bench/seals/REQUIRE_AND_TEST_CELL1_PREREG.md
    sha256 70bce752b759f090681c53dce2b21243b4a2400474aff47442b08fae871b45d6""")

    base = snappy.Manifold("m004")
    failures = []

    # ------------------------------------------------------------------ C1
    rule("CONTROL C1 -- the instrument is wired to the object")
    a4 = amphichiral_det(base)
    sg = base.symmetry_group()
    print(f"    m004  amphichiral_det = {a4}   |Sym| = {sg.order()}   "
          f"is_amphicheiral = {sg.is_amphicheiral()}")
    ok_c1 = (a4 is True and sg.order() == 8)
    print(f"    -> {'PASS' if ok_c1 else 'FAIL'}  (expect True and order 8: D4, amphichiral)")
    if not ok_c1:
        failures.append("C1")

    # ------------------------------------------------------------------ C2
    rule("CONTROL C2 -- the instrument can say NO (else PART C passes vacuously)")
    ok_c2 = True
    for name in ("5_2", "6_1", "m015"):
        M = snappy.Manifold(name)
        ad = amphichiral_det(M)
        nv = naive_amphichiral(M)
        print(f"    {name:6s} amphichiral_det = {str(ad):5s}   naive = {str(nv):5s}")
        if ad is not False:
            ok_c2 = False
    print(f"    -> {'PASS' if ok_c2 else 'FAIL'}  (all three must read CHIRAL)")
    if not ok_c2:
        failures.append("C2")

    # ------------------------------------------------------------------ C3 + PART C
    rule("CONTROL C3 + PART C -- the cyclic (CHARACTERISTIC) covers")
    print("""
    The subgroup is ker(pi_1 ->> H_1 ->> Z/n): characteristic BY CONSTRUCTION.
    sigma_*-fixedness is therefore established without computing anything about
    the cover -- the test is not circular.  The lemma predicts AMPHICHIRAL for
    every row.  A single CHIRAL row refutes it.
""")
    vol0 = float(base.volume())
    rows = []
    ok_c3 = True
    for n in range(2, MAX_CYCLIC_DEGREE + 1):
        C, vec = cyclic_cover(base, n)
        if C is None:
            rows.append((n, None, None, None, "cover construction FAILED"))
            ok_c3 = False
            continue
        info = C.cover_info()
        vol = float(C.volume())
        hom = str(C.homology())
        ad = amphichiral_det(C)
        volok = abs(vol - n * vol0) < 1e-6
        if not volok or info.get("type") != "cyclic":
            ok_c3 = False
        rows.append((n, info.get("type"), vol, hom, ad))
        print(f"    n={n:2d}  type={str(info.get('type')):9s} vol={vol:11.6f} "
              f"(= {n}*vol0: {'yes' if volok else 'NO'})  H1={hom:24s} "
              f"amphichiral={ad}")

    decided = [r for r in rows if r[4] is not None]
    chiral = [r for r in decided if r[4] is False]
    undecided = [r for r in rows if r[4] is None]

    print(f"\n    cyclic covers built and DECIDED : {len(decided)} of {MAX_CYCLIC_DEGREE - 1}")
    print(f"    undecided (reported, not counted as either) : {len(undecided)}"
          + (f"  degrees {[r[0] for r in undecided]}" if undecided else ""))
    print(f"    CHIRAL among them : {len(chiral)}"
          + (f"  degrees {[r[0] for r in chiral]}" if chiral else ""))

    if len(decided) == 0:
        print("    -> PART C VACUOUS: nothing was decided.  No outcome is reported.")
        failures.append("PARTC-VACUOUS")
        partC = "VACUOUS"
    elif len(chiral) == 0:
        partC = "A"
        print("    -> PART C = A : every characteristic cover tested is amphichiral.")
        print("       The lemma survives its falsifier over this population.")
    else:
        partC = "B"
        print("    -> PART C = B : a CHIRAL characteristic cover exists.  LEMMA REFUTED.")
    print(f"    C3 (type and volume of every built cover) -> {'PASS' if ok_c3 else 'FAIL'}")
    if not ok_c3:
        failures.append("C3")

    # ------------------------------------------------------------------ PART V
    rule("PART V -- NON-VACUITY: are any covers of m004 chiral at all?")
    print("""
    If no cover of m004 is chiral, PART C says nothing and must be reported as
    vacuous.  Re-derived here, not cited from B1324.
""")
    tot = ch = am = und = 0
    per_type = {}
    for d in range(2, VACUITY_COVER_DEGREE + 1):
        try:
            covs = base.covers(d)
        except Exception as exc:
            print(f"    degree {d}: enumeration FAILED: {exc}")
            continue
        for C in covs:
            tot += 1
            ty = C.cover_info().get("type", "?")
            ad = amphichiral_det(C)
            slot = per_type.setdefault(ty, [0, 0, 0])
            if ad is True:
                am += 1
                slot[0] += 1
            elif ad is False:
                ch += 1
                slot[1] += 1
            else:
                und += 1
                slot[2] += 1
        print(f"    degree {d}: {len(covs)} covers")
    print(f"\n    POPULATION (asserted non-empty before any rate): {tot}")
    assert tot > 0, "empty cover population -- the B1197 vacuity trap"
    print(f"    amphichiral {am}   chiral {ch}   undecided {und}")
    for ty in sorted(per_type):
        a, c, u = per_type[ty]
        print(f"      {ty:10s} amphichiral {a:3d}   chiral {c:3d}   undecided {u:3d}")
    partV = "A" if ch > 0 else "B"
    print(f"    -> PART V = {partV} : "
          + ("chiral covers exist, the lemma has content."
             if ch > 0 else "NO chiral cover at this depth -- PART C IS VACUOUS."))

    # the lemma's prediction, restated against this independent population
    cyc_chiral = per_type.get("cyclic", [0, 0, 0])[1]
    print(f"\n    cross-check: chiral CYCLIC covers in this independent enumeration: {cyc_chiral}")
    print("      (the lemma predicts 0; this is a second, independent look at PART C)")
    if cyc_chiral != 0:
        failures.append("LEMMA-CROSSCHECK")

    # ------------------------------------------------------------------ verdict
    rule("VERDICT")
    print(f"    PART C = {partC}    PART V = {partV}")
    print(f"    controls: {'ALL PASSED' if not failures else 'FAILED: ' + ', '.join(failures)}")
    if partV == "B":
        print("    PART C's result is VACUOUS and is reported as such, whatever it says.")
    print("""
    PART E (the four named escape routes) is adjudication against the record,
    not a computation; it is carried in the memo, from the seal's fixed list.""")
    return 0 if not failures else 1


if __name__ == "__main__":
    sys.exit(main())
