#!/usr/bin/env python3
"""THE TWO THREES -- is the Z/3 in B1355's sum rule the object's own 2T/Q_8?

Seal: outside_bench/seals/THE_TWO_THREES_PREREG.md
      sha256 46475ca8c813bde69db705491c086f26b4d82748416e09971d659e35dc60f9d8
      (committed d88b0a70, BEFORE this file was written)

The seal states up front that most of the identification is ALREADY BANKED
(B1273 section 2: Y_3's holonomy is V_4 = ker(A_4 -> Z/3), its three flat
directions "permuted by the deck Z/3"), so outcome A is close to forced and
is NOT this cell's contribution.  What this cell establishes is the exact
equivariance, re-derived rather than cited, and the CONSEQUENCE for B1355's
sum rule.

Exact arithmetic only: quaternions over Z[1/2] represented as integer
4-tuples in HALF units (so (1+i+j+k)/2 is (1,1,1,1) and 1 is (2,0,0,0)).
No floats anywhere.

Stdlib only.
"""
from __future__ import annotations

from itertools import product

# ---------------------------------------------------------------- quaternions
# All quaternions are integer 4-tuples in units of 1/2:  (w,x,y,z) means
# (w + x i + y j + z k)/2.


def qmul(p, q):
    """Product in half-units: (P/2)(Q/2) = (PQ)/4, so divide by 2 to stay in
    half-units.  Exact: the product of two elements of 2T is in 2T, whose
    half-unit coordinates are always integers, so the division is exact."""
    a1, b1, c1, d1 = p
    a2, b2, c2, d2 = q
    w = a1 * a2 - b1 * b2 - c1 * c2 - d1 * d2
    x = a1 * b2 + b1 * a2 + c1 * d2 - d1 * c2
    y = a1 * c2 - b1 * d2 + c1 * a2 + d1 * b2
    z = a1 * d2 + b1 * c2 - c1 * b2 + d1 * a2
    assert all(v % 2 == 0 for v in (w, x, y, z)), "non-exact product"
    return (w // 2, x // 2, y // 2, z // 2)


def qconj(p):
    a, b, c, d = p
    return (a, -b, -c, -d)


def qinv(p):
    """2T consists of UNIT quaternions, so the inverse is the conjugate."""
    return qconj(p)


ONE = (2, 0, 0, 0)
NEG = (-2, 0, 0, 0)
I = (0, 2, 0, 0)
J = (0, 0, 2, 0)
K = (0, 0, 0, 2)


def build_2T():
    """The binary tetrahedral group: the 8 Lipschitz units +-1, +-i, +-j, +-k
    and the 16 Hurwitz units (+-1+-i+-j+-k)/2."""
    els = [ONE, NEG, I, (0, -2, 0, 0), J, (0, 0, -2, 0), K, (0, 0, 0, -2)]
    for s in product((1, -1), repeat=4):
        els.append(s)
    return els


def norm2(p):
    """|q|^2 in half-units squared; a unit quaternion has sum of squares 4."""
    return sum(v * v for v in p)


def rule(t):
    print("\n" + "-" * 78)
    print(" " + t)
    print("-" * 78)


def main():
    ok = {}

    # ---------------------------------------------------------------- setup
    rule("SETUP -- 2T and Q_8, exact (integer half-units, no floats)")
    T2 = build_2T()
    assert len(set(T2)) == 24
    assert all(norm2(p) == 4 for p in T2), "not all unit quaternions"
    # closure
    S = set(T2)
    assert all(qmul(p, q) in S for p in T2 for q in T2), "2T not closed"
    print(f"  |2T| = {len(T2)}  (all unit, closed under multiplication)")

    Q8 = [ONE, NEG, I, (0, -2, 0, 0), J, (0, 0, -2, 0), K, (0, 0, 0, -2)]
    assert len(set(Q8)) == 8
    SQ = set(Q8)
    print(f"  |Q_8| = {len(Q8)}")

    # Q_8 normal in 2T?
    normal = all(qmul(qmul(g, h), qinv(g)) in SQ for g in T2 for h in Q8)
    print(f"  Q_8 normal in 2T: {normal}")
    print(f"  index [2T : Q_8]  = {len(T2) // len(Q8)}")
    ok["Q8 normal, index 3"] = normal and len(T2) // len(Q8) == 3

    # the quotient is Z/3: take w = (1+i+j+k)/2
    W = (1, 1, 1, 1)
    assert W in S
    W2 = qmul(W, W)
    W3 = qmul(W2, W)
    print(f"  w = (1+i+j+k)/2 in 2T; w^3 = {W3}  (= -1: w has order 6, "
          f"w^3 central)")
    cyclic = (W not in SQ) and (W2 not in SQ) and (W3 in SQ)
    print(f"  w, w^2 outside Q_8 and w^3 inside  ->  2T/Q_8 = <wQ_8> = Z/3: "
          f"{cyclic}")
    ok["2T/Q8 = Z/3 generated by w"] = cyclic

    # ------------------------------------------------- SIDE A (B1269)
    rule("SIDE A (B1269) -- the three imaginary quaternion units of Q_8, "
         "under conjugation by 2T/Q_8")
    # the triple is {+-i, +-j, +-k}, i.e. the three classes mod +-1
    def cls(p):
        """the class of an imaginary unit modulo sign: 'i', 'j' or 'k'"""
        for nm, base in (("i", I), ("j", J), ("k", K)):
            if p == base or p == tuple(-v for v in base):
                return nm
        return None

    sideA = {}
    for nm, base in (("i", I), ("j", J), ("k", K)):
        img = qmul(qmul(W, base), qinv(W))
        sideA[nm] = cls(img)
        print(f"  w {nm} w^-1 = {img}  ->  class {sideA[nm]}")
    a_is_3cycle = sorted(sideA.values()) == ["i", "j", "k"] and all(
        sideA[n] != n for n in sideA)
    print(f"  the action is a 3-cycle on {{i, j, k}}: {a_is_3cycle}   "
          f"({sideA})")
    ok["side A is a 3-cycle"] = a_is_3cycle

    # ------------------------------------------------- V4, A4 (B1273)
    rule("B1273's GROUPS RE-DERIVED -- V_4 = Q_8/{+-1}, A_4 = 2T/{+-1}, "
         "and V_4 = ker(A_4 -> Z/3)")

    def modpm(p):
        """canonical representative of {p, -p}"""
        q = tuple(-v for v in p)
        return min(p, q)

    V4 = sorted({modpm(p) for p in Q8})
    A4 = sorted({modpm(p) for p in T2})
    print(f"  |V_4| = {len(V4)}   |A_4| = {len(A4)}")
    # V4 exponent 2 (every element squares to the identity class)
    idc = modpm(ONE)
    exp2 = all(modpm(qmul(p, p)) == idc for p in V4)
    print(f"  V_4 has exponent 2 (Klein four-group): {exp2}")
    print(f"  index [A_4 : V_4] = {len(A4) // len(V4)}  -> the quotient is "
          f"Z/3, and V_4 = ker(A_4 -> Z/3)")
    ok["V4 = ker(A4 -> Z/3), Klein"] = (
        len(V4) == 4 and len(A4) == 12 and exp2 and len(A4) // len(V4) == 3)

    # ------------------------------------------------- SIDE B (B1273)
    rule("SIDE B (B1273) -- the three NON-TRIVIAL CHARACTERS of V_4 "
         "(= the three flat directions of Y_3), under the deck Z/3")
    # label V4's non-identity elements by their imaginary unit
    v_label = {}
    for p in V4:
        if p == idc:
            continue
        v_label[p] = cls(p) if cls(p) else cls(tuple(-v for v in p))
    print(f"  V_4 non-identity elements: "
          f"{ {v_label[p]: p for p in v_label} }")

    # characters of V4 = Hom(V4, {+-1}); the three non-trivial ones are
    # chi_n = the character with kernel <n>, i.e. chi_n(m) = +1 iff m in {e,n}
    nonid = sorted(v_label, key=lambda p: v_label[p])

    def chi(n, m):
        """the non-trivial character whose kernel is {e, n}"""
        return 1 if (m == idc or m == n) else -1

    for n in nonid:
        row = {v_label[m]: chi(n, m) for m in nonid}
        print(f"  chi_{v_label[n]} on (i,j,k) = "
              f"{[row[x] for x in ('i','j','k')]}   (kernel <{v_label[n]}>)")

    # the deck Z/3 acts on V4 by conjugation by w; it acts on characters by
    # (g . chi)(m) = chi(g^-1 m g)
    def conj_v(g, p):
        return modpm(qmul(qmul(g, p), qinv(g)))

    sideB = {}
    for n in nonid:
        # w . chi_n has kernel <w n w^-1>
        sideB[v_label[n]] = v_label[conj_v(W, n)]
        print(f"  w . chi_{v_label[n]} = chi_{sideB[v_label[n]]}")
    b_is_3cycle = sorted(sideB.values()) == ["i", "j", "k"] and all(
        sideB[n] != n for n in sideB)
    print(f"  the deck action is a 3-cycle on the three characters: "
          f"{b_is_3cycle}   ({sideB})")
    ok["side B is a 3-cycle"] = b_is_3cycle

    # ------------------------------------------------- THE INTERTWINING
    rule("THE INTERTWINING TEST -- is the natural map "
         "(imaginary units mod +-1) -> (non-trivial characters of V_4) "
         "Z/3-EQUIVARIANT?")

    def equivariant(labelmap):
        """labelmap: how side A's labels are matched to side B's.
        Equivariance: labelmap(sideA[n]) == sideB[labelmap(n)] for all n."""
        return all(labelmap[sideA[n]] == sideB[labelmap[n]] for n in sideA)

    identity_map = {"i": "i", "j": "j", "k": "k"}
    res_true = equivariant(identity_map)
    print(f"  natural map (i->chi_i, j->chi_j, k->chi_k):  equivariant = "
          f"{res_true}")

    # Z3 CONTROL: the routine must be able to return FALSE
    swapped = {"i": "j", "j": "i", "k": "k"}
    res_false = equivariant(swapped)
    print(f"  CONTROL Z3, a deliberately wrong relabelling (i<->j): "
          f"equivariant = {res_false}   (MUST be False)")
    ok["Z3 -- the test returns BOTH answers"] = (res_true and not res_false)

    # ------------------------------------------------- Z4
    rule("CONTROL Z4 -- B1273's FINGERPRINT REPRODUCED from "
         "F(2,6) = <x_1..x_6 | x_i x_{i+1} = x_{i+2}>")
    # abelianised: x_i + x_{i+1} - x_{i+2} = 0, indices mod 6
    M = []
    for i in range(6):
        row = [0] * 6
        row[i] += 1
        row[(i + 1) % 6] += 1
        row[(i + 2) % 6] -= 1
        M.append(row)

    def smith_diagonal(mat):
        """integer Smith normal form diagonal, exact, no libraries"""
        A = [r[:] for r in mat]
        m, n = len(A), len(A[0])
        res = []
        r = c = 0
        while r < m and c < n:
            piv = None
            for i in range(r, m):
                for j in range(c, n):
                    if A[i][j] != 0 and (piv is None or
                                         abs(A[i][j]) < abs(A[piv[0]][piv[1]])):
                        piv = (i, j)
            if piv is None:
                break
            pi, pj = piv
            A[r], A[pi] = A[pi], A[r]
            for row in A:
                row[c], row[pj] = row[pj], row[c]
            again = True
            while again:
                again = False
                for i in range(r + 1, m):
                    if A[i][c] != 0:
                        q = A[i][c] // A[r][c]
                        for j in range(c, n):
                            A[i][j] -= q * A[r][j]
                        if A[i][c] != 0:
                            A[r], A[i] = A[i], A[r]
                            again = True
                for j in range(c + 1, n):
                    if A[r][j] != 0:
                        q = A[r][j] // A[r][c]
                        for i in range(r, m):
                            A[i][j] -= q * A[i][c]
                        if A[r][j] != 0:
                            for i in range(r, m):
                                A[i][c], A[i][j] = A[i][j], A[i][c]
                            again = True
            res.append(abs(A[r][c]))
            r += 1
            c += 1
        return res

    d = smith_diagonal(M)
    torsion = [x for x in d if x not in (0, 1)]
    free = 6 - len(d)
    print(f"  Smith diagonal of the 6x6 relation matrix: {d}")
    print(f"  -> H_1(Y_3) torsion {torsion}, free rank {free}  "
          f"(B1273: Z/4 + Z/4, b_1 = 0)")
    ok["Z4a -- H_1(Y_3) = Z/4 + Z/4"] = (sorted(torsion) == [4, 4] and free == 0)

    # hom counts: x3..x6 are determined by x1,x2; two wrap-around relations
    # remain, so only |G|^2 pairs need testing.
    def count_homs(elts, mul, eq):
        n = 0
        for x1 in elts:
            for x2 in elts:
                x = [x1, x2]
                for i in range(4):
                    x.append(mul(x[i], x[i + 1]))
                # relations x_5 x_6 = x_1 and x_6 x_1 = x_2 (1-indexed)
                if eq(mul(x[4], x[5]), x[0]) and eq(mul(x[5], x[0]), x[1]):
                    n += 1
        return n

    nq8 = count_homs(Q8, qmul, lambda a, b: a == b)
    print(f"  homomorphisms F(2,6) -> Q_8 : {nq8}   (B1273: 64; "
          f"of |Q_8|^2 = {len(Q8)**2} pairs)")

    # A_4 as even permutations of 4 points
    def perms_A4():
        out = []
        for p in product(range(4), repeat=4):
            if sorted(p) != [0, 1, 2, 3]:
                continue
            inv = sum(1 for a in range(4) for b in range(a + 1, 4)
                      if p[a] > p[b])
            if inv % 2 == 0:
                out.append(p)
        return out

    A4p = perms_A4()
    assert len(A4p) == 12
    na4 = count_homs(A4p, lambda p, q: tuple(p[q[i]] for i in range(4)),
                     lambda a, b: a == b)
    print(f"  homomorphisms F(2,6) -> A_4 : {na4}   (B1273: 16; "
          f"of |A_4|^2 = {len(A4p)**2} pairs -- NOT all pairs, so the count "
          f"is load-bearing)")
    ok["Z4b -- 64 homs to Q_8, 16 to A_4"] = (nq8 == 64 and na4 == 16)

    # --------------------------------- ADDED AFTER THE SEAL (labelled)
    rule("NOT PREREGISTERED -- added after the seal, and labelled as such: "
         "WHY b_2 = 1 FORCES THE CHARGES TO ZERO")
    print("""  B1355's escape clause says a Z/3-symmetric triple "needs b_2 >= 2 with the
  Z/3 moving the harmonic forms".  The reason it cannot be met at b_2 = 1 is
  elementary and is exhibited here rather than asserted:

    H^2(X; R) = R^{b_2}, and a Z/3 action is a homomorphism Z/3 -> GL(b_2, R).""")
    # b_2 = 1: GL(1,R) = R^*, whose only finite subgroups are {1} and {+-1}.
    # An element of order 3 would have to lie in {+-1}; neither has order 3.
    orders_in_GL1 = {1: 1, -1: 2}           # order of each finite element
    has_order_3_in_GL1 = any(o == 3 for o in orders_in_GL1.values())
    print(f"    b_2 = 1: the finite elements of GL(1,R) = R^* are "
          f"{sorted(orders_in_GL1)} with orders "
          f"{[orders_in_GL1[x] for x in sorted(orders_in_GL1)]};")
    print(f"             an element of order 3 exists: {has_order_3_in_GL1}"
          f"   -> every Z/3 action on R^1 is TRIVIAL.")
    # b_2 = 2: the rotation by 120 degrees has order 3 -- so the argument is
    # dimension-specific, not a triviality (the shape of B1259's own control).
    # exact check in the ring Z[x]/(x^2+x+1): the companion matrix of that
    # polynomial is an order-3 element of GL(2,Z) < GL(2,R).
    C = ((0, -1), (1, -1))                  # companion matrix of x^2 + x + 1

    def m2(a, b):
        return tuple(tuple(sum(a[i][k] * b[k][j] for k in range(2))
                           for j in range(2)) for i in range(2))

    C2 = m2(C, C)
    C3 = m2(C2, C)
    ident = ((1, 0), (0, 1))
    order3 = (C != ident and C2 != ident and C3 == ident)
    print(f"    b_2 = 2: the companion matrix of x^2+x+1, C = {C}, has "
          f"C^3 = {C3} = I and C, C^2 != I: order 3 = {order3}")
    print("""             -> a Z/3 CAN move the harmonic forms once b_2 >= 2.

  So the obstruction is specific to b_2 = 1 rather than a general fact about
  Z/3 -- the same shape as B1259's own control (SO(6) elements generically
  avoid eigenvalue +1 while SO(7) never do).  Consequence, with the Z/3 now
  known to be the object's own 2T/Q_8: at b_2 = 1 the three charges are
  EQUAL, the sum rule forces 3q = 0 hence q = 0, and there is NO INFLOW.""")
    ok["post-seal -- b_2=1 forces trivial Z/3, b_2=2 does not"] = (
        (not has_order_3_in_GL1) and order3)

    # ------------------------------------------------- verdict
    rule("CONTROLS")
    for k, v in ok.items():
        print(f"  {'PASS' if v else 'FAIL'}   {k}")

    rule("THE QUESTION")
    outcome = "A" if (res_true and not res_false and a_is_3cycle
                      and b_is_3cycle) else "B"
    print(f"  side A (B1269): w conjugates the three imaginary units of Q_8 "
          f"as {sideA}")
    print(f"  side B (B1273): the deck Z/3 permutes the three characters of "
          f"V_4 = Q_8/{{+-1}} as {sideB}")
    print(f"  the natural map is Z/3-equivariant: {res_true}")
    print(f"\n  -> OUTCOME {outcome}")
    if outcome == "A":
        print("""
  READING (and the seal fixed this pricing BEFORE the run):
  The identification itself is NOT news -- B1273 section 2 already computes
  that Y_3's holonomy is V_4 = ker(A_4 -> Z/3) with the three flat
  directions "permuted by the deck Z/3", and A_4 = 2T/{+-1}, V_4 = Q_8/{+-1}
  make the rest elementary.  What the result establishes is the CONSEQUENCE:
  the Z/3 in B1355's charge sum rule is THE OBJECT'S OWN 2T/Q_8, not a
  design choice of the closing.  B1355 asks "whether the tower's Z/3 descent
  CAN place three apexes"; the symmetry is not optional, so its escape
  clause -- b_2 >= 2 AND the Z/3 moving the harmonic forms -- is a FORCED
  necessary condition on any closing realising destination item 1.

  FENCES: X is not constructed; no b_2 of any 7-manifold is computed or
  inferred here (the record has none, and the Q -> X bridge is absent from
  every head); I-26 is UNEARNED so no generation count is licensed; B1355's
  "one 27 per point" is the literature's rule, not re-derived.  This is a
  condition ON a closing, never a property OF one, and it is NOT progress
  toward chirality.""")
    print()
    return 0 if all(ok.values()) else 1


if __name__ == "__main__":
    raise SystemExit(main())
