r"""A4 — do m004's TWO surjections differ STRUCTURALLY from everyone else's?

The base-rate control killed the atom on a COUNT: 36.4% of census knots admit
exactly two surjections pi_1 ->> 2T, m004's own number. But a count is a coarse
invariant. This asks the finer question the base-rate arc explicitly queued:

    among the knots that TIE m004's count, do the surjections carry the same
    structure -- or is m004's pair distinguished at finer resolution?

THE FINGERPRINT. A knot group has a canonical peripheral subgroup generated by
the meridian m and longitude l. Any surjection phi: pi_1 ->> 2T sends m to some
element whose ORDER is a conjugacy invariant, and sends l likewise. The pair

    signature(M) = sorted multiset over the surjections of (ord phi(m), ord phi(l))

is a genuine structural fingerprint that the raw count cannot see. If m004's
signature is rare among the knots that tie its count, the atom survives at finer
resolution. If it is modal, the count result stands as the whole story.

Longitude note: for a knot in S^3 the longitude is nullhomologous, so it lands
in the commutator subgroup; its image order is still an invariant and is
recorded, but the meridian carries most of the discrimination.

Gate 5-Q. Structure only.
"""
import argparse
import collections
import importlib.util
import json
import os

import snappy

_spec = importlib.util.spec_from_file_location(
    'br', os.path.join(os.path.dirname(os.path.abspath(__file__)), 'base_rate_2T.py'))
br = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(br)

AUT = 24


def order(g):
    """Order of an element of 2T = SL(2,3)."""
    n, x = 1, g
    while x != br.IDENT:
        x = br.mul(x, g)
        n += 1
    return n


def signature(M):
    """Sorted multiset of (ord phi(meridian), ord phi(longitude)) over surjections."""
    G = M.fundamental_group()
    if G.num_generators() > 3:
        return None
    per = G.peripheral_curves()
    if not per:
        return None
    mer, lon = per[0]
    sig = []
    for images in br._tuples(G.num_generators()):
        if not all(br.evaluate(r, images) == br.IDENT for r in G.relators()):
            continue
        if len(br.subgroup_closure(images)) != 24:
            continue
        sig.append((order(br.evaluate(mer, images)),
                    order(br.evaluate(lon, images))))
    return tuple(sorted(sig))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--n', type=int, default=3200)
    args = ap.parse_args()

    m4 = snappy.Manifold('m004')
    sig4 = signature(m4)
    n_surj4 = len(sig4) // AUT
    print(f'm004 signature (raw, {len(sig4)} surjections = {n_surj4} orbits):')
    print(f'  {collections.Counter(sig4)}\n')

    tally = collections.Counter()
    same_count = 0
    n = 0
    matches = []
    for M in snappy.CensusKnots():
        if n >= args.n:
            break
        try:
            s = signature(M)
        except Exception:
            continue
        if s is None:
            continue
        n += 1
        if len(s) // AUT != n_surj4:      # only knots that TIE m004's count
            continue
        same_count += 1
        key = tuple(sorted(collections.Counter(s).items()))
        tally[key] += 1
        if key == tuple(sorted(collections.Counter(sig4).items())):
            matches.append(M.name())

    print(f'knots swept                       : {n}')
    print(f'knots tying m004\'s surjection count: {same_count}')
    print(f'distinct peripheral signatures     : {len(tally)}\n')
    for key, cnt in tally.most_common():
        mark = '   <== m004' if key == tuple(sorted(collections.Counter(sig4).items())) else ''
        print(f'  {cnt:5}  {dict(key)}{mark}')
    print(f'\nknots sharing m004\'s FULL signature: {len(matches)}')
    print(f'  {matches[:15]}')
    json.dump({'m004_signature': {str(k): v for k, v in collections.Counter(sig4).items()},
               'swept': n, 'tie_count': same_count,
               'distinct_signatures': len(tally),
               'sharing_full_signature': len(matches), 'examples': matches[:40]},
              open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                'a4_signature.json'), 'w'), indent=1)


if __name__ == '__main__':
    main()
