r"""THE BASE-RATE CONTROL for the Standard-Model derivation.

The chain to the SM runs

    pi_1(m004)  -->>  2T  --McKay-->  E6  --cascade-->  SM

Every step after the first is group theory that knows nothing about m004.
The ONE object-specific fact carrying the whole derivation is the surjection
pi_1 ->> 2T (B266: exactly two of them).

B855, in the repo: "the programme has never had a valid control, so
'generic vs specific' has essentially never been TESTED."

This is that control. For a census of hyperbolic 3-manifolds, count
surjections pi_1(M) ->> 2T. If a large fraction of manifolds admit one, the
E6 atom is base-rate generic (E20's failure mode) and the derivation selects
nothing. If it is rare, the atom is real.

VALIDATION: the counter must reproduce B266's banked "exactly two" for m004
before any census number is believed. The script asserts it.

Gate 5-Q. Structure only; no physical constant appears.
"""
import argparse
import collections

import snappy

# ---------------------------------------------------- 2T = SL(2,3), order 24
def _sl23():
    return [(a, b, c, d)
            for a in range(3) for b in range(3) for c in range(3) for d in range(3)
            if (a * d - b * c) % 3 == 1]


G = _sl23()
IDENT = (1, 0, 0, 1)


def mul(x, y):
    a, b, c, d = x
    e, f, g, h = y
    return ((a * e + b * g) % 3, (a * f + b * h) % 3,
            (c * e + d * g) % 3, (c * f + d * h) % 3)


def inv(x):
    a, b, c, d = x
    return (d % 3, (-b) % 3, (-c) % 3, a % 3)


def subgroup_closure(gens):
    """The subgroup generated by gens (small group, brute force)."""
    seen = {IDENT}
    frontier = [IDENT]
    while frontier:
        nxt = []
        for s in frontier:
            for g in gens:
                p = mul(s, g)
                if p not in seen:
                    seen.add(p)
                    nxt.append(p)
        frontier = nxt
    return seen


def evaluate(word, images):
    """Evaluate a relator word. Lowercase = generator, uppercase = inverse."""
    acc = IDENT
    for ch in word:
        if ch.islower():
            acc = mul(acc, images[ord(ch) - 97])
        else:
            acc = mul(acc, inv(images[ord(ch) - 65]))
    return acc


def count_surjections(gp, cap_gens=3):
    """Count homs pi_1 -> 2T whose image is ALL of 2T. None if too big."""
    n = gp.num_generators()
    if n > cap_gens:
        return None
    rels = gp.relators()
    total = surj = 0
    for images in _tuples(n):
        if all(evaluate(r, images) == IDENT for r in rels):
            total += 1
            if len(subgroup_closure(images)) == 24:
                surj += 1
    return total, surj


def _tuples(n):
    if n == 1:
        for g in G:
            yield (g,)
    elif n == 2:
        for g in G:
            for h in G:
                yield (g, h)
    else:
        for g in G:
            for h in G:
                for k in G:
                    yield (g, h, k)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--n', type=int, default=2000,
                    help='how many census manifolds to sweep')
    ap.add_argument('--cusps', type=int, default=1)
    args = ap.parse_args()

    # ---- VALIDATION against B266 before anything else is believed ----
    # B266 counts surjections UP TO Aut(2T); |Aut(SL(2,3))| = 24, verified
    # independently by constructing every automorphism from a generating pair.
    AUT = 24
    m4 = snappy.Manifold('m004')
    tot, sur = count_surjections(m4.fundamental_group())
    print(f'VALIDATION  m004: homs to 2T = {tot}, raw surjections = {sur}, '
          f'orbits under Aut(2T) = {sur // AUT}')
    assert sur // AUT == 2, f"expected B266's exactly two, got {sur // AUT}"
    print('  matches B266 ("exactly two surjections onto 2T")  OK\n')

    census = snappy.OrientableCuspedCensus(cusps=args.cusps)
    print(f'sweeping {args.n} of {len(census)} one-cusped census manifolds\n')

    n = with_surj = skipped = 0
    dist = collections.Counter()
    examples2 = []
    for M in census:
        if n >= args.n:
            break
        try:
            res = count_surjections(M.fundamental_group())
        except Exception:
            skipped += 1
            continue
        if res is None:
            skipped += 1
            continue
        _, s = res
        s //= 24          # orbits under Aut(2T), B266's convention
        n += 1
        dist[s] += 1
        if s:
            with_surj += 1
            if s == 2 and len(examples2) < 8:
                examples2.append(M.name())
        if n % 500 == 0:
            print(f'  {n:6} swept … {100*with_surj/n:5.1f}% admit a surjection')

    print(f'\n{"="*64}\nBASE RATE — surjections pi_1(M) ->> 2T\n{"="*64}')
    print(f'  manifolds swept          : {n}   (skipped {skipped}: >3 generators)')
    print(f'  admitting >=1 surjection : {with_surj}  = {100*with_surj/n:.1f}%')
    print(f'  admitting EXACTLY 2      : {dist[2]}  = {100*dist[2]/n:.1f}%'
          '   <- m004 sits here')
    print(f'\n  distribution of surjection counts:')
    for k in sorted(dist):
        print(f'    {k:4} surjections : {dist[k]:6}  ({100*dist[k]/n:5.2f}%)')
    print(f'\n  a few other manifolds with exactly 2: {examples2}')
    print('\n  READ THIS CAREFULLY: a high percentage means the 2T atom — and')
    print('  therefore E6, and therefore the whole cascade — is BASE-RATE')
    print('  GENERIC, and the derivation selects the class, not the object.')


if __name__ == '__main__':
    main()
