#!/usr/bin/env python3
"""B1634 post seal -- the read-back of the sealed run, written after it (disclosed in FINDINGS).  Four things the sealed
instrument did not settle:
 P1  V3's first law check failed at tau = 0.13 + 1.21i (T: relative error 1.10) and held at the other point.  Diagnosis:
     mpmath's jtheta(2, 0, q) takes the principal q^(1/4); at tau + 1 with Re > 1 the nome's argument wraps past pi and
     theta_2^2 changes sign.  Test: the laws at six points with the sealed F and with theta and eta summed directly in tau;
     and whether the failures are exactly the points where the principal branch disagrees with exp(i pi tau / 4).
 P2  V1/V2 at length <= 10 are forced by the exponent sum (any word for Delta^4 has exponent sum 12), so they are
     vacuous there.  Length 12, H_1 = I and H_1 = -I: the automorphisms, classified, and the lift on T in two senses --
     the product of the move matrices along the word (the weave's lift of the word) and M_of of the composed
     automorphism (defined only up to sign: lift_of takes the first of +-g in 2O).
 P3  The residual on T of the weave <L, R> alone at i (generated by Delta^{-1} = R L^-1 R) and at omega (by an order-6
     element of SL(2, Z)): eigen-structure, and where its lines sit against the parity lines.
 P4  chi_k(rho_theta) by a route independent of the Borcherds-Skoruppa formula: f in M_k(rho_theta) <-> h = eta^3 f in
     M_d(A), d = k + 3/2, A the weight-one multiplier of u = (theta_2^2, theta_3^2, theta_4^2), with h vanishing at the
     cusp; A is trivial on Gamma(4) and M_*(Gamma(4)) = C[u]/(u_3^2 - u_2^2 - u_4^2) (dimension 2d + 1, checked here
     numerically), so M_d(A) = the A-equivariant degree-d polynomial maps mod the quadric, exact in sympy.
 P5  The genuine completions of the lifts with T unrescaled, for each of the eight identifications: the S-scalar the
     Mp2(Z) relations force, and chi_{3/2}; and the six twists rho_theta (x) chi_eta^j allowed at 3/2.
 P6  The sign: M_of against the product of the move matrices for L, R and S~ (the sealed V3 and B1632 took S~ from M_of);
     then, with H_1's convention (S = H_1(S~), T = H_1(L); the lifts compose in reverse, so rho(g) = lift(g)^-1), whether
     the relations hold with no rescaling and whether rho equals rho_theta exactly (alpha = beta = 1), and chi there.
Writes post_seal_w50.json."""
import json, pathlib, os, importlib.util, itertools, cmath, math
import numpy as np
import mpmath as mp
import sympy as sp
HERE = pathlib.Path(__file__).resolve().parent
FRONTIER = pathlib.Path(os.environ.get("OA_FRONTIER", HERE.parents[1]))
spec = importlib.util.spec_from_file_location("w45", FRONTIER / "B1632_w45_verified_on_main" / "verification" / "w45_on_main.py")
w45 = importlib.util.module_from_spec(spec); spec.loader.exec_module(w45)
om, cp, TB = w45.om, w45.cp, w45.TB
W = om.W
K = 23 / 2
P13 = np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]], dtype=complex); P23 = np.array([[1, 0, 0], [0, 0, 1], [0, 1, 0]], dtype=complex)
rS = cmath.exp(-23j * math.pi / 4) * P13
rT = cmath.exp(7j * math.pi / 4) * np.diag([1j, 1, 1]) @ P23


def F_sealed(t):
    q = mp.exp(1j * mp.pi * t); eta = mp.exp(1j * mp.pi * t / 12) * mp.qp(mp.exp(2j * mp.pi * t))
    return np.array([complex(eta ** 21 * mp.jtheta(n, 0, q) ** 2) for n in (2, 3, 4)])


def F_direct(t, N=40):
    e = lambda x: mp.exp(1j * mp.pi * t * x)
    th2 = mp.fsum(e((n + mp.mpf(1) / 2) ** 2) for n in range(-N, N))
    th3 = mp.fsum(e(n * n) for n in range(-N, N + 1))
    th4 = mp.fsum((-1) ** abs(n) * e(n * n) for n in range(-N, N + 1))
    eta = mp.exp(1j * mp.pi * t / 12) * mp.fprod(1 - mp.exp(2j * mp.pi * t * n) for n in range(1, 4 * N))
    return np.array([complex(eta ** 21 * x ** 2) for x in (th2, th3, th4)])


def law_errors(F, t):
    lT, rT_ = F(t + 1), rT @ F(t)
    lS, rS_ = F(-1 / t), complex(t ** K) * (rS @ F(t))
    return float(np.abs(lT - rT_).max() / np.abs(rT_).max()), float(np.abs(lS - rS_).max() / np.abs(rS_).max())


def branch_wraps(t):
    q = mp.exp(1j * mp.pi * t)
    return bool(abs(q ** mp.mpf(0.25) - mp.exp(1j * mp.pi * t / 4)) > 1e-12)


def p1():
    mp.mp.dps = 30
    pts = [mp.mpc(0.13, 1.21), mp.mpc(-0.31, 0.93), mp.mpc(0.4, 1.1), mp.mpc(0.8, 0.9), mp.mpc(-0.7, 1.3), mp.mpc(0.05, 0.6)]
    rows = []
    for t in pts:
        sT, sS = law_errors(F_sealed, t); dT, dS = law_errors(F_direct, t)
        rows.append({"tau": [float(t.real), float(t.imag)], "sealed_T": sT, "sealed_S": sS, "direct_T": dT, "direct_S": dS,
                     "branch_wraps_at_tau_plus_1": branch_wraps(t + 1), "branch_wraps_at_minus_1_over_tau": branch_wraps(-1 / t),
                     "branch_wraps_at_tau": branch_wraps(t)})
    fail = [r for r in rows if max(r["sealed_T"], r["sealed_S"]) > 1e-8]
    wrap = [r for r in rows if r["branch_wraps_at_tau_plus_1"] or r["branch_wraps_at_minus_1_over_tau"] or r["branch_wraps_at_tau"]]
    return {"rows": rows, "direct_max_error": max(max(r["direct_T"], r["direct_S"]) for r in rows),
            "sealed_failures_are_exactly_the_wraps": [r["tau"] for r in fail] == [r["tau"] for r in wrap]}


def lift_matrices():
    T3 = lambda M: cp.restrict(M, TB)
    ML, MR = T3(W.ML), T3(W.MR)
    return {"L": ML, "l": np.linalg.inv(ML), "R": MR, "r": np.linalg.inv(MR)}


def p2(nmax=12):
    L = {"a": "a", "b": "ab"}; R = {"a": "ab", "b": "b"}; Li = {"a": "a", "b": "Ab"}; Ri = {"a": "aB", "b": "b"}
    gens = {"L": L, "l": Li, "R": R, "r": Ri}
    H = {"L": np.array([[1, 1], [0, 1]]), "R": np.array([[1, 0], [1, 1]])}
    H["l"] = np.round(np.linalg.inv(H["L"])).astype(int); H["r"] = np.round(np.linalg.inv(H["R"])).astype(int)
    # the H_1 matrices from the code's own h1, so the convention is the instrument's
    for x in "LlRr": H[x] = om.h1(gens[x])
    Mt = lift_matrices()
    inv = {"L": "l", "l": "L", "R": "r", "r": "R"}
    # composition order: f = x1 o x2 o ... ; which product order reproduces M_of up to sign?
    def word_auto(w):
        f = {"a": "a", "b": "b"}
        for x in w: f = om.compose(f, gens[x])
        return f
    def prod(w, rev):
        P = np.eye(3, dtype=complex)
        for x in (reversed(w) if rev else w): P = P @ Mt[x]
        return P
    test = ["LR", "LRR", "LrL", "RlRL", "LLRrL"[:4], "RRLlR"[:4], "LRLR"]
    order = {}
    for rev in (False, True):
        ok = 0
        for w in test:
            A = cp.restrict(om.M_of(word_auto(w)), TB); B = prod(w, rev)
            ok += int(np.allclose(A, B, atol=1e-8) or np.allclose(A, -B, atol=1e-8))
        order["reversed" if rev else "left_to_right"] = ok
    rev = order["reversed"] > order["left_to_right"]
    c = "aBAb"
    conj = lambda x: {"a": om.red(x + "a" + om.inv(x)), "b": om.red(x + "b" + om.inv(x))}
    named = {"id": {"a": "a", "b": "b"}, "conj(c)": conj(c), "conj(c^-1)": conj(om.inv(c)), "conj(a)": conj("a"),
             "conj(a^-1)": conj("A"), "conj(b)": conj("b"), "conj(b^-1)": conj("B"), "sign": {"a": "A", "b": "B"}}
    I2 = np.eye(2, dtype=int)
    res = {"+I": {}, "-I": {}}; lifts = {"+I": {}, "-I": {}}; mof = {"+I": {}, "-I": {}}; nonscalar = {"+I": 0, "-I": 0}
    autos_minus = {}
    stack = [("", I2)]
    while stack:
        w, h = stack.pop()
        if w:
            key = "+I" if np.array_equal(h, I2) else ("-I" if np.array_equal(h, -I2) else None)
            if key:
                f = word_auto(w)
                nm = next((k for k, g in named.items() if f == g), None)
                if nm is None and key == "-I":
                    sig = json.dumps(f, sort_keys=True); autos_minus[sig] = autos_minus.get(sig, 0) + 1; nm = "other(-I)"
                nm = nm or "other(+I)"
                res[key][nm] = res[key].get(nm, 0) + 1
                P = prod(w, rev); s = P[0, 0]
                if not np.allclose(P, s * np.eye(3), atol=1e-8): nonscalar[key] += 1
                else:
                    tag = f"{nm}: {round((cmath.phase(s) / (2 * math.pi)) % 1, 6) % 1:.6f} turn"
                    lifts[key][tag] = lifts[key].get(tag, 0) + 1
                A = cp.restrict(om.M_of(f), TB); sa = A[0, 0]
                if np.allclose(A, sa * np.eye(3), atol=1e-8):
                    tag = f"{nm}: {round((cmath.phase(sa) / (2 * math.pi)) % 1, 6) % 1:.6f} turn"
                    mof[key][tag] = mof[key].get(tag, 0) + 1
                else:
                    mof[key]["nonscalar"] = mof[key].get("nonscalar", 0) + 1
        if len(w) < nmax:
            for x in "LlRr":
                if w and inv[x] == w[-1]: continue
                stack.append((w + x, h @ H[x]))
    # the braid relation on the move matrices, and Delta's powers
    Lm, Rinv = Mt["L"], Mt["r"]
    braid = prod("LrL", rev) - prod("rLr", rev)
    D = prod("LrL", rev)
    eig = lambda A: sorted(round((cmath.phase(e) / (2 * math.pi)) % 1, 6) % 1 for e in np.linalg.eigvals(A))
    return {"max_length": nmax, "product_order": "reversed" if rev else "left_to_right", "order_test": order,
            "classified": res, "word_lift_scalars": lifts, "M_of_scalars": mof, "word_lift_nonscalar": nonscalar,
            "distinct_automorphisms_with_H1_minus_I": len(autos_minus),
            "braid_relation_on_move_matrices_max_defect": float(np.abs(braid).max()),
            "Delta_eigen_turns": eig(D), "Delta2_eigen_turns": eig(D @ D), "Delta4_eigen_turns": eig(np.linalg.matrix_power(D, 4))}


def parity_basis():
    Ta, Tb = (cp.restrict(om.M_of(x), TB) for x in ({"a": "a", "b": "abA"}, {"a": "baB", "b": "b"}))
    _, Pb = np.linalg.eig(Ta + 0.3719 * Tb); Pb, _ = np.linalg.qr(Pb)
    chars = [(int(round(float(np.real(np.vdot(Pb[:, i], Ta @ Pb[:, i]))))), int(round(float(np.real(np.vdot(Pb[:, i], Tb @ Pb[:, i])))))) for i in range(3)]
    return Pb, chars


def p3(rev):
    Mt = lift_matrices(); Pb, chars = parity_basis()
    def prod(w):
        P = np.eye(3, dtype=complex)
        for x in (reversed(w) if rev else w): P = P @ Mt[x]
        return P
    out = {"parity_lines": chars}
    for name, w in (("i: Delta^-1 = R L^-1 R", "RlR"), ("omega: L R^-1 (order 6 in SL2Z)", "Lr")):
        A = Pb.conj().T @ prod(w) @ Pb
        vals, vecs = np.linalg.eig(A)
        n = 1; P = A.copy()
        while not np.allclose(P, P[0, 0] * np.eye(3), atol=1e-8) and n < 100: P = P @ A; n += 1
        groups = {}
        for i, v in enumerate(vals):
            k = round((cmath.phase(v) / (2 * math.pi)) % 1, 6) % 1
            groups.setdefault(f"{k:.6f}", []).append(i)
        lines = {}
        for k, idx in groups.items():
            V = vecs[:, idx]; Q, _ = np.linalg.qr(V); Pj = Q @ Q.conj().T
            lines[k] = {"dim": len(idx), "weight_on_each_parity_line": [round(float(np.real(Pj[j, j])), 6) for j in range(3)]}
        # order of the element in GL(T), and modulo scalars
        m = 1; Q = A.copy()
        while not np.allclose(Q, np.eye(3), atol=1e-8) and m < 200: Q = Q @ A; m += 1
        out[name] = {"order_on_T": m, "order_mod_scalars": n, "eigenspaces": lines}
    return out


def p4(dmax=15):
    u2, u3, u4 = sp.symbols("u2 u3 u4"); I = sp.I
    AS = [[0, 0, -I], [0, -I, 0], [-I, 0, 0]]
    AT = [[I, 0, 0], [0, 0, 1], [0, 1, 0]]
    U = [u2, u3, u4]
    lin = lambda Am: [sum(Am[r][c] * U[c] for c in range(3)) for r in range(3)]
    Q = sp.Poly(u3 ** 2 - u2 ** 2 - u4 ** 2, u3, u2, u4)
    def nf(expr):
        _, r = sp.reduced(sp.expand(expr), [u3 ** 2 - u2 ** 2 - u4 ** 2], u3, u2, u4, order="lex"); return sp.expand(r)
    # numeric check that the 2d+1 normal monomials are independent forms on Gamma(4) (rank at random points)
    mp.mp.dps = 20
    pts = [mp.mpc(0.11 + 0.07 * j, 0.8 + 0.05 * j) for j in range(40)]
    def uval(t):
        F = F_direct(t, N=25); eta21 = (mp.exp(1j * mp.pi * t / 12) * mp.fprod(1 - mp.exp(2j * mp.pi * t * n) for n in range(1, 100))) ** 21
        return [complex(x / complex(eta21)) for x in F]
    UV = [uval(t) for t in pts]
    rows = []
    for d in range(1, dmax + 1, 2):
        mons = [u2 ** a * u4 ** (d - a) for a in range(d + 1)] + [u3 * u2 ** a * u4 ** (d - 1 - a) for a in range(d)]
        Mnum = np.array([[complex(sp.lambdify((u2, u3, u4), m)(*uv)) for m in mons] for uv in UV])
        rank_mons = int(np.linalg.matrix_rank(Mnum / np.abs(Mnum).max(axis=0), tol=1e-9))
        nmon = len(mons)
        cs = sp.symbols(f"c0:{3 * nmon}")
        P = [sum(cs[i * nmon + j] * mons[j] for j in range(nmon)) for i in range(3)]
        eqs = []
        for Am in (AS, AT):
            sub = dict(zip(U, lin(Am)))
            for r in range(3):
                lhs = P[r].subs(sub, simultaneous=True)
                rhs = sum(Am[r][c] * P[c] for c in range(3))
                e = nf(lhs - rhs)
                eqs += sp.Poly(e, u2, u3, u4).coeffs() if e != 0 else []
        Msys = sp.Matrix([[sp.expand(e).coeff(c) for c in cs] for e in eqs]) if eqs else sp.zeros(0, len(cs))
        null = Msys.nullspace()
        dimMd = len(null)
        # vanishing at the cusp: P(0, 1, 1) = 0 on the solution space
        if dimMd:
            B = sp.Matrix.hstack(*null)
            vals = sp.Matrix([[p.subs({u2: 0, u3: 1, u4: 1}) for p in [sum(B[i * nmon + j, col] * mons[j] for j in range(nmon)) for i in range(3)]] for col in range(dimMd)]).T
            dimk = dimMd - vals.rank()
        else:
            dimk = 0
        k = d - 1.5
        chi = round(w45.chi(k, rS, rT), 9) if w45.allowed(k, rS) else None
        rows.append({"d": d, "k": k, "normal_monomials": nmon, "numeric_rank_of_monomials": rank_mons, "dim_M_d(A)": dimMd,
                     "dim_M_k(rho_theta)": dimk, "chi_k_formula": chi})
    return rows


def p5():
    Pb, chars = parity_basis()
    Sa = om.compose(om.compose({"a": "ab", "b": "b"}, {"a": "a", "b": "Ab"}), {"a": "ab", "b": "b"})
    Mt = lift_matrices()
    TS = Mt["R"] @ Mt["l"] @ Mt["R"]
    to_par = lambda A: Pb.conj().T @ A @ Pb
    Sopts = {"S~": to_par(TS), "S~^-1": to_par(np.linalg.inv(TS))}
    Topts = {"L": to_par(Mt["L"]), "L^-1": to_par(Mt["l"]), "R": to_par(Mt["R"]), "R^-1": to_par(Mt["r"])}
    out = []
    for (sn, S), (tn, T) in itertools.product(Sopts.items(), Topts.items()):
        X = S @ S; Y = np.linalg.matrix_power(S @ T, 3)
        j = np.unravel_index(np.argmax(np.abs(Y)), Y.shape); r = X[j] / Y[j]
        prop = bool(np.allclose(X, r * Y, atol=1e-8))
        row = {"S": sn, "T": tn, "S2_proportional_to_ST3": prop}
        if prop:
            lam = r                                   # (lam S)^2 = (lam S T)^3  <=>  lam = X/Y
            S2 = lam * S
            row["lambda_turns"] = round((cmath.phase(lam) / (2 * math.pi)) % 1, 6) % 1
            row["S8_is_I"] = bool(np.allclose(np.linalg.matrix_power(S2, 8), np.eye(3), atol=1e-8))
            row["relations_hold"] = bool(np.allclose(S2 @ S2, np.linalg.matrix_power(S2 @ T, 3), atol=1e-8))
            row["T_eigen_turns"] = sorted(round((cmath.phase(e) / (2 * math.pi)) % 1, 6) % 1 for e in np.linalg.eigvals(T))
            row["chi_3_2"] = round(w45.chi(1.5, S2, T), 9) if w45.allowed(1.5, S2) else "not allowed"
        out.append(row)
    tw = []
    for jj in range(24):
        cS = cmath.exp(-1j * math.pi / 4 * jj); cT = cmath.exp(2j * math.pi * jj / 24)
        S2, T2 = cS * rS, cT * rT
        if w45.allowed(1.5, S2): tw.append({"j": jj, "chi_3_2": round(w45.chi(1.5, S2, T2), 9)})
    return {"completions_T_unrescaled": out, "theta_twists_allowed_at_3_2": tw}


def p6():
    L = {"a": "a", "b": "ab"}; R = {"a": "ab", "b": "b"}; Li = {"a": "a", "b": "Ab"}
    Sa = om.compose(om.compose(R, Li), R)
    Mt = lift_matrices(); prodS = Mt["R"] @ Mt["l"] @ Mt["R"]
    r3 = lambda M: cp.restrict(M, TB)
    sign = {}
    for nm, A, B in (("L", r3(om.M_of(L)), Mt["L"]), ("R", r3(om.M_of(R)), Mt["R"]), ("S~", r3(om.M_of(Sa)), prodS)):
        sign[nm] = "+" if np.allclose(A, B, atol=1e-9) else ("-" if np.allclose(A, -B, atol=1e-9) else "neither")
    Pb, chars = parity_basis(); to_par = lambda A: Pb.conj().T @ A @ Pb
    BS, BT = to_par(np.linalg.inv(prodS)), to_par(np.linalg.inv(Mt["L"]))
    A1 = np.kron(np.eye(3), rS.T) - np.kron(BS, np.eye(3)); A2 = np.kron(np.eye(3), rT.T) - np.kron(BT, np.eye(3))
    _, s, Vh = np.linalg.svd(np.vstack([A1, A2])); M = Vh[-1].conj().reshape(3, 3)
    return {"M_of_sign_vs_move_product": sign, "H1_of_S~": om.h1(Sa).tolist(), "H1_of_L": om.h1(L).tolist(),
            "relations_exact_unrescaled": bool(np.allclose(BS @ BS, np.linalg.matrix_power(BS @ BT, 3), atol=1e-9)),
            "S8_is_I": bool(np.allclose(np.linalg.matrix_power(BS, 8), np.eye(3), atol=1e-9)),
            "intertwiner_to_rho_theta_smallest_singular_value": float(s[-1]), "intertwiner_abs_det": float(abs(np.linalg.det(M))),
            "monomial": bool(all(np.sum(np.abs(M[:, j]) > 1e-6) == 1 for j in range(3))),
            "theta2_to": chars[int(np.argmax(np.abs(M[:, 0])))], "theta3_to": chars[int(np.argmax(np.abs(M[:, 1])))],
            "theta4_to": chars[int(np.argmax(np.abs(M[:, 2])))],
            "allowed_3_2": bool(w45.allowed(1.5, BS)), "chi_3_2": round(w45.chi(1.5, BS, BT), 9), "chi_23_2": round(w45.chi(11.5, BS, BT), 9),
            "dual_allowed_3_2": bool(w45.allowed(1.5, BS.conj()))}


def main():
    out = {"P1": p1()}
    out["P2"] = p2(int(os.environ.get("B1634_N", "12")))
    out["P3"] = p3(out["P2"]["product_order"] == "reversed")
    out["P4"] = p4()
    out["P5"] = p5()
    out["P6"] = p6()
    json.dump(out, open(HERE / "post_seal_w50.json", "w"), indent=1, default=str)
    print(json.dumps(out, indent=1, default=str)[:9000])


if __name__ == "__main__":
    main()
