"""
rootsys.py -- root systems from scratch, exact rational arithmetic.

Everything is built here; nothing is imported from a Lie-theory library.
Roots live in Q^n as tuples of Fractions. Inner product is the standard
Euclidean one on Q^n. Reflections s_a(x) = x - 2(x,a)/(a,a) * a.
"""
from fractions import Fraction as F
from collections import deque
from itertools import combinations


# ---------------------------------------------------------------- basics
def vec(*xs):
    return tuple(F(x) for x in xs)


def ip(a, b):
    return sum(x * y for x, y in zip(a, b))


def add(a, b):
    return tuple(x + y for x, y in zip(a, b))


def neg(a):
    return tuple(-x for x in a)


def refl(x, a):
    c = 2 * ip(x, a) / ip(a, a)
    return tuple(xi - c * ai for xi, ai in zip(x, a))


# ------------------------------------------------- root system generation
def generate_roots(simple):
    """Closure of the simple roots (and negatives) under the simple
    reflections.  Pure BFS: no table of roots is assumed."""
    seen = set()
    q = deque()
    for a in simple:
        for r in (a, neg(a)):
            if r not in seen:
                seen.add(r)
                q.append(r)
    while q:
        x = q.popleft()
        for a in simple:
            y = refl(x, a)
            if y not in seen:
                seen.add(y)
                q.append(y)
    return sorted(seen)


def cartan_matrix(simple):
    n = len(simple)
    return [[2 * ip(simple[i], simple[j]) / ip(simple[j], simple[j])
             for j in range(n)] for i in range(n)]


def dynkin_edges(simple):
    """Edges (i,j,n_ij*n_ji) of the Coxeter/Dynkin graph, from the Cartan."""
    A = cartan_matrix(simple)
    n = len(simple)
    out = []
    for i in range(n):
        for j in range(i + 1, n):
            p = A[i][j] * A[j][i]
            if p != 0:
                out.append((i, j, p))
    return out


def is_closed_under_reflections(roots, simple):
    S = set(roots)
    for x in roots:
        for a in simple:
            if refl(x, a) not in S:
                return False
    return True


def rank_of(vectors):
    """Exact rank over Q by fraction-free Gaussian elimination."""
    M = [list(v) for v in vectors]
    if not M:
        return 0
    rows, cols = len(M), len(M[0])
    r = 0
    for c in range(cols):
        piv = None
        for i in range(r, rows):
            if M[i][c] != 0:
                piv = i
                break
        if piv is None:
            continue
        M[r], M[piv] = M[piv], M[r]
        for i in range(rows):
            if i != r and M[i][c] != 0:
                f = M[i][c] / M[r][c]
                M[i] = [a - f * b for a, b in zip(M[i], M[r])]
        r += 1
        if r == rows:
            break
    return r


# --------------------------------------------------- Weyl group as perms
def simple_reflection_perms(roots, simple):
    idx = {r: i for i, r in enumerate(roots)}
    perms = []
    for a in simple:
        perms.append(tuple(idx[refl(r, a)] for r in roots))
    return perms


def compose(p, q):
    """(p after q)[i] = p[q[i]]"""
    return tuple(p[i] for i in q)


def weyl_group_order(roots, simple, cap=10 ** 7):
    """BFS closure of the permutation group generated by the simple
    reflections acting on the set of roots.  Returns (order, group)."""
    gens = simple_reflection_perms(roots, simple)
    n = len(roots)
    ident = tuple(range(n))
    seen = {ident}
    q = deque([ident])
    while q:
        g = q.popleft()
        for s in gens:
            h = compose(s, g)
            if h not in seen:
                seen.add(h)
                q.append(h)
                if len(seen) > cap:
                    raise RuntimeError("group too big")
    return len(seen), seen


# ------------------------------------------------------- A2 subsystems
def a2_subsystems(roots):
    """All subsets of the root system that form a closed A2 subsystem.

    CONVENTION: returned as frozensets of root INDICES, each of size 6
    ({+-a, +-b, +-(a+b)}).  Two generating pairs giving the same 6-element
    set count ONCE.  Verified afterwards: 6 distinct roots, closed under
    negation, rank 2, closed under addition inside the ambient system, all
    six of equal length, and pairwise angles are those of A2.
    """
    idx = {r: i for i, r in enumerate(roots)}
    R = set(roots)
    found = set()
    n = len(roots)
    for i in range(n):
        a = roots[i]
        la = ip(a, a)
        for j in range(n):
            if i == j:
                continue
            b = roots[j]
            if ip(b, b) != la:
                continue
            # angle 120 degrees  <=>  (a,b) = -|a|^2/2
            if ip(a, b) != -la / 2:
                continue
            c = add(a, b)
            if c not in R:
                continue
            S = (a, neg(a), b, neg(b), c, neg(c))
            if len(set(S)) != 6:
                continue
            found.add(frozenset(idx[s] for s in S))
    # verification pass
    good = set()
    for fs in found:
        S = [roots[k] for k in fs]
        assert len(S) == 6
        lens = {ip(s, s) for s in S}
        if len(lens) != 1:
            continue
        if not all(neg(s) in set(S) for s in S):
            continue
        if rank_of(S) != 2:
            continue
        closed = True
        Sset = set(S)
        for x in S:
            for y in S:
                z = add(x, y)
                if z in R and z not in Sset:
                    closed = False
        if not closed:
            continue
        good.add(fs)
    return sorted(good, key=lambda s: sorted(s))


def a2_a1_subsystems(roots, a2list):
    """Closed subsystems A2 (+) A1 with the A1 orthogonal to the A2.

    CONVENTION: frozenset of the 8 root indices {A2's six} U {+-c}.
    Closure under addition is re-verified explicitly."""
    idx = {r: i for i, r in enumerate(roots)}
    R = set(roots)
    out = set()
    for fs in a2list:
        S = [roots[k] for k in fs]
        for j, c in enumerate(roots):
            if any(ip(c, s) != 0 for s in S):
                continue
            T = S + [c, neg(c)]
            Tset = set(T)
            if len(Tset) != 8:
                continue
            ok = True
            for x in T:
                for y in T:
                    z = add(x, y)
                    if z in R and z not in Tset:
                        ok = False
            if ok:
                out.add(frozenset(idx[t] for t in T))
    return sorted(out, key=lambda s: sorted(s))


# ------------------------------------------------------- orbit machinery
def orbits_of_subsets(subsets, gens):
    """Partition a list of frozensets of root-indices into orbits under the
    group generated by `gens` (permutations of the root indices)."""
    universe = set(subsets)
    remaining = set(subsets)
    orbits = []
    while remaining:
        start = next(iter(remaining))
        orb = {start}
        q = deque([start])
        while q:
            s = q.popleft()
            for g in gens:
                t = frozenset(g[k] for k in s)
                if t not in orb:
                    assert t in universe, "orbit left the enumerated set!"
                    orb.add(t)
                    q.append(t)
        orbits.append(orb)
        remaining -= orb
    return orbits


def setwise_stabilizer_order(subset, group):
    n = 0
    for g in group:
        if frozenset(g[k] for k in subset) == subset:
            n += 1
    return n


# ------------------------------------------------------- simple systems
def E6_simple():
    h = F(1, 2)
    a1 = (h, -h, -h, -h, -h, -h, -h, h)
    a2 = vec(1, 1, 0, 0, 0, 0, 0, 0)
    a3 = vec(-1, 1, 0, 0, 0, 0, 0, 0)
    a4 = vec(0, -1, 1, 0, 0, 0, 0, 0)
    a5 = vec(0, 0, -1, 1, 0, 0, 0, 0)
    a6 = vec(0, 0, 0, -1, 1, 0, 0, 0)
    return [a1, a2, a3, a4, a5, a6]


def F4_simple():
    h = F(1, 2)
    return [vec(0, 1, -1, 0), vec(0, 0, 1, -1), vec(0, 0, 0, 1),
            (h, -h, -h, -h)]


def D4_simple():
    return [vec(1, -1, 0, 0), vec(0, 1, -1, 0), vec(0, 0, 1, -1),
            vec(0, 0, 1, 1)]


def A3_simple():
    return [vec(1, -1, 0, 0), vec(0, 1, -1, 0), vec(0, 0, 1, -1)]


def B3_simple():
    return [vec(1, -1, 0), vec(0, 1, -1), vec(0, 0, 1)]
