"""Construct the hypercharge direction explicitly instead of searching:
find an A4 (su(5)) subsystem of E6 whose Dynkin chain is
      b1 - b2 - delta - gamma
with (b1,b2) the colour A2 and gamma the weak A1.  Then Y is the unique
vector in the A4 span with (Y,b1)=(Y,b2)=(Y,gamma)=0, (Y,delta)=1.
This is the su(5) hypercharge coweight, built from scratch.
"""
from fractions import Fraction as F
from rootsys import *
from collections import Counter, defaultdict
from itertools import product
import json

simple = E6_simple()
roots = generate_roots(simple)
idx = {r: i for i, r in enumerate(roots)}
gens = simple_reflection_perms(roots, simple)
order, group = weyl_group_order(roots, simple)
A = cartan_matrix(simple)


def solve_exact(M, b):
    n = len(M)
    Mx = [list(map(F, M[i])) + [F(b[i])] for i in range(n)]
    for c in range(n):
        piv = next(i for i in range(c, n) if Mx[i][c] != 0)
        Mx[c], Mx[piv] = Mx[piv], Mx[c]
        pv = Mx[c][c]
        Mx[c] = [x / pv for x in Mx[c]]
        for i in range(n):
            if i != c and Mx[i][c] != 0:
                f = Mx[i][c]
                Mx[i] = [x - f * y for x, y in zip(Mx[i], Mx[c])]
    return [Mx[i][n] for i in range(n)]


def from_simple_coords(c):
    out = [F(0)] * 8
    for ck, a in zip(c, simple):
        out = [x + ck * y for x, y in zip(out, a)]
    return tuple(out)


def simple_coeffs(r):
    return solve_exact(A, [ip(r, simple[j]) for j in range(6)])


omegas = [from_simple_coords(solve_exact(A, [1 if k == i else 0 for k in range(6)]))
          for i in range(6)]


def weight_orbit(w):
    seen, q = {w}, [w]
    while q:
        x = q.pop()
        for a in simple:
            y = refl(x, a)
            if y not in seen:
                seen.add(y)
                q.append(y)
    return sorted(seen)


W27 = weight_orbit(omegas[0])

A2 = a2_subsystems(roots)
A2A1 = a2_a1_subsystems(roots, A2)
rep = A2A1[0]
a2part = [g for g in A2 if g <= rep][0]
a2roots = [roots[k] for k in a2part]
a1roots = [roots[k] for k in rep if k not in a2part]
b1 = a2roots[0]
b2 = next(r for r in a2roots if ip(b1, r) == -1)
gam = a1roots[0]
Srts = a2roots + a1roots
stab = [g for g in group if frozenset(g[k] for k in rep) == rep]

# --- find delta ----------------------------------------------------------
deltas = [d for d in roots
          if ip(d, b1) == 0 and ip(d, b2) == -1 and ip(d, gam) == -1]
print("roots delta completing b1-b2-delta-gamma to an A4 chain:", len(deltas))
assert deltas
delta = deltas[0]

# verify the A4: generate the subsystem from {b1,b2,delta,gam}
sub = generate_roots([b1, b2, delta, gam])
print("subsystem generated by the four: %d roots, rank %d"
      % (len(sub), rank_of(sub)), "(A4 has 20 roots, rank 4)")
print("is it a closed subsystem of E6:",
      all(x in set(roots) for x in sub))
Asub = cartan_matrix([b1, b2, delta, gam])
print("its Cartan matrix:", [[int(x) for x in r] for r in Asub])

# --- the hypercharge coweight -------------------------------------------
# Y in span(A4), (Y,b1)=(Y,b2)=(Y,gam)=0, (Y,delta)=1
basis = [b1, b2, delta, gam]
G = [[ip(u, v) for v in basis] for u in basis]
coef = solve_exact(G, [0, 0, 1, 0])
Y = [F(0)] * 8
for c, u in zip(coef, basis):
    Y = [x + c * y for x, y in zip(Y, u)]
Y = tuple(Y)
print("Y (in the A4 simple-root basis b1,b2,delta,gam):", [str(c) for c in coef])
print("checks: (Y,b1)=%s (Y,b2)=%s (Y,gam)=%s (Y,delta)=%s"
      % (ip(Y, b1), ip(Y, b2), ip(Y, gam), ip(Y, delta)))
print("Y in fundamental-coweight (Dynkin) coordinates of E6:",
      [str(ip(Y, a)) for a in simple])

# --- branching of the 27 under (A2, A1, Y) -------------------------------
def su3_orbit(lab):
    seen, q = {lab}, [lab]
    while q:
        a, b = q.pop()
        for y in ((-a, a + b), (a + b, -b)):
            if y not in seen:
                seen.add(y)
                q.append(y)
    return seen


LIB3 = {(0, 0): {(0, 0)}, (1, 0): su3_orbit((1, 0)), (0, 1): su3_orbit((0, 1))}
LIB2 = {0: [0], 1: [1, -1]}
NAME3 = {(0, 0): "1", (1, 0): "3", (0, 1): "3b"}


def branch(Y, weights=W27):
    bylevel = defaultdict(list)
    for w in weights:
        bylevel[ip(w, Y)].append((ip(w, b1), ip(w, b2), ip(w, gam)))
    out = []
    for y, ws in bylevel.items():
        M = Counter(ws)
        while sum(M.values()):
            dom = [t for t in M if t[0] >= 0 and t[1] >= 0 and t[2] >= 0]
            if not dom:
                return None
            hw = max(dom, key=lambda t: (t[0] + t[1] + t[2], t))
            l3, l2 = (hw[0], hw[1]), hw[2]
            if l3 not in LIB3 or l2 not in LIB2:
                return None
            for p in LIB3[l3]:
                for q in LIB2[l2]:
                    t = (p[0], p[1], q)
                    if M[t] <= 0:
                        return None
                    M[t] -= 1
                    if M[t] == 0:
                        del M[t]
            out.append((NAME3[l3], int(l2) + 1, y))
    return sorted(out, key=lambda t: (t[2], t[0], t[1]))


sig = branch(Y)
print()
print("=== BRANCHING OF THE 27 UNDER su(3)+su(2)+u(1)_Y ===")
q = [c for a, b, c in sig if b == 2 and a in ("3", "3b")]
print("charge of the colour-triplet weak-doublet piece:", q)
lam = F(1, 6) / q[0] if q and q[0] != 0 else F(1)
for a, b, c in sig:
    print("   (%-2s, %d)_Y = %s   [normalised: %s]" % (a, b, c, lam * c))
tot = sum({"1": 1, "3": 3, "3b": 3}[a] * b for a, b, c in sig)
print("total dimension:", tot)

SM = sorted([("3", 2, F(1, 6)), ("3b", 1, F(-2, 3)), ("1", 1, F(1)),
             ("3b", 1, F(1, 3)), ("1", 2, F(-1, 2)),
             ("3b", 1, F(1, 3)), ("1", 2, F(-1, 2)),
             ("3", 1, F(-1, 3)), ("1", 2, F(1, 2)),
             ("1", 1, F(0)), ("1", 1, F(0))])
flip = {"3": "3b", "3b": "3", "1": "1"}
matched = False
for f in (False, True):
    for sgn in (1, -1):
        t = sorted((flip[a] if f else a, b, sgn * lam * c) for a, b, c in sig)
        if t == SM:
            matched = True
print("MATCHES the Standard-Model hypercharge pattern exactly:", matched)

# --- where does Y sit relative to the search box? -------------------------
n = [ip(Y, a) for a in simple]
den = 1
for x in n:
    den = den * x.denominator // __import__("math").gcd(den, x.denominator)
nn = [int(x * den) for x in n]
from math import gcd
g = 0
for x in nn:
    g = gcd(g, abs(x))
nn = [x // g for x in nn]
print("primitive integral coweight coords of the hypercharge line:", nn,
      "-> max |n_i| =", max(abs(x) for x in nn))

# --- how many W-classes give the SM pattern? -----------------------------
# act on Y by the stabiliser of the A2+A1 and see how many distinct LINES
def lin_of_perm(g):
    images = [roots[g[idx[a]]] for a in simple]

    def act(v):
        c = simple_coeffs(v)
        out = [F(0)] * 8
        for ck, im in zip(c, images):
            out = [x + ck * y for x, y in zip(out, im)]
        return tuple(out)
    return act


stab_lin = [lin_of_perm(g) for g in stab]
orb = set()
for act in stab_lin:
    w = act(Y)
    orb.add(min(w, tuple(-x for x in w)))
print()
print("Stab_W(A2+A1) orbit of the hypercharge LINE has size:", len(orb))
print("stabiliser of the line inside Stab_W(A2+A1):",
      len(stab) // len(orb) if len(orb) else 0)

# every line in that orbit gives the same branching (sanity)
print("all lines in the orbit give the same branching up to sign:",
      len({tuple(sorted((a, b, abs(c)) for a, b, c in branch(v))) for v in orb}) == 1)

# --- now: are there OTHER, non-conjugate SM-like lines? ------------------
# enumerate primitive integral coweight lines orthogonal to the A2+A1 in a
# box big enough to contain the hypercharge line, test the SM pattern
conds = [[int(x) for x in simple_coeffs(r)] for r in [b1, b2, gam]]
NBOX = max(6, max(abs(x) for x in nn))
cands = []
for m in product(range(-NBOX, NBOX + 1), repeat=6):
    if any(sum(ci * mi for ci, mi in zip(c, m)) != 0 for c in conds):
        continue
    if all(x == 0 for x in m):
        continue
    g = 0
    for x in m:
        g = gcd(g, abs(x))
    if g != 1:
        continue
    if m > tuple(-x for x in m):
        continue
    cands.append(m)
print()
print("box |n_i| <= %d : primitive coweight LINES orthogonal to the A2+A1: %d"
      % (NBOX, len(cands)))


def vec_of(m):
    v = [F(0)] * 8
    for mi, w in zip(m, omegas):
        v = [x + mi * y for x, y in zip(v, w)]
    return tuple(v)


def is_sm(v):
    s = branch(v)
    if s is None:
        return False
    qq = [c for a, b, c in s if b == 2 and a in ("3", "3b")]
    if len(qq) != 1 or qq[0] == 0:
        return False
    lm = F(1, 6) / qq[0]
    for f in (False, True):
        for sgn in (1, -1):
            t = sorted((flip[a] if f else a, b, sgn * lm * c) for a, b, c in s)
            if t == SM:
                return True
    return False


smlines = [m for m in cands if is_sm(vec_of(m))]
print("of these, lines whose 27 branches exactly as the SM:", len(smlines))
# group them into Stab-orbits
vecs = {m: vec_of(m) for m in smlines}
key = {}
for m in smlines:
    key[min(vecs[m], tuple(-x for x in vecs[m]))] = m
parent = {m: m for m in smlines}


def find(x):
    while parent[x] != x:
        parent[x] = parent[parent[x]]
        x = parent[x]
    return x


for m in smlines:
    for act in stab_lin:
        w = act(vecs[m])
        k = min(w, tuple(-x for x in w))
        if k in key:
            a, b = find(m), find(key[k])
            if a != b:
                parent[a] = b
cls = set(find(m) for m in smlines)
print("they fall into", len(cls), "Stab_W(A2+A1)-orbit(s)")
print("=> at least", len(cls), "W(E6)-conjugacy class(es) of regular",
      "su(3)+su(2)+u(1) subalgebras with exactly the SM branching of the 27")
for c in sorted(cls):
    members = [m for m in smlines if find(m) == c]
    print("   orbit of size", len(members), " representative n =", c)
