#!/usr/bin/env python3
"""GC-1 part 3: the commensurability class of the 35 non-regular members.

Criterion (Maclachlan-Reid, non-cocompact case): a cusped finite-volume
Kleinian group is arithmetic iff its invariant trace field is imaginary
quadratic AND all traces are algebraic integers; an arithmetic non-cocompact
group with invariant trace field Q(sqrt-3) is commensurable with the Bianchi
group PSL2(O_{-3}) (one commensurability class per field).

Numeric tests per member (ManifoldHP, ~60 significant digits; mpmath 50 dps):
  (a) every tetrahedron shape z lies in Q(sqrt-3): PSLQ finds small integer
      relations Re(z) = p/r, Im(z) = q*sqrt(3)/r  (shape field = invariant
      trace field for cusped manifolds, Neumann-Reid);
  (b) traces of the holonomy generators, all pairwise products, and all
      triple products are Eisenstein integers t = (m + n*sqrt(-3))/2 with
      m,n in Z, m = n mod 2. The trace ring of a finitely generated group is
      generated by traces of products of DISTINCT generators (Maclachlan-Reid
      3.5.2/3.5.3), so integrality on these words certifies ALL traces.
"""
import json
import itertools
import snappy
import mpmath as mp

mp.mp.dps = 50
TOL = mp.mpf(10) ** -20
SQRT3 = mp.sqrt(3)

fam = json.load(open(str(__import__("pathlib").Path(__file__).resolve().parents[3] / "frontier/B1186_family_is_112/verification/family_census.json")))
nonreg = sorted(set(fam["members_B"]) - set(fam["members_A"]))
assert len(nonreg) == 35

def to_mp(x):
    return mp.mpf(str(x).replace(" ", ""))

def shape_in_Qsqrt3(z):
    """z = (p + q*sqrt(-3))/r with small integers?  PSLQ on each coordinate."""
    def rat_fit(x):
        if abs(x) < TOL:
            return (0, 1)
        rel = mp.pslq([x, mp.mpf(1)], tol=TOL, maxcoeff=10**12)
        if rel is None:
            return None
        a, b = rel           # a*x + b = 0 -> x = -b/a
        return (-b, a)
    fr = rat_fit(mp.re(z))
    fi = rat_fit(mp.im(z) / SQRT3)
    if fr is None or fi is None:
        return None
    return fr + fi

def eisenstein_check(t):
    """t = (m + n*sqrt(-3))/2, m,n integers, m=n (mod 2)?"""
    m = 2 * mp.re(t)
    n = 2 * mp.im(t) / SQRT3
    mi, ni = mp.nint(m), mp.nint(n)
    if abs(m - mi) > TOL or abs(n - ni) > TOL:
        return None
    mi, ni = int(mi), int(ni)
    if (mi - ni) % 2 != 0:
        return False
    return (mi, ni)

results, shape_fails, trace_fails, parity_fails = [], [], [], []
for name in nonreg:
    M = snappy.ManifoldHP(name)
    # (a) shapes
    bad_shape = []
    for s in M.tetrahedra_shapes("rect"):
        z = mp.mpc(to_mp(s.real()), to_mp(s.imag()))
        fit = shape_in_Qsqrt3(z)
        if fit is None:
            bad_shape.append(complex(z))
    # (b) traces
    G = M.fundamental_group()
    gens = G.generators()
    words = list(gens)
    words += ["".join(p) for p in itertools.permutations(gens, 2)]
    words += ["".join(p) for p in itertools.permutations(gens, 3)]
    bad_trace, bad_parity, max_dev = [], [], mp.mpf(0)
    for w in words:
        A = G.SL2C(w)
        t = mp.mpc(to_mp(A[0, 0].real()), to_mp(A[0, 0].imag())) + \
            mp.mpc(to_mp(A[1, 1].real()), to_mp(A[1, 1].imag()))
        chk = eisenstein_check(t)
        if chk is None:
            bad_trace.append((w, complex(t)))
        elif chk is False:
            bad_parity.append((w, complex(t)))
        else:
            m2, n2 = chk
            dev = max(abs(2 * mp.re(t) - m2), abs(2 * mp.im(t) / SQRT3 - n2))
            max_dev = max(max_dev, dev)
    results.append({"name": name, "num_gens": len(gens), "words_tested": len(words),
                    "shapes_ok": not bad_shape, "traces_integral": not (bad_trace or bad_parity),
                    "max_int_deviation": float(max_dev)})
    if bad_shape:
        shape_fails.append((name, bad_shape[:2]))
    if bad_trace:
        trace_fails.append((name, bad_trace[:3]))
    if bad_parity:
        parity_fails.append((name, bad_parity[:3]))

n_ok = sum(1 for r in results if r["shapes_ok"] and r["traces_integral"])
overall_max_dev = max(r["max_int_deviation"] for r in results)
total_words = sum(r["words_tested"] for r in results)
print(f"NON-REGULAR MEMBERS TESTED: {len(results)} / 35")
print(f"shape-field Q(sqrt-3) fits: {sum(1 for r in results if r['shapes_ok'])}/35;  failures: {shape_fails if shape_fails else 'NONE'}")
print(f"integral (Eisenstein) traces: {sum(1 for r in results if r['traces_integral'])}/35 over {total_words} words;  non-integral: {trace_fails if trace_fails else 'NONE'};  parity fails: {parity_fails if parity_fails else 'NONE'}")
print(f"max deviation of 2Re(t), 2Im(t)/sqrt3 from integers over ALL words: {float(overall_max_dev):.3e} (tol {float(TOL):.0e})")
print(f"BOTH criteria: {n_ok}/35")

# instrument two-sided control: a manifold whose traces are NOT in Q(sqrt-3)
for ctl in ["m015", "m016"]:
    M = snappy.ManifoldHP(ctl)
    G = M.fundamental_group()
    bad = 0
    for w in G.generators():
        A = G.SL2C(w)
        t = mp.mpc(to_mp(A[0, 0].real()), to_mp(A[0, 0].imag())) + \
            mp.mpc(to_mp(A[1, 1].real()), to_mp(A[1, 1].imag()))
        if eisenstein_check(t) in (None, False):
            bad += 1
    print(f"CONTROL {ctl}: {bad}/{len(G.generators())} generator traces NOT Eisenstein (instrument bites)")

json.dump(results, open("SCRATCH/b1188/cells/gc1_traces.json", "w"), indent=1)
print("DONE")
