#!/usr/bin/env python3
"""B1366 -- THE SIGN IS E6'S: the Standard Model embeds in E6 in one way up to conjugacy, and in every reading the 27's two
Standard-Model singlets form a doublet of the SM's centraliser SU(2)_beta and carry the same charge under the remaining U(1)'.

Computed on the E6 root system (SO(10) x U(1) coordinates, B1364/B1365):
  (1) the A2 root subsystems of E6 and their Weyl orbits (su(3)_c must be a root A2: the branching 27 -> 3x3 + 3x3bar + 9x1 has
      embedding index 1);
  (2) for su(3)_c fixed, its centraliser's root system (A2 x A2) and the root A1's inside it that give 27 -> 6x2 + 15x1 (su(2)_L,
      index 1), and the Weyl orbits of the pairs (A2, A1);
  (3) the hypercharges: every Y in the Cartan orthogonal to su(3)_c + su(2)_L giving the 27 the Standard Model's multiset of
      (SU(3), SU(2), Y) representations -- a generation, a Higgs pair, one exotic triplet pair, two singlets;
  (4) for each such Y: the roots commuting with the SM and Y-neutral (+-beta), the direction gamma orthogonal to the SM Cartan, Y and
      beta, the two SM singlets' beta and gamma charges, and the 78's SM singlets' gamma charges;
  (5) the conclusion: for every embedding, the SM singlets of the 27 are an SU(2)_beta doublet with equal gamma, the 78's SM singlets
      have gamma = 0 -- so the U(1)' D-term has one sign on every E6-charged SM singlet of a theory built from 27s and 78s.
Usage: python3 sm_in_e6.py"""
import itertools
from fractions import Fraction as Fr
from collections import Counter, deque
import sympy

def roots_e6():
    R = []
    for i in range(5):
        for j in range(i + 1, 5):
            for si in (1, -1):
                for sj in (1, -1):
                    v = [Fr(0)] * 5; v[i] = Fr(si); v[j] = Fr(sj); R.append((tuple(v), Fr(0)))
    for signs in itertools.product((1, -1), repeat=5):
        if signs.count(-1) % 2 == 0:
            w = tuple(Fr(s, 2) for s in signs); R.append((w, Fr(1))); R.append((tuple(-x for x in w), Fr(-1)))
    return R
def dot(a, b): return sum(x * y for x, y in zip(a[0], b[0])) + Fr(3, 4) * a[1] * b[1]
def neg(r): return (tuple(-x for x in r[0]), -r[1])
def add(r, s): return (tuple(x + y for x, y in zip(r[0], s[0])), r[1] + s[1])
def scale(c, r): return (tuple(c * x for x in r[0]), c * r[1])
R = roots_e6(); Rset = set(R); assert len(R) == 72
W27 = []
for signs in itertools.product((1, -1), repeat=5):
    if signs.count(-1) % 2 == 1: W27.append((tuple(Fr(s, 2) for s in signs), Fr(1, 3)))
for k in range(5):
    for s in (1, -1):
        v = [Fr(0)] * 5; v[k] = Fr(s); W27.append((tuple(v), Fr(-2, 3)))
W27.append((tuple([Fr(0)] * 5), Fr(4, 3)))
assert len(W27) == 27 and all(dot(w, r).denominator == 1 for w in W27 for r in R)
# simple roots (a base) and reflections
def reflect(r, a): return add(r, scale(-dot(r, a), a))     # s_a(r) = r - (r.a) a   (roots have norm 2)
pos = [r for r in R if (r[1] > 0) or (r[1] == 0 and [x for x in r[0] if x != 0][0] > 0)]
assert len(pos) == 36
simple = [r for r in pos if not any((add(r, neg(s)) in Rset and add(r, neg(s)) in set(pos)) for s in pos if s != r)]
simple = [r for r in pos if all(add(r, neg(s)) not in set(pos) for s in pos if s != r)]
assert len(simple) == 6, len(simple)
print(f"E6: 72 roots, a base of {len(simple)} simple roots found")

# ---------------------------------------------------------------- (1) A2 root subsystems and their Weyl orbits
def a2_of(a, b): return frozenset([a, neg(a), b, neg(b), add(a, b), neg(add(a, b))])
A2s = set()
for a in R:
    for b in R:
        if dot(a, b) == -1: A2s.add(a2_of(a, b))
A2s = list(A2s)
def w_orbits(objs, act):
    """orbits of the Weyl group (generated by simple reflections) on a family of objects"""
    remaining = set(objs); orbits = []
    while remaining:
        x0 = next(iter(remaining)); orb = {x0}; q = deque([x0])
        while q:
            x = q.popleft()
            for s in simple:
                y = act(x, s)
                if y not in orb: orb.add(y); q.append(y)
        orbits.append(orb); remaining -= orb
    return orbits
act_set = lambda S, s: frozenset(reflect(r, s) for r in S)
orbA2 = w_orbits(A2s, act_set)
print(f"(1) A2 root subsystems of E6: {len(A2s)}; Weyl orbits: {len(orbA2)} (sizes {[len(o) for o in orbA2]})")

# ---------------------------------------------------------------- (2) su(3)_c fixed: centraliser, su(2)_L candidates, orbits of pairs
def sm_branch27(S3, A1):
    """multiset of (dim SU(3) rep, dim SU(2) rep) of the 27 under a root A2 (S3) and a root A1 (A1): via highest-weight counting"""
    pos3 = sorted(S3, key=lambda r: (r[1], r[0]))[3:]      # three of the six: use a positive system: those with positive pairing with a regular vector
    # regular vector inside span(S3): rho = sum of a positive system; choose positive roots by sign of pairing with a generic combination
    a, b = [r for r in S3 if True][:2]
    # find two simple roots of the A2: a, b with a.b = -1
    pairs = [(x, y) for x in S3 for y in S3 if dot(x, y) == -1]
    a, b = pairs[0]; c = add(a, b); P3 = [a, b, c]
    # weights of 27 restricted to the A2 Cartan: Dynkin labels (w.a, w.b); a weight is highest for A2 if w + a and w + b are not weights
    Wset = set(W27)
    def labels(w): return (dot(w, a), dot(w, b))
    def a1label(w): return dot(w, A1)
    hw = [w for w in W27 if add(w, a) not in Wset and add(w, b) not in Wset]
    return hw, labels, a1label
S3 = next(iter(orbA2[0]))
cent = [r for r in R if all(dot(r, s) == 0 for s in S3)]
centA2 = set()
for a in cent:
    for b in cent:
        if dot(a, b) == -1: centA2.add(a2_of(a, b))
print(f"(2) centraliser of su(3)_c: {len(cent)} roots forming {len(centA2)} A2's (A2 x A2: the other two of the A2^3)")
# su(2)_L: a root A1 in the centraliser with the 27 -> 6 x 2 + 15 x 1
def a1_content(A1):
    cnt = Counter()
    for w in W27:
        cnt[dot(w, A1)] += 1
    return dict(cnt)
cands = [r for r in cent if r[1] > 0 or (r[1] == 0 and [x for x in r[0] if x != 0][0] > 0)]
good = [r for r in cands if a1_content(r) == {Fr(1): 6, Fr(-1): 6, Fr(0): 15}]
print(f"    positive roots of the centraliser: {len(cands)}; those with 27 -> 6 x 2 + 15 x 1 (a root su(2)_L): {len(good)} (all of them: {len(good) == len(cands)})")
pairs = set()
for S in A2s:
    for r in R:
        if all(dot(r, s) == 0 for s in S): pairs.add((S, frozenset([r, neg(r)])))
act_pair = lambda p, s: (frozenset(reflect(r, s) for r in p[0]), frozenset(reflect(r, s) for r in p[1]))
orb_pairs = w_orbits(list(pairs), act_pair)
print(f"    pairs (A2, A1 commuting): {len(pairs)}; Weyl orbits: {len(orb_pairs)} -> su(3)_c + su(2)_L sits in E6 in {len(orb_pairs)} way(s) up to conjugacy")

# ---------------------------------------------------------------- (3) the hypercharges
A1 = good[0]
sm_roots = list(S3) + [A1, neg(A1)]
def su3_labels(w):
    pairs_ = [(x, y) for x in S3 for y in S3 if dot(x, y) == -1]; a, b = pairs_[0]
    return (dot(w, a), dot(w, b))
def rep_type(w, Y):
    """(SU(3) content, SU(2) content, Y) of the irreducible piece containing w: SU(3) by the orbit size under its Weyl group is messy;
    use the weight's pairings: colour-charged iff some su(3)_c root pairs non-trivially; weak-charged iff A1 pairs non-trivially."""
    col = any(dot(w, s) != 0 for s in S3); wk = dot(w, A1) != 0
    return (col, wk, dot(Y, w))
# the Cartan subspace orthogonal to the SM roots: 3-dimensional; parametrise Y = x*u + y*v + z*t on a basis (u, v, t)
M = sympy.Matrix([[*[sympy.Rational(x.numerator, x.denominator) for x in r[0]], sympy.Rational(3, 4) * sympy.Rational(r[1].numerator, r[1].denominator)] for r in [*S3, A1]])
ns = M.nullspace(); assert len(ns) == 3
basis = [(tuple(Fr(int(sympy.Rational(x).p), int(sympy.Rational(x).q)) for x in v[:5]), Fr(int(sympy.Rational(v[5]).p), int(sympy.Rational(v[5]).q))) for v in ns]
# the 27's decomposition under su(3)_c + su(2)_L: group weights into irreducibles by (colour-charged?, weak-charged?) and count
groups = Counter((any(dot(w, s) != 0 for s in S3), dot(w, A1) != 0) for w in W27)
print(f"(3) 27 under su(3)_c + su(2)_L by (colour-charged, weak-charged): {dict(groups)}  -> (3,2): 6 weights, (3,1)+(3bar,1)x3: 12, (1,2)x3: 6, (1,1)x3: 3")
# required hypercharge multiset on the 27's weights (Q: 6 weights at 1/6; u^c 3 at -2/3; d^c 3 at 1/3; D 3 at -1/3; Dbar 3 at 1/3;
# L 2 at -1/2; H_d 2 at -1/2; H_u 2 at 1/2; e^c 1 at 1; nu^c, N at 0)
target = Counter({(True, True, Fr(1, 6)): 6, (True, False, Fr(-2, 3)): 3, (True, False, Fr(1, 3)): 6, (True, False, Fr(-1, 3)): 3,
                  (False, True, Fr(-1, 2)): 4, (False, True, Fr(1, 2)): 2, (False, False, Fr(1)): 1, (False, False, Fr(0)): 2})
# solve: Y linear in (x, y, z); the values on the 27 must realise the target multiset.  Brute force over assignments is unnecessary:
# fix Y(Q-weight) = 1/6 for all six (3,2) weights (they differ by SM roots, so one condition), then the three colour-singlet weak-singlets
# get {1, 0, 0} (3 choices of which is e^c) and the rest follows; enumerate the 3 choices x the (3bar,1) assignment of -2/3 (3 choices).
x, y, z = sympy.symbols('x y z')
def Yval(w, coeffs):
    return sum(c * float(dot(b, w)) for c, b in zip(coeffs, basis))
def Ysym(w):
    return sum(c * sympy.Rational(dot(b, w).numerator, dot(b, w).denominator) for c, b in zip((x, y, z), basis))
Q_w = [w for w in W27 if any(dot(w, s) != 0 for s in S3) and dot(w, A1) != 0]
sing = [w for w in W27 if all(dot(w, s) == 0 for s in S3) and dot(w, A1) == 0]
trip = [w for w in W27 if any(dot(w, s) != 0 for s in S3) and dot(w, A1) == 0]
solutions = []
for e_c in sing:
    eqs = [sympy.Eq(Ysym(Q_w[0]), sympy.Rational(1, 6)), sympy.Eq(Ysym(e_c), 1)] + [sympy.Eq(Ysym(s), 0) for s in sing if s != e_c]
    sol = sympy.solve(eqs, [x, y, z], dict=True)
    for s_ in sol:
        Y = (tuple(sum(Fr(int(sympy.Rational(s_[c]).p), int(sympy.Rational(s_[c]).q)) * b[0][i] for c, b in zip((x, y, z), basis)) for i in range(5)),
             sum(Fr(int(sympy.Rational(s_[c]).p), int(sympy.Rational(s_[c]).q)) * b[1] for c, b in zip((x, y, z), basis)))
        got = Counter(rep_type(w, Y) for w in W27)
        if got == target: solutions.append((e_c, Y))
print(f"    hypercharges Y in the 3-dim commutant Cartan with the Standard Model's multiset on the 27: {len(solutions)} (one per choice of e^c among the three colour-weak singlets)")
# are the solutions Weyl-conjugate (by the Weyl group of the residual A2 = su(3)_R, which permutes the three singlets)?
def act_Y(Y, s): return reflect(Y, s)
# the stabiliser of (S3, A1) in W contains the Weyl group of the centraliser's other A2 (su(3)_R): check that its reflections permute the solutions
otherA2 = [S for S in centA2 if not (A1 in S)]
assert len(otherA2) == 1
refl = list(otherA2[0])
sols_Y = {Y for _, Y in solutions}
closed = all(reflect(Y, s) in sols_Y for Y in sols_Y for s in refl)
print(f"    the reflections of su(3)_R (the A2 commuting with su(3)_c + su(2)_L) permute the {len(solutions)} hypercharges among themselves: {closed} -> one embedding up to conjugacy")

# ---------------------------------------------------------------- (4)-(5) beta, gamma and the singlets for every solution
print("(4) for each hypercharge: the roots commuting with the SM and Y-neutral, gamma, and the singlets' charges")
all_ok = True
for e_c, Y in solutions:
    comm = [r for r in R if all(dot(r, s) == 0 for s in sm_roots) and dot(Y, r) == 0]
    assert len(comm) == 2 and comm[1] == neg(comm[0]); beta = comm[0] if (comm[0][1] > 0 or (comm[0][1] == 0 and [v for v in comm[0][0] if v != 0][0] > 0)) else comm[1]
    Mg = sympy.Matrix([[*[sympy.Rational(v.numerator, v.denominator) for v in r[0]], sympy.Rational(3, 4) * sympy.Rational(r[1].numerator, r[1].denominator)] for r in sm_roots + [Y, beta]])
    ng = Mg.nullspace(); assert len(ng) == 1
    g = ng[0]; gamma = (tuple(Fr(int(sympy.Rational(v).p), int(sympy.Rational(v).q)) for v in g[:5]), Fr(int(sympy.Rational(g[5]).p), int(sympy.Rational(g[5]).q)))
    singlets = [w for w in W27 if all(dot(w, s) == 0 for s in sm_roots) and dot(Y, w) == 0]
    qb = [dot(beta, w) for w in singlets]; qg = [dot(gamma, w) for w in singlets]
    sing78 = [r for r in R if all(dot(r, s) == 0 for s in sm_roots) and dot(Y, r) == 0]
    g78 = [dot(gamma, r) for r in sing78]
    doublet = (add(singlets[0], neg(singlets[1])) in (beta, neg(beta)))
    ok = len(singlets) == 2 and set(qb) == {Fr(1), Fr(-1)} and qg[0] == qg[1] and qg[0] != 0 and all(v == 0 for v in g78) and doublet
    all_ok &= ok
    print(f"    e^c = weight {tuple(str(v) for v in e_c[0])}, psi {e_c[1]}c: +-beta with beta = ({', '.join(str(v) for v in beta[0])}; {beta[1]}c); singlets' beta charges {[str(v) for v in qb]}, "
          f"gamma charges {[str(v) for v in qg]} (equal, non-zero: {qg[0] == qg[1] and qg[0] != 0}); their difference is +-beta (an SU(2)_beta doublet): {doublet}; "
          f"the 78's SM singlets (+-beta) have gamma = {sorted(set(str(v) for v in g78))}")
print(f"(5) for every embedding of the Standard Model in E6: the 27's two SM singlets are an SU(2)_beta doublet with equal U(1)' charge and the 78's "
      f"SM singlets are U(1)'-neutral -> the U(1)' D-term has one sign on all E6-charged SM singlets of 27s and 78s: {all_ok}")
print("\nDONE")
