#!/usr/bin/env python3
"""B1360 -- THE COMPANION-FREE APEX: the computed inputs of the topology of Acharya-Witten's E7 -> E6 unfolding cone.

AW (hep-th/0109152, sec. 2.3) build, for G c G-hat with g-hat = g + u(1) + r + r-bar, the cone X = (H^k /// K') / U(1)' from
Kronheimer's quiver of G-hat with the U(1) of one node omitted; X is the total space of the family of ALE spaces X_zeta over
zeta in R^3 (the omitted node's D-term), the fibre over 0 being C^2/Gamma-hat and the generic fibre having exactly a G singularity.
The FINDINGS give the homotopy argument for b_2(link) = 1 and for the non-vanishing of the E6 link's pairing; this script computes
its inputs:
  (1) the E7 root system from its Cartan matrix: the highest root's coefficient on the omitted node alpha_7 (the index n_7,
      so that the omitted group is U(n_7)), and the roots with zero coefficient on alpha_7 -- they must form the E6 root system
      (72 roots), which is the singularity type of the generic fibre;
  (2) H_2 of the generic fibre: the E7 root lattice modulo the E6 sublattice has rank 1 (the surviving curve C_7);
  (3) the centraliser of 2T in U(2) is the scalars (Schur), so the hyperkaehler circle acts on the tangent cone C^2/2T of the E6
      point as a non-trivial scalar -- the twist that makes the E6 link pair non-trivially;
  (4) the calibration on AW's SU(N) case, X = cone over WCP^3_{1,1,N,N}: the core of the generic fibre is P(1,N) = {b = d = 0}, the
      hyperkaehler circle (right multiplication) rotates it with relative weight N - 1 modulo U(1)', fixing the Z_N point and the
      smooth pole, and the orbifold degrees are  int_U H = 1/N^2 (the SU(N) locus's link U = P(N,N)) and int_V H = 1.
"""
import itertools
import numpy as np
from fractions import Fraction as Fr

# ---------- (1)-(2): E7 roots and the E6 subsystem ----------
# Bourbaki numbering: chain 1-3-4-5-6-7 with 2 attached to 4; E6 = nodes 1..6 (remove 7).
A = np.zeros((7, 7), dtype=int)
edges = [(1, 3), (3, 4), (4, 5), (5, 6), (6, 7), (2, 4)]
for i in range(7):
    A[i, i] = 2
for i, j in edges:
    A[i-1, j-1] = -1; A[j-1, i-1] = -1

def roots_from_cartan(A):
    n = A.shape[0]
    simple = [tuple(int(i == j) for j in range(n)) for i in range(n)]
    roots = set(simple)
    frontier = list(simple)
    while frontier:
        new = []
        for r in frontier:
            for i in range(n):
                # reflection s_i(r) = r - <r, alpha_i^vee> alpha_i, with <r, alpha_i^vee> = sum_j r_j A[j][i]
                c = sum(r[j] * A[j, i] for j in range(n))
                s = list(r); s[i] -= c; s = tuple(s)
                if s not in roots:
                    roots.add(s); new.append(s)
        frontier = new
    return roots

R7 = roots_from_cartan(A)
pos = [r for r in R7 if all(c >= 0 for c in r)]
highest = tuple(int(c) for c in max(pos, key=lambda r: sum(r)))
print(f"E7: {len(R7)} roots ({len(pos)} positive); highest root {highest}; coefficient on alpha_7 = n_7 = {highest[6]} "
      f"(the omitted node's group is U({highest[6]}))")
sub = [r for r in R7 if r[6] == 0]
A6 = A[:6, :6]
R6 = roots_from_cartan(A6)
print(f"roots of E7 with zero coefficient on alpha_7: {len(sub)}; roots of E6 from its own Cartan matrix: {len(R6)}; equal as sets "
      f"(dropping the seventh coordinate): {set(r[:6] for r in sub) == R6}")
# H_2 of the generic fibre: Z^7 / (E6 sublattice spanned by alpha_1..alpha_6) has rank 1, generated by C_7
import sympy
M = sympy.Matrix([[int(i == j) for j in range(7)] for i in range(6)])   # the E6 simple roots inside Z^7
rank_quot = 7 - M.rank()
print(f"H_2 of the E7 resolution modulo the E6 configuration: rank {rank_quot} (the surviving curve C_7): H_2(X_t; Q) = Q -> {rank_quot == 1}")

# ---------- (3): the centraliser of 2T in U(2) ----------
def qmul(a, b):
    a0, a1, a2, a3 = a; b0, b1, b2, b3 = b
    return (a0*b0 - a1*b1 - a2*b2 - a3*b3, a0*b1 + a1*b0 + a2*b3 - a3*b2,
            a0*b2 - a1*b3 + a2*b0 + a3*b1, a0*b3 + a1*b2 - a2*b1 + a3*b0)
def su2(q):
    a, b, c, d = q
    return np.array([[a + 1j*b, c + 1j*d], [-c + 1j*d, a - 1j*b]])
gens = [(0., 1., 0., 0.), (0., 0., 1., 0.), (0.5, 0.5, 0.5, 0.5)]
# commutant of the three generators in M_2(C): solve X g - g X = 0 as a linear system in the 4 entries of X
rows = []
for g in gens:
    G = su2(g)
    for p in range(2):
        for q in range(2):
            row = np.zeros(4, dtype=complex)
            for r in range(2):
                for s in range(2):
                    # (X G - G X)[p,q] = sum_r X[p,r] G[r,q] - G[p,r] X[r,q]
                    if r == p:
                        row[2*p + s] += G[s, q] if False else 0
            rows.append(row)
# simpler: build the 4x4 matrix of the map X -> XG - GX via basis matrices
def comm_map(G):
    Mx = np.zeros((4, 4), dtype=complex)
    for k in range(4):
        E = np.zeros((2, 2), dtype=complex); E[k // 2, k % 2] = 1
        Mx[:, k] = (E @ G - G @ E).reshape(4)
    return Mx
Mall = np.vstack([comm_map(su2(g)) for g in gens])
s = np.linalg.svd(Mall, compute_uv=False)
nullity = int(np.sum(s < 1e-9))
print(f"centraliser of 2T in gl(2, C): dimension {nullity} (the scalars: {nullity == 1}) -> the hyperkaehler circle at the E6 point "
      f"acts on the tangent cone C^2/2T as a scalar e^(i phi/2), weight 1/2 on the tangent and on the normal of the surviving curve")

# ---------- (4): the SU(N) calibration ----------
print("\nAW's SU(N) case, X = cone over WCP^3_{1,1,N,N}: U(1)' acts on (a, b, c, d) with weights (1, -1, N, -N)")
for N in (1, 2, 3, 4):
    # the core of the generic fibre: {b = d = 0}, |a|^2 + N|c|^2 = t, modulo U(1)': the weighted line P(1, N) with [a : c]
    # the hyperkaehler circle: right multiplication, (a, b, c, d) -> (e^{i phi} a, e^{-i phi} b, e^{i phi} c, e^{-i phi} d);
    # modulo U(1)' (theta = phi): [a : c] -> [a : e^{i(1 - N) phi} c]
    rel_weight = 1 - N
    intU = Fr(1, N * N); intV = Fr(1, 1)
    print(f"  N = {N}: the circle rotates the core P(1,{N}) with relative weight {rel_weight} (trivial iff N = 1); "
          f"orbifold degrees: int_U H = 1/(N N) = {intU} over the SU({N}) link U = P({N},{N}), int_V H = {intV} over V = P(1,1); "
          f"U is a genuine locus for N >= 2: {N >= 2}")
print("  (for N = 1 the cone is over CP^3 with no locus and the circle acts trivially on the core: consistent)")
print("\nDONE")
