#!/usr/bin/env python3
"""Own check of memo 233 (THE TWO THREES) v2 and of the v1 vacuity claim.
(1) 2T/Q8 = Z/3 and conjugation by w=(1+i+j+k)/2 3-cycles {i,j,k} mod sign.
(2) Fox calculus on SnapPy's m004 presentation -> Delta(t); H1(Y3)=Z[t]/(t^3-1,Delta) Smith form;
    deck action on the three nonzero classes of H1/2H1.
(3) SnapPy's own 3-fold cyclic cover: H1 and volume (flat?).
(4) v1 certificate: is side B literally the same conjugation as side A (the vacuity)?
(5) b2=1: finite-order elements of GL(1,R)."""
import itertools, re, pathlib, sympy as sp, snappy
ok = {}
# (1) quaternions in half-units
def qmul(p,q):
    a1,b1,c1,d1=p; a2,b2,c2,d2=q
    w=a1*a2-b1*b2-c1*c2-d1*d2; x=a1*b2+b1*a2+c1*d2-d1*c2; y=a1*c2-b1*d2+c1*a2+d1*b2; z=a1*d2+b1*c2-c1*b2+d1*a2
    assert all(v%2==0 for v in (w,x,y,z)); return (w//2,x//2,y//2,z//2)
def qinv(p): return (p[0],-p[1],-p[2],-p[3])
T2=[(2,0,0,0),(-2,0,0,0),(0,2,0,0),(0,-2,0,0),(0,0,2,0),(0,0,-2,0),(0,0,0,2),(0,0,0,-2)]+[s for s in itertools.product((1,-1),repeat=4)]
Q8=set(T2[:8]); assert len(T2)==24
# closure check and normality
assert all(qmul(a,b) in set(T2) for a in T2 for b in T2)
assert all(qmul(qmul(g,q),qinv(g)) in Q8 for g in T2 for q in Q8)
W=(1,1,1,1); cos=[W]; 
w2=qmul(W,W); w3=qmul(w2,W)
ok['Q8 normal index 3, w^3=-1 in Q8, w,w^2 not in Q8']=(w3==(-2,0,0,0) and W not in Q8 and w2 not in Q8)
I,J,K=(0,2,0,0),(0,0,2,0),(0,0,0,2)
conj={n:qmul(qmul(W,n),qinv(W)) for n in (I,J,K)}
ok['w conjugation is i->j->k->i']=(conj[I]==J and conj[J]==K and conj[K]==I)
# (2) Fox calculus
M=snappy.Manifold('m004'); G=M.fundamental_group()
rel=G.relators()[0]; gens=G.generators(); print('presentation', gens, rel)
t=sp.symbols('t')
exps={g:0 for g in gens}
for ch in rel: exps[ch.lower()]+= 1 if ch.islower() else -1
print('exponent sums', exps)
# abelianisation map: a generator with exponent sum e maps to t^? -- H1=Z generated by the generator of exponent sum 0's partner
# generic: solve for weights: sum_e w_g e_g = 0 with weights integer primitive
(g1,g2)=gens; e1,e2=exps[g1],exps[g2]
from math import gcd
gg=gcd(abs(e1),abs(e2)) or 1
wt={g1: -e2//gg, g2: e1//gg}   # e1*w1+e2*w2=0
print('weights', wt)
def ab(word):
    e=0
    for ch in word: e+= wt[ch.lower()]*(1 if ch.islower() else -1)
    return t**e
def fox(word,g):
    res=sp.Integer(0); prefix=''
    for ch in word:
        if ch.lower()==g:
            if ch.islower(): res+=ab(prefix)
            else: res-=ab(prefix+ch)
        prefix+=ch
    return sp.expand(res)
d1,d2=fox(rel,g1),fox(rel,g2)
print('dr/d',g1,'=',d1,' dr/d',g2,'=',d2)
delta=sp.Poly(d1 if d2==0 else sp.gcd(d1,d2),t) if False else None
# Alexander polynomial = gcd of the 1x1 minors after killing the column of the generator mapping to t^{±1}: here one derivative is 0
nz=[d for d in (d1,d2) if d!=0]
D=sp.factor(nz[0]); print('Delta candidate', sp.expand(nz[0]))
Dpoly=sp.Poly(sp.expand(nz[0]*t**5),t)  # shift to positive powers
coeffs=[int(c) for c in Dpoly.all_coeffs()]
while coeffs and coeffs[-1]==0: coeffs.pop()
while coeffs and coeffs[0]==0: coeffs.pop(0)
print('Delta coefficients', coeffs)
ok['Delta = t^2-3t+1 up to units']=(coeffs in ([1,-3,1],[-1,3,-1]))
# H1(Y3) = Z[t]/(t^3-1, Delta): 3x3 relation matrix of multiplication by Delta on basis 1,t,t^2
n=3
def mulmat(poly):
    Mx=sp.zeros(n,n)
    for j in range(n):
        for i,c in enumerate(reversed(poly)):  # c * t^i
            Mx[(i+j)%n,j]+=c
    return Mx
R=mulmat([1,-3,1])
print('relation matrix', R.tolist())
from sympy.matrices.normalforms import smith_normal_form as _snf; snf=_snf(R,domain=sp.ZZ)
diag=[abs(int(snf[i,i])) for i in range(n)]
print('Smith', diag)
ok['H1(Y3)=Z/4+Z/4']=(sorted(diag)==[1,4,4])
# deck = multiplication by t (cyclic shift). Classes of H1/2H1: relations mod 2 -> R mod 2
R2=R.applyfunc(lambda x: x%2)
print('R mod 2', R2.tolist())
# H1/2H1 = F2^3 / colspace(R2)
import numpy as np
cols=[tuple(int(R2[i,j]) for i in range(3)) for j in range(3)]
span={(0,0,0)}
for c in cols:
    span|={tuple((a+b)%2 for a,b in zip(s,c)) for s in span}
print('column span mod 2', sorted(span), 'quotient size', 8//len(span))
ok['H1/2H1 = (Z/2)^2']=(8//len(span)==4)
def canon(v): return min(tuple((a+b)%2 for a,b in zip(v,s)) for s in span)
classes=sorted({canon(v) for v in itertools.product((0,1),repeat=3)}-{canon((0,0,0))})
shift=lambda v:(v[2],v[0],v[1])  # t * (c0 + c1 t + c2 t^2) = c2 + c0 t + c1 t^2
perm={c:canon(shift(c)) for c in classes}
print('deck on H1/2H1 classes', perm)
cyc=len(classes)==3 and all(perm[c]!=c for c in classes)
ok['deck 3-cycles the three order-2 characters']=cyc
ok['deck=I trivial (V-FIRE)']=all(canon(c)==c for c in classes)
# (3) SnapPy cover
covs=M.covers(3,cover_type='cyclic'); C=covs[0]
print('cyclic 3-cover', C, C.homology(), 'vol', C.volume())
F=C.copy(); F.dehn_fill((1,0)); print('filled (1,0):', F.homology(), 'vol', F.volume())
ok['3-cover filled: H1=Z/4+Z/4, vol~0']=(str(F.homology()) in ('Z/4 + Z/4',) and abs(float(F.volume()))<1e-4)
# (4) v1 vacuity, textual
src=pathlib.Path('outside_bench/certificates/the_two_threes.py').read_text()
m=re.search(r"def conj_v\(.*?\n(?:.*\n){0,6}",src)
print('v1 side-B definition:\n', m.group(0) if m else 'NOT FOUND')
ok['v1 side B is conjugation by W (same as side A)']=bool(m and 'qmul(qmul(' in m.group(0))
# (5) GL(1,R)
ok['GL(1,R) finite elements are {+-1}: no order 3']=True  # x^3=1 over R => x=1
for k,v in ok.items(): print(('PASS' if v else 'FAIL'), k)
print('ALL PASS' if all(ok.values()) else 'SOME FAIL')
