"""B281 (addendum) -- the FINER geometric probe: not just dim H^1=rank, but IRREDUCIBILITY. Run with sage-python.

dim H^1 = rank is a coarse invariant; the physically relevant question is whether the figure-eight has genuinely
G-IRREDUCIBLE (G-Zariski-dense) flat connections for a given type, or whether the principal deformations stay
trapped in a subalgebra. If E6 were the ONLY type with dense flat connections, the character variety WOULD
distinguish E6 and the geometric-level scoping conclusion would be WRONG. This computes, for each principal sl(2)->g,
the dimension of the Lie subalgebra generated by <principal sl(2), v_m> for each exponent m (B265's method,
generalized to all types via a convention-robust principal triple).

RESULT: EVERY type has a dense direction (G2 at exp 5, F4 fully at {5,7,11}, SO(8) at exp 3, E6 at {4,8}, SU(n) at
exp 2). So E6 is NOT distinguished even at the irreducibility level -- the geometric-level conclusion HOLDS.
"""
from sage.all import LieAlgebra, QQ, matrix, vector, identity_matrix

EXPON = {("A", 2): [1, 2], ("G", 2): [1, 5], ("A", 3): [1, 2, 3], ("D", 4): [1, 3, 5],
         ("F", 4): [1, 5, 7, 11], ("E", 6): [1, 4, 5, 7, 8, 11]}


def analyze(ct):
    L = LieAlgebra(QQ, cartan_type=list(ct)); dim = L.dimension(); idx = list(L.cartan_type().index_set()); r = len(idx)
    Hh = [L.bracket(L.e(i), L.f(i)) for i in idx]
    e = sum(L.e(i) for i in idx)
    Bmat = matrix(QQ, r, r)                                    # solve principal h: [sum c_k Hh_k, e_i] = 2 e_i
    for k in range(r):
        for ii, i in enumerate(idx):
            br = L.bracket(Hh[k], L.e(i)); ev = L.e(i).to_vector(); bv = br.to_vector()
            piv = next(j for j in range(dim) if ev[j] != 0); Bmat[k, ii] = bv[piv] / ev[piv]
    c = Bmat.transpose().solve_right(vector(QQ, [2] * r)); h = sum(c[k] * Hh[k] for k in range(r))
    assert L.bracket(h, e) == 2 * e
    bas = list(L.basis()); vtoel = lambda v: sum(v[i] * bas[i] for i in range(dim))
    adh = matrix(QQ, [L.bracket(h, b).to_vector() for b in bas]).transpose()
    ade = matrix(QQ, [L.bracket(e, b).to_vector() for b in bas]).transpose()
    Em2 = matrix(QQ, [list(b) for b in (adh + 2 * identity_matrix(QQ, dim)).right_kernel().basis()]).transpose()
    f = vtoel(Em2 * (ade * Em2).solve_right(h.to_vector())); assert L.bracket(e, f) == h
    Ke = ade.right_kernel()

    def gendim(v):
        gens = [e, h, f, vtoel(v)]; M = matrix(QQ, [x.to_vector() for x in gens]); cur = list(gens); ch = True
        while ch:
            ch = False
            for x in list(cur):
                for gg in gens:
                    br = L.bracket(x, gg)
                    if M.stack(br.to_vector()).rank() > M.rank(): M = M.stack(br.to_vector()); cur.append(br); ch = True
        return M.rank()

    out = {}
    for m in EXPON[ct]:
        sp = (adh - 2 * m * identity_matrix(QQ, dim)).right_kernel().intersection(Ke)
        out[m] = max(gendim(b) for b in sp.basis())
    return dim, out


if __name__ == "__main__":
    all_have_dense = True
    for ct in [("A", 2), ("G", 2), ("A", 3), ("D", 4), ("F", 4), ("E", 6)]:
        g, out = analyze(ct); dense = [m for m, d in out.items() if d == g]
        all_have_dense &= len(dense) > 0
        print(f"{ct[0]}{ct[1]} dim={g:3}: {{exp:gen}}={out} | DENSE exps {dense}")
    print("\nEVERY type has a dense (G-irreducible) direction:", all_have_dense)
    print("=> E6 NOT distinguished even at the irreducibility level; geometric-level scoping HOLDS.")
    assert all_have_dense
