import json
d=json.load(open('verify_1.json'))
C='CONFIRM';D='DEMOTE'
N='NON-UNIQUENESS';P='PAIRING';F='FLATNESS'
v={
'B281':(C,N,'text says character variety does not single out E6; unforced'),
'B282':(C,N,'generic to any hyperbolic knot; nothing selects the object'),
'B284':(C,N,'generic smooth point; nothing distinguishes 2T component'),
'B308':(C,N,'E6 fixes coupling but not texture; not forced'),
'B322':(D,'OTHER:null-test-chance','chance-level match against data, no named non-selection'),
'B329':(C,P,'sigma-stable embeddings force n1=n2; symmetry-forced balance'),
'B330':(C,N,'states no forced choice exists'),
'B331':(C,P,'conjugate to inverse forces real character and n1=n2'),
'B333':(D,'OTHER:null-no-value','arithmetic generic but kill is carries-no-value null'),
'B349':(C,N,'no member marked, no forced choice'),
'B350':(C,N,'no forced choice; symmetrizable Galois orbit'),
'B355':(D,'OTHER:reality-no-mechanism','exactly real products; no symmetry partner named'),
'B369':(C,F,'seam readout identically null'),
'B395':(D,'OTHER:premise-false','cell-wise sigma-law fails; mirror summation-emergent, no pairing named'),
'B398':(C,N,'banks as numerology-class'),
'B413':(C,F,'tower-measure flat, constant modulus for every character'),
'B414':(C,N,'no canonical frame; privilege test fails'),
'B422':(D,'OTHER:orthogonality','sectors orthogonal; no cancellation by partner named'),
'B438':(C,N,'shared with 5_2 control; nothing figure-eight-unique'),
'B441':(C,N,'forced, not object-specific; shared field'),
'B442':(C,N,'commensurability-shared; no figure-eight-specific structure'),
'B447':(C,N,'surrogate reproduces; no golden exceptionality'),
'B455':(C,F,'kappa conserved along orbits; no restoring response'),
'B457':(C,N,'catalog class-generic or whitelist-laundered'),
'B458':(C,F,'complex volume identically zero; nothing to decompose'),
'B461':(C,N,'sqrt(-7) appears on unrelated control; not selective'),
'B462':(C,N,'launders through class-generic mechanism'),
'B464':(C,N,'no relational invariant escaping class-laundering'),
'B480':(C,N,'Dirac emergence generic; mass tunable angle'),
'B529':(C,N,'generic degeneracy; loses to random controls'),
'B541':(D,'OTHER:null-test-chance','matches data no better than chance; no non-selection named'),
'B592':(C,P,'C-symmetry makes theta-odd amplitudes vanish'),
'B600':(D,'OTHER:computed-zero','trace zero at one level; no flatness mechanism named'),
'B660':(D,'OTHER:no-go-dimensionful','zero trilinear plus dimensionful no-go; mixed mechanism'),
'B671':(C,N,'two canonical scalarizations disagree; gauge, nothing selects'),
'B674':(C,F,'trace-silent for all m; identically zero'),
'B686':(D,'OTHER:tautology','parametrization tautology and convention-dependence'),
'B697':(D,'OTHER:tautology','tautological Gaussian period'),
'B713':(C,N,'non-canonical Galois torsor bit'),
'B716':(C,N,'no canonical arrow, filling or Wick rotation'),
'B719':(C,N,'no preferred size; filter generic, shared by controls'),
'B735':(C,N,'generic to every cusped hyperbolic manifold'),
'B737':(D,'OTHER:vacuity','zeta_K is the field\'s; vacuity plus object-deletion'),
'B751':(D,'OTHER:scale-knob-null','scale-knob-dependent target, constructed assignment, null-consistent hits'),
'B752':(D,'OTHER:base-rate-misidentified','base-rate hits and misidentified trace matrix'),
'B760':(C,N,'no operation canonically signs the sector'),
'B802':(C,P,'reversal leaves frequencies unchanged; direction unreadable'),
'B850':(C,N,'genericity of foliation type is the kill form'),
'B854':(D,'OTHER:centralizer-abelian','centralizer of 2T abelian; not flatness or pairing'),
'B924':(C,P,'psi0-reality and C-centrality close both parity channels'),
'B935':(C,F,'rank-2 overlap, det zero exactly; cascade index undefined'),
'B971':(D,'OTHER:vacuity','criterion cannot fail; vacuous check'),
'B996':(C,N,'E6 access generic across most metallic grammars'),
'B1064':(C,P,'amphichirality deletes the quantized sector; CS=0'),
'B1076':(C,N,'element-specific values; nature supplies the gauge'),
'B1084':(D,'OTHER:non-isolation','fixed-set census shows non-isolated loci; geometry not flatness'),
'B1086':(C,P,'Poincare duality pairing forces h1(27)=h1(27bar)'),
'B1096':(C,F,'every anomaly channel identically zero'),
'B1140':(C,F,'invariant content zero; no invariant direction'),
'B1142':(D,'OTHER:count-mismatch','zeros 697x too sparse to be geodesic spectrum'),
'B1157':(C,N,'ingredients generic to any hyperbolic 3-manifold'),
'B1165':(C,N,'dynamical sector generic rhyme; survives swapping manifold'),
'B1203':(C,N,'symmetry cannot select; cut zero, invariant conserved'),
'B1205':(C,N,'cubic surface selects nothing; singular locus empty'),
'B1209':(C,F,'torsor trivial; freedom exactly zero'),
'B1258':(C,N,'identical for both candidates; cannot select embedding'),
'B1267':(C,F,'both h1 vanish; rigid, no modes'),
'B1296':(C,P,'sigma-even locus forces theta-even Cartan; parity constraint'),
'B1297':(C,P,'Galois self-duality and period-2 inversion force zero index'),
'B1322':(D,'OTHER:computed-no-mechanism','computed dead on benches; no pairing or flatness named'),
'B1330':(D,'OTHER:computed-zero','four members return zero; no mechanism named'),
'B1336':(D,'OTHER:borel-density','Zariski-density forces central centralizer; different mechanism'),
'B1340':(D,'OTHER:vacuity','checks vacuous, cannot fail'),
'B1347':(C,N,'stratum fixes no arrow; both outcomes occur'),
'B1349':(D,'OTHER:kind-field-mismatch','closed by tie and field mismatch, not non-selection'),
'B1450':(D,'OTHER:no-discriminating-feature','six features fail to separate sets; no mechanism named'),
'B1455':(C,P,'index odd under dualising; self-dual module has zero index'),
}
out=[]
for e in d:
    ve,k,w=v[e['id']]
    out.append({'id':e['id'],'verdict':ve,'kind':k,'why':w})
assert len(out)==77 and len(v)==77
json.dump(out,open('verified_1.json','w'),ensure_ascii=False,indent=0)
from collections import Counter
print(Counter(o['verdict'] for o in out))
