import json
b=json.load(open('batch_0.json'))
O,P,F,N="OTHER","PAIRING","FLATNESS","NON-UNIQUENESS"
R={
"B101":(O,"no-landing-site","does NOT climb","high"),
"B107":(O,"kind-mismatch","category error — tower/torsion are linearized monodromy on moduli-space tangent","high"),
"B111":(O,"arithmetic-mismatch","s_n ∈ {±1} (order ≤2) cannot equal the order-4 secondary c=i","high"),
"B120":(O,"no-extra-structure","distinct integer matrices with equal (trace,det) yield identical towers","low"),
"B128":(O,"kind-mismatch","center ≠ gauge group","high"),
"B132":(O,"genericity","the field content is quantum-group arithmetic","medium"),
"B140":(P,"orientation-reversal","mirror has same volume, opposite CS, conjugate-isomorphic trace field","low"),
"B146":(P,"mirror-indifference","no selection using only orientation-independent invariants can prefer M vs its mirror","medium"),
"B154":(O,"value-miss","off-principal data gives k=4 at BOTH n=3 and n=4","low"),
"B157":(O,"value-miss","REFUTED by computed bronze (m=3) counterexamples","medium"),
"B161":(N,"free-continuum","κ is a FREE continuum on the trace-map fixed locus","high"),
"B165":(O,"instrument","marked NEEDS-SPECIALIST","high"),
"B166":(O,"kind-mismatch","SL(n≥3) is not the transfer group of ANY self-adjoint operator","high"),
"B172":(O,"instrument","sharp label certification is method-limited","high"),
"B177":(F,"no-dynamics","no dissipation, no arrow","low"),
"B182":(N,"proliferation","proliferation not selection-to-unique","high"),
"B183":(N,"external-scale","externally sourced (the imaginary gauge field is input)","low"),
"B184":(N,"proliferating-product","a growing product, not a selected Lie/gauge group","medium"),
"B185":(N,"fork-size>1","the fork has size >1, multiplies under composition, and is choice-dependent","high"),
"B186":(O,"instrument","the rigorous off-axis uniform-hyperbolicity PROOF is unreachable in-sandbox","high"),
"B191":(N,"proliferating-fork","stays discrete-and-proliferating","high"),
"B192":(O,"instrument","an artifact of three cherry-picked energies plus a dense-Gaussian rigged control","high"),
"B193":(O,"premise-false","all four (chirality, field) combinations occur","high"),
"B197":(O,"not-independent","the volume filter is unique only GIVEN torsion-free","medium"),
"B198":(O,"instrument","the exact symbolic k at SL(5) is unreachable","medium"),
"B199":(O,"no-closed-form","killed by PROVEN collisions","medium"),
"B200":(O,"scope","t_eff=2t^2/U is strong-coupling only","high"),
"B214":(O,"premise-false","vacuous (identical |Z| for the same monodromy is the definition of a topological invariant)","medium"),
"B216":(O,"instrument","from a proxy invariant (scalar-depth tested against +/-I only)","high"),
"B219":(F,"invariant-constant","every content-1 class has period exactly 80 = lcm/content, regardless of genus signature","low"),
"B225":(O,"genericity","the '2 = octahedral parent' half","low"),
"B237":(O,"premise-false","Silver bundle pi_1 carries a binary octahedral (2O) quotient","medium"),
"B239":(O,"no-landing-site","reachability of Q(sqrt(-7)) by any unimodular element (below the disc=-4 floor)","high"),
"B243":(N,"numerology","The 'metallic ladder' V(m^2+2) in Q(sqrt(m^2+4))","low"),
"B247":(O,"premise-false","'geometric holonomy lives in SU(2)' refuted","medium"),
"B252":(P,"conjugation-odd","complex-conjugation-odd (chiral / CP-odd) invariant that could prefer 27 over 27-bar","low"),
"B272":(O,"genericity","'REDUCED -- no math obstruction left' for the E6 bridge","low"),
"B279":(O,"unstated","'tau could SWAP the two spin structures of 4_1'","low"),
"B285":(O,"kind-mismatch","physical CP-violating (Jarlskog-type) phase sourcing baryon asymmetry","medium"),
"B294":(N,"catalogue","selective for the object's own structure, catalogue for SM values","medium"),
"B295":(O,"kind-mismatch","the V(tau) potential is the wrong object","medium"),
"B296":(O,"not-a-kill","red-team found none (0 refutations)","high"),
"B299":(O,"no-landing-site","phi acts FREELY on the 27 (9 orbits of 3, zero fixed weights)","medium"),
"B305":(O,"no-landing-site","A2 is impossible (needs a height-12 root; E6 tops at 11)","high"),
"B307":(O,"arithmetic-mismatch","C3 fields are totally real, hyperbolic invariant trace fields always have a complex place","high"),
"B310":(O,"genericity","equal pi*i/3 deformation spacing tied to the cusp shape","low"),
"B313":(O,"genericity","the figure-eight is forced as a theorem","low"),
"B320":(O,"genericity","observer=seam is proven mathematics","low"),
"B321":(N,"numerology","The CP phase pi/6 IS the core geodesic length of the (6,3) Dehn filling","low"),
"B325":(O,"unstated","the E6 cubic cannot split them and the CRUX relocates to Level 4","low"),
"B332":(N,"numerology","the 1/4 volume-suppression fits SM ratios","low"),
"B334":(N,"numerology","137 lands non-principal","low"),
"B335":(O,"kind-mismatch","The mass hierarchy is in the object","low"),
"B343":(N,"no-selection","The object selects a TM2 (or any) TBM-breaking direction","low"),
"B360":(O,"premise-false","Seam brightness follows seed parity","medium"),
"B361":(O,"premise-false","bright iff the pair contains a seed elliptic at both primes","medium"),
"B364":(O,"unstated","T-stability forces the theta lift as THE geometric lift","low"),
"B365":(O,"no-landing-site","triangular family S-closed on its own 15-dim span, square not","medium"),
"B367":(O,"instrument","uniform local-symbol product formula at declared complexity","medium"),
"B372":(O,"premise-false","the sqrt(-15) content does not persist at level 45","medium"),
"B373":(O,"scope","gapless-trending reading feeding the tower-limit door PD2.2","medium"),
"B374":(O,"scope","no invariant sector at the first mixed m=15","medium"),
"B385":(F,"identical-profiles","kill 1: identical invariant profiles","low"),
"B389":(O,"premise-false","dihedral mechanism M1/M2: inversion law t(−a,−b)=t(a,b)","low"),
"B392":(O,"no-landing-site","T-spectrum no-match, completing the earlier S-level no-match","medium"),
"B394":(O,"scope","actual support a≡31 mod 45, twelve cells","medium"),
"B397":(O,"premise-false","both killed exhaustively","medium"),
"B399":(O,"kind-mismatch","the tower is a RESOLUTION generator, not a scale generator","medium"),
"B400":(N,"arbitrary-identification","any linking object requires arbitrary identification choices","low"),
"B401":(O,"premise-false","killed by 7 (inert) sitting in the bright (3,4) Gram spectrum","medium"),
"B403":(O,"premise-false","vacuous on denominators","medium"),
"B405":(N,"numerology","equal dressability = unfalsifiable","medium"),
"B406":(O,"genericity","FORCED BY TORSION","medium"),
"B407":(O,"scope","(2,4) has both exclusives (no nesting either way), (1,3) nests in REVERSE","high"),
"B409":(O,"scope","holds on only 4/6 pairs","high"),
"B411":(N,"multi-valued","multi-valued on generic invertible-det cells (6 H-types share one class label)","low"),
"B412":(O,"kind-mismatch","the tower is a mass-conserving refining MEASURE","medium"),
"B418":(O,"no-landing-site","none realizes the mirror cell-wise","medium"),
"B428":(O,"no-landing-site","no theta=-1 object at level 1 or 2","high"),
"B433":(O,"method-limit","scale enters only via external embedding (R/CY)","medium"),
"B435":(O,"genericity","H1 = Z/p for EVERY knot at slope p (trefoil control)","high"),
"B437":(O,"genericity","trefoil(5,1) gives the SAME field Q(sqrt5)","high"),
"B440":(O,"genericity","4_1 and 5_2 children both have exactly 4 irreducible vacua in the identical -283 field","high"),
"B443":(O,"genericity","figure-eight-unique features: none found at any floor","high"),
"B444":(O,"genericity","separation inherited from SL(2) arithmeticity (not created at SL(3))","high"),
"B445":(O,"genericity","H1 = 6 = rank(E6) is universal (Menal-Ferrer-Porti)","high"),
"B459":(O,"genericity","the weakest possible structural match","medium"),
"B465":(O,"no-landing-site","needs an irreducible 8; none exists","high"),
"B468":(O,"instrument","a float tier-misclassification with the dark total itself wrong","medium"),
"B472":(O,"premise-false","kappa_q(1,1) = -1 != kappa_classical = -2","medium"),
"B474":(O,"instrument","the seventh float-kill","high"),
"B476":(O,"arithmetic-mismatch","5x13=65≠49 (does not factor)","medium"),
"B477":(O,"premise-false","refuted as universal by s776's count (3 fertile classes, not a power of 2)","medium"),
"B482":(O,"arithmetic-mismatch","a different number/clock","low"),
"B483":(N,"numerology","3,8,15 = a(a+2) = adjoint dims of SU(2),SU(3),SU(4) (forced spin-j arithmetic at any level)","medium"),
"B484":(O,"no-landing-site","the braid image is DENSE in SU(dim), the antithesis of a closed proper gauge subgroup","medium"),
"B486":(O,"arithmetic-mismatch","the figure-eight cusp modulus is 2√−3 (disc −48), rectangular, NOT the hexagonal point","high"),
"B487":(O,"kind-mismatch","the SU(3) is a GLOBAL FLAVOR symmetry of a 3d N=2 U(1) gauge theory","high"),
"B489":(O,"no-landing-site","no gauge enhancement anywhere","high"),
"B491":(O,"not-novel","COROLLARY of Cantat 2009","high"),
"B492":(O,"genericity","classical RCFT modular data: the same banked golden phi dressed as boundary entropy","medium"),
}
out=[]
ids=[e['id'] for e in b]
assert set(ids)==set(R) and len(ids)==len(R),(set(ids)^set(R))
for e in b:
    k,l,q,c=R[e['id']]
    assert q in e['claim_killed'] or q in (e['kill_form'] or ''),(e['id'],q)
    assert len(q.split())<=20,(e['id'],len(q.split()))
    out.append({"id":e['id'],"kind":k,"label":l,"quote":q,"confidence":c})
json.dump(out,open('out_0.json','w'),ensure_ascii=False,indent=1)
from collections import Counter
print(Counter(o['kind'] for o in out),len(out))
