import json
d=json.load(open('batch_1.json'))
P,F,N,O='PAIRING','FLATNESS','NON-UNIQUENESS','OTHER'
H,M,L='high','medium','low'
R=[
(O,'instrument',"35/150 (23%) UNCHECKED",M),
(N,'genericity',"the (2,1) is generic to any F₂ variety",L),
(O,'premise-false',"KILLED BY COUNTEREXAMPLE",H),
(N,'no-selection',"so 3 is not dimension-selected",M),
(O,'no-landing-site',"The naive three-channel Fibonacci tight-binding model supplies the PC12 physics bridge",L),
(O,'premise-false',"Exploration-seat handoff claims",L),
(O,'no-landing-site',"Some peripheral invariant forces a choice the object doesn't make",L),
(N,'genericity',"is generic to any 2-real-1-complex quartic Pisot",M),
(O,'instrument',"3 of 9 CRACKED (B519-NOCROSS retracted, C3-CONE certificate bug, CHILD-NOTSHORT downgraded)",M),
(O,'no-landing-site',"the isotropy-Stein no-go, via non-normal transient growth",M),
(O,'instrument',"NOT REPRODUCED — natural lift gives period 20, convention-dependent",L),
(N,'numerology',"matches relations among the SM's 19 dimensionless parameters",L),
(O,'arithmetic-mismatch',"7 inert in Q(sqrt(3))",M),
(N,'genericity',"un-hideability as a discriminating special property of the object",M),
(O,'premise-false',"Promotion-Sign Conjecture",M),
(O,'scope',"killed as KNOWN — KKT 1983/Casdagli/Roberts",L),
(O,'premise-false',"REFUTED (181,678/299,999 = 61% mismatches",M),
(O,'value-miss',"0/17 dictionary values at 1%, 0 dictionary-relation matches",L),
(N,'numerology',"linking it to the c=1 Eisenstein structure (a holonomy bridge)",L),
(O,'no-landing-site',"The figure-eight's Eisenstein Z/3 selects SU(3)^2 (A2xA2~) inside F4",L),
(O,'unstated',"SM-like level structure",L),
(F,'zero-intertwiner',"zero-intertwiner",L),
(N,'numerology',"The apparent match between the class number h(Q(sqrt-15))=2",L),
(O,'no-landing-site',"'sigma distinguishes 27 from 27bar'",L),
(O,'no-landing-site',"escapes the fifth (vector-like) wall",L),
(N,'numerology',"alpha_s(M_Z)=1/(2 phi^3), sin^2 theta13 = 1/phi^8",M),
(O,'instrument',"the cotangent cleanly yields a_d",L),
(O,'value-miss',"failed hold-out at kappa=17,18",M),
(O,'value-miss',"PC12's Open Prediction for the SL(4) fixed-line Jacobian",L),
(O,'instrument',"cond(Dx) ~ 1e11 conditioning barrier",H),
(O,'no-landing-site',"which theta-odd pair goes to the V8 block and which to V16",L),
(O,'premise-false',"the amphichiral involution tau is a reflection with Fix(tau) a totally geodesic surface",M),
(N,'numerology',"a group-identity bridge from the stage to A5 flavor models",L),
(O,'instrument',"tr and det scatter across seeds",M),
(O,'premise-false',"trace(B_odd) is the SAME twelve-term Gauss assembly up to a fixed framing phase",M),
(O,'premise-false',"J-as-function-of-t killed outright by the exact counterexample RRLL vs RRRRL",H),
(F,'vanishing-class',"H^2(M;C)=0 + graded-commutativity force antisymmetry, zero diagonal",L),
(O,'value-miss',"predicts Q(zeta8) for silver; observed Q(i)",M),
(O,'premise-false',"a universal cocycle factor, not an area count",M),
(O,'premise-false',"the holonomy-invariant line v0 is NOT the GUT singlet",M),
(O,'premise-false',"the |k|=3 multiplicity at SL(6) is exactly 2, same as SL(5)",M),
(N,'no-selection',"'the golden is the ONLY real minimum' (refuted",M),
(F,'trivial-period',"a periodic sequence has ZERO asymptotic 1/k content",M),
(O,'premise-false',"boundedness is certificate-structural, not amphichirality",L),
(O,'arithmetic-mismatch',"unique quadratic subfield Q(sqrt5) REAL",M),
(O,'arithmetic-mismatch',"genuinely Q(zeta5)-irrational leading coefficient vs the INTEGER targets",L),
(O,'premise-false',"killed by the exact decomposition v5(den c_n) = n + v5(n!)",L),
(O,'arithmetic-mismatch',"the streams require growing 5-adic denominators",H),
(N,'numerology',"sin^2 theta12 has ~20 golden values in its band",M),
(F,'trivial-value',"a_(5) = +1, the trivial Steinberg value in Q",L),
(O,'no-landing-site',"The meeting is a product, not a fusion",M),
(N,'genericity',"filling is generic by strong approximation",M),
(N,'numerology',"a post-hoc fit atop the Q=2/3 parametrization tautology",M),
(N,'numerology',"base-rate-dead coincidence",M),
(O,'kind-mismatch',"discrete orientation bits vs ~19-26 continuous real parameters",M),
(O,'kind-mismatch',"T4 permitted-not-forced",L),
(O,'kind-mismatch',"fig-8 saddle actions real (Im=0, AT the conjugation fixed point",L),
(O,'premise-false',"distinct commuting involutions acting ORTHOGONALLY",M),
(N,'non-canonical',"Non-canonicity goes TOTAL",L),
(O,'no-landing-site',"NO-MATCH: needs higher-dim bulk",M),
(O,'kind-mismatch',"Killed as rung-mismatch",M),
(O,'mixed',"re-adjudicated with every discriminating fact RECOMPUTED",L),
(O,'arithmetic-mismatch',"neither lives in a bare quadratic face (Q(sqrt5) is totally real, no phase)",M),
(N,'genericity',"the three faces are canonical functions of ONE ADE label",M),
(O,'premise-false',"B731 concluded NON-congruence (congruence closure index 6 < geometric 12)",M),
(O,'kind-mismatch',"abelian GL(1) type mismatch vs the non-abelian Bianchi tower",M),
(O,'no-landing-site',"all 24 graded (d)=nothing-forced",L),
(O,'premise-false',"A<->D unification conjecture (I-series)",L),
(O,'instrument',"I1: the SL(5) tower barrier is a fixable gauge/basis artifact",M),
(O,'premise-false',"m=2 (genus 1, j=1728, CM by Z[i]) is a genus MINIMUM",M),
(O,'premise-false',"L1a is a TAUTOLOGY (holds for arbitrary (A,t)",M),
(N,'numerology',"matches a measured SM value beyond base rate",L),
(O,'no-landing-site',"A Yukawa-type (symmetric) family tensor for identical generations exists",L),
(O,'no-landing-site',"A symmetric mass-matrix-shaped object (a scalar-valued symmetric texture on H^1) exists",L),
(O,'no-landing-site',"a pair-to-block assignment exists",L),
(F,'zero-index',"nonzero chiral index",M),
(O,'arithmetic-mismatch',"some hyperbolic knot has a cyclic-cubic (C3) trace field",M),
(O,'no-landing-site',"The naive Z/3 triality acts on H^1(D;27)",L),
(P,'mirror',"Some orientation-reversing (mirror) symmetry of Isom(4_1)=D4 survives",L),
(F,'zero-intertwiner',"A nonzero C-linear monodromy-equivariant map exists",L),
(O,'kind-mismatch',"The framework can output any dimensionful quantity AS A VALUE",M),
(O,'kind-mismatch',"SM flavor ratios are low-height algebraic over the audible field Q(sqrt5)",L),
(N,'numerology',"Λ = Λ_Planck·φ^(−2N)",L),
(O,'kind-mismatch',"The SL(n) tower eigenvalues are a physical mass/operator-dimension spectrum",L),
(O,'premise-false',"The Goldman/Weil–Petersson form on the character variety is Lorentzian (1,1)",L),
(N,'numerology',"SL(3) character variety has 6 real dimensions → 3+1 spacetime",L),
(O,'unstated',"Lorentzian signature climbs the principal-SL(2) ladder to give 3+1 at higher rank",L),
(O,'instrument',"An information-geometry (Fisher-metric) reading of the Chern–Simons level",L),
(N,'genericity',"The Fibonacci critical chain's entanglement signals holography",L),
(O,'premise-false',"A single repeated −1 is the common root cause",L),
(O,'value-miss',"θ=−w₀ predicts all four per-eigenvector Dehn-filling scalars c",L),
(O,'premise-false',"The tower sign s_n∈{±1} equals the degree=rank secondary scalar c=i",L),
(N,'numerology',"The Chern–Simons level crosses over near k≈4, matching the rank n=4",L),
(O,'scope',"Five quantum-tower/knot observations read as framework-specific bridges",L),
(O,'no-landing-site',"det=−1 breaks chirality and selects the Standard-Model chiral structure",L),
(O,'kind-mismatch',"The quantized figure-eight is the physical Fibonacci topological order",L),
(O,'kind-mismatch',"Some metallic member furnishes physical (unitary, chiral) topological order",L),
(N,'genericity',"non-generic physical ratio",L),
(O,'kind-mismatch',"H₁ torsion tracks chirality and its ℤ/n is an SU(n) center selecting a gauge group",L),
(N,'no-selection',"Isolated fixed points with distinct unsymmetrizable κ values give the structure a forced choice",L),
(O,'premise-false',"chirality causes the eigenvalue field content",L),
]
assert len(R)==len(d),(len(R),len(d))
out=[]
for e,(k,l,q,c) in zip(d,R):
    t=(e['claim_killed'] or '')+' '+(e['kill_form'] or '')
    assert q in t,(e['id'],q)
    assert len(q.split())<=20,(e['id'],len(q.split()))
    out.append(dict(id=e['id'],kind=k,label=l,quote=q,confidence=c))
json.dump(out,open('out_1.json','w'),ensure_ascii=False,indent=1)
from collections import Counter
print(Counter(o['kind'] for o in out),len(out))
