import json
d=json.load(open('batch_3.json'))
P,F,N,O="PAIRING","FLATNESS","NON-UNIQUENESS","OTHER"
r={
"B413":(F,"flat","The tower-measure is flat (|L(chi)|=1/4 for every character, Gauss-sum phases)","high"),
"B414":(N,"","no canonical frame exists","medium"),
"B419":(O,"no-landing-site","a hyperbolic volume with golden-field arithmetic, not an SM structure","medium"),
"B420":(O,"no-landing-site","with the bar not cleared and no SM structure","medium"),
"B421":(O,"no-landing-site","every destination is named pure mathematics and none cleared the bar","medium"),
"B422":(P,"mirror-orthogonality","Under the Z/2 mirror frame the golden and Mercedes sectors stay exactly orthogonal","low"),
"B429":(O,"no-landing-site","no first-order deformation of the object's E₆ structure produces spinorial matter","medium"),
"B430":(O,"no-landing-site","the object forces only the principal bosonic one, so the fermion door is closed","medium"),
"B438":(N,"not-object-specific","nothing about the child is figure-eight-unique","medium"),
"B441":(N,"not-object-specific","its sqrt5/sqrt-3/sqrt-15 content is forced, not object-specific","low"),
"B442":(N,"not-object-specific","adding no figure-eight-specific structure (Bin 3)","low"),
"B447":(N,"laundered-match","reproduced by a parameter-free 8-moment surrogate — no golden exceptionality","low"),
"B455":(F,"no-dynamics","kappa is conserved along perturbed orbits, so no restoring response exists","medium"),
"B457":(N,"null-consistent-hits","the behavior catalog is class-generic or whitelist-laundered","low"),
"B458":(F,"zero-invariant","has complex volume 0 + i*0","medium"),
"B461":(N,"not-object-specific","Q(sqrt(-7)) appears on an unrelated control","low"),
"B462":(N,"class-generic","launders through a class-generic mechanism","low"),
"B464":(N,"class-generic","no relational invariant escaping class-laundering","low"),
"B480":(N,"generic","Dirac emergence is generic, mass is a tunable alignment angle","medium"),
"B481":(O,"instrument","det(T) = zeta_5 is a float artifact","high"),
"B490":(O,"unstated","one structural no-go, stated as a single provable theorem","low"),
"B498":(O,"premise-false","Depth-3 mixed words refute both the golden monopoly and cyclotomic tameness","high"),
"B512":(O,"arithmetic-mismatch","the McKay ladder to E₆ is golden-specific (silver is a 2-group)","medium"),
"B529":(N,"generic","generic spectral degeneracy and the golden-angle coin loses to 2 of 10 random controls","medium"),
"B541":(N,"chance-match","matches SM constants no better than chance","medium"),
"B549":(O,"value-miss","Both time-independent cosmic ratios return null","medium"),
"B551":(O,"no-landing-site","no rotation/winding mechanism can emit it","medium"),
"B559":(O,"premise-false","critical with log-law entanglement, not area-law","medium"),
"B563":(O,"value-miss","nulls at every rung (p≈0.53, zero hits)","medium"),
"B573":(O,"premise-false","the principal sl2 preserves no Spin(10) grading","medium"),
"B577":(O,"recall-failure","already banked weeks earlier (B265/B352): a non-recall failure","high"),
"B592":(P,"C-symmetry-cancellation","C-symmetry of the state makes every closed theta-odd amplitude vanish for every gluing","high"),
"B596":(O,"value-miss","the θ-odd block's clock is not the naive cat-map period in any registered form","medium"),
"B597":(O,"premise-false","structurally exclude the free-rotation outcome C (conditionally)","low"),
"B600":(F,"zero-invariant","Z₄ = Tr ρ₄(A₁) = 0 and Tr(Θρ₄) = 0 at E₆ level 4","medium"),
"B602":(O,"value-miss","all X1 cells fail with residual exactly −π/15","medium"),
"B606":(O,"arithmetic-mismatch","no partners in the hearing integers","medium"),
"B611":(O,"premise-false","Both sealed predictions failed","medium"),
"B612":(O,"premise-false","The sealed per-level pairing biconditional FAILED","medium"),
"B631":(O,"value-miss","does not match PMNS at the 1% tier: 0/9 entries within 0.01","high"),
"B633":(O,"value-miss","the last SM residual dissolves (p = 0.078 becomes 0.145-0.62)","medium"),
"B639":(O,"no-landing-site","admits no representation-twisted amalgam realization in any tested class","medium"),
"B643":(O,"no-landing-site","no invertible global companion exists (solution dimension 1, singular)","medium"),
"B655":(O,"premise-false","its anchors contradict the banked cards","high"),
"B658":(O,"no-landing-site","break on the weld double's 27 local system (solution dimension 1","medium"),
"B660":(F,"zero-coupling","an exactly zero v₀-mediated trilinear","low"),
"B671":(N,"gauge-dependent","scalarization-gauge rather than object content","medium"),
"B674":(F,"trace-silent","trace-silent (tr(A₁*|H¹(Symᵐ))=0 for all m)","medium"),
"B678":(O,"premise-false","no growth in any of 96 cells, refuting chat1's amphichiral-suppression mechanism","medium"),
"B686":(N,"convention-dependent","Q = 2/3 is a parametrization tautology for every phase and theta0 = 2/9 is convention-dependent","medium"),
"B697":(N,"tautology-not-specific","a tautological Gaussian period carrying no object-specific content","low"),
"B713":(N,"non-canonical-bit","'which chirality' is a non-canonical Galois torsor bit","low"),
"B716":(N,"observer-supplied","Time, 4-dimensionality and Lorentzian signature are all the observer's","high"),
"B718":(O,"arithmetic-mismatch","SL(2,F_p) is McKay only at p=3,5","low"),
"B719":(N,"no-preferred-size","Multiplicity/scale is the observer's — every cover's volume is exactly degree·base with no preferred size","high"),
"B728":(O,"arithmetic-mismatch","zeta_5 is impossible in the resummed object","medium"),
"B729":(O,"arithmetic-mismatch","every native invariant yields only the two quadratic fields","high"),
"B735":(N,"generic","generic to every cusped hyperbolic manifold","medium"),
"B737":(N,"not-object-specific","the ζ_K in the object's voice is the field's (vacuity plus object-deletion)","low"),
"B740":(O,"arithmetic-mismatch","no closed filling of m004 re-sees sqrt(-3)","medium"),
"B743":(O,"value-miss","contain no SM ratio at testable precision","high"),
"B747":(O,"arithmetic-mismatch","all 78 fillings' invariant trace fields are √5-free","high"),
"B748":(O,"arithmetic-mismatch","None of the 78 hyperbolic fillings in the |p|,q <= 8 child grid re-sees the meeting face Q(sqrt-15)","high"),
"B751":(N,"scale-knob-dependent","the target is scale-knob-dependent, and the hits are null-consistent","low"),
"B752":(N,"base-rate","its c*phi^-n hits are base-rate by its own decision rule","medium"),
"B754":(O,"unstated","17 KILL-EXTENDS, 2 FACE-IRRELEVANT and 0 FACE-OPENS","low"),
"B756":(O,"premise-false","dies on five exact counterexamples","high"),
"B757":(O,"premise-false","The two Z/3's are never the same element (deck reps are torsion-free)","medium"),
"B760":(N,"no-selection","canonically signs the theta-odd chord sector: the object cannot close itself","medium"),
"B772":(O,"unstated","only 4 are load-bearing; the corpus is seam-independent","low"),
"B775":(O,"no-landing-site","walls the mover door (no object-native outer operation)","low"),
"B790":(O,"instrument","LMFDB holds no Bianchi Laplace data, three tests are vacuous","medium"),
"B793":(O,"instrument","the B788 solver is bounded refinement inside a supplied window, cannot count roots","high"),
"B802":(P,"reversal-invariance","reversal leaves the Fibonacci letter frequencies unchanged","low"),
"B808":(O,"instrument","34 of 35 are artifacts and the lone survivor is below chance expectation","medium"),
"B811":(O,"no-landing-site","a scale-free object cannot emit a scale-dependent value","low"),
"B812":(O,"no-landing-site","zero genuine paths: five blocked by M (no computed mechanism","low"),
"B813":(O,"no-landing-site","cannot fill the coefficient slot of e^{iθW(A)}","high"),
"B814":(O,"premise-false","the component is a smooth 6-fold (15 vanishing cross-pairings, unobstructed to third order), not dimension 1","medium"),
"B821":(O,"instrument","failed its sealed vacuity ceiling (46.2% of the corpus vs ≤25%)","medium"),
"B824":(O,"instrument","failed its sealed vacuity ceiling at 18.4% of the corpus","medium"),
}
out=[]
for x in d:
    if x['id'] in r:
        k,l,q,c=r[x['id']]
        assert q in x['claim_killed'],(x['id'],q)
        assert len(q.split())<=20,(x['id'],len(q.split()))
    else:
        assert not x['claim_killed']
        k,l,q,c=O,"unstated","","high"
    out.append({"id":x['id'],"kind":k,"label":l,"quote":q,"confidence":c})
json.dump(out,open('out_3.json','w'),ensure_ascii=False,indent=1)
from collections import Counter
print(Counter(o['kind'] for o in out),len(out))
