import json
d=json.load(open('batch_2.json'))
O='OTHER';P='PAIRING';F='FLATNESS';N='NON-UNIQUENESS'
R=[
(O,'premise-false','S₃-invariant SL(2,ℂ) character variety of dim 2 = rank SU(3)','low'),
(O,'arithmetic-mismatch',"monodromy multiplier equals the seed's φ²",'medium'),
(O,'premise-false','The gap-labeling spectral rank equals the composition period k','medium'),
(O,'premise-false','The spectral rank climbs with the SL(n) tower depth','medium'),
(O,'premise-false','A measurable gap-labeling-rank prediction built on K-K/K-L','low'),
(N,'numerology','value-numerology','low'),
(N,'genericity','distinguishes it from other hyperbolic words','medium'),
(O,'scope',"NO invariant escapes the trace ring's discretely-multivalued-and-unsymmetric behavior",'low'),
(O,'premise-false','triality on the 27 gives three symmetric generations','low'),
(O,'no-landing-site','manifoldlike causal set','high'),
(O,'no-landing-site','hosts the object\'s full signature set','high'),
(O,'premise-false','selects SO(9)=B₄ inside F₄','low'),
(O,'no-landing-site','reaches the multiplicity-2 char(M²) sector before n=5','low'),
(O,'no-landing-site','An intrinsic (Higgs-like) scale exists on the Hitchin/Higgs side of the object','medium'),
(O,'instrument','cited-as-sufficient','medium'),
(O,'arithmetic-mismatch','sqrt(5/(4 log phi)), not phi','high'),
(O,'no-landing-site','no fusion-to-scattering map exists','high'),
(O,'arithmetic-mismatch','rejected under the Fricke-Vogt normalization','medium'),
(O,'premise-false','not a new uniqueness theorem under the existing selection filters','low'),
(O,'no-landing-site','never reads its invariant, failing the operational self-model criterion','medium'),
(P,'orientation-reversing','generic for all orientation-reversing symmetric-square lifts','low'),
(N,'not-selected','not selected by the framework','medium'),
(O,'arithmetic-mismatch','the literal T^6 quadratic is t^2-27t+1','medium'),
(N,'no-selection','selects no invariant surface without the extra A-sector matching rule','high'),
(N,'no-selection','does not select I=1/4','medium'),
(N,'no-selection','gap-label controls fail to distinguish I=1/4','medium'),
(O,'no-landing-site','fails the self-model criterion','medium'),
(N,'family','leaves an infinite discrete family c^2=(m+2)/4','high'),
(O,'premise-false','conditional on a newly named, underived assumption T1','medium'),
(N,'free-parameter','c stays free, so it does not select I=1/4','high'),
(F,'no-gradient','no intrinsic stationary point at I=1/4','medium'),
(N,'no-selection','higher rank is consistent with S1 but does not derive it','low'),
(O,'premise-false','lambda/h=1 is conditional, not derived','low'),
(O,'instrument','char(DT_0) scatters across seeds','medium'),
(O,'no-landing-site','every attempted bridge','medium'),
(O,'no-landing-site','a root-system fact that functoriality cannot dissolve','low'),
(O,'no-landing-site','closing the Lorentzian-emergence reading','medium'),
(O,'premise-false','present by construction, not emergent or derived spacetime','low'),
(O,'scope','the tower is a trivial-rep phenomenon','high'),
(O,'scope',"not the Dickson tower, confirming the two fixed points carry different invariants",'medium'),
(P,'involution','it only sends c to 1/c','low'),
(O,'no-landing-site','The off-locus irreducible sector is empty','medium'),
(O,'arithmetic-mismatch','is about k^(n-1), not k','high'),
(O,'scope','equals the tower only through n=5 and diverges at n=6','medium'),
(O,'no-landing-site','the principal degree=rank object is absent for n>=5','medium'),
(O,'no-landing-site','no 3-manifold supplies the 2d-boundary data','high'),
(O,'unstated','Chirality, topology and arithmetic each kill the physics-bridge claims','low'),
(F,'no-new-content','climbing ranks acquires no new field or content','low'),
(N,'free-parameter','kappa is free on the fixed locus, so a single seed cannot force any choice','high'),
(O,'scope','only m=1 has lambda<2','medium'),
(P,'mirror','the mirror preserves every computed invariant except the Chern-Simons sign','high'),
(P,'mirror','structurally mirror-blind','medium'),
(P,'mirror','Cusp-glued composites are mirror-closed','high'),
(P,'amphichiral','coincides with the self-mirror (amphichiral) family','high'),
(O,'no-landing-site','no kappa- or volume-type invariant can source a physical scale','medium'),
(O,'no-landing-site','cannot source an internal scale','medium'),
(O,'no-landing-site','every emergent rate is dimensionless, so the ensemble yields no scale','medium'),
(N,'numerology','value-matching, fails a random-base null control','medium'),
(F,'no-dynamics','zero Lyapunov, no transition','medium'),
(F,'no-relaxation','matches the extended chain, decays with L','low'),
(O,'instrument','a graded-DAG truncation artifact, reproduced by a random null','medium'),
(N,'no-selection','never converges to a forced-unique value','high'),
(O,'scope','non-generic in the metallic family','low'),
(O,'no-landing-site','No GUT-style McKay breaking chain exists','medium'),
(F,'no-hierarchy','entirely O(1) and BSD-generic: no forced small number, no hierarchy','low'),
(O,'scope','it governs the cusped volume, while the closed-bundle period stays algebraic','medium'),
(O,'no-landing-site','no conserved fermion parity and hence no exact lattice supercharge','medium'),
(N,'coincidence','is a central-charge coincidence with a different coset','medium'),
(O,'arithmetic-mismatch','the metallic mean equals the spin-½ quantum dimension iff m=1','medium'),
(O,'arithmetic-mismatch','ℚ(√−7) never appears','high'),
(O,'premise-false','different type (flavor vs gauge) and specificity','medium'),
(N,'no-selection','does not resolve the three SL(3,ℂ) character-variety components','low'),
(O,'value-miss','grows at the complement volume 2.0299, group-independently, not at the SL(3) geometric 8.1195','medium'),
(O,'no-landing-site','no SU(2) enhancement','medium'),
(O,'arithmetic-mismatch','branches as 2+2 (two distinct doublets), not triplet+singlet','medium'),
(N,'no-selection','does not distinguish E₆','medium'),
(N,'genericity','generic to any hyperbolic knot','medium'),
(O,'premise-false','the prime-absence claim is falsified','low'),
(N,'genericity','a generic smooth point','medium'),
(O,'scope','an open-object property destroyed by closing','medium'),
(O,'no-landing-site','none supplies the N=2→N=1 chiral datum','medium'),
(O,'arithmetic-mismatch','gives multiplicities 1 or 2 across seven independent routes, never 3','high'),
(O,'no-landing-site','the degree-3 carrier absent','low'),
(N,'no-selection','E6 fixes the coupling but not the texture','medium'),
(N,'numerology','match 12 SM parameters at chance level','high'),
(P,'conjugation','gives n1=n2','medium'),
(N,'no-selection','no forced choice exists','medium'),
(P,'conjugate-to-inverse','elliptic and conjugate to its inverse, forcing chi_27(g) real and n1=n2','high'),
(N,'genericity','the seam\'s arithmetic is generic and carries no value','low'),
(O,'no-landing-site','√−15 is unreachable','high'),
(O,'arithmetic-mismatch','the hoped-for sqrt(-3) signature is absent','medium'),
(O,'value-miss','is disfavoured by data relative to TM1','high'),
(N,'no-selection','no member is marked and no forced choice exists','low'),
(N,'no-selection','The cyclic-cover abelian torsion class carries no forced choice','low'),
(P,'real-cancellation','all 605 gauge-invariant triple products are exactly real','low'),
(F,'null-readout','seam readout identically null in all six words','high'),
(O,'scope','the seam/value-sector coincidence is exclusive to level 15','medium'),
(O,'no-landing-site','No transport law of the registered forms exists','medium'),
(P,'mirror','the mirror is summation-emergent with no cell-local Galois origin','low'),
(N,'numerology','banks as numerology-class','high'),
(O,'no-landing-site','closing the object\'s last internal scale-lever candidate','low'),
]
assert len(R)==len(d)==101,(len(R),len(d))
out=[]
for e,(k,l,q,c) in zip(d,R):
    src=e['claim_killed']+' || '+e['kill_form']
    assert q in src,(e['id'],q)
    assert len(q.split())<=20
    out.append(dict(id=e['id'],kind=k,label=l,quote=q,confidence=c))
json.dump(out,open('out_2.json','w'),ensure_ascii=False,indent=1)
from collections import Counter
print(Counter(o['kind'] for o in out),len(out))
