import json
d=json.load(open('batch_r1.json'))
P,F,N,O="PAIRING","FLATNESS","NON-UNIQUENESS","OTHER"
R=[
("B268",O,"unstated","wall #1 dissolved, wall #2 reduced to a single physics conjecture","medium"),
("B315",O,"no-landing-site","pseudoreality FS(56)=-1 the shared root among three independent obstructions","low"),
("B348",P,"galois-amphichiral-pairing","Galois orbit {β,−β} summing to zero","high"),
("B363",O,"scope","all 225 one-sided twists and the one-slot theta lift are dark","low"),
("B384",O,"value-miss","the triangular (S,T) slot block gives a sector NO-MATCH","medium"),
("B434",O,"arithmetic-mismatch","the Meyerhoff manifold with new arithmetic (disc -283)","low"),
("B454",O,"no-landing-site","the word channel can never leave ℚ(√−3)","medium"),
("B470",O,"no-landing-site","level-2 trace fields escalate per rung and escape level-1 laundering","low"),
("B497",O,"unstated","End(F₂) on the character variety splits into four strata","low"),
("B524",O,"no-landing-site","F4-by-phi is word-hyperbolic but not a 3-manifold group","medium"),
("B540",O,"instrument","correcting B535's window-length-limited census","medium"),
("B564",O,"no-landing-site","The SL(3) phi-fixed locus contains no irreducible representation","medium"),
("B588",P,"even-odd-sector-exchange","identical sqrt5 Gauss data is even on one stage and odd on the other","medium"),
("B638",P,"antilinear-involution","The deck swap is an antilinear involution with Eisenstein-unit spectrum","medium"),
("B680",O,"unstated","Verified exactly that Vol(4_1) = (3sqrt3/2) L(chi_-3, 2)","low"),
("B700",N,"torsor-no-canonical-choice","the canonical torsor-iso is provably obstructed","medium"),
("B739",O,"no-landing-site","carrying no level characters","medium"),
("B753",O,"premise-false","refuting the disputed 108°/'different quantity' claim","medium"),
("B766",N,"free-choice-torsor","time's arrow and the basepoint bit are one choice","medium"),
("B780",O,"instrument","the signatures were hardcoded literals, not computed booleans","high"),
("B797",O,"value-miss","the sealed SM comparison returns zero gated hits","high"),
("B839",O,"instrument","the non-3 denominator is an EXPANSION ARTIFACT","high"),
("B13",O,"unstated","contains the A-sector as an exact rank-2 lattice-conjugate block","low"),
("B64",P,"parity-sector","even-|k| char(M^k) is P-symmetric, odd-|k| P-antisymmetric","medium"),
("B112",P,"involution-reversal","The opposition involution acts on height-h A(n-1) root spaces as a reversal","medium"),
("B125",O,"arithmetic-mismatch","arithmeticity selects m=1 (Q(sqrt-3)) and m=2 (Q(i)) and kills m>=3","high"),
("B141",O,"scope","The phi-fixed principal tower is reducible for all n>=3 by Q8 finiteness","medium"),
("B155",O,"unstated","An explicit SL(4,Z) matrix realizes figure-eight monodromy times an order-6 phase","low"),
("B171",O,"instrument","leaving the rank-3 combination gap unsettled","low"),
("B211",O,"instrument","not 40a1 (its σ-quotient); the point counts are isogeny-invariant and stand","medium"),
("B227",O,"unstated","has an explicit Seifert dual","low"),
("B256",O,"no-landing-site","remaining the one group with no geometric realization","medium"),
("B316",O,"arithmetic-mismatch","disc -7 is below the unimodular floor","medium"),
("B366",N,"selection-resolved","the lift is not a choice","low"),
("B386",O,"unstated","factorizes exactly as C3 times C5 on all 240 cells","low"),
("B415",O,"value-miss","the registered SM-emergence bar was not cleared","high"),
("B436",O,"premise-false","the '-283 equals figure-eight fingerprint' reading is corrected to a class property","high"),
("B471",O,"unstated","the unique metallic pair whose commutator is parabolic and closes the cusp","low"),
("B527",N,"family-not-point","Stein evolution selects no metric","high"),
("B589",P,"theta-odd-pairs","The three E₆₂ θ-odd pair amplitudes","low"),
("B601",P,"odd-trace-law","trace(B_odd)(kappa) = [5|kappa]/phi - [4|kappa] holds exactly","low"),
("B683",O,"premise-false","the inert-5 monofocal reading fails","high"),
("B702",O,"premise-false","The arc's law 'metallic hearing iff real-quadratic swap field' is retracted as a swap/weld conflation","high"),
("B722",O,"no-landing-site","with no free continuous parameter","medium"),
("B781",O,"unstated","m004 is uniquely selected over its V4-sharing sister m003","low"),
("B14",P,"orientation-reversal","L_aR_b has an orientation-reversing integer square root iff a=b","medium"),
("B65",O,"unstated","factors directly into the seven Dickson factors","low"),
("B113",O,"scope","confines degree=rank to the height-1/top-power interface","low"),
("B142",F,"reducible-by-finiteness","proves the principal phi-fixed stratum reducible without any search","low"),
("B156",O,"unstated","Six Omega strict-full theorems were independently re-derived","low"),
("B173",N,"rank-not-point","The woven two-seed gap-label group is rank 3","low"),
("B196",O,"unstated","Delta = -(ln lambda_m/pi)^2, exact","low"),
("B212",O,"premise-false","correcting the assumed silver framing","medium"),
("B228",N,"uniqueness-positive","forcing golden as the only SUSY metallic chain","low"),
("B242",P,"level-rank-conjugation","Level-rank duality acts as complex conjugation at κ=5","high"),
("B257",F,"vanishing-complex-volume","vanishing complex volume","medium"),
("B270",F,"vanishing-obstruction","the quadratic cup-product obstruction vanishes in the SL(2)/exponent-1 block","medium"),
("B301",N,"no-unique-selection","not a unique SO(10)","high"),
("B317",O,"no-landing-site","outside the algebraic Lisovyy-Tykhyy list of finite orbits","medium"),
("B368",O,"no-new-values","cyclic covers create no new seam values","medium"),
("B416",O,"no-landing-site","no SM structure, and the structure is generic","high"),
("B479",O,"unstated","with no non-elliptic components; field labels corrected","low"),
("B528",O,"premise-false","the 'U(N-1) nonabelian generic gauge' reading is a structure-group conflation","high"),
("B543",O,"value-miss","100-2500x off the golden lattice","high"),
("B575",F,"vanishing-obstruction","The quadratic obstruction Q(u)=[u∪u] vanishes identically in all six E₆ directions","medium"),
("B590",O,"instrument","R1's SEALED verdict was VACUOUS","high"),
("B617",P,"sign-parity","sign det'(I - Sym^2m A) = (-1)^m","low"),
("B640",O,"scope","the tone law's scope is corrected to det=1","high"),
("B661",O,"no-new-object","no new object","medium"),
("B684",O,"unstated","the generation sum rule is derived as a theorem of the cubic shadow","low"),
("B723",O,"unstated","measurement is identified as the β=1 KMS symmetry breaking","low"),
("B782",N,"no-equivariant-section","it admits no equivariant section","high"),
("B67",O,"unstated","reproduced exactly from the metallic SL(2,C) trace map's fixed locus","low"),
("B83",O,"unstated","L=(-1)^{n-1}M^n on the principal component","low"),
("B158",O,"unstated","Omega is the ABELIANIZED SPECTRAL IMAGE of the metallic trace-map tower","low"),
("B174",N,"continuum-vs-discrete","gives a continuum only on the curve-aligned locus","medium"),
("B201",N,"components-not-point","has exactly four dimension-2 components","low"),
("B229",N,"two-realizations","two distinct 3d-3d bulk realizations","medium"),
("B258",O,"arithmetic-mismatch","coinciding only at m=1","high"),
("B271",P,"amphichiral-locus","Identified the amphicheiral τ-breaking (chirality) locus with the E6-irreducibility locus","low"),
("B286",O,"no-landing-site","wall #4 needs an external 2- or 4-manifold input" if False else "Dehn filling the open complement supplies a forced 10-element exceptional set","low"),
("B302",O,"unstated","lives in the commensurator PGL(2,O₋₃) as a hidden symmetry","low"),
("B318",P,"amphichiral-involution","the Eisenstein Z/2 is the geometric amphichiral involution (complex conjugation)","medium"),
("B337",O,"structure-xor-ordering","the shared arithmetic forcing E6 also forces a degenerate spectrum","medium"),
("B351",P,"sign-pairing","fixed 𝔣₄=52 acting on exponent lines by (−1)^{m+1}","low"),
("B439",N,"multiple-vacua","gives 4 irreducible vacua in the -283 trace field","low"),
]
assert [r[0] for r in R]==[x['id'] for x in d],(len(R))
out=[]
from collections import Counter
for r,x in zip(R,d):
    q=r[3]
    assert q in x['claim_killed'] or q in (x['kill_form'] or ''),r[0]
    assert len(q.split())<=20
    out.append(dict(id=r[0],kind=r[1],label=r[2],quote=q,confidence=r[4]))
json.dump(out,open('out_r1.json','w'),ensure_ascii=False,indent=1)
print(Counter(o['kind'] for o in out),len(out))
