import json
d=json.load(open('batch_r0.json'))
P,F,N,O="PAIRING","FLATNESS","NON-UNIQUENESS","OTHER"
r={
"B54":(O,"positive-result","Exchange commutation [J(m,c),P]=0 holds with c symbolic","medium"),
"B76":(O,"positive-result","order-2k torsion on both sides","low"),
"B93":(P,"parity-sector","parity (contragredient m->-m) is distinct from the Galois involution","low"),
"B106":(O,"positive-result","degree=rank holds eigenvector-by-eigenvector","medium"),
"B121":(O,"no-landing-site","inequivalent to Kostant's principal sl(2) for all n>=3 via the odd-Sym parity obstruction","low"),
"B136":(P,"amphichiral-criterion","fixed by reverse-order-plus-component-swap up to cyclic rotation","medium"),
"B150":(O,"rhyme-only","tau-modularity and magnitude are only rhymes","medium"),
"B222":(O,"positive-result","confirming the golden chain's emergent N=1 supersymmetry","high"),
"B251":(O,"scope","so the E6↔E8 geometric transition is golden-specific","medium"),
"B265":(O,"positive-result","establishing E6-irreducible flat connections on the figure-eight","high"),
"B311":(O,"no-landing-site","N=2 is reducible and N>=4 off-curve, so the chain is not realized","medium"),
"B327":(P,"self-duality","n1=n2 in the 27|2T branching is forced by self-duality","medium"),
"B345":(O,"positive-result","force an anti-diagonal charge-conservation texture","medium"),
"B357":(O,"positive-result","one universal tau = the cusp shape governs every block","high"),
"B380":(P,"galois-symmetry","the mirror is derived as conjugation","low"),
"B449":(O,"premise-false","The disc×disc seam formula is category-confused","high"),
"B466":(P,"deck-exchange","Under sigma the SL(3) Dehn-filling components exchange","medium"),
"B518":(O,"positive-result","kappa is a substrate-independent scale-free universality class","high"),
"B535":(O,"positive-result","determines the substitution uniquely up to conjugacy","high"),
"B584":(P,"theta-odd-cancel","the theta-even block cancels exactly","high"),
"B675":(O,"premise-false","the SU(4)_1 half is REFUTED","high"),
"B695":(O,"premise-false","the claimed emergent chirality is falsified as generic even-rank behaviour","medium"),
"B55":(O,"positive-result","The c=1 fixed-line sector structure is settled for all m","high"),
"B78":(O,"instrument","a method-limit: every converged SL(5) bundle rep is reducible","high"),
"B94":(O,"scope","every sign/parity sector is det=-1-specific","medium"),
"B122":(O,"positive-result","a genuine GL(2)-module identity","high"),
"B137":(O,"positive-result","zero irreducible off-sublocus fixed points escape Q(i)","medium"),
"B187":(F,"thresholdless","stays thresholdless at all interaction strengths","low"),
"B208":(O,"positive-result","the field radicand squarefree(m^2+4) always divides P(m), proved","high"),
"B236":(O,"positive-result","literally the same coset","high"),
"B253":(O,"scope","E6 is the only chirality-capable (complex-fundamental) end","medium"),
"B266":(O,"positive-result","The trace field's unique ramified prime canonically selects E6","high"),
"B293":(O,"no-landing-site","no trajectory k(t) is derived","high"),
"B312":(O,"positive-result","the level itself is generic","medium"),
"B346":(P,"conjugation-grading","symplectic conjugation lambda->1/lambda is exactly its Z/3 charge conjugation","medium"),
"B358":(F,"vanishes-in-lift","vanishes identically in the canonical lift","low"),
"B381":(O,"positive-result","the seam is nonzero exactly when the quantization carries the half-characteristic twist","medium"),
"B410":(O,"positive-result","bright iff some X₃·X₅ carries √−15","high"),
"B451":(O,"instrument","the banked 0.51 was shown to be an early-window artifact","medium"),
"B467":(P,"orientation-bit","the only odd permutation is the orientation-reversing half-monodromy","low"),
"B537":(O,"arithmetic-mismatch","(1,1,5) is proved to be a phantom","high"),
"B560":(O,"positive-result","Chat-3's campaign cells verified and re-derived","high"),
"B586":(P,"antiphase-hearing","4_1's invertibility makes the solo antiphase identically zero","medium"),
"B598":(O,"positive-result","The Kashaev baseline is computed","high"),
"B651":(O,"positive-result","proving the E6 Z-ladder periodic","high"),
"B696":(O,"positive-result","The Eisenstein anatomy campaign is closed","high"),
"B717":(O,"no-landing-site","the observer supplies every closing","medium"),
"B764":(O,"premise-false","C19's sqrt|disc K| form breaks at 5_2","high"),
"B776":(O,"positive-result","the symmetrized product is pure-3 through order 50","high"),
"B794":(O,"premise-false","refuting the narrower norm-split claim","high"),
"B61":(O,"instrument","was a rank-23 forward-word coordinate defect","high"),
"B79":(O,"positive-result","with no cell contradicting it","high"),
"B95":(O,"no-landing-site","degenerates to a reducible dihedral rep at n=5, and is impossible at n>=6","medium"),
"B109":(O,"positive-result","a (2,1) saddle of kappa","high"),
"B123":(O,"positive-result","offered as a third independent m=1 selection criterion","high"),
"B138":(O,"positive-result","the converse stays open","high"),
"B152":(P,"amphichiral-torsion","amphichiral implies 2-torsion Chern-Simons","medium"),
"B169":(O,"instrument","correcting B164's orbit-norm proxy","medium"),
"B209":(O,"no-landing-site","with the four spinorial 2I irreps completing E8 absent","medium"),
"B224":(O,"positive-result","Golden is the unique metallic mean whose anyon chain is superconformal","high"),
"B238":(O,"scope","but only for the figure-eight","medium"),
"B254":(O,"positive-result","Verified the arithmetic spine","high"),
"B267":(O,"positive-result","are the same Lie object","high"),
"B314":(N,"no-forced-choice","hence symmetrizable, not forced","medium"),
"B347":(P,"hyperelliptic-grading","the hyperelliptic involution grades the six lines by (-1)^{m+1}","low"),
"B359":(O,"positive-result","the theta-lift seam form is pair-specific and parity-selective","low"),
"B382":(O,"positive-result","decomposing 1/12 as generic 1/16 plus 5-ramified 1/48","high"),
"B431":(O,"positive-result","two value-level readings corrected as artifacts","medium"),
"B453":(O,"positive-result","the child is IDENTICAL, not merely sharing invariants","high"),
"B469":(P,"double-cover","every metallic bundle double-covers a non-orientable bundle","low"),
"B496":(O,"positive-result","verified, with degree growth 2","high"),
"B522":(O,"positive-result","reducing the tower conjecture to a static multiplicity-splitting problem located at n=5","high"),
"B538":(O,"value-miss","while the SM structural checklist scores 0/3","medium"),
"B587":(O,"positive-result","The tone mechanism is solved","high"),
"B599":(P,"theta-parity-vanishing","vanishes unless the number of θ-odd factors is even","high"),
"B613":(P,"conjugation-closed","the odd hearing spectrum is conjugation-closed at every level","high"),
"B637":(O,"positive-result","All seven registered h0/h1 dimension predictions","high"),
"B795":(O,"positive-result","reproduced by an independently written collocation solver","high"),
"B63":(O,"positive-result","factors over Z[m] into Dickson factors","high"),
"B80":(O,"positive-result","The SL(4) metallic tower is established from first principles","high"),
"B124":(P,"reciprocal-pairing","Reciprocal (lambda,1/lambda) eigenvalue pairing is a generic symplectic fact","medium"),
"B153":(O,"scope","degree=rank is rank-stratified","medium"),
"B210":(O,"positive-result","Golden carries both exceptional McKay groups","high"),
"B226":(O,"scope","separated by the hyperbolic/non-hyperbolic divide","medium"),
"B240":(O,"positive-result","pure integers {1,−2,−2,1}","high"),
"B255":(O,"positive-result","is the unique regular simplex","high"),
}
out=[]
for e in d:
    k,l,q,c=r[e['id']]
    assert q in e['claim_killed'] or q in (e['kill_form'] or ''),e['id']
    assert len(q.split())<=20,e['id']
    out.append(dict(id=e['id'],kind=k,label=l,quote=q,confidence=c))
assert len(out)==86 and len(r)==86
json.dump(out,open('out_r0.json','w'),ensure_ascii=False,indent=1)
from collections import Counter
print(Counter(o['kind'] for o in out))
