import json
d=json.load(open('batch_r2.json'))
P,F,N,O="PAIRING","FLATNESS","NON-UNIQUENESS","OTHER"
R={
"B504":(O,"positive-result","tr(t)^2 = 2 exactly","high"),
"B544":(O,"no-landing-site","the carrier holds only the Q(phi) shadow, not the degree-4 layer","low"),
"B576":(P,"theta-even-vectorlike","theta-even deformations stay F4-stable and vector-like","low"),
"B591":(O,"positive-result","the golden 5-tone's conductor is literally the torsion of the chord's carrier","high"),
"B603":(O,"positive-result","all single-generator L1 contractions are weight-forced","high"),
"B618":(O,"positive-result","The registered third-object prediction passes","high"),
"B663":(O,"positive-result","the heart is an invertible Jordan unit","high"),
"B704":(O,"positive-result","The per-stage torsors assemble into one F2-vector space","high"),
"B769":(O,"positive-result","T1's fixedness under the closing group is forced because <c,theta,gamma_5> = (Z/2)^3 is abelian","medium"),
"B800":(O,"instrument","the claim stays uncomputed","high"),
"B16":(O,"scope","forced by (LX)^2=A but not by axioms A1-A6","low"),
"B69":(O,"positive-result","extends the figure-eight A-polynomial","high"),
"B100":(O,"positive-result","agree with the repo's SL(3) figure-eight character variety","high"),
"B115":(O,"instrument","both remain unsettled, blocked by the missing SL(4) classification","high"),
"B159":(O,"positive-result","all 474 classes reciprocal","high"),
"B175":(O,"positive-result","The woven collective spectrum is two-number predictable","high"),
"B215":(O,"positive-result","is verified exact for conductors f in {2,3,4}","high"),
"B245":(O,"positive-result","extends the SU(2)_k = SU(k)_2 conjugation result beyond the fundamental","high"),
"B259":(O,"premise-false","wall #5's '122 orders' withdrawn per B980","high"),
"B273":(F,"obstruction-vanishes","The full quadratic cup product H¹×H¹→H²(e₆) at ρ_prin is identically zero","medium"),
"B287":(O,"positive-result","unique torus-bundle closing among the ten exceptional fillings","high"),
"B303":(P,"amphichiral-CS-zero","CS=0 amphichiral, definite sign per closing","low"),
"B319":(O,"premise-false","Resolved the woven-vs-single conflict as a false dichotomy","medium"),
"B338":(N,"external-input","the filling slope is external input","low"),
"B352":(F,"obstruction-vanishes","the second-order cup-product obstruction [z u z] vanishes in all six E6 exponent directions","low"),
"B370":(F,"obstruction-vanishes","All six E6 tangent directions at the geometric representation are unobstructed to third order","low"),
"B390":(P,"rank-2-pairing","dark pairs attributed by an exact rank-2 pairing","low"),
"B460":(O,"positive-result","per-vacuum Chern-Simons values computed by a two-gate-validated Kirk-Klassen integral","high"),
"B507":(O,"value-miss","the measurement verb is NOT marginal there","low"),
"B530":(O,"positive-result","its pure discrete spectrum is certified","high"),
"B547":(O,"arithmetic-mismatch","obstructed by an inert prime rather than elliptic rigidity","medium"),
"B620":(O,"positive-result","the object's field has exactly one door","high"),
"B644":(O,"positive-result","all gates pass","high"),
"B665":(N,"trace-not-determining","trace does not determine hearing (RLRL versus R^5L at equal trace)","low"),
"B689":(O,"positive-result","exists only at level 15 = 3*5","high"),
"B707":(O,"instrument","three bridge tests named, none run","high"),
"B786":(F,"trace-trivial","trace-trivial at every rank","low"),
"B830":(O,"positive-result","the Markov quiver is mutation-finite but not finite-type","high"),
"B25":(O,"not-derived","the coupling stays MOTIVATED, not derived","low"),
"B70":(O,"positive-result","closure bounded at bidegree (3,3)","high"),
"B86":(O,"instrument","no new theorem and the external literature check ungated","medium"),
"B102":(O,"no-landing-site","excluded from the Hitchin component by ellipticity, not complexity","medium"),
"B160":(O,"positive-result","kappa=-2 gives the parabolic figure-eight cusp","high"),
"B176":(O,"scope","but the ordering below it breaks","low"),
"B203":(O,"positive-result","explaining B202's missing tidy relation","high"),
"B260":(O,"no-landing-site","zero theorems block object→physics, but no bridge is built","low"),
"B274":(O,"positive-result","making the {4,8} E6-irreducible flat connections exist unconditionally","high"),
"B304":(O,"premise-false","refuted Chat-1's saddle-SU(3) claim","medium"),
"B353":(P,"involution-identity","The hyperelliptic involution induces exactly the E6 diagram involution theta","low"),
"B371":(O,"positive-result","exactly Weil-invariant, dihedrally irreducible, helicity-paired","medium"),
"B391":(O,"positive-result","both registered predictions (243, 625) hit","high"),
"B423":(O,"no-landing-site","figure-eight-specific arithmetic, not SM structure","medium"),
"B509":(O,"positive-result","The square-time curve has rank 0 (proved) and is 40a3","high"),
"B531":(O,"instrument","closed forms remain open","low"),
"B593":(P,"first-order-cancels","with no first-order term","low"),
"B607":(O,"no-landing-site","no subsystem/coset grading exists anywhere else","medium"),
"B621":(O,"positive-result","zero exceptions for kappa = 4..27","high"),
"B645":(O,"positive-result","holds exactly on all six 024-silent doubles","high"),
"B670":(O,"positive-result","every metallic representation lives in one F4-form and h0=1 is canonical","high"),
"B690":(O,"scope","the hearing (5-adic) one does not at all","low"),
"B708":(O,"positive-result","audibility is non-linking with the infinite prime","high"),
"B746":(O,"scope","GAPPED at the voice floor, not confirmed and not refuted","medium"),
"B759":(O,"scope","couple at SL(3)=Sym^2 but not at SL(2)","low"),
"B787":(O,"value-miss","all six doors MISS","medium"),
"B27":(O,"positive-result","retains the A quadratic sector","high"),
"B71":(O,"positive-result","exactly the SL(3) figure-eight character variety","high"),
"B88":(O,"positive-result","finds exactly two components over the spectra searched","high"),
"B103":(O,"positive-result","a class function (all n)","high"),
"B117":(O,"no-landing-site","the 'promotion' is really a Sym-1 absence","low"),
"B131":(O,"positive-result","collapsing the free kappa into a discrete internal fork","medium"),
"B147":(O,"positive-result","so arithmetic chiral bundles exist","high"),
"B162":(O,"positive-result","kappa=2 is the unique fiber with positive-measure spectrum","high"),
"B178":(O,"positive-result","confirmed contamination-robustly","high"),
"B204":(O,"positive-result","A closed-form WRT level-period law holds for ALL once-punctured-torus bundles","high"),
"B218":(O,"no-landing-site","all m>=2 exceed the index-4 wall","medium"),
"B232":(O,"instrument","REDUCED to one unproved plethysm statement","medium"),
"B248":(O,"positive-result","realized as the hyperbolic (ℚ(√−3), 2T) and spherical (ℚ(√5), 2I) ends","high"),
"B261":(O,"positive-result","One AJ recursion carries both ends","high"),
"B275":(O,"positive-result","Exhibited an explicit numerical E6 flat connection on the figure-eight","high"),
"B289":(P,"sign-pairing","CS(p,-q) = -CS(p,q) is robust","medium"),
"B306":(O,"positive-result","Established the forced E6 principal-grading cascade N=1..6","high"),
"B323":(O,"no-landing-site","the omega-circulant Yukawa is tautological and unmatched","low"),
"B340":(P,"amphichiral-cusp","extremal at pi/6 at the amphichiral cusp","low"),
"B354":(O,"no-landing-site","the strong-channel kill (only trivial and quaternion points are shared)","low"),
"B376":(O,"positive-result","identifying the tower as the quantized golden cat map","high"),
"B393":(P,"pairs-annihilate","Dark pairs annihilate termwise rather than by cancellation","medium"),
}
out=[]
for e in d:
    k,l,q,c=R[e['id']]
    t=e['claim_killed']+' '+(e['kill_form'] or '')
    assert q in t,(e['id'],q)
    assert len(q.split())<=20,e['id']
    out.append(dict(id=e['id'],kind=k,label=l,quote=q,confidence=c))
assert len(out)==86 and len(R)==86
json.dump(out,open('out_r2.json','w'),ensure_ascii=False,indent=1)
from collections import Counter
print(Counter(o['kind'] for o in out),len(out))
