import json
d=json.load(open('batch_r3.json'))
O='OTHER';P='PAIRING';F='FLATNESS';N='NON-UNIQUENESS'
U=(O,'unstated')
m={
'B425':(*U,'the object has two torsions','low'),
'B446':(O,'unstated','every channel launders to banked arithmetic','low'),
'B485':(*U,'Closed the metallic Alexander law','low'),
'B510':(O,'premise-false','the roles below are inverted','high'),
'B532':(*U,'period-3 is absent from the spectrum','low'),
'B552':(F,'conserved-invariant','transported unchanged along the observer flow, and it decouples from the double clock','low'),
'B581':(P,'sign-pairing','sign(tau_m) = (-1)^m gives the chirality fold a scalar signature','low'),
'B594':(*U,'its diagonal coefficients equal minus the banked Z/7 sine-kernel closed forms','low'),
'B608':(*U,'The E6 Rosetta table exists only in mixed form','low'),
'B622':(*U,'a second negative data point for the exterior sign law','low'),
'B646':(*U,'one lead killed','low'),
'B691':(P,'self-conjugate-doublet','phi(3)=2 is prime (a minimal self-conjugate doublet)','low'),
'B730':(*U,'ℚ(√−7) is an external stage','low'),
'B789':(N,'rep-dependent','Q is rep-dependent','low'),
'B803':(O,'scope','any derivation routing through it is class-level not the object','medium'),
'B48':(*U,'extends to the whole metallic family','low'),
'B74':(P,'involution-identity','are literally the same involution -w0 of A_{n-1}','low'),
'B89':(*U,'PROVED symbolic-exact over Q(omega)','low'),
'B104':(O,'instrument','localizes the SL(5) failure to eps-series gauge degeneracy (21/24)','low'),
'B118':(O,'premise-false',"B112's assumed uniform +1 holds only for odd h",'medium'),
'B134':(P,'amphichiral-palindrome','a metallic-block bundle is amphichiral iff its block-length sequence is a cyclic palindrome','low'),
'B148':(*U,'pinned exactly','low'),
'B163':(O,'no-landing-site','no spectral feature encodes the figure-eight geometry at kappa=-2','medium'),
'B179':(*U,'with three same-named parameters fenced off','low'),
'B205':(*U,'was constructed and verified in-sandbox','low'),
'B220':(*U,'is gapless with central charge c=0.71','low'),
'B233':(O,'premise-false','not eight miracles','low'),
'B249':(O,'arithmetic-mismatch','making E₆+E₈ and the E₇ exclusion one arithmetic fact','low'),
'B262':(O,'no-landing-site','abelian, confirming McKay-E6 is arithmetic-only','medium'),
'B276':(*U,'values in ℤ[ζ₃], the trace field ℚ(√−3)','low'),
'B290':(O,'premise-false','the filling n is not the WRT level k','low'),
'B324':(O,'no-landing-site','structure, not values','low'),
'B377':(*U,'reproducing all six banked level verdicts','low'),
'B426':(F,'no-invariant-growth','every Galois-invariant functional of its orbit is <1 — no invariant growth','low'),
'B463':(F,'zero-centralizer','The centralizer of the principal sl2 in e6 is exactly zero','medium'),
'B533':(*U,'The coupling is not a gauge choice','low'),
'B556':(*U,'UNSETTLED: the tower-as-physics-ladder reading, banked as a labelled HYPOTHESIS','low'),
'B582':(*U,'so its 27 is complex — chiral matter constructed','low'),
'B595':(*U,"E6_2's fixed theta-odd ear hears no chirality",'low'),
'B609':(*U,'hashed before any comparison exists','low'),
'B629':(*U,'with NO comparison of any kind performed in this arc','low'),
'B647':(N,'not-forced','the core ratio Y[023]/Y[123] is NOT forced','low'),
'B673':(*U,'all three slots of 27x27 couple under a graded sign rule','low'),
'B692':(*U,'no prior art for the E6/bifocal/totient synthesis','low'),
'B714':(*U,'chirality, generations-as-permutable, and all values are negative','low'),
'B732':(P,'outer-automorphism','The observer\'s conjugation is realized as the outer automorphism of A5','low'),
'B761':(F,'zero-fiber','fiber_dim(n)=0 at every rank','medium'),
'B773':(O,'instrument','was a projection artifact','medium'),
'B804':(O,'scope','so its Dirac spectral type is determined but class-level','low'),
'B49':(*U,'is not promoted to a proven claim','low'),
'B75':(O,'scope','not a figure-eight accident','low'),
'B92':(N,'free-parameter','m is free, m=1 selected only by the systole metric','medium'),
'B105':(O,'instrument','The explicit n=5 catalog stays open','medium'),
'B149':(*U,'making M^4=L unconditional on the genuine locus','low'),
'B164':(*U,'bridged to the once-punctured-torus cubic at the void fiber','low'),
'B180':(*U,'cusp-gluing and potential-weaving are distinct-but-analogous operations','low'),
'B206':(*U,'with the classical/quantum divide exactly the A5/2I spin double cover','low'),
'B221':(*U,'proved by three agreeing exact derivations','low'),
'B234':(O,'premise-false','caught one overclaim in each chat','low'),
'B250':(*U,'the arithmetic invariants sit in the volumes','low'),
'B264':(*U,'with {4,8} directions deforming out of F₄','low'),
'B277':(O,'no-landing-site','a chiral 4d SM is blocked by two named inputs','medium'),
'B291':(N,'no-selection','selection is axis-stratified with no universally distinguished closing','high'),
'B309':(*U,'Unified four banked faces','low'),
'B326':(O,'no-landing-site','texture, not magnitudes','low'),
'B344':(P,'reciprocal-pair','forced into a symplectic reciprocal pair (lambda, 1/lambda)','medium'),
'B356':(P,'self-dual','forces a quaternionic self-dual 2 (det-lemma)','low'),
'B379':(P,'galois-conjugate-pair','the Galois-conjugate pair -(phi/6)sqrt(-3) and +(1/6phi)sqrt(-3)','low'),
'B402':(*U,'the untwisted canonical point the unique dark address','low'),
'B427':(P,'galois-exchange','Exchange of the two seam slots acts by the Galois element sigma_17','low'),
'B448':(*U,'no sqrt5 through period 7','low'),
'B488':(*U,'SU(3) flavor enhancement applies only at m=1','low'),
'B517':(*U,'the golden-3d bootstrap coupling is unique','low'),
'B534':(F,'zero-locus','T(j,l)=0 ⟺ jl≡−4 except the (2,−2) survivor','low'),
'B557':(N,'choice','a CHOICE above it (B517 intertwining forces C=p(M))','low'),
'B583':(O,'no-landing-site','vacuum Dehn-filling probes can never hear chirality','low'),
'B610':(*U,'never conjugation-closed, and never leaves the unit circle','low'),
'B649':(N,'object-chosen','VALUE rows are object-chosen','medium'),
'B694':(O,'arithmetic-mismatch','the automorphic avatar structurally cannot carry the golden','medium'),
'B715':(*U,'the non-real adjoint trace excludes every real form','low'),
'B733':(N,'bounded-menu','The menu of observers at the congruence doors is a bounded discrete F_2-space','low'),
'B749':(*U,'F5 and F6 FRAGILE','low'),
'B762':(*U,'so the emitted word is a self-name','low'),
'B774':(*U,'zero overturns','low'),
'B791':(O,'premise-false','dissolving the claimed live defect','low'),
}
out=[]
for e in d:
    k,l,q,c=m[e['id']]
    assert q in e['claim_killed'] or q in (e['kill_form'] or ''),(e['id'],q)
    assert len(q.split())<=20
    out.append(dict(id=e['id'],kind=k,label=l,quote=q,confidence=c))
assert len(out)==85==len(m)
json.dump(out,open('out_r3.json','w'),ensure_ascii=False,indent=1)
from collections import Counter
print(Counter(o['kind'] for o in out))
