#!/usr/bin/env python3
"""B1609 -- THE EVEN SUBWEAVE: both hands global, and the count.  The even subweave is Gamma = ker(SL(2, Z) -> S_3 -> +-1),
the even-length words in L and R (the preimage of A_3, containing Gamma(2)), on which the McKay orientation (omega against
omega^2) is a global choice and the records' orientation is kept.  Exact facts (integers; finite groups):

 E1  Gamma = Z/6 *_{Z/2} Z/6 (generators U = ST and S U S^-1 sharing -I): chi(Gamma; V) = 2 dim V^{<U>} - dim V^{<-I>}, and
     Shapiro: chi(Gamma; V) = chi(SL; V) + chi(SL; V (x) eps), eps the sign of the permutation of the three parities
     (eps(S) = -1, eps(U) = +1, eps(-I) = +1); checked on Sym^k, k = 0, 2, ..., 22, with the sign-twisted SL-amalgam
     dim (V (x) eps)^{<S>} = the (-1)-eigenspace of S.
 E2  the E6 count on Gamma: -chi(Gamma; 27) for 27 = Sym16 + Sym8 + Sym0 (the principal sl2; also E6(a1), E6(a3)), and the
     78 control.
 E3  the level-2 cover Gamma(2) (free of rank 2 modulo -I): chi(Gamma(2); Sym^k) = -(k + 1) for k even, = chi(SL; V) +
     chi(SL; V (x) eps) + 2 chi(SL; V (x) std) with std the two-dimensional irreducible of S_3; the S_3-decomposition of
     the level-2 count of the 27; the Z/3 = Gamma/Gamma(2) sectors chi(Gamma; 27 (x) omega^j) for j = 0, 1, 2 by the
     Gamma-amalgam (omega(U) = omega, omega(S U S^-1) = omega^2) and by Shapiro (Ind omega = std).
 E4  the puncture on the even subweave: the lifts of even words generate a subgroup of 2O on the six local solutions
     (B1606's model); its order, commutant, isotypic pieces (their dimensions and the eigenvalues of the lift of LR on
     each), the kept dimensions and indices; with the parity grading; and which isotypic pieces the deck involution
     (conjugation by the lift of L) fixes or exchanges.
Writes even_subweave.json.  `python3 even_subweave.py --controls` computes only the banked controls (W20's chi(SL(2, Z);
Sym^k), B1600; the moves' group on the six local solutions, B1606) and writes controls.json; no cell."""
import json, pathlib, itertools, sys
import numpy as np, sympy as sp
HERE = pathlib.Path(__file__).resolve().parent
x, y = sp.symbols("x y")


def sym_matrix(M, k):
    a, b, c, d = [sp.Integer(int(v)) for v in np.array(M).flatten()]
    basis = [x ** (k - j) * y ** j for j in range(k + 1)]; cols = []
    for p in basis:
        q = sp.expand(p.subs({x: a * x + c * y, y: b * x + d * y}, simultaneous=True)); poly = sp.Poly(q, x, y)
        cols.append([poly.coeff_monomial(x ** (k - j) * y ** j) for j in range(k + 1)])
    return np.array(cols, dtype=complex).T


S = np.array([[0, -1], [1, 0]]); T = np.array([[1, 1], [0, 1]]); U = S @ T; MI = -np.eye(2, dtype=int)
SUS = S @ U @ np.linalg.inv(S).astype(int)
w = np.exp(2j * np.pi / 3)
# characters / representations of SL(2, Z) through S_3 = SL(2, F_2), as dicts on the generators we use
EPS = {"S": -1, "U": 1, "SUS": 1, "MI": 1}
STD = {"S": np.array([[0, 1], [1, 0]], dtype=complex), "U": np.array([[0, -1], [1, -1]], dtype=complex), "MI": np.eye(2, dtype=complex)}
STD["SUS"] = STD["S"] @ STD["U"] @ np.linalg.inv(STD["S"])
OMEGA = {"U": w, "SUS": w ** 2, "MI": 1}                   # a character of Gamma (U and SUS^-1 are the two 3-cycles)
MAT = {"S": S, "U": U, "SUS": SUS, "MI": MI}


def order_of(A):
    n = A.shape[0]; P = A.copy(); o = 1
    while not np.allclose(P, np.eye(n)):
        P = P @ A; o += 1
        if o > 100: raise RuntimeError("order")
    return o


def fixed_dim(A):
    """dim of the invariants of the cyclic group generated by A (finite order)"""
    o = order_of(A)
    return int(round((sum(np.trace(np.linalg.matrix_power(A, i)) for i in range(o)) / o).real))


def module(name, k, twist=None):
    """the matrix of generator `name` on Sym^k, optionally tensored with eps, std or omega"""
    A = sym_matrix(MAT[name], k)
    if twist == "eps": return A * EPS[name]
    if twist == "std": return np.kron(A, STD[name])
    if twist == "omega": return A * OMEGA[name]
    if twist == "omega2": return A * np.conj(OMEGA[name])
    return A


def chi_SL(k, twist=None):
    return fixed_dim(module("S", k, twist)) + fixed_dim(module("U", k, twist)) - fixed_dim(module("MI", k, twist))


def chi_Gamma(k, twist=None):
    return fixed_dim(module("U", k, twist)) + fixed_dim(module("SUS", k, twist)) - fixed_dim(module("MI", k, twist))


def chi_Gamma2(k):
    """Gamma(2) contains -I; modulo -I it is free of rank 2; -I acts on Sym^k by (-1)^k"""
    return -(k + 1) if k % 2 == 0 else 0


# ---- the six local solutions (B1606's model)
I2 = np.eye(2, dtype=complex); qi = np.array([[1j, 0], [0, -1j]]); qj = np.array([[0, 1], [-1, 0]]); qk = qi @ qj; s = 1 / np.sqrt(2)
LIFT = {"L": (I2 + qi) * s, "R": (I2 - qj) * s}
PAR = [(1, 0), (0, 1), (1, 1)]; UQ = {(1, 0): qj, (0, 1): qi, (1, 1): qk}
MOVES = {"L": {"a": "a", "b": "ab"}, "R": {"a": "ab", "b": "b"}}
def chi_p(p, letter): return (-1) ** (p[0] if letter == "a" else p[1])
def act_parity(m, p):
    sa = np.prod([chi_p(p, c.lower()) for c in m["a"]]); sb = np.prod([chi_p(p, c.lower()) for c in m["b"]])
    return (0 if sa == 1 else 1, 0 if sb == 1 else 1)
def six(m, g):
    M = np.zeros((6, 6), dtype=complex)
    for ip, p in enumerate(PAR):
        q = act_parity(MOVES[m], p); iq = PAR.index(q)
        M[2 * iq: 2 * iq + 2, 2 * ip: 2 * ip + 2] = np.linalg.inv(UQ[q]) @ g @ UQ[p]
    return M
GL, GR = six("L", LIFT["L"]), six("R", LIFT["R"])
def group(gens, n=6):
    G = [np.eye(n, dtype=complex)]; fr = [np.eye(n, dtype=complex)]
    while fr:
        M = fr.pop()
        for g in gens:
            N = M @ g
            if not any(np.allclose(N, E, atol=1e-7) for E in G):
                G.append(N); fr.append(N)
                if len(G) > 5000: raise RuntimeError("not finite")
    return G
def commutant_basis(G, n=6):
    rows = [np.kron(np.eye(n), g) - np.kron(g.T, np.eye(n)) for g in G]
    A = np.vstack(rows); U_, sv, Vh = np.linalg.svd(A); c = int(sum(1 for v in sv if v < 1e-8))
    return [Vh[-i - 1].conj().reshape(n, n, order="F") for i in range(c)]
def isotypic(G, n=6, seed=1608):
    basis = commutant_basis(G, n); rng = np.random.default_rng(seed)
    X = sum(rng.normal() * B for B in basis); ev, V = np.linalg.eig(X)
    pieces = {}
    for e, v in zip(ev, V.T):
        key = tuple(np.round([e.real, e.imag], 5)); pieces.setdefault(key, []).append(v)
    return len(basis), [np.array(vs).T for vs in pieces.values()]


def controls():
    """banked numbers only: W20's chi(SL(2, Z); Sym^k) as B1600 recorded it, and B1606's group of the moves on C^6"""
    import os
    frontier = pathlib.Path(os.environ.get("OA_FRONTIER", HERE.parents[1]))
    f = frontier / "B1600_the_weave_verified" / "verification" / "w20_w22_check.json"
    w20 = json.load(open(f)) if f.exists() else None
    ks = list(range(0, 23, 2)); mine = {k: chi_SL(k) for k in ks}
    G = group([GL, GR]); c, pieces = isotypic(G)
    out = {"chi_SL_Sym_k": mine, "matches_B1600": (None if w20 is None else all(int(w20["chi_SL2Z_Sym_k"][str(k)]) == mine[k] for k in mine if str(k) in w20["chi_SL2Z_Sym_k"])),
           "moves_on_C6": {"order": len(G), "commutant": c, "isotypic_dimensions": sorted(P.shape[1] for P in pieces)}}
    json.dump(out, open(HERE / "controls.json", "w"), indent=1, default=str); print(json.dumps(out, indent=1, default=str))


def cells():
    out = {}
    ks = list(range(0, 23, 2))
    E1 = {"chi_SL": {k: chi_SL(k) for k in ks}, "chi_SL_eps": {k: chi_SL(k, "eps") for k in ks}, "chi_Gamma": {k: chi_Gamma(k) for k in ks}}
    E1["shapiro_holds"] = all(E1["chi_Gamma"][k] == E1["chi_SL"][k] + E1["chi_SL_eps"][k] for k in ks)
    E1["orders"] = {"S": order_of(S.astype(complex)), "U": order_of(U.astype(complex)), "SUS": order_of(SUS.astype(complex))}
    out["E1"] = E1
    dec = {"E6 (principal)": [16, 8, 0], "E6(a1)": [12, 8, 4], "E6(a3)": [8, 6, 4, 4, 0], "78 through the principal sl2": [22, 16, 14, 10, 8, 2]}
    out["E2"] = {"minus_chi_SL": {n: -sum(chi_SL(k) for k in kk) for n, kk in dec.items()},
                 "minus_chi_Gamma": {n: -sum(chi_Gamma(k) for k in kk) for n, kk in dec.items()},
                 "minus_chi_SL_eps_twisted": {n: -sum(chi_SL(k, "eps") for k in kk) for n, kk in dec.items()}}
    E3 = {"chi_Gamma2": {k: chi_Gamma2(k) for k in ks}, "chi_SL_std": {k: chi_SL(k, "std") for k in ks}}
    E3["shapiro_level2_holds"] = all(chi_Gamma2(k) == E1["chi_SL"][k] + E1["chi_SL_eps"][k] + 2 * E3["chi_SL_std"][k] for k in ks)
    E3["level2_count_27"] = -sum(chi_Gamma2(k) for k in (16, 8, 0))
    E3["S3_decomposition_of_27"] = {"trivial": out["E2"]["minus_chi_SL"]["E6 (principal)"], "sign": out["E2"]["minus_chi_SL_eps_twisted"]["E6 (principal)"],
                                    "std (times 2)": -sum(E3["chi_SL_std"][k] for k in (16, 8, 0))}
    E3["Z3_sectors_on_Gamma"] = {"omega^0": -sum(chi_Gamma(k) for k in (16, 8, 0)), "omega": -sum(chi_Gamma(k, "omega") for k in (16, 8, 0)), "omega^2": -sum(chi_Gamma(k, "omega2") for k in (16, 8, 0))}
    E3["omega_sector_equals_std_sector"] = E3["Z3_sectors_on_Gamma"]["omega"] == E3["S3_decomposition_of_27"]["std (times 2)"]
    E3["sectors_sum_to_level2_count"] = sum(E3["Z3_sectors_on_Gamma"].values()) == E3["level2_count_27"]
    out["E3"] = E3

    gens_even = [A @ B for A in (GL, GR, np.linalg.inv(GL), np.linalg.inv(GR)) for B in (GL, GR, np.linalg.inv(GL), np.linalg.inv(GR))]
    G_even = group(gens_even); G_full = group([GL, GR])
    c, pieces = isotypic(G_even)
    dims = sorted(P.shape[1] for P in pieces)
    subs = sorted({sum(cc) for r in range(len(dims) + 1) for cc in itertools.combinations(dims, r)})
    LR = GL @ GR
    def eig_on(piece, M):
        """eigenvalues of M restricted to the invariant subspace spanned by piece's columns"""
        Q, _ = np.linalg.qr(piece); A = Q.conj().T @ M @ Q
        return sorted(np.round(np.linalg.eigvals(A), 6).tolist(), key=lambda z: (round(z.real, 6), round(z.imag, 6)))
    E4 = {"order_full": len(G_full), "order_even": len(G_even), "commutant_even": c, "isotypic_dimensions": dims,
          "kept_dimensions": subs, "kept_indices": [d - 3 for d in subs], "minus_one_in_even_group": bool(any(np.allclose(g, -np.eye(6), atol=1e-7) for g in G_even)),
          "LR_lift_order": order_of(LR), "LR_eigenvalues_on_pieces": [[str(z) for z in eig_on(P, LR)] for P in pieces]}
    # the deck involution: conjugation by the lift of L maps each isotypic piece to some isotypic piece
    def piece_index(v):
        for i, P in enumerate(pieces):
            Q, _ = np.linalg.qr(P)
            if np.allclose(Q @ (Q.conj().T @ v), v, atol=1e-6): return i
        return None
    E4["deck_L_maps_pieces_to"] = [piece_index(GL @ P[:, 0]) for P in pieces]
    grading = [np.diag(np.repeat([1 if k == j else -1 for k in range(3)], 2)).astype(complex) for j in range(3)]
    G_eg = group(gens_even + grading); cg, pg = isotypic(G_eg); dg = sorted(P.shape[1] for P in pg)
    E4["even_and_grading"] = {"order": len(G_eg), "commutant": cg, "isotypic_dimensions": dg,
                              "kept_dimensions": sorted({sum(cc) for r in range(len(dg) + 1) for cc in itertools.combinations(dg, r)})}
    E4["even_and_grading"]["kept_indices"] = [d - 3 for d in E4["even_and_grading"]["kept_dimensions"]]
    out["E4"] = E4
    json.dump(out, open(HERE / "even_subweave.json", "w"), indent=1, default=str); print(json.dumps(out, indent=1, default=str))


if __name__ == "__main__":
    controls() if "--controls" in sys.argv else cells()
