#!/usr/bin/env python3
"""B1617 -- THE WEAVE AT tau = omega (given tau = omega: the owner's tagged postulate of 2026-10-08).  Choosing the fibre's
modulus breaks the weave's symmetry to the stabiliser of tau: the automorphisms of F2 whose action on H_1 fixes omega --
the order-3 elliptic class (U = [[0, -1], [1, 1]] and its powers, with -I) together with every inner automorphism (which
acts trivially on tau).  Their lifts act on W10's V = T + T-bar.  Exact up to floating point:
 Z0  the conventions: the H_1 matrix of an automorphism (columns = images of a, b), its Moebius action on tau, and the
     composition order of W10's move matrices (checked on a composite).
 Z1  the residual group at omega on V: generated by the lifts of an automorphism whose H_1 matrix is U, of the sign iota
     (a -> a^-1, b -> b^-1, H_1 matrix -I), and of conjugation by a and by b; its order; whether it preserves T.
 Z2  T under the residual group: irreducible or split; the characters of the pieces (the residual charges); whether the
     inner automorphisms act on V as the parity signs.
 Z3  the mass terms at exactly omega: for every irreducible r of T-bar (x) T and of Sym^2 T (B1615, B1616), the vacua fixed by the
     residual group and the resulting spectra (Dirac: singular values; Majorana: Takagi), with the number of free couplings.
 Z4  the near-omega pattern: the eigenvalues of U's lift on T as cube or sixth roots of unity -- the residual charges q_i --
     and the charge differences q_i - q_j mod 3 that, in the Novichkov-Penedo-Petcov mechanism (imported, tagged), set the
     powers of epsilon = tau - omega in each mass-matrix entry.
No data is read.  Writes weave_at_omega.json."""
import json, pathlib, sys, os, importlib.util, itertools
import numpy as np
HERE = pathlib.Path(__file__).resolve().parent
FRONTIER = pathlib.Path(os.environ.get("OA_FRONTIER", HERE.parents[1]))
spec = importlib.util.spec_from_file_location("nm", FRONTIER / "B1616_the_neutrino_masses_on_the_weave" / "verification" / "neutrino_masses_on_the_weave.py")
nm = importlib.util.module_from_spec(spec); spec.loader.exec_module(nm)
cw = nm.cw; cp = nm.cp; W = cp.W; TB = cp.TB
I2 = np.eye(2, dtype=complex); qi, qj = W.qi, W.qj


def inv(w): return "".join(c.swapcase() for c in reversed(w))
def red(w):
    o = []
    for c in w:
        if o and o[-1] == c.swapcase(): o.pop()
        else: o.append(c)
    return "".join(o)
def apply(auto, w): return red("".join(auto[c] if c.islower() else inv(auto[c.lower()]) for c in w))
def compose(f, g): return {x: apply(f, g[x]) for x in "ab"}              # f after g
def h1(auto): return np.array([[auto[x].count("a") - auto[x].count("A"), auto[x].count("b") - auto[x].count("B")] for x in "ab"]).T
def rho_word(w): return W.rep(w, (0, 0))
H = cp.H                                                                    # B1610's module (via B1611's)
def lift_of(auto):
    A, B = rho_word(auto["a"]), rho_word(auto["b"])
    for g in H.TWO_O:
        if np.allclose(g @ qi @ np.linalg.inv(g), A) and np.allclose(g @ qj @ np.linalg.inv(g), B): return g
    return None
def M_of(auto):
    g = lift_of(auto); return None if g is None else W.move_matrix(auto, g)


def order_n(A):
    P = A.copy(); n = 1
    while not np.allclose(P, np.eye(A.shape[0]), atol=1e-8):
        P = P @ A; n += 1
        if n > 200: return None
    return n


def mobius(Mx, t):
    a, b, c, d = Mx[0, 0], Mx[0, 1], Mx[1, 0], Mx[1, 1]
    return (a * t + b) / (c * t + d)


def main():
    out = {}
    L = {"a": "a", "b": "ab"}; R = {"a": "ab", "b": "b"}
    Linv = {"a": "a", "b": "Ab"}
    assert compose(L, Linv) == {"a": "a", "b": "b"}
    # Z0: composition order of move matrices
    LR = compose(L, R)
    M_LR = M_of(LR); ML, MR = W.ML, W.MR
    out["Z0"] = {"H1_of_L_after_R": h1(LR).tolist(), "H1_L_times_H1_R": (h1(L) @ h1(R)).tolist(),
                 "move_matrix_of_L_after_R_equals_ML_MR": bool(M_LR is not None and np.allclose(M_LR, ML @ MR)),
                 "move_matrix_of_L_after_R_equals_MR_ML": bool(M_LR is not None and np.allclose(M_LR, MR @ ML))}
    # an automorphism with H1 matrix U = [[0,-1],[1,1]] (order 6 in SL(2,Z)): search short compositions of L, R, Linv, Rinv
    Rinv = {"a": "aB", "b": "b"}; assert compose(R, Rinv) == {"a": "a", "b": "b"}
    gens = {"L": L, "R": R, "l": Linv, "r": Rinv}
    target = np.array([[0, -1], [1, 1]]); found = None
    for n in range(1, 5):
        for t in itertools.product(gens, repeat=n):
            f = {"a": "a", "b": "b"}
            for s in t: f = compose(f, gens[s])
            if np.array_equal(h1(f), target): found = ("".join(t), f); break
        if found: break
    word, U = found
    omega = np.exp(2j * np.pi / 3)
    fixed = [complex(mobius(h1(U), omega)), complex(mobius(h1(U).T, omega)), complex(mobius(np.linalg.inv(h1(U)), omega))]
    out["Z0"]["U_word"] = word; out["Z0"]["U_images"] = U
    out["Z0"]["U_fixes_omega"] = {"action_by_matrix": bool(abs(fixed[0] - omega) < 1e-12), "by_transpose": bool(abs(fixed[1] - omega) < 1e-12),
                                  "by_inverse": bool(abs(fixed[2] - omega) < 1e-12)}
    iota = {"a": "A", "b": "B"}; inn_a = {"a": "a", "b": "abA"}; inn_b = {"a": "baB", "b": "b"}
    mats = {"U": M_of(U), "iota": M_of(iota), "inn_a": M_of(inn_a), "inn_b": M_of(inn_b)}
    out["Z1_lifts_found"] = {k: v is not None for k, v in mats.items()}
    Gres = cp.Group([mats["U"], mats["iota"], mats["inn_a"], mats["inn_b"]])
    keepsT = all(np.allclose(TB @ cp.restrict(M, TB), M @ TB, atol=1e-8) for M in Gres.els)
    out["Z1"] = {"order": Gres.n, "preserves_T": bool(keepsT),
                 "inner_a_on_V_diagonal_signs": [round(float(x.real), 6) for x in np.diag(mats["inn_a"])] if np.allclose(mats["inn_a"], np.diag(np.diag(mats["inn_a"]))) else "not diagonal",
                 "inner_b_on_V_diagonal_signs": [round(float(x.real), 6) for x in np.diag(mats["inn_b"])] if np.allclose(mats["inn_b"], np.diag(np.diag(mats["inn_b"]))) else "not diagonal"}
    Tmats = [cp.restrict(M, TB) for M in Gres.els]
    pieces, comm = cp.decompose(Tmats, 3)
    chis = []
    for P in pieces:
        Q, _ = np.linalg.qr(P); chis.append({"dim": int(P.shape[1]), "chi_U": complex(np.trace(Q.conj().T @ cp.restrict(mats["U"], TB) @ Q))})
    out["Z2"] = {"T_commutant_under_residual": comm, "pieces": [{"dim": c["dim"], "chi_U": [round(c["chi_U"].real, 6), round(c["chi_U"].imag, 6)]} for c in chis]}
    evU = np.linalg.eigvals(cp.restrict(mats["U"], TB))
    turns = sorted(round(float(np.angle(e) / (2 * np.pi)) % 1, 6) for e in evU)
    out["Z4"] = {"U_eigen_turns_on_T": turns, "U_order_on_T": order_n(cp.restrict(mats["U"], TB)),
                 "charge_differences_turns": sorted({round((a - b) % 1, 6) for a in turns for b in turns if a != b})}
    # Z3: mass terms at exactly omega, vacua fixed by the whole residual group
    Z3 = {}
    for label, kind in (("Dirac T-bar(x)T", "dirac"), ("Majorana Sym2 T", "majorana")):
        if kind == "dirac":
            reps = [np.kron(cp.restrict(M, TB).conj(), cp.restrict(M, TB)) for M in Gres.els]; Bm = np.eye(9, dtype=complex); n = 9
        else:
            Bm = nm.sym_basis(); reps = [Bm.conj().T @ np.kron(cp.restrict(M, TB), cp.restrict(M, TB)) @ Bm for M in Gres.els]; n = 6
        P = sum(reps) / len(reps)
        ev, V = np.linalg.eigh((P + P.conj().T) / 2); fixed = V[:, [i for i, e in enumerate(ev) if abs(e - 1) < 1e-7]]
        rows = {"fixed_dim": int(fixed.shape[1])}
        if fixed.shape[1]:
            rng = np.random.default_rng(1617); spectra = set()
            for _ in range(200):
                v = fixed @ (rng.normal(size=fixed.shape[1]) + 1j * rng.normal(size=fixed.shape[1]))
                M3 = (Bm @ v).reshape(3, 3) if kind == "dirac" else (Bm @ v).reshape(3, 3)
                s = np.sort(np.linalg.svd(M3, compute_uv=False))
                spectra.add((round(float(s[0] / s[2]), 3), round(float(s[1] / s[2]), 3)))
            rows["free_couplings"] = int(fixed.shape[1]); rows["sample_spectra_m1_m3_m2_m3"] = sorted(spectra)[:8]; rows["distinct_spectra_sampled"] = len(spectra)
        Z3[label] = rows
    out["Z3"] = Z3
    json.dump(out, open(HERE / "weave_at_omega.json", "w"), indent=1, default=str); print(json.dumps(out, indent=1, default=str))


if __name__ == "__main__":
    main()
