"""Generate docs/SEAL_LEDGER.md — the seal-provenance view (R20-11).

For every sealed-style document (PREREG*, *DESIGN*.md, SEALED*.md under
frontier/B*/): its sha256 (current content), its banking commit, whether
it was ever amended after banking (commit count > 1), and whether its
sha8 is recorded anywhere in the repo. A generated view (GOVERNANCE
section 12): regenerate with  python3 scripts/seal_ledger.py  — never
hand-edit the output.

Honest semantics: a post-hoc row here RECORDS provenance; it does not
retroactively make an unrecorded seal "hash-first". Arcs that predate
the hash-first ritual are labeled by their git provenance, not excused.
"""
import glob
import hashlib
import os
import subprocess

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))


def git(*args):
    return subprocess.run(["git", "-C", ROOT, *args], capture_output=True,
                          text=True).stdout


def main():
    sealed = []
    for d in sorted(glob.glob(os.path.join(ROOT, "frontier", "B*", ""))):
        for pat in ("PREREG*", "*DESIGN*.md", "SEALED*.md"):
            sealed.extend(sorted(glob.glob(os.path.join(d, pat))))
    sealed = sorted(set(sealed))

    # index of all repo text for recorded-hash lookup (one pass)
    corpus = []
    for base, dirs, files in os.walk(ROOT):
        dirs[:] = [x for x in dirs if x not in
                   (".git", "__pycache__", "legacy", ".github")]
        for fn in files:
            if fn.endswith((".md", ".txt", ".py")):
                p = os.path.join(base, fn)
                try:
                    corpus.append((p, open(p, errors="ignore").read()))
                except Exception:
                    pass

    rows = []
    for path in sealed:
        rel = os.path.relpath(path, ROOT)
        h = hashlib.sha256(open(path, "rb").read()).hexdigest()
        h8 = h[:8]
        log = git("log", "--follow", "--format=%h", "--", rel).split()
        n_commits = len(log)
        banked = log[-1] if log else "untracked"
        recorded = any(h8 in text for p, text in corpus
                       if os.path.relpath(p, ROOT) != rel)
        rows.append((rel, h8, banked, n_commits, recorded))

    out = [
        "# THE SEAL LEDGER (generated — do not hand-edit)",
        "",
        "*Generated by `scripts/seal_ledger.py` (R20-11; GOVERNANCE §12: a",
        "view, regenerable). One row per sealed-style document. `recorded` =",
        "the current content's sha8 appears somewhere else in the repo.",
        "`commits` > 1 means the file changed after banking — its CURRENT",
        "hash is not its sealed hash; consult the arc's trail. A post-hoc",
        "row records provenance; it does not retroactively confer",
        "hash-first status.*",
        "",
        "| sealed document | sha8 (current) | banked in | commits | recorded elsewhere |",
        "|---|---|---|---|---|",
    ]
    n_unrec_single = n_unrec_multi = 0
    for rel, h8, banked, n, rec in rows:
        if not rec:
            if n <= 1:
                n_unrec_single += 1
            else:
                n_unrec_multi += 1
        out.append(f"| {rel} | {h8} | {banked} | {n} | "
                   f"{'yes' if rec else 'NO'} |")
    out.append("")
    out.append(f"*Totals: {len(rows)} sealed documents; "
               f"{n_unrec_single} unrecorded with single-commit provenance "
               f"(content = banked content); {n_unrec_multi} unrecorded "
               f"AND amended after banking (current hash ≠ sealed hash — "
               f"see each arc's trail).*")
    # preserve the append-only reservation/verdict section (the collision
    # protocol, adopted 2026-07-21) below the marker; create it if absent
    ledger_path = os.path.join(ROOT, "docs", "SEAL_LEDGER.md")
    MARKER = "## Reservation & verdict rows (APPEND-ONLY — the collision protocol; preserved by the generator)"
    manual = ""
    if os.path.exists(ledger_path):
        cur = open(ledger_path, encoding="utf-8").read()
        if MARKER in cur:
            manual = cur.split(MARKER, 1)[1]
        else:
            # migrate: everything after the generated Totals line is manual
            m = cur.split("*Totals:", 1)
            if len(m) == 2:
                tail = m[1].split("\n", 1)
                manual = tail[1] if len(tail) == 2 else ""
    out.append("")
    out.append(MARKER)
    out.append(manual.rstrip("\n") if manual.strip() else "")
    with open(ledger_path, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"{len(rows)} rows; unrecorded single-commit {n_unrec_single}; "
          f"unrecorded amended {n_unrec_multi}")


if __name__ == "__main__":
    main()
