#!/usr/bin/env python3
"""Does the parabolic MERIDIAN pair generate?  B1401 left this as its one unproved step.

Two levels:
 (1) WORD-LEVEL PROOF, where the meridian word makes it immediate.
 (2) ABELIANISATION TEST, a NECESSARY condition: <mer, x> can only be all of pi_1 if the images
     of mer and x generate H_1. A failure here is decisive; a pass is not a proof.
"""
import numpy as np, snappy
from itertools import product

NAMES = ["m004", "m009", "m003", "v2873", "m202"]

def exps(word):
    """exponent vector of a word in the 2 generators (abelianisation)"""
    e = [0, 0]
    for ch in word:
        i = 0 if ch.lower() == 'a' else 1
        e[i] += 1 if ch.islower() else -1
    return e

print("=" * 88)
print("(1) WORD-LEVEL: can the other generator be recovered from (meridian, x)?")
print("=" * 88)
proved = {}
for n in NAMES:
    G = snappy.Manifold(n).fundamental_group()
    m = G.meridian(0)
    note = ""
    if m in ("ab", "ba"):
        note = f"mer = {m!r}: a^-1.mer = b  (and b^-1.mer = a) -> <mer,a> = <mer,b> = <a,b>  PROVED"
        proved[n] = True
    elif m in ("AB", "BA"):
        note = f"mer = {m!r} = (ba)^-1 / (ab)^-1 -> <mer,x> = <ab or ba, x> -> same argument  PROVED"
        proved[n] = True
    else:
        note = f"mer = {m!r}: not a length-2 word; not immediate"
        proved[n] = False
    print(f"  {n:>7}: {note}")

print()
print("=" * 88)
print("(2) ABELIANISATION (necessary condition) for the two that are not immediate")
print("=" * 88)
for n in NAMES:
    if proved[n]:
        continue
    M = snappy.Manifold(n); G = M.fundamental_group()
    h1 = M.homology()
    mer = G.meridian(0)
    em = exps(mer)
    print(f"  {n:>7}: H_1 = {h1}   meridian exponents = {em}")
    # relator exponents give the abelianised relation
    rels = [exps(r) for r in G.relators()]
    print(f"           relator exponents = {rels}")
    for other, eo in (("a", [1, 0]), ("b", [0, 1])):
        # does the subgroup of Z^2 generated by em, eo, and the relators equal that generated by
        # e_a, e_b and the relators?  compare Smith normal forms via determinant/index
        Msub = np.array([em, eo] + rels, dtype=np.int64)
        Mall = np.array([[1, 0], [0, 1]] + rels, dtype=np.int64)
        def index(A):
            # index of the subgroup of Z^2 spanned by the rows (0 if full rank 2 -> |det| of a basis)
            from math import gcd
            best = 0
            for i in range(len(A)):
                for j in range(i + 1, len(A)):
                    d = int(round(A[i][0] * A[j][1] - A[i][1] * A[j][0]))
                    best = gcd(best, abs(d))
            g = 0
            for r in A:
                g = gcd(gcd(g, abs(int(r[0]))), abs(int(r[1])))
            return best, g
        print(f"           (mer,{other}) spans index-data {index(Msub)}   vs full {index(Mall)}"
              f"   -> abelianisation {'ALLOWS' if index(Msub) == index(Mall) else 'FORBIDS'} generation")
