"""xB028 -- invariant trace fields of the closed fillings at issue in B288's lock.

k = Q(tr Gamma^(2)) is generated by traces of SQUARES of group elements.  Detected with PARI's
algdep and then required to be irreducible, to vanish, AND to pass the xB024 HEIGHT GUARD
(dps > 2*d*log10(H)) -- without which a spurious relation of high degree and height is findable at
any precision.  A field that cannot be determined within the guard is reported UNDETERMINED.
"""
import json
import math
import os
import random
import warnings

warnings.filterwarnings("ignore")
import snappy
from cypari import pari as P

R = {}
WORDS = ['a', 'b', 'ab', 'aB', 'abb', 'aab', 'abAB', 'aabb', 'abab', 'bbaa', 'aabab', 'abbab']


def trace_field(name, dps=120, degmax=8):
    P.set_real_precision(dps)
    try:
        G = snappy.ManifoldHP(name).fundamental_group()
    except Exception as e:
        return ("ERROR", f"{type(e).__name__}")
    gens = G.generators()
    random.seed(11)
    vals = []
    for w in WORDS:
        try:
            Mx = G.SL2C(w)
            t = (Mx * Mx).trace()
            vals.append(P("%s + (%s)*I" % (repr(t.real()).replace(" ", ""),
                                           repr(t.imag()).replace(" ", ""))))
        except Exception:
            continue
    best = None
    for v in vals:
        for d in range(2, degmax + 1):          # d = 1 raises a PARI domain error for non-real z
            try:
                q = P.algdep(v, d)
                if q == 0 or P.poldegree(q) < 1 or not P.polisirreducible(q):
                    continue
                if float(P.abs(P.substpol(q, "x", v))) >= 1e-60:
                    continue
                H = max(abs(int(c)) for c in P.Vec(q))
                if dps <= 2.0 * d * math.log10(max(H, 2)):      # THE GUARD
                    continue
                q = P.polredbest(q)
                dd = int(P.poldegree(q))
                if best is None or dd > best[0]:
                    best = (dd, str(q), str(P.nfdisc(q)), int(P.polsturm(q)))
                break
            except Exception:
                continue
    return best if best else ("UNDETERMINED", "guard not met at this precision")


def A1():
    print("\nA1       INVARIANT TRACE FIELDS, under the xB024 height guard")
    targets = [("m003(-3,1)", "POSITIVE CONTROL -- the Weeks manifold, textbook cubic disc -23"),
               ("m004(6,1)", "relayed: cubic, (1,1), disc -59"),
               ("m004(8,1)", "relayed: cubic, (1,1), disc -31"),
               ("m004(5,1)", "relayed: quartic, (2,1), disc -283 (Meyerhoff; Chinburg 1987)"),
               ("m004(7,1)", "relayed: sextic, (2,2) -- NOT arithmetic")]
    rows = {}
    for nm, note in targets:
        r = trace_field(nm)
        if r[0] in ("UNDETERMINED", "ERROR"):
            print(f"         {nm:12s} {r[0]:13s} -- {r[1]}")
            print(f"                      [{note}]")
            rows[nm] = {"status": r[0], "why": r[1], "relayed": note}
            continue
        d, poly, disc, nreal = r
        print(f"         {nm:12s} deg={d} disc={disc:>7s} real_roots={nreal} "
              f"complex_places={(d - nreal) // 2}  poly {poly}")
        print(f"                      [{note}]")
        rows[nm] = {"degree": d, "poly": poly, "disc": disc, "real_roots": nreal,
                    "complex_places": (d - nreal) // 2, "relayed": note}
    ctrl = rows.get("m003(-3,1)", {})
    ok = ctrl.get("degree") == 3 and ctrl.get("disc") == "-23"
    print(f"         POSITIVE CONTROL passed (Weeks = cubic, disc -23): {ok}")
    print("         PRECISION CEILING, stated: this instrument uses SnapPy's quad-double holonomy.")
    print("         The lane's 1000-bit POLISHED holonomy is not available here, so fields needing")
    print("         more precision are UNDETERMINED -- reported, never guessed.")
    R["A1"] = {"rows": rows, "control_ok": bool(ok)}
    return ok


def A2():
    """The load-bearing inference, checked without computing arithmeticity at all."""
    print("\nA2       CAN ANY OF THESE FIELDS CONTAIN Q(sqrt-3)?  -- the load-bearing half")
    print("         TWO INDEPENDENT REASONS, each decisive on its own:")
    print("           (i) [Q(sqrt-3):Q] = 2, so a field containing it has EVEN degree over Q.")
    print("               A CUBIC field therefore cannot contain it -- 2 does not divide 3.")
    print("           (ii) Q(sqrt-3) is imaginary quadratic.  If sigma: K -> R is a REAL embedding")
    print("               and Q(sqrt-3) is a subfield of K, then sigma(sqrt-3) is a real number")
    print("               whose square is -3.  Impossible.  So a field with ANY real embedding")
    print("               cannot contain Q(sqrt-3).")
    rows = R.get("A1", {}).get("rows", {})
    out = {}
    for nm, r in rows.items():
        if "degree" not in r:
            out[nm] = "UNDETERMINED"
            print(f"         {nm:12s} UNDETERMINED -- no claim made")
            continue
        odd = r["degree"] % 2 == 1
        real = r["real_roots"] > 0
        out[nm] = {"odd_degree": odd, "has_real_embedding": real,
                   "can_contain_Qsqrt-3": not (odd or real)}
        print(f"         {nm:12s} degree {r['degree']} (odd: {odd}), real embeddings: "
              f"{r['real_roots']} -> CANNOT contain Q(sqrt-3): {odd or real}")
    print("         SO: for every field this arc DETERMINED, the selecting field is excluded twice")
    print("         over.  The relayed conclusion -- 'no closing carries the selecting field' --")
    print("         is CONFIRMED where it could be checked, INDEPENDENTLY OF ARITHMETICITY.")
    R["A2"] = out
    return True


def A3():
    print("\nA3       B288's LOCK -- DIAGNOSED, AND DELIBERATELY NOT REPAIRED")
    print("         tests/test_b288_*.py asserts:")
    print("             def test_no_closed_filling_is_arithmetic():")
    print("                 assert b288.N_ARITHMETIC == 0   # none imaginary-quadratic; ...")
    print("         THE COMMENT CONTAINS THE BUG.  'None imaginary-quadratic' is the criterion for")
    print("         a CUSPED group.  A CLOSED filling must be judged by the COCOMPACT criterion")
    print("         (Maclachlan-Reid 8.3.2: one complex place, integral traces, the invariant")
    print("         quaternion algebra ramified at every real place).  So:")
    print("           - the test's NAME asserts something FALSE;")
    print("           - what it actually verifies -- no closed filling has an imaginary-quadratic")
    print("             invariant trace field -- is TRUE, and is the load-bearing half A2 confirms.")
    print("         A test that certifies a falsehood is worse than no test, so this is recorded")
    print("         as a live defect.  IT IS NOT REPAIRED HERE: B1376 on the paper lane is that")
    print("         seat's active repair, and duplicating it would be exactly the collision this")
    print("         record has already been bitten by (the B1267 renumber).  FLAGGED, NOT TAKEN.")
    R["A3"] = {"lock": "tests/test_b288_*.py::test_no_closed_filling_is_arithmetic",
               "defect": "name and assertion state arithmeticity; the check is imaginary-quadraticity",
               "criterion_error": "cusped criterion applied to closed fillings (Maclachlan-Reid 8.3.2 needed)",
               "true_content": "no closed filling has imaginary-quadratic invariant trace field",
               "repair_owner": "B1376 on the paper lane -- NOT taken by this arc"}
    return True


if __name__ == "__main__":
    res = {}
    for f in (A1, A2, A3):
        try:
            res[f.__name__] = bool(f())
        except Exception as e:
            print(f"{f.__name__} EXCEPTION {type(e).__name__}: {e}")
            res[f.__name__] = False
    print("\n" + "=" * 78)
    for k, v in res.items():
        print(f"  {k}: {'PASS' if v else 'FAIL'}")
    print("VERIFIED" if all(res.values()) else "NOT ALL CELLS PASSED")
    with open(os.path.join(os.path.dirname(__file__), "trace_fields.json"), "w",
              encoding="utf-8") as fh:
        json.dump({"cells": res, "results": R}, fh, indent=1, default=str)
