#!/usr/bin/env python3
"""B1538 -- the regenerated records against the read-out of 2026-10-04 (written before the regenerated records are read).

The read-out ran once on 2026-10-04 at 17:15Z on the original records, which were lost unbanked with the seat's container
(run_notes.md).  Its verdict and aggregates were recorded in this seat's relay of 2026-10-06, section 3
(SM_TO_CC_AND_CODEX_2026-10-06_THE_COUNT_ON_THE_ROOM.md).  The records are regenerated by the sealed code.  The sealed
read_out.py and read_out_scoped.py then run on them once each, and this script compares their outputs, and Part F''s own rows,
with every number the relay recorded.  A single difference withholds the bank and goes to ERROR_LEDGER first.

Where each number is read:
  - the predictions, Part L's counts, routes P and T, Proposition H: read_out.json (the sealed read-out).  The sealed read-out
    writes predictions, not a verdict; the seal's section 9 decides it from them (PROVED: P1-P3 and P9 True, P8 False;
    NEGATIVE: P1-P3, P9 and P8 True; else OPEN);
  - P7', P8', the scoped verdict and the in-scope candidates and members: read_out_scoped.json;
  - the members by state, their room min(capW, capL2), and the covers and the candidates' zeta orders at room 3: Part F''s own
    rows, run_F_scoped.jsonl (the 12,152 in-scope candidates; the sealed partial record's one candidate is out of scope).  If
    that file is gone, the same rows are read from run_F.jsonl or its .jsonl.gz, after the sealed partial record's 12,826
    lines.  Room is read in route R.  Route P4's caps are compared with route R's at every member; the number that differ is
    reported (it is not a recorded number).  A candidate's zeta is stored reduced to its exact order m (punct_covers'
    galois_reps); the order is still computed as m / gcd(m, zeta).

    python3 regen_compare.py   ->  regen_compare.json (exit status 1 on any difference)"""
import gzip
import json
import sys
from collections import Counter, defaultdict
from functools import reduce
from math import gcd
from pathlib import Path

HERE = Path(__file__).resolve().parent
PARTIAL_LINES = 12826                    # the sealed partial record: the first candidate's header and 12,825 readings
ROOM3 = ["m135.D8.2-0-4.w1", "m135.D8.4-0-2.w4", "m136.D8.2-0-4.w3", "m136.D8.4-0-2.w5"]

# the read-out of 2026-10-04, as recorded in the relay of 2026-10-06, section 3 (verbatim numbers)
RECORDED = {
    "verdict (the seal's section 9, from the sealed read-out's predictions)": "PROVED",
    "P1": True, "P2": True, "P3": True, "P8": False, "P9": True,
    "predictions held (the sealed read-out, of 11)": 7,
    "scoped: P7'": False, "scoped: P8'": False, "verdict (the scoped read-out)": "PROVED",
    "Part L: Galois orbits with n >= 1": 483692,
    "Part L: candidates (n >= 2)": 64422,
    "route P: reads": 3376190, "route P: disagreements": 0,
    "route T: reads": 483692, "route T: disagreements": 0,
    "Part F': candidates in scope (read_out_scoped.json)": 12152,
    "Part F': candidates (its rows)": 12152,
    "Part F': members (read_out_scoped.json)": 10346,
    "Part F': members (its rows)": 10346,
    "Part F': members on m003": 106, "Part F': members on m004": 0, "Part F': members on m135": 1216,
    "Part F': members on m136": 9024,
    "Part F': the rooms of the members on m003": [0],
    "Part F': members with room 3": 1856,
    "Part F': the covers of the members with room 3": ROOM3,
    "Part F': the candidates' zeta orders at room 3, on m135's covers": [2],
    "Part F': the candidates' zeta orders at room 3, on m136's covers": [4, 6, 12],
    "Proposition H: covers": 10,
    "Proposition H: covers with sum 4": 10,
}


def seal_verdict(p):
    """the seal's section 9, from the sealed read-out's predictions"""
    if not all(p.get(k) is True for k in ("P1", "P2", "P3", "P9")):
        return "OPEN"
    if p.get("P8") is False:
        return "PROVED"
    if p.get("P8") is True:
        return "NEGATIVE"
    return "OPEN"


def part_f_rows():
    """Part F''s own rows"""
    p = HERE / "run_F_scoped.jsonl"
    if p.exists():
        with open(p) as f:
            for line in f:
                if line.strip():
                    yield json.loads(line)
        return
    q = HERE / "run_F.jsonl"
    f = open(q) if q.exists() else gzip.open(HERE / "run_F.jsonl.gz", "rt")
    with f:
        for i, line in enumerate(f):
            if i >= PARTIAL_LINES and line.strip():
                yield json.loads(line)


def part_f_prime():
    heads, members, by_state, rooms, rooms_m003 = set(), 0, Counter(), Counter(), set()
    covers3, orders3, p4_differs = set(), defaultdict(set), 0
    for r in part_f_rows():
        ck = (r["cover"], tuple(r["chi"]["zeta"]), r["chi"]["m"], tuple(r["chi"]["s"]))
        if r["kind"] == "candidate":
            heads.add(ck)
            continue
        if not r.get("member"):
            continue
        st = r["cover"].split(".")[0]
        members += 1
        by_state[st] += 1
        room = min(r["R"]["capW"], r["R"]["capL2"])
        p4_differs += (r["R"]["capW"], r["R"]["capL2"]) != (r["P4"]["capW"], r["P4"]["capL2"])
        rooms[room] += 1
        if st == "m003":
            rooms_m003.add(room)
        if room == 3:
            covers3.add(r["cover"])
            m = r["chi"]["m"]
            orders3[st].add(m // reduce(gcd, r["chi"]["zeta"], m))
    return {"candidates": len(heads), "members": members, "by state": dict(by_state), "rooms": dict(sorted(rooms.items())),
            "rooms on m003": sorted(rooms_m003), "covers at room 3": sorted(covers3),
            "zeta orders at room 3": {k: sorted(v) for k, v in sorted(orders3.items())},
            "members whose route P4 caps differ from route R's": p4_differs}


def main():
    ro = json.loads((HERE / "read_out.json").read_text())
    rs = json.loads((HERE / "read_out_scoped.json").read_text())
    got = {}
    pred = ro["predictions"]
    got["verdict (the seal's section 9, from the sealed read-out's predictions)"] = seal_verdict(pred)
    for k in ("P1", "P2", "P3", "P8", "P9"):
        got[k] = pred.get(k)
    got["predictions held (the sealed read-out, of 11)"] = (sum(1 for v in pred.values() if v is True)
                                                         if len(pred) == 11 else f"{len(pred)} predictions")
    got["scoped: P7'"] = rs.get("P7'")
    got["scoped: P8'"] = rs.get("P8'")
    got["verdict (the scoped read-out)"] = rs.get("verdict")
    got["Part L: Galois orbits with n >= 1"] = ro.get("hits (n >= 1), Galois orbits")
    got["Part L: candidates (n >= 2)"] = ro.get("candidates (n >= 2)")
    got["route P: reads"] = ro["route P"]["reads"]
    got["route P: disagreements"] = ro["route P"]["disagree"]
    got["route T: reads"] = ro["route T"]["reads"]
    got["route T: disagreements"] = ro["route T"]["disagree"]
    fs = rs.get("Part F (in scope)")
    fs = fs if isinstance(fs, dict) else {}
    got["Part F': candidates in scope (read_out_scoped.json)"] = fs.get("candidates")
    got["Part F': members (read_out_scoped.json)"] = fs.get("members")
    fp = part_f_prime()
    got["Part F': candidates (its rows)"] = fp["candidates"]
    got["Part F': members (its rows)"] = fp["members"]
    for st in ("m003", "m004", "m135", "m136"):
        got[f"Part F': members on {st}"] = fp["by state"].get(st, 0)
    got["Part F': the rooms of the members on m003"] = fp["rooms on m003"]
    got["Part F': members with room 3"] = fp["rooms"].get(3, 0)
    got["Part F': the covers of the members with room 3"] = fp["covers at room 3"]
    got["Part F': the candidates' zeta orders at room 3, on m135's covers"] = fp["zeta orders at room 3"].get("m135", [])
    got["Part F': the candidates' zeta orders at room 3, on m136's covers"] = fp["zeta orders at room 3"].get("m136", [])
    ph = ro.get("Proposition H")
    sums = ph.get("sum of n", {}) if isinstance(ph, dict) else {}
    got["Proposition H: covers"] = ph.get("covers") if isinstance(ph, dict) else None
    got["Proposition H: covers with sum 4"] = sum(1 for v in sums.values() if v == 4)
    diff = {k: {"recorded": RECORDED[k], "regenerated": got.get(k)} for k in RECORDED if got.get(k) != RECORDED[k]}
    out = {"recorded (the relay of 2026-10-06, section 3)": RECORDED, "regenerated": got, "differences": diff,
           "every recorded number reproduced": not diff,
           "descriptive (not recorded numbers)": {"Part F': rooms of the members (route R)": fp["rooms"],
                                                  "Part F': zeta orders at room 3, by state": fp["zeta orders at room 3"],
                                                  "Part F': members whose route P4 caps differ from route R's":
                                                      fp["members whose route P4 caps differ from route R's"],
                                                  "routes agree (in scope; read_out_scoped.json)":
                                                      rs.get("routes agree (in scope)")}}
    (HERE / "regen_compare.json").write_text(json.dumps(out, indent=1) + "\n")
    print(json.dumps(out, indent=1))
    return 0 if not diff else 1


if __name__ == "__main__":
    sys.exit(main())
