"""B265 -- integrability + Zariski-density: genuine E6-irreducible flat connections on the figure-eight EXIST.
FIREWALLED (geometry / rep theory of flat connections, not physics). Nothing to CLAIMS.md.

The integrability rung of chat-1's program. B264 found the tangent space to the E6 character variety at the
principal-composed geometric rep has dim 6 = rank(E6), with directions graded by the E6 exponents {1,4,5,7,8,11}.
This probe answers: do those infinitesimal deformations (i) INTEGRATE to actual reps, and (ii) is the generic
deformation E6-ZARISKI-DENSE (an honest E6-irreducible flat connection) -- or trapped in a subgroup?

(1) ZARISKI-DENSITY (decisive, computed in t41_e6_generation_sage.py with sage-python; results hard-coded below):
    in e6, the subalgebra generated by the principal sl(2) together with ONE deformation direction graded by
    exponent m has dimension
        exponent 4, 8  (E6 exponents NOT in F4)  -> 78 = dim e6   => E6-ZARISKI-DENSE
        exponent 5,7,11 (F4 exponents)           -> 52 = dim f4   => trapped in F4
        principal sl(2) alone (exponent 1)       ->  3            => the SL(2) A-polynomial curve.
    So the 6-dim tangent space splits EXACTLY by the F4/E6 structure: the {4,8} directions (the e6/f4 = 26 coset)
    are E6-dense; the F4 directions stay in F4. A deformation with a {4,8} component is genuinely E6-irreducible.
    (Lie fact behind it: the only subalgebras of e6 containing the principal sl(2) are sl(2), f4, e6 -- Dynkin;
    the {4,8} directions leave f4, forcing the closure to be e6.)

(2) INTEGRABILITY: the obstruction to integrating a class in H^1 lives in H^2. We compute (Fox complex, exact
    Riley rep) dim H^2(pi_1(4_1), Sym^{2k}) = 1 for all k -- consistent with the Euler characteristic of the
    knot complement (chi = 0, H^0 = 0 for k>=1  =>  H^2 = H^1). So the obstruction SPACE is 6-dim, nonzero;
    integrability is NOT automatic. BUT the discrete-faithful (geometric) holonomy is a SMOOTH point of the
    G-character variety of a 1-cusped hyperbolic 3-manifold, of dimension = rank(G)*#cusps = 6 (Thurston for
    SL(2); the higher-rank principal-composed version, e.g. Menal-Ferrer-Porti / higher-Teichmuller). Smoothness
    means the cup-product obstruction H^1 x H^1 -> H^2 VANISHES at this rep despite H^2 != 0. Hence the rank-6
    family consists of ACTUAL representations -- the deformations integrate.

CONCLUSION: combining (1)+(2), the {4,8} deformations integrate to a positive-dimensional family of E6-Zariski-dense
representations of pi_1(4_1). => GENUINE E6-irreducible flat connections on the figure-eight EXIST (near rho_prin).
chat-1's hope confirmed at the actual-representation level (not merely infinitesimal).

HONEST GUARDRAILS (verify-don't-trust): (a) "exist near rho_prin" -- a local statement around the geometric rep
(the right neighborhood for the 3d-3d story); we do not classify the global E6 character variety. (b) Existence of
E6-dense reps is NOT SM physics: the input-E6 (chosen 6d type) vs output-McKay-E6 (trace field) selection is still
a conjecture, and the 4d-lift / chirality / scale walls (B259) stand untouched. (c) consistent with the SL(n)
ladder dim=rank (SL2->1, SL3->2 [B71], ..., E6->6); E6 is the exceptional capstone.

Run: python e6_integrability.py  (pyenv; imports B264's verified Fox machinery). Density reproduced separately by
sage-python t41_e6_generation_sage.py.
"""
import importlib.util
import pathlib

import mpmath as mp

_B264 = pathlib.Path(__file__).resolve().parents[1] / "B264_e6_character_variety" / "e6_charvar_tangent.py"
_spec = importlib.util.spec_from_file_location("b264", _B264)
b264 = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(b264)

E6_EXPONENTS = b264.E6_EXPONENTS          # [1,4,5,7,8,11]
F4_EXPONENTS = b264.F4_EXPONENTS          # [1,5,7,11]
DIM_E6, DIM_F4 = 78, 52

# (1) Zariski-density: dim of <principal sl(2), v_exp> in e6 (from t41_e6_generation_sage.py)
GENERATION_DIM = {1: 3, 4: 78, 5: 52, 7: 52, 8: 78, 11: 52}


def zariski_dense_exponents():
    """Exponents whose deformation direction generates all of e6 (E6-Zariski-dense)."""
    return sorted(m for m, d in GENERATION_DIM.items() if d == DIM_E6)


def trapped_exponents():
    """Exponents whose direction stays inside f4 (excluding the principal sl(2) itself, exponent 1)."""
    return sorted(m for m, d in GENERATION_DIM.items() if d == DIM_F4)


# (2) Integrability: dim H^2(pi_1(4_1), Sym^{2k}) via the Fox complex (H^2 = coker d1 = dim V - rank d1).
def H2_sym(k):
    n = 2 * k
    S = {g: b264.symn(b264.BASE[g], n) for g in "ab"}
    Si = {g: b264.symn(b264.BASE[g.upper()], n) for g in "ab"}
    dim = n + 1
    seq = [(ch.lower(), 1 if ch.islower() else -1) for ch in b264.REL]

    def fox(j):
        tot = mp.zeros(dim, dim)
        pre = mp.eye(dim)
        for g, s in seq:
            Mg = S[g] if s == 1 else Si[g]
            if g == j:
                tot = tot + (pre if s == 1 else -(pre * Mg))
            pre = pre * Mg
        return tot

    fa, fb = fox("a"), fox("b")
    d1 = mp.zeros(dim, 2 * dim)
    for i in range(dim):
        for j in range(dim):
            d1[i, j], d1[i, dim + j] = fa[i, j], fb[i, j]
    return dim - b264._rank(d1)               # coker d1 = H^2


def obstruction_dim():
    """dim H^2(Ad rho_prin) = sum over E6 exponents (the obstruction space)."""
    return sum(H2_sym(m) for m in E6_EXPONENTS)


if __name__ == "__main__":
    print("=== B265: integrability + Zariski-density of the E6 deformations ===\n")
    print("(1) Zariski-density  (dim <principal sl(2), v_exp> in e6; sage-python):")
    for m in sorted(GENERATION_DIM):
        tag = "E6-DENSE" if GENERATION_DIM[m] == DIM_E6 else ("F4-trapped" if GENERATION_DIM[m] == DIM_F4 else "sl(2) curve")
        print(f"    exponent {m:>2}: dim {GENERATION_DIM[m]:>2}   {tag}")
    dense, trapped = zariski_dense_exponents(), trapped_exponents()
    print(f"    -> E6-Zariski-dense directions: exponents {dense}  (= E6 \\ F4)")
    print(f"    -> F4-trapped directions:       exponents {trapped}")
    assert dense == [4, 8] == sorted(set(E6_EXPONENTS) - set(F4_EXPONENTS))
    assert trapped == [5, 7, 11]

    print("\n(2) Integrability  (dim H^2(Sym^{2k}); obstruction space):")
    for k in range(1, 12):
        h2 = H2_sym(k)
        print(f"    H^2(Sym^{2*k:>2}) = {h2}")
        assert h2 == 1                        # = H^1 by chi=0; obstruction space nonzero but cup product vanishes
    obs = obstruction_dim()
    print(f"    dim H^2(Ad) = {obs} = dim H^1(Ad) (chi=0); geometric rep is a SMOOTH point (Thurston / MFP)")
    assert obs == 6

    print("\n=> The {4,8} deformations integrate (smoothness) to E6-Zariski-dense reps.")
    print("=> GENUINE E6-irreducible flat connections on the figure-eight EXIST (near rho_prin). ALL PASS")
