"""B265 reproducibility -- the Lie-algebra density computation (run with sage-python, NOT pyenv).
Shows: in e6, the principal sl(2) together with a deformation direction graded by exponent m generates
  - all of e6 (dim 78) for m in {4,8} = E6 exponents NOT in F4  -> E6-Zariski-dense,
  - only f4 (dim 52) for m in {5,7,11} = F4 exponents          -> trapped in F4.
This is the decisive Zariski-density input for B265. Output hard-coded into e6_integrability.py."""
from sage.all import LieAlgebra, QQ, matrix, vector, identity_matrix

L = LieAlgebra(QQ, cartan_type=['E', 6]); dim = L.dimension(); idx = list(L.cartan_type().index_set())
Hh = {i: L.bracket(L.e(i), L.f(i)) for i in idx}
A = L.cartan_type().cartan_matrix(); c = 2 * A.inverse() * vector(QQ, [1] * len(idx))
e = sum(L.e(i) for i in idx)
h = sum(c[k] * Hh[idx[k]] for k in range(len(idx)))
f = sum(c[k] * L.f(idx[k]) for k in range(len(idx)))
assert L.bracket(h, e) == 2 * e and L.bracket(e, f) == h          # principal sl(2)
basisels = list(L.basis())
adh = matrix(QQ, [L.bracket(h, b).to_vector() for b in basisels]).transpose()
ade = matrix(QQ, [L.bracket(e, b).to_vector() for b in basisels]).transpose()
Ke = ade.right_kernel()


def hw(ev):  # highest-weight vector at ad(h)-eigenvalue ev (killed by ad e)
    inter = (adh - ev * identity_matrix(QQ, dim)).right_kernel().intersection(Ke)
    return sum(inter.basis()[0][i] * basisels[i] for i in range(dim))


def gendim(extra):  # dim of subalgebra generated by principal sl(2) + extra
    gens = [e, h, f] + extra; M = matrix(QQ, [x.to_vector() for x in gens]); cur = list(gens); ch = True
    while ch:
        ch = False
        for x in list(cur):
            for gg in gens:
                br = L.bracket(x, gg)
                if M.stack(br.to_vector()).rank() > M.rank():
                    M = M.stack(br.to_vector()); cur.append(br); ch = True
    return M.rank()


if __name__ == "__main__":
    print("dim <principal sl2> =", gendim([]))
    for m in (4, 8, 5, 7, 11):
        print(f"dim <principal sl2, v_exp{m}> = {gendim([hw(2 * m)])}")
    # expected: exp4,8 -> 78 ; exp5,7,11 -> 52
