#!/usr/bin/env python3
"""B1378 -- the Reidemeister-Schreier presentation of pi_1(Y6), the degree-6 cyclic cover of m004, and two structural
cross-checks independent of any representation: the classical monodromy computation of H_1(Y6) (m004 fibers over S^1
with once-punctured-torus fiber and monodromy M = RL, so H_1(Y_n) = coker(M^n - I) (+) Z, the deck transformation
acting as M on the torsion part) and the order of the order-3 deck square TAU2 on that H_1.  This is an own
re-derivation of the construction reported by an external seat's audit package (seat "0925", 2026-09-25,
m6_deck_chiral_triplet/verify_m6_triplet.py and REPORT.md, harvested into this branch's scratchpad -- see B1378
FINDINGS Sec. 0 for provenance); the coset-rewriting code, the classical monodromy check, and the H1/TAU2 structural
checks below are this seat's own code, not copied from that package, and are cross-checked against it and against
this branch's own B1375 (which builds the same Y6 by SnapPy's covers() on its own presentation).

Ambient presentation (B1368's conventions): pi_1(m004) = <a, b | a w b^-1 w^-1>, w = b a^-1 b^-1 a (W = [2,-1,-2,1]),
w* = a b^-1 a^-1 b (WSTAR = [1,-2,-1,2]); meridian mu = a; longitude lambda = w w* (LONG = W + WSTAR).  Generators are
signed integers (1 = a, 2 = b, negative = inverse); words are lists of such integers.

The degree-n cyclic cover Y_n corresponds to the surjection pi_1(m004) -> Z -> Z/n given by the meridian-exponent sum
(both a and b are meridians of the knot, so both map to +1 in Z/n).  Its subgroup is generated by z = a^n and
x_k = a^k b a^-k (k = 0..n-1); the standard Reidemeister-Schreier rewriting process below, with transversal
{1, a, ..., a^{n-1}}, rewrites the ambient relator (read at each of the n cosets) and the longitude into words in
these n + 1 generators, numbered 1 = z, 2..n+1 = x_0..x_{n-1}."""
import sys
import sympy as sp
from sympy.matrices.normalforms import smith_normal_form, hermite_normal_form

# ---------------------------------------------------------------- the ambient presentation (B1368)
W = [2, -1, -2, 1]
WSTAR = [1, -2, -1, 2]
REL = [1] + W + [-2] + [-x for x in reversed(W)]      # a w b^-1 w^-1
LONG = W + WSTAR                                       # lambda = w w*


def rewrite(word, n, k=0):
    """Reidemeister-Schreier rewrite of `word` (a word in a, b) into the subgroup <a^n, a^i b a^-i>, starting at
    coset k (= the current power of a mod n).  Returns (rewritten word, ending coset).  Generator numbering:
    1 = z (= a^n), 2 + i = x_i (= a^i b a^-i)."""
    out = []
    for L in word:
        if L == 1:                                     # a: advances the coset; emits z only at the wraparound
            if k == n - 1: out.append(1)
            k = (k + 1) % n
        elif L == -1:
            if k == 0: out.append(-1)
            k = (k - 1) % n
        elif L == 2:                                    # b: emits x_k at the current coset (b is also a meridian)
            out.append(2 + k); k = (k + 1) % n
        else:
            k = (k - 1) % n; out.append(-(2 + k))
    return out, k


N_COVER = 6
NG = N_COVER + 1                                        # 7 generators: z, x0..x5
LETTERS = "abcdefg"                                      # 1=z=a, 2..7 = x0..x5 = b..g


def word_str(word):
    return "".join(chr(ord('a') + L - 1) if L > 0 else chr(ord('A') - L - 1) for L in word)


RELS = [rewrite(REL, N_COVER, k)[0] for k in range(N_COVER)]          # 6 relators, one per coset
RELS_STR = [word_str(r) for r in RELS]
MU = [1]; MU_STR = "a"                                                # the new meridian is z itself
LAM, _k_end = rewrite(LONG, N_COVER, 0)                                # the longitude is null-homologous: lifts at coset 0
assert _k_end == 0
LAM_STR = word_str(LAM)

# TAU2, a word-level candidate for the order-3 deck square, on the abelianization H_1(Y6) ONLY (see the caveat
# below): worked out by hand from TAU = conjugation-by-a acting on the Schreier generators (z -> z, x_k -> x_{k+1}
# for k < 5, x5 -> z x0 z^-1), composed with itself.  Two independent hand/derivation attempts were made in the
# course of this arc (the first reproducing an error also present in the external audit's own script, verify_m6_
# triplet.py's TAU2 = {..., 5:[7,-1], ..., 7:[1,3]}; a second, corrected attempt using the Schreier generators'
# more careful definition) -- BOTH give the CORRECT order (exactly 3, matching the classical, presentation-free
# monodromy computation below) when tested at the ABELIANIZED (H_1) level, which is the only level asserted here.
# CAVEAT (own finding, disclosed rather than papered over): neither attempt was confirmed at the full, non-abelian
# representation level (substituting the word into each of the six relators and evaluating in a genuine rank-2
# representation of pi_1(Y6) does NOT give the identity on every relator for either candidate) -- so TAU2 as coded
# here is verified ONLY as inducing the correct order-3 map on H_1(Y6), not as an exact automorphism of the full
# group.  This arc does not need the stronger statement: Sec. 3 of deck_triplet.py establishes the three orbit
# members are genuinely TAU-related by a clean cohomological argument (deck() is confirmed to be the exact
# character-level pullback by TAU wherever it is used, and h^1 = 1 forces the extension class to be pinned up to a
# scalar, hence the pulled-back representation is isomorphic to the next member) that does not depend on any
# word-level formula for TAU or TAU2 at all.
TAU2 = {1: [1], 2: [4], 3: [5], 4: [6], 5: [7], 6: [1, 2, -1], 7: [1, 3, -1]}
TAU2_STR = {LETTERS[g - 1]: word_str(w) for g, w in TAU2.items()}


def expvec(word, ng=NG):
    v = [0] * ng
    for L in word: v[abs(L) - 1] += 1 if L > 0 else -1
    return v


def h1_by_reidemeister_schreier():
    """H_1(Y_6) from the Reidemeister-Schreier presentation's abelianization (Smith normal form of the 6x7 relator
    exponent matrix): own re-derivation, no SnapPy."""
    Erels = sp.Matrix([expvec(r) for r in RELS])
    snf = smith_normal_form(Erels, domain=sp.ZZ)
    diag = [int(snf[i, i]) for i in range(min(snf.shape))]
    torsion = [d for d in diag if d not in (0, 1)]
    free_rank = NG - snf.rank()
    return torsion, free_rank


def _in_lattice(basis, v):
    """Exact test: is the integer vector v in the lattice spanned by the (independent) columns of `basis`?  Solves
    the least-squares system over Q (exact, sympy Rationals) -- since basis has full column rank, a solution in the
    column span is automatically unique, so this is exact membership, not merely approximate."""
    basis = sp.Matrix(basis); v = sp.Matrix(v)
    BtB = basis.T * basis
    x = BtB.solve(basis.T * v)                                         # unique exact rational solution, if any
    return (basis * x == v), x


def tau2_order_on_h1():
    """The order of TAU2's induced action on H_1(Y_6) = Z^7 / (lattice spanned by the relators' exponent vectors),
    via an exact lattice-membership test (own code, robust to the internal pivot structure hermite_normal_form
    happens to return): TAU2 is order 3 on H_1 iff (TAU2)^3 - I maps every generator into the relator lattice, and
    TAU2 - I does not (order != 1)."""
    basis = sp.Matrix([expvec(r) for r in RELS]).T                     # 7 x 6: relator lattice, as columns
    Etau = sp.Matrix([expvec(TAU2[g]) for g in range(1, NG + 1)])      # rows: images of each generator
    I7 = sp.eye(NG)
    cubed_minus_I = (Etau.T) ** 3 - I7
    order3_ok = all(_in_lattice(basis, cubed_minus_I[:, j])[0] for j in range(NG))
    minus_I = Etau.T - I7
    order1_fails = not all(_in_lattice(basis, minus_I[:, j])[0] for j in range(NG))
    return order3_ok, order1_fails


def classical_monodromy_check(n=N_COVER):
    """Independent, presentation-free cross-check: m004 fibers over S^1 with once-punctured-torus fiber and
    monodromy M = R L (R, L the standard Dehn-twist generators of the mapping class group of the punctured torus);
    H_1(Y_n) = coker(M^n - I) (+) Z with the deck transformation acting as M on the coker part.  Own re-derivation
    (sympy), independent of any group presentation."""
    R = sp.Matrix([[1, 1], [0, 1]]); L = sp.Matrix([[1, 0], [1, 1]]); M = R * L
    assert M == sp.Matrix([[2, 1], [1, 1]]) and M.det() == 1 and M.trace() == 3
    A = M ** n - sp.eye(2)
    snf = smith_normal_form(A, domain=sp.ZZ)
    invariant_factors = [int(snf[i, i]) for i in range(2) if snf[i, i] != 0]

    # the order of M acting on coker(A) = Z^2 / (lattice spanned by A's columns): track the class of (1,0) by its
    # exact representative modulo the lattice at each step (find any w with A x = v - w for integer x, w reduced).
    def reduce_class(v):
        v = sp.Matrix(v)
        BtB = A.T * A
        x = BtB.solve(A.T * v)
        xi = sp.Matrix([sp.floor(xj) for xj in x])                     # round toward a nearby lattice point
        return tuple(int(t) for t in (v - A * xi))

    def order_of_M():
        v0 = reduce_class([1, 0])
        v = v0
        for k in range(1, 200):
            v = reduce_class(list(M * sp.Matrix(v)))
            if v == v0: return k
        return None
    return invariant_factors, order_of_M(), M


if __name__ == "__main__":
    torsion, free_rank = h1_by_reidemeister_schreier()
    print(f"H1(Y6) by Reidemeister-Schreier: torsion {sorted(torsion)}, free rank {free_rank}  "
          f"(expect Z/8 (+) Z/40 (+) Z)")
    assert sorted(torsion) == [8, 40] and free_rank == 1
    order3_ok, order1_fails = tau2_order_on_h1()
    print(f"TAU2 on H1(Y6): (TAU2)^3 = I: {order3_ok}; TAU2 != I: {order1_fails}  (expect True, True -- order exactly 3)")
    assert order3_ok and order1_fails
    invariant_factors, order_M, M = classical_monodromy_check()
    print(f"classical check (monodromy M = {M.tolist()}, no presentation): coker(M^6 - I) invariant factors "
          f"{invariant_factors}, order of M on it: {order_M}  (expect [8, 40], 6 -- tau^2 = M^2 has order 3)")
    assert invariant_factors == [8, 40] and order_M == 6
    print("ALL STRUCTURAL CHECKS PASSED")
