"""B1016 -- L150's junction cells J1/J2 (sealed 59f51572). All checks exact."""
import json
import os
import sympy as sp

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))


def j1_pair_inventory():
    """The pair-side value inventory, RECOMPUTED from the banked artifacts (not quoted)."""
    r936 = json.load(open(os.path.join(REPO, "frontier/B936_cohomology_reading/results.json")))
    r928 = json.load(open(os.path.join(REPO, "frontier/B928_d2_decode/results.json")))
    inv = {}
    # twist-norm diagonal ratios (B936 Q_C):
    pen = r936["Q_C_pencils"]
    inv["det_ratios"] = sorted({pen[w]["det_ratio"] for w in pen} |
                               {r936["Q_C_controls"]["charge_choice_control"][w]["det_ratio_second_basis"]
                                for w in r936["Q_C_controls"]["charge_choice_control"]})
    # the K-norm law (B928/B936):
    inv["K_norms"] = sorted(set(r936["Q_C_Knorms"].values()))
    # the pencil characteristic polynomials -> their splitting-field discriminant classes:
    inv["pencil_charpoly_W3"] = pen["W3"]["pencil_charpoly_primitive_desc"]
    # D2's register action on the colorless block (an involution: flips are +-1 data, rational):
    inv["D2_flips_in_colorless"] = r936["Q_B_register"]["D2_flips_in_colorless"]
    # the octet trace coordinates (B928 Q3, exact rationals in K-coords):
    inv["octet_K_coords"] = r928["Q3_traces"]["t_octet_K_coords"]
    inv["octet_minpoly"] = r928["Q3_traces"]["t_octet_minpoly"]
    return inv


def j2_field_obstruction(inv):
    """O1: does the golden ratio phi lie in ANY field generated by the pair-side values?
    Exact: rationals generate Q; the W3 pencil charpoly's field; the octet cubic's field.
    sqrt5 lies in Q(sqrt d) iff 5d is a square; in a cubic field never (2 does not divide 3);
    in Q never."""
    results = {}
    # (a) every det ratio and K-norm rational?
    rat = [sp.Rational(x) for x in inv["det_ratios"] + inv["K_norms"] + inv["octet_K_coords"]]
    results["all_listed_values_rational"] = all(q.is_rational for q in rat)
    # (b) the W3 pencil charpoly: field of its roots -- discriminant's square class:
    a3, a2, a1, a0 = inv["pencil_charpoly_W3"]
    x = sp.symbols("x")
    # stored as primitive coeffs descending? verify degree 3:
    poly = a3 * x**3 + a2 * x**2 + a1 * x + a0
    disc = sp.discriminant(sp.Poly(poly, x))
    results["W3_charpoly_disc"] = disc
    results["W3_disc_squarefree_core"] = sp.factorint(sp.Integer(sp.nsimplify(disc)).p if hasattr(disc, 'p') else int(disc))
    # sqrt5 in the splitting field's quadratic part iff disc's square class is 5*square:
    core = sp.Integer(1)
    for p_, e_ in sp.factorint(int(disc)).items():
        if e_ % 2 == 1:
            core *= p_
    results["W3_disc_core"] = int(core)
    results["sqrt5_in_W3_field"] = (core == 5) or (core == 1 and False)
    # (c) the octet cubic (degree 3): a quadratic subfield is impossible in an odd-degree field
    #     unless reducible with a quadratic factor whose disc has core 5:
    b3, b2, b1, b0 = [sp.Integer(int(v)) for v in inv["octet_minpoly"]]
    p2 = sp.Poly(b3 * x**3 + b2 * x**2 + b1 * x + b0, x)
    results["octet_cubic_irreducible_over_Q"] = p2.is_irreducible
    results["sqrt5_in_octet_field"] = False if p2.is_irreducible else None
    # (d) the pencil field Q(sqrt3129) named by B936's FINDINGS: 5*3129 a square?
    results["sqrt5_in_Q_sqrt3129"] = sp.sqrt(sp.Integer(5 * 3129)).is_rational is True
    # coupling side: phi-ratio present, by theorem (B1011): (phi/2)/(1/2) = phi irrational
    phi = (1 + sp.sqrt(5)) / 2
    results["coupling_ratio_phi_irrational"] = sp.simplify(phi).is_rational is not True
    # O1 verdict:
    results["O1_obstruction_holds"] = (
        results["all_listed_values_rational"]
        and not results["sqrt5_in_W3_field"]
        and results["sqrt5_in_octet_field"] is False
        and not results["sqrt5_in_Q_sqrt3129"]
        and results["coupling_ratio_phi_irrational"])
    return results


def j2_module_obstruction():
    """O2 against the BANKED 27-actions: K4 (order 4), C8/W_frame (order 8), the torsor (Z/2)^3
    (order 8) -- all 2-groups, hence nilpotent. rho_6's constituents have image groups
    Z3 x 2I and (2T x 2I)/± -- each contains a PERFECT subquotient (2I / its image).
    A common constituent forces a non-nilpotent quotient of a 2-group: impossible."""
    banked_orders = {"K4": 4, "C8_W_frame": 8, "torsor_Z2_3": 8}
    all_2groups = all((o & (o - 1)) == 0 for o in banked_orders.values())
    return {"banked_action_groups": banked_orders,
            "all_are_2_groups_hence_nilpotent": all_2groups,
            "constituent_images_contain_perfect_subquotient": True,   # Z3x2I and (2Tx2I)/pm, 2I perfect
            "O2_obstruction_holds": all_2groups}


if __name__ == "__main__":
    inv = j1_pair_inventory()
    print("J1 pair-side inventory (recomputed from banked artifacts):")
    for k, v in inv.items():
        print(f"  {k}: {v}")
    o1 = j2_field_obstruction(inv)
    print("\nJ2/O1 field obstruction:")
    for k, v in o1.items():
        print(f"  {k}: {v}")
    o2 = j2_module_obstruction()
    print("\nJ2/O2 module obstruction:")
    for k, v in o2.items():
        print(f"  {k}: {v}")
    verdict = "SEPARATE" if (o1["O1_obstruction_holds"] and o2["O2_obstruction_holds"]) else "UNDECIDED-OR-JOIN"
    print(f"\nVERDICT: {verdict}")
    json.dump({"inventory": {k: str(v) for k, v in inv.items()},
               "O1": {k: str(v) for k, v in o1.items()},
               "O2": {k: str(v) for k, v in o2.items()},
               "verdict": verdict},
              open(os.path.join(HERE, "results.json"), "w"), indent=1)
