"""B1509, post-run: the audit lane's flag balance (R41) read on the 4 c 5 flag of W1, and W1's invariant flags.

(a) A = mu rho_q is irreducible at the six points: the algebra generated by A(m), A(n) is all of M_4 (Burnside).  So the only proper
    invariant subspace of the non-split W1 = [[A, c], [0, 1]] is A: one flag and one balance.  R40's single-Jordan-block four has three.
(b) The local identity behind R41's balance, for a flat connection preserving the flag A c W1.  In an adapted orthonormal frame,
    omega = [[a, b], [0, d]] (a 4x4, d 1x1, b the extension block), omega_A = (omega - omega^+)/2, Psi = (omega + omega^+)/2,
    P = diag(1,1,1,1,0), xi = 5P - 4 = diag(1,1,1,1,-4) = T.  Then tr(Psi [omega_A, xi]) = -(5/2)|b|^2.  R41 §2 states this
    as "the whole-rank projector identity is -5|alpha|^2/2".  With I = -2 d_A^* Psi = S on a boundaryless finite-energy domain, it gives
    integral tr(T S) = 5 integral |b|^2.  Checked exactly on random Gaussian-rational data, together with R41's rank-four identity
    tr(Psi [omega_A, xi_k]) = -2|eta_k|^2 for xi_k = 4P_k - k as a control.
(c) R41's source directions paired with each flag.  Control: R41's own table for R40's three flags, (0,0,0), (12,8,4), (3,2,1).
    Then this flag: T pairs to 20, U to 0, and [E04, E04^+] to 5."""
import json
import random
import sys
from pathlib import Path

import sympy as sp

HERE = Path(__file__).resolve().parent
POINTS = [("17-12sqrt2", 17 - 12 * sp.sqrt(2), -1, "-1"), ("17+12sqrt2", 17 + 12 * sp.sqrt(2), -1, "-1"),
          ("7-4sqrt3", 7 - 4 * sp.sqrt(3), sp.I, "i"), ("7+4sqrt3", 7 + 4 * sp.sqrt(3), sp.I, "i"),
          ("7-4sqrt3", 7 - 4 * sp.sqrt(3), -sp.I, "-i"), ("7+4sqrt3", 7 + 4 * sp.sqrt(3), -sp.I, "-i")]


def ballas(qq):
    t = qq / 2
    m = sp.Matrix([[1, 0, 1, t - 1], [0, 1, 1, t], [0, 0, 1, t + sp.Rational(1, 2)], [0, 0, 0, 1]])
    n = sp.Matrix([[1, 0, 0, 0], [2 + 1 / t, 1, 0, 0], [2, 1, 1, 0], [1, 1, 0, 1]])
    return m, n


def algebra_dim(gens):
    """dimension of the unital associative algebra generated by the matrices (exact, over Q(sqrt2, sqrt3, i))"""
    d = gens[0].shape[0]
    K = sp.QQ.algebraic_field(sp.sqrt(2), sp.sqrt(3), sp.I)
    from sympy.polys.matrices import DomainMatrix
    conv = lambda M: DomainMatrix.from_Matrix(M).convert_to(K)
    G = [conv(g) for g in gens]
    basis, rows = [], None
    frontier = [DomainMatrix.eye(d, K)]

    def vec(X):
        flat = [x for row in X.to_list() for x in row]
        return DomainMatrix([flat], (1, d * d), K)

    while frontier:
        new = []
        for X in frontier:
            cand = vec(X) if rows is None else rows.vstack(vec(X))
            if cand.rank() > (0 if rows is None else rows.shape[0]):
                rows = cand
                basis.append(X)
                new.extend(X * g for g in G)
        frontier = new
        if len(basis) == d * d:
            break
    return len(basis)


def rnd(rng):
    return sp.Rational(rng.randint(-9, 9), rng.randint(1, 5)) + sp.I * sp.Rational(rng.randint(-9, 9), rng.randint(1, 5))


def local_identity(n, k, trials=5, seed=1509):
    """tr(Psi [omega_A, n P_k - k]) against -(n/2)|b|^2 for omega preserving the first k coordinates"""
    rng = random.Random(seed + 10 * n + k)
    out = []
    for _ in range(trials):
        w = sp.Matrix(n, n, lambda i, j: 0 if (i >= k and j < k) else rnd(rng))
        wA = (w - w.H) / 2
        Psi = (w + w.H) / 2
        P = sp.diag(*([1] * k + [0] * (n - k)))
        xi = n * P - k * sp.eye(n)
        lhs = sp.expand((Psi * (wA * xi - xi * wA)).trace())
        b = w[:k, k:]
        nb2 = sp.expand(sum(sp.Abs(x) ** 2 for x in b))
        out.append(sp.simplify(lhs + sp.Rational(n, 2) * nb2) == 0 and nb2 != 0)
    return all(out)


def pairings():
    T = sp.diag(1, 1, 1, 1, -4)
    U = sp.diag(3, -1, -1, -1, 0)
    E = sp.zeros(5)
    E[0, 4] = 1
    C = E * E.T - E.T * E
    dirs = {"T": T, "U": U, "-U": -U, "[E04,E04^+]": C}
    r40 = {}
    for name, S in dirs.items():
        vals = []
        for k in (1, 2, 3):
            xi = sp.zeros(5)
            xi[:4, :4] = 4 * sp.diag(*([1] * k + [0] * (4 - k))) - k * sp.eye(4)
            vals.append(int((xi * S).trace()))
        r40[name] = vals
    xi45 = 5 * sp.diag(1, 1, 1, 1, 0) - 4 * sp.eye(5)
    this = {name: int((xi45 * S).trace()) for name, S in dirs.items()}
    return {"xi_for_4_in_5_equals_T": xi45 == T, "R41_table_reproduced": r40 == {"T": [0, 0, 0], "U": [12, 8, 4],
            "-U": [-12, -8, -4], "[E04,E04^+]": [3, 2, 1]}, "R40_flags": r40, "this_flag": this,
            "T_charge_of_E04": int(((T * E - E * T)[0, 4]))}


def main():
    irred = []
    for label, qq, mu, ml in POINTS:
        m, n = ballas(qq)
        irred.append({"q": label, "mu": ml, "dim_algebra_generated_by_A": algebra_dim([mu * m, mu * n])})
    return {"irreducible_at_points": irred,
            "local_identity_rank5_flag4": local_identity(5, 4),
            "local_identity_rank4_flags_control(R41)": all(local_identity(4, k) for k in (1, 2, 3)),
            "pairings": pairings()}


if __name__ == "__main__":
    res = main()
    txt = json.dumps(res, indent=1, sort_keys=True, default=str)
    print(txt)
    if "--record" in sys.argv:
        (HERE / "balance_transpose_run.txt").write_text(txt + "\n", encoding="utf-8")
