#!/usr/bin/env python3
"""B1535 Part M -- the covers' own classes at the pulled-back members of m135 and m136 (sL-10 item 14, first half), read in two
routes.  Library and runner; the sealed run is `python3 -u part_m.py --record` (after the seal), the controls use the same
functions on banked comparisons only.

The population (PREREGISTRATION section 5): every member nu of sm:B1534 at kappa = +-1 and every subgroup B != 1 of its
contributing group (sm:B1534's C_nu, Lemma Z'): the deck characters of every finite abelian cover that can carry a count at nu.

The classes at (nu, B), each a set of components c_chi in Z^1(M; nu^5 chi rho), chi in B (mixed_lib's comps):
  - pure-1:<name>    the class of sm:B1534 named <name> at chi = 1 (a pulled-back class);
  - pure-<chi0>:<name>  at one chi0 != 1, the class <name> of sm:B1534's member eta = nu^5 chi0 (Lemma R: banked as eta's count
                     over B);
  - mixed-generic-1, -2  every component with h^1 >= 1, each a combination of its representatives with coefficients from a
                     hash of (state, nu, B, name, chi, j) in {1, ..., 97};
  - mixed-interior   every component's interior classes, hashed coefficients, where at least two components have one;
  - mixed-int+gen    the first component with an interior class at its interior class, the others generic;
  - mixed-cancel     at a fibre-direction cover, a combination of the components vanishing on the first non-identity cover
                     cusp g P g^-1 and not interior, where one exists.  On that cusp the class pulled back to P is
                     (nu^5 rho)(g) Sum_chi chi(g) [c_chi|_P] (c_chi(g p g^-1) = M(g) c_chi(p) + (1 - M(g p g^-1)) c_chi(g)).
                     Route RS reads the cusps itself, so its k checks the cancellation.
Route Ind (exact over Q(zeta_24), mixed_lib): the circulant modules on M.  Route RS (GF(p) at two primes, rs_lib): the same
components restricted to the cover's own Reidemeister-Schreier presentation.  Both read Theorem C's identities at every class."""
import hashlib
import itertools
import json
import sys
import time
from datetime import datetime, timezone
from fractions import Fraction
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import mixed_lib as ML  # noqa: E402
import rs_lib as RS  # noqa: E402

SL, E = ML.SL, ML.E
ROOT = HERE.parents[2]
B1534V = ROOT / "frontier" / "B1534_the_silver_covers" / "verification"
GEN_S = (Fraction(3, 7), Fraction(-11, 5))          # sm:B1534's two generic classes


def H(*parts):
    return int(hashlib.sha256(("B1535 part M:" + ":".join(str(x) for x in parts)).encode()).hexdigest(), 16)


def coef(*parts):
    return 1 + H(*parts) % 97


# ============================================================================================ the population
def lab_of(w, k):
    return ML.lab(w[0], w[1], k)


def lstr(x):
    return f"({x[0]}, {x[1]}; {x[2]})"


def subgroups_of(C):
    """every subgroup of the contributing group C (labels), generated by subsets (closure); B = 1 excluded"""
    labs = [lab_of(w, k) for w, k in C]
    seen = set()
    for r in (1, 2, 3):
        for gens in itertools.combinations(labs, r):
            B = tuple(ML.closure(list(gens)))
            if len(B) > 1 and B not in seen and all(x in labs for x in B):
                seen.add(B)
    return sorted(seen, key=lambda b: (len(b), b))


def population(st):
    mems = SL.members(st)
    out = []
    for m in mems:
        C = SL.contributing(st, m)
        for B in subgroups_of(C):
            out.append((m, B))
    return mems, out


def turn(x):
    for j in range(24):
        if x == E.zeta(j):
            return Fraction(j, 24)
    raise ValueError("not a 24th root of unity")


def cover_of(st, B):
    """route RS's cover for the deck characters B (generated by B's elements; images in (Q/Z)^|B|)"""
    chs = [ML.chardict(st, x) for x in B]
    imgs = {g: tuple(turn(ch[g]) for ch in chs) for g in st["G"].gens}
    return RS.Cover(st["G"], imgs)


# ============================================================================================ the classes
def member_classes(m):
    """sm:B1534's classes at member m: name -> cocycle"""
    if m["h1"] == 1:
        return {"the class": m["classes"]["the class"]}
    out = {"c_int": m["c_int"]}
    for i, s in enumerate(GEN_S, 1):
        out[f"c_g{i}"] = SL.lin(m["c_b"], m["c_int"], E.ONE, E.K.of(s))
    return out


def classes_at(st, mems, m, B):
    """name -> comps (chi label -> cocycle) at (nu, B)"""
    nu = lab_of(m["u"], m["kappa"])
    by_lab = {lab_of(x["u"], x["kappa"]): x for x in mems}
    comp = ML.components(st, nu, B)
    out = {}
    one = ML.lab(0, 0, 0)
    for nm, c in member_classes(m).items():
        out[f"pure-1:{nm}"] = {one: c}
    for x in B:
        if x == one or comp[x].h1 == 0:
            continue
        eta = ML.ladd(ML.lab(*(5 * nu[i] for i in range(3))), x)
        if eta in by_lab:
            for nm, c in member_classes(by_lab[eta]).items():
                out[f"pure-{lstr(x)}:{nm}"] = {x: c}
    tag = (st["state"], nu, B)
    live = [x for x in B if comp[x].h1 >= 1]
    for g in (1, 2):
        out[f"mixed-generic-{g}"] = {x: ML.combo(comp[x], [coef(*tag, "gen", g, x, j) for j in range(comp[x].h1)])
                                     for x in live}
    ints = [x for x in live if comp[x].n >= 1]
    if len(ints) >= 2:
        out["mixed-interior"] = {x: ML.interior_cocycle(comp[x], [coef(*tag, "int", x, j) for j in range(comp[x].n)])
                                 for x in ints}
    if ints and len(live) >= 2:
        d = {x: ML.combo(comp[x], [coef(*tag, "ig", x, j) for j in range(comp[x].h1)]) for x in live}
        d[ints[0]] = ML.interior_cocycle(comp[ints[0]], [coef(*tag, "ig-int", j) for j in range(comp[ints[0]].n)])
        out["mixed-int+gen"] = d
    canc = cancel_class(st, nu, B, comp, live, tag)
    if canc is not None:
        out["mixed-cancel"] = canc
    return out


def cancel_class(st, nu, B, comp, live, tag):
    """at a fibre-direction cover (every chi trivial on t'), a combination vanishing on the first non-identity cover cusp and not
    interior; None if none exists"""
    if any(x[2] != 0 for x in B) or len(live) < 2:
        return None
    cov = cover_of(st, B)
    rep = next(c for c in cov.cosets if any(c))           # the first non-identity coset: its word g
    g = cov.rep[rep]
    chs = {x: ML.chardict(st, x) for x in B}

    def val(ch, w):
        v = E.ONE
        for c in w:
            v = v * (ch[c] if c.islower() else E.ONE / ch[c.lower()])
        return v
    # unknowns: x_{chi, j} over live chi and their representatives; condition: sum chi(g)^-1 x r(z) in span(BP)
    cols, keys = [], []
    C0 = comp[live[0]]
    d = C0.d
    for x in live:
        w = val(chs[x], g)                                 # the class at the cusp g P g^-1, pulled back to P: sum chi(g) [c_chi|P]
        for j, z in enumerate(comp[x].reps):
            cols.append([w * v for v in comp[x].restrict(z)])
            keys.append((x, j))
    BP = C0.BP                                             # the cusp coboundaries are the same for every chi (chi|P = 1)
    A = [[cols[i][r] for i in range(len(cols))] + [-BP[j][r] for j in range(d)] for r in range(2 * d)]
    sol = E.nullspace(A, len(cols) + d)
    best = None
    for s in sol:
        xs = s[:len(cols)]
        if all(v.is_zero() for v in xs):
            continue
        comps = {}
        for (x, j), v in zip(keys, xs):
            if not v.is_zero():
                comps.setdefault(x, [E.ZERO] * len(comp[x].reps))
                comps[x][j] = v
        cocs = {x: comp[x].combine(v) for x, v in comps.items()}
        interior = all(comp[x].coboundary_on_P(c) is not None for x, c in cocs.items())
        if not interior and len(cocs) >= 2:
            best = cocs
            break
    return best


# ============================================================================================ the two routes
def read_ind(st, nu, B, comps):
    R = ML.ind_reading(st, nu, B, comps, direct=False)
    return {k: R[k] for k in ("I(W)", "I(L2W)", "k", "b0", "n((VL)*)", "n(V)", "n(L)", "rk d1", "all")} | \
        {"failed": [k for k, v in R["checks"].items() if not v]}


def read_rs(st, nu, B, comps, p, cov=None):
    cov = cov or cover_of(st, B)
    F = RS.GF(p)
    ch = ML.chardict(st, nu)
    V = st["rho"].twist(ch)
    Lc = SL.S.power_char(ch, -4)
    Veta = st["rho"].twist(SL.S.power_char(ch, 5))
    VA = RS.CModule.restrict(cov, F, V.M)
    Lv = []
    for i in range(len(cov.sgens)):
        v = E.ONE
        for c in cov.sword(i):
            v = v * (Lc[c] if c.islower() else E.ONE / Lc[c.lower()])
        Lv.append(F.of_K(v))
    Lv = np.array(Lv, dtype=np.int64)
    z = np.zeros(4 * len(cov.sgens), dtype=np.int64)
    for x, c in comps.items():
        mod = Veta.twist(ML.chardict(st, x))
        zc = np.concatenate([F.vec(E.cocycle_at(mod, c, cov.sword(i))) for i in range(len(cov.sgens))])
        z = (z + zc) % p
    W = RS.extension(VA, z, Lv)
    R = RS.reading(W)
    return {k: R[k] for k in ("I(W)", "I(L2W)", "k", "b0", "n((VL)*)", "n(V)", "n(L)", "rk d1", "all")} | \
        {"failed": [k for k, v in R["checks"].items() if not v], "cusps": len(cov.cusps), "order": cov.order}


def banked_sum(banked, state, m_lab, cname, B):
    """sm:B1534's banked count of member m_lab = (u, kappa) at class cname over B (Lemma S)"""
    u = [str(m_lab[0]), str(m_lab[1])]
    kap = str(m_lab[2])
    bm = next(x for x in banked["states"][state]["members"] if x["u"] == u and x["kappa"] == kap)
    terms = bm["terms"][cname]
    w = l = 0
    for x in B:
        key = f"({x[0]}, {x[1]}; {x[2]})"
        if key not in terms:
            # a twist outside the member's contributing set leaves the cusp acyclic: its term is (0, 0) (Lemma Z')
            assert key not in bm["contributing"], ("a contributing term is missing from the bank", key)
            continue
        t = terms[key]
        w, l = w + t[0], l + t[1]
    return [w, l]


def lemma_r_target(name, x, nu):
    """the banked comparison for a pure class: (member label, class name)"""
    if name.startswith("pure-1:"):
        return nu, name.split(":", 1)[1]
    if name.startswith("pure-"):
        eta = ML.ladd(ML.lab(*(5 * nu[i] for i in range(3))), x)
        return eta, name.split(":", 1)[1]
    return None


def run(selection=None, ind_max=2, out_path=None, log=print):
    banked = json.loads((B1534V / "terms.json").read_text())
    rows = []
    t0 = time.time()
    for state in ("-LLRR", "+LLRR"):
        st = SL.setup(state)
        mems, pop = population(st)
        for m, B in pop:
            nu = lab_of(m["u"], m["kappa"])
            if selection is not None and (state, nu, B) not in selection:
                continue
            cov = cover_of(st, B)
            for name, comps in classes_at(st, mems, m, B).items():
                row = {"state": state, "nu": [str(v) for v in nu], "B": [[str(v) for v in x] for x in B], "class": name,
                       "components": [[str(v) for v in x] for x in sorted(comps)]}
                rs1, rs2 = read_rs(st, nu, B, comps, RS.P1, cov), read_rs(st, nu, B, comps, RS.P2, cov)
                row["RS p1"], row["RS p2"] = rs1, rs2
                if len(B) <= ind_max and name.startswith("mixed"):
                    row["Ind"] = read_ind(st, nu, B, comps)
                tgt = None
                if name.startswith("pure-"):
                    x = next(iter(comps))
                    tgt = lemma_r_target(name, x, nu)
                if tgt is not None:
                    row["banked"] = banked_sum(banked, state, tgt[0], tgt[1], B)
                rows.append(row)
                log(f"{state} nu {row['nu']} |B| {len(B)} {name}: RS {(rs1['I(W)'], rs1['I(L2W)'])} "
                    f"{(rs2['I(W)'], rs2['I(L2W)'])}" + (f" Ind {(row['Ind']['I(W)'], row['Ind']['I(L2W)'])}" if 'Ind' in row
                                                        else "") + (f" banked {tuple(row['banked'])}" if 'banked' in row
                                                                    else "") +
                    f" all {rs1['all'] and rs2['all'] and row.get('Ind', {'all': True})['all']} ({time.time() - t0:.0f} s)")
                if out_path is not None:
                    with open(out_path, "a") as f:
                        f.write(json.dumps(row) + "\n")
    return rows


if __name__ == "__main__":
    if "--record" in sys.argv:
        started = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        outp = HERE / "part_m.jsonl"
        assert not outp.exists(), "part_m.jsonl exists: the sealed run is not resumed blindly"
        lines = []

        def log(s):
            print(s, flush=True)
            lines.append(s)
        log(f"B1535 Part M, sealed run, {started}")
        rows = run(out_path=outp, log=log)
        (HERE / "part_m_log.txt").write_text("\n".join(lines) + "\n")
