#!/usr/bin/env python3
"""B1535 -- route RS: the cover read on its own Reidemeister-Schreier presentation, over GF(p), sharing no linear algebra with
route Ind (mixed_lib on sm:B1530's exact_lib).  Nothing is computed on import.

- The cover.  A finite regular abelian cover M_A -> M is given by images of the base generators in A (tuples in (Q/Z)^r, the
  values of a generating set of the deck characters B).  Cosets by breadth-first search (a Schreier transversal); Schreier
  generators s_{c,x} = rep(c) x rep(c x)^-1 off the tree; relators: every base relator rewritten from every coset.  The cusps:
  one per double coset P \\ pi_1 M / pi_1 M_A = A / <image of P>, generated by the rewrites of ell = abAB and t'^m from that coset.
- The modules.  A base module R (exact over K = Q(zeta_24)) is reduced to GF(p) by zeta_24 -> a primitive 24th root of unity
  mod p (p = 1 mod 24); on the cover R(s_{c,x}) = R(rep c) R(x) R(rep(c x))^-1.  A base cocycle z restricts to the cover by
  evaluating it on the words s_{c,x} (Fox).
- The cohomology on the cover: Z^1 from the Fox Jacobian of the cover's relators, B^1, H^1, h^0, the restriction to every cusp
  jointly (r1), n = h^1 - r1, t0 summed over the cusps, and the class index with B1297's identity and the annihilator identity
  asserted at every call.  Theorem C's identities are read exactly as cap_lib reads them, with every dimension over GF(p)."""
from collections import deque
from fractions import Fraction

import numpy as np

P1, P2 = 2147483497, 2147483353          # primes = 1 mod 24 below 2^31: products of residues fit in int64


# ============================================================================================ GF(p)
class GF:
    def __init__(self, p):
        assert (p - 1) % 24 == 0
        self.p = p
        a = 2
        while True:
            g = pow(a, (p - 1) // 24, p)
            if pow(g, 12, p) != 1 and pow(g, 8, p) != 1:
                break
            a += 1
        assert (pow(g, 8, p) - pow(g, 4, p) + 1) % p == 0, "not a root of the 24th cyclotomic polynomial"
        self.zpow = [pow(g, k, p) for k in range(24)]

    def of_K(self, x):
        """an element of exact_lib's K (sum c_k zeta^k / d) mod p"""
        p = self.p
        num = sum(int(c) * self.zpow[k] for k, c in enumerate(x.c)) % p
        return num * pow(int(x.d) % p, -1, p) % p

    def mat(self, M):
        return np.array([[self.of_K(x) for x in row] for row in M], dtype=np.int64)

    def vec(self, v):
        return np.array([self.of_K(x) for x in v], dtype=np.int64)


def rref(M, p):
    """row-reduced echelon form mod p: (rows, pivot columns)"""
    M = np.array(M, dtype=np.int64) % p
    if M.size == 0:
        return M.reshape(0, M.shape[1] if M.ndim == 2 else 0), []
    rows, cols = M.shape
    piv, r = [], 0
    for c in range(cols):
        if r >= rows:
            break
        nz = np.nonzero(M[r:, c])[0]
        if len(nz) == 0:
            continue
        i = r + nz[0]
        if i != r:
            M[[r, i]] = M[[i, r]]
        M[r] = (M[r] * pow(int(M[r, c]), -1, p)) % p
        col = M[:, c].copy()
        col[r] = 0
        nzr = np.nonzero(col)[0]
        if len(nzr):
            M[nzr] = (M[nzr] - (col[nzr, None] * M[r][None, :]) % p) % p
        piv.append(c)
        r += 1
    return M[:r], piv


def rank(M, p):
    M = np.asarray(M)
    if M.size == 0:
        return 0
    return len(rref(M, p)[1])


def nullspace(M, p, ncols=None):
    """a basis of {x : M x = 0} mod p, as rows"""
    M = np.asarray(M, dtype=np.int64)
    n = M.shape[1] if M.ndim == 2 and M.size else ncols
    if M.size == 0:
        return np.eye(n, dtype=np.int64)
    R, piv = rref(M, p)
    free = [c for c in range(n) if c not in piv]
    out = []
    for f in free:
        x = np.zeros(n, dtype=np.int64)
        x[f] = 1
        for i, c in enumerate(piv):
            x[c] = (-R[i, f]) % p
        out.append(x)
    return np.array(out, dtype=np.int64).reshape(len(out), n)


def minv(A, p):
    n = A.shape[0]
    R, piv = rref(np.concatenate([A % p, np.eye(n, dtype=np.int64)], axis=1), p)
    assert piv[:n] == list(range(n)), "singular matrix"
    return R[:, n:]


def mmul(A, B, p):
    """A B mod p without int64 overflow (residues < 2^31, products accumulated one column at a time)"""
    A, B = np.asarray(A, dtype=np.int64), np.asarray(B, dtype=np.int64)
    out = np.zeros((A.shape[0], B.shape[1]), dtype=np.int64)
    for k in range(A.shape[1]):
        out = (out + (A[:, k:k + 1] * B[k:k + 1, :]) % p) % p
    return out


# ============================================================================================ the cover's presentation
def _add(x, y, s=1):
    return tuple((a + s * b) % 1 for a, b in zip(x, y))


class Cover:
    def __init__(self, G, imgs):
        """G: exact_lib Group (gens, rels, cusp words); imgs: gen -> tuple in (Q/Z)^r"""
        self.G = G
        self.gens = list(G.gens)
        self.imgs = {g: tuple(Fraction(v) % 1 for v in imgs[g]) for g in self.gens}
        r = len(next(iter(self.imgs.values())))
        zero = tuple(Fraction(0) for _ in range(r))
        self.rep = {zero: ""}
        self.tree = set()
        q = deque([zero])
        while q:
            c = q.popleft()
            for x in self.gens:
                for s in (1, -1):
                    d = _add(c, self.imgs[x], s)
                    if d not in self.rep:
                        self.rep[d] = self.rep[c] + (x if s == 1 else x.upper())
                        self.tree.add((c, x) if s == 1 else (d, x))
                        q.append(d)
        self.cosets = sorted(self.rep)
        self.order = len(self.cosets)
        self.sgens = [(c, x) for c in self.cosets for x in self.gens if (c, x) not in self.tree]
        self.sidx = {cx: i for i, cx in enumerate(self.sgens)}
        self.rels = []
        for c in self.cosets:
            for rel in G.rels:
                w, end = self.rewrite(c, rel)
                assert end == c, "a relator does not close up"
                self.rels.append(w)
        # the cusps: one per coset of <image of t'> (ell is a commutator, so its image is 0)
        ell, tp = G.cusp
        assert self.image(ell) == zero
        it = self.image(tp)
        m, y = 1, it
        while y != zero:
            y = _add(y, it)
            m += 1
        self.cusp_m = m
        seen, self.cusps = set(), []
        for c in self.cosets:
            if c in seen:
                continue
            orb, y = [c], _add(c, it)
            while y != c:
                orb.append(y)
                y = _add(y, it)
            seen.update(orb)
            w1, e1 = self.rewrite(c, ell)
            w2, e2 = self.rewrite(c, tp * m)
            assert e1 == c and e2 == c
            self.cusps.append((w1, w2))
        assert len(self.gens_cover()) == self.order * (len(self.gens) - 1) + 1, "Schreier rank"

    def gens_cover(self):
        return self.sgens

    def image(self, w):
        r = len(next(iter(self.imgs.values())))
        c = tuple(Fraction(0) for _ in range(r))
        for ch in w:
            c = _add(c, self.imgs[ch.lower()], 1 if ch.islower() else -1)
        return c

    def rewrite(self, c, w):
        out = []
        for ch in w:
            x = ch.lower()
            if ch.islower():
                if (c, x) not in self.tree:
                    out.append((self.sidx[(c, x)], 1))
                c = _add(c, self.imgs[x], 1)
            else:
                c = _add(c, self.imgs[x], -1)
                if (c, x) not in self.tree:
                    out.append((self.sidx[(c, x)], -1))
        return out, c

    def sword(self, i):
        """the base word of the i-th Schreier generator"""
        c, x = self.sgens[i]
        d = _add(c, self.imgs[x])
        inv = "".join(ch.swapcase() for ch in reversed(self.rep[d]))
        return self.rep[c] + x + inv


# ============================================================================================ modules on the cover
class CModule:
    """a module on the cover: one matrix (and its inverse) per Schreier generator, over GF(p)"""

    def __init__(self, cov, F, mats):
        self.cov, self.F, self.p = cov, F, F.p
        self.M = mats
        self.d = mats[0].shape[0]
        self.Mi = [minv(A, self.p) for A in mats]

    @staticmethod
    def restrict(cov, F, base_mats):
        """restrict a base module (dict gen -> exact K matrix) to the cover"""
        p = F.p
        bm = {g: F.mat(base_mats[g]) for g in cov.gens}
        bmi = {g: minv(bm[g], p) for g in cov.gens}
        d = next(iter(bm.values())).shape[0]
        out = []
        for i in range(len(cov.sgens)):
            X = np.eye(d, dtype=np.int64)
            for ch in cov.sword(i):
                X = mmul(X, bm[ch] if ch.islower() else bmi[ch.lower()], p)
            out.append(X)
        return CModule(cov, F, out)

    def word(self, w):
        X = np.eye(self.d, dtype=np.int64)
        for i, e in w:
            X = mmul(X, self.M[i] if e == 1 else self.Mi[i], self.p)
        return X

    def dual(self):
        return CModule(self.cov, self.F, [A.T.copy() for A in self.Mi])

    def permuted(self, order):
        o = np.array(order)
        return CModule(self.cov, self.F, [A[np.ix_(o, o)] for A in self.M])

    def blocks(self, dS):
        for A in self.M:
            assert not np.any(A[dS:, :dS] % self.p), "not block upper-triangular"
        S = CModule(self.cov, self.F, [A[:dS, :dS].copy() for A in self.M])
        Q = CModule(self.cov, self.F, [A[dS:, dS:].copy() for A in self.M])
        return S, Q


def fox(mod, w):
    """Kb[i]: the coefficient matrices of z(w) = sum_i Kb[i] z(s_i), and the matrix of w"""
    p, d = mod.p, mod.d
    Kb = {}
    P = np.eye(d, dtype=np.int64)
    for i, e in w:
        if e == 1:
            Kb[i] = (Kb.get(i, 0) + P) % p
            P = mmul(P, mod.M[i], p)
        else:
            P = mmul(P, mod.Mi[i], p)
            Kb[i] = (Kb.get(i, 0) - P) % p
    return Kb, P


def cocycle_value(mod, z, w):
    d = mod.d
    Kb, _ = fox(mod, w)
    out = np.zeros(d, dtype=np.int64)
    for i, K in Kb.items():
        out = (out + mmul(K, z[i * d:(i + 1) * d].reshape(d, 1), mod.p).ravel()) % mod.p
    return out


class Coh:
    """h^0, H^1, the restriction to every cusp, r1, n and t0 for one module on the cover"""

    def __init__(self, mod):
        self.mod = mod
        p, d = mod.p, mod.d
        ng = len(mod.M)
        self.d, self.ng = d, ng
        rows = []
        for w in mod.cov.rels:
            Kb, P = fox(mod, w)
            assert not np.any((P - np.eye(d, dtype=np.int64)) % p), "a cover relator is not the identity"
            blk = np.zeros((d, d * ng), dtype=np.int64)
            for i, K in Kb.items():
                blk[:, i * d:(i + 1) * d] = K
            rows.append(blk)
        J = np.concatenate(rows, axis=0) if rows else np.zeros((0, d * ng), dtype=np.int64)
        self.Z = nullspace(J, p, d * ng)
        Dg = [(A - np.eye(d, dtype=np.int64)) % p for A in mod.M]
        self.a0 = d - rank(np.concatenate(Dg, axis=0), p)
        self.Bv = np.concatenate([D.T for D in Dg], axis=1)          # rows j: the coboundary of e_j
        self.dimB = rank(self.Bv, p)
        assert self.dimB == d - self.a0
        self.h1 = len(self.Z) - self.dimB
        # the cusps, jointly
        self.cusps = []
        BP_rows, t0 = [], 0
        for (w1, w2) in mod.cov.cusps:
            K1, P1m = fox(mod, w1)
            K2, P2m = fox(mod, w2)
            D1, D2 = (P1m - np.eye(d, dtype=np.int64)) % p, (P2m - np.eye(d, dtype=np.int64)) % p
            t0 += d - rank(np.concatenate([D1, D2], axis=0), p)
            self.cusps.append((K1, K2, D1, D2))
        nc = len(self.cusps)
        self.t0 = t0
        self.BP = np.zeros((nc * d, nc * 2 * d), dtype=np.int64)     # rows: the cusp coboundaries, cusp by cusp
        for ci, (K1, K2, D1, D2) in enumerate(self.cusps):
            for j in range(d):
                self.BP[ci * d + j, ci * 2 * d:ci * 2 * d + d] = D1[:, j]
                self.BP[ci * d + j, ci * 2 * d + d:ci * 2 * d + 2 * d] = D2[:, j]
        self.rBP = rank(self.BP, p)
        RZ = np.array([self.restrict(z) for z in self.Z], dtype=np.int64).reshape(len(self.Z), nc * 2 * d)
        self.r1 = rank(np.concatenate([self.BP, RZ], axis=0), p) - self.rBP
        self.n = self.h1 - self.r1
        # H^1 representatives
        basis = [b for b in rref(self.Bv, p)[0]]
        self.reps = []
        for z in self.Z:
            if rank(np.array(basis + [z]), p) > len(basis):
                basis.append(z)
                self.reps.append(z)
        assert len(self.reps) == self.h1

    def restrict(self, z):
        d, p = self.d, self.mod.p
        out = []
        for (K1, K2, D1, D2) in self.cusps:
            for K in (K1, K2):
                v = np.zeros(d, dtype=np.int64)
                for i, Kk in K.items():
                    v = (v + mmul(Kk, z[i * d:(i + 1) * d].reshape(d, 1), p).ravel()) % p
                out.append(v)
        return np.concatenate(out) if out else np.zeros(0, dtype=np.int64)

    def interior_basis(self):
        """a basis of the interior classes, as cocycles: combinations of reps whose restriction lies in the cusp coboundaries"""
        p = self.mod.p
        if not self.reps:
            return []
        R = np.array([self.restrict(z) for z in self.reps], dtype=np.int64)
        A = np.concatenate([R, (-self.BP) % p], axis=0).T            # unknowns (x over reps, v over BP rows)
        sol = nullspace(A, p)
        k = len(self.reps)
        xs = []
        for s in sol:
            x = s[:k]
            if np.any(x) and rank(np.array(xs + [x]), p) > len(xs):
                xs.append(x)
        assert len(xs) == self.n, (len(xs), self.n)
        return [(sum((int(c) * z for c, z in zip(x, self.reps)), np.zeros_like(self.reps[0]))) % p for x in xs]

    def kernel_at(self, cusp_ids):
        """cocycles (combinations of reps) whose restriction vanishes in H^1 of the given cusps"""
        p, d = self.mod.p, self.d
        if not self.reps:
            return []
        cols = []
        for ci in cusp_ids:
            cols += list(range(ci * 2 * d, (ci + 1) * 2 * d))
        R = np.array([self.restrict(z)[cols] for z in self.reps], dtype=np.int64)
        BPs = np.array([row[cols] for row in self.BP if np.any(row[cols])], dtype=np.int64).reshape(-1, len(cols))
        A = np.concatenate([R, (-BPs) % p], axis=0).T
        sol = nullspace(A, p)
        k = len(self.reps)
        return [(sum((int(c) * z for c, z in zip(s[:k], self.reps)), np.zeros_like(self.reps[0]))) % p
                for s in sol if np.any(s[:k])]


def class_index(mod):
    A, B = Coh(mod), Coh(mod.dual())
    I = A.n - B.n
    assert I == (A.a0 - B.a0) + B.t0 - A.r1, "B1297's identity"
    assert A.r1 + B.r1 == A.t0 + B.t0, "the annihilator identity"
    return {"I": I, "A": A, "B": B}


# ============================================================================================ the frame and Theorem C on the cover
def extension(V, z, Lvals):
    """[[V, z L], [0, L]] on the cover: z a cocycle of V (x) L^-1 (concatenated), Lvals the line's values per generator"""
    p, d = V.p, V.d
    mats = []
    for i, A in enumerate(V.M):
        W = np.zeros((d + 1, d + 1), dtype=np.int64)
        W[:d, :d] = A
        W[:d, d] = (z[i * d:(i + 1) * d] * Lvals[i]) % p
        W[d, d] = Lvals[i]
        mats.append(W)
    return CModule(V.cov, V.F, mats)


def wedge2_mat(A, p):
    n = A.shape[0]
    idx = [(i, j) for i in range(n) for j in range(i + 1, n)]
    W = np.zeros((len(idx), len(idx)), dtype=np.int64)
    for a, (i, j) in enumerate(idx):
        for b, (k, m) in enumerate(idx):
            W[a, b] = (A[i, k] * A[j, m] - A[i, m] * A[j, k]) % p
    return W


PAIRS5 = [(i, j) for i in range(5) for j in range(i + 1, 5)]
SUB2 = [a for a, (i, j) in enumerate(PAIRS5) if j < 4]
QUO2 = [a for a, (i, j) in enumerate(PAIRS5) if j == 4]


def les(mod, dS):
    S, Q = mod.blocks(dS)
    cS, cQ, cE = Coh(S), Coh(Q), Coh(mod)
    dims = {nm: {"h0": c.a0, "h1": c.h1, "t0": c.t0, "n": c.n} for nm, c in (("S", cS), ("Q", cQ), ("E", cE))}
    rk0 = cS.a0 + cQ.a0 - cE.a0
    rk1 = cS.h1 + cQ.h1 - cE.h1 - rk0
    rk0P = cS.t0 + cQ.t0 - cE.t0
    return {**dims, "rk d0": rk0, "rk d1": rk1, "rk d0_P": rk0P, "pieces": (class_index(S)["I"], class_index(Q)["I"])}


def reading(W):
    """Theorem C's identities on the cover at the frame module W (5-dim, V first)"""
    p = W.p
    L2 = CModule(W.cov, W.F, [wedge2_mat(A, p) for A in W.M])
    mods = {"E": (W, 4),
            "E*": (W.dual().permuted([4, 0, 1, 2, 3]), 1),
            "L2": (L2.permuted(SUB2 + QUO2), 6),
            "L2*": (L2.dual().permuted(QUO2 + SUB2), 4)}
    L = {nm: les(md, dS) for nm, (md, dS) in mods.items()}
    idx = {nm: class_index(md)["I"] for nm, (md, dS) in mods.items()}
    k = L["L2"]["rk d0_P"]
    nQ2s, nV, nL, b0 = L["L2*"]["S"]["n"], L["E"]["S"]["n"], L["E"]["Q"]["n"], L["E"]["rk d0"]
    lemma_e = all(idx[a] == (sum(L[a]["pieces"]) + (L[a]["rk d1"] - L[b]["rk d1"]) + (L[b]["rk d0"] - L[a]["rk d0"]) +
                             (L[a]["rk d0_P"] - L[b]["rk d0_P"])) for a, b in (("E", "E*"), ("L2", "L2*")))
    checks = {
        "the duals' indices": idx["E*"] == -idx["E"] and idx["L2*"] == -idx["L2"],
        "Lemma E assembled from the pieces": lemma_e,
        "I(S) = I(Q) = 0 for every piece": all(L[nm]["pieces"] == (0, 0) for nm in L),
        "L2: rk d0 = rk d0* = 0": L["L2"]["rk d0"] == 0 and L["L2*"]["rk d0"] == 0,
        "L2: rk d1 = 0": L["L2"]["rk d1"] == 0,
        "L2*: rk d0_P = 0": L["L2*"]["rk d0_P"] == 0,
        "I(L2) = k - rk d1(L2*)": idx["L2"] == k - L["L2*"]["rk d1"],
        "k <= rk d1(L2*) <= k + n((VL)*)": k <= L["L2*"]["rk d1"] <= k + nQ2s,
        "W: rk d0(E*) = 0 and rk d0_P(E*) = 0": L["E*"]["rk d0"] == 0 and L["E*"]["rk d0_P"] == 0,
        "W: rk d0_P(E) = k": L["E"]["rk d0_P"] == k,
        "W: rk d1(E) <= n(V)": L["E"]["rk d1"] <= nV,
        "W: rk d1(E*) <= k + n(L)": L["E*"]["rk d1"] <= k + nL,
        "I(E) = -b0 + k + rk d1(E) - rk d1(E*)": idx["E"] == -b0 + k + L["E"]["rk d1"] - L["E*"]["rk d1"],
        "cap: -n((VL)*) <= I(L2) <= 0": -nQ2s <= idx["L2"] <= 0,
        "cap: I(E) >= -b0 - n(L)": idx["E"] >= -b0 - nL,
    }
    return {"I(W)": idx["E"], "I(L2W)": idx["L2"], "k": k, "b0": b0, "n((VL)*)": nQ2s, "n(V)": nV, "n(L)": nL,
            "rk d1": {nm: L[nm]["rk d1"] for nm in L}, "checks": checks, "all": all(checks.values())}
