"""T-PERIOD-2-INVERTS-THE-ALEXANDER-MODULE, checked symbolically: with a -> 1, b -> t the Fox complex of <a,b | aaabABBAb> gives
H1(X~) = Z[t^+-]/(dr/da) with dr/da = unit * Delta, ker d1 = Z[t^+-] e_a, and the period-2 automorphism P (a -> a^-1, b -> a^3 b)
acts on e_a by dP(a)/da = -a^-1 -> -1.  Hence P = -1 on H1(X~) and on Tors H1(C_n) for every cyclic cover C_n."""
import sympy as sp
t = sp.symbols('t')
REL = "aaabABBAb"
def fox_ab(word, var):
    """Fox derivative d(word)/d(var) evaluated under a -> 1, b -> t (a Laurent polynomial in t)"""
    total = 0; prefix = 1
    for ch in word:
        g = ch.lower(); e = 1 if ch.islower() else -1
        img = sp.Integer(1) if g == "a" else t
        if g == var:
            if e == 1: total += prefix
            else: total -= prefix * img**-1
        prefix *= img**e
    return sp.simplify(total)
dra, drb = fox_ab(REL, "a"), fox_ab(REL, "b")
Delta = t**2 - 3*t + 1
print("dr/da =", sp.factor(dra), "   dr/db =", sp.simplify(drb), "   (must be 0: d1 d2 = 0 with a -> 1)")
print("dr/da / Delta =", sp.simplify(dra / Delta), "  => H1(X~) = Z[t^+-]/(Delta), generated by e_a")
# P: a -> A, b -> aaab.  Induced map on C1: e_a -> (dP(a)/da) e_a + (dP(a)/db) e_b ; e_b -> (dP(b)/da) e_a + (dP(b)/db) e_b
Pa, Pb = "A", "aaab"
u_aa, u_ab = fox_ab(Pa, "a"), fox_ab(Pa, "b")
u_ba, u_bb = fox_ab(Pb, "a"), fox_ab(Pb, "b")
print("P on C1 (a->1, b->t):  e_a -> (%s) e_a + (%s) e_b ;  e_b -> (%s) e_a + (%s) e_b" % (u_aa, u_ab, u_ba, u_bb))
print("P commutes with the deck action (P(b) -> t):", sp.simplify(fox_ab(Pb, "b") * (t - 1) + fox_ab(Pb, "a") * 0 - (t - 1)) == 0)
print("=> P acts on H1(X~) = Z[t^+-] e_a / (Delta) as multiplication by", u_aa)
assert sp.simplify(u_aa + 1) == 0 and sp.simplify(u_ab) == 0
# consequences on the cyclic covers: Tors H1(C_n) = torsion of Z[t]/(Delta, t^n - 1) (+ the free part); P = -1 there; sizes:
for n in (2, 3, 4, 5, 6):
    # order of the torsion = |prod_{zeta^n = 1, zeta != 1} Delta(zeta)| = |Res(Delta, (t^n-1)/(t-1))|
    q = sp.quo(t**n - 1, t - 1)
    print(f"  n={n}: |Tors H1(C_n)| = |Res(Delta, (t^n-1)/(t-1))| = {abs(sp.resultant(Delta, q, t))}")
print("T-PERIOD-2-INVERTS-THE-ALEXANDER-MODULE: PASS")
