"""Main's B1615 (the couplings the weave allows) and B1616 (the neutrino masses on the weave) verified with this seat's
code. A VERIFICATION, not blind: both read-outs were read first (main @ dfb57904).

The weave's group on the matter triplet T is rebuilt as in W35, from W21's construction, in the orthonormal basis of the
Hodge-Riemann form. Then:
  - the invariants' dimensions by characters: T (x) T-bar, T (x) T, Sym^2 T, Lambda^2 T, T (x) T (x) T, T (x) T (x) T-bar;
  - Dirac masses. T-bar (x) T is End(T), M -> g M g^dagger. Its isotypic pieces are those of a generic element of the
    commutant. For each piece and each residual element (L, R, RL, RRL) the fixed matrices; the masses are the singular
    values. A one-dimensional fixed space gives a rigid spectrum; a two-dimensional one a family, sampled for a sum rule;
  - Majorana masses. Sym^2 T is the symmetric matrices, M -> g M g^T. Its pieces, and each residual element's fixed
    symmetric matrices; the masses are the singular values (Takagi). Lambda^2 T's commutant.

Run: python3 the_couplings_verified.py  ->  the_couplings_verified.json beside it.
"""
import itertools
import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import the_mixing_patterns_verified as MV  # noqa: E402  (W35: the weave's group on T, in Q's orthonormal basis)

OUT = HERE / "the_couplings_verified.json"
RNG = np.random.default_rng(38)
TOL = 1e-8


def the_group():
    named, _ = MV.H.triplets()
    C = named["T"]
    G0 = MV.H.gram_V()
    Qt = C.conj().T @ G0 @ C
    K = np.linalg.cholesky((Qt + Qt.conj().T) / 2).conj().T
    gens_V = [MV.CT.on_V(MV.CP.AUT[m], g) for m in ("L", "R") for g in MV.CP.extend(MV.CP.AUT[m])]
    GV = MV.CT.closure(gens_V)
    GT = {}
    for X in GV:
        g = MV.on_T(C, K, X)
        GT[tuple(np.round(np.concatenate([g.real.ravel(), g.imag.ravel()]), 6))] = g
    gens = [MV.on_T(C, K, X) for X in gens_V]
    (_, gL, gR) = MV.H.lift_choices()[0]
    lifts = {"L": MV.CT.on_V(MV.CP.AUT["L"], gL), "R": MV.CT.on_V(MV.CP.AUT["R"], gR)}
    el = {w: MV.on_T(C, K, MV.word(lifts, w)) for w in ("L", "R", "RL", "RRL")}
    return list(GT.values()), gens, el


def null(A, tol=TOL):
    _, s, vh = np.linalg.svd(A)
    r = int(sum(s > tol * max(1.0, s[0] if len(s) else 1.0)))
    return vh[r:].conj().T


def pieces(ops, dim):
    """the isotypic pieces of the representation generated by ops (dim x dim), from a generic commutant element"""
    M = np.vstack([np.kron(np.eye(dim), A) - np.kron(A.T, np.eye(dim)) for A in ops])
    Nb = null(M)
    comm_dim = Nb.shape[1]
    X = sum(RNG.normal() * Nb[:, i].reshape(dim, dim, order="F") for i in range(comm_dim))
    X = X + 0.37j * sum(RNG.normal() * Nb[:, i].reshape(dim, dim, order="F") for i in range(comm_dim))
    w, V = np.linalg.eig(X)
    groups = []
    for i, z in enumerate(w):
        for grp in groups:
            if abs(grp[0] - z) < 1e-6:
                grp[1].append(i)
                break
        else:
            groups.append([z, [i]])
    out = []
    for _, idx in groups:
        Q, _ = np.linalg.qr(V[:, idx])
        out.append(Q[:, :len(idx)])
    return comm_dim, out


def fixed_in(piece, op):
    """the vectors of the piece that op fixes, as a basis"""
    A = (op - np.eye(op.shape[0])) @ piece
    n = null(A)
    return piece @ n if n.shape[1] else np.zeros((op.shape[0], 0))


def spectrum(Mvec, shape_basis):
    M = shape_basis(Mvec)
    s = np.sort(np.linalg.svd(M, compute_uv=False))
    return s / s[-1] if s[-1] > 1e-12 else s


def main():
    GT, gens, el = the_group()
    order = len(GT)
    tr = [np.trace(g) for g in GT]
    tr2 = [np.trace(g @ g) for g in GT]
    inv = {
        "T (x) T-bar": round(float(np.real(sum(abs(t) ** 2 for t in tr)) / order), 6),
        "T (x) T": round(float(np.real(sum(t ** 2 for t in tr)) / order), 6),
        "Sym^2 T": round(float(np.real(sum((t ** 2 + u) / 2 for t, u in zip(tr, tr2))) / order), 6),
        "Lambda^2 T": round(float(np.real(sum((t ** 2 - u) / 2 for t, u in zip(tr, tr2))) / order), 6),
        "T (x) T (x) T": round(float(np.real(sum(t ** 3 for t in tr)) / order), 6),
        "T (x) T (x) T-bar": round(float(np.real(sum(t ** 2 * np.conj(t) for t in tr)) / order), 6),
    }

    # ---- Dirac: End(T), M -> g M g^dagger, vec column-major: kron(conj(g), g)
    def endo(g):
        return np.kron(g.conj(), g)

    cd, pcs = pieces([endo(g) for g in gens], 9)
    dirac = {"commutant dimension": cd, "piece dimensions": sorted(p.shape[1] for p in pcs)}
    rows = []
    shape9 = (lambda v: v.reshape(3, 3, order="F"))
    sumrule = {}
    for p in sorted(pcs, key=lambda q: q.shape[1]):
        d = p.shape[1]
        for w, k in el.items():
            F = fixed_in(p, endo(k))
            f = F.shape[1]
            row = {"piece dimension": d, "residual": w, "fixed dimension": f}
            if f == 1:
                row["spectrum"] = [round(float(x), 6) for x in spectrum(F[:, 0], shape9)]
            if f == 2:
                worst, lo, hi = 0.0, 1.0, 0.0
                for _ in range(4000):
                    c = RNG.normal(size=2) + 1j * RNG.normal(size=2)
                    s = spectrum(F @ c, shape9)
                    worst = max(worst, abs(s[0] + s[1] - s[2]))
                    lo, hi = min(lo, s[0]), max(hi, s[0])
                row["family: max |m1 + m2 - m3| / m3 over 4000 samples"] = float("%.3g" % worst)
                row["family: m1/m3 sampled range"] = [round(lo, 4), round(hi, 4)]
                sumrule[(d, w)] = worst
            rows.append(row)
    dirac["fixed vacua"] = rows
    singlet = [p for p in pcs if p.shape[1] == 1]
    dirac["the singlet Higgs's spectrum"] = [round(float(x), 6) for x in spectrum(singlet[0][:, 0], shape9)] if singlet else None

    # ---- Majorana: symmetric matrices, M -> g M g^T, vec: kron(g, g) restricted to Sym^2
    S = []
    for i, j in itertools.combinations_with_replacement(range(3), 2):
        E = np.zeros((3, 3), dtype=complex)
        E[i, j] = E[j, i] = 1.0
        S.append(E.reshape(9, order="F") / np.linalg.norm(E))
    S = np.array(S).T                                         # 9 x 6, orthonormal
    A_ = []
    for i, j in itertools.combinations(range(3), 2):
        E = np.zeros((3, 3), dtype=complex)
        E[i, j], E[j, i] = 1.0, -1.0
        A_.append(E.reshape(9, order="F") / np.linalg.norm(E))
    A_ = np.array(A_).T                                       # 9 x 3

    def sym_op(g):
        return S.conj().T @ np.kron(g, g) @ S

    def alt_op(g):
        return A_.conj().T @ np.kron(g, g) @ A_

    cds, spcs = pieces([sym_op(g) for g in gens], 6)
    cda, _ = pieces([alt_op(g) for g in gens], 3)
    shape6 = (lambda v: (S @ v).reshape(3, 3, order="F"))
    mrows = []
    for p in sorted(spcs, key=lambda q: q.shape[1]):
        for w, k in el.items():
            F = fixed_in(p, sym_op(k))
            f = F.shape[1]
            row = {"piece dimension": p.shape[1], "residual": w, "fixed dimension": f}
            if f == 1:
                row["spectrum"] = [round(float(x), 6) for x in spectrum(F[:, 0], shape6)]
            mrows.append(row)
    majorana = {"Sym^2 T: commutant dimension": cds, "Sym^2 T: piece dimensions": sorted(p.shape[1] for p in spcs),
                "Lambda^2 T: commutant dimension (1 = irreducible)": cda, "fixed vacua": mrows}

    # ---- the checks against B1615 and B1616
    rrl_triplet_family = [r for r in rows if r["residual"] == "RRL" and r["fixed dimension"] == 2]
    spectra_dirac = {tuple(r["spectrum"]) for r in rows if "spectrum" in r}
    spectra_major = {tuple(r["spectrum"]) for r in mrows if "spectrum" in r}
    res = {
        "status": "VERIFICATION of main's B1615 and B1616 (read first), with this seat's code",
        "the group's order on T": order,
        "invariant dimensions (characters)": inv,
        "Dirac (T-bar (x) T = End T)": dirac,
        "Majorana (Sym^2 T)": majorana,
        "RL has three distinct eigenvalues on T": len(np.unique(np.round(np.linalg.eigvals(el["RL"]), 6))) == 3,
    }
    res["checks"] = {
        "order 96": order == 96,
        "(T (x) T-bar)^G = 1; T (x) T, Sym^2, Lambda^2, T (x) T (x) T, T (x) T (x) T-bar have none": (
            inv["T (x) T-bar"] == 1 and all(inv[k] == 0 for k in ("T (x) T", "Sym^2 T", "Lambda^2 T", "T (x) T (x) T",
                                                                   "T (x) T (x) T-bar"))),
        "T-bar (x) T = 3 + 3 + 2 + 1, each once": dirac["piece dimensions"] == [1, 2, 3, 3] and cd == 4,
        "a singlet Higgs gives (1, 1, 1)": dirac["the singlet Higgs's spectrum"] == [1.0, 1.0, 1.0],
        "rigid Dirac spectra are (0, 1, 1) and (1/2, 1/2, 1)": spectra_dirac <= {(0.0, 1.0, 1.0), (0.5, 0.5, 1.0),
                                                                              (1.0, 1.0, 1.0)},
        "along RRL one triplet has a two-dimensional family with m1 + m2 = m3": (
            len(rrl_triplet_family) == 1 and rrl_triplet_family[0]["piece dimension"] == 3
            and rrl_triplet_family[0]["family: max |m1 + m2 - m3| / m3 over 4000 samples"] < 1e-9),
        "Sym^2 T = 1 + 2 + 3; Lambda^2 T irreducible": (majorana["Sym^2 T: piece dimensions"] == [1, 2, 3]
                                                        and cda == 1),
        "along RRL no Majorana vacuum is fixed": all(r["fixed dimension"] == 0 for r in mrows if r["residual"] == "RRL"),
        "rigid Majorana spectra are (1, 1, 1), (1/2, 1/2, 1), (0, 1, 1)": spectra_major <= {
            (1.0, 1.0, 1.0), (0.5, 0.5, 1.0), (0.0, 1.0, 1.0)} and len(spectra_major) >= 2,
        "RL has three distinct eigenvalues": res["RL has three distinct eigenvalues on T"],
    }
    res["every check holds"] = all(res["checks"].values())
    OUT.write_text(json.dumps(res, indent=1, ensure_ascii=False, default=str) + "\n", encoding="utf-8")
    print(json.dumps(res, indent=1, ensure_ascii=False, default=str))


if __name__ == "__main__":
    main()
