"""Main's B1612 (the mixing patterns the weave fixes) verified with this seat's own code. A VERIFICATION, not blind: B1612's
read-out was read first (main @ 80f48eeb).

The weave's group is built here from W21's construction, not from main's instrument: V = H^1(F2; sum_p chi_p (x) rho_Q)
with the moves' lifts (the_chiral_triplet.on_V), its closure, the holomorphic triplet T (the_holomorphic_triplet.
triplets), and the Hodge-Riemann form Q, positive on T, as the inner product. On T:
  - the image's order and the elements with three distinct eigenvalues;
  - every abelian subgroup generated by at most two elements whose joint eigenspaces are three lines: the eigenbases;
  - every element with exactly one simple eigenvalue: the eigenlines;
  - the patterns |U|^2 between two eigenbases, and the columns between an eigenbasis and an eigenline, each up to the
    order of rows and columns;
  - B1612's named cells: L against R (bimaximal), RL against <RR, R^-1 L L> (tri-bimaximal), L against RL (trimaximal,
    |U_e3|^2 = (2 - sqrt 3)/6), RL against RR's eigenline (TM2) and against RRL's eigenline (TM1).

Run: python3 the_mixing_patterns_verified.py  ->  the_mixing_patterns_verified.json beside it.
"""
import itertools
import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import the_chiral_triplet as CT  # noqa: E402  (the moves on V, the closure)
import the_common_point as CP  # noqa: E402  (the moves as automorphisms, their lifts in 2O)
import the_holomorphic_triplet as H  # noqa: E402  (T and T-bar, the Hodge-Riemann form)

OUT = HERE / "the_mixing_patterns_verified.json"
TOL = 1e-8


def on_T(C, K, X):
    """X (on V) restricted to T in the basis C, then made unitary by the Cholesky factor K of Q on T"""
    t = H.restrict(C, X)
    return K @ t @ np.linalg.inv(K)


def eigenspaces(g):
    w, V = np.linalg.eig(g)
    groups = []
    for i, z in enumerate(w):
        for grp in groups:
            if abs(grp[0] - z) < 1e-6:
                grp[1].append(i)
                break
        else:
            groups.append([z, [i]])
    out = []
    for z, idx in groups:
        Q_, _ = np.linalg.qr(V[:, idx])
        out.append(Q_[:, :len(idx)])
    return out


def line_key(v):
    v = v / np.linalg.norm(v)
    k = int(np.argmax(np.abs(v) > 1e-6))
    v = v * abs(v[k]) / v[k]
    return tuple(np.round(np.concatenate([v.real, v.imag]), 6))


def basis_key(lines):
    return tuple(sorted(line_key(v) for v in lines))


def joint_lines(gs):
    """the joint eigenspaces of commuting matrices, as lines if they are all lines, else None"""
    spaces = [np.eye(3, dtype=complex)]
    for g in gs:
        new = []
        for S in spaces:
            if S.shape[1] == 1:
                new.append(S)
                continue
            gS = np.linalg.lstsq(S, g @ S, rcond=None)[0]
            for E in eigenspaces(gS):
                new.append(S @ E)
        spaces = new
    if len(spaces) == 3 and all(S.shape[1] == 1 for S in spaces):
        return [S[:, 0] / np.linalg.norm(S[:, 0]) for S in spaces]
    return None


def pattern(B1, B2):
    M = np.array([[abs(np.vdot(u, v)) ** 2 for v in B2] for u in B1])
    return M


def canon_matrix(M):
    best = None
    for pr in itertools.permutations(range(3)):
        for pc in itertools.permutations(range(3)):
            t = tuple(round(float(M[i][j]), 6) for i in pr for j in pc)
            if best is None or t < best:
                best = t
    return best


def canon_column(c):
    return tuple(sorted(round(float(x), 6) for x in c))


def word(lifts, w):
    g = np.eye(6, dtype=complex)
    for ch in w:
        g = g @ (lifts[ch.upper()] if ch.isupper() else np.linalg.inv(lifts[ch.upper()]))
    return g


def main():
    named, order_V = H.triplets()
    C = named["T"]
    G0 = H.gram_V()
    Qt = C.conj().T @ G0 @ C
    Qt = (Qt + Qt.conj().T) / 2
    ev = np.linalg.eigvalsh(Qt)
    assert all(ev > 0), "Q is not positive on T"
    K = np.linalg.cholesky(Qt).conj().T                        # Qt = K^H K
    gens = [CT.on_V(CP.AUT[m], g) for m in ("L", "R") for g in CP.extend(CP.AUT[m])]
    GV = CT.closure(gens)
    GT = [on_T(C, K, X) for X in GV]
    for g in GT:
        assert np.allclose(g.conj().T @ g, np.eye(3), atol=1e-7), "not unitary in Q's basis"
    imgs = {}
    for g in GT:
        imgs[tuple(np.round(np.concatenate([g.real.ravel(), g.imag.ravel()]), 6))] = g
    GT = list(imgs.values())
    distinct = [g for g in GT if len(eigenspaces(g)) == 3]

    bases = {}
    for g in GT:
        B = joint_lines([g])
        if B is not None:
            bases.setdefault(basis_key(B), B)
    for g, h in itertools.combinations(GT, 2):
        if np.allclose(g @ h, h @ g, atol=1e-7):
            B = joint_lines([g, h])
            if B is not None:
                bases.setdefault(basis_key(B), B)
    lines = {}
    for g in GT:
        sp = eigenspaces(g)
        if len(sp) == 2:
            for S in sp:
                if S.shape[1] == 1:
                    lines.setdefault(line_key(S[:, 0]), S[:, 0])
    blist, llist = list(bases.values()), list(lines.values())
    patterns, columns = {}, {}
    for B1, B2 in itertools.combinations(blist, 2):
        M = pattern(B1, B2)
        patterns.setdefault(canon_matrix(M), M)
    for B in blist:
        for v in llist:
            c = [abs(np.vdot(u, v)) ** 2 for u in B]
            columns.setdefault(canon_column(c), c)

    # B1612's named cells, with the lifts chosen by W21's braid relation
    (_, gL, gR) = H.lift_choices()[0]
    lifts = {"L": CT.on_V(CP.AUT["L"], gL), "R": CT.on_V(CP.AUT["R"], gR)}
    el = {w: on_T(C, K, word(lifts, w)) for w in ("L", "R", "RL", "RR", "rLL", "RRL")}
    basis_of = {w: joint_lines([el[w]]) for w in ("L", "R", "RL")}
    klein = joint_lines([el["RR"], el["rLL"]])
    commute = bool(np.allclose(el["RR"] @ el["rLL"], el["rLL"] @ el["RR"], atol=1e-7))

    def eigline(w):
        sp = [S for S in eigenspaces(el[w]) if S.shape[1] == 1]
        return sp[0][:, 0] if len(sp) == 1 else None

    def col(B, v):
        return canon_column([abs(np.vdot(u, v)) ** 2 for u in B])

    s3 = np.sqrt(3)
    named_cells = {
        "L against R (bimaximal: canonical form)": canon_matrix(pattern(basis_of["L"], basis_of["R"])),
        "RL against <RR, R^-1 L L> (tri-bimaximal)": canon_matrix(pattern(basis_of["RL"], klein)) if klein else None,
        "RR and R^-1 L L commute": commute,
        "L against RL: the smallest entry (trimaximal, (2 - sqrt 3)/6 = %.6f)" % ((2 - s3) / 6):
            round(float(np.min(pattern(basis_of["L"], basis_of["RL"]))), 6),
        "RL against RR's eigenline (TM2)": col(basis_of["RL"], eigline("RR")) if eigline("RR") is not None else None,
        "RL against RRL's eigenline (TM1)": col(basis_of["RL"], eigline("RRL")) if eigline("RRL") is not None else None,
    }
    tbm = canon_matrix(np.array([[2 / 3, 1 / 3, 0], [1 / 6, 1 / 3, 1 / 2], [1 / 6, 1 / 3, 1 / 2]]))
    bm = canon_matrix(np.array([[1 / 2, 1 / 2, 0], [1 / 4, 1 / 4, 1 / 2], [1 / 4, 1 / 4, 1 / 2]]))
    res = {
        "status": "VERIFICATION of main's B1612 (read first), from this seat's W21 construction",
        "the group on V (order)": len(GV),
        "the image on T (order)": len(GT),
        "elements of the image with three distinct eigenvalues": len(distinct),
        "eigenbases": len(blist),
        "eigenlines": len(llist),
        "full patterns (canonical |U|^2, rows of three)": [[list(p[i:i + 3]) for i in (0, 3, 6)] for p in sorted(patterns)],
        "the number of full patterns": len(patterns),
        "columns (sorted)": sorted(list(c) for c in columns),
        "the number of columns": len(columns),
        "B1612's named cells": named_cells,
        "checks": {
            "order 96 on T": len(GT) == 96,
            "56 elements with distinct eigenvalues": len(distinct) == 56,
            "11 eigenbases": len(blist) == 11,
            "6 full patterns": len(patterns) == 6,
            "5 columns": len(columns) == 5,
            "tri-bimaximal among the patterns": tbm in patterns,
            "bimaximal among the patterns": bm in patterns,
            "democratic among the patterns": canon_matrix(np.full((3, 3), 1 / 3)) in patterns,
            "TM1 (1/6, 1/6, 2/3) among the columns": (0.166667, 0.166667, 0.666667) in columns,
            "TM2 (1/3, 1/3, 1/3) among the columns": (0.333333, 0.333333, 0.333333) in columns,
            "L against R is bimaximal": named_cells["L against R (bimaximal: canonical form)"] == bm,
            "RL against <RR, R^-1 L L> is tri-bimaximal":
                named_cells["RL against <RR, R^-1 L L> (tri-bimaximal)"] == tbm,
            "L against RL has (2 - sqrt 3)/6":
                bool(abs(named_cells["L against RL: the smallest entry (trimaximal, (2 - sqrt 3)/6 = %.6f)" % ((2 - s3) / 6)]
                    - (2 - s3) / 6) < 1e-6),
            "RL against RR's eigenline is TM2": named_cells["RL against RR's eigenline (TM2)"] == (0.333333,) * 3,
            "RL against RRL's eigenline is TM1":
                named_cells["RL against RRL's eigenline (TM1)"] == (0.166667, 0.166667, 0.666667),
        },
    }
    res["every check holds"] = all(res["checks"].values())
    OUT.write_text(json.dumps(res, indent=1, ensure_ascii=False, default=str) + "\n", encoding="utf-8")
    print(json.dumps(res, indent=1, ensure_ascii=False, default=str))


if __name__ == "__main__":
    main()
