"""B95 (Task M) -- the degree=rank mechanism: the principal spectrum is forced, and it degenerates at n>=5.

The audit (V75) killed the "exponent = Cayley-Hamilton degree" mechanism (both SL(4) components have CH
degree 4 but exponents 4 and 3). The exponent reads the SPECIFIC eigenvalue structure of A. This stage
finds what the principal component's spectrum must be, and shows the "exponent = rank" pattern is a
LOW-RANK (n=3,4) phenomenon -- it cannot be continued to n>=5.

(1) THE PRINCIPAL SPECTRUM IS FORCED. On the principal degree=rank component tr A = tr A^-1 = 1, with the
    eigenvalue 1 at multiplicity n-2 (verified n=3,4: {1,i,-i}, {1,1,w,w2}). The two remaining eigenvalues
    a, 1/a (det A = 1) satisfy a + 1/a = 3 - n (from tr A = 1), i.e. 2 cos(theta) = 3 - n:
        n=3: 2cos=0   -> a = i        -> {1, i, -i}        (primitive 4th roots)
        n=4: 2cos=-1  -> a = w        -> {1, 1, w, w^2}    (primitive 3rd roots)
        n=5: 2cos=-2  -> a = -1       -> {1, 1, 1, -1, -1} (a = -1, order 2)
        n>=6: 2cos = 3-n <= -3 -> |cos| > 1 IMPOSSIBLE for a root of unity.
    So the handoff's guessed SL(5) spectrum {1,1,1,w,w2} (which has tr = 2, not 1) is WRONG; the forced
    one is {1,1,1,-1,-1}; and at n>=6 NO finite-order principal spectrum of this shape exists.

(2) THE n=5 PRINCIPAL DEGENERATES (proven). At n=5 the forced spectrum {1,1,1,-1,-1} has A^2 = I. The
    figure-eight bundle relation t A t^-1 = A^2 B then reads t A t^-1 = B, so B = t A t^-1 is conjugate to
    A and B^2 = I: both A and B are INVOLUTIONS. The group <A,B> generated by two involutions is DIHEDRAL,
    whose irreducible representations are all 1- or 2-dimensional; hence any 5-dimensional bundle rep is
    REDUCIBLE. (Verified: B = t A t^-1 for random t gives <A,B> with algebra-span rank 8 << 25.) So there
    is NO irreducible principal Dehn-filling rep at SL(5) -- this UPGRADES B78's numerical "method-limit"
    (only reducible reps found) to a structural reason: the component genuinely degenerates.

CONCLUSION (the mechanism, as far as this settles it). "exponent = rank" (M^n = L on the principal
component) is an n in {3, 4} phenomenon: the principal spectrum is forced, it gives an irreducible bundle
rep only at n=3 (A order 4) and n=4 (A order 3), it DEGENERATES to an involution/dihedral (reducible) at
n=5, and is IMPOSSIBLE (no root-of-unity spectrum) at n>=6. So the degree-pattern data is {n=3: 3},
{n=4: 4 (principal), 3 (secondary {prim 8th})}, and {n=5: the principal does not exist irreducibly}. The
mechanism does not read "matrix size"; it reads whether the cusp's forced finite-order spectrum admits an
irreducible rep -- which is exactly why both the tower (B84/B85) and degree=rank hit a wall at n>=5.

HONEST SCOPE. (1)-(2) are exact for the forced (mult-1 = n-2) principal spectrum. This does not
enumerate every tr=1 finite-order SL(5) spectrum (an alternative {1,i,i,-i,-i} was probed and also came
out reducible at small budget -- suggestive, not exhaustive); a complete degree CLASSIFICATION at every
rank remains open. The point established is structural: the principal M^n=L component is low-rank.

Standalone low-dim topology / representation theory; no physics, no Origin-core claim; P1-P16 untouched.
"""
from __future__ import annotations

import numpy as np
import sympy as sp

z = sp.symbols("z")


def forced_principal_spectrum(n):
    """The forced principal spectrum at rank n (eigenvalue 1 at mult n-2; two extra eigenvalues a,1/a with
    a+1/a = 3-n). Returns (spectrum_or_None, is_root_of_unity, a_plus_ainv)."""
    s = sp.Integer(3 - n)                        # a + 1/a
    cos = sp.Rational(s, 2)
    if abs(cos) > 1:
        return None, False, int(s)               # |cos| > 1: impossible for a root of unity
    disc = sp.sqrt(s * s - 4)
    a, ainv = sp.simplify((s + disc) / 2), sp.simplify((s - disc) / 2)   # the two roots, with multiplicity
    spec = [sp.Integer(1)] * (n - 2) + [a, ainv]                          # always n eigenvalues
    return spec, True, int(s)


def n5_principal_is_reducible(seeds=(0, 1, 2)):
    """At n=5 the forced spectrum {1,1,1,-1,-1} has A^2=I, forcing B=tAt^-1 (also an involution); <A,B> is
    dihedral -> reducible. Returns (A_squared_is_I, [algebra-span ranks] (all << 25))."""
    A = np.diag([1, 1, 1, -1, -1]).astype(complex)
    a2 = np.max(np.abs(A @ A - np.eye(5))) < 1e-12
    ranks = []
    ws = ["", "A", "B", "AB", "BA", "AA", "BB", "ABA", "BAB", "ABAB", "AABB"]
    for sd in seeds:
        rng = np.random.default_rng(sd)
        t = rng.standard_normal((5, 5)) + 1j * rng.standard_normal((5, 5))
        B = t @ A @ np.linalg.inv(t)             # forced by t A t^-1 = A^2 B = B
        g = {"A": A, "B": B}

        def word(s):
            M = np.eye(5, dtype=complex)
            for c in s:
                M = M @ g[c]
            return M.flatten()
        ranks.append(int(np.linalg.matrix_rank(np.array([word(w) for w in ws]), tol=1e-9)))
    return bool(a2), ranks


def main():
    print("B95 (Task M) -- the degree=rank mechanism: the principal spectrum is forced & degenerates at n>=5\n")
    print("(1) the forced principal spectrum (eigenvalue 1 at mult n-2; a+1/a = 3-n):")
    for n in range(3, 7):
        spec, rou, s = forced_principal_spectrum(n)
        if rou:
            print(f"    n={n}: a+1/a={s} -> spectrum {[sp.nsimplify(x) for x in spec]}")
        else:
            print(f"    n={n}: a+1/a={s} -> |cos|>1 IMPOSSIBLE (no finite-order principal of this shape)")
    print("\n(2) the n=5 forced principal {1,1,1,-1,-1} is reducible (A^2=I => A,B involutions => dihedral):")
    a2, ranks = n5_principal_is_reducible()
    print(f"    A^2 = I: {a2};  <A,B> algebra-span ranks {ranks} (all << 25 => REDUCIBLE)")
    print("\n=> 'exponent = rank' is an n in {3,4} phenomenon: the principal M^n=L component is irreducible")
    print("   only at n=3,4; it degenerates (dihedral/reducible) at n=5 and is impossible at n>=6.")
    print("   degree data: {n=3: 3}, {n=4: 4 principal, 3 secondary}, {n=5: principal not irreducible}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
