"""xB024 L1 -- THE FULL SHAPE FIELD, and the defect reading Neumann-Reid found in xB022 V4.

NEUMANN-REID, "Arithmetic of Hyperbolic Manifolds", Topology '90, de Gruyter (1992) 273-310,
read at source (Neumann's own copy, math.columbia.edu/~neumann/preprints/nrarith.pdf).  From the
text preceding Theorem 2.4, verbatim:

  "...the invariant trace field k(Gamma) in case M = H^3/Gamma is a CUSPED hyperbolic manifold.
   By [EP], M has at least one triangulation by ideal tetrahedra: M = S_1 u S_2 u ... u S_n, where
   each S_j is an ideal tetrahedron in H^3.  ... the tetrahedron S_j is described up to isometry by
   a single complex number z_j with positive imaginary part (the tetrahedral parameter of S_j) ...
   Denote the field Q(z_j : j = 1,...,n) by k_M or k_Delta.  A priori k_Delta might depend on the
   choice of triangulation, but we have:"

  THEOREM 2.4.  k_Delta = k(Gamma).

And from the paper's introduction:

  "It turns out that the existence of PARABOLIC elements in Gamma facilitates many arithmetic
   questions.  ... Moreover, k(Gamma) equals the field generated by the tetrahedral parameters of
   the ideal tetrahedra of ANY ideal triangulation of H^3/Gamma (Theorem 2.4)."

THE DEFECT THIS FOUND IN THIS SEAT'S OWN xB022 V4.  k_Delta is generated by ALL n tetrahedral
parameters.  xB022 V4's instrument computed the minimal polynomial of z_1 ALONE -- i.e. Q(z_1),
which can be a PROPER SUBFIELD of k_Delta = Q(z_1,...,z_n).  For m004 and m003 the two tetrahedra
share a shape, so the value reported there is right; but the 40-word corpus sample compared Q(z_1),
not the trace field.  This cell recomputes the FULL field and reports how often the two differ.
"""
import itertools
import json
import os

import snappy
from cypari import pari as P

R = {}
DET_DPS, CONF_DPS, DEG_MAX = 40, 80, 12


def shapes(name, dps):
    P.set_real_precision(dps)
    M = snappy.ManifoldHP(name)
    out = []
    for sh in M.tetrahedra_shapes("rect"):
        out.append(P("%s + (%s)*I" % (repr(sh.real()).replace(" ", ""),
                                      repr(sh.imag()).replace(" ", ""))))
    return out


def height_ok(q, dps=None):
    """THE HEIGHT GUARD -- the E56 lesson applied to integer-relation detection.

    algdep will ALWAYS return some polynomial; a spurious one of degree d and height H becomes
    findable once the working precision drops below roughly d*log10(H) digits.  So a detection is
    trustworthy only when the confirmation precision EXCEEDS that by a safety factor.  Without
    this guard the cell reported a degree-12 polynomial with 10^18-scale coefficients as a real
    field difference -- exactly the shape of this session's E56 instance (limit_denominator at a
    tolerance that could not support it)."""
    dps = CONF_DPS if dps is None else dps
    try:
        d = int(P.poldegree(q))
        H = max(abs(int(c)) for c in P.Vec(q))
    except Exception:
        return False
    import math
    need = d * math.log10(max(H, 2))
    return dps > 2.0 * need          # safety factor 2


def minpoly(z_det, z_conf, degmax=DEG_MAX):
    """Minimal-degree irreducible integer polynomial, detected at DET_DPS, then required to be
    irreducible, to vanish at CONF_DPS, AND to pass the height guard.  Returns the polredbest
    normal form, or None -- and None here means UNDETERMINED, never 'no field'."""
    for d in range(1, degmax + 1):
        try:
            q = P.algdep(z_det, d)
            if q == 0 or P.poldegree(q) < 1 or not P.polisirreducible(q):
                continue
            P.set_real_precision(CONF_DPS)
            if float(P.abs(P.substpol(q, "x", z_conf))) >= 1e-50:
                continue
            if not height_ok(q):
                continue                    # detection unsupported by the precision: reject
            return str(P.polredbest(q))
        except Exception:
            continue
    return None


def field_of(name, coeffs=(1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31)):
    """k_Delta = Q(z_1,...,z_n), via a primitive element sum c_j z_j (primitive for generic c).
    Returns (minpoly_string, n_tetrahedra) or (None, n)."""
    try:
        zd, zc = shapes(name, DET_DPS), shapes(name, CONF_DPS)
    except Exception:
        return None, 0
    n = len(zd)
    lam_d = sum((P(coeffs[j % len(coeffs)]) * zd[j] for j in range(n)), P(0))
    lam_c = sum((P(coeffs[j % len(coeffs)]) * zc[j] for j in range(n)), P(0))
    return minpoly(lam_d, lam_c), n


def first_shape_field(name):
    """What xB022 V4 actually computed: Q(z_1)."""
    try:
        zd, zc = shapes(name, DET_DPS)[0], shapes(name, CONF_DPS)[0]
    except Exception:
        return None
    return minpoly(zd, zc)


def L1():
    print("\nL1       THE FULL SHAPE FIELD k_Delta = Q(z_1,...,z_n), per Neumann-Reid Theorem 2.4")
    print("         (xB022 V4 computed Q(z_1) only -- reading the paper found that defect.)")
    print("         GUARD: detect at %d digits, confirm irreducible AND vanishing at %d."
          % (DET_DPS, CONF_DPS))
    # the object and its sister, with BOTH computations side by side
    for nm in ("m004", "m003"):
        full, n = field_of(nm)
        first = first_shape_field(nm)
        print(f"         {nm}: {n} tetrahedra;  Q(z_1) = {first};  k_Delta = {full};  "
              f"same: {first == full}")
    # PRIMITIVE-ELEMENT STABILITY: a different coefficient vector must give the SAME field
    alt = field_of("m004", coeffs=(3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41))[0]
    base = field_of("m004")[0]
    print(f"         primitive-element stability on m004 (second coefficient vector): "
          f"{alt == base}   ({alt})")
    # POSITIVE CONTROL: a manifold whose field differs must be seen to differ
    ctrl = field_of("m015")[0]
    print(f"         POSITIVE CONTROL m015: k_Delta = {ctrl};  differs from m004: {ctrl != base}")
    R["L1"] = {"m004_full": base, "m003_full": field_of("m003")[0],
               "m004_first": first_shape_field("m004"), "m003_first": first_shape_field("m003"),
               "primitive_stable": bool(alt == base), "control": ctrl}
    ok = base is not None and base == field_of("m003")[0] and alt == base and ctrl != base
    print(f"L1 {'PASS' if ok else 'FAIL'}  the object and its sister share k_Delta, which by")
    print("         Neumann-Reid Theorem 2.4 IS the invariant trace field (they are cusped, so the")
    print("         hypothesis is met).  xB022 V4's fence can now be RETIRED -- for these two.")
    return ok


def L2(maxlen=6):
    print("\nL2       HOW OFTEN DOES Q(z_1) DIFFER FROM k_Delta?  -- sizing xB022 V4's defect")
    words = []
    for n in range(2, maxlen + 1):
        for t in itertools.product("RL", repeat=n):
            w = "".join(t)
            if "R" in w and "L" in w:
                words.append(w)
    tested = differ = same_pair_full = same_pair_first = undet = 0
    examples = []
    for w in words:
        a_full, _ = field_of("b++" + w)
        b_full, _ = field_of("b+-" + w)
        a_first = first_shape_field("b++" + w)
        if a_full is None or b_full is None or a_first is None:
            undet += 1
            continue
        tested += 1
        if a_full != a_first:
            differ += 1
            if len(examples) < 4:
                examples.append((w, a_first, a_full))
        same_pair_full += (a_full == b_full)
        b_first = first_shape_field("b+-" + w)
        same_pair_first += (a_first == b_first)
    print(f"         words tested: {tested};  UNDETERMINED under the height guard: {undet}")
    print("         (UNDETERMINED means the precision could not support a detection -- it is")
    print("          NOT a difference, and it is excluded rather than counted either way.)")
    print(f"         Q(z_1) != k_Delta (xB022 V4 measured the wrong field): {differ} of {tested}")
    for w, f1, fk in examples:
        print(f"           {w}: Q(z_1) = {f1}   but k_Delta = {fk}")
    print(f"         A5 leaves k_Delta unchanged:  {same_pair_full} of {tested}"
          f"   <- the CORRECTED version of xB022 V4")
    print(f"         A5 leaves Q(z_1) unchanged:   {same_pair_first} of {tested}"
          f"   <- what xB022 V4 actually reported")
    concl = ("xB022 V4's CONCLUSION is UNCHANGED" if same_pair_full == tested
             else "xB022 V4's CONCLUSION CHANGES and must be corrected")
    print(f"         {concl}")
    R["L2"] = {"tested": tested, "first_differs_from_full": differ,
               "a5_fixes_full_field": same_pair_full, "a5_fixes_first_field": same_pair_first,
               "conclusion": concl, "undetermined": undet}
    return True


if __name__ == "__main__":
    res = {}
    for f in (L1, L2):
        try:
            res[f.__name__] = bool(f())
        except Exception as e:
            print(f"{f.__name__} EXCEPTION {type(e).__name__}: {e}")
            res[f.__name__] = False
    print("\n" + "=" * 78)
    for k, v in res.items():
        print(f"  {k}: {'PASS' if v else 'FAIL'}")
    print("VERIFIED" if all(res.values()) else "NOT ALL CELLS PASSED")
    with open(os.path.join(os.path.dirname(__file__), "shape_field.json"), "w",
              encoding="utf-8") as fh:
        json.dump({"cells": res, "results": R}, fh, indent=1, default=str)
