"""The class index on m000's non-orientable levels (PREREG e88cac0f). Own implementation over F_p (not B1297's d2lib)."""
import itertools, snappy, numpy as np
from collections import Counter
p = 13

# ---------------- linear algebra over F_p ----------------
def rref(Mx):
    A = [r[:] for r in Mx]; piv = []; r = 0
    ncol = len(A[0]) if A else 0
    for c in range(ncol):
        k = next((i for i in range(r, len(A)) if A[i][c] % p), None)
        if k is None: continue
        A[r], A[k] = A[k], A[r]; iv = pow(A[r][c], -1, p); A[r] = [(v * iv) % p for v in A[r]]
        for i in range(len(A)):
            if i != r and A[i][c] % p:
                f = A[i][c]; A[i] = [(x - f * y) % p for x, y in zip(A[i], A[r])]
        piv.append(c); r += 1
    return A[:r], piv
def rank(Mx): return len(rref(Mx)[0]) if Mx and Mx[0] else 0
def nullspace(Mx, ncol):
    if not Mx: return [[int(i == j) for i in range(ncol)] for j in range(ncol)]
    R, piv = rref(Mx); free = [c for c in range(ncol) if c not in piv]; out = []
    for f in free:
        v = [0] * ncol; v[f] = 1
        for row, pc in zip(R, piv): v[pc] = (-row[f]) % p
        out.append(v)
    return out
def mm(A, B): return [[sum(A[i][k] * B[k][j] for k in range(len(B))) % p for j in range(len(B[0]))] for i in range(len(A))]
def eye(n): return [[int(i == j) for j in range(n)] for i in range(n)]
def minv(A):
    n = len(A); R, piv = rref([A[i] + eye(n)[i] for i in range(n)]); assert piv[:n] == list(range(n))
    return [row[n:] for row in R]
def tr_(A): return [list(r) for r in zip(*A)]
def sc(A, s): return [[(s * x) % p for x in r] for r in A]

# ---------------- words, reps, cohomology of a pair ----------------
def W(s): return [(c.lower(), 1 if c.islower() else -1) for c in s]
def letter(rep, g, e): return rep[g] if e == 1 else minv(rep[g])
def evw(rep, word, n):
    P = eye(n)
    for g, e in word: P = mm(P, letter(rep, g, e))
    return P
def fox(rep, word, gens, n):
    D = {g: [[0] * n for _ in range(n)] for g in gens}; P = eye(n)
    for g, e in word:
        if e == 1: D[g] = [[(x + y) % p for x, y in zip(r, s)] for r, s in zip(D[g], P)]; P = mm(P, rep[g])
        else: P = mm(P, minv(rep[g])); D[g] = [[(x - y) % p for x, y in zip(r, s)] for r, s in zip(D[g], P)]
    return D
def blockrow(blocks):  # list of n x n blocks side by side
    n = len(blocks[0]); return [sum((b[i] for b in blocks), []) for i in range(n)]
def d0(rep, gens, n): return [r for g in gens for r in [[(x - int(i == j)) % p for j, x in enumerate(rep[g][i])] for i in range(n)]]
def d1(rep, gens, rels, n): return [r for R in rels for r in blockrow([fox(rep, R, gens, n)[g] for g in gens])]
def coh(rep, gens, rels, n):
    D0 = d0(rep, gens, n); D1 = d1(rep, gens, rels, n); r0 = rank(D0); r1_ = rank(D1)
    return dict(a0=n - r0, a1=n * len(gens) - r1_ - r0, a2=n * len(rels) - r1_, D0=D0, D1=D1)
def pair_data(rep, gens, rels, cusp_words, cusp_gens, cusp_rels, n):
    """(a0,a1,a2,t0,t1,t2,r1) for X with cusp group generated by cusp_words (words in gens)."""
    c = coh(rep, gens, rels, n); Z = nullspace(c['D1'], n * len(gens))
    crep = {cg: evw(rep, cw, n) for cg, cw in zip(cusp_gens, cusp_words)}
    cc = coh(crep, cusp_gens, cusp_rels, n)
    Res = [r for cw in cusp_words for r in blockrow([fox(rep, cw, gens, n)[g] for g in gens])]   # rows: cusp gens x n
    ResZ = tr_(mm(Res, tr_(Z))) if Z else []                                                       # vectors in C^1(P)
    cd0cols = tr_(cc['D0'])                                                                         # coboundary vectors
    r1 = rank(ResZ + cd0cols) - rank(cd0cols) if ResZ else 0
    return dict(a0=c['a0'], a1=c['a1'], a2=c['a2'], t0=cc['a0'], t1=cc['a1'], t2=cc['a2'], r1=r1)
def dual(rep): return {g: tr_(minv(M)) for g, M in rep.items()}
def twist(rep, w): return {g: (sc(M, p - 1) if w[g] else M) for g, M in rep.items()}

# ---------------- the two non-orientable objects ----------------
def tomat(S): return np.array([[float(S[i, j]) for j in range(4)] for i in range(4)])
def setup(N, m):
    G = N.fundamental_group(); gens = list(G.generators()); rels = [W(r) for r in G.relators()]
    w = {g: 0 if np.linalg.det(tomat(G.O31(g))) > 0 else 1 for g in gens}
    x, y = G.peripheral_curves()[0]
    Ncusp = ([W(m), W(x)], ['m', 'x'], [W('mxMx')])                     # Klein bottle: m x m^-1 x = 1
    # Reidemeister-Schreier for H = ker w, transversal {1, t}
    t = next(g for g in gens if w[g] == 1); rep_ = {0: [], 1: [(t, 1)]}
    def sw(r, g): nr = (r + w[g]) % 2; return rep_[r] + [(g, 1)] + [(c, -e) for c, e in reversed(rep_[nr])]
    SY = {f"s{r}{g}": sw(r, g) for r in (0, 1) for g in gens}
    triv = [s for s, wd in SY.items() if len(wd) == 2 and wd[0][0] == wd[1][0] and wd[0][1] == -wd[1][1]]
    hg = [s for s in SY if s not in triv]
    def rw(word):
        cur = 0; out = []
        for g, e in word:
            if e == 1: out.append((f"s{cur}{g}", 1)); cur = (cur + w[g]) % 2
            else: nw = (cur - w[g]) % 2; out.append((f"s{nw}{g}", -1)); cur = nw
        assert cur == 0
        return [(s, e) for s, e in out if s not in triv]
    inv_ = lambda wd: [(c, -e) for c, e in reversed(wd)]
    hrels = [rw(rep_[r] + R + inv_(rep_[r])) for r in (0, 1) for R in rels]
    Mcusp = ([rw(W(x)), rw(W(m) + W(m))], ['x', 'y'], [W('xyXY')])      # torus <x, m^2>
    return dict(gens=gens, rels=rels, w=w, Ncusp=Ncusp, hg=hg, hrels=hrels, SY=SY, Mcusp=Mcusp)

def characters(S):
    out = []
    for vals in itertools.product(range(1, p), repeat=len(S['gens'])):
        ch = dict(zip(S['gens'], vals))
        if all(np.prod([pow(ch[g], e % (p - 1), p) for g, e in R]) % p == 1 for R in S['rels']):
            out.append(ch)
    return out
def extensions(S, c1, c2):
    gens = S['gens']; n = 2
    def rep_of(cv): return {g: [[c1[g], cv[i]], [0, c2[g]]] for i, g in enumerate(gens)}
    C = []
    for R in S['rels']:
        row = []
        for k in range(len(gens)):
            e_k = [int(i == k) for i in range(len(gens))]; row.append(evw(rep_of(e_k), R, 2)[0][1])
        C.append(row)
    Z = nullspace(C, len(gens)); b = [(c1[g] - c2[g]) % p for g in gens]
    out = []; span = [b] if any(b) else []
    for z in Z:
        if rank(span + [z]) > rank(span): out.append(rep_of(z)); span = span + [z]
    return out

def run(name, N, m):
    S = setup(N, m); gens, rels, w = S['gens'], S['rels'], S['w']; Nc = S['Ncusp']; Mc = S['Mcusp']
    chars = characters(S)
    tests = [{g: [[c[g]]] for g in gens} for c in chars]
    for c1, c2 in itertools.product(chars, repeat=2): tests += extensions(S, c1, c2)
    L1a = L1b_fail = L2 = ctrl = 0; nz_w = Counter(); nz_M = Counter(); n_ = len(tests)
    for V in tests:
        n = len(V[gens[0]]); Vw = twist(V, w); Vd = dual(V); Vdw = twist(Vd, w)
        A = pair_data(V, gens, rels, *Nc, n); Bw = pair_data(Vdw, gens, rels, *Nc, n); Bd = pair_data(Vd, gens, rels, *Nc, n)
        L1a += (A['r1'] + Bw['r1'] == A['t1']); L1b_fail += (A['r1'] + Bd['r1'] != A['t1'])
        Aw = pair_data(Vw, gens, rels, *Nc, n); Bdd = pair_data(twist(dual(Vw), w), gens, rels, *Nc, n)
        Iw = (A['a1'] - A['r1']) - (Bw['a1'] - Bw['r1'])
        Iw2 = (Aw['a1'] - Aw['r1']) - (Bdd['a1'] - Bdd['r1'])
        pv = {s: evw(V, S['SY'][s], n) for s in S['hg']}
        U = pair_data(pv, S['hg'], S['hrels'], *Mc, n); Ud = pair_data(dual(pv), S['hg'], S['hrels'], *Mc, n)
        IM = (U['a1'] - U['r1']) - (Ud['a1'] - Ud['r1'])
        L2 += (IM == Iw + Iw2)
        ctrl += (A['a0'] - A['a1'] + A['a2'] == 0 and A['t0'] - A['t1'] + A['t2'] == 0 and
                 U['a0'] - U['a1'] + U['a2'] == 0 and U['r1'] + Ud['r1'] == U['t1'])
        nz_w[(n, Iw)] += 1; nz_M[(n, IM)] += 1
    print(f"\n{name}: w = {w}; {len(chars)} characters, {n_} test systems ({n_ - len(chars)} non-split extensions)")
    print(f"  L1a twisted  r1(V)+r1(V*w) = t1 : {L1a}/{n_}")
    print(f"  L1b untwisted r1(V)+r1(V*) != t1: {L1b_fail}/{n_}  (witnesses that V* is the wrong partner)")
    print(f"  L2  I(M;p*V) = I_w(V) + I_w(Vw) : {L2}/{n_}")
    print(f"  controls (Euler N, cusp, M; orientable annihilator on M): {ctrl}/{n_}")
    print(f"  L3  (dim, I_w(N;V)) distribution : {dict(sorted(nz_w.items()))}")
    print(f"      (dim, I(M;p*V)) distribution : {dict(sorted(nz_M.items()))}")

M0 = snappy.Manifold('m000')
run('m000 (-> m004)', M0, 'a')
run('N3   (-> M3)  ', M0.covers(3, cover_type='cyclic')[0], 'bAcb')
