#!/usr/bin/env python3
"""
run_frw_observables_from_effective_vacuum.py

R3: Take the FRW histories generated by run_frw_from_effective_vacuum.py and
construct simple observables:

  - Normalized scale factor histories a(t) for:
      * matter-only (Omega_m = 1, Omega_Lambda = 0)
      * effective vacuum (Omega_m = 0.3, Omega_Lambda = 0.7)

  - A normalized redshift grid z from the effective a(t), assuming the final
    time corresponds to "today" (a_today = 1 by construction).

  - A Hubble-like distance curve D_L(z) up to z ~ 3 based on the shape of H(z).
    Units are arbitrary; we care about relative scaling.

Outputs:
  data/processed/frw_effective_observables.npz
      z        : redshift samples
      H        : dimensionless H(z) samples
      Dc       : comoving distance (arbitrary units)
      Dl       : luminosity-like distance (arbitrary units)
      t        : original time grid (effective)
      a_eff    : normalized effective a(t)
      a_matter : normalized matter-only a(t)

  figures/frw_from_effective_vacuum_a_of_t.pdf
  figures/frw_effective_hubble_diagram.png
"""

import numpy as np
from pathlib import Path

import matplotlib.pyplot as plt


DATA_DIR = Path("data/processed")
FIG_DIR = Path("figures")


def main() -> None:
    npz_path = DATA_DIR / "frw_from_effective_vacuum.npz"
    if not npz_path.exists():
        raise FileNotFoundError(
            f"Missing {npz_path}. Run src/run_frw_from_effective_vacuum.py first."
        )

    arr = np.load(npz_path)

    # Time and scale factors
    t_matter = np.asarray(arr["t_matter_only"], dtype=float)
    a_matter = np.asarray(arr["a_matter_only"], dtype=float)

    t_eff = np.asarray(arr["t_effective"], dtype=float)
    a_eff = np.asarray(arr["a_effective"], dtype=float)

    # Normalize so that a_eff(t_final) = 1 and a_matter(t_final) = 1, by construction.
    a_eff_norm = a_eff / float(a_eff[-1])
    a_matter_norm = a_matter / float(a_matter[-1])

    # Redshift from normalized a_eff: z = 1 / a_eff_norm - 1
    z_eff = 1.0 / a_eff_norm - 1.0

    # Sort by redshift (ascending) and build an approximate H(z)
    order = np.argsort(z_eff)
    z_sorted = z_eff[order]
    a_sorted = a_eff_norm[order]
    t_sorted = t_eff[order]

    # Numerical Hubble parameter: H = (1/a) da/dt
    # Use gradient for robustness.
    da_dt = np.gradient(a_sorted, t_sorted)
    H_sorted = da_dt / a_sorted

    # Keep a reasonable redshift range for plotting (e.g., 0 <= z <= 3)
    z_max = 3.0
    mask = (z_sorted >= 0.0) & (z_sorted <= z_max)

    z_use = z_sorted[mask]
    H_use = H_sorted[mask]

    if z_use.size < 3:
        raise RuntimeError(
            "Not enough samples in the chosen redshift range to build observables."
        )

    # Simple comoving distance integral: Dc(z) ~ ∫ dz' / H(z')
    Dc = np.zeros_like(z_use)
    invH = 1.0 / H_use
    dz = np.diff(z_use)
    # trapezoidal integration in z
    Dc[1:] = np.cumsum(0.5 * (invH[1:] + invH[:-1]) * dz)

    # Luminosity-like distance (up to an overall scale): D_L = (1 + z) Dc
    Dl = (1.0 + z_use) * Dc

    # Save observables
    out_path = DATA_DIR / "frw_effective_observables.npz"
    np.savez(
        out_path,
        z=z_use,
        H=H_use,
        Dc=Dc,
        Dl=Dl,
        t=t_eff,
        a_eff=a_eff_norm,
        a_matter=a_matter_norm,
    )

    print(f"Wrote observables to {out_path}")

    # Ensure figure directory exists
    FIG_DIR.mkdir(parents=True, exist_ok=True)

    # 1) Scale-factor histories
    fig1_path = FIG_DIR / "frw_from_effective_vacuum_a_of_t.pdf"
    plt.figure()
    plt.plot(t_matter, a_matter_norm, label="Matter-only FRW")
    plt.plot(t_eff, a_eff_norm, label="Effective vacuum FRW")
    plt.xlabel("Time (arb. units)")
    plt.ylabel("Scale factor a(t), normalized")
    plt.legend()
    plt.tight_layout()
    plt.savefig(fig1_path, bbox_inches="tight")
    plt.close()
    print(f"Wrote {fig1_path}")

    # 2) Hubble-like distance curve
    fig2_path = FIG_DIR / "frw_effective_hubble_diagram.png"
    plt.figure()
    plt.plot(z_use, Dl, marker=".")
    plt.xlabel("Redshift z")
    plt.ylabel("Distance (arb. units)")
    plt.title("Effective vacuum Hubble-like curve")
    plt.tight_layout()
    plt.savefig(fig2_path, dpi=200, bbox_inches="tight")
    plt.close()
    print(f"Wrote {fig2_path}")


if __name__ == "__main__":
    main()