"""B739 Stage B recompute -- TOMB-L255 (K-L: `rank = SL(n) tower depth` -- DEAD).

BANKED KILL (speculations/TOMBSTONES.md:L255, review-session spectral-rank cluster):
  claim_killed : "spectral rank equals SL(n) tower depth -- the rank climbs with n up the tower"
  kill fact    : "The tower eigenvalues are all powers of phi^2 (multiplicative free-rank 1) at
                  every n (cf. the B85 constraint note); the spectral rank does not climb with n."
  citation hop : frontier/B85_tower_lynchpin/FINDINGS.md L61-64, constraint (i):
                  "Every Sym^d(M) eigenvalue is +-phi^(d-2j), so the multiplicative group the
                  tower eigenvalues generate has free rank 1 (<phi>, times the sign <-1>) at
                  every n."  -- "(Verified in-session; not previously recorded here.)"
                 i.e. NO committed computation exists (fact_basis = cited-unverified). This
                 script IS that computation, re-derived from the arcs' declared conventions.
  (Supersedes an earlier in-place draft at this path that swept the principal Sym^(n-1)(M)
   ladder only; this version assembles the arc's ACTUAL declared tower object -- the K003
   two-sequence rho_n, dim n^2-1 -- and cross-checks it against the B80 proved catalog at
   n=4. Same verdict; the definition-match gap is closed.)

DECLARED CONVENTIONS (E1):
  * Seed matrix (B80 FINDINGS: `L_k = tr([[m,1],[1,0]]^k)`, metallic family; golden case
    m = 1):  M = [[1,1],[1,0]],  det M = -1,  eigenvalues phi = (1+sqrt5)/2 and -1/phi.
  * THE TOWER (K003 "The Dickson tower", B103/B117 two-sequence -- the arcs' declared object):
        rho_n  =  (+)_d  Sym^d(M)^{mu_d},   mu_d = [2<=d<=n] + [0<=d<=n-3],
    the (n^2-1)-dimensional linearization of the SL(n) figure-eight trace map at the trivial
    fixed point.  "Tower depth" at SL(n) is n (undeclared in the tombstone -- CHOSEN HERE, E1;
    any strictly-increasing depth function gives the same verdict, since the computed rank is
    CONSTANT in n).
  * Sym^d(A) convention (undeclared in the arcs -- CHOSEN HERE, E1): the induced action on
    degree-d binary forms in basis {x^(d-j) y^j, j=0..d} via the substitution
    x -> a11*x + a21*y, y -> a12*x + a22*y.  Sym^1(A) = A under this choice; the SPECTRUM of
    Sym^d(A) is invariant under the alternative (transpose/inverse) conventions, so the
    discriminating fact does not depend on this choice.
  * "Spectral rank" (the killed claim's object): the free rank (rank modulo torsion) of the
    multiplicative subgroup of Q(sqrt5)^* generated by the tower eigenvalues.  As an
    object-robustness cross-check we ALSO compute the additive Z-rank of the Q-span of the
    eigenvalues in the basis {1, sqrt5}  (the K-K session's additive/gap-labeling reading);
    the kill must hold under BOTH readings or the fact is not discriminating (E19 both
    directions: a recompute that only rescues one reading would be a proxy).
  * Depth swept explicitly: n = 2..12 (Sym^d blocks d = 0..12).  The banked "every n" is
    covered by the explicit sweep plus the mechanism, itself verified exactly in-sweep:
    Sym^d(A.B) = Sym^d(A).Sym^d(B) as an exact polynomial identity in 8 symbolic matrix
    entries (d = 1..6) and Sym^d(diag(lam,mu)) = diag(lam^(d-j) mu^j), so every rho_n
    eigenvalue for ANY n lies in the fixed group <-1, phi> (free rank 1); a subgroup of a
    free-rank-1 group can never have free rank > 1, at any depth.

Everything below is exact symbolic arithmetic (sympy over Q(sqrt5)); no floats, no
wall-clock, no randomness, no network.  Gate 5: pure mathematics, no SM quantities.
"""
from __future__ import annotations

from math import gcd

import sympy as sp

x, y, t = sp.symbols("x y t")
SQRT5 = sp.sqrt(5)
PHI = (1 + SQRT5) / 2

D_MAX = 12          # top Sym block needed for the n-sweep
N_MAX = 12          # tower depth sweep n = 2..N_MAX


def sym_power(A: sp.Matrix, d: int) -> sp.Matrix:
    """Matrix of Sym^d(A) on binary forms, basis x^(d-j) y^j (convention declared above)."""
    xs = A[0, 0] * x + A[1, 0] * y
    ys = A[0, 1] * x + A[1, 1] * y
    S = sp.zeros(d + 1, d + 1)
    for j in range(d + 1):
        img = sp.expand((xs ** (d - j)) * (ys ** j))
        poly = sp.Poly(img, x, y)
        for i in range(d + 1):
            S[i, j] = poly.coeff_monomial(x ** (d - i) * y ** i)
    return S


def _norm(v):
    """Exact normal form in Q(sqrt5): rationalize denominators, expand."""
    return sp.expand(sp.radsimp(sp.together(v)))


def coords_in_1_sqrt5(v):
    """Exact coordinates (a, b) with v = a + b*sqrt5, a,b rational."""
    e = _norm(v)
    b = e.coeff(SQRT5)
    a = sp.simplify(e - b * SQRT5)
    assert a.is_rational and b.is_rational, (v, a, b)
    return sp.Rational(a), sp.Rational(b)


def match_unit(v, bound):
    """Return (sign, e) with v == sign * PHI**e exactly (|e| <= bound), or None."""
    va, vb = coords_in_1_sqrt5(v)
    for e in range(-bound, bound + 1):
        pa, pb = coords_in_1_sqrt5(PHI ** e)
        if (va, vb) == (pa, pb):
            return (1, e)
        if (va, vb) == (-pa, -pb):
            return (-1, e)
    return None


def exact_spectrum(S: sp.Matrix, bound: int):
    """DERIVE the spectrum of an integer matrix S exactly: factor char(S) over Q(sqrt5),
    then identify every root as sign*phi^e (exact coordinate match). Returns the multiset
    [(sign, e), ...]; asserts full splitting and full identification."""
    cp = sp.Poly(S.charpoly(t).as_expr(), t, extension=SQRT5)
    rts = sp.roots(cp)
    assert sum(rts.values()) == S.shape[0], "char poly did not split over Q(sqrt5)"
    out = []
    for r, mult in rts.items():
        mk = match_unit(r, bound)
        assert mk is not None, f"eigenvalue {r} is not of the form +-phi^e"
        out.extend([mk] * mult)
    return sorted(out, key=lambda se: (se[1], se[0]))


def mu(n: int, d: int) -> int:
    """K003/B103/B117 two-sequence multiplicity of Sym^d(M) inside rho_n."""
    return int(2 <= d <= n) + int(0 <= d <= n - 3)


def mult_free_rank(exponents):
    """Free rank of the subgroup of {+-1} x <phi> generated by {sign_i * phi^(e_i)}:
    0 if every e_i = 0, else 1 (the exponent lattice is g*Z, g = gcd)."""
    g = 0
    for e in exponents:
        g = gcd(g, abs(e))
    return (0 if g == 0 else 1), g


def additive_rank(marks):
    """Z-rank of the span of {sign*phi^e} inside Q(sqrt5) = Q*1 + Q*sqrt5 (rank <= 2)."""
    rows = [list(coords_in_1_sqrt5(s * PHI ** e)) for (s, e) in set(marks)]
    return sp.Matrix(rows).rank()


def main():
    print("B739 Stage B recompute -- TOMB-L255 (K-L: rank = SL(n) tower depth)")
    print("seed convention (B80): M = [[m,1],[1,0]] at m=1 (golden)")
    print("tower convention (K003/B103/B117): rho_n = (+)_d Sym^d(M)^{mu_d}, "
          "mu_d = [2<=d<=n] + [0<=d<=n-3]\n")

    # ---- 0. Seed facts, exact -------------------------------------------------
    M = sp.Matrix([[1, 1], [1, 0]])
    lam_, mu_ = PHI, -1 / PHI
    cp_seed = M.charpoly(t).as_expr()
    assert sp.expand(cp_seed - (t ** 2 - t - 1)) == 0
    assert _norm(cp_seed.subs(t, lam_)) == 0 and _norm(cp_seed.subs(t, mu_)) == 0
    assert M.det() == -1 and _norm(lam_ * mu_ + 1) == 0
    print("seed: char(M) = t^2 - t - 1;  eigenvalues phi, -1/phi;  det M = -1  [verified exact]")

    # ---- 1. The mechanism, exact: functoriality + diagonal form ---------------
    a11, a12, a21, a22, b11, b12, b21, b22 = sp.symbols("a11 a12 a21 a22 b11 b12 b21 b22")
    A = sp.Matrix([[a11, a12], [a21, a22]])
    B = sp.Matrix([[b11, b12], [b21, b22]])
    for d in range(1, 7):
        Dev = sp.expand(sym_power(A * B, d) - sym_power(A, d) * sym_power(B, d))
        assert Dev == sp.zeros(d + 1, d + 1), f"functoriality fails at d={d}"
    print("Sym^d(A.B) = Sym^d(A).Sym^d(B): exact 8-symbol polynomial identity, d = 1..6  [verified]")
    lam_s, mu_s = sp.symbols("lam mu")
    Dg = sym_power(sp.diag(lam_s, mu_s), 6)
    assert Dg == sp.diag(*[lam_s ** (6 - j) * mu_s ** j for j in range(7)])
    print("Sym^d(diag(lam,mu)) = diag(lam^(d-j) mu^j): symbolic, d = 6 spot-verified  [mechanism]")
    print("=> every Sym^d(M) eigenvalue lies in the FIXED group <-1, phi> for EVERY d "
          "(free rank 1 ambient)\n")

    # ---- 2. Per-block spectra, DERIVED from the matrices ----------------------
    spectra = {}
    for d in range(0, D_MAX + 1):
        S = sym_power(M, d)                          # integer (d+1)x(d+1) matrix -- the object
        spectra[d] = exact_spectrum(S, bound=2 * d + 2)
        expected = sorted((((-1) ** j, d - 2 * j) for j in range(d + 1)),
                          key=lambda se: (se[1], se[0]))
        assert spectra[d] == expected, f"B85 formula fails at d={d}"
    print(f"Sym^d(M) spectra DERIVED exactly for d = 0..{D_MAX}: each equals "
          "{(-1)^j phi^(d-2j), j=0..d}")
    print("  (this IS B85 FINDINGS L61-64 constraint (i), now an artifact, not an assertion)\n")

    # ---- 2b. Block-diagonal charpoly = product of block charpolys (spot exact) -
    for n_chk in (3, 4):
        blocks = []
        for d in range(0, D_MAX + 1):
            blocks.extend([sym_power(M, d)] * mu(n_chk, d))
        R = sp.Matrix(sp.BlockDiagMatrix(*blocks))
        cp_direct = sp.expand(R.charpoly(t).as_expr())
        cp_prod = sp.expand(sp.prod(
            [b.charpoly(t).as_expr() for b in blocks]))
        assert sp.expand(cp_direct - cp_prod) == 0, n_chk
        assert R.shape[0] == n_chk ** 2 - 1
    print("char(rho_n) = prod of block charpolys: verified DIRECTLY on the assembled "
          "8x8 (n=3) and 15x15 (n=4) integer matrices\n")

    # ---- 3. THE TOWER SWEEP: rho_n, n = 2..N_MAX ------------------------------
    print("The two-sequence tower rho_n: exact eigenvalue group ranks vs depth n")
    print("%-4s %-8s %-26s %-12s %-9s %-11s %-7s" % (
        "n", "dim", "exponent range (phi^e)", "mult-rank", "add-rank", "claim(K-L)", "climb?"))
    results = []
    prev_rank = None
    for n in range(2, N_MAX + 1):
        marks = []
        dim = 0
        for d in range(0, D_MAX + 1):
            m_d = mu(n, d)
            if m_d:
                marks.extend(spectra[d] * m_d)
                dim += m_d * (d + 1)
        assert dim == n * n - 1, (n, dim)
        exps = [e for (_, e) in marks]
        r_mult, g = mult_free_rank(exps)
        r_add = additive_rank(marks)
        climbed = (prev_rank is not None and r_mult > prev_rank)
        results.append((n, dim, r_mult, g, r_add, climbed))
        prev_rank = r_mult
        print("%-4d %-8d %-26s %-12s %-9d %-11s %-7s" % (
            n, dim, f"[{min(exps)} .. {max(exps)}], gcd {g}",
            r_mult, r_add, f"rank={n}: NO", "no"))

    assert all(r == 1 for (_, _, r, _, _, _) in results), "mult free rank not constant 1"
    assert all(r == 2 for (_, _, _, _, r, _) in results), "additive rank not constant 2"
    assert not any(c for (*_, c) in results), "rank climbed somewhere"
    assert all(r != n for (n, _, r, _, _, _) in results), "mult rank equals depth somewhere"
    assert all(r != n for (n, _, _, _, r, _) in results if n != 2), "add rank equals depth beyond n=2"
    print("\nmultiplicative free rank: constant 1 for n = 2..%d (never equals n; never climbs)" % N_MAX)
    print("additive Z-rank (K-K reading): constant 2 (equals n only accidentally at n=2, then flat)")

    # ---- 4. Cross-check vs the PROVED B80 SL(4) catalog at m=1 ----------------
    # B80 FINDINGS: char(J(m)) = char(M^-1) char(M) char(M^2) char(M^3) char(M^4)
    #                            char(-M^2) (t-1)^2 (t+1)   [proved, exact symbolic]
    catalog = []
    for Mk in (M ** -1, M, M ** 2, M ** 3, M ** 4, -(M ** 2)):
        catalog.extend(exact_spectrum(Mk, bound=10))
    catalog.extend([(1, 0), (1, 0), (-1, 0)])        # (t-1)^2 (t+1)
    rho4 = []
    for d in range(0, D_MAX + 1):
        rho4.extend(spectra[d] * mu(4, d))
    assert sorted(catalog) == sorted(rho4), "B80 catalog != two-sequence rho_4"
    r80, g80 = mult_free_rank([e for (_, e) in catalog])
    print(f"\nB80 proved SL(4) catalog at m=1: {len(catalog)} eigenvalues == rho_4 multiset "
          f"[exact match];")
    print(f"  exponents {sorted(e for (_, e) in catalog)}; free rank {r80} (gcd {g80})")
    assert (r80, len(catalog)) == (1, 15)

    # ---- 5. The tombstone's literal wording: "all powers of phi^2" ------------
    s3 = spectra[3]
    assert (1, 3) in s3                              # phi^3: an ODD power of phi
    for d in range(1, 7):
        for (s, e) in exact_spectrum(sym_power(M ** 2, d), bound=4 * d + 2):
            assert s == 1 and e % 2 == 0, (d, s, e)
    print("\nliteral-wording audit: on the SEED tower the eigenvalue phi^3 (d=3) is an ODD power")
    print("  of phi -- 'all powers of phi^2' is literally true only on the geodesic/even tower")
    print("  Sym^d(M^2) (d = 1..6 verified: every eigenvalue a pure power of phi^2, no sign).")
    print("  The parenthetical '(multiplicative free-rank 1)' -- the DISCRIMINATING content --")
    print("  is exact under BOTH conventions: <-1,phi> and <phi^2> both have free rank 1.")

    # ---- Verdict --------------------------------------------------------------
    print("\nVERDICT-FACT: on the arcs' declared tower rho_n (dim n^2-1, two-sequence mu_d),")
    print("the spectral rank = multiplicative free rank of the eigenvalue group = 1 at every")
    print("depth n = 2..%d while depth climbs 2..%d; the additive reading gives constant 2." % (N_MAX, N_MAX))
    print("Under NO reading does the rank equal or climb with n; the mechanism (functoriality +")
    print("diagonal form, exact) pins every eigenvalue at every n inside <-1, phi>, free rank 1.")
    print("The banked kill of K-L is RECONFIRMED by direct recomputation.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
