#!/usr/bin/env python3
"""B1534 Part D, route C (run after run_terms.py): Lemma S's middle term read directly.  For each member, on the cover cut out
by H4, the first subgroup of order min(4, |C|) of its contributing group C in silver_lib.subgroups' order, and at c_int (or
the one class) and at c_{g1}: I(W1 (x) C[A]) and I(Lambda^2 W1 (x) C[A]) with C[A] the permutation module of A = H4^ (Gamma
acting by translation through psi(g) = (the turns of chi(g)) over chi in H4), never split into characters.  Compared with
the sum of route E's terms over H4 in terms.json.  Writes route_c.json and route_c_log.txt."""
import json
import sys
import time
import warnings
from datetime import datetime, timezone
from fractions import Fraction
from pathlib import Path

warnings.filterwarnings("ignore")
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import silver_lib as SL  # noqa: E402

E = SL.E
GEN1 = Fraction(3, 7)
LOG = []


def say(s):
    print(s, flush=True)
    LOG.append(s)


def turns(st, h):
    w, k = h
    ch = SL.char(st, w, k)
    out = {}
    for g in st["G"].gens:
        out[g] = next(Fraction(e, 24) for e in range(24) if E.root_of_unity(Fraction(e, 24)) == ch[g])
    return out


def perm_module(G, mod, H, tv):
    """mod (x) C[A]: the points of A are the turn vectors generated by psi(g) = (tv[chi][g])_chi, acted on by translation"""
    Hl = sorted(H)
    step = {g: tuple(tv[h][g] for h in Hl) for g in G.gens}
    pts, frontier = {tuple(Fraction(0) for _ in Hl)}, None
    frontier = list(pts)
    while frontier:
        new = []
        for p in frontier:
            for g in G.gens:
                q = tuple((a + b) % 1 for a, b in zip(p, step[g]))
                if q not in pts:
                    pts.add(q)
                    new.append(q)
        frontier = new
    pts = sorted(pts)
    idx = {p: i for i, p in enumerate(pts)}
    m = len(pts)
    mats = {}
    for g in G.gens:
        A = mod.M[g]
        n = len(A)
        M = E.zeros(n * m, n * m)
        for p in pts:
            q = tuple((a + b) % 1 for a, b in zip(p, step[g]))
            k, l = idx[q], idx[p]
            for i in range(n):
                for j in range(n):
                    if not A[i][j].is_zero():
                        M[i * m + k][j * m + l] = A[i][j]
        mats[g] = M
    return E.Module(G.gens, mats), m


def main():
    t0 = time.time()
    T = json.loads((HERE / "terms.json").read_text())
    out = {"started": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"), "rows": [], "agree": True}
    say(f"B1534 route C, {out['started']}")
    for state in ("-LLRR", "+LLRR"):
        st = SL.setup(state)
        recs = {(tuple(m["u"]), m["kappa"]): m for m in T["states"][state]["members"]}
        for m in SL.members(st):
            mrec = recs[(tuple(str(x) for x in m["u"]), str(m["kappa"]))]
            C = SL.contributing(st, m)
            subs = SL.subgroups(C)
            target = min(4, len(C))
            H4 = next(H for H in subs if len(H) == target)
            tv = {h: turns(st, h) for h in H4}
            for cname in (("the class",) if m["h1"] == 1 else ("c_int", "c_g1")):
                c = (m["classes"]["the class"] if cname == "the class" else m["c_int"] if cname == "c_int" else
                     SL.lin(m["c_b"], m["c_int"], E.ONE, E.K.of(GEN1)))
                W1 = E.extension(m["V"], c, m["L"])
                MW, order = perm_module(st["G"], W1, H4, tv)
                ML, _ = perm_module(st["G"], W1.wedge2(), H4, tv)
                IW, IL = E.class_index(st["G"], MW)["I"], E.class_index(st["G"], ML)["I"]
                summed = [sum(mrec["terms"][cname][SL.key(h)][0] for h in H4),
                          sum(mrec["terms"][cname][SL.key(h)][1] for h in H4)]
                agree = [IW, IL] == summed
                out["agree"] &= agree
                row = {"state": state, "u": mrec["u"], "kappa": mrec["kappa"], "class": cname,
                       "H": sorted(SL.key(h) for h in H4), "|A|": order, "route C": [IW, IL], "sum of route E's terms": summed,
                       "agree": agree}
                out["rows"].append(row)
                say(f"{state} u {mrec['u']} kappa {mrec['kappa']} {cname}: |A| = {order}, route C ({IW}, {IL}), sum {summed}, "
                    f"agree {agree} ({time.time() - t0:.0f} s)")
    out["seconds"] = round(time.time() - t0)
    (HERE / "route_c.json").write_text(json.dumps(out, indent=1, default=str))
    (HERE / "route_c_log.txt").write_text("\n".join(LOG) + "\n")
    say(f"route C: all agree {out['agree']} ({out['seconds']} s)")


if __name__ == "__main__":
    main()
