"""Saturated peripheral lattice  Lambda = {(x,y) in Q^2 : x*Mr + y*Ln in Z^{3N}}  (contains Z^2)."""
from fractions import Fraction as F
from math import gcd
from idx import rows
K = 60
def sat_basis(name, mfd=None):
    M,n,r,E,Mr,Ln = rows(name, mfd); assert r==1
    A=[Mr[0],Ln[0]]
    def integral(x,y): return all(((x*A[0][j]+y*A[1][j])).denominator==1 for j in range(len(A[0])))
    gens=[(K,0),(0,K)]+[(a,b) for a in range(K) for b in range(K) if integral(F(a,K),F(b,K))]
    # HNF of the 2-column integer lattice generated by gens
    rowsg=[list(g) for g in gens]
    # column-style reduction to a 2x2 upper triangular basis
    def lat_basis(rws):
        rws=[r[:] for r in rws if any(r)]
        # gcd of first coordinates
        b=[]
        # reduce first column
        while True:
            nz=[r for r in rws if r[0]!=0]
            if not nz: break
            g=0
            for r in nz: g=gcd(g,abs(r[0]))
            piv=None
            # build a vector with first coord = g by extended gcd combination
            cur=None
            for r in nz:
                if cur is None: cur=r[:]
                else:
                    x,y=cur[0],r[0]
                    # extended gcd
                    old_r,rr=x,y; old_s,s=1,0; old_t,t=0,1
                    while rr: q=old_r//rr; old_r,rr=rr,old_r-q*rr; old_s,s=s,old_s-q*s; old_t,t=t,old_t-q*t
                    cur=[old_s*cur[i]+old_t*r[i] for i in range(2)]
            piv=cur; b.append(piv)
            rws=[[r[0]-(r[0]//piv[0])*piv[0], r[1]-(r[0]//piv[0])*piv[1]] for r in rws]
            rws=[r for r in rws if r[0]==0 and r[1]!=0]
            break
        g2=0
        for r in rws: g2=gcd(g2,abs(r[1]))
        if g2: b.append([0,g2])
        return b
    bb=lat_basis(rowsg)
    b1=(F(bb[0][0],K),F(bb[0][1],K)); b2=(F(bb[1][0],K),F(bb[1][1],K))
    cov=abs(b1[0]*b2[1]-b1[1]*b2[0])
    return b1,b2,cov
if __name__=="__main__":
    for nm in ["m004","m003","m015","m006","m007","m016","m017","m022","m023","m009"]:
        b1,b2,cov=sat_basis(nm)
        print(f"{nm}: saturated basis g1={b1} g2={b2}   covolume={cov}  (1 => Lambda = H_1(torus;Z))")
