#!/usr/bin/env python3
"""
Appendix B -- verification of the global-form proposition (paper Prop. "z6").

Self-contained: needs only sympy.  Imports NOTHING project-internal, so it travels with
the paper.  Exact arithmetic throughout -- the kernel is found by solving root-of-unity
conditions symbolically, not by sampling angles numerically.

THE STATEMENT.  Embed su(3) (+) su(2) (+) u(1) in su(5) in the standard way, with the
abelian generator diag(2,2,2,-3,-3)/6.  On groups,

    SU(3) x SU(2) x U(1)  ->  S(U(3) x U(2))  subset  SU(5),
    (A, B, e^{i theta})   |->  diag(e^{2 i theta} A,  e^{-3 i theta} B)

has kernel exactly Z/6.

WHY IT MATTERS, and it is the only place in the paper where this kind of statement is
available: the ALGEBRA su(3)+su(2)+u(1) does not determine its GROUP.  All four quotients
by Gamma in {1, Z2, Z3, Z6} share that algebra, and no statement about the algebra tells
them apart.  Arriving through su(5) does tell them apart, and picks Z6.  Every other
result in the paper is a statement about algebras; this one is not.

Verifies, in order:
  1. the abelian generator is traceless, so it lies in su(5);
  2. an element of the product maps to the identity iff A = a I3, B = b I2 with
     a^3 = b^2 = 1 and e^{2 i th} a = e^{-3 i th} b = 1;
  3. the solutions are exactly six, at theta in (pi/3) Z;
  4. they form a CYCLIC group of order 6 -- generated by (omega I3, -I2, e^{i pi/3});
  5. the four candidate quotients are distinguished, i.e. 6 is not 1, 2 or 3.

Run:  python3 check_global_form.py        (exit 0 = all PASS)
"""

import sys

import sympy as sp

FAILURES = []


def check(label, got, want):
    ok = got == want
    print(f"  [{'PASS' if ok else 'FAIL'}] {label}")
    if not ok:
        print(f"          expected: {want}")
        print(f"          got:      {got}")
        FAILURES.append(label)
    return ok


def main():
    print("=" * 70)
    print("Appendix B -- the global form determined by the A_4 stratum")
    print("=" * 70)

    print("\n1. the abelian generator lies in su(5)")
    Y = sp.diag(2, 2, 2, -3, -3) / 6
    check("trace diag(2,2,2,-3,-3)/6 = 0", sp.simplify(Y.trace()), 0)
    check("the two blocks have weights 2 and -3", (2 * 3, -3 * 2), (6, -6))

    print("\n2/3. the kernel, solved exactly over the roots of unity")
    # (A,B,e^{i th}) -> diag(e^{2 i th} A, e^{-3 i th} B) = I  forces A = a I3, B = b I2
    # with a^3 = 1 (det A = 1), b^2 = 1 (det B = 1), and e^{2 i th} a = e^{-3 i th} b = 1.
    kernel = []
    for k in range(12):                      # theta = 2 pi k / 12 covers pi/3 multiples
        th = 2 * sp.pi * sp.Rational(k, 12)
        a = sp.simplify(sp.exp(-2 * sp.I * th))
        b = sp.simplify(sp.exp(3 * sp.I * th))
        if sp.simplify(a**3 - 1) == 0 and sp.simplify(b**2 - 1) == 0:
            kernel.append((sp.nsimplify(a), sp.nsimplify(b), sp.nsimplify(
                sp.simplify(sp.exp(sp.I * th)))))
    check("the kernel has exactly six elements", len(kernel), 6)

    thetas = []
    for k in range(12):
        th = 2 * sp.pi * sp.Rational(k, 12)
        a = sp.simplify(sp.exp(-2 * sp.I * th))
        b = sp.simplify(sp.exp(3 * sp.I * th))
        if sp.simplify(a**3 - 1) == 0 and sp.simplify(b**2 - 1) == 0:
            thetas.append(sp.Rational(k, 12) * 2)          # in units of pi
    check("the solutions sit at theta in (pi/3)Z",
          thetas, [sp.Rational(n, 3) for n in range(6)])

    print("\n4. the kernel is CYCLIC of order six")
    omega = sp.exp(2 * sp.I * sp.pi / 3)
    gen = (sp.nsimplify(omega), sp.Integer(-1), sp.nsimplify(sp.exp(sp.I * sp.pi / 3)))
    powers = set()
    for n in range(1, 13):
        a = sp.nsimplify(sp.simplify(gen[0] ** n))
        b = sp.nsimplify(sp.simplify(gen[1] ** n))
        t = sp.nsimplify(sp.simplify(gen[2] ** n))
        powers.add((sp.srepr(a), sp.srepr(b), sp.srepr(t)))
        if n == 6:
            check("the generator has order dividing 6",
                  (sp.simplify(a - 1), sp.simplify(b - 1), sp.simplify(t - 1)),
                  (0, 0, 0))
    check("the generator's distinct powers number six", len(powers), 6)

    print("\n5. the four candidate global forms are distinguished")
    check("|Z6| is not |1|, |Z2| or |Z3|",
          [6 == n for n in (1, 2, 3)], [False, False, False])
    print("          (the algebra su(3)+su(2)+u(1) admits all four quotients;")
    print("           arriving through su(5) selects the one of order six.)")

    print("-" * 70)
    if FAILURES:
        print(f"FAIL: {len(FAILURES)} check(s) did not reproduce.")
        for f in FAILURES:
            print(f"   - {f}")
        return 1
    print("PASS: the kernel is exactly Z/6, cyclic.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
