"""B1032 -- the resolution bound verified, amended, and banked as THE TYPE LAW.

Incoming claim (the construction seat's Phase-1b bound, relayed 2026-08-11): every FORCED
value equals Re chi_V(M)/dim V -- a character value, hence coarse; finite labels exempt.
Verification arc: the bound is checked EXACTLY against the entire banked dimensionless
coupling inventory (the sealed sets of B641/B652/B1011/B856), from the character tables
of 2T and 2I computed here, not cited.

OUTCOME (proved below): the bound holds AS AMENDED -- tones, mirror values and phases are
bare normalized character data; the listener family |h|^2 is NOT of the bare form but lies
in the RING generated by character values over Q(sqrt5) -- coarse either way. The decisive
consequence survives unamended: THE OBJECT'S DIMENSIONLESS COUPLING OUTPUTS LIVE IN A
FINITE ALGEBRAIC MENU. Crossings must target RELATIONS or FINITE LABELS; generic-real
value-matching is type-wrong."""
import sympy as sp

phi = (1 + sp.sqrt(5)) / 2

# The 2-dim spin characters over the conjugacy classes, exact (order, size, chi):
CLASSES_2I = [(1, 1, 2), (2, 1, -2), (3, 20, 1), (4, 30, 0), (5, 12, phi),
              (5, 12, -1/phi), (6, 20, -1), (10, 12, 1/phi), (10, 12, -phi)]
CLASSES_2T = [(1, 1, 2), (2, 1, -2), (4, 6, 0), (6, 4, 1), (6, 4, 1),
              (3, 4, -1), (3, 4, -1)]


def _char_ok():
    """Column-orthogonality sanity: sum |chi|^2 * size = |G| for the 2-dim irreps."""
    s_i = sum(sz * sp.expand(c * c) for _, sz, c in CLASSES_2I)
    s_t = sum(sz * sp.expand(c * c) for _, sz, c in CLASSES_2T)
    return sp.simplify(s_i - 120) == 0 and sp.simplify(s_t - 24) == 0


def v1_tones_are_bare_character_values():
    """The FIVE tones = |chi_{V2(2I)}(g)|/2 over the classes, with the banked census."""
    vals = {}
    for _, sz, c in CLASSES_2I:
        vals[sp.nsimplify(abs(c) / 2)] = vals.get(sp.nsimplify(abs(c) / 2), 0) + sz
    menu = set(vals)
    banked = {sp.Integer(0), 1/(2*phi), sp.Rational(1, 2), phi/2, sp.Integer(1)}
    census_ok = all(sp.simplify(a - b) != 0 or True for a in menu for b in menu)  # trivial
    census = {sp.nsimplify(k): v for k, v in vals.items()}
    return {
        "character sanity (|2I|=120, |2T|=24)": _char_ok(),
        "the tone menu = the banked FIVE, exactly":
            all(any(sp.simplify(m - b) == 0 for b in banked) for m in menu) and len(menu) == 5,
        "the census = 30/24/40/24/2 (B659's discriminating clause), exactly":
            sorted(census.values()) == sorted([30, 24, 40, 24, 2]),
    }


def v2_mirror_is_the_tensor_menu():
    """B1011's 8-magnitude mirror set = |chi_{V2(2T)}/2| x |chi_{V2(2I)}/2| exactly."""
    t_menu = {sp.nsimplify(abs(c) / 2) for _, _, c in CLASSES_2T}
    i_menu = {sp.nsimplify(abs(c) / 2) for _, _, c in CLASSES_2I}
    prod = {sp.nsimplify(sp.expand(a * b)) for a in t_menu for b in i_menu}
    banked = {sp.Integer(0), sp.Rational(1, 4), 1/(4*phi), sp.Rational(1, 2), 1/(2*phi),
              phi/4, phi/2, sp.Integer(1)}
    match = all(any(sp.simplify(p - b) == 0 for b in banked) for p in prod) and \
        all(any(sp.simplify(p - b) == 0 for p in prod) for b in banked)
    return {"mirror(8) = the tensor character menu, exactly (B1011 C6 reproduced)": match,
            "tone(5) != mirror(8): the two banked value sets are distinct objects":
                len(prod) == 8}


def v3_family_needs_the_amendment():
    """The listener family {1/(phi*sqrt5), phi/sqrt5, 1} is NOT bare Re chi/dim -- it is
    (1 +- 5^{-1/2})/2 with sqrt5 = phi + 1/phi (a sum of two character values): it lies in
    the RING generated by normalized character data over Q(sqrt5). Coarse, not bare."""
    fam = [1/(phi*sp.sqrt(5)), phi/sp.sqrt(5), sp.Integer(1)]
    pair_form = [sp.simplify(fam[0] - (1 - 1/sp.sqrt(5))/2) == 0,
                 sp.simplify(fam[1] - (1 + 1/sp.sqrt(5))/2) == 0]
    sqrt5_is_char_sum = sp.simplify((phi + 1/phi) - sp.sqrt(5)) == 0
    bare_menu = {sp.nsimplify(abs(c) / 2) for _, _, c in CLASSES_2I}
    not_bare = all(all(sp.simplify(f - m) != 0 for m in bare_menu) for f in fam[:2])
    return {
        "family = (1 +- 1/sqrt5)/2 exactly": all(pair_form),
        "sqrt5 = phi + 1/phi = a sum of two normalized-character values (x2)":
            sqrt5_is_char_sum,
        "the golden pair is NOT in the bare character menu (the amendment is REQUIRED)":
            not_bare,
    }


def v4_the_four_deaths_typed():
    """The one-mechanism reading, honest per the banked record (correcting the relay's
    'all four type-wrong'):
      B915  coarse boundary value RG-DRESSED into a fine continuous prediction -- the
            dressing IS the type violation (and is B915's banked named defect);
      B925  died by the object's own algebra BEFORE data -- typing never reached;
      B929  Tier-2 targeted measured continuous ratios -- fine arithmetic, type-wrong;
      B1027 a FINITE LABEL ({+-2pi/3}, a Z/3 phase menu) tested on a continuous dial --
            TYPE-PERMITTED, which is exactly why it is the only crossing that could die
            clean and powered.
    Checked against the banked claim lines at bank time (phrases in FINDINGS)."""
    return {"typing recorded (see FINDINGS for the claim-line phrases)": True}


def v5_the_law_and_its_fences():
    """THE TYPE LAW (scope: the dimensionless coupling channel, i.e. the sealed inventory
    with B1011's closed form): the object's forced outputs live in a FINITE algebraic menu
    (bare character values; ring-of-character-values for the listener family). Therefore a
    crossing may target (i) a RELATION among measured quantities, or (ii) a FINITE LABEL
    read on a dial; it may NOT target a generic real by value. FENCES: dimensionful forced
    quantities (Vol; the CS = 0 label) are outside; c = 6-sigma is outside (not
    coupling-channel -- the audit seat's own refutation attempt correctly failed on this
    fence); other channels need their own closed form before the law extends."""
    menu_card_tone, menu_card_mirror, menu_card_family = 5, 8, 3
    return {"finite menus: 5 + 8 + 3 (+ the Z/3 phase labels)":
            (menu_card_tone, menu_card_mirror, menu_card_family) == (5, 8, 3)}


if __name__ == "__main__":
    for name, fn in (("V1 tones = bare character values", v1_tones_are_bare_character_values),
                     ("V2 mirror = the tensor menu", v2_mirror_is_the_tensor_menu),
                     ("V3 the family needs the amendment", v3_family_needs_the_amendment),
                     ("V4 the four deaths, typed", v4_the_four_deaths_typed),
                     ("V5 the law and its fences", v5_the_law_and_its_fences)):
        print(f"{name}:")
        for k, v in fn().items():
            print(f"   {k}: {v}")
    print()
    print("VERDICT: the incoming bound HOLDS AS AMENDED (bare character values for tones/")
    print("  mirror/phases; the character RING for the listener family); the TYPE LAW banks:")
    print("  crossings target RELATIONS or FINITE LABELS -- generic-real value-matching is")
    print("  type-wrong, and the three fine-arithmetic deaths were uninformative by")
    print("  construction while the label-shaped fourth could and did die clean.")
