#!/usr/bin/env python3
# B674 W2 -- THE MOLIEN CELL (cc seat). Governing document: PREREG_W2.md
# (sealed, sha b4c9a6bb). Runs ONLY: the VACUITY GATE, step (i), step (ii).
# Step (iii) is LOCKED (pending the cc2 input-verification gate); no W33
# target stream is loaded anywhere in this cell; no coefficient of the
# Molien series is expanded or compared.
#
# THE CANDIDATE (per the sealed prereg + the pinned formulation):
#   V   = the graded module generated by the vector-valued weight-1/5
#         system (F1,F2) over the modular-form ring of Gamma(5), graded
#         by weight step [PRIMARY]:  V_k = C^2_{(F1,F2)} (x) M_k(Gamma(5)),
#         dim 2(5k+1)   [M_k(Gamma(5)) = Sym^{5k} span(f1,f2), banked, arc T3]
#   W   = sigma(A1), the canonical order-10 elliptic lift of the monodromy
#         A1 = [[2,1],[1,1]] = T S T^-1 S^-1 through the weight-1/5 slash
#         action (the banked golden-rotation law: tr = phi exactly),
#         lifted canonically to Sym(V);
#         W|V_k = sigma(A1) (x) Sym^{5k} sigma(A1).
#   CONTROL = the plain weight tower (+)_k M_k(Gamma(5)),
#         W|M_k = Sym^{5k} sigma(A1).
#
# All decisive arithmetic exact: Q(zeta20) as Fraction-vectors modulo
# Phi_20(x) = x^8 - x^6 + x^4 - x^2 + 1, plus an independent sympy exact
# construction of the same commutator (trace/det gates) and a numeric pin
# against the arc's stored 40-digit canonical sigma(A1) (an independent
# 70-dps modular-q-series solve, cellES).
import json
from fractions import Fraction as Fr
from math import comb
from pathlib import Path

HERE = Path(__file__).resolve().parent
ARC = HERE.parent  # frontier/B674_generation_leg

LOG = []
def log(s=""):
    for ln in str(s).split("\n"):
        LOG.append(ln)
        print(ln[:196], flush=True)

FAILURES = []
def gate(name, ok):
    log("  [%s] %s" % ("PASS" if ok else "FAIL", name))
    if not ok:
        FAILURES.append(name)
    return ok

# ------------------------------------------------------------------ Q(zeta20)
# basis 1, z, ..., z^7 with z = zeta20 = exp(i pi/10); z^8 = z^6 - z^4 + z^2 - 1
D = 8
RED = [Fr(0)]*6 + [Fr(0)]*0  # placeholder
def _mkred():
    # RED[l] = vector of z^l for l = 0..14 (enough for degree-14 convolutions)
    tab = []
    for l in range(15):
        if l < D:
            v = [Fr(0)]*D; v[l] = Fr(1); tab.append(v)
        else:
            # z^l = z^{l-8} * (z^6 - z^4 + z^2 - 1)
            base = tab[l-8]
            v = [Fr(0)]*D
            for j, c in enumerate(base):
                if c == 0: continue
                for (e, s) in ((6, 1), (4, -1), (2, 1), (0, -1)):
                    w = tab[j+e] if j+e < len(tab) else None
                    if w is None:
                        raise RuntimeError("reduction order")
                    for t in range(D):
                        v[t] += s*c*w[t]
            tab.append(v)
    return tab
REDT = _mkred()

def cz(vec):  # canonical tuple
    return tuple(vec)
ZERO = cz([Fr(0)]*D)
ONE = cz([Fr(1)] + [Fr(0)]*(D-1))

def cadd(a, b): return tuple(x+y for x, y in zip(a, b))
def csub(a, b): return tuple(x-y for x, y in zip(a, b))
def cneg(a):    return tuple(-x for x in a)
def cscal(r, a): return tuple(r*x for x in a)
def cmul(a, b):
    conv = [Fr(0)]*(2*D-1)
    for i, x in enumerate(a):
        if x == 0: continue
        for j, y in enumerate(b):
            if y == 0: continue
            conv[i+j] += x*y
    out = [Fr(0)]*D
    for l, c in enumerate(conv):
        if c == 0: continue
        w = REDT[l]
        for t in range(D):
            out[t] += c*w[t]
    return cz(out)
def cpow(a, n):
    r = ONE
    for _ in range(n):
        r = cmul(r, a)
    return r

# powers of zeta20: Z(n) = z^n reduced
ZP = [ONE]
zgen = cz([Fr(0), Fr(1)] + [Fr(0)]*(D-2))
for _ in range(40):
    ZP.append(cmul(ZP[-1], zgen))
def Z(n): return ZP[n % 20]

def cnum(a):
    import cmath
    return sum(complex(x)*cmath.exp(1j*cmath.pi*j/10) for j, x in enumerate(a))

def cconj(a):
    # complex conjugation: z^j -> z^{-j} = z^{20-j}
    out = ZERO
    for j, x in enumerate(a):
        if x == 0: continue
        out = cadd(out, cscal(x, Z((20 - j) % 20)))
    return out

# field constants
HALF = Fr(1, 2)
PHI = cadd(Z(2), Z(18))                    # 2cos(pi/5) = phi
SQRT5 = csub(cscal(Fr(2), PHI), ONE)       # sqrt5 = 2 phi - 1
I_ = Z(5)
ZETA5 = Z(4)
ZETA10 = Z(2)                              # exp(i pi/5)
def sin_pi_k5(k):  # sin(k pi/5) = (z^{2k} - z^{-2k}) * (-z^5) / 2
    return cscal(HALF, cmul(csub(Z(2*k), Z(-2*k)), cneg(I_)))

# ------------------------------------------------------------------ matrices
def mident(n):
    return [[ONE if i == j else ZERO for j in range(n)] for i in range(n)]
def mmul(A, B):
    n, m, p = len(A), len(B), len(B[0])
    out = [[ZERO]*p for _ in range(n)]
    for i in range(n):
        Ai = A[i]
        for k in range(m):
            a = Ai[k]
            if a == ZERO: continue
            Bk = B[k]
            Oi = out[i]
            for j in range(p):
                if Bk[j] == ZERO: continue
                Oi[j] = cadd(Oi[j], cmul(a, Bk[j]))
    return out
def mtrace(A):
    t = ZERO
    for i in range(len(A)):
        t = cadd(t, A[i][i])
    return t
def meq(A, B):
    return all(A[i][j] == B[i][j] for i in range(len(A)) for j in range(len(A[0])))
def mscal(r, A):
    return [[cscal(r, x) for x in row] for row in A]
def mcel(e, A):  # scale a matrix by a field element
    return [[cmul(e, x) for x in row] for row in A]
def det2(A):
    return csub(cmul(A[0][0], A[1][1]), cmul(A[0][1], A[1][0]))
def kron(A, B):
    n, m = len(A), len(B)
    out = [[ZERO]*(n*m) for _ in range(n*m)]
    for i in range(n):
        for j in range(n):
            a = A[i][j]
            if a == ZERO: continue
            for k in range(m):
                for l in range(m):
                    if B[k][l] == ZERO: continue
                    out[i*m+k][j*m+l] = cmul(a, B[k][l])
    return out
def sym_power(g, m):
    # Sym^m of a 2x2 (basis e_i = x^{m-i} y^i), same construction as arc rho()
    (a, b), (c, d) = g[0], g[1]
    ap = [cpow(a, r) for r in range(m+1)]; bp = [cpow(b, r) for r in range(m+1)]
    cp = [cpow(c, r) for r in range(m+1)]; dp = [cpow(d, r) for r in range(m+1)]
    cols = []
    for i in range(m+1):
        p = [ZERO]*(m+1)
        e1 = [cscal(Fr(comb(m-i, r)), cmul(ap[m-i-r], cp[r])) for r in range(m-i+1)]
        e2 = [cscal(Fr(comb(i, s)), cmul(bp[i-s], dp[s])) for s in range(i+1)]
        for r, v1 in enumerate(e1):
            if v1 == ZERO: continue
            for s, v2 in enumerate(e2):
                if v2 == ZERO: continue
                p[r+s] = cadd(p[r+s], cmul(v1, v2))
        cols.append(p)
    return [[cols[i][j] for i in range(m+1)] for j in range(m+1)]

log("== W2 MOLIEN CELL (cc seat) -- prereg b4c9a6bb; vacuity gate + step (i) + step (ii) only ==")
log("")
log("== PHASE 0: reconstruct sigma(A1) exactly (the banked convention, arc cellES) ==")
# sigma(T) = diag(1, zeta5)  [arc gate, asserted at 1e-45 there]
sigT = [[ONE, ZERO], [ZERO, ZETA5]]
sigTi = [[ONE, ZERO], [ZERO, Z(-4)]]
# sigma(S): the golden S-matrix (2/sqrt5)[[sin 2pi/5, sin pi/5],[sin pi/5, -sin 2pi/5]].
# NOTE (declared choice): the arc's honest slash sigma(S) equals this matrix times a
# global phase (zeta20^-1); the canonical lift sigma(A1) is the COMMUTATOR
# [sigma(T), sigma(S)], where every global phase cancels -- so the phase-free real
# golden S-matrix is the valid representative for the lift. Verified below by a
# 30+ digit numeric pin against the arc's stored canonical sigma(A1).
c25 = cscal(Fr(2, 5), SQRT5)               # 2/sqrt5 = (2/5) sqrt5
s36, s72 = sin_pi_k5(1), sin_pi_k5(2)
sigS = mcel(c25, [[s72, s36], [s36, cneg(s72)]])
ok = gate("sigma(S)^2 = I (involution => sigma(S)^-1 = sigma(S))", meq(mmul(sigS, sigS), mident(2)))
gate("sigma(S) symmetric", sigS[0][1] == sigS[1][0])
gate("det sigma(S) = -1", det2(sigS) == cneg(ONE))
gate("sigma(T) sigma(T)^-1 = I", meq(mmul(sigT, sigTi), mident(2)))
# the canonical commutator lift
sigA = mmul(mmul(sigT, sigS), mmul(sigTi, sigS))
gate("det sigma(A1) = 1", det2(sigA) == ONE)
gate("tr sigma(A1) = phi EXACT (the golden-rotation law; base-grade self-check)",
     mtrace(sigA) == PHI)
# order: sigma^5 = -I, order exactly 10
p5 = sigA
for _ in range(4):
    p5 = mmul(p5, sigA)
gate("sigma(A1)^5 = -I", meq(p5, mscal(Fr(-1), mident(2))))
pw = sigA
order = None
for n in range(1, 21):
    if meq(pw, mident(2)):
        order = n; break
    pw = mmul(pw, sigA)
gate("order of sigma(A1) = 10 exactly", order == 10)
# char poly x^2 - phi x + 1; roots zeta10^{+-1}
gate("char poly = x^2 - phi*x + 1  (tr = phi, det = 1)", mtrace(sigA) == PHI and det2(sigA) == ONE)
gate("zeta10^{+1} is a root of x^2 - phi*x + 1",
     cadd(csub(cmul(ZETA10, ZETA10), cmul(PHI, ZETA10)), ONE) == ZERO)
gate("zeta10^{-1} is a root of x^2 - phi*x + 1",
     cadd(csub(cmul(Z(-2), Z(-2)), cmul(PHI, Z(-2))), ONE) == ZERO)
gate("phi^2 = phi + 1 ; sqrt5^2 = 5",
     cmul(PHI, PHI) == cadd(PHI, ONE) and cmul(SQRT5, SQRT5) == cscal(Fr(5), ONE))
# Galois: the conjugate seed. sqrt5 -> -sqrt5 sends phi -> 1-phi; the conjugate
# char poly is x^2 - (1-phi)x + 1 and zeta10^{+-3} are its roots.
ONEmPHI = csub(ONE, PHI)
gate("zeta10^{+3} is a root of the conjugate poly x^2 - (1-phi)*x + 1",
     cadd(csub(cmul(Z(6), Z(6)), cmul(ONEmPHI, Z(6))), ONE) == ZERO)
gate("zeta10^{-3} is a root of the conjugate poly x^2 - (1-phi)*x + 1",
     cadd(csub(cmul(Z(-6), Z(-6)), cmul(ONEmPHI, Z(-6))), ONE) == ZERO)
gate("2cos(pi/5) = phi and 2cos(3pi/5) = 1-phi (exact)",
     cadd(Z(2), Z(-2)) == PHI and cadd(Z(6), Z(-6)) == ONEmPHI)

# numeric pin vs the arc's stored canonical sigma(A1) (independent 70-dps route)
arc_traces = json.loads((ARC / "cellES" / "cellES_traces.json").read_text())
stored = arc_traces["sigmaA1_canonical_numeric"]
def parse_mp(s):
    s = s.strip().lstrip("(").rstrip(")").replace(" ", "")
    return complex(s.replace("j", "j"))
devmax = 0.0
for i in range(2):
    for j in range(2):
        dv = abs(cnum(sigA[i][j]) - parse_mp(stored[i][j]))
        devmax = max(devmax, dv)
gate("numeric pin: exact sigma(A1) vs arc's stored canonical matrix, max dev < 1e-12 (got %.2e)" % devmax,
     devmax < 1e-12)
gate("arc's banked recognition reproduced: order 10, angle pi/5, trace 0+1*phi",
     arc_traces["sigmaA1_order"] == 10 and arc_traces["sigmaA1_eigen_angle_over_pi"] == "1/5"
     and arc_traces["sigmaA1_trace_in_Zphi"] == {"a": 0, "b": 1})

# independent sympy exact construction (second engine): trace and det of the
# commutator built from sympy's own sqrt/sin/exp objects.
import sympy as sp
zeta5_sp = sp.exp(2*sp.pi*sp.I/5)
T_sp = sp.Matrix([[1, 0], [0, zeta5_sp]])
S_sp = (2/sp.sqrt(5))*sp.Matrix([[sp.sin(2*sp.pi/5), sp.sin(sp.pi/5)],
                                 [sp.sin(sp.pi/5), -sp.sin(2*sp.pi/5)]])
A_sp = sp.simplify(T_sp * S_sp * T_sp.inv() * S_sp.inv())
tr_sp = sp.simplify(sp.expand_complex(sp.trace(A_sp) - sp.GoldenRatio))
det_sp = sp.simplify(sp.expand_complex(A_sp.det() - 1))
gate("sympy second engine: tr(commutator) - phi == 0 exactly", tr_sp == 0)
gate("sympy second engine: det(commutator) - 1 == 0 exactly", det_sp == 0)
def to_sympy(a):
    return sum(sp.Rational(x.numerator, x.denominator) * sp.exp(sp.I*sp.pi*j/10)
               for j, x in enumerate(a) if x != 0)
ok_entry = True
for i in range(2):
    for j in range(2):
        diff = sp.simplify(sp.expand_complex(A_sp[i, j] - to_sympy(sigA[i][j])))
        if diff != 0:
            # exactness fallback: 60-digit evaluation of the SAME exact expressions
            if abs(complex(sp.N(A_sp[i, j] - to_sympy(sigA[i][j]), 60))) > 1e-50:
                ok_entry = False
gate("sympy second engine: entrywise EXACT agreement with the Q(zeta20) engine", ok_entry)

if FAILURES:
    log("PHASE 0 FAILURES: %s -- STOP" % FAILURES)
    (HERE / "run_log.txt").write_text("\n".join(LOG) + "\n")
    raise SystemExit(1)

log("")
log("  sigma(A1) EXACT over Q(zeta20)  [zeta = exp(i pi/10)]:")
for i in range(2):
    log("    row %d: %s" % (i, [ [str(x) for x in sigA[i][j]] for j in range(2) ]))
log("  eigenvalues: zeta10^{+1}, zeta10^{-1}  (zeta10 = exp(i pi/5)); trace = phi; order 10")

# ------------------------------------------------------------------ distributions
# Eigenvalue class bookkeeping in Z/10 over zeta10 = exp(i pi/5).
# Sym^m sigma(A1) (diagonalizable, eigenvalues zeta10^{+-1}) has eigenvalues
# zeta10^{m-2j}, j = 0..m.  W|V_k = sigma(A1) (x) Sym^{5k} sigma(A1) has
# eigenvalues zeta10^{eps + 5k - 2j}, eps in {+1,-1}, j = 0..5k.
KMAX = 40
def dist_sym(m, seed=1):
    d = {t: 0 for t in range(10)}
    for j in range(m+1):
        d[(seed*(m - 2*j)) % 10] += 1
    return d
def dist_Vk(k, seed=1):
    d = {t: 0 for t in range(10)}
    for eps in (1, -1):
        for j in range(5*k + 1):
            d[(seed*(eps + 5*k - 2*j)) % 10] += 1
    return d
MK = [dist_Vk(k) for k in range(KMAX+1)]            # PRIMARY V_k
MKC = [dist_sym(5*k) for k in range(KMAX+1)]        # CONTROL M_k tower
MKp = [dist_Vk(k, seed=3) for k in range(KMAX+1)]   # Galois-conjugate seed +-3
MKCp = [dist_sym(5*k, seed=3) for k in range(KMAX+1)]

def dist_trace(d):
    t = ZERO
    for r, m in d.items():
        if m:
            t = cadd(t, cscal(Fr(m), Z(2*r)))
    return t

log("")
log("== VACUITY GATE (runs first, per the sealed prereg) ==")
log("  W scalar on V_k  <=>  the eigenvalue distribution of W|V_k has ONE occupied class.")
log("  Matrix-level witness (k <= 3): W_k - W_k[0,0]*I != 0; distribution-level for all k <= %d." % KMAX)
vac_rows = []
all_noncentral = True
matwitness = {}
for k in range(0, 4):
    Wk = kron(sigA, sym_power(sigA, 5*k)) if k > 0 else kron(sigA, mident(1))
    lam = Wk[0][0]
    scal = all(Wk[i][j] == (lam if i == j else ZERO) for i in range(len(Wk)) for j in range(len(Wk)))
    matwitness[k] = not scal
for k in range(KMAX+1):
    occ = sorted(t for t, m in MK[k].items() if m > 0)
    scalar = (len(occ) == 1)
    if scalar:
        all_noncentral = False
    vac_rows.append((k, 2*(5*k+1), len(occ), occ, "SCALAR" if scalar else "NON-CENTRAL"))
gate("matrix-level: W|V_k non-scalar for k = 0,1,2,3", all(matwitness.values()))
gate("distribution-level: W|V_k NON-CENTRAL on EVERY graded piece k = 0..%d" % KMAX, all_noncentral)
verdict_vac = "PROCEED (W non-central on every graded piece; no DESIGN-KILL)" if all_noncentral \
    else "DESIGN-KILL (W central)"
log("  VACUITY VERDICT: %s" % verdict_vac)

vg = ["# W2 MOLIEN CELL -- VACUITY GATE (per-piece verdict table)",
      "# prereg b4c9a6bb; runs FIRST. W scalar on every piece => DESIGN-KILL abort.",
      "# W|V_k = sigma(A1) (x) Sym^{5k} sigma(A1) on V_k = C^2_{(F1,F2)} (x) M_k(Gamma(5)).",
      "# Matrix-level witness (exact, Q(zeta20)): W_k != W_k[0,0]*I for k = 0,1,2,3: " +
      ("CONFIRMED" if all(matwitness.values()) else "FAILED"),
      "",
      "| k | dim V_k | #occupied eigenvalue classes | occupied classes t (eigenvalue zeta10^t) | verdict |",
      "|---|---------|------------------------------|------------------------------------------|---------|"]
for (k, dim, nocc, occ, v) in vac_rows:
    vg.append("| %d | %d | %d | %s | %s |" % (k, dim, nocc, occ, v))
vg.append("")
vg.append("VERDICT: " + verdict_vac)
(HERE / "vacuity_gate.md").write_text("\n".join(vg) + "\n")

if not all_noncentral:
    log("DESIGN-KILL -- aborting before step (i) per the sealed prereg.")
    (HERE / "run_log.txt").write_text("\n".join(LOG) + "\n")
    raise SystemExit(0)

log("")
log("== STEP (i): the eigenvalue distribution of W on the graded pieces of V ==")
log("   exact over Q(sqrt5) (classes and multiplicities in zeta10-exponents), k = 0..%d" % KMAX)
log("   (grades k <= 40 bound q^40 in Sym(V): a part of grade k >= 41 cannot touch q^{<=40};")
log("    the grade-0 piece contributes a constant factor, see step (ii))")

# verification 1: dimensions and symmetry m_k(t) = m_k(-t)
ok_dim = all(sum(MK[k].values()) == 2*(5*k+1) for k in range(KMAX+1))
ok_sym = all(MK[k][t] == MK[k][(-t) % 10] for k in range(KMAX+1) for t in range(10))
gate("dim V_k = 2(5k+1) reproduced by the distribution, all k", ok_dim)
gate("m_k(t) = m_k(-t) (Galois-real: coefficients land in Q(sqrt5)), all k", ok_sym)

# verification 2: the trace law tr(W|V_k) = phi * (-1)^k, exact, all k
ok_tr = True
for k in range(KMAX+1):
    want = cscal(Fr((-1)**k), PHI)
    if dist_trace(MK[k]) != want:
        ok_tr = False; break
gate("trace law tr(W|V_k) = (-1)^k * phi EXACT for all k = 0..%d" % KMAX, ok_tr)
# control trace law tr(W|M_k) = (-1)^k (the arc's banked alternating law)
ok_trc = all(dist_trace(MKC[k]) == cscal(Fr((-1)**k), ONE) for k in range(KMAX+1))
gate("CONTROL trace law tr(W|M_k) = (-1)^k EXACT for all k (arc's banked law reproduced)", ok_trc)
# Chebyshev cross-check in Z[phi]: p_m(phi): p_0 = 1, p_1 = phi, p_{m+1} = phi p_m - p_{m-1};
# tr Sym^m sigma = p_m; check p_{5k} = (-1)^k for k <= KMAX  (pure Z[phi], no zeta20)
pa, pb = (Fr(1), Fr(0)), (Fr(0), Fr(1))   # (a + b phi)
ok_cheb = True
plist = [pa, pb]
for m in range(2, 5*KMAX+1):
    a1, b1 = plist[-1]; a0, b0 = plist[-2]
    # phi*(a1 + b1 phi) = a1 phi + b1 (phi+1) = b1 + (a1+b1) phi
    plist.append((b1 - a0, a1 + b1 - b0))
for k in range(KMAX+1):
    if plist[5*k] != (Fr((-1)**k), Fr(0)):
        ok_cheb = False; break
gate("Chebyshev in Z[phi]: tr Sym^{5k} sigma = p_{5k}(phi) = (-1)^k for all k <= %d" % KMAX, ok_cheb)

# verification 3: matrix-level class recovery by exact DFT over Z/10
# multiplicity(t) = (1/10) sum_p tr(A^p) zeta10^{-pt}  (A of order 10)
def dft_classes(A):
    n = len(A)
    traces = [cscal(Fr(n), ONE)]
    P = A
    for p in range(1, 10):
        traces.append(mtrace(P))
        P = mmul(P, A)
    out = {}
    for t in range(10):
        acc = ZERO
        for p in range(10):
            acc = cadd(acc, cmul(traces[p], Z((-2*p*t) % 20)))
        acc = cscal(Fr(1, 10), acc)
        # must be a rational integer
        if acc == ZERO:
            out[t] = 0
        else:
            assert all(x == 0 for x in acc[1:]) and acc[0].denominator == 1, "DFT non-integer"
            out[t] = int(acc[0])
    return out
ok_sydft = True
for m in (5, 10, 15, 20):
    got = dft_classes(sym_power(sigA, m))
    if got != dist_sym(m):
        ok_sydft = False
        log("    Sym^%d DFT mismatch: %s vs %s" % (m, got, dist_sym(m)))
gate("matrix-level DFT class recovery == enumeration for Sym^m, m in {5,10,15,20}", ok_sydft)
ok_tvdft = True
for k in (0, 1, 2, 3):
    Wk = kron(sigA, sym_power(sigA, 5*k)) if k > 0 else kron(sigA, mident(1))
    got = dft_classes(Wk)
    if got != MK[k]:
        ok_tvdft = False
        log("    V_%d DFT mismatch: %s vs %s" % (k, got, MK[k]))
gate("matrix-level DFT class recovery == enumeration for W|V_k, k in {0,1,2,3}", ok_tvdft)

# verification 4: the closed-form law
def law_mk(k, t):
    if (t - (k+1)) % 2 != 0:
        return 0
    if t % 10 in ((5*k+1) % 10, (5*k-1) % 10):
        return 2*k + 1
    return 2*k
ok_law = all(MK[k][t] == law_mk(k, t) for k in range(KMAX+1) for t in range(10))
gate("closed-form law: m_k(t) = 2k+1 at t = 5k+-1 (mod 10), 2k at other t = k+1 (mod 2), 0 else",
     ok_law)

def trace_str(k):
    return "phi" if k % 2 == 0 else "-phi"
def charpoly_str(k):
    if k % 2 == 0:
        return "(x^2 - phi*x + 1)^%d * (x^2 - (1-phi)*x + 1)^%d * (x + 1)^%d" % (2*k+1, 2*k, 2*k)
    return "(x^2 + phi*x + 1)^%d * (x^2 + (1-phi)*x + 1)^%d * (x - 1)^%d" % (2*k+1, 2*k, 2*k)
# verify the charpoly factorization degrees + root classes against the distribution
def charpoly_check(k):
    d = MK[k]
    if k % 2 == 0:
        return (d[1] == 2*k+1 and d[9] == 2*k+1 and d[3] == 2*k and d[7] == 2*k and d[5] == 2*k
                and d[0] == d[2] == d[4] == d[6] == d[8] == 0)
    return (d[4] == 2*k+1 and d[6] == 2*k+1 and d[2] == 2*k and d[8] == 2*k and d[0] == 2*k
            and d[1] == d[3] == d[5] == d[7] == d[9] == 0)
gate("char-poly factorization over Q(sqrt5) consistent with the distribution, all k",
     all(charpoly_check(k) for k in range(KMAX+1)))
# pair classes: {1,9} <-> x^2-phi*x+1 ; {3,7} <-> x^2-(1-phi)*x+1 ; {4,6} <-> x^2+phi*x+1
# {2,8} <-> x^2+(1-phi)*x+1 [2cos(2pi/5) = phi-1] ; {5} <-> x+1 ; {0} <-> x-1
gate("pair identities: 2cos(2pi/5) = phi-1, 2cos(4pi/5) = -phi (exact)",
     cadd(Z(4), Z(-4)) == csub(PHI, ONE) and cadd(Z(8), Z(-8)) == cneg(PHI))

log("")
log("  THE DISTRIBUTION (PRIMARY V; eigenvalues zeta10^t, zeta10 = exp(i pi/5)):")
log("   k even: t in {1,9}: 2k+1 ; t in {3,5,7}: 2k ; t even: 0     trace = +phi")
log("   k odd : t in {4,6}: 2k+1 ; t in {0,2,8}: 2k ; t odd: 0      trace = -phi")
log("  CONTROL (M_k tower): 5k+-... : t = 5k (mod 10): k+1 ; other t = k (mod 2): k ; trace = (-1)^k")

# ------------------------------------------------------------------ artifacts (i)
gate_primary = {}
for k in range(KMAX+1):
    gate_primary[str(k)] = {
        "dim": 2*(5*k+1),
        "mult_by_zeta10_exponent": {str(t): MK[k][t] for t in range(10) if MK[k][t] > 0},
        "trace_Zphi": trace_str(k),
        "charpoly_Qsqrt5": charpoly_str(k),
        "distinct_classes": sum(1 for t in range(10) if MK[k][t] > 0),
    }
control = {}
for k in range(KMAX+1):
    control[str(k)] = {
        "dim": 5*k+1,
        "mult_by_zeta10_exponent": {str(t): MKC[k][t] for t in range(10) if MKC[k][t] > 0},
        "trace_Zphi": "1" if k % 2 == 0 else "-1",
    }
artifact = {
    "artifact": "eigen_distribution.json (THE STEP-(i) GATE ARTIFACT; cc2's independent derivation must match GATE_PRIMARY exactly)",
    "prereg": "PREREG_W2.md sealed sha b4c9a6bb; cc cell step (i)",
    "conventions": {
        "A1": "[[2,1],[1,1]] = T S T^-1 S^-1 (the banked monodromy word, arc cellES)",
        "sigma_T": "diag(1, zeta5), zeta5 = exp(2 pi i/5) (banked gate: f1 integer q-powers, f2 = q^{1/5}*integer stream)",
        "sigma_S": "(2/sqrt5)[[sin(2pi/5), sin(pi/5)],[sin(pi/5), -sin(2pi/5)]] (real golden S-matrix; the honest slash sigma(S) differs by a global phase which CANCELS in the commutator)",
        "sigma_A1": "sigma_T sigma_S sigma_T^-1 sigma_S^-1; order 10; det 1; trace = phi exactly; eigenvalues zeta10^{+-1}; numerically pinned to the arc's stored canonical matrix (< 1e-12)",
        "V": "PRIMARY: V_k = C^2_{(F1,F2)} (x) M_k(Gamma(5)), weight-step grade k, dim 2(5k+1); W|V_k = sigma(A1) (x) Sym^{5k} sigma(A1) [M_k = Sym^{5k} span(f1,f2), banked arc T3]",
        "eigenvalue_labels": "zeta10^t, t in Z/10, zeta10 = exp(i pi/5) = zeta20^2; classes t,-t pair into Q(sqrt5)-irreducible quadratics",
        "galois": "PRIMARY = the trace-phi embedding (Yang-Lee side); conjugate seed = eigenvalues zeta10^{+-3} (trace 1-phi = -1/phi, the Fibonacci-unitary side); on classes: t -> 3t (mod 10)",
        "grade_bound": "k = 0..40 bounds q^40 in Sym(V); the grade-0 piece contributes a constant factor",
    },
    "closed_form_law": "m_k(t) = 2k+1 if t = 5k+-1 (mod 10); m_k(t) = 2k if t = k+1 (mod 2) otherwise; m_k(t) = 0 if t = k (mod 2). trace(W|V_k) = (-1)^k phi.",
    "GATE_PRIMARY": gate_primary,
    "CONTROL_weight_tower": control,
    "verifications": [
        "matrix-level exact DFT class recovery at Sym^m m in {5,10,15,20} and W|V_k k in {0,1,2,3}",
        "trace law (-1)^k phi all k <= 40 (cyclotomic exact) + Chebyshev p_{5k}(phi) = (-1)^k in Z[phi]",
        "dim and t <-> -t symmetry all k <= 40",
        "numeric pin of sigma(A1) to the arc's stored 40-digit canonical matrix",
        "independent sympy engine: commutator trace/det exact",
    ],
}
(HERE / "eigen_distribution.json").write_text(json.dumps(artifact, indent=1))

ti = ["# STEP (i) -- the eigenvalue distribution of W = sigma(A1) on the graded pieces of V",
      "# (human-readable companion of eigen_distribution.json, the gate artifact)",
      "",
      "W|V_k = sigma(A1) (x) Sym^{5k} sigma(A1) on V_k = C^2_{(F1,F2)} (x) M_k(Gamma(5)), dim 2(5k+1).",
      "Eigenvalues written zeta10^t, zeta10 = exp(i pi/5) (a primitive 10th root; zeta10^t = zeta20^{2t}).",
      "",
      "LAW (verified k = 0..40, matrix-exact at k <= 3): m_k(t) = 2k+1 at t = 5k+-1 (mod 10);",
      "2k at the other three classes of parity k+1 (mod 2); 0 at parity k (mod 2).",
      "tr(W|V_k) = (-1)^k * phi exactly.  Char poly over Q(sqrt5):",
      "  k even: (x^2 - phi*x + 1)^{2k+1} (x^2 - (1-phi)*x + 1)^{2k} (x + 1)^{2k}",
      "  k odd : (x^2 + phi*x + 1)^{2k+1} (x^2 + (1-phi)*x + 1)^{2k} (x - 1)^{2k}",
      "",
      "| k | dim | t=0 | t=1 | t=2 | t=3 | t=4 | t=5 | t=6 | t=7 | t=8 | t=9 | trace |",
      "|---|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-------|"]
for k in range(KMAX+1):
    ti.append("| %d | %d | %s | %s |" % (k, 2*(5*k+1),
              " | ".join(str(MK[k][t]) for t in range(10)), trace_str(k)))
ti += ["",
       "CONTROL (the plain weight tower M_k(Gamma(5)), W = Sym^{5k} sigma(A1)):",
       "S_k(t) = k+1 at t = 5k (mod 10), k at the other classes of parity k (mod 2), else 0;",
       "tr = (-1)^k (the arc's banked alternating law, reproduced).",
       ""]
(HERE / "step_i_table.md").write_text("\n".join(ti) + "\n")
log("  artifacts written: eigen_distribution.json (GATE), step_i_table.md, vacuity_gate.md")

# ------------------------------------------------------------------ STEP (ii)
log("")
log("== STEP (ii): THE SUPPORT PRE-TEST (first falsifier) ==")
log("  Molien series (per Galois conjugate): M(q) = prod_{k>=0} prod_t (1 - zeta10^t q^k)^{-m_k(t)}")
log("  Formed SYMBOLICALLY from the step-(i) data; NO coefficient is expanded or compared.")

s_results = []
def s_gate(name, ok, detail=""):
    s_results.append((name, ok, detail))
    return gate(name + (("  [" + detail + "]") if detail else ""), ok)

# (ii-a) well-definedness: the grade-0 factor must be a finite CONSTANT:
# requires m_0(0) = 0 (no eigenvalue 1 at grade 0). Then
# grade-0 factor = 1/det(I - W|V_0) = 1/((1-zeta10)(1-zeta10^-1)) = 1/(2-phi) = 1+phi = phi^2.
ok_a = (MK[0][0] == 0)
# det(I - W|V_0) computed DIRECTLY from the exact matrix (attempt 1 used a mistyped
# Cayley-Hamilton shortcut, 2 + det - tr, and failed; the failed log is preserved
# byte-faithfully in run_log_attempt1_failed.txt; this is the corrected computation)
ImA = [[csub(mident(2)[i][j], sigA[i][j]) for j in range(2)] for i in range(2)]
detI = det2(ImA)
ok_a2 = (detI == csub(cscal(Fr(2), ONE), PHI))
ok_a3 = (cmul(csub(cscal(Fr(2), ONE), PHI), cadd(ONE, PHI)) == ONE)  # (2-phi)(1+phi) = 1
ok_a4 = (cmul(PHI, PHI) == cadd(ONE, PHI))                            # phi^2 = 1+phi
s_gate("(ii-a) m_0(0) = 0: no unit eigenvalue at grade 0 => the Molien product is well-defined",
       ok_a)
s_gate("(ii-a) grade-0 factor EXACT: det(I - W|V_0) = 2-phi and 1/(2-phi) = 1+phi = phi^2",
       ok_a2 and ok_a3 and ok_a4, "M(0) = phi^2; conjugate M'(0) = 2-phi = (1-phi)^2")
# doublet grade-0 gap: phi^2 - (1-phi)^2 = 2phi - 1 = sqrt5 (exact witness of non-collapse)
ok_gap = (csub(cadd(ONE, PHI), csub(cscal(Fr(2), ONE), PHI)) == SQRT5)
s_gate("(ii-a) doublet non-collapse witness at grade 0: M(0) - M'(0) = sqrt5 != 0", ok_gap)

# (ii-b) support side of the convention: the weight-step grading makes every
# Molien part contribute q^k with k a rational INTEGER; the product's q-support
# is contained in Z_{>=0}. (Statement of side: the Molien product lives on the
# REDUCED/integer-support side of the Yang-Lee convention -- the same side as the
# banked reduced streams; ALL fractional content enters through the sealed
# per-component eta-dressing below.)
ok_b = all(isinstance(k, int) for k in range(KMAX+1))  # grading labels are integers by construction
s_gate("(ii-b) Molien q-support is INTEGER (weight-step grading; the reduced side of the convention)",
       ok_b, "support classes mod 1 of the undressed product: {0}")

# (ii-c) the sealed per-component Yang-Lee eta-dressing (banked, B672):
#   comp1 = q^{nu_1} * eta_reduced^{48/5} * (integer-support series), nu_1 = 0   (f1-type slot)
#   comp2 = q^{nu_2} * eta_reduced^{48/5} * (integer-support series), nu_2 = 1/5 (f2-type slot)
# where eta^{48/5} carries q^{(1/24)(48/5)} = q^{2/5}.
eta_class = Fr(48, 5) * Fr(1, 24)
ok_c1 = (eta_class == Fr(2, 5))
s_gate("(ii-c) eta^{48/5} prefactor carries q^{2/5} exactly (48/5 * 1/24 = 2/5)", ok_c1)
# the per-component intrinsic exponents are READ from the representation:
# sigma(T) = diag(1, zeta5) => T-exponents (0, 1/5) for the (f1, f2) slots.
nu = (Fr(0), Fr(1, 5))
ok_c2 = (sigT[0][0] == ONE and sigT[1][1] == Z(4))
s_gate("(ii-c) per-component intrinsic exponents nu = (0, 1/5) read from sigma(T) = diag(1, zeta5)",
       ok_c2)
# the target classes (sealed, banked B672): comp1 -> 2/5, comp2 -> 3/5; gap must equal
# the block's T-exponent gap 1/5 -- a genuine arithmetic coincidence check.
target_classes = (Fr(2, 5), Fr(3, 5))
ok_c3 = (target_classes[1] - target_classes[0] == nu[1] - nu[0])
s_gate("(ii-c) target class gap 3/5 - 2/5 = 1/5 == the vvmf T-exponent gap (could have failed)",
       ok_c3)
dressed = tuple((eta_class + nvi) % 1 for nvi in nu)
ok_c4 = (set(dressed) == {Fr(2, 5), Fr(3, 5)})
s_gate("(ii-c) REQUIRED LANDING: dressed support classes mod 1 = {2/5, 3/5}", ok_c4,
       "dressed = (2/5 + 0, 2/5 + 1/5) = (2/5, 3/5); each component single-class")
# attainment (nonempty support in each class): leading terms phi^2 * q^{2/5}(1 + O(q)) and
# (2-phi) * q^{3/5}(1 + O(q)) -- both grade-0 constants nonzero (exact, from ii-a).
ok_c5 = (cadd(ONE, PHI) != ZERO and csub(cscal(Fr(2), ONE), PHI) != ZERO)
s_gate("(ii-c) both classes ATTAINED (grade-0 constants phi^2, (1-phi)^2 nonzero)", ok_c5)

# (ii-d) THE COMPONENT-SWAP MAP: on the banked side the doublet's two components
# are exchanged by the Galois conjugation sqrt5 -> -sqrt5 (the Yang-Lee <-> Fibonacci
# convention swap; trace phi <-> 1-phi = -1/phi). The Molien doublet must reproduce it:
# conj must send the distribution to the INDEPENDENTLY-built conjugate-seed
# distribution, the pair must be genuinely two-element, and the swap must be an
# involution compatible with the per-component dressing classes 2/5 <-> 3/5.
ok_d1 = all(MKp[k][(3*t) % 10] == MK[k][t] for k in range(KMAX+1) for t in range(10))
s_gate("(ii-d) conj(distribution) == conjugate-seed distribution via t -> 3t (all k <= 40)", ok_d1)
ok_d1b = all(MKp[k][(7*t) % 10] == MK[k][t] for k in range(KMAX+1) for t in range(10))
s_gate("(ii-d) lift-independence: t -> 7t gives the same multisets (m_k(t) = m_k(-t))", ok_d1b)
ok_d2 = any(MKp[k] != MK[k] for k in range(KMAX+1))
wit = sorted(t for t in range(10) if MK[0][t]) , sorted(t for t in range(10) if MKp[0][t])
s_gate("(ii-d) doublet genuinely TWO-element: conjugate distribution differs", ok_d2,
       "witness k=0: classes %s vs %s; grade-0 values phi^2 vs (1-phi)^2, gap sqrt5" % wit)
ok_d3 = all(MK[k][(9*t) % 10] == MK[k][t] for k in range(KMAX+1) for t in range(10))
s_gate("(ii-d) involution: swap^2 = id (3*3 = 9 = -1 mod 10 and m_k(-t) = m_k(t))", ok_d3)
# compatibility with the dressing: the swap exchanges the trace-phi component and the
# trace-(1-phi) component, i.e. the class-2/5 slot and the class-3/5 slot -- exactly the
# banked comp1 <-> comp2 swap (G <-> H under the (2,5) Galois exchange). The exact
# computed content: the two dressed classes differ by nu-gap 1/5 (ii-c) and the swap is
# the sqrt5 -> -sqrt5 conjugation (ii-d1..d3); assignment orientation is a step-(iii)
# matter (locked) -- NOT decided here; no coefficient is compared.
ok_d4 = ok_c3 and ok_c4 and ok_d1 and ok_d2 and ok_d3
s_gate("(ii-d) swap map compatible with the per-component classes 2/5 <-> 3/5", ok_d4)

step2_pass = all(ok for (_, ok, _) in s_results)
log("")
log("  STEP (ii) VERDICT: %s" % ("PASS -- support lands {2/5, 3/5}; the component-swap map is reproduced"
                                 if step2_pass else "KILLED-AT-(ii)"))

t2 = ["# STEP (ii) -- THE SUPPORT PRE-TEST (first falsifier) -- " +
      ("PASS" if step2_pass else "KILLED-AT-(ii)"),
      "# prereg b4c9a6bb; formed symbolically from the step-(i) data; no coefficient",
      "# expanded beyond the two grade-0 constants; no comparison against any target stream.",
      "",
      "## The object",
      "",
      "Molien series, one per Galois conjugate over Q(sqrt5):",
      "  M(q)  = phi^2 * prod_{k>=1} prod_{t} (1 - zeta10^t q^k)^{-m_k(t)}      [trace-phi seed, zeta10^{+-1}]",
      "  M'(q) = (1-phi)^2 * prod_{k>=1} prod_{t} (1 - zeta10^t q^k)^{-m'_k(t)}  [conjugate seed, zeta10^{+-3}]",
      "with m_k the step-(i) gate distribution and m'_k its Galois conjugate (t -> 3t).",
      "The grade-0 piece contributes the exact CONSTANTS 1/(2-phi) = phi^2 and its",
      "conjugate (1-phi)^2 (no q-dependence; the product is well-defined since m_0(0) = 0).",
      "",
      "## Which side of the convention every object is on",
      "",
      "- The Molien product (weight-step grading) has INTEGER q-support: it lives on the",
      "  REDUCED side of the Yang-Lee convention (the side of the banked reduced integer",
      "  streams).",
      "- The sealed per-component eta-dressing (banked, B672 recognition) maps the reduced",
      "  side to the dressed side: comp_a = q^{nu_a} * eta^{48/5}_reduced * (reduced series),",
      "  nu = (0, 1/5) read from sigma(T) = diag(1, zeta5) (the f1/f2 T-exponents).",
      "- eta^{48/5} carries exactly q^{2/5} (48/5 * 1/24 = 2/5, exact Fraction arithmetic).",
      "",
      "## The tests (all exact; each could have failed)",
      ""]
for (name, ok, detail) in s_results:
    t2.append("- [%s] %s%s" % ("PASS" if ok else "FAIL", name, (" -- " + detail) if detail else ""))
t2 += ["",
       "## Verdict",
       "",
       "REQUIRED: dressed q-support classes mod 1 land in {2/5, 3/5}: " +
       ("MET -- the two dressed components have single-class support 2/5 and 3/5" if step2_pass else "NOT MET"),
       "REQUIRED: the component-swap map reproduced by the Molien doublet: " +
       ("MET -- Galois conjugation sqrt5 -> -sqrt5 exchanges the two conjugate series" if step2_pass else "NOT MET") +
       " (involution; genuinely two-element, grade-0 gap sqrt5; classes 2/5 <-> 3/5 exchange",
       " matching the banked comp1 <-> comp2 = Yang-Lee <-> Fibonacci convention swap,",
       " trace phi <-> 1-phi).",
       "",
       "Teeth (how this could have killed): (alpha) m_0(0) != 0 would make the product",
       "divergent (DESIGN defect); (beta) a T-exponent gap != 1/5 in the block would land",
       "the dressed classes outside {2/5, 3/5}; (gamma) a conj-unstable distribution or a",
       "collapsed doublet (M = M') could not reproduce the two-component swap; (delta) a",
       "fractional-support grading (weight instead of weight-step) would smear the support",
       "over all five classes mod 1. Each was computed, none occurred.",
       "",
       "The orientation (which Galois conjugate is comp1) is NOT fixed here: that is a",
       "step-(iii) coefficient question and step (iii) is LOCKED pending the cc2 gate.",
       "Structural note (no stream loaded): the trace-phi side's grade-0 value is phi^2 --",
       "the same landscape value the banked Galois-partner doublet carries (W32).",
       ""]
(HERE / "step_ii_support.md").write_text("\n".join(t2) + "\n")
log("  artifact written: step_ii_support.md")

(HERE / "run_log.txt").write_text("\n".join(LOG) + "\n")
log("")
log("== CELL SUMMARY ==")
log("  VACUITY GATE: %s" % verdict_vac)
log("  STEP (i): distribution banked, k = 0..%d (gate artifact eigen_distribution.json)" % KMAX)
log("  STEP (ii): %s" % ("PASS" if step2_pass else "KILLED-AT-(ii)"))
log("  STEP (iii): LOCKED (pending the cc2 input-verification gate)")
log("  total gate failures: %d" % len(FAILURES))
(HERE / "run_log.txt").write_text("\n".join(LOG) + "\n")
