"""WHY three is out of reach: h1 at a locus is a COrank, and corank is bounded by how many
dimensions the character variety has to spend.

r6 established the fact (0 genuine loci at h1 = 3 in every cover of m004 to degree 8 plus the
family).  This asks for the reason, and tests it.

  h1(chi) = (g - rank J(chi)) - 1   for chi nontrivial,  J = Fox Jacobian (rels x gens).

So h1 = k is the condition "J drops rank by k below its generic value".  In the space of matrices
the corank->=k locus has codimension k^2.  The characters live on the character torus of H1, whose
dimension is b1 = (number of cusps) for a cusped hyperbolic 3-manifold (half-lives-half-dies).
Naive expectation: h1 = k needs b1 >= k^2, so
      h1 = 1 free (b1 >= 1, always) ;  h1 = 2 wants b1 >= 4 ;  h1 = 3 wants b1 >= 9.
m004 has ONE cusp.  Every one-cusped manifold has b1 = 1, so only h1 = 1 is expected there --
which is exactly the 20904-with-no-exceptions that r6 found.

Two things are checked here:
  (1) m004's own Alexander polynomial: separable, and its roots are not roots of unity.
      That is why h1 = 0 at every finite-order character of m004 itself, and why the loci only
      appear upstairs.
  (2) the cusps -> max h1 table over every cover to degree 8 and the family.
      Falsifiable prediction: no one-cusped manifold in the scan carries h1 >= 2.
"""
import snappy, warnings, itertools, sys
from collections import Counter, defaultdict
warnings.filterwarnings("ignore")

sys.path.insert(0, __file__.rsplit('/', 1)[0])
from r6_h1_three import expsums, fox_row, rank_fp, root_of_unity


def fox_symbolic(word, gens, phi, t):
    """Fox derivatives of `word`, pushed to Z[t,t^-1] via phi(g) = t**phi[g]."""
    import sympy as sp
    P = sp.Integer(1)
    D = {g: sp.Integer(0) for g in gens}
    for ch in word:
        g = ch.lower()
        if ch.islower():
            D[g] = D[g] + P
            P = P * t ** phi[g]
        else:
            P = P * t ** (-phi[g])
            D[g] = D[g] - P
    return [sp.expand(sp.simplify(D[g])) for g in gens]


def alexander_facts():
    """Compute m004's Alexander polynomial from the Fox Jacobian -- no Sage, own arithmetic."""
    print("=" * 78)
    print("(1) m004's own Alexander polynomial, from its own Fox Jacobian")
    print("=" * 78)
    import sympy as sp
    t = sp.symbols('t')
    G = snappy.Manifold('m004').fundamental_group()
    gens, rels = list(G.generators()), list(G.relators())
    print(f"   presentation: <{','.join(gens)} | {', '.join(rels)}>")
    e = expsums(rels[0], gens)
    print(f"   relator exponent sums: {e}")
    # phi: F -> Z = H1 must kill the relator, i.e. sum e[j] * phi[j] = 0.  Two generators,
    # one relator: the kernel is rank 1, and its primitive generator is phi.
    assert len(gens) == 2 and len(rels) == 1
    from math import gcd
    v = (-e[1], e[0])
    g0 = gcd(abs(v[0]), abs(v[1])) or 1
    v = (v[0] // g0, v[1] // g0)
    if sum(v) < 0:
        v = (-v[0], -v[1])
    phi = {gens[0]: v[0], gens[1]: v[1]}
    print(f"   abelianisation phi: {gens[0]} -> t^{v[0]},  {gens[1]} -> t^{v[1]}"
          f"   (checks: relator -> t^{sum(e[j]*v[j] for j in range(2))})")
    d = fox_symbolic(rels[0], gens, phi, t)
    print(f"   Fox derivatives under phi:  d r/d {gens[0]} = {sp.factor(d[0])}")
    print(f"                               d r/d {gens[1]} = {sp.factor(d[1])}")
    # Delta(t) = (d r / d gens[i]) / (phi(gens[1-i]) - 1), up to a unit +- t^k
    def normalise(expr):
        q = sp.cancel(sp.together(expr * t ** 12))
        cs = sp.Poly(sp.numer(q), t).all_coeffs()
        while cs and cs[-1] == 0:
            cs.pop()
        if cs and cs[0] < 0:
            cs = [-c for c in cs]
        return sp.Poly(cs, t)

    # The Alexander matrix here is the 1x2 row of abelianised Fox derivatives; the first
    # elementary ideal is generated by its entries, so Delta = their gcd, up to a unit +- t^k.
    nz = [normalise(x) for x in d if sp.simplify(x) != 0]
    Delta = nz[0]
    for q in nz[1:]:
        Delta = sp.Poly(sp.gcd(Delta.as_expr(), q.as_expr()), t)
    print(f"   generators of the first elementary ideal (units stripped): "
          f"{[q.as_expr() for q in nz]}")
    print(f"   cross-check against the classical figure-eight value t^2 - 3t + 1: "
          f"{sp.simplify(Delta.as_expr() - (t**2 - 3*t + 1)) == 0}")
    print(f"   => Delta(t) = {Delta.as_expr()}       (figure-eight: t^2 - 3t + 1)")
    disc = sp.discriminant(Delta.as_expr(), t)
    roots = sp.nroots(Delta.as_expr())
    print(f"   discriminant = {disc}   -> SEPARABLE (no repeated root): {disc != 0}")
    print(f"   roots = {[sp.nsimplify(r) for r in roots]}")
    print(f"   |roots| = {[round(abs(complex(r)), 6) for r in roots]}")
    onu = any(abs(abs(complex(r)) - 1) < 1e-9 for r in roots)
    print(f"   any root on the unit circle (so possibly a root of unity): {onu}")
    print()
    print("   => no finite-order character of H1(m004) = Z is a root of Delta, so h1(chi) = 0 at")
    print("      every nontrivial finite-order chi ON m004 ITSELF: the loci can only be upstairs.")
    print("   => Delta separable: where a rank drop does happen it is a SIMPLE root, so the drop")
    print("      is 1.  h1 = 1 is not an accident of the levels scanned, it is the multiplicity.")


def profile(G, N, p, cap=400000):
    gens = list(G.generators())
    rels = list(G.relators())
    g = len(gens)
    if not rels or g == 0 or N ** g > cap:
        return None
    R = [expsums(r, gens) for r in rels]
    z = root_of_unity(N, p)
    chars = [tt for tt in itertools.product(range(N), repeat=g)
             if all(sum(R[i][j] * tt[j] for j in range(g)) % N == 0 for i in range(len(R)))]
    h1 = {}
    for tt in chars:
        chi = {gens[j]: pow(z, tt[j], p) for j in range(g)}
        J = [fox_row(r, gens, chi, p) for r in rels]
        h1[tt] = (g - rank_fp(J, p)) - (0 if all(x % N == 0 for x in tt) else 1)
    prof = Counter()
    for tt in chars:
        t2 = tuple((2 * x) % N for x in tt)
        if all(x % N == 0 for x in t2):
            continue                      # chi^2 trivial: not a genuine extension locus
        v = h1.get(t2, 0)
        if v:
            prof[v] += 1
    return prof


def main():
    alexander_facts()
    N, p = 60, 421
    M = snappy.Manifold('m004')

    items = []
    for d in range(2, 9):
        for i, c in enumerate(M.covers(d)):
            items.append((f"m004 cover d={d} #{i}", snappy.Manifold(c)))
    fam = ['m003', 'm202', 'm203', 'm206', 'm207', 'm208', 'm410', 'm412',
           's955', 's956', 's957', 's958', 's959', 's960', 's961',
           't12833', 't12835', 't12839', 'v2873']
    items += [(nm, snappy.Manifold(nm)) for nm in fam]

    print()
    print("=" * 78)
    print("(2) cusps -> max h1 over every cover of m004 to degree 8, plus the family")
    print("=" * 78)
    by_cusps = defaultdict(Counter)
    maxima = defaultdict(int)
    counted = 0
    violations = []
    for nm, Mf in items:
        try:
            ncusps = Mf.num_cusps()
            G = Mf.fundamental_group()
            prof = profile(G, N, p)
        except Exception as e:
            print(f"   {nm:22s} -- {type(e).__name__}")
            continue
        if prof is None:
            continue
        counted += 1
        by_cusps[ncusps].update(prof)
        if prof:
            maxima[ncusps] = max(maxima[ncusps], max(prof))
            if ncusps == 1 and max(prof) >= 2:
                violations.append((nm, dict(prof)))

    print(f"   manifolds profiled: {counted}")
    print()
    print("   cusps (= b1)   genuine-locus h1 distribution                     max h1   naive bound k^2<=b1")
    for k in sorted(by_cusps):
        d = dict(sorted(by_cusps[k].items()))
        naive = max([j for j in range(1, 6) if j * j <= k] or [0])
        print(f"      {k:>2}          {str(d):<48s}  {maxima[k]:>4}        {naive}")

    print()
    print("   ONE-CUSPED manifolds carrying h1 >= 2:", violations if violations else "NONE")
    tot = Counter()
    for k in by_cusps:
        tot.update(by_cusps[k])
    print("   pooled:", dict(sorted(tot.items())))
    print("   genuine loci at h1 = 3:", tot.get(3, 0))
    print()
    print("   READING: on one-cusped manifolds -- the only place the index instrument is defined,")
    print("   and the only place Jorgensen minimality has anything to say -- h1 is 1 and nothing")
    print("   else, over every locus found.  Three generations need 3.  Not one instance, and the")
    print("   bound that forbids it (b1 = 1) is the same fact that makes m004 the minimal object.")


if __name__ == "__main__":
    main()
