"""Referee check of the Summary's 'cleanest witness':
   'Among once-punctured torus bundles built from the same two shears, four are arithmetic at word
    length up to seven, and two of them -- a mirror pair over Q(sqrt-7) -- are chiral.'
A cusped hyperbolic 3-manifold is arithmetic iff its invariant trace field is imaginary quadratic
and its traces are algebraic integers (Maclachlan-Reid); for these bundles the invariant trace field
is the field generated by the tetrahedron shapes."""
import snappy, warnings, itertools, random
warnings.filterwarnings("ignore")
from cypari import pari
pari.set_real_precision(60)
I = pari('I')
random.seed(3)

def words(nmax):
    """words in {L,R} of length <= nmax, up to cyclic rotation, using both letters"""
    seen, out = set(), []
    for n in range(2, nmax + 1):
        for w in itertools.product('LR', repeat=n):
            s = ''.join(w)
            if 'L' not in s or 'R' not in s:
                continue
            rots = min(s[i:] + s[:i] for i in range(n))
            if rots in seen:
                continue
            seen.add(rots); out.append(rots)
    return sorted(set(out), key=lambda s: (len(s), s))

def shape_field(M, maxdeg=12, tol=1e-40):
    sh = list(M.high_precision().tetrahedra_shapes('rect'))
    s = pari(0)
    for w in sh:
        s = s + pari(random.randint(1, 9)) * (pari(str(w.real())) + pari(str(w.imag())) * I)
    for d in range(2, maxdeg + 1):
        try:
            p = s.algdep(d)
        except Exception:
            continue
        if int(p.poldegree()) != d:
            continue
        try:
            if abs(complex(p.subst('x', s))) > tol:
                continue
            if int(p.polisirreducible()) != 1:
                continue
        except Exception:
            continue
        return d, p
    return None, None

def amph(M):
    try:
        return M.symmetry_group().is_amphicheiral()
    except Exception:
        try:
            M.canonize(); return M.symmetry_group().is_amphicheiral()
        except Exception:
            return None

ws = words(7)
print("words in {L,R} of length 2..7, up to rotation, using both letters:", len(ws))
arith = []
for w in ws:
    try:
        M = snappy.Manifold('b++' + w)
    except Exception as e:
        print("  cannot build b++%s: %s" % (w, type(e).__name__)); continue
    if M.solution_type() != 'all tetrahedra positively oriented':
        continue
    d, p = shape_field(M)
    if d == 2:                       # imaginary quadratic invariant trace field -> arithmetic (cusped)
        disc = int(p.nfdisc())
        arith.append((w, float(M.volume()), disc, p, amph(M), M.num_cusps()))
print("\nARITHMETIC bundles (degree-2 invariant trace field) at word length <= 7:", len(arith))
for w, v, disc, p, a, nc in arith:
    print("   b++%-8s vol=%.10f  field disc=%-5d  %-22s  amphichiral=%s  cusps=%d"
          % (w, v, disc, str(p), a, nc))
chiral = [r for r in arith if r[4] is False]
print("\n   of these, CHIRAL:", len(chiral), [r[0] for r in chiral],
      " discriminants:", sorted({r[2] for r in chiral}))
print("   paper: four arithmetic at word length <= 7; two of them, a mirror pair over Q(sqrt-7), are chiral")
print("   (disc of Q(sqrt-7) is -7)")
