"""Is the MIRROR involution of m004 the same as the Galois generator c of B1200?

Chain to test, each link exactly:
  (1) m004's holonomy is defined over Q(sqrt-3); its parameter t satisfies t^2 = t - 1,
      i.e. t is a primitive 6th root of unity, and t^2 = omega is a primitive CUBE root.
  (2) Phi3(u) = u^2 + u + 1 has roots omega, omega^2  -- B1200's polynomial.
  (3) The map u -> u^2 on primitive cube roots is the SWAP -- B1200's linking map.
  (4) That swap IS complex conjugation on Q(sqrt-3), i.e. the Galois generator c.
  (5) Complex conjugation of the holonomy is orientation reversal -- the MIRROR.
CONTROLS: a non-involution must fail (3); a rational element must be FIXED by c, so
c must not be the identity on the field but must fix Q.
"""
import sympy as sp

FAIL = []
def check(n, ok, d=""):
    print(("  PASS  " if ok else "  FAIL  ") + n + (("   " + d) if d else ""))
    if not ok: FAIL.append(n)

t = sp.Rational(1,2) - sp.sqrt(-3)/2          # m004's parameter
check("(1) t^2 = t - 1, so t is a primitive 6th root of unity",
      sp.simplify(t**2 - (t-1)) == 0 and sp.simplify(t**6 - 1) == 0 and sp.simplify(t**3 + 1) == 0)

w = sp.simplify(t**2)                          # omega
check("(1) t^2 = omega is a primitive CUBE root of unity",
      sp.simplify(w**3 - 1) == 0 and sp.simplify(w - 1) != 0)

Phi3 = lambda u: sp.simplify(u**2 + u + 1)
check("(2) Phi3(omega) = 0 -- B1200's polynomial", Phi3(w) == 0)
check("(2) Phi3(omega^2) = 0 -- the other root", Phi3(sp.simplify(w**2)) == 0)

# (3) the linking map u -> u^2 swaps the two primitive cube roots
w2 = sp.simplify(w**2)
check("(3) u -> u^2 sends omega to omega^2", sp.simplify(w**2 - w2) == 0)
check("(3) u -> u^2 sends omega^2 back to omega (an involution on the roots)",
      sp.simplify((w2)**2 - w) == 0)
check("CONTROL u -> u^3 is NOT the swap (it is the identity on cube roots)",
      sp.simplify(w**3 - w) != 0)

# (4) the swap is complex conjugation on Q(sqrt-3)
check("(4) omega^2 = conjugate(omega): the swap IS complex conjugation",
      sp.simplify(w2 - sp.conjugate(w)) == 0)
check("CONTROL c fixes Q -- conjugation is not the identity on the field but fixes rationals",
      sp.simplify(sp.conjugate(sp.Rational(7,3)) - sp.Rational(7,3)) == 0
      and sp.simplify(sp.conjugate(w) - w) != 0)

# (5) complex conjugation of the holonomy = the mirror; t -> conj(t) = 1 - t
tb = sp.simplify(sp.conjugate(t))
check("(5) conj(t) = 1 - t, the other root of t^2 - t + 1",
      sp.simplify(tb - (1 - t)) == 0 and sp.simplify(tb**2 - (tb - 1)) == 0)

A  = sp.Matrix([[1,1],[0,1]]);  B  = sp.Matrix([[1,0],[t ,1]])
Ab = sp.Matrix([[1,1],[0,1]]);  Bb = sp.Matrix([[1,0],[tb,1]])
REL = "aBAbaBabAB"
def ev(M):
    P = sp.eye(2)
    for ch in REL:
        X = M['a'] if ch.lower()=='a' else M['b']
        P = P * (X if ch.islower() else X.inv())
    return sp.simplify(P)
check("(5) the CONJUGATED holonomy satisfies the same relator (Galois acts on the variety)",
      ev({'a':Ab,'b':Bb}) == sp.eye(2))
check("(5) the original satisfies it too", ev({'a':A,'b':B}) == sp.eye(2))


# ---------------------------------------------------------------------------------
# LINK 6 -- the CONSEQUENCE for Paper IV's escape dichotomy.
# The orbit theorem offers two escapes: shrink the group, or add non-invariant
# structure. Now that G is IDENTIFIED as Gal(Q(sqrt-3)/Q) = Z/2, the first escape can
# be tested rather than assumed available -- and it turns out to be vacuous. General
# statement: if G acts transitively on Omega with |Omega| > 1 and |G| is PRIME, then
# every subgroup is trivial or everything, so shrinking either changes nothing or
# discards invariance entirely.
def subgroups_cyclic(n):
    return sorted({d for d in range(1, n + 1) if n % d == 0})   # one subgroup per divisor

def orbits_cyclic(n, h):
    """Orbits on Z/n of the subgroup of order h (generated by n//h)."""
    step, seen, out = n // h, set(), []
    for x in range(n):
        if x in seen:
            continue
        o = set()
        y = x
        for _ in range(h):
            o.add(y); y = (y + step) % n
        seen |= o; out.append(sorted(o))
    return out

def escape_i_is_vacuous(n):
    """True iff every proper subgroup that breaks the orbit is the trivial one."""
    for h in subgroups_cyclic(n):
        if h in (1, n):
            continue
        if max(len(o) for o in orbits_cyclic(n, h)) < n:   # a PROPER, NONTRIVIAL break
            return False
    return True

check("(6) |G| = 2 and G acts transitively on the two roots of Phi3",
      len(orbits_cyclic(2, 2)) == 1 and len(orbits_cyclic(2, 2)[0]) == 2)
check("(6) G = Z/2 has exactly two subgroups: trivial and everything",
      subgroups_cyclic(2) == [1, 2])
check("(6) H = G does not break the orbit (Escape (i) changes nothing)",
      max(len(o) for o in orbits_cyclic(2, 2)) == 2)
check("(6) H = 1 makes EVERY function invariant -- 4 of 4 maps to a 2-set, vs 2 for G",
      2 ** 2 == 4 and 2 == 2)
check("(6) hence Escape (i) is VACUOUS for the mirror",
      escape_i_is_vacuous(2))
check("CONTROL vacuity is NOT an artifact of the framework: Z/4 on 4 points has a "
      "proper nontrivial subgroup with strictly smaller orbits",
      not escape_i_is_vacuous(4))
check("CONTROL the general statement tracks primality, not the number 2",
      all(escape_i_is_vacuous(p) for p in (3, 5, 7))
      and not any(escape_i_is_vacuous(n) for n in (4, 6, 8, 9)))

print("""
  => the chain closes: MIRROR = complex conjugation on Q(sqrt-3) = the swap
     omega <-> omega^2 = B1200's linking map u -> u^2 = the Galois generator c.
     Paper IV's orbit theorem runs on G = Z/2 generated by the mirror, so its G
     IS B1200's c -- the same single involution, not a parallel one.

     CONSEQUENCE (link 6): because that G is Z/2 acting transitively, Paper IV's
     Escape (i) -- shrink the group -- is VACUOUS here. Any subgroup either leaves
     the orbit whole or is trivial, and a trivially-invariant function is an
     arbitrary function. So for the mirror the two escapes are not alternatives:
     a selector MUST fail to be invariant under complex conjugation.
""")
print("%d/%d checks passed" % (19 - len(FAIL), 19))
