"""Is the MIRROR involution of m004 the same as the Galois generator c of B1200?

Chain to test, each link exactly:
  (1) m004's holonomy is defined over Q(sqrt-3); its parameter t satisfies t^2 = t - 1,
      i.e. t is a primitive 6th root of unity, and t^2 = omega is a primitive CUBE root.
  (2) Phi3(u) = u^2 + u + 1 has roots omega, omega^2  -- B1200's polynomial.
  (3) The map u -> u^2 on primitive cube roots is the SWAP -- B1200's linking map.
  (4) That swap IS complex conjugation on Q(sqrt-3), i.e. the Galois generator c.
  (5) Complex conjugation of the holonomy is orientation reversal -- the MIRROR.
CONTROLS: a non-involution must fail (3); a rational element must be FIXED by c, so
c must not be the identity on the field but must fix Q.
"""
import sympy as sp

FAIL = []
def check(n, ok, d=""):
    print(("  PASS  " if ok else "  FAIL  ") + n + (("   " + d) if d else ""))
    if not ok: FAIL.append(n)

t = sp.Rational(1,2) - sp.sqrt(-3)/2          # m004's parameter
check("(1) t^2 = t - 1, so t is a primitive 6th root of unity",
      sp.simplify(t**2 - (t-1)) == 0 and sp.simplify(t**6 - 1) == 0 and sp.simplify(t**3 + 1) == 0)

w = sp.simplify(t**2)                          # omega
check("(1) t^2 = omega is a primitive CUBE root of unity",
      sp.simplify(w**3 - 1) == 0 and sp.simplify(w - 1) != 0)

Phi3 = lambda u: sp.simplify(u**2 + u + 1)
check("(2) Phi3(omega) = 0 -- B1200's polynomial", Phi3(w) == 0)
check("(2) Phi3(omega^2) = 0 -- the other root", Phi3(sp.simplify(w**2)) == 0)

# (3) the linking map u -> u^2 swaps the two primitive cube roots
w2 = sp.simplify(w**2)
check("(3) u -> u^2 sends omega to omega^2", sp.simplify(w**2 - w2) == 0)
check("(3) u -> u^2 sends omega^2 back to omega (an involution on the roots)",
      sp.simplify((w2)**2 - w) == 0)
check("CONTROL u -> u^3 is NOT the swap (it is the identity on cube roots)",
      sp.simplify(w**3 - w) != 0)

# (4) the swap is complex conjugation on Q(sqrt-3)
check("(4) omega^2 = conjugate(omega): the swap IS complex conjugation",
      sp.simplify(w2 - sp.conjugate(w)) == 0)
check("CONTROL c fixes Q -- conjugation is not the identity on the field but fixes rationals",
      sp.simplify(sp.conjugate(sp.Rational(7,3)) - sp.Rational(7,3)) == 0
      and sp.simplify(sp.conjugate(w) - w) != 0)

# (5) complex conjugation of the holonomy = the mirror; t -> conj(t) = 1 - t
tb = sp.simplify(sp.conjugate(t))
check("(5) conj(t) = 1 - t, the other root of t^2 - t + 1",
      sp.simplify(tb - (1 - t)) == 0 and sp.simplify(tb**2 - (tb - 1)) == 0)

A  = sp.Matrix([[1,1],[0,1]]);  B  = sp.Matrix([[1,0],[t ,1]])
Ab = sp.Matrix([[1,1],[0,1]]);  Bb = sp.Matrix([[1,0],[tb,1]])
REL = "aBAbaBabAB"
def ev(M):
    P = sp.eye(2)
    for ch in REL:
        X = M['a'] if ch.lower()=='a' else M['b']
        P = P * (X if ch.islower() else X.inv())
    return sp.simplify(P)
check("(5) the CONJUGATED holonomy satisfies the same relator (Galois acts on the variety)",
      ev({'a':Ab,'b':Bb}) == sp.eye(2))
check("(5) the original satisfies it too", ev({'a':A,'b':B}) == sp.eye(2))

print("""
  => the chain closes: MIRROR = complex conjugation on Q(sqrt-3) = the swap
     omega <-> omega^2 = B1200's linking map u -> u^2 = the Galois generator c.
     Paper IV's orbit theorem runs on G = Z/2 generated by the mirror, so its G
     IS B1200's c -- the same single involution, not a parallel one.
""")
print("%d/%d checks passed" % (12 - len(FAIL), 12))
