#!/usr/bin/env python3
"""B1352 stage A'' -- THE MODULE STRUCTURE OF THE 27 AT THE LOCUS POINTS.  At rho_0 the 27 is reducible, 13 + 9 + 5, with one
cusp-fixed vector per block.  At each banked locus point: the cusp-fixed vectors (kernel of [mu - I; lambda - I]), the
pi_1-submodule each generates (iterate span <- span + A span + B span to stability; its dimension is 27 iff the vector is
cyclic), and the submodule generated by all of them.  A dimension pattern 13/9/5 says the point is on the reducible
(sl2-type) stratum; 27 says the 27 is cyclic there.  The V10 points of B1350 (no cusp-fixed vector) get the same test on
a random vector.  Usage: python3 locus_point_structure.py [points.json ...]"""
import sys, os, json, random
import mpmath as mp
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', '..', 'B1268_cusped_net_chirality_bound', 'verification'))
import cusped_theta_odd_hp as H
from flint import acb_mat, acb, arb
mp.mp.dps = 100
n = 27
paths = sys.argv[1:] or [os.path.join(HERE, "fixed_locus_points.json"),
                         os.path.join(HERE, "..", "..", "B1350_the_v10_direction", "verification", "v10_direction_points.json")]
def load(path):
    d = json.load(open(path))
    for name, v in d.items():
        mats = {int(g): acb_mat([[acb(arb(re), arb(im)) for (re, im) in row] for row in v[g]]) for g in ("1", "2")}
        invs = {g: mats[g].inv() for g in (1, 2)}
        yield name, mats, invs
def numrank(cols, tol=mp.mpf('1e-40')):
    if not cols: return 0
    M = mp.matrix([[c[i] for c in cols] for i in range(n)])
    s = mp.svd_c(M, compute_uv=False)
    top = max(s) if len(s) else mp.mpf(0)
    return sum(1 for x in s if x > tol * top)
def orth(cols, tol=mp.mpf('1e-40')):
    """orthonormal basis of the span (Gram-Schmidt with a relative tolerance)"""
    out = []
    for c in cols:
        v = mp.matrix(c)
        for q in out:
            v = v - q * sum(mp.conj(q[i]) * v[i] for i in range(n))
        nv = mp.norm(v)
        if nv > tol: out.append(v / nv)
    return out
def submodule(Amp, Bmp, gens):
    S = orth(gens)
    while True:
        new = orth(S + [Amp * q for q in S] + [Bmp * q for q in S])
        if len(new) == len(S): return len(S)
        S = new
for path in paths:
    print(f"== {os.path.relpath(path, HERE)}")
    for name, mats, invs in load(path):
        lam = H.ev(mats, invs, H.LONG, n)
        K = H.mp_nullspace(H.mat2mp(H.vstack(mats[1] - H.eye(n), lam - H.eye(n))))
        Amp, Bmp = H.mat2mp(mats[1]), H.mat2mp(mats[2])
        print(f"    {name}: cusp-fixed vectors: {len(K)}")
        dims = []
        for v in K:
            dom = max(range(n), key=lambda i: abs(v[i]))
            d = submodule(Amp, Bmp, [v]); dims.append(d)
            print(f"      fixed vector with dominant coordinate {dom}: generates a submodule of dimension {d}")
        if K:
            print(f"      all cusp-fixed vectors together generate dimension {submodule(Amp, Bmp, list(K))}")
        random.seed(1)
        r = mp.matrix([mp.mpc(random.random(), random.random()) for _ in range(n)])
        print(f"      a random vector generates dimension {submodule(Amp, Bmp, [r])}   (27 = cyclic)")
