#!/usr/bin/env python3
"""B1620 -- POST-SEAL CELL: THE RESIDUALS THAT CONTAIN THE INNER AUTOMORPHISMS (written after the sealed run, to answer the
SM seat's relay section 41, point 2; disclosed in FINDINGS).  Couplings that depend on tau alone are invariant under the
inner automorphisms (conjugation by a and by b fix every tau, B1617, W40), so at every tau the residual group of such a
coupling contains their lifts.  On B1620's whole lattice, under the three mass tensors of post_seal_tensors.py:
 I1  the subgroup K generated by the lifts of the two inner automorphisms (and the sign iota): its order, whether T
     restricted to it is three distinct characters (the parity lines);
 I2  every subgroup H of G containing K: is it viable (three distinct non-zero masses) under each tensor;
 I3  every ordered pair of such viable subgroups: the family dimension of the mixing, and the distinct mixing patterns
     (|V_ij|^2 up to row and column permutations) -- the seat's consequence is that every one is a permutation.
No data is read.  Writes post_seal_inner.json."""
import json, pathlib, itertools, importlib.util
import numpy as np
HERE = pathlib.Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("pt", HERE / "post_seal_tensors.py")
pt = importlib.util.module_from_spec(spec); spec.loader.exec_module(pt)
ps, bw, G = pt.ps, pt.bw, pt.G
spec2 = importlib.util.spec_from_file_location("om", HERE.parents[1] / "B1617_the_weave_at_tau_omega" / "verification" / "weave_at_omega.py")
om = importlib.util.module_from_spec(spec2); spec2.loader.exec_module(om)
cp = om.cp


def index_of(auto):
    R = cp.restrict(om.M_of(auto), cp.TB)
    hits = [i for i, M in enumerate(ps.bw.T) if np.allclose(M, R, atol=1e-9)]
    assert len(hits) == 1, hits
    return hits[0]


def canon(P):
    best = None
    for r in itertools.permutations(range(3)):
        for c in itertools.permutations(range(3)):
            k = tuple(np.round(P[np.ix_(r, c)], 4).ravel())
            if best is None or k < best: best = k
    return best


def main():
    ia, ib, ii = (index_of(x) for x in ({"a": "a", "b": "abA"}, {"a": "baB", "b": "b"}, {"a": "A", "b": "B"}))
    K = bw.closure_of({ia, ib}); Ki = bw.closure_of({ia, ib, ii})
    pcs = ps.pieces(K)
    out = {"I1": {"inner_lift_indices": [ia, ib], "sign_index": ii, "order_K": len(K), "order_K_with_sign": len(Ki),
                  "K_abelian": ps.is_abelian(K), "T_on_K_piece_dims": [q.shape[1] for q in pcs] if pcs else None}}
    subs = [H for H in bw.subgroup_lattice() if K <= H]
    out["I2"] = {"subgroups_containing_K": len(subs), "their_orders": sorted(len(H) for H in subs)}
    for tensor in pt.TENSORS:
        vs = []
        for H in subs:
            b = pt.invariant_basis(H, tensor); ok, _ = pt.viable(b, len(H) * 31 + min(H) + max(H))
            if ok: vs.append((H, b))
        dims = set(); pats = set()
        for (Hu, bu), (Hd, bd) in itertools.product(vs, vs):
            V, npar = pt.pair_V(bu, bd); d = pt.family_dim(V, npar, len(Hu) * 997 + len(Hd)); dims.add(d)
            rng = np.random.default_rng(len(Hu) + 7 * len(Hd))
            for _ in range(2): pats.add(canon(np.abs(V(rng.normal(size=npar))) ** 2))
        out[tensor] = {"viable_containing_K": len(vs), "viable_orders": sorted(len(H) for H, _ in vs),
                       "family_dims": sorted(dims), "distinct_patterns": [list(p) for p in sorted(pats)],
                       "every_pattern_a_permutation": all(sorted(np.round(p, 4)) == [0.0] * 6 + [1.0] * 3 for p in pats)}
    json.dump(out, open(HERE / "post_seal_inner.json", "w"), indent=1, default=str)
    print(json.dumps(out, indent=1, default=str))


if __name__ == "__main__":
    main()
